In [16]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import threading
import json
from dhanhq import dhanhq  as dh
from dhanhq import marketfeed  
import asyncio
import nest_asyncio
import pandas_ta as ta
import time
import concurrent.futures
import threading
import schedule
import logging
from dhanhq import marketfeed
import yfinance as yf
pd.set_option('display.max_columns', None)

In [17]:
from NorenRestApiPy.NorenApi import  NorenApi
from threading import Timer
import pandas as pd
import time
import concurrent.futures
import logging

#enable dbug to see request and responses
logging.basicConfig(level=logging.DEBUG)


class ShoonyaApiPy(NorenApi):
    def __init__(self):
        NorenApi.__init__(self, host='https://api.shoonya.com/NorenWClientTP/', websocket='wss://api.shoonya.com/NorenWSTP/')        
        global api
        api = self
api=ShoonyaApiPy()

In [18]:
user    = "FA194273"
pwd     = "21900@Agr"
factor2 = "583670"
vc      = "FA194273_U"
app_key = "24dec73fd5d525c6a2b1be21cafe213c"
imei    = "abc1234"
shoonya = api.login(userid=user, password=pwd, twoFA=factor2, vendor_code=vc, api_secret=app_key, imei=imei)

DEBUG:NorenRestApiPy.NorenApi:https://api.shoonya.com/NorenWClientTP//QuickAuth
DEBUG:NorenRestApiPy.NorenApi:Req:jData={"source": "API", "apkversion": "1.0.0", "uid": "FA194273", "pwd": "be07d30e0d548d800179e36ba62d0807d42790e2352a9ed0130b06f3e1593787", "factor2": "583670", "vc": "FA194273_U", "appkey": "c31254bcd2d505abefc97d4cf0e953cb7921c2cade9888f144142c93cac58ff3", "imei": "abc1234"}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.shoonya.com:443
DEBUG:urllib3.connectionpool:https://api.shoonya.com:443 "POST /NorenWClientTP//QuickAuth HTTP/1.1" 502 150
DEBUG:NorenRestApiPy.NorenApi:Reply:<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [4]:
shoonya

{'request_time': '21:37:08 28-11-2024',
 'actid': 'FA194273',
 'access_type': ['WEB', 'TT', 'MOB', 'API'],
 'uname': 'ATHARVA  AGARWAL',
 'prarr': [{'prd': 'C',
   's_prdt_ali': 'CNC',
   'exch': ['NSE', 'BSE', 'NIPO', 'BSTAR']},
  {'prd': 'M', 's_prdt_ali': 'NRML', 'exch': ['NFO', 'BFO', 'CDS', 'BCD']},
  {'prd': 'I',
   's_prdt_ali': 'MIS',
   'exch': ['NSE', 'BSE', 'NFO', 'BFO', 'CDS', 'BCD']},
  {'prd': 'H', 's_prdt_ali': 'CO', 'exch': ['NSE', 'NFO', 'CDS', 'BSE']},
  {'prd': 'B', 's_prdt_ali': 'BO', 'exch': ['NSE', 'NFO', 'CDS', 'BSE']}],
 'exch_prd': [{'exch': 'NSE', 'prds': ['C', 'I', 'H', 'B']},
  {'exch': 'NIPO', 'prds': ['C']},
  {'exch': 'BSE', 'prds': ['C', 'I', 'H', 'B']},
  {'exch': 'BSTAR', 'prds': ['C']},
  {'exch': 'NFO', 'prds': ['M', 'I', 'H', 'B']},
  {'exch': 'CDS', 'prds': ['M', 'I', 'H', 'B']},
  {'exch': 'BCD', 'prds': ['M', 'I']},
  {'exch': 'BFO', 'prds': ['M', 'I']}],
 'stat': 'Ok',
 'susertoken': 'd0141df4f87a79feb7c3ced007b6c664613be7d627706fe354c51c4f951f9e8f',
 'susertokenspl': '123a77b19cf1153c9212e0d52aff1842e4c656d82c78dff785bb2c714f1cf348',
 'email': 'Atharvaagr65@gmail.com',
 'uid': 'FA194273',
 'brnchid': 'HO',
 'totp_set': '1',
 'm_num': '9936053873',
 'orarr': ['MKT', 'LMT', 'SL-LMT', 'SL-MKT'],
 'exarr': ['NSE', 'NIPO', 'BSE', 'BSTAR', 'NFO', 'CDS', 'BCD', 'BFO'],
 'values': ['2', '1', '3'],
 'mws': {'2': [{'exch': 'NSE',
    'token': '3045',
    'tsym': 'SBIN-EQ',
    'cname': 'STATE BANK OF INDIA',
    'instname': 'EQ',
    'pp': '2',
    'ls': '1',
    'ti': '0.05'},
   {'exch': 'NSE',
    'token': '4963',
    'tsym': 'ICICIBANK-EQ',
    'cname': 'ICICI BANK LTD.',
    'instname': 'EQ',
    'pp': '2',
    'ls': '1',
    'ti': '0.05'},
   {'exch': 'NSE',
    'token': '5900',
    'tsym': 'AXISBANK-EQ',
    'cname': 'AXIS BANK LIMITED',
    'instname': 'EQ',
    'pp': '2',
    'ls': '1',
    'ti': '0.05'},
   {'exch': 'NSE',
    'token': '1922',
    'tsym': 'KOTAKBANK-EQ',
    'cname': 'KOTAK MAHINDRA BANK LTD',
    'instname': 'EQ',
    'pp': '2',
    'ls': '1',
    'ti': '0.05'},
   {'exch': 'NSE',
    'token': '1333',
    'tsym': 'HDFCBANK-EQ',
    'cname': 'HDFC BANK LTD',
    'instname': 'EQ',
    'pp': '2',
    'ls': '1',
    'ti': '0.05'}],
  '1': [{'exch': 'NSE',
    'token': '27297',
    'tsym': 'RTNINDIA-EQ',
    'cname': 'RATTANINDIA ENT LIMITED',
    'instname': 'EQ',
    'pp': '2',
    'ls': '1',
    'ti': '0.01'},
   {'exch': 'NSE',
    'token': '9552',
    'tsym': 'RVNL-EQ',
    'cname': 'RAIL VIKAS NIGAM LIMITED',
    'instname': 'EQ',
    'pp': '2',
    'ls': '1',
    'ti': '0.05'},
   {'exch': 'NSE',
    'token': '2475',
    'tsym': 'ONGC-EQ',
    'cname': 'OIL AND NATURAL GAS CORP.',
    'instname': 'EQ',
    'pp': '2',
    'ls': '1',
    'ti': '0.05'},
   {'exch': 'NSE',
    'token': '3672',
    'tsym': 'SOLARA-EQ',
    'cname': 'SOLARA ACTIVE PHA SCI LTD',
    'instname': 'EQ',
    'pp': '2',
    'ls': '1',
    'ti': '0.05'},
   {'exch': 'NSE',
    'token': '10576',
    'tsym': 'NIFTYBEES-EQ',
    'cname': 'NIP IND ETF NIFTY BEES',
    'instname': 'EQ',
    'pp': '2',
    'ls': '1',
    'ti': '0.01'},
   {'exch': 'NSE',
    'token': '3787',
    'tsym': 'WIPRO-EQ',
    'cname': 'WIPRO LTD',
    'instname': 'EQ',
    'pp': '2',
    'ls': '1',
    'ti': '0.05'},
   {'exch': 'NSE',
    'token': '1594',
    'tsym': 'INFY-EQ',
    'cname': 'INFOSYS LIMITED',
    'instname': 'EQ',
    'pp': '2',
    'ls': '1',
    'ti': '0.05'},
   {'exch': 'BSE',
    'token': '532822',
    'tsym': 'IDEA',
    'cname': 'VODAFONE IDEA  LIMITED',
    'instname': 'A',
    'pp': '2',
    'ls': '1',
    'ti': '0.01'},
   {'exch': 'BSE',
    'token': '505685',
    'tsym': 'TAPARIA',
    'cname': 'TAPARIA TOOLS LTD.',
    'instname': 'XT',
    'pp': '2',
    'ls': '1',
    'ti': '0.01'},
   {'exch': 'NSE',
    'token': '1333',
    'tsym': 'HDFCBANK-EQ',
    'cname': 'HDFC BANK LTD',
    'instname': 'EQ',
    'pp': '2',
    'ls': '1',
    'ti': '0.05'},
   {'exch': 'BSE',
    'token': '500180',
    'tsym': 'HDFCBANK',
    'cname': 'HDFC BANK LTD.',
    'instname': 'A',
    'pp': '2',
    'ls': '1',
    'ti': '0.05'},
   {'exch': 'NSE',
    'token': '26009',
    'tsym': 'Nifty Bank',
    'cname': 'NIFTY BANK',
    'instname': 'UNDIND',
    'pp': '2',
    'ls': '1',
    'ti': '0.05',
    'nontrd': '1'}],
  '3': []},
 'brkname': 'FINV',
 'dmsg': '',
 'lastaccesstime': '1732810028',
 'lastpwdtime': '1729853971'}

In [5]:
#Dhan login info
client_id='1104809158'
access_token='eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJkaGFuIiwicGFydG5lcklkIjoiIiwiZXhwIjoxNzM0MzM1MzY2LCJ0b2tlbkNvbnN1bWVyVHlwZSI6IlNFTEYiLCJ3ZWJob29rVXJsIjoiIiwiZGhhbkNsaWVudElkIjoiMTEwNDgwOTE1OCJ9.hJqErLAF9CKDCts79TAX1tT9sE2-FnfAUtujMfxyo697XeIGxIeSulHmeAkEY3B8fvwotIbuDVR96ou8UZ-rAA'
logging.basicConfig(level=logging.DEBUG)
atha =dh(client_id=client_id,
         access_token=access_token)

In [6]:
equ=pd.read_csv('https://lapi.kotaksecurities.com/wso2-scripmaster/v1/prod/2024-10-14/transformed/nse_cm.csv') # There is the presence of all the stock available , from kotak neo 
stock=pd.read_csv('/Users/Macbook/Desktop/n500.csv')  # This is the nifty 500 stock download from nse site
nifty500=equ[equ['pSymbolName'].isin(stock['Symbol'])]
nifty500=nifty500[nifty500['pGroup']=='EQ'].reset_index(drop=True)
nifty500.drop(index=45, inplace=True)
nifty500

,pSymbol,pGroup,pExchSeg,pInstType,pSymbolName,pTrdSymbol,pOptionType,pScripRefKey,pISIN,pAssetCode,pSubGroup,pCombinedSymbol,pDesc,pAmcCode,pContractId,dTickSize,lLotSize,lExpiryDate,lMultiplier,lPrecision,dStrikePrice;,pExchange,pInstName,pExpiryDate,pIssueDate,pMaturityDate,pListingDate,pNoDelStartDate,pNoDelEndDate,pBookClsStartDate,pBookClsEndDate,pRecordDate,pCreditRating,pReAdminDate,pExpulsionDate,pLocalUpdateTime,pDeliveryUnits,pPriceUnits,pLastTradingDate,pTenderPeridEndDate,pTenderPeridStartDate,pSellVarMargin,pBuyVarMargin,pInstrumentInfo,pRemarksText,pSegment,pNav,pNavDate,pMfAmt,pSipSecurity,pFaceValue,pTrdUnits,pExerciseStartDate,pExerciseEndDate,pElmMargin,pVarMargin,pTotProposedLimitValue,pScripBasePrice,pSettlementType,pCurrectionTime,iPermittedToTrade,iBoardLotQty,iMaxOrderSize,iLotSize,dOpenInterest,dHighPriceRange,dLowPriceRange,dPriceNum,dGenDen,dGenNum,dPriceQuatation,dIssuerate,dPriceDen,dWarningQty,dIssueCapital,dExposureMargin,dMinRedemptionQty,lFreezeQty
0,6545,EQ,nse_cm,NaN,NYKAA,NYKAA-EQ,NaN,NYKAA,INE388Y01029,NaN,NaN,NaN,FSN E COMMERCE VENTURES,NaN,NaN,1,1,-1,-1,2,-1,NSE,NaN,NaN,1.320970e+09,NaN,1.320970e+09,0.0,0.0,0.000000e+00,0.000000e+00,1.352592e+09,153.60-230.41,0.0,0.0,1.413138e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CASH,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,0.0,20.0,NaN,NaN,T+1,315513000.0,0,1,519998,1,0,23041.0,15360.0,1,1,1,0,0,1,0,2.857140e+09,0,0,519998
1,7,EQ,nse_cm,NaN,AARTIIND,AARTIIND-EQ,NaN,AARTIIND,INE769A01020,NaN,NaN,NaN,AARTI INDUSTRIES LTD,NaN,NaN,5,1,-1,-1,2,-1,NSE,NaN,NaN,4.730400e+08,NaN,4.766688e+08,0.0,0.0,0.000000e+00,0.000000e+00,1.406419e+09,476.30-582.10,0.0,0.0,1.413138e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CASH,NaN,NaN,NaN,NaN,500.0,NaN,NaN,NaN,0.0,20.0,NaN,NaN,T+1,315513000.0,0,1,188871,1,0,58210.0,47630.0,1,1,1,0,0,1,0,3.625170e+08,0,0,188871
2,13404,EQ,nse_cm,NaN,SUNTV,SUNTV-EQ,NaN,SUNTV,INE424H01027,NaN,NaN,NaN,SUN TV NETWORK LIMITED,NaN,NaN,5,1,-1,-1,2,-1,NSE,NaN,NaN,8.303040e+08,NaN,8.303040e+08,0.0,0.0,0.000000e+00,0.000000e+00,1.408579e+09,705.50-862.20,0.0,0.0,1.413138e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CASH,NaN,NaN,NaN,NaN,500.0,NaN,NaN,NaN,0.0,20.0,NaN,NaN,T+1,315513000.0,0,1,127289,1,0,86220.0,70550.0,1,1,1,0,0,1,0,3.940850e+08,0,0,127289
3,13409,EQ,nse_cm,NaN,GPIL,GPIL-EQ,NaN,GPIL,INE177H01039,NaN,NaN,NaN,GODAWARI POW & ISP LTD,NaN,NaN,5,1,-1,-1,2,-1,NSE,NaN,NaN,8.303904e+08,NaN,8.303904e+08,0.0,0.0,0.000000e+00,0.000000e+00,1.412467e+09,152.75-229.05,0.0,0.0,1.413138e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CASH,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,0.0,20.0,NaN,NaN,T+1,315513000.0,0,1,523807,1,0,22905.0,15275.0,1,1,1,0,0,1,0,6.689750e+08,0,0,523807
4,6596,EQ,nse_cm,NaN,SONATSOFTW,SONATSOFTW-EQ,NaN,SONATSOFTW,INE269A01021,NaN,NaN,NaN,SONATA SOFTWARE LTD,NaN,NaN,5,1,-1,-1,2,-1,NSE,NaN,NaN,6.175872e+08,NaN,6.175872e+08,0.0,0.0,1.406506e+09,1.407283e+09,0.000000e+00,486.20-729.20,0.0,0.0,1.413138e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CASH,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,0.0,20.0,NaN,NaN,T+1,315513000.0,0,1,164328,1,0,72920.0,48620.0,1,1,1,0,0,1,0,2.804250e+08,0,0,164328
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,13285,EQ,nse_cm,NaN,M&MFIN,M&MFIN-EQ,NaN,M&MFIN,INE774D01024,NaN,NaN,NaN,M&M FIN. SERVICES LTD,NaN,NaN,5,1,-1,-1,2,-1,NSE,NaN,NaN,8.270208e+08,NaN,8.270208e+08,0.0,0.0,1.405642e+09,1.406160e+09,0.000000e+00,255.65-312.45,0.0,0.0,1.413138e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CASH,NaN,NaN,NaN,NaN,200.0,NaN,NaN,NaN,0.0,20.0,NaN,NaN,T+1,315513000.0,0,1,350890,1,0,31245.0,25565.0,1,1,1,0,0,1,0,1.235530e+09,0,0,350890
492,13305,EQ,nse_cm,NaN,CENTURYPLY,CENTURYPLY-EQ,NaN,CENTURYPLY,INE348B01021,NaN,NaN,NaN,CENTURY PLYBOARDS (I) LTD,NaN,NaN,5,1,-1,-1,2,-1,NSE,NaN,NaN,8.275392e+08,NaN,8.275392e+08,0.0,0.0,1.411171e+09,1.411690e+09,0.000000e+00,723.95-1085.85,0.0,0.0,1.413138e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CASH,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,0.0,20.0,NaN,NaN,T+1,315513000.0,0,1,110419,1,0,108585.0,72395.0,1,1,1,0,0,1,0,2.221730e+08,0,0,110419
493,13310,EQ,nse_cm,NaN,KEI,KEI-EQ,NaN,KEI,INE878B01027,NaN,NaN,NaN,KEI INDUSTRIES LTD.,NaN,NaN,5,1,-1,-1,2,-1,NSE,NaN,NaN,8.275392e+08,NaN,8.275392e+08,0.0,0.0,1.409962e+09,1.410480e+09,0.000000e+00,3660.80-5491.10,0.0,0.0,1.413138e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CASH,NaN,NaN,NaN,NaN,200.0,NaN,NaN,NaN,0.0,20.0,NaN,NaN,T+1,315513000.0,0,1,21838,1,0,549110.0,366080.0,1,1,1,0,0,1,0,9.024140e+07,0,0,21838
494,13332,EQ,nse_cm,NaN,SOLARINDS,SOLARINDS-EQ,NaN,SOLARINDS,INE343H01029,NaN,NaN,NaN,SOLAR INDUSTRIES (I) LTD,NaN,NaN,5,1,-1,-1,2,-1,NSE,NaN,NaN,8.284896e+08,NaN,8.284896e+08,0.0,0.0,1.404605e+09,1.405728e+09,0.000000e+00,9054.80-13582.10,0.0,0.0,1.413138e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CASH,NaN,NaN,NaN,NaN,200.0,NaN,NaN,NaN,0.0,20.0,NaN,NaN,T+1,315513000.0,0,1,8777,1,0,1358210.0,905480.0,1,1,1,0,0,1,0,9.049010e+07,0,0,8777
495,13359,EQ,nse_cm,NaN,KFINTECH,KFINTECH-EQ,NaN,KFINTECH,INE138Y01010,NaN,NaN,NaN,KFIN TECHNOLOGIES LIMITED,NaN,NaN,5,1,-1,-1,2,-1,NSE,NaN,NaN,1.356739e+09,NaN,1.356739e+09,0.0,0.0,0.000000e+00,0.000000e+00,1.408838e+09,835.30-1252.90,0.0,0.0,1.413138e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CASH,NaN,NaN,NaN,NaN,1000.0,NaN,NaN,NaN,0.0,20.0,NaN,NaN,T+1,315513000.0,0,1,95627,1,0,125290.0,83530.0,1,1,1,0,0,1,0,1.713750e+08,0,0,95627

In [7]:
def imi(close,opens,time=14):  
    df=pd.DataFrame()
    df['Gain'] = np.where(close > opens, close - opens, 0)
    df['Loss'] = np.where(close < opens, opens - close, 0)

    # Set the period for IMI (e.g., 14 days)
    period = time

    # Calculate rolling sums of gains and losses
    df['SumGain'] = df['Gain'].rolling(window=period).sum()
    df['SumLoss'] = df['Loss'].rolling(window=period).sum()

    # Calculate IMI
    df['IMI'] = 100 * (df['SumGain'] / (df['SumGain'] + df['SumLoss']))
    return df['IMI']

In [8]:

The given imi function is well-suited for calculating the Intraday Momentum Index (IMI) for 1-minute data, as long as you provide a DataFrame with close and open prices sampled at 1-minute intervals. The only change required is a clarification that the time parameter corresponds to the number of intervals (in this case, minutes), rather than days.

Updated Function for 1-Minute Data
python
Copy code
import pandas as pd
import numpy as np

def imi(close, opens, time=14):  
    """
    Calculate the Intraday Momentum Index (IMI) for 1-minute data.

    Parameters:
        close (pd.Series): Series of close prices.
        opens (pd.Series): Series of open prices.
        time (int): The period for the rolling calculation (default is 14 intervals).

    Returns:
        pd.Series: The IMI values.
    """
    df = pd.DataFrame()
    df['Gain'] = np.where(close > opens, close - opens, 0)
    df['Loss'] = np.where(close < opens, opens - close, 0)

    # Calculate rolling sums of gains and losses
    df['SumGain'] = df['Gain'].rolling(window=time).sum()
    df['SumLoss'] = df['Loss'].rolling(window=time).sum()

    # Calculate IMI
    df['IMI'] = 100 * (df['SumGain'] / (df['SumGain'] + df['SumLoss']))
    return df['IMI']  # Returning only the IMI column

SyntaxError: invalid syntax (3286977597.py, line 1)

In [9]:
perm_file=pd.DataFrame()
temp_file=pd.DataFrame()
tim1_data=pd.DataFrame()
def cha(data,symbol_number, symbol_name):
    global temp_file,tim1_data ,perm_file
    tryd=pd.DataFrame(data['data'])
    tryd['start_Time'] = tryd['start_Time'].apply(atha.convert_to_date_time)
    tryd=tryd.set_index('start_Time')
    perm_file=pd.concat([perm_file,tryd])

In [10]:
perm_file=pd.DataFrame()
temp_file=pd.DataFrame()
tim1_data=pd.DataFrame()
def cha(data,symbol_number, symbol_name):
    global temp_file,tim1_data ,perm_file
    tryd=pd.DataFrame(data['data'])
    tryd['start_Time'] = tryd['start_Time'].apply(atha.convert_to_date_time)
    tryd=tryd.set_index('start_Time')
    perm_file=pd.concat([perm_file,tryd])
    tim1_data=min1(tryd,symbol_number, symbol_name)
    last_line,temp_file=min5(tryd,symbol_number, symbol_name)
    return(last_line)


def men(data):
    data['diff']=data['high']-data['low']
    data['per']=(data['diff']/data['low'])*100
    data['type']=np.where(data['open']<data['close'],"up", "down") # to know wheather the stock rised (up) or fall(down)
    data['rsi14']=ta.rsi(data['close'],lenght=14) #RSI with length of 14 
    data['obv']=ta.obv(close=data['close'],volume=data['volume'])
    data['ema20']=ta.ema(close=data['close'],length=20)
    data[["bbl","bbm","bbu","bbb","bbp"]]=(ta.bbands(close=data['low'],mamode='ema',length=5))
    data['adx']=ta.adx(close=data['close'],high=data['open'],low=data['low'],length=14)['ADX_14']
    data['psl']=ta.psl(close=data['close'])
    data['doji'] = data.ta.cdl_pattern(name="doji")
    data['zscore']=ta.zscore(close=data['close'])
    data[['hmid','hupper','hlower']]=ta.hwc(close=data['close'])
    data['imi']=imi(close=data['close'],opens=data['open'])
    return data

In [11]:
def min5(data,symbol_number, symbol_name):
    global temp_file
    mi5=data.resample('5T').agg({"open":"first",
                             "high":"max",
                             "low":'min',
                             "close":'last',
                             "volume":'sum'})
    dat=men(mi5)
    last_line=dat.tail(1)
    last_line['symbol_number'] = symbol_number
    last_line['symbol_name'] = symbol_name
    temp_file=pd.concat([temp_file,last_line])
    return (last_line,temp_file)

def min2(data,symbol_number, symbol_name):
    global temp_file
    mi5=data.resample('2T').agg({"open":"first",
                             "high":"max",
                             "low":'min',
                             "close":'last',
                             "volume":'sum'})
    dat=men(mi5)
    last_line=dat.tail(1)
    last_line['symbol_number'] = symbol_number
    last_line['symbol_name'] = symbol_name
    temp_file=pd.concat([temp_file,last_line])
    return (last_line,temp_file)

def min3(data,symbol_number, symbol_name):
    global temp_file
    mi5=data.resample('3T').agg({"open":"first",
                             "high":"max",
                             "low":'min',
                             "close":'last',
                             "volume":'sum'})
    dat=men(mi5)
    last_line=dat.tail(1)
    last_line['symbol_number'] = symbol_number
    last_line['symbol_name'] = symbol_name
    temp_file=pd.concat([temp_file,last_line])
    return (last_line,temp_file)

def min4(data,symbol_number, symbol_name):
    global temp_file
    mi5=data.resample('4T').agg({"open":"first",
                             "high":"max",
                             "low":'min',
                             "close":'last',
                             "volume":'sum'})
    dat=men(mi5)
    last_line=dat.tail(1)
    last_line['symbol_number'] = symbol_number
    last_line['symbol_name'] = symbol_name
    temp_file=pd.concat([temp_file,last_line])
    return (last_line,temp_file)

def min10(data,symbol_number, symbol_name):
    global temp_file
    mi5=data.resample('10T').agg({"open":"first",
                             "high":"max",
                             "low":'min',
                             "close":'last',
                             "volume":'sum'})
    dat=men(mi5)
    last_line=dat.tail(1)
    last_line['symbol_number'] = symbol_number
    last_line['symbol_name'] = symbol_name
    temp_file=pd.concat([temp_file,last_line])
    return (last_line,temp_file)

def min1(data,symbol_number, symbol_name):
    global tim1_data
    dat=men(data)
    time1_last_line=dat.tail(1)
    time1_last_line['symbol_number'] = symbol_number
    time1_last_line['symbol_name'] = symbol_name
    tim1_data=pd.concat([tim1_data,time1_last_line])
    return (tim1_data)

In [12]:
def work(i,data):
    row=data.iloc[i]
    close=row['close']
    bal=atha.get_fund_limits()
    print(bal)
    balance=(bal['data']['availabelBalance'])
    prob_quantity=int((balance*4.5)/close)
    print(row)
    #stop_loss=(close*(1-0.0020))
    #target=round(close*(1+0.005))
    #print(stop_loss)
    status=atha.place_order(security_id= str(row['symbol_number']),           
                exchange_segment=atha.NSE,
                transaction_type=atha.BUY,
                quantity=prob_quantity,
                order_type=atha.MARKET,
                product_type='INTRADAY',
                #bo_profit_value=target,
                #bo_stop_loss_Value=stop_loss,
                #trigger_price = stop_loss,
                price=0)
    print(status)

In [13]:
def sh_work(i,data):
    row=data.iloc[i]
    close=row['close']
    bal=api.get_limits()
    print(bal['cash'])
    balance=float(bal['cash'])
    prob_quantity=int((balance*4)/close)
    print(balance , prob_quantity)
    print(row)
    #stop_loss=(close*(1-0.0020))
    #target=round(close*(1+0.005))
    #print(stop_loss)
    status=api.place_order( buy_or_sell='B',
                            product_type='I',
                            exchange="NSE",
                            tradingsymbol=str(row['symbol_name']),
                            quantity=prob_quantity,
                            discloseqty=0,
                            price_type='MKT',
                            price=0.0,
                            trigger_price=0,
                            retention='DAY',
                            amo='NO',
                            remarks=None,
                            bookloss_price=0.0,
                            bookprofit_price=0.0,
                            trail_price=0.0)
    print(status)

In [14]:
bal=api.get_limits()

(bal)

DEBUG:NorenRestApiPy.NorenApi:https://api.shoonya.com/NorenWClientTP//Limits
DEBUG:NorenRestApiPy.NorenApi:jData={"uid": "FA194273", "actid": "FA194273"}&jKey=d0141df4f87a79feb7c3ced007b6c664613be7d627706fe354c51c4f951f9e8f
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.shoonya.com:443
DEBUG:urllib3.connectionpool:https://api.shoonya.com:443 "POST /NorenWClientTP//Limits HTTP/1.1" 200 562
DEBUG:NorenRestApiPy.NorenApi:{"request_time":"21:37:20 28-11-2024","stat":"Ok","prfname":"SHOONYA","cash":"10321.70","payin":"0.00","payout":"0.00","brkcollamt":"0.00","unclearedcash":"0.00","aux_daycash":"0.00","aux_brkcollamt":"0.00","aux_unclearedcash":"0.00","daycash":"0.00","turnoverlmt":"999999999999.00","pendordvallmt":"999999999999.00","remarks_amt":"0.00","turnover":"881528.75","marginused":"725.91","peak_mar":"8250.64","mtomcurper":"6.26","margincurper":"7.03","rpnl":"646.35","brokerage":"79.56","rzpnl_e_i":"646.35","brkage_e_i":"79.56","blk_amt":"0.00","mr_der_a":"6812.32"}

{'request_time': '21:37:20 28-11-2024',
 'stat': 'Ok',
 'prfname': 'SHOONYA',
 'cash': '10321.70',
 'payin': '0.00',
 'payout': '0.00',
 'brkcollamt': '0.00',
 'unclearedcash': '0.00',
 'aux_daycash': '0.00',
 'aux_brkcollamt': '0.00',
 'aux_unclearedcash': '0.00',
 'daycash': '0.00',
 'turnoverlmt': '999999999999.00',
 'pendordvallmt': '999999999999.00',
 'remarks_amt': '0.00',
 'turnover': '881528.75',
 'marginused': '725.91',
 'peak_mar': '8250.64',
 'mtomcurper': '6.26',
 'margincurper': '7.03',
 'rpnl': '646.35',
 'brokerage': '79.56',
 'rzpnl_e_i': '646.35',
 'brkage_e_i': '79.56',
 'blk_amt': '0.00',
 'mr_der_a': '6812.32'}

In [69]:
import time
import concurrent.futures

# Define the worker function
def fetch_data(symbol, error_symbols):
    try:
        new = atha.intraday_minute_data(exchange_segment="NSE_EQ",
                                        instrument_type='EQUITY',
                                      security_id=symbol)
        name=nifty500.loc[nifty500['pSymbol'] == symbol, 'pTrdSymbol'].values[0]
        a = cha(new , symbol ,name)
        print(f"Symbol: {symbol}, Processed Data: {a}")
        #time.sleep(0.1)  # Add the delay as per your requirement
    except Exception as e:
        print(f"Error fetching data for {symbol}: {e}")
        if "DataFrame constructor not properly called!" in str(e):
            error_symbols.append(symbol)  # Store symbol for retry

# Use ThreadPoolExecutor to run the tasks in parallel
def run_in_threads():
    
    global temp_file
    temp_file=pd.DataFrame()
    symbols_to_retry = list(nifty500['pSymbol'][250:500])  # Convert to list

    # Repeat until all symbols succeed
    while len(symbols_to_retry) > 0:
        error_symbols = []  # Reset for each attempt

        with concurrent.futures.ThreadPoolExecutor(max_workers=4) as executor:
            futures = [executor.submit(fetch_data, symbol, error_symbols)
                       for symbol in symbols_to_retry]

            # Optionally, wait for all threads to complete
            for future in concurrent.futures.as_completed(futures):
                try:
                    future.result()  # This will raise any exceptions caught in the thread
                except Exception as exc:
                    print(f"Thread raised an exception: {exc}")

        # Update the list with symbols that encountered errors in this run
        symbols_to_retry = error_symbols

        if len(symbols_to_retry) > 0:
            print(f"\nRetrying {len(symbols_to_retry)} symbols with errors...\n")
        else:
            print("\nAll symbols processed successfully without errors.\n")

# Timing the execution
start_time = time.time()  # Start time
run_in_threads()           # Run the function
end_time = time.time()   # End time
decide_file=temp_file
tim1_decide_file=tim1_data
tim1_data=pd.DataFrame()
temp_file=pd.DataFrame()

# Calculate and print the total time taken
total_time = end_time - start_time
print(f"\nTotal time taken: {total_time:.2f} seconds")

DEBUG:urllib3.connectionpool:Resetting dropped connection: api.dhan.co
DEBUG:urllib3.connectionpool:Resetting dropped connection: api.dhan.co
DEBUG:urllib3.connectionpool:Resetting dropped connection: api.dhan.co
DEBUG:urllib3.connectionpool:Resetting dropped connection: api.dhan.co
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 31181, Processed Data:                        open     high     low    close  volume  diff       per
start_Time
2024-11-28 15:10:00  6085.0  6091.15  6082.8  6086.65  1056.0  8.35  0.137272  \

                    type      rsi14      obv        ema20          bbl
start_Time
2024-11-28 15:10:00   up  45.933137  11624.0  6092.759287  6073.136652  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  6082.691002  6092.245352  0.314149  0.505704  15.557712  \

                           psl  doji   zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  58.333333   0.0 -0.39269  6091.218153  6105.261753  \

                          hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  6077.174554  NaN          31181      MCX-EQ
Symbol: 25780, Processed Data:                         open     high     low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  1468.95  1469.75  1466.2  1468.0  7216.0  3.55  0.242122  \

                     type      rsi14      obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  53.119064 -59198.0  1467.179679  1464.629745  \

                             bbm          bbu      bbb       bbp        adx
start_Time
2024-11-28 15:10:00  1466.258241  1467.886737  0.22213  0.482118  14.961971  \

                      psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  50.0   0.0  0.561499  1468.620576  1471.929972  \

                         hlower  imi  symbol_number   symbol_name
start_Time
2024-11-28 15:10:00  1465.31118  NaN          25780  APLAPOLLO-EQ

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 25897, Processed Data:                        open   high    low  close  volume  diff       per type
start_Time
2024-11-28 15:10:00  500.35  501.0  500.2  501.0  1881.0   0.8  0.159936   up  \

                         rsi14      obv      ema20         bbl         bbm
start_Time
2024-11-28 15:10:00  62.198379  25978.0  499.27673  497.922997  499.447464  \

                            bbu       bbb       bbp        adx   psl  doji
start_Time
2024-11-28 15:10:00  500.971931  0.610461  0.746819  16.463193  50.0   0.0  \

                       zscore        hmid      hupper      hlower  imi
start_Time
2024-11-28 15:10:00  1.739473  501.176329  502.194572  500.158087  NaN  \

                     symbol_number   symbol_name
start_Time
2024-11-28 15:10:00          25897  MINDACORP-EQ
Symbol: 31163, Processed Data:                       open   high     low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  516.9  517.0  515.75  515.85  1121.0  1.25  0.242365  \

                     type     rsi14      obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  33.97723 -33188.0  518.062356  514.745953  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  516.611857  518.477762  0.722362  0.269051  12.248426  \

                      psl  doji    zscore       hmid      hupper      hlower
start_Time
2024-11-28 15:10:00  25.0   0.0 -2.556894  517.63548  518.542831  516.728129  \

                     imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  NaN          31163     RHIM-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 31415, Processed Data:                       open   high    low  close   volume  diff       per type
start_Time
2024-11-28 15:10:00  98.48  98.83  98.45  98.75  91078.0  0.38  0.385983   up  \

                         rsi14        obv      ema20        bbl        bbm
start_Time
2024-11-28 15:10:00  47.667744  3740626.0  98.780555  98.156702  98.418206  \

                           bbu       bbb       bbp        adx        psl
start_Time
2024-11-28 15:10:00  98.679709  0.531413  0.560791  19.420058  41.666667  \

                     doji    zscore       hmid     hupper    hlower  imi
start_Time
2024-11-28 15:10:00   0.0 -0.625122  98.415702  98.680044  98.15136  NaN  \

                     symbol_number symbol_name
start_Time
2024-11-28 15:10:00          31415     NBCC-EQ
Symbol: 31234, Processed Data:                       open   high     low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  818.0  818.0  816.35  816.35  1399.0  1.65  0.202119  \

                     type      rsi14     obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  30.185441  1548.0  820.762183  814.241198  \

                            bbm        bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  817.221534  820.20187  0.729383  0.353786  17.582269  \

                      psl  doji    zscore        hmid      hupper      hlower
start_Time
2024-11-28 15:10:00  25.0   0.0 -2.502675  818.022883  819.556112  816.489654  \

                     imi  symbol_number   symbol_name
start_Time
2024-11-28 15:10:00  NaN          31234  SCHNEIDER-EQ
Symbol: 1011, Processed Data:                         open     high     low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  3554.35  3558.15  3550.3  3551.8   368.0  7.85  0.221108  \

                     type      rsi14      obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  37.556131  28942.0  3566.574742  3533.730829  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  3553.832312  3573.933794  1.131257  0.412138  15.059675  \

                           psl  doji    zscore         hmid      hupper
start_Time
2024-11-28 15:10:00  33.333333   0.0 -2.219456  3567.550135  3580.53769  \

                          hlower  imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  3554.562579  NaN           1011  SCHAEFFLER-EQ
Symbol: 1008, Processed Data:                       open   high    low  close  volume  diff       per  type
start_Time
2024-11-28 15:10:00  896.4  898.9  894.5  894.5  6766.0   4.4  0.491895  down  \

                         rsi14     obv      ema20         bbl         bbm
start_Time
2024-11-28 15:10:00  43.066112 -2285.0  896.79582  894.120049  894.836708  \

                            bbu       bbb       bbp        adx        psl
start_Time
2024-11-28 15:10:00  895.553367  0.160176  0.265085  14.655794  41.666667  \

                     doji   zscore        hmid      hupper      hlower  imi
start_Time
2024-11-28 15:10:00   0.0 -1.19673  900.269193  905.188213  895.350173  NaN  \

                     symbol_number symbol_name
start_Time
2024-11-28 15:10:00           1008     FACT-EQ

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name

Symbol: 1023, Processed Data:                        open    high     low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  211.06  211.06  210.95  210.95  79569.0  0.11  0.052145  \

                     type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  45.352997 -381580.0  211.038177  210.830308  \

                            bbm         bbu       bbb       bbp       adx
start_Time
2024-11-28 15:10:00  210.905568  210.980827  0.071368  0.795194  6.649578  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0 -0.813549  210.966893  211.122933  \

                         hlower  imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  210.810853  NaN           1023  FEDERALBNK-EQ
Symbol: 1038, Processed Data:                        open    high     low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  1144.4  1146.0  1144.0  1144.0  1014.0   2.0  0.174825  \

                     type     rsi14     obv       ema20          bbl
start_Time
2024-11-28 15:10:00  down  43.23699 -2570.0  1145.28172  1141.797979  \

                             bbm         bbu       bbb       bbp       adx
start_Time
2024-11-28 15:10:00  1143.557524  1145.31707  0.307732  0.625736  9.262362  \

                      psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  50.0   0.0 -0.982969  1143.924319  1145.603341  \

                          hlower  imi  symbol_number   symbol_name
start_Time
2024-11-28 15:10:00  1142.245297  NaN           1038  FINCABLES-EQ
Symbol: 1041, Processed Data:                       open   high     low  close  volume  diff       per
start_Time
2024-11-28 15:10:00  268.9  268.9  268.25  268.5   633.0  0.65  0.242311  \

                     type      rsi14      obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  39.580118 -28842.0  269.283613  267.283924  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  268.197379  269.110834  0.681181  0.528803  20.404287  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0 -1.423952  268.074629  268.575888  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  267.573369  NaN           1041  FINPIPE-EQ
Symbol: 1076, Processed Data:                       open    high     low  close  volume  diff      per
start_Time
2024-11-28 15:10:00  755.8  756.75  755.25  755.3  2804.0   1.5  0.19861  \

                     type      rsi14     obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  47.048688 -5870.0  755.619083  754.558408  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  755.017101  755.475795  0.121506  0.753872  15.198453  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  33.333333   0.0 -0.280371  755.461745  756.340505  \

                         hlower  imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  754.582984  NaN           1076  ZENSARTECH-EQ

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 1181, Processed Data:                        open    high     low    close  volume  diff       per
start_Time
2024-11-28 15:10:00  5873.0  5877.7  5852.0  5869.15   745.0  25.7  0.439166  \

                     type      rsi14    obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  42.309739  467.0  5881.641115  5846.905694  \

                             bbm          bbu       bbb       bbp       adx
start_Time
2024-11-28 15:10:00  5867.167047  5887.428399  0.690669  0.125715  8.982993  \

                           psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0 -1.665082  5879.107911  5887.067457  \

                          hlower  imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  5871.148366  NaN           1181  GODFRYPHLP-EQ  Symbol: 1153, Processed Data:                         open    high      low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  2417.65  2420.0  2411.65  2413.7  1175.0  8.35  0.346236  \

                     type      rsi14      obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  57.766863  15425.0  2408.326708  2398.325013  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  2408.677481  2419.029949  0.859598  0.643566  17.694747  \

                           psl  doji    zscore        hmid       hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0  1.406863  2410.29202  2415.349532  \

                          hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  2405.234508  NaN           1153    GLAXO-EQ

Symbol: 1185, Processed Data:                         open     high     low   close  volume   diff
start_Time
2024-11-28 15:10:00  6015.05  6018.55  6007.0  6011.6  5431.0  11.55  \

                          per  type      rsi14       obv        ema20
start_Time
2024-11-28 15:10:00  0.192276  down  36.932104 -276752.0  6040.144645  \

                             bbl          bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  5996.315783  6007.488965  6018.662147  0.371975  \

                          bbp        adx        psl  doji    zscore
start_Time
2024-11-28 15:10:00  0.478119  39.336605  33.333333   0.0 -1.153765  \

                            hmid       hupper       hlower  imi
start_Time
2024-11-28 15:10:00  6008.565303  6025.900427  5991.230179  NaN  \

                     symbol_number symbol_name
start_Time
2024-11-28 15:10:00           1185    AMBER-EQ
Symbol: 1174, Processed Data:                        open   high    low  close   volume  diff       per
start_Time
2024-11-28 15:10:00  614.45  616.9  614.0  616.5  36880.0   2.9  0.472313  \

                    type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  72.832901  481030.0  612.500608  612.175505  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  613.223169  614.270833  0.341691  0.870744  26.624809  \

                           psl  doji    zscore       hmid      hupper
start_Time
2024-11-28 15:10:00  58.333333   0.0  1.884867  617.31422  619.633908  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  614.994532  NaN           1174     GNFC-EQ

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 1196, Processed Data:                        open   high    low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  275.25  275.4  274.8  275.15   459.0   0.6  0.218341  \

                     type      rsi14      obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  46.299403 -12487.0  275.398416  274.002679  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  274.729315  275.455951  0.528983  0.548639  15.198749  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  58.333333   0.0 -0.845078  274.539507  275.096142  \

                         hlower  imi  symbol_number   symbol_name
start_Time
2024-11-28 15:10:00  273.982873  NaN           1196  KANSAINER-EQ
Symbol: 1232, Processed Data:                        open     high      low    close   volume  diff
start_Time
2024-11-28 15:10:00  2569.1  2572.15  2567.05  2570.05  11226.0   5.1  \

                          per type      rsi14     obv       ema20
start_Time
2024-11-28 15:10:00  0.198672   up  50.703258  3905.0  2567.11601  \

                             bbl          bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  2552.682981  2561.662959  2570.642937  0.701105  \

                          bbp        adx   psl  doji   zscore        hmid
start_Time
2024-11-28 15:10:00  0.799947  23.789544  50.0   0.0  0.06337  2564.33332  \

                          hupper       hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  2568.829512  2559.837128  NaN           1232   GRASIM-EQ
Symbol: 1186, Processed Data:                        open    high     low   close  volume  diff      per
start_Time
2024-11-28 15:10:00  1724.3  1724.3  1717.0  1718.2   830.0   7.3  0.42516  \

                     type      rsi14      obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  33.210273  50071.0  1726.890692  1716.690269  \

                             bbm          bbu      bbb       bbp        adx
start_Time
2024-11-28 15:10:00  1720.557568  1724.424867  0.44954  0.040045  15.834385  \

                           psl  doji   zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0 -2.20247  1720.546647  1723.436597  \

                          hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  1717.656697  NaN           1186    GLAND-EQ
Symbol: 1247, Processed Data:                       open   high     low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  213.6  214.5  213.55  214.06  46192.0  0.95  0.444861  \

                    type      rsi14        obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  71.476004  1239985.0  212.568615  212.442748  \

                           bbm         bbu      bbb       bbp        adx
start_Time
2024-11-28 15:10:00  213.07866  213.714572  0.59688  0.870602  37.043898  \

                           psl  doji   zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  58.333333   0.0  1.47807  214.978427  216.192231  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  213.764622  NaN           1247     GSFC-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 1270, Processed Data:                       open   high     low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  513.5  514.1  513.25  513.85  66580.0  0.85  0.165611  \

                    type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  43.658662 -118579.0  514.573761  511.678916  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  513.017572  514.356228  0.521875  0.586814  15.678516  \

                      psl  doji    zscore        hmid      hupper    hlower
start_Time
2024-11-28 15:10:00  50.0   0.0 -0.917372  513.249142  514.540384  511.9579  \

                     imi  symbol_number   symbol_name
start_Time
2024-11-28 15:10:00  NaN           1270  AMBUJACEM-EQ
Symbol: 1250, Processed Data:                        open    high     low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  198.66  198.97  198.29  198.45  26378.0  0.68  0.342932  \

                     type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  47.289976  140160.0  198.526696  197.962211  \

                            bbm         bbu      bbb       bbp        adx
start_Time
2024-11-28 15:10:00  198.184346  198.406481  0.22417  0.737814  11.468015  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  33.333333   0.0 -0.213592  198.851129  199.368164  \

                         hlower  imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  198.334094  NaN           1250  CASTROLIND-EQ
Symbol: 1336, Processed Data:                       open   high    low   close  volume  diff       per type
start_Time
2024-11-28 15:10:00  431.9  432.9  431.8  432.45  9959.0   1.1  0.254748   up  \

                         rsi14       obv       ema20         bbl         bbm
start_Time
2024-11-28 15:10:00  58.742115  127666.0  430.777311  428.786012  430.589786  \

                           bbu       bbb       bbp        adx        psl
start_Time
2024-11-28 15:10:00  432.39356  0.837815  0.835467  17.170891  58.333333  \

                     doji    zscore        hmid      hupper     hlower  imi
start_Time
2024-11-28 15:10:00   0.0  2.075381  431.031362  432.198675  429.86405  NaN  \

                     symbol_number symbol_name
start_Time
2024-11-28 15:10:00           1336      HEG-EQ
Symbol: 1333, Processed Data:                         open     high     low    close    volume  diff
start_Time
2024-11-28 15:10:00  1793.95  1794.15  1793.3  1794.15  163254.0  0.85  \

                          per type      rsi14      obv        ema20
start_Time
2024-11-28 15:10:00  0.047399   up  41.072592 -24513.0  1796.199856  \

                             bbl          bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  1790.521646  1792.194248  1793.866851  0.186654  \

                          bbp        adx   psl   doji    zscore         hmid
start_Time
2024-11-28 15:10:00  0.830548  23.568326  75.0  100.0 -0.897413  1790.972761  \

                          hupper       hlower  imi  symbol_number  symbol_name
start_Time
2024-11-28 15:10:00  1796.122662  1785.822861  NaN           1333  HDFCBANK-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name

Symbol: 1363, Processed Data:                        open    high    low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  649.65  649.75  649.3  649.65  37305.0  0.45  0.069305  \

                     type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  36.358655  461320.0  652.018062  647.264385  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  649.031869  650.799353  0.544652  0.575851  22.089736  \

                      psl   doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  25.0  100.0 -1.691163  649.935547  651.925981  \

                         hlower  imi  symbol_number  symbol_name
start_Time
2024-11-28 15:10:00  647.945113  NaN           1363  HINDALCO-EQ
Symbol: 1394, Processed Data:                        open    high      low    close   volume  diff
start_Time
2024-11-28 15:10:00  2460.4  2462.2  2458.55  2461.25  45060.0  3.65  \

                          per type      rsi14      obv        ema20
start_Time
2024-11-28 15:10:00  0.148461   up  38.429954 -25683.0  2467.195273  \

                             bbl          bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  2454.223769  2458.485505  2462.747242  0.346696  \

                          bbp        adx        psl  doji    zscore
start_Time
2024-11-28 15:10:00  0.507567  17.447276  41.666667   0.0 -1.223158  \

                            hmid       hupper       hlower  imi
start_Time
2024-11-28 15:10:00  2457.562984  2464.104452  2451.021517  NaN  \

                     symbol_number    symbol_name
start_Time
2024-11-28 15:10:00           1394  HINDUNILVR-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name

Symbol: 1348, Processed Data:                        open    high      low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  4783.7  4788.0  4780.45  4785.8  6149.0  7.55  0.157935  \

                    type      rsi14       obv        ema20          bbl
start_Time
2024-11-28 15:10:00   up  34.222127 -124161.0  4800.042027  4764.428012  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  4782.664831  4800.901651  0.762622  0.439276  28.661983  \

                           psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  58.333333   0.0 -1.897073  4794.985716  4809.291446  \

                          hlower  imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  4780.679986  NaN           1348  HEROMOTOCO-EQ
Symbol: 1406, Processed Data:                       open    high     low  close   volume  diff       per
start_Time
2024-11-28 15:10:00  380.3  380.75  380.15  380.7  37699.0   0.6  0.157832  \

                    type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  52.862623 -434436.0  380.104063  376.698563  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  379.053982  381.409402  1.242788  0.732659  10.194441  \

                           psl  doji    zscore        hmid     hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0  0.851512  381.066759  382.41316  \

                         hlower  imi  symbol_number   symbol_name
start_Time
2024-11-28 15:10:00  379.720358  NaN           1406  HINDPETRO-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 1442, Processed Data:                        open    high     low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  6190.1  6208.8  6187.9  6187.9    72.0  20.9  0.337756  \

                     type     rsi14     obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  50.83548 -2030.0  6186.837807  6175.344172  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  6183.552363  6191.760554  0.265485  0.764835  31.717489  \

                      psl   doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  25.0  100.0 -0.027441  6180.672139  6191.498879  \

                        hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  6169.8454  NaN           1442   SANOFI-EQ
Symbol: 1424, Processed Data:                        open   high     low  close  volume  diff       per
start_Time
2024-11-28 15:10:00  494.75  495.0  494.15  494.4  5219.0  0.85  0.172013  \

                     type      rsi14      obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  50.415367 -28908.0  494.270415  493.188658  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  493.727545  494.266433  0.218294  0.891969  15.148851  \

                      psl  doji    zscore        hmid      hupper      hlower
start_Time
2024-11-28 15:10:00  25.0   0.0  0.642809  494.816508  495.458467  494.174548  \

                     imi  symbol_number  symbol_name
start_Time
2024-11-28 15:10:00  NaN           1424  HINDZINC-EQ
Symbol: 1476, Processed Data:                      open   high    low  close   volume  diff       per type
start_Time
2024-11-28 15:10:00  82.0  82.08  81.93  82.06  48704.0  0.15  0.183083   up  \

                         rsi14       obv      ema20        bbl      bbm
start_Time
2024-11-28 15:10:00  37.402222  839027.0  82.446885  81.809039  81.9389  \

                           bbu       bbb       bbp        adx        psl
start_Time
2024-11-28 15:10:00  82.068762  0.316971  0.465731  16.413788  41.666667  \

                     doji    zscore       hmid     hupper     hlower  imi
start_Time
2024-11-28 15:10:00   0.0 -1.752524  82.158183  82.498647  81.817719  NaN  \

                     symbol_number symbol_name
start_Time
2024-11-28 15:10:00           1476     IDBI-EQ

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name

Symbol: 1508, Processed Data:                        open    high    low  close   volume  diff       per
start_Time
2024-11-28 15:10:00  486.45  486.45  484.0  485.0  33045.0  2.45  0.506198  \

                     type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  57.653801  383442.0  483.857891  482.902956  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  484.618765  486.334574  0.708107  0.319687  34.086899  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  58.333333   0.0  1.084009  487.352666  488.858769  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  485.846562  NaN           1508  ASTERDM-EQ
Symbol: 1512, Processed Data:                       open    high     low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  778.2  778.75  777.75  778.05  43574.0   1.0  0.128576  \

                     type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  45.521161 -402069.0  778.649584  777.045235  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  777.648559  778.251883  0.155166  0.584068  12.971366  \

                           psl   doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  58.333333  100.0 -0.908648  778.842721  781.826112  \

                        hlower  imi  symbol_number  symbol_name
start_Time
2024-11-28 15:10:00  775.85933  NaN           1512  INDHOTEL-EQ
Symbol: 1494, Processed Data:                       open   high    low  close  volume  diff       per  type
start_Time
2024-11-28 15:10:00  85.55  85.55  85.41  85.52  6349.0  0.14  0.163915  down  \

                         rsi14       obv      ema20        bbl        bbm
start_Time
2024-11-28 15:10:00  55.176482 -126200.0  85.393001  84.978619  85.279657  \

                           bbu       bbb       bbp        adx   psl  doji
start_Time
2024-11-28 15:10:00  85.580696  0.706002  0.716488  14.845885  50.0   0.0  \

                       zscore       hmid     hupper     hlower  imi
start_Time
2024-11-28 15:10:00  1.231509  85.694626  85.925189  85.464063  NaN  \

                     symbol_number symbol_name
start_Time
2024-11-28 15:10:00           1494      RBA-EQ
Symbol: 1515, Processed Data:                       open    high    low  close  volume  diff       per
start_Time
2024-11-28 15:10:00  363.1  363.45  363.0  363.0  4281.0  0.45  0.123967  \

                     type      rsi14      obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  45.154462  86496.0  363.561581  361.426615  \

                            bbm         bbu       bbb       bbp       adx
start_Time
2024-11-28 15:10:00  362.877959  364.329303  0.799908  0.542044  46.26915  \

                      psl  doji    zscore        hmid      hupper      hlower
start_Time
2024-11-28 15:10:00  25.0   0.0 -0.601279  363.689102  364.914358  362.463846  \

                     imi  symbol_number  symbol_name
start_Time
2024-11-28 15:10:00  NaN           1515  INDIACEM-EQ

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 429 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name

Symbol: 1570, Processed Data:                        open     high     low    close  volume  diff       per
start_Time
2024-11-28 15:10:00  1208.8  1208.95  1207.5  1208.75   595.0  1.45  0.120083  \

                     type      rsi14      obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  47.781567 -35365.0  1208.799676  1206.766156  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  1207.685721  1208.605286  0.152285  0.399017  19.098623  \

                      psl   doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  50.0  100.0  0.116856  1208.964942  1212.097035  \

                          hlower  imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  1205.832848  NaN           1570  GMMPFAUDLR-EQ
Error fetching data for 1621: DataFrame constructor not properly called!
Symbol: 1594, Processed Data:                         open    high      low   close    volume  diff
start_Time
2024-11-28 15:10:00  1858.65  1858.7  1856.15  1856.6  108103.0  2.55  \

                          per  type      rsi14        obv        ema20
start_Time
2024-11-28 15:10:00  0.137381  down  38.464907 -1217953.0  1859.537325  \

                             bbl          bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  1855.007523  1856.263549  1857.519574  0.135328  \

                          bbp        adx        psl  doji    zscore
start_Time
2024-11-28 15:10:00  0.454798  16.940559  41.666667   0.0 -1.396366  \

                            hmid       hupper       hlower  imi
start_Time
2024-11-28 15:10:00  1857.092638  1860.371115  1853.814161  NaN  \

                     symbol_number symbol_name
start_Time
2024-11-28 15:10:00           1594     INFY-EQ
Symbol: 1576, Processed Data:                         open    high     low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  9733.85  9743.7  9721.2  9736.9   255.0  22.5  0.231453  \

                    type      rsi14     obv        ema20          bbl
start_Time
2024-11-28 15:10:00   up  47.271412 -5226.0  9739.226303  9710.951724  \

                             bbm          bbu       bbb       bbp       adx
start_Time
2024-11-28 15:10:00  9719.058659  9727.165594  0.166826  0.632068  9.650567  \

                           psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  66.666667   0.0 -0.399283  9712.568001  9734.451411  \

                          hlower  imi  symbol_number  symbol_name
start_Time
2024-11-28 15:10:00  9690.684591  NaN           1576  GILLETTE-EQ

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 1624, Processed Data:                        open    high     low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  137.65  137.76  137.58  137.66  91005.0  0.18  0.130833  \

                    type     rsi14       obv       ema20        bbl
start_Time
2024-11-28 15:10:00   up  40.26088 -822057.0  137.966436  137.11327  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  137.493376  137.873481  0.552907  0.613948  27.830505  \

                           psl   doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  41.666667  100.0 -1.303031  137.639887  137.887432  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  137.392342  NaN           1624      IOC-EQ
Symbol: 1627, Processed Data:                         open     high      low    close  volume  diff
start_Time
2024-11-28 15:10:00  6954.85  6955.75  6944.65  6954.45   354.0  11.1  \

                          per  type      rsi14     obv        ema20
start_Time
2024-11-28 15:10:00  0.159835  down  54.443446 -1191.0  6941.536694  \

                             bbl          bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  6907.082327  6940.347287  6973.612248  0.958596  \

                          bbp        adx        psl   doji    zscore
start_Time
2024-11-28 15:10:00  0.564673  13.835235  58.333333  100.0  1.348626  \

                            hmid      hupper       hlower  imi  symbol_number
start_Time
2024-11-28 15:10:00  6966.628242  6982.83679  6950.419693  NaN           1627  \

                       symbol_name
start_Time
2024-11-28 15:10:00  LINDEINDIA-EQ
Symbol: 1633, Processed Data:                         open    high     low    close  volume  diff       per
start_Time
2024-11-28 15:10:00  1514.75  1514.8  1511.5  1511.65  5248.0   3.3  0.218326  \

                     type      rsi14       obv        ema20         bbl
start_Time
2024-11-28 15:10:00  down  49.239603  110913.0  1511.801814  1508.59859  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  1511.167948  1513.737306  0.340049  0.564618  12.274478  \

                      psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  50.0   0.0  0.324401  1513.607773  1516.496244  \

                          hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  1510.719302  NaN           1633  IPCALAB-EQ
Symbol: 1660, Processed Data:                        open    high     low  close    volume  diff       per
start_Time
2024-11-28 15:10:00  474.75  475.15  474.65  475.1  100347.0   0.5  0.105341  \

                    type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  55.833222 -879509.0  474.219842  472.640365  \

                            bbm         bbu       bbb      bbp        adx
start_Time
2024-11-28 15:10:00  474.030904  475.421444  0.586687  0.72261  10.085969  \

                      psl  doji    zscore        hmid      hupper      hlower
start_Time
2024-11-28 15:10:00  50.0   0.0  1.655327  474.922165  475.843406  474.000923  \

                     imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  NaN           1660      ITC-EQ

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 429 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name

Error fetching data for 1814: DataFrame constructor not properly called!
Symbol: 1675, Processed Data:                       open    high     low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  296.0  296.45  295.16  296.45  50127.0  1.29  0.437051  \

                    type      rsi14        obv      ema20         bbl
start_Time
2024-11-28 15:10:00   up  48.283277  4413910.0  297.13179  293.078745  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  295.320231  297.561716  1.518003  0.464258  18.943528  \

                      psl  doji    zscore        hmid      hupper      hlower
start_Time
2024-11-28 15:10:00  50.0   0.0 -1.068231  296.446777  297.820429  295.073125  \

                     imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  NaN           1675      ITI-EQ
Symbol: 1726, Processed Data:                        open    high     low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  1740.0  1740.0  1731.8  1732.9  1207.0   8.2  0.473496  \

                     type      rsi14       obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  45.198254 -227987.0  1736.196195  1727.034478  \

                             bbm         bbu       bbb       bbp       adx
start_Time
2024-11-28 15:10:00  1732.019014  1737.00355  0.575575  0.478031  16.37917  \

                      psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  50.0   0.0 -0.805063  1724.803621  1734.874724  \

                          hlower  imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  1714.732519  NaN           1726  JBCHEPHARM-EQ

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name

Symbol: 1808, Processed Data:                        open     high      low    close  volume  diff
start_Time
2024-11-28 15:10:00  1210.0  1210.05  1208.65  1209.85   713.0   1.4  \

                          per  type      rsi14      obv       ema20
start_Time
2024-11-28 15:10:00  0.115832  down  53.177884  50335.0  1208.57067  \

                             bbl          bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  1205.660809  1207.735803  1209.810797  0.343617  \

                          bbp       adx   psl   doji    zscore         hmid
start_Time
2024-11-28 15:10:00  0.720289  14.78863  50.0  100.0  1.477606  1210.002101  \

                          hupper       hlower  imi  symbol_number
start_Time
2024-11-28 15:10:00  1211.257096  1208.747106  NaN           1808  \

                       symbol_name
start_Time
2024-11-28 15:10:00  KAJARIACER-EQ
Symbol: 1838, Processed Data:                       open   high     low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  239.0  239.0  238.51  238.76  86991.0  0.49  0.205442  \

                     type      rsi14        obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  60.967613  2201959.0  237.862515  237.565093  \

                           bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  238.15547  238.745846  0.495791  0.800258  47.797825  \

                           psl  doji   zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  66.666667   0.0  1.03989  237.955485  238.786117  \

                         hlower  imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  237.124852  NaN           1838  KARURVYSYA-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name

Symbol: 1922, Processed Data:                        open    high      low    close   volume  diff
start_Time
2024-11-28 15:10:00  1758.5  1759.8  1757.05  1759.45  82801.0  2.75  \

                          per type      rsi14       obv        ema20
start_Time
2024-11-28 15:10:00  0.156512   up  49.586786 -109527.0  1758.922982  \

                             bbl          bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  1754.028795  1756.115515  1758.202235  0.237652  \

                          bbp        adx        psl  doji    zscore
start_Time
2024-11-28 15:10:00  0.723912  16.174652  58.333333   0.0  0.129776  \

                            hmid      hupper       hlower  imi  symbol_number
start_Time
2024-11-28 15:10:00  1759.327942  1762.24652  1756.409363  NaN           1922  \

                      symbol_name
start_Time
2024-11-28 15:10:00  KOTAKBANK-EQ
Symbol: 1901, Processed Data:                         open    high     low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  3482.05  3485.0  3480.8  3484.8  6026.0   4.2  0.120662  \

                    type      rsi14      obv       ema20          bbl
start_Time
2024-11-28 15:10:00   up  68.416235  74202.0  3466.33149  3460.136944  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  3472.907066  3485.677187  0.735414  0.809039  23.546417  \

                      psl  doji    zscore        hmid       hupper
start_Time
2024-11-28 15:10:00  75.0   0.0  2.209258  3490.51134  3496.927939  \

                          hlower  imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  3484.094741  NaN           1901  CUMMINSIND-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 1964, Processed Data:                        open    high     low    close   volume  diff       per
start_Time
2024-11-28 15:10:00  6730.0  6734.6  6720.1  6722.55  12022.0  14.5  0.215771  \

                     type      rsi14      obv        ema20         bbl
start_Time
2024-11-28 15:10:00  down  29.143014 -43892.0  6771.430637  6716.81412  \

                             bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  6727.955395  6739.09667  0.331193  0.147464  26.528005  \

                           psl  doji    zscore         hmid      hupper
start_Time
2024-11-28 15:10:00  33.333333   0.0 -2.206835  6719.128904  6732.36553  \

                          hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  6705.892277  NaN           1964    TRENT-EQ  Symbol: 1949, Processed Data:                       open   high    low   close  volume  diff       per type
start_Time
2024-11-28 15:10:00  838.6  839.4  838.3  838.65   223.0   1.1  0.131218   up  \

                         rsi14      obv       ema20         bbl         bbm
start_Time
2024-11-28 15:10:00  42.674797 -11349.0  840.682134  837.584465  838.599157  \

                            bbu       bbb       bbp        adx        psl
start_Time
2024-11-28 15:10:00  839.613849  0.241997  0.352587  22.905041  41.666667  \

                      doji    zscore        hmid      hupper      hlower  imi
start_Time
2024-11-28 15:10:00  100.0 -1.178293  838.107454  840.193191  836.021717  NaN  \

                     symbol_number symbol_name
start_Time
2024-11-28 15:10:00           1949      KSB-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 27095, Processed Data:                        open    high     low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  615.35  615.55  613.35  613.85  20620.0   2.2  0.358686  \

                     type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  46.429968  755424.0  614.788679  612.624673  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  613.580916  614.537159  0.311692  0.379259  14.042174  \

                      psl  doji    zscore        hmid     hupper      hlower
start_Time
2024-11-28 15:10:00  50.0   0.0 -0.563503  613.507801  615.59443  611.421171  \

                     imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  NaN          27095  SWANENERGY-EQ
Symbol: 1997, Processed Data:                       open   high    low  close   volume  diff       per type
start_Time
2024-11-28 15:10:00  634.9  636.0  634.8  635.3  12571.0   1.2  0.189036   up  \

                       rsi14       obv       ema20        bbl         bbm
start_Time
2024-11-28 15:10:00  58.3033  385182.0  633.803598  631.72427  633.536893  \

                            bbu       bbb      bbp       adx        psl  doji
start_Time
2024-11-28 15:10:00  635.349515  0.572223  0.84842  12.98124  58.333333   0.0  \

                       zscore        hmid      hupper      hlower  imi
start_Time
2024-11-28 15:10:00  1.940571  635.000592  635.955048  634.046137  NaN  \

                     symbol_number   symbol_name
start_Time
2024-11-28 15:10:00           1997  LICHSGFIN-EQ
Symbol: 27297, Processed Data:                       open   high    low  close   volume  diff       per type
start_Time
2024-11-28 15:10:00  65.39  65.45  65.33  65.42  28317.0  0.12  0.183683   up  \

                         rsi14       obv      ema20        bbl        bbm
start_Time
2024-11-28 15:10:00  55.515751  494808.0  65.288115  65.112467  65.240467  \

                           bbu       bbb      bbp        adx   psl  doji
start_Time
2024-11-28 15:10:00  65.368467  0.392394  0.84974  12.755305  50.0   0.0  \

                       zscore       hmid     hupper     hlower  imi
start_Time
2024-11-28 15:10:00  1.269209  65.615593  65.883204  65.347983  NaN  \

                     symbol_number  symbol_name
start_Time
2024-11-28 15:10:00          27297  RTNINDIA-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number

Symbol: 2029, Processed Data:                        open    high    low   close    volume  diff       per
start_Time
2024-11-28 15:10:00  153.08  153.25  153.0  153.15  159179.0  0.25  0.163399  \

                    type      rsi14        obv       ema20        bbl
start_Time
2024-11-28 15:10:00   up  49.395726  6158606.0  153.134953  152.67427  \

                           bbm        bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  152.90833  153.14239  0.306144  0.695825  11.337919  \

                           psl  doji   zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0 -0.06305  153.165648  153.443472  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  152.887824  NaN           2029     IRFC-EQ
Symbol: 2043, Processed Data:                        open    high    low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  974.45  975.65  974.3  975.15  3837.0  1.35  0.138561  \

                    type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  48.214949  105650.0  975.264295  971.166699  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  973.060478  974.954258  0.389242  0.827261  23.215755  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  58.333333   0.0 -0.615114  971.665721  973.121623  \

                         hlower  imi  symbol_number  symbol_name
start_Time
2024-11-28 15:10:00  970.209818  NaN           2043  RAMCOCEM-EQ
Symbol: 2031, Processed Data:                         open    high     low    close   volume  diff
start_Time
2024-11-28 15:10:00  2897.25  2898.0  2895.0  2895.55  87048.0   3.0  \

                          per  type      rsi14       obv        ema20
start_Time
2024-11-28 15:10:00  0.103627  down  31.812252 -136162.0  2911.061962  \

                             bbl          bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  2888.982367  2897.407093  2905.831818  0.581536  \

                          bbp        adx        psl  doji   zscore
start_Time
2024-11-28 15:10:00  0.357141  23.817934  33.333333   0.0 -1.80652  \

                            hmid       hupper      hlower  imi  symbol_number
start_Time
2024-11-28 15:10:00  2898.703333  2911.575586  2885.83108  NaN           2031  \

                    symbol_name
start_Time
2024-11-28 15:10:00      M&M-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name

Symbol: 2048, Processed Data:                        open    high     low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  1433.9  1433.9  1431.0  1432.0   319.0   2.9  0.202655  \

                     type      rsi14      obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  34.309852 -26012.0  1437.260327  1427.611112  \

                             bbm          bbu       bbb       bbp       adx
start_Time
2024-11-28 15:10:00  1432.643567  1437.676022  0.702541  0.336703  21.27395  \

                           psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  33.333333   0.0 -1.377908  1433.933423  1437.331584  \

                          hlower  imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  1430.535262  NaN           2048  INDIGOPNTS-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 429 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name

Symbol: 2049, Processed Data:                       open    high    low  close  volume  diff       per
start_Time
2024-11-28 15:10:00  628.5  628.55  626.7  627.7  4050.0  1.85  0.295197  \

                     type      rsi14       obv    ema20         bbl
start_Time
2024-11-28 15:10:00  down  46.829231  176147.0  628.241  624.463763  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  625.946193  627.428624  0.473661  0.754247  22.142943  \

                      psl  doji    zscore        hmid      hupper      hlower
start_Time
2024-11-28 15:10:00  50.0   0.0 -0.868604  626.266403  627.363379  625.169427  \

                     imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  NaN           2049  CHENNPETRO-EQ
Symbol: 2073, Processed Data:                       open    high    low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  473.1  473.95  472.8  473.15   709.0  1.15  0.243232  \

                    type      rsi14      obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  35.561634 -27255.0  475.277744  471.388143  \

                            bbm        bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  472.920462  474.45278  0.648024  0.460693  20.330946  \

                           psl   doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  33.333333  100.0 -1.789947  472.210677  473.396313  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  471.025042  NaN           2073      VTL-EQ
Symbol: 2056, Processed Data:                         open     high      low   close  volume  diff
start_Time
2024-11-28 15:10:00  1098.05  1098.05  1090.85  1091.0  8289.0   7.2  \

                          per  type     rsi14     obv        ema20
start_Time
2024-11-28 15:10:00  0.660036  down  29.08896 -2287.0  1099.003232  \

                             bbl          bbm          bbu       bbb      bbp
start_Time
2024-11-28 15:10:00  1087.291157  1094.735188  1102.179219  1.359969  0.23904  \

                           adx        psl  doji   zscore         hmid
start_Time
2024-11-28 15:10:00  14.450373  33.333333   0.0 -4.09048  1097.476609  \

                          hupper       hlower  imi  symbol_number
start_Time
2024-11-28 15:10:00  1099.008971  1095.944248  NaN           2056  \

                      symbol_name
start_Time
2024-11-28 15:10:00  HOMEFIRST-EQ
Symbol: 2088, Processed Data:                       open   high    low  close  volume  diff       per  type
start_Time
2024-11-28 15:10:00  642.0  642.5  641.5  641.5   148.0   1.0  0.155885  down  \

                         rsi14     obv      ema20         bbl         bbm
start_Time
2024-11-28 15:10:00  36.149244 -9184.0  643.43862  641.278845  641.588684  \

                            bbu       bbb       bbp      adx        psl  doji
start_Time
2024-11-28 15:10:00  641.898522  0.096585  0.356887  19.4829  41.666667   0.0  \

                       zscore        hmid     hupper      hlower  imi
start_Time
2024-11-28 15:10:00 -1.804594  641.311632  642.07613  640.547135  NaN  \

                     symbol_number    symbol_name
start_Time
2024-11-28 15:10:00           2088  MAHSEAMLES-EQ
Error fetching data for 2181: DataFrame constructor not properly called!

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 429 None

Symbol: 2142, Processed Data:                         open     high      low   close   volume  diff
start_Time
2024-11-28 15:10:00  1145.75  1146.95  1137.55  1141.5  89633.0   9.4  \

                          per  type      rsi14       obv        ema20
start_Time
2024-11-28 15:10:00  0.826337  down  54.747505  149441.0  1128.330691  \

                             bbl         bbm          bbu       bbb       bbp
start_Time
2024-11-28 15:10:00  1116.214344  1130.12644  1144.038535  2.462042  0.766802  \

                           adx        psl  doji    zscore         hmid
start_Time
2024-11-28 15:10:00  33.034009  58.333333   0.0  0.592114  1124.189539  \

                          hupper       hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  1151.287678  1097.091399  NaN           2142     MFSL-EQ
Symbol: 2124, Processed Data:                        open     high     low    close  volume   diff
start_Time
2024-11-28 15:10:00  3170.0  3172.65  3151.0  3167.45  4467.0  21.65  \

                          per  type      rsi14      obv        ema20
start_Time
2024-11-28 15:10:00  0.687083  down  34.373676 -11186.0  3180.220674  \

                            bbl          bbm          bbu       bbb       bbp
start_Time
2024-11-28 15:10:00  3146.95995  3164.638298  3182.316647  1.117243  0.114265  \

                           adx        psl  doji    zscore        hmid
start_Time
2024-11-28 15:10:00  16.936234  33.333333   0.0 -2.185772  3180.28938  \

                          hupper       hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  3189.988586  3170.590174  NaN           2124   MASTEK-EQ
Symbol: 2144, Processed Data:                        open     high     low    close   volume  diff      per
start_Time
2024-11-28 15:10:00  1167.8  1168.45  1167.0  1167.95  16498.0  1.45  0.12425  \

                    type      rsi14       obv       ema20          bbl
start_Time
2024-11-28 15:10:00   up  62.369737  298732.0  1163.96264  1160.101401  \

                            bbm          bbu       bbb      bbp        adx
start_Time
2024-11-28 15:10:00  1163.99478  1167.888159  0.668968  0.88594  20.584205  \

                           psl   doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  58.333333  100.0  1.881128  1165.149723  1168.428202  \

                          hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  1161.871244  NaN           2144      BDL-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name

Error fetching data for 2303: DataFrame constructor not properly called!
Symbol: 2277, Processed Data:                          open      high       low     close  volume   diff
start_Time
2024-11-28 15:10:00  123580.3  123750.0  123580.3  123750.0   190.0  169.7  \

                         per type      rsi14    obv          ema20
start_Time
2024-11-28 15:10:00  0.13732   up  52.926691  214.0  123676.633928  \

                               bbl            bbm           bbu       bbb
start_Time
2024-11-28 15:10:00  123523.925284  123582.031167  123640.13705  0.094036  \

                          bbp        adx        psl  doji    zscore
start_Time
2024-11-28 15:10:00  0.485103  17.811423  41.666667   0.0  0.862024  \

                              hmid        hupper         hlower  imi
start_Time
2024-11-28 15:10:00  123749.515861  123884.97369  123614.058031  NaN  \

                     symbol_number symbol_name
start_Time
2024-11-28 15:10:00           2277      MRF-EQ
Symbol: 2263, Processed Data:                        open    high     low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  171.14  171.41  171.11  171.12  46978.0   0.3  0.175326  \

                     type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  49.789614 -699586.0  171.065723  170.203336  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  170.778474  171.353612  0.673549  0.788214  17.828104  \

                           psl   doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  33.333333  100.0  0.273925  171.168384  171.431205  \

                         hlower  imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  170.905563  NaN           2263  BANDHANBNK-EQ
Symbol: 2283, Processed Data:                        open   high     low  close   volume  diff      per
start_Time
2024-11-28 15:10:00  154.22  154.4  154.18  154.4  17118.0  0.22  0.14269  \

                    type     rsi14      obv       ema20        bbl
start_Time
2024-11-28 15:10:00   up  45.26185 -78406.0  154.537859  153.91941  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  154.223884  154.528357  0.394846  0.427935  10.274585  \

                           psl  doji    zscore        hmid     hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0 -1.037403  154.387474  154.66073  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  154.114217  NaN           2283     MRPL-EQ

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name

Symbol: 2319, Processed Data:                       open    high    low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  303.4  304.25  303.4  304.15  22846.0  0.85  0.280158  \

                    type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  65.264151  484406.0  302.546833  301.719681  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  302.652634  303.585586  0.616517  0.900538  15.659948  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  58.333333   0.0  2.409392  303.767098  304.453136  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  303.081059  NaN           2319      NCC-EQ
Symbol: 2475, Processed Data:                       open    high    low   close    volume  diff       per
start_Time
2024-11-28 15:10:00  251.7  251.85  251.5  251.55  124522.0  0.35  0.139165  \

                     type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  31.680229 -598118.0  252.553149  251.168554  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  251.540576  251.912597  0.295794  0.445466  18.896572  \

                      psl  doji    zscore        hmid      hupper      hlower
start_Time
2024-11-28 15:10:00  25.0   0.0 -1.882302  251.477102  252.102631  250.851573  \

                     imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  NaN           2475     ONGC-EQ
Symbol: 2431, Processed Data:                       open    high    low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  407.4  407.95  407.3  407.45  11791.0  0.65  0.159588  \

                    type      rsi14      obv      ema20         bbl
start_Time
2024-11-28 15:10:00   up  39.060356  68372.0  408.90912  404.242318  \

                            bbm        bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  407.232034  410.22175  1.468311  0.511367  16.655057  \

                      psl   doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  50.0  100.0 -1.839609  407.962273  408.866518  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  407.058027  NaN           2431  RAILTEL-EQ
Symbol: 2412, Processed Data:                         open    high      low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  1179.95  1181.1  1179.45  1180.1  6874.0  1.65  0.139896  \

                    type      rsi14       obv        ema20          bbl
start_Time
2024-11-28 15:10:00   up  45.297451 -234113.0  1181.462988  1175.634016  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  1178.476831  1181.319647  0.482456  0.671163  18.770317  \

                           psl   doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  66.666667  100.0 -0.819631  1178.820026  1183.038012  \

                          hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  1174.602039  NaN           2412      PEL-EQ

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 429 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name

Error fetching data for 2649: DataFrame constructor not properly called!
Symbol: 2489, Processed Data:                       open    high    low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  864.0  865.05  864.0  864.65  4517.0  1.05  0.121528  \

                    type      rsi14      obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  33.170054 -46755.0  870.681628  861.751698  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  866.607375  871.463052  1.120618  0.231513  24.897342  \

                      psl  doji    zscore        hmid      hupper      hlower
start_Time
2024-11-28 15:10:00  50.0   0.0 -1.842964  870.786498  873.816673  867.756323  \

                     imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  NaN           2489     ISEC-EQ
Symbol: 2535, Processed Data:                         open     high       low     close  volume   diff
start_Time
2024-11-28 15:10:00  15910.0  15910.0  15885.05  15907.05    69.0  24.95  \

                          per  type      rsi14     obv         ema20
start_Time
2024-11-28 15:10:00  0.157066  down  54.973652  2892.0  15888.770744  \

                              bbl           bbm           bbu       bbb
start_Time
2024-11-28 15:10:00  15871.698683  15879.147549  15886.596415  0.093819  \

                          bbp        adx   psl  doji    zscore         hmid
start_Time
2024-11-28 15:10:00  0.896198  26.096982  50.0   0.0  1.350131  15889.76759  \

                           hupper        hlower  imi  symbol_number
start_Time
2024-11-28 15:10:00  15907.620772  15871.914409  NaN           2535  \

                    symbol_name
start_Time
2024-11-28 15:10:00     PGHH-EQ
Symbol: 2606, Processed Data:                       open   high     low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  130.2  130.2  130.06  130.07  8108.0  0.14  0.107643  \

                     type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  50.776212  362561.0  130.040589  129.669694  \

                           bbm         bbu      bbb       bbp        adx
start_Time
2024-11-28 15:10:00  129.94187  130.214047  0.41892  0.717009  13.724605  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  33.333333   0.0  0.154761  130.002364  130.302405  \

                         hlower  imi  symbol_number   symbol_name
start_Time
2024-11-28 15:10:00  129.702323  NaN           2606  LEMONTREE-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 429 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 429 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 2664, Processed Data:                        open    high     low    close  volume  diff       per
start_Time
2024-11-28 15:10:00  3042.0  3047.8  3042.0  3044.45  2551.0   5.8  0.190664  \

                    type      rsi14      obv        ema20          bbl
start_Time
2024-11-28 15:10:00   up  66.012152  74497.0  3032.396532  3032.661206  \

                             bbm          bbu      bbb       bbp       adx
start_Time
2024-11-28 15:10:00  3038.147334  3043.633462  0.36115  0.851128  31.48807  \

                           psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  66.666667   0.0  1.495219  3059.319658  3069.133389  \

                          hlower  imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  3049.505927  NaN           2664  PIDILITIND-EQ
Symbol: 2705, Processed Data:                       open   high     low   close  volume  diff      per
start_Time
2024-11-28 15:10:00  795.3  796.1  794.65  795.05  5501.0  1.45  0.18247  \

                     type      rsi14      obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  38.926153  41664.0  798.428188  792.996984  \

                            bbm         bbu      bbb       bbp        adx
start_Time
2024-11-28 15:10:00  795.993382  798.989779  0.75287  0.275834  12.409142  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0 -1.945159  796.511505  798.319178  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  794.703832  NaN           2705  PRAJIND-EQ
Error fetching data for 2783: DataFrame constructor not properly called!
Error fetching data for 2792: DataFrame constructor not properly called!
Symbol: 2739, Processed Data:                        open    high    low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  192.69  192.69  192.3  192.35  16174.0  0.39  0.202808  \

                     type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  33.775138 -628447.0  193.149183  192.079034  \

                            bbm         bbu       bbb      bbp        adx
start_Time
2024-11-28 15:10:00  192.449633  192.820233  0.385139  0.29812  36.122401  \

                      psl  doji    zscore        hmid     hupper      hlower
start_Time
2024-11-28 15:10:00  25.0   0.0 -1.893673  193.410914  194.49567  192.326159  \

                     imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  NaN           2739  PRSMJOHNSN-EQ
Symbol: 2709, Processed Data:                        open     high     low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  1781.5  1782.15  1779.5  1780.0  1402.0  2.65  0.148918  \

                     type      rsi14     obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  54.035499  4094.0  1777.745677  1773.733919  \

                             bbm          bbu       bbb       bbp       adx
start_Time
2024-11-28 15:10:00  1777.576522  1781.419125  0.432342  0.750283  11.29541  \

                           psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  58.333333   0.0  1.109228  1781.796846  1785.145886  \

                          hlower  imi  symbol_number  symbol_name
start_Time
2024-11-28 15:10:00  1778.447806  NaN           2709  MTARTECH-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 429 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name

Symbol: 2829, Processed Data:                       open    high    low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  737.7  738.35  735.1  736.25  1514.0  3.25  0.442117  \

                     type      rsi14      obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  57.380596  11964.0  734.634192  732.176082  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  734.339783  736.503484  0.589291  0.675675  22.376099  \

                      psl  doji    zscore        hmid      hupper      hlower
start_Time
2024-11-28 15:10:00  50.0   0.0  1.175099  735.173063  736.531531  733.814595  \

                     imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  NaN           2829   ANURAS-EQ
Error fetching data for 2866: DataFrame constructor not properly called!
Symbol: 2859, Processed Data:                        open     high     low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  1613.6  1614.05  1612.0  1612.8  1391.0  2.05  0.127171  \

                     type      rsi14      obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  43.846887 -15370.0  1614.588666  1610.256923  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  1611.235902  1612.214881  0.121519  0.890253  20.521632  \

                           psl  doji    zscore         hmid      hupper
start_Time
2024-11-28 15:10:00  58.333333   0.0 -0.586193  1611.391393  1615.20991  \

                          hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  1607.572875  NaN           2859  RAYMOND-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 2854, Processed Data:                        open     high     low   close  volume   diff       per
start_Time
2024-11-28 15:10:00  5061.0  5066.95  5013.0  5013.0  1453.0  53.95  1.076202  \

                     type      rsi14     obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  64.781425  3404.0  4985.760024  4955.884981  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  4987.812148  5019.739315  1.280207  0.894458  11.941503  \

                           psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  58.333333   0.0  2.273516  5000.348709  5012.775279  \

                         hlower  imi  symbol_number   symbol_name
start_Time
2024-11-28 15:10:00  4987.92214  NaN           2854  CRAFTSMAN-EQ  Symbol: 2841, Processed Data:                       open    high    low  close  volume  diff       per
start_Time
2024-11-28 15:10:00  260.9  260.95  260.3  260.8  4756.0  0.65  0.249712  \

                     type      rsi14      obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  46.365407 -42910.0  261.000438  260.185199  \

                            bbm         bbu      bbb       bbp        adx
start_Time
2024-11-28 15:10:00  260.442881  260.700563  0.19788  0.222756  17.182242  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  33.333333   0.0 -0.363199  261.398854  262.101945  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  260.695764  NaN           2841   LXCHEM-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name

Symbol: 2885, Processed Data:                         open    high     low   close    volume  diff
start_Time
2024-11-28 15:10:00  1269.85  1270.4  1269.3  1270.3  200427.0   1.1  \

                          per type      rsi14        obv        ema20
start_Time
2024-11-28 15:10:00  0.086662   up  32.342449 -2961856.0  1275.067052  \

                             bbl          bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  1267.435861  1270.522218  1273.608575  0.485841  \

                          bbp        adx        psl  doji    zscore
start_Time
2024-11-28 15:10:00  0.301997  21.767891  33.333333   0.0 -1.988284  \

                            hmid       hupper       hlower  imi
start_Time
2024-11-28 15:10:00  1271.159204  1272.980674  1269.337735  NaN  \

                     symbol_number  symbol_name
start_Time
2024-11-28 15:10:00           2885  RELIANCE-EQ
Symbol: 2963, Processed Data:                        open   high     low   close    volume  diff      per
start_Time
2024-11-28 15:10:00  115.97  116.1  115.93  116.02  139818.0  0.17  0.14664  \

                    type      rsi14        obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  50.087911 -1067531.0  115.987147  115.698248  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  115.881377  116.064505  0.316062  0.632757  16.322806  \

                           psl  doji    zscore        hmid     hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0  0.258623  116.059673  116.32141  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  115.797936  NaN           2963     SAIL-EQ
Symbol: 3024, Processed Data:                        open   high     low  close  volume  diff       per
start_Time
2024-11-28 15:10:00  311.65  312.1  311.55  312.1  5676.0  0.55  0.176537  \

                    type      rsi14      obv       ema20        bbl
start_Time
2024-11-28 15:10:00   up  55.421253  41632.0  311.808629  311.12326  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  311.475397  311.827533  0.226109  0.605929  16.705254  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  58.333333   0.0  0.724219  312.719556  313.669567  \

                         hlower  imi  symbol_number   symbol_name
start_Time
2024-11-28 15:10:00  311.769545  NaN           3024  JINDALSAW-EQ
Symbol: 2955, Processed Data:                        open    high     low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  706.15  706.45  704.05  704.25  28009.0   2.4  0.340885  \

                     type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  50.200939  715405.0  704.705396  702.168499  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  704.251381  706.334264  0.591517  0.451658  24.362853  \

                      psl  doji   zscore        hmid      hupper      hlower
start_Time
2024-11-28 15:10:00  50.0   0.0  0.17969  707.589625  710.246017  704.933234  \

                     imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  NaN           2955  KALYANKJIL-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 3045, Processed Data:                       open   high    low  close    volume  diff       per
start_Time
2024-11-28 15:10:00  837.1  837.9  836.7  837.8  172091.0   1.2  0.143421  \

                    type      rsi14       obv      ema20         bbl
start_Time
2024-11-28 15:10:00   up  47.647554 -519205.0  838.32105  835.588885  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  837.006771  838.424657  0.338799  0.391821  11.502634  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  33.333333   0.0 -0.344725  838.708084  840.044606  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  837.371562  NaN           3045     SBIN-EQ
Symbol: 3149, Processed Data:                        open   high    low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  442.05  442.4  441.1  442.05  3465.0   1.3  0.294718  \

                     type      rsi14      obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  38.816348 -43629.0  443.452218  440.562434  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  441.729311  442.896187  0.528322  0.230344  14.725721  \

                           psl   doji   zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  33.333333  100.0 -1.96846  442.163616  442.938991  \

                        hlower  imi  symbol_number   symbol_name
start_Time
2024-11-28 15:10:00  441.38824  NaN           3149  BORORENEW-EQ
Symbol: 3063, Processed Data:                        open   high    low  close   volume  diff       per
start_Time
2024-11-28 15:10:00  453.15  453.2  452.7  452.9  61179.0   0.5  0.110448  \

                     type      rsi14        obv       ema20        bbl
start_Time
2024-11-28 15:10:00  down  49.969196  2381437.0  452.982369  450.95131  \

                            bbm         bbu       bbb       bbp       adx
start_Time
2024-11-28 15:10:00  452.246841  453.542372  0.572931  0.674893  11.74556  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0  0.149871  453.322725  454.352433  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  452.293018  NaN           3063     VEDL-EQ
Symbol: 3103, Processed Data:                         open      high      low     close  volume   diff
start_Time
2024-11-28 15:10:00  25497.5  25501.35  25466.3  25466.35   227.0  35.05  \

                          per  type      rsi14     obv         ema20
start_Time
2024-11-28 15:10:00  0.137633  down  45.095763  1382.0  25521.082679  \

                              bbl           bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  25417.029233  25482.367901  25547.70657  0.512815  \

                          bbp        adx   psl  doji    zscore          hmid
start_Time
2024-11-28 15:10:00  0.377041  28.387242  25.0   0.0 -0.318758  25585.368643  \

                           hupper        hlower  imi  symbol_number
start_Time
2024-11-28 15:10:00  25686.531878  25484.205408  NaN           3103  \

                     symbol_name
start_Time
2024-11-28 15:10:00  SHREECEM-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 429 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 429 None

Symbol: 3186, Processed Data:                         open     high     low    close  volume  diff      per
start_Time
2024-11-28 15:10:00  4981.95  4983.75  4979.4  4983.75   126.0  4.35  0.08736  \

                    type      rsi14     obv        ema20          bbl
start_Time
2024-11-28 15:10:00   up  58.118692 -1655.0  4976.304001  4978.514838  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  4978.994838  4979.474838  0.019281  0.922044  30.821512  \

                      psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  50.0   0.0  1.120108  4999.239593  5010.569387  \

                        hlower  imi  symbol_number  symbol_name
start_Time
2024-11-28 15:10:00  4987.9098  NaN           3186  SKFINDIA-EQ  Symbol: 3150, Processed Data:                        open     high      low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  7430.0  7432.95  7421.45  7425.0  6564.0  11.5  0.154956  \

                     type      rsi14       obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  38.984746  122055.0  7448.994248  7401.248586  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  7427.876511  7454.504436  0.716973  0.379328  23.416107  \

                           psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0 -1.001909  7455.929363  7487.106136  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  7424.75259  NaN           3150  SIEMENS-EQ

Symbol: 10099, Processed Data:                        open    high     low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  1253.0  1253.5  1251.1  1251.9  49280.0   2.4  0.191831  \

                     type      rsi14       obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  41.166177 -267264.0  1254.011112  1248.604407  \

                            bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  1251.64388  1254.683354  0.485677  0.410531  23.739961  \

                           psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  66.666667   0.0 -1.265758  1253.756311  1256.657516  \

                          hlower  imi  symbol_number  symbol_name
start_Time
2024-11-28 15:10:00  1250.855106  NaN          10099  GODREJCP-EQ
Symbol: 3220, Processed Data:                        open    high      low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  1274.9  1274.9  1272.45  1274.8  16938.0  2.45  0.192542  \

                     type      rsi14       obv       ema20          bbl
start_Time
2024-11-28 15:10:00  down  28.975238  306642.0  1285.70527  1267.348432  \

                            bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  1274.54971  1281.750987  1.130011  0.354213  24.581154  \

                           psl   doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  33.333333  100.0 -2.134395  1278.422155  1285.581508  \

                          hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  1271.262802  NaN           3220    LODHA-EQ
Error fetching data for 3345: DataFrame constructor not properly called!
Error fetching data for 3351: DataFrame constructor not properly called!

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 429 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name

Error fetching data for 3363: DataFrame constructor not properly called!
Symbol: 3339, Processed Data:                        open    high     low    close  volume  diff      per
start_Time
2024-11-28 15:10:00  4106.2  4106.2  4090.4  4092.45  1589.0  15.8  0.38627  \

                     type     rsi14     obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  37.79682 -4254.0  4102.949844  4061.341441  \

                             bbm          bbu       bbb      bbp        adx
start_Time
2024-11-28 15:10:00  4085.343691  4109.345941  1.175042  0.60533  41.924542  \

                           psl  doji  zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  33.333333   0.0 -1.2406  4093.674463  4099.010094  \

                          hlower  imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  4088.338832  NaN           3339  SUNDARMFIN-EQ
Symbol: 10217, Processed Data:                        open    high     low   close  volume  diff  per  type
start_Time
2024-11-28 15:10:00  726.85  726.85  726.85  726.85  2367.0   0.0  0.0  down  \

                         rsi14        obv       ema20     bbl     bbm     bbu
start_Time
2024-11-28 15:10:00  60.354039  2643827.0  726.830487  726.85  726.85  726.85  \

                              bbb         bbp        adx  psl  doji  zscore
start_Time
2024-11-28 15:10:00  3.054889e-17  58812928.0  17.126182  0.0   0.0     inf  \

                           hmid      hupper      hlower  imi  symbol_number
start_Time
2024-11-28 15:10:00  727.607755  728.574599  726.640911  NaN          10217  \

                       symbol_name
start_Time
2024-11-28 15:10:00  ADANIENSOL-EQ
Symbol: 3273, Processed Data:                         open    high      low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  2261.45  2264.9  2261.25  2264.3  2785.0  3.65  0.161415  \

                    type      rsi14      obv        ema20          bbl
start_Time
2024-11-28 15:10:00   up  48.403098  12154.0  2264.162623  2258.267511  \

                            bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  2259.99262  2261.717728  0.152665  0.864435  17.140945  \

                           psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  58.333333   0.0 -0.348346  2262.275697  2267.582407  \

                          hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  2256.968988  NaN           3273      SRF-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 10243, Processed Data:                       open    high    low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  916.9  918.45  916.9  917.05  4759.0  1.55  0.169048  \

                    type      rsi14      obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  51.305457  46074.0  917.271229  914.484992  \

                           bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  916.62546  918.765927  0.467032  0.564131  23.053464  \

                      psl   doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  50.0  100.0  0.178078  918.752582  921.619899  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  915.885264  NaN          10243  SYNGENE-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 3405, Processed Data:                         open     high      low    close   volume  diff
start_Time
2024-11-28 15:10:00  1100.35  1102.05  1099.55  1101.95  14385.0   2.5  \

                          per type      rsi14      obv        ema20
start_Time
2024-11-28 15:10:00  0.227366   up  49.113614  36346.0  1101.609392  \

                             bbl         bbm          bbu       bbb       bbp
start_Time
2024-11-28 15:10:00  1096.119496  1098.63473  1101.149963  0.457884  0.681945  \

                           adx   psl  doji    zscore         hmid      hupper
start_Time
2024-11-28 15:10:00  21.982374  50.0   0.0 -0.161409  1100.127095  1102.65031  \

                          hlower  imi  symbol_number  symbol_name
start_Time
2024-11-28 15:10:00  1097.603879  NaN           3405  TATACHEM-EQ
Symbol: 3411, Processed Data:                        open    high     low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  6763.2  6763.2  6751.2  6755.0   896.0  12.0  0.177746  \

                     type      rsi14      obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  44.965372  10636.0  6765.174933  6736.498968  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  6755.871897  6775.244827  0.573514  0.379422  20.057805  \

                           psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  33.333333   0.0 -1.063244  6768.960742  6780.131137  \

                          hlower  imi  symbol_number   symbol_name
start_Time
2024-11-28 15:10:00  6757.790347  NaN           3411  TATAELXSI-EQ
Symbol: 3417, Processed Data:                          open      high       low    close  volume   diff
start_Time
2024-11-28 15:10:00  40999.95  40999.95  40886.95  40903.3   120.0  113.0  \

                          per  type      rsi14     obv         ema20
start_Time
2024-11-28 15:10:00  0.276372  down  25.413488 -2123.0  41178.906396  \

                              bbl           bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  40856.024484  40936.922652  41017.82082  0.395233  \

                          bbp        adx   psl  doji    zscore         hmid
start_Time
2024-11-28 15:10:00  0.191139  37.149926  25.0   0.0 -2.233597  40965.86826  \

                           hupper        hlower  imi  symbol_number
start_Time
2024-11-28 15:10:00  41098.063868  40833.672652  NaN           3417  \

                    symbol_name
start_Time
2024-11-28 15:10:00   HONAUT-EQ
Symbol: 3426, Processed Data:                        open    high    low  close    volume  diff       per
start_Time
2024-11-28 15:10:00  412.85  413.35  412.7  413.0  133415.0  0.65  0.157499  \

                    type    rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  42.7934 -523441.0  413.639508  411.794581  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  412.607969  413.421357  0.394267  0.556573  16.137403  \

                           psl  doji   zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  33.333333   0.0 -1.32594  413.132987  413.873403  \

                         hlower  imi  symbol_number   symbol_name
start_Time
2024-11-28 15:10:00  412.392571  NaN           3426  TATAPOWER-EQ

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 3432, Processed Data:                       open   high     low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  940.8  941.2  940.35  940.75  17381.0  0.85  0.090392  \

                     type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  39.210753 -121575.0  943.255996  938.362205  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  939.813549  941.264894  0.308858  0.684812  23.630044  \

                      psl   doji    zscore        hmid      hupper     hlower
start_Time
2024-11-28 15:10:00  25.0  100.0 -1.300661  940.556927  942.925175  938.18868  \

                     imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  NaN           3432  TATACONSUM-EQ
Symbol: 3499, Processed Data:                        open    high     low   close    volume  diff     per
start_Time
2024-11-28 15:10:00  143.45  143.46  143.33  143.38  165632.0  0.13  0.0907  \

                     type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  32.586642 -714478.0  143.864531  142.997514  \

                            bbm         bbu       bbb      bbp        adx
start_Time
2024-11-28 15:10:00  143.412551  143.827588  0.578802  0.40055  19.036229  \

                      psl  doji    zscore        hmid      hupper      hlower
start_Time
2024-11-28 15:10:00  25.0   0.0 -2.317864  143.549563  143.829953  143.269174  \

                     imi  symbol_number   symbol_name
start_Time
2024-11-28 15:10:00  NaN           3499  TATASTEEL-EQ
Symbol: 3456, Processed Data:                        open    high     low   close    volume  diff       per
start_Time
2024-11-28 15:10:00  779.55  779.55  778.45  778.95  164560.0   1.1  0.141306  \

                     type     rsi14        obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  31.50479  1167958.0  782.680435  777.836051  \

                           bbm        bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  778.95926  780.08247  0.288387  0.273301  25.081719  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  33.333333   0.0 -1.895357  779.162061  781.978293  \

                         hlower  imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  776.345828  NaN           3456  TATAMOTORS-EQ
Symbol: 3475, Processed Data:                         open     high      low    close  volume  diff
start_Time
2024-11-28 15:10:00  4573.95  4580.95  4569.85  4580.35  1290.0  11.1  \

                          per type     rsi14     obv        ema20         bbl
start_Time
2024-11-28 15:10:00  0.242896   up  33.05955 -6446.0  4608.614867  4540.18848  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  4584.031564  4627.874648  1.912861  0.338269  18.661242  \

                           psl  doji   zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  33.333333   0.0 -2.57387  4602.736255  4614.155943  \

                          hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  4591.316567  NaN           3475  THERMAX-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name

Symbol: 3506, Processed Data:                         open    high     low    close   volume  diff
start_Time
2024-11-28 15:10:00  3208.25  3209.5  3207.5  3208.05  23912.0   2.0  \

                          per  type      rsi14       obv       ema20
start_Time
2024-11-28 15:10:00  0.062354  down  41.968888 -348041.0  3211.89594  \

                             bbl          bbm         bbu       bbb       bbp
start_Time
2024-11-28 15:10:00  3200.042155  3204.847402  3209.65265  0.299874  0.776011  \

                           adx   psl   doji    zscore         hmid
start_Time
2024-11-28 15:10:00  30.634948  25.0  100.0 -0.912384  3214.562489  \

                          hupper       hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  3226.606501  3202.518478  NaN           3506    TITAN-EQ
Symbol: 3563, Processed Data:                        open    high     low   close  volume  diff  per  type
start_Time
2024-11-28 15:10:00  1087.2  1087.2  1087.2  1087.2  8597.0   0.0  0.0  down  \

                        rsi14        obv        ema20     bbl     bbm     bbu
start_Time
2024-11-28 15:10:00  63.26507  2100806.0  1087.155111  1087.2  1087.2  1087.2  \

                              bbb         bbp        adx  psl  doji  zscore
start_Time
2024-11-28 15:10:00  2.042353e-17  27229184.0  34.915237  0.0   0.0    -inf  \

                            hmid       hupper       hlower  imi
start_Time
2024-11-28 15:10:00  1089.197536  1091.605348  1086.789724  NaN  \

                     symbol_number    symbol_name
start_Time
2024-11-28 15:10:00           3563  ADANIGREEN-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name

Symbol: 10440, Processed Data:                        open     high     low    close  volume  diff       per
start_Time
2024-11-28 15:10:00  1994.6  1997.95  1994.6  1996.05  6351.0  3.35  0.167953  \

                    type      rsi14      obv        ema20          bbl
start_Time
2024-11-28 15:10:00   up  49.349982  71270.0  1996.342853  1990.500788  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  1994.431386  1998.361984  0.394157  0.521449  10.250308  \

                      psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  50.0   0.0  0.101126  1999.847941  2005.079498  \

                          hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  1994.616383  NaN          10440    LUPIN-EQ
Symbol: 3518, Processed Data:                         open     high      low    close   volume  diff
start_Time
2024-11-28 15:10:00  3202.95  3205.85  3202.95  3203.05  11969.0   2.9  \

                          per type      rsi14      obv        ema20
start_Time
2024-11-28 15:10:00  0.090542   up  63.153831  11186.0  3193.930809  \

                             bbl          bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  3181.485234  3195.368663  3209.252092  0.868972  \

                          bbp        adx   psl   doji    zscore         hmid
start_Time
2024-11-28 15:10:00  0.773035  27.588592  75.0  100.0  2.306816  3200.259118  \

                          hupper       hlower  imi  symbol_number
start_Time
2024-11-28 15:10:00  3204.741258  3195.776977  NaN           3518  \

                       symbol_name
start_Time
2024-11-28 15:10:00  TORNTPHARM-EQ
Symbol: 10447, Processed Data:                        open     high     low    close  volume  diff       per
start_Time
2024-11-28 15:10:00  1503.1  1506.15  1502.5  1503.25  4577.0  3.65  0.242928  \

                    type      rsi14      obv        ema20          bbl
start_Time
2024-11-28 15:10:00   up  52.493681  26713.0  1501.919089  1496.114101  \

                             bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  1500.027361  1503.94062  0.521758  0.815931  12.752265  \

                           psl   doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  66.666667  100.0  0.545453  1501.526088  1503.916921  \

                          hlower  imi  symbol_number  symbol_name
start_Time
2024-11-28 15:10:00  1499.135255  NaN          10447  UNITDSPR-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 429 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 3637, Processed Data:                        open    high     low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  1188.7  1189.9  1188.0  1189.3  5794.0   1.9  0.159933  \

                    type     rsi14      obv        ema20          bbl
start_Time
2024-11-28 15:10:00   up  57.76616  96928.0  1184.669973  1182.361033  \

                             bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  1185.775122  1189.18921  0.575841  0.825838  21.876085  \

                      psl  doji  zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  50.0   0.0  1.0813  1183.157507  1190.451683  \

                          hlower  imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  1175.863331  NaN           3637  JUBLPHARMA-EQ
Symbol: 10577, Processed Data:                       open   high    low  close  volume  diff       per type
start_Time
2024-11-28 15:10:00  302.4  302.7  302.0  302.7  4178.0   0.7  0.231788   up  \

                         rsi14     obv      ema20         bbl       bbm
start_Time
2024-11-28 15:10:00  44.736071  5703.0  303.04808  301.074903  301.9769  \

                            bbu       bbb       bbp       adx        psl
start_Time
2024-11-28 15:10:00  302.878898  0.597395  0.512805  9.967646  41.666667  \

                     doji   zscore        hmid    hupper      hlower  imi
start_Time
2024-11-28 15:10:00   0.0 -0.86981  302.055973  302.6986  301.413345  NaN  \

                     symbol_number symbol_name
start_Time
2024-11-28 15:10:00          10577     KRBL-EQ
Error fetching data for 3721: DataFrame constructor not properly called!

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name

Symbol: 3703, Processed Data:                        open    high    low  close  volume  diff   per  type
start_Time
2024-11-28 15:10:00  500.45  500.55  500.0  500.1  1276.0  0.55  0.11  down  \

                         rsi14      obv       ema20         bbl        bbm
start_Time
2024-11-28 15:10:00  50.756153  61403.0  500.216444  499.900269  500.02676  \

                            bbu       bbb       bbp        adx        psl
start_Time
2024-11-28 15:10:00  500.153251  0.050594  0.394223  20.947261  33.333333  \

                     doji    zscore       hmid      hupper      hlower  imi
start_Time
2024-11-28 15:10:00   0.0 -0.157137  500.76139  501.959398  499.563382  NaN  \

                     symbol_number symbol_name
start_Time
2024-11-28 15:10:00           3703   VIPIND-EQ
Symbol: 10599, Processed Data:                        open   high    low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  472.35  472.6  471.4  471.65  9361.0   1.2  0.254561  \

                     type      rsi14      obv       ema20        bbl
start_Time
2024-11-28 15:10:00  down  41.478415  17569.0  472.596378  470.47929  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  471.640324  472.801358  0.492339  0.396504  19.229721  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  33.333333   0.0 -1.903654  472.097893  472.601821  \

                         hlower  imi  symbol_number   symbol_name
start_Time
2024-11-28 15:10:00  471.593965  NaN          10599  GUJGASLTD-EQ
Symbol: 3744, Processed Data:                        open    high     low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  5183.0  5185.0  5175.0  5181.2   303.0  10.0  0.193237  \

                     type      rsi14    obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  64.642036  349.0  5166.803681  5173.379798  \

                            bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  5177.24689  5181.113982  0.149388  0.209486  37.667374  \

                      psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  50.0   0.0  1.172494  5212.999105  5230.587126  \

                          hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  5195.411083  NaN           3744  FINEORG-EQ
Symbol: 3718, Processed Data:                        open     high      low   close   volume  diff
start_Time
2024-11-28 15:10:00  1647.9  1649.05  1647.55  1647.6  14746.0   1.5  \

                          per  type      rsi14      obv        ema20
start_Time
2024-11-28 15:10:00  0.091044  down  53.838862 -33261.0  1645.817763  \

                             bbl          bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  1642.398103  1645.298724  1648.199344  0.352595  \

                          bbp        adx        psl   doji    zscore
start_Time
2024-11-28 15:10:00  0.888068  32.221047  58.333333  100.0  1.127924  \

                            hmid       hupper       hlower  imi
start_Time
2024-11-28 15:10:00  1650.901375  1654.172421  1647.630329  NaN  \

                     symbol_number symbol_name
start_Time
2024-11-28 15:10:00           3718   VOLTAS-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 10604, Processed Data:                        open    high     low    close    volume  diff
start_Time
2024-11-28 15:10:00  1559.0  1561.1  1558.8  1559.65  170914.0   2.3  \

                          per type      rsi14        obv        ema20
start_Time
2024-11-28 15:10:00  0.147549   up  36.887981 -1154584.0  1564.918115  \

                            bbl          bbm          bbu       bbb       bbp
start_Time
2024-11-28 15:10:00  1554.90058  1559.646694  1564.392808  0.608614  0.410801  \

                         adx        psl  doji    zscore         hmid
start_Time
2024-11-28 15:10:00  21.4752  41.666667   0.0 -1.288321  1564.058364  \

                          hupper       hlower  imi  symbol_number
start_Time
2024-11-28 15:10:00  1570.967248  1557.149479  NaN          10604  \

                       symbol_name
start_Time
2024-11-28 15:10:00  BHARTIARTL-EQ
Symbol: 3761, Processed Data:                       open   high    low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  289.5  290.0  289.5  289.85  10717.0   0.5  0.172712  \

                    type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  48.596299  197430.0  289.810588  288.987433  \

                            bbm        bbu       bbb      bbp        adx
start_Time
2024-11-28 15:10:00  289.352946  289.71846  0.252642  0.70116  20.645253  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  58.333333   0.0 -0.144614  289.977285  290.494684  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  289.459887  NaN           3761    RITES-EQ
Symbol: 3787, Processed Data:                       open   high     low   close    volume  diff       per
start_Time
2024-11-28 15:10:00  571.2  571.5  570.55  571.05  115982.0  0.95  0.166506  \

                     type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  35.543106 -475947.0  573.256833  569.887127  \

                            bbm         bbu       bbb     bbp        adx
start_Time
2024-11-28 15:10:00  571.208641  572.530156  0.462708  0.2508  17.838765  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  16.666667   0.0 -1.813447  572.179739  574.276253  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  570.083225  NaN           3787    WIPRO-EQ
Symbol: 10637, Processed Data:                         open    high      low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  1573.05  1574.0  1572.25  1574.0  3841.0  1.75  0.111305  \

                    type      rsi14      obv        ema20          bbl
start_Time
2024-11-28 15:10:00   up  43.488784  35292.0  1576.242203  1570.278155  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  1572.652687  1575.027218  0.301978  0.415207  19.168973  \

                           psl  doji  zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0 -0.8543  1577.143183  1581.814117  \

                          hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  1572.472249  NaN          10637  OLECTRA-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 10666, Processed Data:                        open    high     low   close    volume  diff       per
start_Time
2024-11-28 15:10:00  105.74  105.85  105.65  105.79  197884.0   0.2  0.189304  \

                    type      rsi14        obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  63.549653  5688946.0  105.495746  105.408598  \

                            bbm         bbu       bbb       bbp       adx
start_Time
2024-11-28 15:10:00  105.548541  105.688483  0.265172  0.862503  19.48254  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  66.666667   0.0  1.988621  105.853701  105.990225  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  105.717177  NaN          10666      PNB-EQ
Symbol: 3857, Processed Data:                        open   high     low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  517.45  518.5  516.15  516.25  1112.0  2.35  0.455294  \

                     type     rsi14      obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  37.66508  21865.0  518.277707  515.507674  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  516.971094  518.434515  0.566152  0.219461  18.999999  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0 -2.748525  517.833517  518.617509  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  517.049525  NaN           3857   VARROC-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 429 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name

Symbol: 3812, Processed Data:                        open    high    low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  123.04  123.15  123.0  123.02  34046.0  0.15  0.121951  \

                     type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  56.221559  187347.0  122.877571  122.732019  \

                            bbm         bbu     bbb       bbp        adx
start_Time
2024-11-28 15:10:00  122.895286  123.058552  0.2657  0.820685  17.021555  \

                      psl   doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  50.0  100.0  1.589874  123.167497  123.359868  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  122.975125  NaN           3812     ZEEL-EQ
Symbol: 10726, Processed Data:                         open     high     low    close  volume  diff
start_Time
2024-11-28 15:10:00  2337.05  2343.85  2336.0  2343.35  2516.0  7.85  \

                          per type      rsi14       obv       ema20
start_Time
2024-11-28 15:10:00  0.336045   up  46.424479 -108161.0  2344.84651  \

                             bbl          bbm         bbu       bbb       bbp
start_Time
2024-11-28 15:10:00  2331.170583  2338.092316  2345.01405  0.592084  0.348859  \

                           adx        psl  doji    zscore         hmid
start_Time
2024-11-28 15:10:00  17.130772  41.666667   0.0 -0.529436  2345.060816  \

                          hupper       hlower  imi  symbol_number
start_Time
2024-11-28 15:10:00  2350.036688  2340.084944  NaN          10726  \

                      symbol_name
start_Time
2024-11-28 15:10:00  INDIAMART-EQ
Symbol: 10738, Processed Data:                          open     high       low     close  volume   diff
start_Time
2024-11-28 15:10:00  11639.75  11649.1  11614.75  11638.45  1740.0  34.35  \

                          per  type      rsi14     obv         ema20
start_Time
2024-11-28 15:10:00  0.295745  down  63.924458  5959.0  11589.437901  \

                              bbl           bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  11567.421515  11602.214192  11637.00687  0.599759  \

                         bbp        adx   psl   doji    zscore          hmid
start_Time
2024-11-28 15:10:00  0.68015  18.434382  75.0  100.0  1.812429  11670.173115  \

                           hupper        hlower  imi  symbol_number
start_Time
2024-11-28 15:10:00  11695.190665  11645.155566  NaN          10738  \

                    symbol_name
start_Time
2024-11-28 15:10:00     OFSS-EQ
Error fetching data for 10793: DataFrame constructor not properly called!

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name

Symbol: 10753, Processed Data:                       open    high     low   close    volume  diff       per
start_Time
2024-11-28 15:10:00  121.3  121.58  121.05  121.35  257739.0  0.53  0.437836  \

                    type     rsi14        obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  27.64847 -1135808.0  122.239108  120.861586  \

                            bbm         bbu      bbb       bbp        adx
start_Time
2024-11-28 15:10:00  121.325724  121.789862  0.76511  0.202972  30.322172  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  33.333333   0.0 -1.975162  121.576989  122.143662  \

                         hlower  imi  symbol_number   symbol_name
start_Time
2024-11-28 15:10:00  121.010317  NaN          10753  UNIONBANK-EQ
Symbol: 3918, Processed Data:                         open    high      low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  1339.05  1339.2  1337.25  1338.1  2431.0  1.95  0.145822  \

                     type      rsi14      obv        ema20         bbl
start_Time
2024-11-28 15:10:00  down  21.293223 -10676.0  1344.296138  1331.10038  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  1337.694134  1344.287889  0.985839  0.466322  49.058276  \

                           psl  doji    zscore        hmid       hupper
start_Time
2024-11-28 15:10:00  33.333333   0.0 -1.987663  1338.63284  1341.122084  \

                          hlower  imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  1336.143596  NaN           3918  NATCOPHARM-EQ
Symbol: 3906, Processed Data:                         open    high      low    close  volume  diff
start_Time
2024-11-28 15:10:00  2103.05  2107.0  2103.05  2106.45   560.0  3.95  \

                          per type    rsi14      obv        ema20
start_Time
2024-11-28 15:10:00  0.187822   up  47.7751  16952.0  2108.661498  \

                             bbl          bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  2096.896283  2102.694559  2108.492835  0.551509  \

                          bbp       adx   psl  doji    zscore         hmid
start_Time
2024-11-28 15:10:00  0.530651  15.91616  50.0   0.0 -0.182894  2103.713783  \

                          hupper       hlower  imi  symbol_number
start_Time
2024-11-28 15:10:00  2111.376773  2096.050793  NaN           3906  \

                       symbol_name
start_Time
2024-11-28 15:10:00  CAPLIPOINT-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name

Symbol: 10794, Processed Data:                        open    high    low   close    volume  diff       per
start_Time
2024-11-28 15:10:00  102.71  102.79  102.7  102.75  138457.0  0.09  0.087634  \

                    type      rsi14        obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  56.370454  3249133.0  102.604444  102.435422  \

                            bbm         bbu       bbb      bbp        adx
start_Time
2024-11-28 15:10:00  102.587211  102.739001  0.295923  0.87153  17.848043  \

                      psl  doji    zscore        hmid      hupper      hlower
start_Time
2024-11-28 15:10:00  50.0   0.0  1.319878  102.839421  102.988548  102.690295  \

                     imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  NaN          10794    CANBK-EQ
Symbol: 10940, Processed Data:                        open     high      low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  5956.6  5973.25  5955.95  5960.5  4820.0  17.3  0.290466  \

                    type      rsi14      obv        ema20          bbl
start_Time
2024-11-28 15:10:00   up  56.797784  21080.0  5947.262712  5926.888683  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  5943.303969  5959.719254  0.552396  0.885191  15.803321  \

                           psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0  1.082689  5957.378364  5974.748291  \

                          hlower  imi  symbol_number  symbol_name
start_Time
2024-11-28 15:10:00  5940.008436  NaN          10940  DIVISLAB-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 429 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 10925, Processed Data:                         open    high     low   close  volume  diff      per
start_Time
2024-11-28 15:10:00  1065.35  1065.4  1061.6  1062.1   156.0   3.8  0.35795  \

                     type      rsi14      obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  31.828571  31343.0  1065.981444  1060.915932  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  1063.363298  1065.810664  0.460307  0.139756  34.699871  \

                           psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0 -2.321527  1067.280507  1070.083857  \

                          hlower  imi  symbol_number   symbol_name
start_Time
2024-11-28 15:10:00  1064.477158  NaN          10925  GODREJIND-EQ
Symbol: 10945, Processed Data:                        open   high    low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  471.75  471.8  471.2  471.65   210.0   0.6  0.127334  \

                     type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  53.914801  151351.0  471.374032  470.189073  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  470.897875  471.606677  0.301043  0.713124  29.582261  \

                      psl   doji    zscore        hmid      hupper     hlower
start_Time
2024-11-28 15:10:00  50.0  100.0  0.452042  473.120326  475.170011  471.07064  \

                     imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  NaN          10945      TMB-EQ
Symbol: 10990, Processed Data:                         open     high     low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  2402.45  2402.45  2398.5  2399.8   609.0  3.95  0.164686  \

                     type      rsi14      obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  50.348475 -22414.0  2398.690204  2392.998412  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  2396.312624  2399.626836  0.276609  0.829999  14.913513  \

                      psl  doji    zscore        hmid       hupper
start_Time
2024-11-28 15:10:00  50.0   0.0 -0.087794  2392.90638  2398.922592  \

                          hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  2386.890168  NaN          10990   RADICO-EQ
Error fetching data for 4067: DataFrame constructor not properly called!
Symbol: 10999, Processed Data:                          open      high      low     close  volume   diff
start_Time
2024-11-28 15:10:00  10940.35  10953.05  10938.4  10951.45  7494.0  14.65  \

                          per type      rsi14      obv         ema20
start_Time
2024-11-28 15:10:00  0.133932   up  48.992801  21658.0  10952.665008  \

                              bbl           bbm           bbu       bbb
start_Time
2024-11-28 15:10:00  10908.657632  10928.788544  10948.919455  0.368402  \

                          bbp        adx        psl  doji    zscore
start_Time
2024-11-28 15:10:00  0.738724  13.518721  41.666667   0.0 -0.396315  \

                             hmid        hupper        hlower  imi
start_Time
2024-11-28 15:10:00  10937.888322  10957.775034  10918.001609  NaN  \

                     symbol_number symbol_name
start_Time
2024-11-28 15:10:00          10999   MARUTI-EQ

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 429 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name

Error fetching data for 4204: DataFrame constructor not properly called!
Symbol: 29135, Processed Data:                       open    high    low  close   volume  diff      per type
start_Time
2024-11-28 15:10:00  347.4  347.75  347.2  347.7  62587.0  0.55  0.15841   up  \

                        rsi14       obv      ema20         bbl         bbm
start_Time
2024-11-28 15:10:00  45.03012 -377698.0  348.53166  345.352528  347.273569  \

                           bbu       bbb       bbp        adx        psl
start_Time
2024-11-28 15:10:00  349.19461  1.106356  0.480852  15.376518  41.666667  \

                     doji    zscore        hmid      hupper      hlower  imi
start_Time
2024-11-28 15:10:00   0.0 -0.518498  348.780093  350.227281  347.332904  NaN  \

                     symbol_number    symbol_name
start_Time
2024-11-28 15:10:00          29135  INDUSTOWER-EQ
Symbol: 29962, Processed Data:                         open    high      low    close  volume  diff
start_Time
2024-11-28 15:10:00  1120.55  1121.5  1120.05  1120.25   355.0  1.45  \

                          per  type      rsi14      obv        ema20
start_Time
2024-11-28 15:10:00  0.129459  down  44.953312  16723.0  1121.415213  \

                             bbl          bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  1118.181862  1119.506098  1120.830334  0.236575  \

                          bbp       adx   psl  doji    zscore         hmid
start_Time
2024-11-28 15:10:00  0.705364  8.979202  50.0   0.0 -0.875717  1118.235704  \

                          hupper       hlower  imi  symbol_number  symbol_name
start_Time
2024-11-28 15:10:00  1120.513566  1115.957841  NaN          29962  JUSTDIAL-EQ
Symbol: 4244, Processed Data:                         open     high     low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  4204.45  4210.05  4201.2  4202.6  2594.0  8.85  0.210654  \

                     type      rsi14     obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  39.971476 -8756.0  4209.523979  4191.269788  \

                            bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  4200.48317  4209.696551  0.438682  0.538902  13.083479  \

                           psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  33.333333   0.0 -1.040229  4201.763873  4208.497617  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  4195.03013  NaN           4244  HDFCAMC-EQ

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 429 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 429 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name

Symbol: 11184, Processed Data:                       open  high    low  close    volume  diff       per type
start_Time
2024-11-28 15:10:00  64.23  64.3  64.22  64.24  132569.0  0.08  0.124572   up  \

                         rsi14       obv      ema20        bbl        bbm
start_Time
2024-11-28 15:10:00  39.391751 -130493.0  64.363701  64.081446  64.215669  \

                           bbu      bbb       bbp        adx        psl
start_Time
2024-11-28 15:10:00  64.349893  0.41804  0.516132  16.152204  33.333333  \

                      doji    zscore       hmid     hupper     hlower  imi
start_Time
2024-11-28 15:10:00  100.0 -1.468282  64.271417  64.394633  64.148201  NaN  \

                     symbol_number    symbol_name
start_Time
2024-11-28 15:10:00          11184  IDFCFIRSTB-EQ
Symbol: 4306, Processed Data:                        open     high      low   close   volume  diff
start_Time
2024-11-28 15:10:00  3045.4  3046.85  3033.15  3033.2  46053.0  13.7  \

                          per  type      rsi14       obv        ema20
start_Time
2024-11-28 15:10:00  0.451676  down  47.418729  211033.0  3040.258252  \

                             bbl          bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  3031.557329  3037.188812  3042.820295  0.370835  \

                          bbp        adx   psl  doji    zscore         hmid
start_Time
2024-11-28 15:10:00  0.141408  31.752994  50.0   0.0 -0.039393  3056.615659  \

                          hupper       hlower  imi  symbol_number
start_Time
2024-11-28 15:10:00  3074.625266  3038.606051  NaN           4306  \

                       symbol_name
start_Time
2024-11-28 15:10:00  SHRIRAMFIN-EQ
Symbol: 11195, Processed Data:                         open     high     low   close   volume  diff
start_Time
2024-11-28 15:10:00  4358.15  4358.75  4355.0  4355.0  16593.0  3.75  \

                          per  type      rsi14       obv        ema20
start_Time
2024-11-28 15:10:00  0.086108  down  52.232321  284770.0  4353.257362  \

                             bbl         bbm          bbu       bbb       bbp
start_Time
2024-11-28 15:10:00  4341.216489  4348.64282  4356.069152  0.341547  0.928016  \

                           adx   psl  doji    zscore         hmid
start_Time
2024-11-28 15:10:00  26.135736  50.0   0.0  0.126694  4354.872897  \

                          hupper       hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  4371.708204  4338.037589  NaN          11195   INDIGO-EQ
Symbol: 11223, Processed Data:                       open   high    low  close   volume  diff       per
start_Time
2024-11-28 15:10:00  45.02  45.02  44.84  44.87  59891.0  0.18  0.401427  \

                     type      rsi14        obv      ema20        bbl
start_Time
2024-11-28 15:10:00  down  51.957991  1152413.0  44.856907  44.833167  \

                           bbm        bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  44.845816  44.858466  0.056412  0.270084  27.800216  \

                      psl  doji    zscore       hmid     hupper     hlower
start_Time
2024-11-28 15:10:00  50.0   0.0  0.646545  44.977411  45.094816  44.860006  \

                     imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  NaN          11223  UCOBANK-EQ
Error fetching data for 11253: DataFrame constructor not properly called!
Error fetching data for 11287: DataFrame constructor not properly called!

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 11256, Processed Data:                       open    high    low  close  volume  diff       per
start_Time
2024-11-28 15:10:00  917.3  919.15  917.3  917.3    11.0  1.85  0.201679  \

                     type      rsi14     obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  34.827383 -4617.0  921.083919  915.726065  \

                           bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  918.55053  921.374994  0.614983  0.278625  14.518028  \

                      psl   doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  25.0  100.0 -2.626852  919.639806  921.614645  \

                         hlower  imi  symbol_number   symbol_name
start_Time
2024-11-28 15:10:00  917.664967  NaN          11256  JAIBALAJI-EQ
Symbol: 11262, Processed Data:                        open    high     low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  320.25  320.25  319.75  319.75  69819.0   0.5  0.156372  \

                     type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  58.199845  405070.0  319.033376  317.674349  \

                            bbm       bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  318.909824  320.1453  0.774812  0.840021  12.565749  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0  2.079577  319.524348  320.179066  \

                        hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  318.86963  NaN          11262      IGL-EQ
Symbol: 11236, Processed Data:                       open    high    low  close   volume  diff       per
start_Time
2024-11-28 15:10:00  698.3  700.45  697.1  697.1  12306.0  3.35  0.480562  \

                     type      rsi14      obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  49.420941  92240.0  698.119471  690.902702  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  696.686265  702.469828  1.660306  0.535768  32.456207  \

                      psl  doji    zscore       hmid      hupper      hlower
start_Time
2024-11-28 15:10:00  50.0   0.0 -0.027172  700.48594  703.606393  697.365487  \

                     imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  NaN          11236      JSL-EQ
Symbol: 4421, Processed Data:                       open   high    low  close  volume  diff       per  type
start_Time
2024-11-28 15:10:00  989.7  989.7  988.1  988.1   787.0   1.6  0.161927  down  \

                        rsi14     obv       ema20         bbl         bbm
start_Time
2024-11-28 15:10:00  45.09156  6979.0  989.643172  987.043263  987.859596  \

                            bbu       bbb       bbp        adx        psl
start_Time
2024-11-28 15:10:00  988.675929  0.165273  0.647246  13.940705  33.333333  \

                     doji    zscore        hmid      hupper      hlower  imi
start_Time
2024-11-28 15:10:00   0.0 -0.911601  993.225018  999.605991  986.844045  NaN  \

                     symbol_number   symbol_name
start_Time
2024-11-28 15:10:00           4421  CREDITACC-EQ

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 429 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name

Error fetching data for 11364: DataFrame constructor not properly called!

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 4487, Processed Data:                        open    high     low    close  volume  diff       per
start_Time
2024-11-28 15:10:00  1974.6  1974.6  1970.0  1970.05   314.0   4.6  0.233503  \

                     type      rsi14     obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  51.656067 -1285.0  1968.280664  1963.103759  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  1968.670086  1974.236414  0.565491  0.619461  17.484257  \

                           psl  doji   zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  58.333333   0.0  0.60246  1970.63578  1975.50964  \

                         hlower  imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  1965.76192  NaN           4487  ALKYLAMINE-EQ
Symbol: 11343, Processed Data:                        open     high      low    close  volume  diff
start_Time
2024-11-28 15:10:00  1601.8  1602.35  1599.05  1599.05  1360.0   3.3  \

                          per  type      rsi14      obv        ema20
start_Time
2024-11-28 15:10:00  0.206373  down  35.114672 -48977.0  1609.131541  \

                             bbl          bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  1597.543238  1600.405824  1603.268411  0.357733  \

                          bbp        adx        psl  doji   zscore
start_Time
2024-11-28 15:10:00  0.263182  20.599218  33.333333   0.0 -2.27991  \

                            hmid       hupper       hlower  imi
start_Time
2024-11-28 15:10:00  1599.069512  1602.979936  1595.159089  NaN  \

                     symbol_number symbol_name
start_Time
2024-11-28 15:10:00          11343    AFFLE-EQ
Symbol: 11351, Processed Data:                        open   high    low  close   volume  diff       per
start_Time
2024-11-28 15:10:00  327.45  328.5  327.3  328.5  20843.0   1.2  0.366636  \

                    type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  58.544339  131113.0  327.354007  325.571815  \

                            bbm        bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  326.856182  328.14055  0.785892  0.672777  13.381396  \

                           psl  doji    zscore       hmid      hupper
start_Time
2024-11-28 15:10:00  58.333333   0.0  2.427415  327.89408  328.504412  \

                         hlower  imi  symbol_number  symbol_name
start_Time
2024-11-28 15:10:00  327.283749  NaN          11351  PETRONET-EQ
Symbol: 11373, Processed Data:                       open   high     low  close   volume  diff       per
start_Time
2024-11-28 15:10:00  363.9  364.7  363.55  364.3  19444.0  1.15  0.316325  \

                    type      rsi14       obv       ema20        bbl
start_Time
2024-11-28 15:10:00   up  50.923777  991045.0  364.318377  361.91596  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  363.520204  365.124449  0.882616  0.509287  21.186864  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0  0.296638  365.244524  366.404951  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  364.084097  NaN          11373   BIOCON-EQ

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 11377, Processed Data:                      open  high   low  close   volume  diff       per  type
start_Time
2024-11-28 15:10:00  56.8  56.8  56.7  56.72  76779.0   0.1  0.176367  down  \

                         rsi14        obv      ema20        bbl        bbm
start_Time
2024-11-28 15:10:00  47.062659  3890166.0  56.799921  56.632152  56.710739  \

                           bbu       bbb       bbp        adx   psl  doji
start_Time
2024-11-28 15:10:00  56.789327  0.277152  0.431672  22.066377  50.0   0.0  \

                       zscore      hmid     hupper     hlower  imi
start_Time
2024-11-28 15:10:00 -0.935779  56.61193  56.852375  56.371485  NaN  \

                     symbol_number  symbol_name
start_Time
2024-11-28 15:10:00          11377  MAHABANK-EQ
Symbol: 4503, Processed Data:                         open     high     low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  2957.65  2957.65  2953.6  2955.9  3876.0  4.05  0.137121  \

                     type      rsi14      obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  49.929069  32953.0  2955.446866  2946.455494  \

                             bbm          bbu       bbb       bbp       adx
start_Time
2024-11-28 15:10:00  2951.835977  2957.216461  0.364552  0.663928  9.911902  \

                           psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0  0.029709  2955.556737  2960.473709  \

                          hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  2950.639765  NaN           4503  MPHASIS-EQ
Symbol: 11403, Processed Data:                       open   high    low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  372.8  372.9  372.4  372.85  29467.0   0.5  0.134264  \

                    type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  50.356123  336187.0  372.939758  372.203831  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  372.366312  372.528793  0.087269  0.603668  13.475376  \

                           psl   doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  58.333333  100.0  0.244533  374.423915  376.043116  \

                         hlower  imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  372.804713  NaN          11403  POONAWALLA-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 11411, Processed Data:                        open    high    low  close  volume  diff       per
start_Time
2024-11-28 15:10:00  980.65  980.65  975.3  977.6  4718.0  5.35  0.548549  \

                     type      rsi14     obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  54.490081 -8509.0  976.650572  972.415138  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  975.824302  979.233466  0.698725  0.423104  19.969157  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  33.333333   0.0  0.951426  981.229245  983.211064  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  979.247427  NaN          11411  RKFORGE-EQ
Symbol: 11483, Processed Data:                         open     high     low   close   volume  diff
start_Time
2024-11-28 15:10:00  3665.95  3667.95  3664.4  3666.7  26675.0  3.55  \

                          per type    rsi14     obv        ema20          bbl
start_Time
2024-11-28 15:10:00  0.096878   up  49.3957  9375.0  3665.377147  3649.269391  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  3658.076433  3666.883476  0.481512  0.859006  13.360832  \

                      psl   doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  50.0  100.0 -0.175949  3658.642901  3664.530894  \

                          hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  3652.754907  NaN          11483       LT-EQ
Symbol: 11452, Processed Data:                       open   high    low  close   volume  diff       per type
start_Time
2024-11-28 15:10:00  790.0  794.6  790.0  791.4  17424.0   4.6  0.582278   up  \

                         rsi14      obv       ema20         bbl         bbm
start_Time
2024-11-28 15:10:00  63.140614  16973.0  786.818176  785.427395  788.055398  \

                            bbu       bbb       bbp        adx        psl
start_Time
2024-11-28 15:10:00  790.683402  0.666959  0.869977  22.586177  58.333333  \

                     doji   zscore        hmid      hupper      hlower  imi
start_Time
2024-11-28 15:10:00   0.0  2.81231  788.812779  791.025089  786.600469  NaN  \

                     symbol_number symbol_name
start_Time
2024-11-28 15:10:00          11452      CCL-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 4684, Processed Data:                       open    high    low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  664.8  666.95  664.8  665.15  11484.0  2.15  0.323406  \

                    type      rsi14      obv      ema20         bbl
start_Time
2024-11-28 15:10:00   up  39.504883 -80705.0  666.85536  663.440249  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  664.966552  666.492855  0.459062  0.445439  14.514697  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0 -1.580939  666.832983  668.990989  \

                         hlower  imi  symbol_number  symbol_name
start_Time
2024-11-28 15:10:00  664.674977  NaN           4684  SONACOMS-EQ
Symbol: 11491, Processed Data:                         open     high     low    close  volume   diff
start_Time
2024-11-28 15:10:00  9916.85  9921.45  9900.0  9913.65   947.0  21.45  \

                          per  type      rsi14      obv        ema20
start_Time
2024-11-28 15:10:00  0.216667  down  79.454456  10285.0  9801.932158  \

                             bbl          bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  9777.874968  9849.829993  9921.785018  1.461041  \

                          bbp        adx        psl   doji    zscore
start_Time
2024-11-28 15:10:00  0.848621  34.253818  83.333333  100.0  2.660176  \

                            hmid       hupper       hlower  imi
start_Time
2024-11-28 15:10:00  9884.692558  9914.005273  9855.379843  NaN  \

                     symbol_number  symbol_name
start_Time
2024-11-28 15:10:00          11491  APARINDS-EQ
Symbol: 4668, Processed Data:                        open    high     low   close    volume  diff       per
start_Time
2024-11-28 15:10:00  247.55  248.45  247.45  248.35  158440.0   1.0  0.404122  \

                    type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  63.152033  556670.0  247.448647  246.991597  \

                            bbm         bbu       bbb      bbp        adx
start_Time
2024-11-28 15:10:00  247.285536  247.579474  0.237732  0.77976  10.029078  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  58.333333   0.0  2.097994  248.193358  248.643962  \

                         hlower  imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  247.742755  NaN           4668  BANKBARODA-EQ
Symbol: 11532, Processed Data:                         open     high      low    close  volume  diff
start_Time
2024-11-28 15:10:00  11006.4  11006.9  11000.0  11000.2  2955.0   6.9  \

                          per  type     rsi14     obv         ema20
start_Time
2024-11-28 15:10:00  0.062727  down  46.49957  4928.0  11007.741312  \

                              bbl           bbm           bbu       bbb
start_Time
2024-11-28 15:10:00  10958.762187  10982.417884  11006.073581  0.430792  \

                          bbp        adx        psl  doji    zscore
start_Time
2024-11-28 15:10:00  0.871625  18.555299  41.666667   0.0 -0.500845  \

                             hmid       hupper        hlower  imi
start_Time
2024-11-28 15:10:00  10984.366567  11007.59825  10961.134885  NaN  \

                     symbol_number    symbol_name
start_Time
2024-11-28 15:10:00          11532  ULTRACEMCO-EQ

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name

Symbol: 11536, Processed Data:                        open     high     low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  4248.1  4248.65  4245.0  4245.2  32812.0  3.65  0.085984  \

                     type      rsi14       obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  44.065646 -263777.0  4251.983826  4236.461704  \

                             bbm          bbu       bbb       bbp       adx
start_Time
2024-11-28 15:10:00  4243.840593  4251.219482  0.347746  0.578562  15.23884  \

                      psl  doji  zscore        hmid       hupper       hlower
start_Time
2024-11-28 15:10:00  25.0   0.0 -0.6134  4257.79257  4272.492861  4243.092279  \

                     imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  NaN          11536      TCS-EQ
Symbol: 4693, Processed Data:                       open   high    low  close  volume  diff       per  type
start_Time
2024-11-28 15:10:00  837.2  838.1  837.0  837.2   474.0   1.1  0.131422  down  \

                        rsi14      obv       ema20         bbl         bbm
start_Time
2024-11-28 15:10:00  48.27581  21935.0  837.248928  833.992014  836.214085  \

                            bbu      bbb       bbp        adx        psl
start_Time
2024-11-28 15:10:00  838.436156  0.53146  0.676843  23.280409  33.333333  \

                      doji    zscore        hmid      hupper      hlower  imi
start_Time
2024-11-28 15:10:00  100.0  0.275077  837.558432  838.464857  836.652008  NaN  \

                     symbol_number   symbol_name
start_Time
2024-11-28 15:10:00           4693  SHYAMMETL-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number

Symbol: 11580, Processed Data:                       open   high    low  close  volume  diff       per type
start_Time
2024-11-28 15:10:00  764.9  765.0  762.9  765.0  1758.0   2.1  0.275265   up  \

                         rsi14     obv       ema20         bbl         bbm
start_Time
2024-11-28 15:10:00  67.692449  5674.0  760.379284  755.389221  759.906035  \

                            bbu       bbb       bbp        adx   psl   doji
start_Time
2024-11-28 15:10:00  764.422848  1.188782  0.831425  28.246951  50.0  100.0  \

                       zscore        hmid      hupper      hlower  imi
start_Time
2024-11-28 15:10:00  2.833479  760.940096  762.149156  759.731036  NaN  \

                     symbol_number  symbol_name
start_Time
2024-11-28 15:10:00          11580  WESTLIFE-EQ
Symbol: 11571, Processed Data:                       open    high     low  close   volume  diff       per
start_Time
2024-11-28 15:10:00  245.9  246.15  245.75  245.9  19200.0   0.4  0.162767  \

                     type      rsi14      obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  46.622594 -75561.0  246.155089  245.400374  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  245.671668  245.942961  0.220858  0.644368  16.338101  \

                           psl   doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  41.666667  100.0 -0.778198  246.643807  247.503902  \

                         hlower  imi  symbol_number   symbol_name
start_Time
2024-11-28 15:10:00  245.783711  NaN          11571  PPLPHARMA-EQ
Symbol: 11543, Processed Data:                        open    high     low    close  volume  diff       per
start_Time
2024-11-28 15:10:00  8650.0  8655.0  8648.0  8651.95  1920.0   7.0  0.080944  \

                    type      rsi14      obv        ema20          bbl
start_Time
2024-11-28 15:10:00   up  50.721054  25797.0  8651.901131  8644.258376  \

                             bbm          bbu      bbb      bbp        adx
start_Time
2024-11-28 15:10:00  8647.067362  8649.876347  0.06497  0.66601  25.170428  \

                           psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  58.333333   0.0 -0.118227  8647.393775  8662.361364  \

                          hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  8632.426185  NaN          11543  COFORGE-EQ
Symbol: 4717, Processed Data:                       open    high     low   close    volume  diff       per
start_Time
2024-11-28 15:10:00  196.5  196.69  196.24  196.51  367208.0  0.45  0.229311  \

                    type      rsi14        obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  51.417671  2034326.0  196.382552  195.669797  \

                           bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  196.03033  196.390863  0.367834  0.790778  11.196565  \

                      psl   doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  50.0  100.0  0.108728  196.513488  196.997766  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  196.029211  NaN           4717     GAIL-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name

Symbol: 4749, Processed Data:                       open   high     low   close   volume  diff      per
start_Time
2024-11-28 15:10:00  820.8  821.4  820.45  821.05  12331.0  0.95  0.11579  \

                    type      rsi14       obv       ema20        bbl
start_Time
2024-11-28 15:10:00   up  51.967439  673146.0  820.524911  817.44594  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  819.179607  820.913273  0.423269  0.866389  15.127802  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  58.333333   0.0 -0.213401  818.210119  819.762117  \

                        hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  816.65812  NaN           4749   CONCOR-EQ
Symbol: 4745, Processed Data:                       open   high     low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  112.0  112.0  111.82  111.83  94135.0  0.18  0.160973  \

                     type      rsi14        obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  60.646214  1519873.0  111.423776  111.143419  \

                            bbm         bbu      bbb      bbp        adx
start_Time
2024-11-28 15:10:00  111.525707  111.907995  0.68556  0.88491  26.183642  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0  1.302102  112.603784  113.456898  \

                        hlower  imi  symbol_number   symbol_name
start_Time
2024-11-28 15:10:00  111.75067  NaN           4745  BANKINDIA-EQ
Symbol: 11630, Processed Data:                       open    high    low   close    volume  diff      per
start_Time
2024-11-28 15:10:00  361.4  361.75  361.3  361.65  195766.0  0.45  0.12455  \

                    type      rsi14        obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  43.838588 -1360046.0  362.090487  359.388832  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  360.598129  361.807427  0.670717  0.790198  18.412271  \

                      psl  doji    zscore        hmid      hupper      hlower
start_Time
2024-11-28 15:10:00  50.0   0.0 -0.867977  359.955003  361.031463  358.878544  \

                     imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  NaN          11630     NTPC-EQ

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number

Symbol: 11655, Processed Data:                         open     high      low   close  volume  diff
start_Time
2024-11-28 15:10:00  1546.85  1546.85  1541.05  1545.6   922.0   5.8  \

                          per  type      rsi14      obv        ema20
start_Time
2024-11-28 15:10:00  0.376367  down  47.719898  11038.0  1546.433563  \

                             bbl          bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  1540.216453  1541.418785  1542.621116  0.156003  \

                          bbp       adx   psl  doji    zscore        hmid
start_Time
2024-11-28 15:10:00  0.346638  9.379755  50.0   0.0 -0.344749  1547.71736  \

                         hupper       hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  1551.93785  1543.496871  NaN          11655     JBMA-EQ
Symbol: 11654, Processed Data:                        open    high      low    close  volume  diff       per
start_Time
2024-11-28 15:10:00  2983.7  2985.7  2981.35  2984.15   626.0  4.35  0.145907  \

                    type      rsi14    obv        ema20         bbl
start_Time
2024-11-28 15:10:00   up  49.224988 -265.0  2983.510025  2973.45304  \

                             bbm          bbu       bbb       bbp       adx
start_Time
2024-11-28 15:10:00  2978.745903  2984.038766  0.355375  0.746001  9.858005  \

                      psl   doji    zscore         hmid      hupper
start_Time
2024-11-28 15:10:00  50.0  100.0 -0.180235  2978.664191  2983.30245  \

                          hlower  imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  2974.025933  NaN          11654  LALPATHLAB-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name

Symbol: 11723, Processed Data:                       open    high     low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  953.4  953.85  952.15  952.55  26143.0   1.7  0.178543  \

                     type      rsi14       obv       ema20        bbl
start_Time
2024-11-28 15:10:00  down  33.555381 -476187.0  956.507993  947.43793  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  951.965357  956.492785  0.951175  0.520392  22.776541  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0 -1.751012  952.117251  953.485419  \

                         hlower  imi  symbol_number  symbol_name
start_Time
2024-11-28 15:10:00  950.749083  NaN          11723  JSWSTEEL-EQ
Symbol: 4847, Processed Data:                        open    high     low  close  volume  diff       per
start_Time
2024-11-28 15:10:00  574.95  574.95  573.25  574.6  3936.0   1.7  0.296555  \

                     type      rsi14      obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  53.613319 -76640.0  574.017005  572.834873  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  573.395587  573.956301  0.195577  0.370177  19.207146  \

                           psl  doji    zscore        hmid     hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0  0.968153  574.203653  575.32618  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  573.081127  NaN           4847     KIMS-EQ
Symbol: 11703, Processed Data:                         open    high     low    close  volume  diff       per
start_Time
2024-11-28 15:10:00  5452.75  5455.0  5450.0  5450.55  2172.0   5.0  0.091743  \

                     type      rsi14     obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  45.281234  3800.0  5455.578488  5448.249085  \

                             bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  5449.909687  5451.57029  0.060941  0.527193  10.833395  \

                           psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0 -1.343017  5446.545951  5455.989102  \

                        hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  5437.1028  NaN          11703    ALKEM-EQ
Symbol: 4892, Processed Data:                        open    high     low   close  volume  diff      per
start_Time
2024-11-28 15:10:00  500.95  500.95  499.45  499.55  1959.0   1.5  0.30033  \

                     type      rsi14      obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  52.018619  18402.0  499.149516  498.590276  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  499.160889  499.731503  0.228629  0.753333  16.665604  \

                      psl  doji   zscore        hmid     hupper      hlower
start_Time
2024-11-28 15:10:00  50.0   0.0  0.95152  501.942008  503.37911  500.504906  \

                     imi  symbol_number  symbol_name
start_Time
2024-11-28 15:10:00  NaN           4892  SAREGAMA-EQ
Symbol: 4898, Processed Data:                        open    high    low  close  volume  diff       per
start_Time
2024-11-28 15:10:00  516.95  516.95  515.6  515.9  1025.0  1.35  0.261831  \

                     type      rsi14     obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  69.599453 -1567.0  512.199826  509.485159  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  512.881628  516.278097  1.324465  0.900176  19.085938  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  58.333333   0.0  3.031064  513.893632  514.702807  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  513.084458  NaN           4898      FDC-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name

Symbol: 4907, Processed Data:                        open   high     low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  198.99  199.0  198.85  198.97  50247.0  0.15  0.075434  \

                     type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  40.663555  415928.0  199.442998  198.227366  \

                            bbm         bbu      bbb       bbp       adx
start_Time
2024-11-28 15:10:00  198.760223  199.293079  0.53618  0.584242  16.71433  \

                      psl   doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  25.0  100.0 -1.121918  198.590038  199.070757  \

                         hlower  imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  198.109319  NaN           4907  ENGINERSIN-EQ
Symbol: 11809, Processed Data:                        open    high     low  close  volume  diff       per
start_Time
2024-11-28 15:10:00  420.55  421.35  420.15  421.3  8696.0   1.2  0.285612  \

                    type     rsi14      obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  50.65974 -94930.0  420.867369  418.928854  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  419.713711  420.498568  0.373996  0.777942  17.058575  \

                      psl  doji    zscore        hmid      hupper      hlower
start_Time
2024-11-28 15:10:00  50.0   0.0  0.582932  421.525437  422.628006  420.422869  \

                     imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  NaN          11809     IIFL-EQ
Symbol: 4963, Processed Data:                         open     high     low   close    volume  diff
start_Time
2024-11-28 15:10:00  1286.45  1286.75  1285.5  1285.7  276018.0  1.25  \

                          per  type      rsi14        obv        ema20
start_Time
2024-11-28 15:10:00  0.097238  down  40.684749 -4487820.0  1287.754666  \

                             bbl          bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  1284.382146  1285.821035  1287.259923  0.223809  \

                          bbp        adx   psl  doji    zscore         hmid
start_Time
2024-11-28 15:10:00  0.388444  10.652984  50.0   0.0 -0.920074  1288.402054  \

                          hupper      hlower  imi  symbol_number   symbol_name
start_Time
2024-11-28 15:10:00  1290.497217  1286.30689  NaN           4963  ICICIBANK-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 429 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name

Symbol: 11821, Processed Data:                       open   high    low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  769.7  769.7  769.0  769.25  1961.0   0.7  0.091027  \

                     type      rsi14      obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  39.077385  21590.0  771.996951  766.280225  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  769.895747  773.511269  0.939224  0.376125  19.048889  \

                      psl  doji    zscore        hmid      hupper      hlower
start_Time
2024-11-28 15:10:00  50.0   0.0 -1.465856  771.165531  773.204687  769.126374  \

                     imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  NaN          11821  WELCORP-EQ
Symbol: 4986, Processed Data:                        open    high     low   close    volume  diff       per
start_Time
2024-11-28 15:10:00  212.24  212.79  212.14  212.41  100252.0  0.65  0.306401  \

                    type     rsi14       obv       ema20        bbl
start_Time
2024-11-28 15:10:00   up  57.37599  925364.0  211.905923  211.33922  \

                           bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  211.82889  212.318559  0.462325  0.817674  12.847811  \

                      psl  doji    zscore        hmid      hupper      hlower
start_Time
2024-11-28 15:10:00  50.0   0.0  1.466837  212.478314  212.897911  212.058717  \

                     imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  NaN           4986    IRCON-EQ
Symbol: 11840, Processed Data:                         open     high     low    close  volume  diff
start_Time
2024-11-28 15:10:00  1251.05  1251.55  1246.5  1247.45  2800.0  5.05  \

                          per  type      rsi14      obv        ema20
start_Time
2024-11-28 15:10:00  0.405134  down  50.856006 -30275.0  1246.959336  \

                             bbl          bbm         bbu       bbb       bbp
start_Time
2024-11-28 15:10:00  1245.066159  1248.003505  1250.94085  0.470727  0.244071  \

                           adx   psl  doji    zscore         hmid
start_Time
2024-11-28 15:10:00  24.232916  50.0   0.0  0.621312  1250.134373  \

                          hupper       hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  1252.962241  1247.306505  NaN          11840       NH-EQ
Error fetching data for 11872: DataFrame constructor not properly called!
Symbol: 11915, Processed Data:                       open   high    low  close    volume  diff      per type
start_Time
2024-11-28 15:10:00  20.35  20.37  20.35  20.37  570485.0  0.02  0.09828   up  \

                         rsi14         obv      ema20        bbl        bbm
start_Time
2024-11-28 15:10:00  49.647643  16090871.0  20.371297  20.326391  20.341357  \

                           bbu       bbb       bbp        adx   psl  doji
start_Time
2024-11-28 15:10:00  20.356324  0.147155  0.788726  16.284527  50.0   0.0  \

                       zscore       hmid    hupper     hlower  imi
start_Time
2024-11-28 15:10:00 -0.390843  20.374401  20.42848  20.320323  NaN  \

                     symbol_number symbol_name
start_Time
2024-11-28 15:10:00          11915  YESBANK-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name

Symbol: 11860, Processed Data:                       open    high    low  close  volume  diff       per
start_Time
2024-11-28 15:10:00  420.2  420.55  419.5  420.1  5320.0  1.05  0.250298  \

                     type      rsi14      obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  40.654272 -19312.0  421.034158  417.649851  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  419.309249  420.968646  0.791491  0.557476  25.777511  \

                      psl   doji   zscore        hmid      hupper      hlower
start_Time
2024-11-28 15:10:00  50.0  100.0 -1.35626  419.562561  420.347861  418.777262  \

                     imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  NaN          11860  JKPAPER-EQ
Symbol: 11956, Processed Data:                        open    high      low    close  volume  diff       per
start_Time
2024-11-28 15:10:00  1075.3  1075.6  1074.95  1075.45  1178.0  0.65  0.060468  \

                    type      rsi14     obv        ema20          bbl
start_Time
2024-11-28 15:10:00   up  66.487627  9051.0  1072.860667  1072.794933  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  1073.985563  1075.176193  0.221722  0.905011  37.990821  \

                           psl   doji    zscore        hmid       hupper
start_Time
2024-11-28 15:10:00  41.666667  100.0  1.300101  1075.58803  1078.026968  \

                          hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  1073.149091  NaN          11956  MEDANTA-EQ
Symbol: 11966, Processed Data:                        open   high    low  close  volume  diff      per type
start_Time
2024-11-28 15:10:00  801.75  802.1  801.5  802.1  2892.0   0.6  0.07486   up  \

                         rsi14     obv       ema20         bbl         bbm
start_Time
2024-11-28 15:10:00  39.240036 -2224.0  804.806024  799.058701  802.574721  \

                            bbu       bbb       bbp        adx        psl
start_Time
2024-11-28 15:10:00  806.090742  0.876185  0.347168  11.500703  41.666667  \

                     doji    zscore        hmid     hupper      hlower  imi
start_Time
2024-11-28 15:10:00   0.0 -1.676189  804.733863  806.96845  802.499276  NaN  \

                     symbol_number symbol_name
start_Time
2024-11-28 15:10:00          11966   BIKAJI-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 429 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name

Symbol: 5097, Processed Data:                        open   high    low   close    volume  diff      per
start_Time
2024-11-28 15:10:00  286.22  286.6  286.0  286.48  815687.0   0.6  0.20979  \

                    type      rsi14        obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  63.795032  6201181.0  285.092537  284.796876  \

                            bbm         bbu       bbb       bbp       adx
start_Time
2024-11-28 15:10:00  285.521704  286.246532  0.507722  0.829937  32.78406  \

                      psl  doji    zscore        hmid      hupper      hlower
start_Time
2024-11-28 15:10:00  50.0   0.0  1.637479  287.974278  289.338021  286.610535  \

                     imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  NaN           5097   ZOMATO-EQ
Symbol: 5049, Processed Data:                         open     high      low    close  volume  diff
start_Time
2024-11-28 15:10:00  1282.95  1283.95  1281.65  1282.95  4144.0   2.3  \

                          per  type      rsi14      obv        ema20
start_Time
2024-11-28 15:10:00  0.179456  down  40.222111 -43921.0  1284.690587  \

                             bbl          bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  1280.838525  1282.634521  1284.430516  0.280048  \

                          bbp        adx        psl   doji    zscore
start_Time
2024-11-28 15:10:00  0.225912  10.268128  41.666667  100.0 -1.213452  \

                            hmid      hupper       hlower  imi  symbol_number
start_Time
2024-11-28 15:10:00  1283.841107  1285.09008  1282.592133  NaN           5049  \

                    symbol_name
start_Time
2024-11-28 15:10:00    CLEAN-EQ
Symbol: 12018, Processed Data:                       open  high   low  close    volume  diff       per  type
start_Time
2024-11-28 15:10:00  63.73  63.8  63.7  63.73  264788.0   0.1  0.156986  down  \

                         rsi14        obv      ema20        bbl        bbm
start_Time
2024-11-28 15:10:00  40.819836  2569475.0  63.875791  63.589066  63.685896  \

                           bbu       bbb       bbp        adx        psl
start_Time
2024-11-28 15:10:00  63.782726  0.304085  0.572829  14.584776  16.666667  \

                      doji    zscore       hmid     hupper     hlower  imi
start_Time
2024-11-28 15:10:00  100.0 -1.484025  63.855126  64.045067  63.665186  NaN  \

                     symbol_number symbol_name
start_Time
2024-11-28 15:10:00          12018   SUZLON-EQ
Symbol: 12024, Processed Data:                        open   high    low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  689.85  690.7  688.0  689.55  2348.0   2.7  0.392442  \

                     type      rsi14     obv       ema20        bbl
start_Time
2024-11-28 15:10:00  down  40.227466 -8909.0  690.981511  686.14097  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  689.011231  691.881493  0.833154  0.323843  13.209545  \

                      psl  doji    zscore        hmid      hupper      hlower
start_Time
2024-11-28 15:10:00  50.0   0.0 -1.704595  690.480969  691.301081  689.660856  \

                     imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  NaN          12024      ACI-EQ

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 429 None

Error fetching data for 12092: DataFrame constructor not properly called!
Symbol: 12026, Processed Data:                       open   high    low  close   volume  diff      per  type
start_Time
2024-11-28 15:10:00  42.17  42.18  42.12  42.15  55431.0  0.06  0.14245  down  \

                         rsi14       obv      ema20        bbl        bbm
start_Time
2024-11-28 15:10:00  39.481724  329744.0  42.250152  42.086495  42.104384  \

                           bbu       bbb       bbp       adx        psl  doji
start_Time
2024-11-28 15:10:00  42.122273  0.084972  0.936481  19.93884  58.333333   0.0  \

                       zscore       hmid     hupper     hlower  imi
start_Time
2024-11-28 15:10:00 -0.933581  42.039308  42.183395  41.895221  NaN  \

                     symbol_number symbol_name
start_Time
2024-11-28 15:10:00          12026   RENUKA-EQ
Symbol: 12032, Processed Data:                       open    high     low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  657.3  657.95  656.35  656.95  13354.0   1.6  0.243772  \

                     type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  54.306225  343616.0  656.399488  654.038266  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  655.803486  657.568705  0.538338  0.654801  17.153463  \

                           psl  doji    zscore        hmid     hupper
start_Time
2024-11-28 15:10:00  58.333333   0.0  0.849583  657.458051  658.65077  \

                         hlower  imi  symbol_number  symbol_name
start_Time
2024-11-28 15:10:00  656.265332  NaN          12032  FIVESTAR-EQ
Error fetching data for 5373: DataFrame constructor not properly called!
Symbol: 5204, Processed Data:                        open   high    low  close   volume  diff       per
start_Time
2024-11-28 15:10:00  344.95  345.3  343.6  345.3  22990.0   1.7  0.494761  \

                    type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  32.488383  226112.0  349.720146  336.441686  \

                           bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  345.04852  353.655355  4.988768  0.415851  20.258401  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0 -2.417017  346.485369  348.474487  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  344.496251  NaN           5204  GMDCLTD-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number

Symbol: 5258, Processed Data:                       open    high    low  close   volume  diff       per
start_Time
2024-11-28 15:10:00  993.5  993.95  993.4  993.6  19444.0  0.55  0.055365  \

                    type    rsi14        obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  44.1706 -1009260.0  994.798794  991.136207  \

                            bbm         bbu       bbb       bbp       adx
start_Time
2024-11-28 15:10:00  992.848982  994.561758  0.345022  0.660855  12.01992  \

                      psl   doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  50.0  100.0 -0.991852  993.962523  996.265521  \

                         hlower  imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  991.659525  NaN           5258  INDUSINDBK-EQ
Symbol: 5265, Processed Data:                         open     high      low    close  volume  diff
start_Time
2024-11-28 15:10:00  1088.55  1088.55  1083.55  1083.55  1353.0   5.0  \

                          per  type      rsi14     obv        ema20
start_Time
2024-11-28 15:10:00  0.461446  down  63.386225  1017.0  1078.093425  \

                             bbl          bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  1075.532978  1080.063055  1084.593132  0.838854  \

                          bbp       adx        psl  doji    zscore
start_Time
2024-11-28 15:10:00  0.884866  73.28796  58.333333   0.0  2.194057  \

                            hmid       hupper       hlower  imi
start_Time
2024-11-28 15:10:00  1082.028601  1083.567225  1080.489976  NaN  \

                     symbol_number symbol_name
start_Time
2024-11-28 15:10:00           5265      GLS-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 5378, Processed Data:                        open    high     low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  679.45  680.35  679.25  680.35   385.0   1.1  0.161943  \

                    type      rsi14      obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  55.216833  11202.0  678.654614  675.449105  \

                            bbm         bbu      bbb       bbp      adx   psl
start_Time
2024-11-28 15:10:00  677.656365  679.863626  0.65144  0.860998  9.98646  50.0  \

                     doji    zscore        hmid     hupper      hlower  imi
start_Time
2024-11-28 15:10:00   0.0  0.974223  678.895949  680.96224  676.829658  NaN  \

                     symbol_number    symbol_name
start_Time
2024-11-28 15:10:00           5378  ASAHIINDIA-EQ
Symbol: 5385, Processed Data:                         open     high      low   close  volume  diff
start_Time
2024-11-28 15:10:00  1673.55  1673.55  1672.15  1673.2  1782.0   1.4  \

                          per  type      rsi14     obv        ema20
start_Time
2024-11-28 15:10:00  0.083725  down  50.473571 -3851.0  1673.113868  \

                             bbl          bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  1671.559629  1672.815973  1674.072317  0.150207  \

                          bbp        adx        psl  doji    zscore
start_Time
2024-11-28 15:10:00  0.234956  11.305265  33.333333   0.0  0.394286  \

                            hmid       hupper       hlower  imi
start_Time
2024-11-28 15:10:00  1673.791744  1675.427885  1672.155603  NaN  \

                     symbol_number symbol_name
start_Time
2024-11-28 15:10:00           5385    AAVAS-EQ
Symbol: 5426, Processed Data:                       open    high     low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  344.1  344.45  343.55  344.35   541.0   0.9  0.261971  \

                    type      rsi14     obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  44.111633  2974.0  345.126252  342.330943  \

                            bbm         bbu      bbb       bbp       adx
start_Time
2024-11-28 15:10:00  343.871073  345.411203  0.89576  0.395764  17.01882  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  33.333333   0.0 -1.244466  344.738178  345.594261  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  343.882095  NaN           5426   NUVOCO-EQ
Symbol: 5435, Processed Data:                        open   high    low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  316.85  317.0  316.2  316.85  6886.0   0.8  0.253004  \

                     type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  37.458043 -323460.0  317.566536  315.965702  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  316.678443  317.391184  0.450136  0.164364  16.148764  \

                      psl   doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  50.0  100.0 -1.513344  316.623238  317.053332  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  316.193145  NaN           5435    APTUS-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 429 None

Symbol: 5449, Processed Data:                       open   high    low  close  volume  diff       per  type
start_Time
2024-11-28 15:10:00  501.0  501.0  499.7  500.0  1865.0   1.3  0.260156  down  \

                         rsi14     obv       ema20         bbl         bbm
start_Time
2024-11-28 15:10:00  41.915279  4468.0  500.527277  499.649264  499.882502  \

                           bbu       bbb       bbp       adx        psl  doji
start_Time
2024-11-28 15:10:00  500.11574  0.093317  0.108764  9.741327  58.333333   0.0  \

                      zscore        hmid      hupper      hlower  imi
start_Time
2024-11-28 15:10:00 -0.98917  498.175748  500.204708  496.146788  NaN  \

                     symbol_number    symbol_name
start_Time
2024-11-28 15:10:00           5449  CHEMPLASTS-EQ
Symbol: 5475, Processed Data:                        open     high     low    close   volume  diff
start_Time
2024-11-28 15:10:00  1715.0  1722.75  1713.1  1721.55  22422.0  9.65  \

                          per type     rsi14       obv        ema20
start_Time
2024-11-28 15:10:00  0.563306   up  64.58019  124163.0  1707.711362  \

                             bbl          bbm          bbu      bbb       bbp
start_Time
2024-11-28 15:10:00  1700.292092  1708.231866  1716.171639  0.92959  0.806566  \

                          adx        psl  doji    zscore         hmid
start_Time
2024-11-28 15:10:00  18.70266  58.333333   0.0  2.165518  1713.887965  \

                          hupper       hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  1720.219055  1707.556875  NaN           5475     GRSE-EQ
Symbol: 5585, Processed Data:                         open     high     low    close  volume  diff
start_Time
2024-11-28 15:10:00  1166.25  1166.75  1161.0  1163.95  2211.0  5.75  \

                          per  type      rsi14      obv        ema20
start_Time
2024-11-28 15:10:00  0.495263  down  56.890458 -13019.0  1160.759057  \

                            bbl          bbm          bbu       bbb       bbp
start_Time
2024-11-28 15:10:00  1157.99288  1159.651313  1161.309746  0.286023  0.906615  \

                          adx   psl  doji    zscore         hmid      hupper
start_Time
2024-11-28 15:10:00  22.58807  50.0   0.0  1.832706  1160.504923  1162.46564  \

                          hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  1158.544206  NaN           5585   VIJAYA-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Error fetching data for 5701: DataFrame constructor not properly called!
Symbol: 12489, Processed Data:                       open   high    low  close  volume  diff       per type
start_Time
2024-11-28 15:10:00  489.0  490.1  488.5  489.6  5783.0   1.6  0.327533   up  \

                         rsi14      obv       ema20         bbl         bbm
start_Time
2024-11-28 15:10:00  49.890801  23900.0  489.522803  487.084432  488.765622  \

                            bbu       bbb       bbp        adx        psl
start_Time
2024-11-28 15:10:00  490.446812  0.687933  0.421002  17.762619  58.333333  \

                     doji   zscore        hmid      hupper      hlower  imi
start_Time
2024-11-28 15:10:00   0.0  0.20805  490.733215  491.991283  489.475147  NaN  \

                     symbol_number symbol_name
start_Time
2024-11-28 15:10:00          12489  SWSOLAR-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 429 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name

Symbol: 5633, Processed Data:                       open   high   low  close   volume  diff      per type
start_Time
2024-11-28 15:10:00  97.19  97.25  97.1   97.2  21607.0  0.15  0.15448   up  \

                         rsi14       obv      ema20       bbl        bbm
start_Time
2024-11-28 15:10:00  47.609643 -578417.0  97.237185  96.93422  97.085164  \

                           bbu       bbb       bbp        adx        psl
start_Time
2024-11-28 15:10:00  97.236107  0.310951  0.549145  12.537002  41.666667  \

                      doji    zscore      hmid     hupper     hlower  imi
start_Time
2024-11-28 15:10:00  100.0 -0.412318  97.26789  97.579458  96.956321  NaN  \

                     symbol_number symbol_name
start_Time
2024-11-28 15:10:00           5633  J&KBANK-EQ
Symbol: 5748, Processed Data:                         open    high      low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  1859.05  1859.6  1855.95  1857.8   378.0  3.65  0.196665  \

                     type      rsi14      obv       ema20          bbl
start_Time
2024-11-28 15:10:00  down  51.879358 -18267.0  1856.64122  1851.223445  \

                             bbm          bbu       bbb       bbp       adx
start_Time
2024-11-28 15:10:00  1854.256331  1857.289218  0.327127  0.779217  13.79514  \

                           psl  doji    zscore        hmid       hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0  0.809877  1859.66533  1863.209827  \

                          hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  1856.120834  NaN           5748   CYIENT-EQ
Symbol: 5610, Processed Data:                        open    high     low    close  volume  diff       per
start_Time
2024-11-28 15:10:00  6509.0  6509.0  6500.0  6506.55   447.0   9.0  0.138462  \

                     type      rsi14     obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  57.892311  1813.0  6496.818189  6487.258948  \

                             bbm          bbu       bbb       bbp       adx
start_Time
2024-11-28 15:10:00  6496.931713  6506.604479  0.297764  0.658604  24.94213  \

                           psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0  0.796836  6524.602852  6548.266439  \

                          hlower  imi  symbol_number  symbol_name
start_Time
2024-11-28 15:10:00  6500.939264  NaN           5610  ASTRAZEN-EQ
Error fetching data for 13035: DataFrame constructor not properly called!

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 5926, Processed Data:                       open    high    low  close  volume  diff       per
start_Time
2024-11-28 15:10:00  718.9  719.35  717.6  718.1   987.0  1.75  0.243868  \

                     type      rsi14      obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  37.741795  52613.0  720.623319  715.003989  \

                            bbm         bbu       bbb       bbp       adx
start_Time
2024-11-28 15:10:00  717.976127  720.948264  0.827921  0.436725  17.33033  \

                           psl  doji    zscore       hmid      hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0 -2.211705  720.49598  722.445437  \

                         hlower  imi  symbol_number   symbol_name
start_Time
2024-11-28 15:10:00  718.546522  NaN           5926  INTELLECT-EQ
Symbol: 5900, Processed Data:                        open    high      low    close    volume  diff
start_Time
2024-11-28 15:10:00  1132.0  1132.1  1131.25  1131.75  143520.0  0.85  \

                          per  type      rsi14       obv        ema20
start_Time
2024-11-28 15:10:00  0.075138  down  40.879241 -115855.0  1133.490055  \

                             bbl          bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  1130.394054  1131.526132  1132.658209  0.200097  \

                          bbp        adx        psl  doji    zscore
start_Time
2024-11-28 15:10:00  0.378042  23.935857  33.333333   0.0 -0.795595  \

                           hmid       hupper       hlower  imi  symbol_number
start_Time
2024-11-28 15:10:00  1132.66223  1134.833188  1130.491272  NaN           5900  \

                     symbol_name
start_Time
2024-11-28 15:10:00  AXISBANK-EQ
Symbol: 6066, Processed Data:                       open   high    low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  809.0  809.9  806.5  806.95  93630.0   3.4  0.421575  \

                     type      rsi14        obv       ema20        bbl
start_Time
2024-11-28 15:10:00  down  60.078644  5743723.0  800.246037  793.75717  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  801.557836  809.358503  1.946376  0.816778  25.340832  \

                      psl  doji    zscore        hmid      hupper      hlower
start_Time
2024-11-28 15:10:00  75.0   0.0  1.699916  805.022757  810.304452  799.741062  \

                     imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  NaN           6066     ATGL-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 13086, Processed Data:                        open    high      low   close  volume   diff       per
start_Time
2024-11-28 15:10:00  3485.0  3487.0  3475.25  3479.9   578.0  11.75  0.338105  \

                     type      rsi14    obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  59.186889  402.0  3476.396797  3473.530484  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  3475.941293  3478.352102  0.138714  0.356626  14.854201  \

                           psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  66.666667   0.0  1.482502  3483.110916  3485.431718  \

                          hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  3480.790114  NaN          13086   AIAENG-EQ  Symbol: 13061, Processed Data:                        open     high      low    close   volume  diff
start_Time
2024-11-28 15:10:00  1123.1  1129.85  1121.75  1129.15  28161.0   8.1  \

                          per type      rsi14       obv        ema20
start_Time
2024-11-28 15:10:00  0.722086   up  70.927214  125081.0  1115.445915  \

                             bbl          bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  1108.827933  1116.592828  1124.357724  1.390819  \

                          bbp        adx        psl  doji    zscore
start_Time
2024-11-28 15:10:00  0.832082  17.760783  66.666667   0.0  2.640325  \

                            hmid       hupper       hlower  imi
start_Time
2024-11-28 15:10:00  1127.594088  1130.961337  1124.226839  NaN  \

                     symbol_number symbol_name
start_Time
2024-11-28 15:10:00          13061   360ONE-EQ

Symbol: 13081, Processed Data:                       open   high    low  close  volume  diff       per  type
start_Time
2024-11-28 15:10:00  393.3  393.5  392.5  392.5  3396.0   1.0  0.254777  down  \

                         rsi14      obv       ema20         bbl         bbm
start_Time
2024-11-28 15:10:00  43.359788  25080.0  393.245856  392.361721  392.488212  \

                            bbu       bbb       bbp       adx   psl  doji
start_Time
2024-11-28 15:10:00  392.614703  0.064456  0.546596  8.701053  50.0   0.0  \

                       zscore       hmid      hupper      hlower  imi
start_Time
2024-11-28 15:10:00 -1.284474  392.94868  393.578931  392.318428  NaN  \

                     symbol_number symbol_name
start_Time
2024-11-28 15:10:00          13081  TRIVENI-EQ
Symbol: 13147, Processed Data:                         open     high      low    close  volume  diff
start_Time
2024-11-28 15:10:00  1516.55  1517.95  1514.65  1516.65  4044.0   3.3  \

                          per type      rsi14      obv        ema20
start_Time
2024-11-28 15:10:00  0.217872   up  49.613194  67501.0  1517.426791  \

                             bbl          bbm          bbu      bbb       bbp
start_Time
2024-11-28 15:10:00  1512.254509  1515.816755  1519.379002  0.47001  0.336233  \

                           adx        psl   doji    zscore         hmid
start_Time
2024-11-28 15:10:00  17.709667  41.666667  100.0  0.085412  1523.483732  \

                          hupper       hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  1529.971311  1516.996153  NaN          13147  PVRINOX-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name

Symbol: 13197, Processed Data:                        open   high    low  close  volume  diff       per type
start_Time
2024-11-28 15:10:00  346.65  346.8  346.6  346.8  1384.0   0.2  0.057703   up  \

                         rsi14       obv       ema20         bbl         bbm
start_Time
2024-11-28 15:10:00  54.556622  424845.0  346.541363  345.611315  346.682016  \

                            bbu       bbb     bbp        adx   psl  doji
start_Time
2024-11-28 15:10:00  347.752717  0.617685  0.4617  37.793378  50.0   0.0  \

                       zscore        hmid      hupper      hlower  imi
start_Time
2024-11-28 15:10:00  0.761913  348.026655  348.619244  347.434065  NaN  \

                     symbol_number symbol_name
start_Time
2024-11-28 15:10:00          13197     GSPL-EQ
Symbol: 6364, Processed Data:                        open    high     low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  248.75  248.95  248.66  248.75  96514.0  0.29  0.116625  \

                     type      rsi14        obv       ema20       bbl
start_Time
2024-11-28 15:10:00  down  51.122733  4256815.0  248.662668  247.7219  \

                            bbm         bbu       bbb      bbp        adx
start_Time
2024-11-28 15:10:00  248.367699  249.013498  0.520034  0.72631  12.430155  \

                      psl   doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  50.0  100.0  0.377602  248.762014  249.367575  \

                         hlower  imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  248.156452  NaN           6364  NATIONALUM-EQ
Symbol: 13260, Processed Data:                        open    high      low    close   volume  diff
start_Time
2024-11-28 15:10:00  1054.1  1055.9  1053.25  1054.55  30108.0  2.65  \

                          per type      rsi14       obv        ema20
start_Time
2024-11-28 15:10:00  0.251602   up  49.807552  105680.0  1053.882851  \

                             bbl          bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  1050.969923  1052.349198  1053.728474  0.262133  \

                          bbp       adx   psl  doji   zscore         hmid
start_Time
2024-11-28 15:10:00  0.826549  9.373251  50.0   0.0  0.21055  1050.129867  \

                          hupper       hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  1054.614694  1045.645039  NaN          13260      KEC-EQ
Symbol: 13270, Processed Data:                         open     high      low    close  volume  diff
start_Time
2024-11-28 15:10:00  4121.65  4132.05  4121.65  4130.95   696.0  10.4  \

                          per type      rsi14     obv        ema20
start_Time
2024-11-28 15:10:00  0.252326   up  54.595845 -3438.0  4122.931919  \

                             bbl          bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  4111.394153  4118.223033  4125.051913  0.331642  \

                          bbp        adx   psl  doji    zscore         hmid
start_Time
2024-11-28 15:10:00  0.750917  20.528748  50.0   0.0  1.318266  4131.600741  \

                          hupper       hlower  imi  symbol_number  symbol_name
start_Time
2024-11-28 15:10:00  4139.797604  4123.403879  NaN          13270  JKCEMENT-EQ

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name

Symbol: 13285, Processed Data:                       open    high    low  close   volume  diff       per
start_Time
2024-11-28 15:10:00  271.0  271.45  270.9  271.4  12588.0  0.55  0.203027  \

                    type      rsi14      obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  50.014766 -71824.0  271.233362  270.397824  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  270.683481  270.969138  0.211064  0.878984  15.487024  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  58.333333   0.0 -0.085635  270.930941  271.397333  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  270.464549  NaN          13285   M&MFIN-EQ
Symbol: 13305, Processed Data:                       open   high    low  close  volume  diff       per type
start_Time
2024-11-28 15:10:00  733.0  734.0  732.2  733.4  1160.0   1.8  0.245834   up  \

                         rsi14     obv       ema20         bbl         bbm
start_Time
2024-11-28 15:10:00  55.839355  2720.0  732.312109  731.664827  732.157168  \

                            bbu       bbb       bbp        adx        psl
start_Time
2024-11-28 15:10:00  732.649509  0.134491  0.543498  27.336689  41.666667  \

                     doji    zscore        hmid      hupper      hlower  imi
start_Time
2024-11-28 15:10:00   0.0  1.054936  736.824704  739.112295  734.537112  NaN  \

                     symbol_number    symbol_name
start_Time
2024-11-28 15:10:00          13305  CENTURYPLY-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 13310, Processed Data:                        open    high     low    close  volume  diff      per
start_Time
2024-11-28 15:10:00  4304.6  4304.6  4300.6  4301.05  1058.0   4.0  0.09301  \

                     type      rsi14      obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  47.214607  12284.0  4302.237004  4298.838882  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  4299.922211  4301.005539  0.050388  0.812827  13.058054  \

                      psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  50.0   0.0  0.061793  4301.291684  4305.448165  \

                          hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  4297.135204  NaN          13310      KEI-EQ  Symbol: 13359, Processed Data:                         open     high     low    close  volume  diff
start_Time
2024-11-28 15:10:00  1159.95  1160.55  1157.5  1157.65  4096.0  3.05  \

                          per  type     rsi14       obv        ema20
start_Time
2024-11-28 15:10:00  0.263499  down  53.31796  111829.0  1156.949887  \

                             bbl          bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  1155.046474  1156.451608  1157.856741  0.243008  \

                          bbp        adx   psl  doji    zscore         hmid
start_Time
2024-11-28 15:10:00  0.873058  20.420051  50.0   0.0  0.879252  1160.685799  \

                          hupper       hlower  imi  symbol_number  symbol_name
start_Time
2024-11-28 15:10:00  1163.307734  1158.063864  NaN          13359  KFINTECH-EQ

Symbol: 13332, Processed Data:                         open     high      low     close  volume  diff
start_Time
2024-11-28 15:10:00  10843.6  10895.0  10837.8  10885.95  2705.0  57.2  \

                          per type      rsi14     obv         ema20
start_Time
2024-11-28 15:10:00  0.527782   up  57.871874  9841.0  10836.285144  \

                              bbl           bbm           bbu       bbb
start_Time
2024-11-28 15:10:00  10785.736709  10831.875526  10878.014342  0.851908  \

                          bbp        adx        psl  doji    zscore
start_Time
2024-11-28 15:10:00  0.564203  30.856602  41.666667   0.0  1.154371  \

                             hmid        hupper        hlower  imi
start_Time
2024-11-28 15:10:00  10943.522473  11019.293799  10867.751147  NaN  \

                     symbol_number   symbol_name
start_Time
2024-11-28 15:10:00          13332  SOLARINDS-EQ

Retrying 23 symbols with errors...

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 1621, Processed Data:                         open     high      low    close  volume  diff
start_Time
2024-11-28 15:10:00  6696.35  6700.85  6670.25  6674.95   170.0  30.6  \

                          per  type      rsi14    obv        ema20
start_Time
2024-11-28 15:10:00  0.458753  down  47.293008  235.0  6679.927228  \

                             bbl          bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  6656.463967  6664.713428  6672.962889  0.247556  \

                          bbp        adx   psl  doji    zscore         hmid
start_Time
2024-11-28 15:10:00  0.835572  18.029151  50.0   0.0 -0.789752  6672.041685  \

                          hupper       hlower  imi  symbol_number
start_Time
2024-11-28 15:10:00  6678.896022  6665.187349  NaN           1621  \

                       symbol_name
start_Time
2024-11-28 15:10:00  TATAINVEST-EQ  Symbol: 2181, Processed Data:                         open     high      low    close  volume  diff
start_Time
2024-11-28 15:10:00  34609.3  34650.0  34603.4  34607.9   304.0  46.6  \

                          per  type      rsi14    obv         ema20
start_Time
2024-11-28 15:10:00  0.134669  down  35.674377  573.0  34706.340396  \

                              bbl          bbm           bbu       bbb
start_Time
2024-11-28 15:10:00  34534.491847  34614.19058  34693.889312  0.460497  \

                          bbp        adx        psl   doji   zscore
start_Time
2024-11-28 15:10:00  0.432304  12.322636  41.666667  100.0 -2.40668  \

                            hmid        hupper        hlower  imi
start_Time
2024-11-28 15:10:00  34670.74334  34718.136543  34623.350136  NaN  \

                     symbol_number  symbol_name
start_Time
2024-11-28 15:10:00           2181  BOSCHLTD-EQ

Symbol: 1814, Processed Data:                         open     high      low   close  volume  diff
start_Time
2024-11-28 15:10:00  1142.15  1144.75  1142.05  1144.1  2127.0   2.7  \

                          per type      rsi14      obv        ema20
start_Time
2024-11-28 15:10:00  0.236417   up  54.052322  90042.0  1142.041131  \

                             bbl         bbm          bbu       bbb       bbp
start_Time
2024-11-28 15:10:00  1135.746001  1139.73298  1143.719959  0.699634  0.790573  \

                           adx        psl  doji    zscore         hmid
start_Time
2024-11-28 15:10:00  15.906354  58.333333   0.0  0.460337  1141.459275  \

                          hupper       hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  1143.774773  1139.143777  NaN           1814     KPIL-EQ
Symbol: 2303, Processed Data:                        open    high     low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  4465.5  4470.0  4464.1  4468.4  8929.0   5.9  0.132165  \

                    type      rsi14      obv        ema20          bbl
start_Time
2024-11-28 15:10:00   up  41.970937  58554.0  4474.944478  4455.750756  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  4465.051809  4474.352863  0.416616  0.448833  15.416175  \

                      psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  25.0   0.0 -1.242856  4468.282446  4474.103302  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  4462.46159  NaN           2303      HAL-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 2792, Processed Data:                       open   high    low  close    volume  diff       per
start_Time
2024-11-28 15:10:00  32.64  32.78  32.64  32.73  356398.0  0.14  0.428922  \

                    type      rsi14       obv      ema20        bbl
start_Time
2024-11-28 15:10:00   up  45.526564  798439.0  32.877504  31.015141  \

                           bbm        bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  32.386704  33.758266  8.469912  0.592339  27.439957  \

                      psl  doji    zscore       hmid     hupper     hlower
start_Time
2024-11-28 15:10:00  50.0   0.0 -0.886848  32.610756  32.951846  32.269666  \

                     imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  NaN           2792  EASEMYTRIP-EQ  Symbol: 2783, Processed Data:                       open   high    low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  744.0  745.0  743.0  743.95   900.0   2.0  0.269179  \

                     type      rsi14      obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  58.105457  20467.0  740.936098  739.056109  \

                            bbm         bbu       bbb       bbp       adx
start_Time
2024-11-28 15:10:00  741.937359  744.818609  0.776683  0.684406  21.50847  \

                           psl   doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  41.666667  100.0  1.249497  743.394428  747.056246  \

                         hlower  imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  739.732609  NaN           2783  JUBLINGREA-EQ

Symbol: 2866, Processed Data:                        open    high    low  close   volume  diff      per
start_Time
2024-11-28 15:10:00  172.35  172.52  172.2  172.2  75240.0  0.32  0.18583  \

                     type     rsi14        obv      ema20         bbl
start_Time
2024-11-28 15:10:00  down  48.02724  1003802.0  172.35157  171.912259  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  172.133673  172.355087  0.257258  0.649781  11.589878  \

                      psl  doji    zscore        hmid      hupper      hlower
start_Time
2024-11-28 15:10:00  50.0   0.0 -0.310552  173.145218  173.996289  172.294147  \

                     imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  NaN           2866      RCF-EQ
Symbol: 2649, Processed Data:                       open    high    low  close   volume  diff       per
start_Time
2024-11-28 15:10:00  431.5  431.95  430.8  431.0  29276.0  1.15  0.266945  \

                     type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  49.284015 -138379.0  431.239212  430.140645  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  431.379031  432.617417  0.574152  0.266215  26.293521  \

                      psl  doji    zscore        hmid      hupper     hlower
start_Time
2024-11-28 15:10:00  50.0   0.0  0.410192  432.356428  433.479706  431.23315  \

                     imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  NaN           2649     PCBL-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 3345, Processed Data:                         open     high      low   close  volume  diff
start_Time
2024-11-28 15:10:00  1164.75  1164.75  1160.35  1161.3  1060.0   4.4  \

                          per  type      rsi14     obv        ema20
start_Time
2024-11-28 15:10:00  0.379196  down  50.856306 -1491.0  1161.370532  \

                             bbl          bbm          bbu      bbb       bbp
start_Time
2024-11-28 15:10:00  1159.400548  1160.166315  1160.932083  0.13201  0.619935  \

                           adx        psl  doji    zscore        hmid
start_Time
2024-11-28 15:10:00  16.217326  41.666667   0.0  0.262205  1162.40578  \

                          hupper       hlower  imi  symbol_number
start_Time
2024-11-28 15:10:00  1163.590777  1161.220783  NaN           3345  \

                       symbol_name
start_Time
2024-11-28 15:10:00  SUNDRMFAST-EQ
Symbol: 3351, Processed Data:                        open     high     low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  1733.6  1735.15  1732.1  1733.1  31142.0  3.05  0.176087  \

                     type      rsi14      obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  47.894518 -43017.0  1734.492447  1728.836121  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  1731.659877  1734.483634  0.326133  0.577932  18.894692  \

                      psl   doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  25.0  100.0 -0.315303  1734.840509  1740.151641  \

                          hlower  imi  symbol_number   symbol_name
start_Time
2024-11-28 15:10:00  1729.529378  NaN           3351  SUNPHARMA-EQ
Symbol: 3363, Processed Data:                         open     high      low    close  volume  diff
start_Time
2024-11-28 15:10:00  4534.45  4534.45  4521.15  4532.05  2964.0  13.3  \

                          per  type      rsi14      obv        ema20
start_Time
2024-11-28 15:10:00  0.294173  down  39.946762 -12462.0  4547.742226  \

                             bbl          bbm          bbu       bbb
start_Time
2024-11-28 15:10:00  4494.885904  4526.677815  4558.469726  1.404647  \

                          bbp        adx        psl  doji    zscore
start_Time
2024-11-28 15:10:00  0.413063  24.481025  33.333333   0.0 -2.176916  \

                           hmid       hupper     hlower  imi  symbol_number
start_Time
2024-11-28 15:10:00  4538.71054  4548.057881  4529.3632  NaN           3363  \

                       symbol_name
start_Time
2024-11-28 15:10:00  SUPREMEIND-EQ
Symbol: 3721, Processed Data:                         open    high     low   close  volume  diff      per
start_Time
2024-11-28 15:10:00  1744.65  1746.7  1744.4  1746.7  4042.0   2.3  0.13185  \

                    type      rsi14      obv        ema20          bbl
start_Time
2024-11-28 15:10:00   up  56.547224  46621.0  1743.598674  1738.767702  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  1742.537583  1746.307464  0.432689  0.747013  12.993355  \

                           psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  66.666667   0.0  0.899591  1744.444545  1750.023916  \

                          hlower  imi  symbol_number  symbol_name
start_Time
2024-11-28 15:10:00  1738.865174  NaN           3721  TATACOMM-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 4204, Processed Data:                        open   high    low   close    volume  diff       per
start_Time
2024-11-28 15:10:00  161.84  161.9  161.7  161.72  259506.0   0.2  0.123686  \

                     type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  47.667917  255449.0  161.838571  161.345248  \

                           bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  161.65776  161.970273  0.386635  0.567581  35.507791  \

                      psl  doji    zscore        hmid      hupper      hlower
start_Time
2024-11-28 15:10:00  50.0   0.0  0.004134  162.300723  162.787967  161.813478  \

                     imi  symbol_number   symbol_name
start_Time
2024-11-28 15:10:00  NaN           4204  MOTHERSON-EQ
Symbol: 4067, Processed Data:                       open   high     low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  645.1  645.9  645.05  645.15  43480.0  0.85  0.131773  \

                    type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  30.543837 -554397.0  649.039602  642.127058  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  645.622999  649.118939  1.082967  0.418048  25.902225  \

                           psl   doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  41.666667  100.0 -1.767837  643.510668  645.724498  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  641.296839  NaN           4067   MARICO-EQ
Symbol: 10793, Processed Data:                        open    high     low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  582.35  582.95  581.55  581.55  17819.0   1.4  0.240736  \

                     type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  68.610441  286384.0  577.108742  575.916327  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  579.258782  582.601236  1.154045  0.842745  17.375604  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  58.333333   0.0  2.028548  582.606808  584.070081  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  581.143535  NaN          10793    SYRMA-EQ
Symbol: 11253, Processed Data:                        open    high     low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  151.25  151.25  150.74  150.99  6133.0  0.51  0.338331  \

                     type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  36.501751 -221728.0  151.476424  150.523535  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  150.964189  151.404843  0.583786  0.245617  18.945511  \

                      psl  doji    zscore        hmid      hupper      hlower
start_Time
2024-11-28 15:10:00  25.0   0.0 -1.923923  151.197431  151.440311  150.954551  \

                     imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  NaN          11253  WELSPUNLIV-EQ

/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None

Symbol: 11287, Processed Data:                       open    high     low  close   volume  diff       per
start_Time
2024-11-28 15:10:00  546.9  547.95  546.35  547.2  44386.0   1.6  0.292853  \

                    type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  41.831082  523897.0  548.590896  544.730534  \

                            bbm         bbu      bbb       bbp        adx
start_Time
2024-11-28 15:10:00  546.333531  547.936528  0.58682  0.505137  16.529915  \

                           psl  doji   zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0 -1.40222  548.203075  550.240622  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  546.165527  NaN          11287      UPL-EQ
Symbol: 11872, Processed Data:                        open   high     low  close   volume  diff       per
start_Time
2024-11-28 15:10:00  583.55  584.7  583.35  584.6  16983.0  1.35  0.231422  \

                    type     rsi14       obv      ema20         bbl
start_Time
2024-11-28 15:10:00   up  54.59512  417234.0  583.57394  581.069294  \

                            bbm         bbu       bbb      bbp       adx
start_Time
2024-11-28 15:10:00  582.866625  584.663957  0.616721  0.63447  16.97968  \

                           psl  doji   zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  58.333333   0.0  0.68263  582.888515  585.091447  \

                         hlower  imi  symbol_number  symbol_name
start_Time
2024-11-28 15:10:00  580.685584  NaN          11872  GRANULES-EQ
Symbol: 11364, Processed Data:                        open    high     low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  285.15  285.15  284.25  284.25  4165.0   0.9  0.316623  \

                     type      rsi14     obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  38.102789  8379.0  285.708971  283.805104  \

                            bbm         bbu       bbb       bbp       adx
start_Time
2024-11-28 15:10:00  284.935767  286.066431  0.793627  0.196741  9.582253  \

                           psl  doji    zscore        hmid      hupper
start_Time
2024-11-28 15:10:00  41.666667   0.0 -2.881961  285.385862  285.935083  \

                         hlower  imi  symbol_number    symbol_name
start_Time
2024-11-28 15:10:00  284.836641  NaN          11364  VAIBHAVGBL-EQ
Symbol: 12092, Processed Data:                        open    high     low    close  volume  diff       per
start_Time
2024-11-28 15:10:00  5862.1  5865.0  5840.7  5841.25  1601.0  24.3  0.416046  \

                     type     rsi14     obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  41.90067  2754.0  5852.514132  5826.194689  \

                             bbm          bbu       bbb      bbp        adx
start_Time
2024-11-28 15:10:00  5835.931752  5845.668815  0.333694  0.74485  13.418236  \

                           psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  33.333333   0.0 -1.307538  5836.281994  5845.936758  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  5826.62723  NaN          12092   KAYNES-EQ

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/intraday HTTP/1.1" 200 None
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time1_last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_number'] = symbol_number
/var/folders/ms/m56fth2536zgjlgb2wr1yf5m0000gn/T/ipykernel_1247/490138063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_line['symbol_name'] = symbol_name

Symbol: 5373, Processed Data:                        open    high     low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  166.06  166.36  165.76  165.86  10276.0   0.6  0.361969  \

                     type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00  down  53.331476  285307.0  165.698498  165.244545  \

                            bbm         bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  165.524831  165.805116  0.338663  0.919518  13.438461  \

                           psl  doji    zscore       hmid     hupper
start_Time
2024-11-28 15:10:00  58.333333   0.0  0.154395  165.51729  165.77249  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  165.262089  NaN           5373  DEVYANI-EQ
Symbol: 5701, Processed Data:                        open    high    low   close   volume  diff       per
start_Time
2024-11-28 15:10:00  178.92  179.35  178.9  179.19  43212.0  0.45  0.251537  \

                    type      rsi14       obv       ema20         bbl
start_Time
2024-11-28 15:10:00   up  41.252816  231568.0  179.732282  178.344287  \

                            bbm         bbu      bbb       bbp        adx
start_Time
2024-11-28 15:10:00  179.091869  179.839452  0.83486  0.371673  14.218515  \

                           psl  doji    zscore       hmid      hupper
start_Time
2024-11-28 15:10:00  33.333333   0.0 -1.603629  179.44495  179.807645  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  179.082255  NaN           5701      CUB-EQ
Symbol: 13035, Processed Data:                        open     high     low   close  volume  diff       per
start_Time
2024-11-28 15:10:00  2525.6  2527.25  2523.3  2525.0   258.0  3.95  0.156541  \

                     type      rsi14     obv        ema20          bbl
start_Time
2024-11-28 15:10:00  down  49.106222  4690.0  2526.104849  2520.411421  \

                             bbm          bbu       bbb       bbp        adx
start_Time
2024-11-28 15:10:00  2523.341677  2526.271933  0.232252  0.492888  26.008373  \

                      psl  doji    zscore         hmid       hupper
start_Time
2024-11-28 15:10:00  50.0   0.0 -0.143865  2527.078846  2530.287972  \

                         hlower  imi  symbol_number symbol_name
start_Time
2024-11-28 15:10:00  2523.86972  NaN          13035   SAFARI-EQ

All symbols processed successfully without errors.


Total time taken: 30.15 seconds

In [70]:
rsi=tim1_decide_file.sort_values(by='rsi14',ascending=True).head(5)
(rsi)

,open,high,low,close,volume,diff,per,type,rsi14,obv,ema20,bbl,bbm,bbu,bbb,bbp,adx,psl,doji,zscore,hmid,hupper,hlower,imi,symbol_number,symbol_name
start_Time,,,,,,,,,,,,,,,,,,,,,,,,,,
2024-11-28 15:12:00,515.75,515.85,515.75,515.85,128.0,0.10,0.019389,up,26.838725,-33694.0,516.978620,515.667419,515.998478,516.329537,0.128318,0.124722,16.326723,33.333333,0.0,-2.110321,515.644270,515.950961,515.337579,NaN,31163,RHIM-EQ
2024-11-28 15:12:00,1091.25,1092.90,1091.00,1091.00,156.0,1.90,0.174152,down,27.698535,-11578.0,1097.052304,1089.431521,1092.783296,1096.135072,0.613438,0.233977,21.422240,25.000000,100.0,-3.122928,1094.268389,1095.939131,1092.597648,NaN,2056,HOMEFIRST-EQ
2024-11-28 15:11:00,917.30,917.30,917.30,917.30,2.0,0.00,0.000000,down,28.547415,-6160.0,919.238406,916.959199,917.570427,918.181656,0.133228,0.278784,22.660672,16.666667,100.0,-2.142151,917.242035,917.824914,916.659157,NaN,11256,JAIBALAJI-EQ
2024-11-28 15:12:00,1061.95,1062.85,1061.60,1062.10,45.0,1.25,0.117747,up,28.550298,40271.0,1064.721262,1060.524827,1063.226974,1065.929121,0.508292,0.198948,35.903250,50.000000,0.0,-3.292797,1063.423491,1063.930183,1062.916798,NaN,10925,GODREJIND-EQ
2024-11-28 15:12:00,769.25,769.70,769.25,769.25,507.0,0.45,0.058499,down,30.149560,66457.0,770.532942,768.399917,769.123796,769.847674,0.188235,0.587172,25.716490,33.333333,100.0,-1.408136,768.171140,768.911990,767.430290,NaN,11821,WELCORP-EQ

In [71]:
zscore=tim1_decide_file.sort_values(by='zscore',ascending=True).head(5)
(zscore)

,open,high,low,close,volume,diff,per,type,rsi14,obv,ema20,bbl,bbm,bbu,bbb,bbp,adx,psl,doji,zscore,hmid,hupper,hlower,imi,symbol_number,symbol_name
start_Time,,,,,,,,,,,,,,,,,,,,,,,,,,
2024-11-28 15:12:00,1087.20,1087.20,1087.20,1087.20,2073.0,0.00,0.000000,down,53.526247,196562.0,1087.200000,1087.200000,1087.200000,1087.200000,2.042353e-17,1024.000000,4.804745,0.000000,0.0,-inf,1087.199490,1087.200120,1087.198859,NaN,3563,ADANIGREEN-EQ
2024-11-28 15:12:00,1061.95,1062.85,1061.60,1062.10,45.0,1.25,0.117747,up,28.550298,40271.0,1064.721262,1060.524827,1063.226974,1065.929121,5.082917e-01,0.198948,35.903250,50.000000,0.0,-3.292797,1063.423491,1063.930183,1062.916798,NaN,10925,GODREJIND-EQ
2024-11-28 15:12:00,1091.25,1092.90,1091.00,1091.00,156.0,1.90,0.174152,down,27.698535,-11578.0,1097.052304,1089.431521,1092.783296,1096.135072,6.134383e-01,0.233977,21.422240,25.000000,100.0,-3.122928,1094.268389,1095.939131,1092.597648,NaN,2056,HOMEFIRST-EQ
2024-11-28 15:12:00,3039.60,3040.50,3033.15,3033.20,17230.0,7.35,0.242322,down,31.775034,-119149.0,3043.723601,3029.980721,3038.467793,3046.954866,5.586416e-01,0.186712,13.412543,41.666667,0.0,-3.117461,3041.683279,3045.755442,3037.611115,NaN,4306,SHRIRAMFIN-EQ
2024-11-28 15:12:00,284.25,284.25,284.25,284.25,12.0,0.00,0.000000,down,30.970597,-55.0,285.435171,283.791154,284.701977,285.612801,6.398437e-01,0.251885,16.460860,25.000000,100.0,-2.840369,285.158040,285.570792,284.745289,NaN,11364,VAIBHAVGBL-EQ

In [72]:
bb=tim1_decide_file[tim1_decide_file['close']<tim1_decide_file['bbl']]
(bb)

Empty DataFrame
Columns: [open, high, low, close, volume, diff, per, type, rsi14, obv, ema20, bbl, bbm, bbu, bbb, bbp, adx, psl, doji, zscore, hmid, hupper, hlower, imi, symbol_number, symbol_name]
Index: []

In [73]:
sh_work(1,zscore)

DEBUG:NorenRestApiPy.NorenApi:https://api.shoonya.com/NorenWClientTP//Limits
DEBUG:NorenRestApiPy.NorenApi:jData={"uid": "FA194273", "actid": "FA194273"}&jKey=ae0da790f566b2ef45911882d65b0103d142db949596068b3f8e71510082c6f5
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.shoonya.com:443
DEBUG:urllib3.connectionpool:https://api.shoonya.com:443 "POST /NorenWClientTP//Limits HTTP/1.1" 200 562
DEBUG:NorenRestApiPy.NorenApi:{"request_time":"15:13:02 28-11-2024","stat":"Ok","prfname":"SHOONYA","cash":"10321.70","payin":"0.00","payout":"0.00","brkcollamt":"0.00","unclearedcash":"0.00","aux_daycash":"0.00","aux_brkcollamt":"0.00","aux_unclearedcash":"0.00","daycash":"0.00","turnoverlmt":"999999999999.00","pendordvallmt":"999999999999.00","remarks_amt":"0.00","turnover":"800557.50","marginused":"869.75","peak_mar":"8250.64","mtomcurper":"7.73","margincurper":"8.43","rpnl":"797.50","brokerage":"72.25","rzpnl_e_i":"797.50","brkage_e_i":"72.25","blk_amt":"0.00","mr_der_a":"6812.32"}
DEBUG:NorenRestApiPy.NorenApi:https://api.shoonya.com/NorenWClientTP//PlaceOrder
DEBUG:NorenRestApiPy.NorenApi:jData={"ordersource": "API", "uid": "FA194273", "actid": "FA194273", "trantype": "B", "prd": "I", "exch": "NSE", "tsym": "GODREJIND-EQ", "qty": "38", "dscqty": "0", "prctyp": "MKT", "prc": "0.0", "trgprc": "0", "ret": "DAY", "remarks": null, "amo": "NO"}&jKey=ae0da790f566b2ef45911882d65b0103d142db949596068b3f8e71510082c6f5
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.shoonya.com:443
DEBUG:urllib3.connectionpool:https://api.shoonya.com:443 "POST /NorenWClientTP//PlaceOrder HTTP/1.1" 200 80
DEBUG:NorenRestApiPy.NorenApi:{"request_time":"15:13:02 28-11-2024","stat":"Ok","norenordno":"24112801608476"}

10321.70
10321.7 38
open                  1061.95
high                  1062.85
low                    1061.6
close                  1062.1
volume                   45.0
diff                     1.25
per                  0.117747
type                       up
rsi14               28.550298
obv                   40271.0
ema20             1064.721262
bbl               1060.524827
bbm               1063.226974
bbu               1065.929121
bbb                  0.508292
bbp                  0.198948
adx                  35.90325
psl                      50.0
doji                      0.0
zscore              -3.292797
hmid              1063.423491
hupper            1063.930183
hlower            1062.916798
imi                       NaN
symbol_number           10925
symbol_name      GODREJIND-EQ
Name: 2024-11-28 15:12:00, dtype: object
{'request_time': '15:13:02 28-11-2024', 'stat': 'Ok', 'norenordno': '24112801608476'}

In [46]:
from dhanhq import marketfeed



# Structure for subscribing is (exchange_segment, "security_id", subscription_type)

instruments = [(marketfeed.NSE, "1333", mark
                etfeed.Ticker),   # Ticker - Ticker Data
    (marketfeed.NSE, "1333", marketfeed.Quote),     # Quote - Quote Data      # Full - Full Packet
    (marketfeed.NSE, "11915", marketfeed.Ticker)]

version = "v2"          # Mention Version and set to latest version 'v2'

# In case subscription_type is left as blank, by default Ticker mode will be subscribed.

try:
    data = marketfeed.DhanFeed(client_id, access_token, instruments)
    while True:
        data.run_forever()
        response = data.get_data()
        print(response)

except Exception as e:
    print(e)

# Close Connection
data.disconnect()

# Subscribe instruments while connection is open
sub_instruments = [(marketfeed.NSE, "14436", marketfeed.Ticker)]

data.subscribe_symbols(sub_instruments)

# Unsubscribe instruments which are already active on connection
unsub_instruments = [(marketfeed.NSE, "1333", 16)]

data.unsubscribe_symbols(unsub_instruments)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3845147331.py, line 7)

In [47]:
nest_asyncio.apply()
instruments = [(1, "1333", 17)]
df=pd.DataFrame()
async def main():
    global df
    try:
        data = mf.DhanFeed(client_id=client_id,
                               access_token=access_token,
                               instruments=[(1,"1333",17)])

            # Await connection
        await data.connect()
        print('Connected to WebSocket')

            # Process real-time data
        while True:
            data.run_forever()  
            response =  data.get_data() 
            #print(response)
            temp=pd.DataFrame([response])
            df=pd.concat([df,temp],ignore_index=True)
            print(df[-1:])

    except Exception as e:
        print(f"Error:{e}")

    # Run the event loop
asyncio.run(main())

Error:name 'mf' is not defined

In [48]:
df

Empty DataFrame
Columns: []
Index: []

In [175]:
# 1 day chart only for that it
all_data = pd.DataFrame()
last_rows = pd.DataFrame()
for symbol in nifty500["pSymbolName"]:
    # Fetch historical daily data (replace with your actual API call)
    tm_data = atha.historical_daily_data(
        symbol=symbol,
        exchange_segment='NSE_EQ',
        instrument_type="EQUITY",
        expiry_code=0,
        from_date="2024-01-01",
        to_date="2024-11-20"
    )
    
    
    # Convert tm_data to DataFrame if it's not already
    tm_data = pd.DataFrame(tm_data['data'])
    tm_data['start_Time'] = tm_data['start_Time'].apply(atha.convert_to_date_time)
    tm_data.insert(0,'Symbol',symbol)
    print(tm_data)

    # Apply the 'men' function
    processed_data = men(tm_data)

    # Append processed data to all_data
    all_data = pd.concat([all_data, processed_data], ignore_index=True)

    # Extract the last row of processed_data and append to last_rows
    last_rows = pd.concat([last_rows, processed_data.tail(1)], ignore_index=True)

DEBUG:urllib3.connectionpool:Resetting dropped connection: api.dhan.co
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close      volume start_Time
0    NYKAA  173.70  173.85  170.50  171.90   2822724.0 2024-01-01
1    NYKAA  172.00  173.40  168.35  169.30   3711343.0 2024-01-02
2    NYKAA  171.20  172.95  167.20  167.90   3883044.0 2024-01-03
3    NYKAA  169.00  171.00  168.50  170.05   2442473.0 2024-01-04
4    NYKAA  170.55  177.00  170.05  173.40  11042757.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216  NYKAA  183.40  189.25  175.26  177.81   6011460.0 2024-11-12
217  NYKAA  179.01  188.00  167.89  172.23  29113654.0 2024-11-13
218  NYKAA  174.60  177.00  168.42  171.05   8232043.0 2024-11-14
219  NYKAA  171.05  171.40  166.22  169.69   6549669.0 2024-11-18
220  NYKAA  170.70  173.44  169.00  170.31   7449516.0 2024-11-19

[221 rows x 7 columns]
       Symbol    open    high     low   close     volume start_Time
0    AARTIIND  653.70  656.85  648.35  651.75  1541664.0 2024-01-01
1    AARTIIND  655.00  661.15  645.25  655.65  2079464.0 2024-01-02
2    AARTIIND  655.95  656.80  643.50  652.45  1162051.0 2024-01-03
3    AARTIIND  653.55  656.20  643.00  644.40  1802609.0 2024-01-04
4    AARTIIND  647.85  649.05  622.00  629.30  1833576.0 2024-01-05
..        ...     ...     ...     ...     ...        ...        ...
216  AARTIIND  442.05  449.15  440.00  445.25  3393998.0 2024-11-12
217  AARTIIND  446.00  446.00  426.20  428.65  2078650.0 2024-11-13
218  AARTIIND  429.00  440.50  427.45  438.25  1303934.0 2024-11-14
219  AARTIIND  439.00  439.00  429.50  431.25  1246002.0 2024-11-18
220  AARTIIND  433.00  441.95  431.00  434.90   965128.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close     volume start_Time
0    SUNTV  712.00  715.90  706.20  710.30   311339.0 2024-01-01
1    SUNTV  710.50  715.70  700.20  707.00   539315.0 2024-01-02
2    SUNTV  712.00  723.60  704.50  718.90   913280.0 2024-01-03
3    SUNTV  718.90  734.90  716.25  729.75   623308.0 2024-01-04
4    SUNTV  733.00  734.35  716.35  721.30   544064.0 2024-01-05
..     ...     ...     ...     ...     ...        ...        ...
216  SUNTV  744.70  754.80  726.55  730.60   220524.0 2024-11-12
217  SUNTV  721.55  729.45  707.10  724.70   599444.0 2024-11-13
218  SUNTV  702.35  750.65  702.35  730.75  1014340.0 2024-11-14
219  SUNTV  732.10  734.30  717.80  725.20   252905.0 2024-11-18
220  SUNTV  732.00  749.95  727.55  740.60   306046.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close     volume start_Time
0     GPIL  151.60  156.60  149.97  155.13   639838.0 2024-01-01
1     GPIL  155.00  158.39  152.66  156.10   487957.0 2024-01-02
2     GPIL  157.36  158.33  154.82  155.69   231081.0 2024-01-03
3     GPIL  156.90  158.89  155.74  157.24   250446.0 2024-01-04
4     GPIL  158.50  160.00  149.01  154.54   399906.0 2024-01-05
..     ...     ...     ...     ...     ...        ...        ...
216   GPIL  197.95  200.35  193.90  194.95   864670.0 2024-11-12
217   GPIL  193.00  194.86  183.65  185.16  1549491.0 2024-11-13
218   GPIL  184.00  189.00  184.00  185.45   748345.0 2024-11-14
219   GPIL  183.30  189.48  182.11  187.07  1040663.0 2024-11-18
220   GPIL  187.07  192.79  184.45  185.93  1081333.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol    open    high     low   close     volume start_Time
0    SONATSOFTW  736.00  739.90  720.40  722.90  1066481.0 2024-01-01
1    SONATSOFTW  728.80  728.80  708.00  709.65   447140.0 2024-01-02
2    SONATSOFTW  705.05  718.80  697.05  705.85   745261.0 2024-01-03
3    SONATSOFTW  710.00  714.35  702.35  705.15   356682.0 2024-01-04
4    SONATSOFTW  712.05  716.55  702.00  715.35   543171.0 2024-01-05
..          ...     ...     ...     ...     ...        ...        ...
216  SONATSOFTW  591.85  602.45  581.00  585.10   985547.0 2024-11-12
217  SONATSOFTW  582.35  588.65  569.00  573.95   368705.0 2024-11-13
218  SONATSOFTW  568.75  575.40  553.50  559.10  1073493.0 2024-11-14
219  SONATSOFTW  559.10  567.95  549.20  553.10   410886.0 2024-11-18
220  SONATSOFTW  556.00  565.00  544.05  547.00   440708.0 2024-11-19

[221 rows x 7 columns]
        Symbol     open     high      low    close   volume start_Time
0    RATNAMANI  3370.90  3390.00  3310.00  3322.50  37970.0 2024-01-01
1    RATNAMANI  3339.15  3384.05  3308.05  3356.40  30626.0 2024-01-02
2    RATNAMANI  3349.05  3378.80  3330.05  3351.65  18923.0 2024-01-03
3    RATNAMANI  3358.00  3407.95  3358.00  3387.35  43142.0 2024-01-04
4    RATNAMANI  3390.75  3417.95  3348.00  3399.60  21066.0 2024-01-05
..         ...      ...      ...      ...      ...      ...        ...
216  RATNAMANI  3605.00  3625.00  3525.45  3540.45  14068.0 2024-11-12
217  RATNAMANI  3540.00  3614.60  3449.00  3512.20  16173.0 2024-11-13
218  RATNAMANI  3512.20  3544.40  3455.00  3519.40   7594.0 2024-11-14
219  RATNAMANI  3505.00  3551.00  3393.00  3452.35  28719.0 2024-11-18
220  RATNAMANI  3456.00  3495.30  3371.80  3403.80  93668.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

        Symbol    open    high     low   close    volume start_Time
0    JKLAKSHMI  905.20  915.00  891.35  904.80  140374.0 2024-01-01
1    JKLAKSHMI  902.00  902.00  877.05  890.70  103489.0 2024-01-02
2    JKLAKSHMI  894.95  895.50  877.45  881.25   72251.0 2024-01-03
3    JKLAKSHMI  882.15  898.45  878.90  894.20   61206.0 2024-01-04
4    JKLAKSHMI  908.00  909.90  873.00  877.35  127396.0 2024-01-05
..         ...     ...     ...     ...     ...       ...        ...
216  JKLAKSHMI  740.00  745.25  695.80  699.25  278994.0 2024-11-12
217  JKLAKSHMI  699.25  719.00  690.00  709.40  151313.0 2024-11-13
218  JKLAKSHMI  709.40  718.00  696.00  697.30  330301.0 2024-11-14
219  JKLAKSHMI  697.40  732.15  685.45  719.60  205903.0 2024-11-18
220  JKLAKSHMI  711.20  750.95  711.20  749.50  176749.0 2024-11-19

[221 rows x 7 columns]
        Symbol     open     high      low    close     volume start_Time
0    POLICYBZR   794.65   802.70   786.00   800.90   694439.0 2024-01-01
1    POLICYBZR   800.95   804.90   783.00   788.60   854345.0 2024-01-02
2    POLICYBZR   786.00   794.45   767.25   782.65  1253829.0 2024-01-03
3    POLICYBZR   789.00   795.70   779.90   783.80   229143.0 2024-01-04
4    POLICYBZR   784.10   803.65   784.10   798.80   875428.0 2024-01-05
..         ...      ...      ...      ...      ...        ...        ...
216  POLICYBZR  1679.90  1711.00  1661.00  1685.10   478459.0 2024-11-12
217  POLICYBZR  1685.10  1690.05  1625.05  1632.85   476493.0 2024-11-13
218  POLICYBZR  1636.10  1745.00  1636.10  1724.50  1346952.0 2024-11-14
219  POLICYBZR  1683.85  1807.70  1675.55  1719.85  1402978.0 2024-11-18
220  POLICYBZR  1751.00  1753.90  1691.10  1712.65   939422.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol   open   high    low  close      volume start_Time
0    ALLCARGO  82.23  86.71  81.50  82.26   5617549.0 2024-01-01
1    ALLCARGO  86.00  98.00  85.65  90.10  25954115.0 2024-01-02
2    ALLCARGO  90.95  91.00  87.55  87.95   4694239.0 2024-01-03
3    ALLCARGO  88.00  91.40  86.65  89.90   6824273.0 2024-01-04
4    ALLCARGO  91.00  91.35  89.60  90.80   2186680.0 2024-01-05
..        ...    ...    ...    ...    ...         ...        ...
216  ALLCARGO  55.62  56.09  53.25  54.24   1288965.0 2024-11-12
217  ALLCARGO  55.00  55.59  52.30  52.57   3215676.0 2024-11-13
218  ALLCARGO  53.39  54.94  52.89  54.03   1846181.0 2024-11-14
219  ALLCARGO  55.00  55.19  52.91  53.76   1220047.0 2024-11-18
220  ALLCARGO  53.80  55.36  53.79  54.16   1343494.0 2024-11-19

[221 rows x 7 columns]
       Symbol    open    high     low   close     volume start_Time
0    EMAMILTD  569.90  588.60  567.35  572.70  2442680.0 2024-01-01
1    EMAMILTD  572.00  574.40  553.50  564.20   997994.0 2024-01-02
2    EMAMILTD  560.10  574.35  538.10  544.05  1190793.0 2024-01-03
3    EMAMILTD  550.00  569.15  550.00  559.30  1030036.0 2024-01-04
4    EMAMILTD  562.25  569.20  557.55  564.80   605066.0 2024-01-05
..        ...     ...     ...     ...     ...        ...        ...
216  EMAMILTD  681.55  699.30  670.05  691.00   470310.0 2024-11-12
217  EMAMILTD  677.00  683.00  642.20  649.75  2056417.0 2024-11-13
218  EMAMILTD  648.10  664.75  634.60  642.85   434476.0 2024-11-14
219  EMAMILTD  643.25  644.25  611.30  615.30   591079.0 2024-11-18
220  EMAMILTD  613.85  649.65  612.30  643.15   711152.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol   open   high    low  close      volume start_Time
0    GMRINFRA  80.90  82.30  79.85  80.35  37830090.0 2024-01-01
1    GMRINFRA  80.75  80.75  77.25  79.60  28625842.0 2024-01-02
2    GMRINFRA  79.95  83.00  78.85  81.80  36193954.0 2024-01-03
3    GMRINFRA  82.20  84.95  81.75  84.45  91736436.0 2024-01-04
4    GMRINFRA  84.80  85.25  81.90  83.90  40706295.0 2024-01-05
..        ...    ...    ...    ...    ...         ...        ...
216  GMRINFRA  79.59  80.22  77.75  78.22   6872819.0 2024-11-12
217  GMRINFRA  77.93  78.37  75.41  76.01   9038751.0 2024-11-13
218  GMRINFRA  76.12  77.45  75.73  76.81  12842078.0 2024-11-14
219  GMRINFRA  77.00  78.99  75.95  78.01  17220570.0 2024-11-18
220  GMRINFRA  80.50  82.40  79.15  80.53  43057112.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open     high      low    close     volume start_Time
0    TECHM  1273.00  1303.80  1265.25  1297.15  1776828.0 2024-01-01
1    TECHM  1298.00  1299.10  1272.85  1278.10  1615064.0 2024-01-02
2    TECHM  1265.00  1274.00  1240.00  1244.20  2231707.0 2024-01-03
3    TECHM  1250.10  1254.70  1231.70  1247.50  3355191.0 2024-01-04
4    TECHM  1254.90  1271.85  1245.55  1248.30  1756868.0 2024-01-05
..     ...      ...      ...      ...      ...        ...        ...
216  TECHM  1710.00  1710.50  1684.00  1687.00  1414446.0 2024-11-12
217  TECHM  1680.00  1689.00  1663.65  1675.60  1063556.0 2024-11-13
218  TECHM  1663.00  1692.00  1663.00  1687.50  1919974.0 2024-11-14
219  TECHM  1684.75  1688.00  1633.25  1660.80  1617013.0 2024-11-18
220  TECHM  1664.90  1724.40  1664.10  1699.65  1982317.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

        Symbol     open     high      low    close   volume start_Time
0    GRINDWELL  2349.60  2390.75  2306.50  2359.60  68098.0 2024-01-01
1    GRINDWELL  2359.65  2369.90  2316.45  2336.00  24818.0 2024-01-02
2    GRINDWELL  2350.35  2350.35  2294.70  2342.50  31581.0 2024-01-03
3    GRINDWELL  2342.50  2367.25  2315.05  2345.85  24415.0 2024-01-04
4    GRINDWELL  2345.85  2365.80  2300.00  2331.20  32517.0 2024-01-05
..         ...      ...      ...      ...      ...      ...        ...
216  GRINDWELL  2128.70  2166.50  2082.35  2120.20  18187.0 2024-11-12
217  GRINDWELL  2110.00  2118.00  2066.00  2090.65  27177.0 2024-11-13
218  GRINDWELL  2060.50  2110.85  2060.50  2084.80  90124.0 2024-11-14
219  GRINDWELL  2084.80  2124.00  2081.00  2096.05  29889.0 2024-11-18
220  GRINDWELL  2103.20  2114.40  2090.00  2098.55  15793.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open     high      low    close     volume start_Time
0      ACE   834.00   852.00   834.00   845.90   147904.0 2024-01-01
1      ACE   851.00   880.00   837.00   869.70   595007.0 2024-01-02
2      ACE   875.90   928.00   867.00   925.50  1395777.0 2024-01-03
3      ACE   931.10   937.00   895.00   899.80   455671.0 2024-01-04
4      ACE   906.95   921.25   896.05   911.40   245802.0 2024-01-05
..     ...      ...      ...      ...      ...        ...        ...
216    ACE  1340.55  1363.05  1293.90  1301.75   154969.0 2024-11-12
217    ACE  1303.95  1303.95  1225.00  1228.20   268862.0 2024-11-13
218    ACE  1228.25  1279.70  1228.25  1242.40   208691.0 2024-11-14
219    ACE  1243.50  1251.95  1197.65  1211.75   251045.0 2024-11-18
220    ACE  1212.95  1263.90  1206.65  1242.00   205789.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol     open     high      low    close    volume start_Time
0      ABB  4674.85  4715.00  4653.80  4682.20   84544.0 2024-01-01
1      ABB  4699.95  4713.00  4600.00  4701.60  178550.0 2024-01-02
2      ABB  4714.00  4829.90  4699.10  4775.55  291954.0 2024-01-03
3      ABB  4818.90  4866.00  4770.05  4824.75  266936.0 2024-01-04
4      ABB  4855.95  4900.00  4802.00  4832.35  118877.0 2024-01-05
..     ...      ...      ...      ...      ...       ...        ...
216    ABB  7296.05  7308.75  6935.25  6964.25  547081.0 2024-11-12
217    ABB  6940.00  6999.00  6782.00  6802.00  509564.0 2024-11-13
218    ABB  6808.00  6834.15  6629.85  6680.15  599381.0 2024-11-14
219    ABB  6700.35  6745.45  6605.00  6625.90  327357.0 2024-11-18
220    ABB  6672.25  6788.40  6626.30  6701.60  415057.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open     high      low    close     volume start_Time
0      ACC  2212.00  2260.00  2208.65  2243.30   531769.0 2024-01-01
1      ACC  2244.00  2278.00  2214.90  2267.30   534118.0 2024-01-02
2      ACC  2283.00  2333.80  2255.00  2280.20  1440573.0 2024-01-03
3      ACC  2299.80  2367.25  2273.55  2358.20   853756.0 2024-01-04
4      ACC  2357.95  2403.80  2340.05  2377.45   644750.0 2024-01-05
..     ...      ...      ...      ...      ...        ...        ...
216    ACC  2282.85  2293.00  2257.00  2263.90   128192.0 2024-11-12
217    ACC  2257.00  2270.35  2190.10  2197.80   154307.0 2024-11-13
218    ACC  2198.90  2214.95  2178.05  2188.15   194258.0 2024-11-14
219    ACC  2200.00  2211.90  2162.90  2187.40    96713.0 2024-11-18
220    ACC  2193.70  2231.55  2170.05  2185.70    98826.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol     open     high      low   close      volume start_Time
0    ADANIENT  2852.30  2947.00  2842.05  2917.2   2898619.0 2024-01-01
1    ADANIENT  2922.00  2948.20  2841.00  2932.4   2671368.0 2024-01-02
2    ADANIENT  3047.00  3199.00  2955.60  3003.0  19725411.0 2024-01-03
3    ADANIENT  3039.40  3044.45  2990.00  2998.3   2975620.0 2024-01-04
4    ADANIENT  3009.95  3066.90  2981.10  3006.6   3219949.0 2024-01-05
..        ...      ...      ...      ...     ...         ...        ...
216  ADANIENT  2910.00  2930.45  2855.00  2870.0    597231.0 2024-11-12
217  ADANIENT  2860.00  2889.00  2808.00  2816.7    890146.0 2024-11-13
218  ADANIENT  2824.00  2844.80  2801.00  2826.8    646797.0 2024-11-14
219  ADANIENT  2826.80  2858.65  2793.30  2818.7    489692.0 2024-11-18
220  ADANIENT  2831.00  2894.80  2809.80  2821.5    536296.0 2024-11-19

[221 rows x 7 columns]
       Symbol    open    high     low   close     volume start_Time
0    AEGISLOG  351.90  354.35  346.20  349.55   407119.0 2024-01-01
1    AEGISLOG  349.55  353.80  346.35  349.00   340934.0 2024-01-02
2    AEGISLOG  350.75  354.00  348.15  349.75   214285.0 2024-01-03
3    AEGISLOG  350.95  352.45  342.65  343.90   432892.0 2024-01-04
4    AEGISLOG  345.00  345.10  333.30  333.95  1520015.0 2024-01-05
..        ...     ...     ...     ...     ...        ...        ...
217  AEGISLOG  760.50  777.00  760.50  774.75   208575.0 2024-11-12
218  AEGISLOG  765.05  780.00  747.25  771.85   326688.0 2024-11-13
219  AEGISLOG  784.45  819.50  771.85  805.05   718373.0 2024-11-14
220  AEGISLOG  819.50  851.00  819.50  842.90   961111.0 2024-11-18
221  AEGISLOG  842.00  858.00  833.00  839.90   219675.0 2024-11-19

[222 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol    open    high     low   close    volume start_Time
0    HAPPSTMNDS  898.50  913.00  898.50  903.65  300820.0 2024-01-01
1    HAPPSTMNDS  908.75  915.00  891.10  909.50  400253.0 2024-01-02
2    HAPPSTMNDS  908.05  908.80  897.00  903.75  318933.0 2024-01-03
3    HAPPSTMNDS  907.70  912.95  899.00  900.70  297248.0 2024-01-04
4    HAPPSTMNDS  901.90  910.90  895.10  903.80  337363.0 2024-01-05
..          ...     ...     ...     ...     ...       ...        ...
216  HAPPSTMNDS  765.05  770.00  755.50  757.10  223724.0 2024-11-12
217  HAPPSTMNDS  741.40  764.10  741.40  749.85  984270.0 2024-11-13
218  HAPPSTMNDS  744.50  758.60  732.00  735.80  503025.0 2024-11-14
219  HAPPSTMNDS  736.20  744.00  721.20  723.50  996368.0 2024-11-18
220  HAPPSTMNDS  723.50  747.50  723.45  736.50  401917.0 2024-11-19

[221 rows x 7 columns]
    Symbol   open    high     low   close      volume start_Time
0    PAYTM  637.0  648.85  636.65  646.10   3043220.0 2024-01-01
1    PAYTM  648.0  654.00  641.10  651.10   3129266.0 2024-01-02
2    PAYTM  654.0  678.75  648.35  673.70   8321160.0 2024-01-03
3    PAYTM  675.5  677.00  664.25  668.70   3098366.0 2024-01-04
4    PAYTM  674.7  688.00  672.00  685.15   5866520.0 2024-01-05
..     ...    ...     ...     ...     ...         ...        ...
216  PAYTM  828.0  839.85  785.35  789.70   5713703.0 2024-11-12
217  PAYTM  791.0  794.05  750.00  753.25   7588676.0 2024-11-13
218  PAYTM  766.0  797.55  763.05  769.10  10003402.0 2024-11-14
219  PAYTM  771.0  788.00  758.00  783.90   7590159.0 2024-11-18
220  PAYTM  787.0  834.00  787.00  814.25  12025683.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol    open    high     low   close    volume start_Time
0    SAPPHIRE  282.43  285.67  280.02  281.85   19605.0 2024-01-01
1    SAPPHIRE  281.85  283.44  279.20  281.22   13864.0 2024-01-02
2    SAPPHIRE  281.22  282.98  279.81  281.76   25418.0 2024-01-03
3    SAPPHIRE  281.76  287.80  280.60  286.28  270557.0 2024-01-04
4    SAPPHIRE  287.60  288.00  281.43  284.61  221236.0 2024-01-05
..        ...     ...     ...     ...     ...       ...        ...
216  SAPPHIRE  315.00  317.70  311.90  316.05  298023.0 2024-11-12
217  SAPPHIRE  315.00  316.05  303.40  308.95  268749.0 2024-11-13
218  SAPPHIRE  305.55  312.10  302.60  307.05  215286.0 2024-11-14
219  SAPPHIRE  303.05  307.95  299.80  305.50  105149.0 2024-11-18
220  SAPPHIRE  302.50  311.15  302.50  306.30  168380.0 2024-11-19

[221 rows x 7 columns]
         Symbol    open    high     low   close     volume start_Time
0    JINDALSTEL  752.00  753.50  741.15  744.00  1153090.0 2024-01-01
1    JINDALSTEL  744.00  747.85  730.00  743.20   844656.0 2024-01-02
2    JINDALSTEL  741.00  741.00  723.45  732.00  1578330.0 2024-01-03
3    JINDALSTEL  734.90  751.60  732.95  744.95  1762967.0 2024-01-04
4    JINDALSTEL  745.00  755.50  730.05  735.75  1749327.0 2024-01-05
..          ...     ...     ...     ...     ...        ...        ...
216  JINDALSTEL  906.85  915.95  883.20  887.00  2703824.0 2024-11-12
217  JINDALSTEL  881.00  884.90  855.00  858.65  2232128.0 2024-11-13
218  JINDALSTEL  859.75  888.00  859.00  877.40  1864763.0 2024-11-14
219  JINDALSTEL  880.00  903.95  875.25  886.75  1348925.0 2024-11-18
220  JINDALSTEL  886.95  890.85  862.35  865.40  1585170.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol   open    high     low   close     volume start_Time
0    IRCTC  892.0  916.85  888.00  891.85  9040913.0 2024-01-01
1    IRCTC  895.7  903.30  866.80  886.20  5242381.0 2024-01-02
2    IRCTC  886.3  910.00  886.20  899.25  6852189.0 2024-01-03
3    IRCTC  903.9  912.00  895.25  901.55  4427039.0 2024-01-04
4    IRCTC  905.0  923.45  894.05  905.90  9811302.0 2024-01-05
..     ...    ...     ...     ...     ...        ...        ...
216  IRCTC  836.0  843.80  810.00  811.65  1007697.0 2024-11-12
217  IRCTC  809.7  817.30  796.50  801.40  1223260.0 2024-11-13
218  IRCTC  800.0  808.25  791.00  799.60   845850.0 2024-11-14
219  IRCTC  801.9  810.90  787.00  797.10  1009781.0 2024-11-18
220  IRCTC  796.0  815.65  796.00  800.10   774201.0 2024-11-19

[221 rows x 7 columns]
         Symbol    open    high     low   close     volume start_Time
0    JMFINANCIL   98.70  100.80   97.75   99.90  4803515.0 2024-01-01
1    JMFINANCIL  100.00  102.30   98.90   99.90  6400056.0 2024-01-02
2    JMFINANCIL  100.25  103.50   99.50  101.10  9384238.0 2024-01-03
3    JMFINANCIL  101.70  103.75  101.00  102.60  6249300.0 2024-01-04
4    JMFINANCIL  102.60  104.40   99.30  101.15  6252710.0 2024-01-05
..          ...     ...     ...     ...     ...        ...        ...
216  JMFINANCIL  141.00  142.50  134.23  135.91  6494954.0 2024-11-12
217  JMFINANCIL  135.00  136.70  128.17  129.35  8806277.0 2024-11-13
218  JMFINANCIL  130.25  133.80  128.21  129.05  7738406.0 2024-11-14
219  JMFINANCIL  129.90  131.64  125.35  129.77  9358386.0 2024-11-18
220  JMFINANCIL  130.46  135.49  130.30  132.06  8729989.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

     Symbol    open    high     low   close    volume start_Time
0    ELECON  466.48  472.45  464.48  468.70  147484.0 2024-01-01
1    ELECON  470.10  472.48  452.50  459.63  248544.0 2024-01-02
2    ELECON  460.00  464.53  458.43  460.88  119030.0 2024-01-03
3    ELECON  462.95  470.63  458.50  464.18  155641.0 2024-01-04
4    ELECON  467.98  472.38  463.28  467.43  188937.0 2024-01-05
..      ...     ...     ...     ...     ...       ...        ...
216  ELECON  568.00  577.00  552.50  557.50  266363.0 2024-11-12
217  ELECON  549.15  568.65  536.95  543.80  556905.0 2024-11-13
218  ELECON  548.00  560.40  530.15  558.50  438406.0 2024-11-14
219  ELECON  557.00  557.00  537.45  548.05  331485.0 2024-11-18
220  ELECON  549.80  581.95  543.80  573.10  473998.0 2024-11-19

[221 rows x 7 columns]
         Symbol    open    high     low   close    volume start_Time
0    LATENTVIEW  457.70  459.40  453.40  455.45  386502.0 2024-01-01
1    LATENTVIEW  455.50  456.95  446.00  454.70  449051.0 2024-01-02
2    LATENTVIEW  454.75  461.80  450.05  455.65  588636.0 2024-01-03
3    LATENTVIEW  457.05  459.75  452.70  453.75  518162.0 2024-01-04
4    LATENTVIEW  454.05  456.80  448.35  450.50  644252.0 2024-01-05
..          ...     ...     ...     ...     ...       ...        ...
216  LATENTVIEW  485.50  489.40  474.00  476.55  377256.0 2024-11-12
217  LATENTVIEW  472.20  478.45  462.60  465.15  363357.0 2024-11-13
218  LATENTVIEW  467.50  471.25  454.00  456.40  224377.0 2024-11-14
219  LATENTVIEW  459.00  460.70  452.70  454.55  267876.0 2024-11-18
220  LATENTVIEW  459.00  459.00  436.55  446.40  265317.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close    volume start_Time
0    FLUOROCHEM  3699.25  3826.40  3653.00  3812.75  184135.0 2024-01-01
1    FLUOROCHEM  3824.00  3899.95  3743.00  3871.50  239730.0 2024-01-02
2    FLUOROCHEM  3920.00  3920.00  3822.80  3892.10  172810.0 2024-01-03
3    FLUOROCHEM  3872.05  3894.75  3801.20  3824.50   85513.0 2024-01-04
4    FLUOROCHEM  3824.75  3869.80  3592.05  3625.60  274750.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  FLUOROCHEM  4200.00  4238.60  4110.00  4151.50   76577.0 2024-11-12
217  FLUOROCHEM  4154.80  4154.85  3965.00  4034.15  106522.0 2024-11-13
218  FLUOROCHEM  4082.40  4149.00  3985.55  4103.90   78792.0 2024-11-14
219  FLUOROCHEM  4100.00  4116.70  3939.45  3997.55  115640.0 2024-11-18
220  FLUOROCHEM  4049.00  4049.00  3855.75  3878.10  142183.0 2024-11-19

[221 rows x 7 columns]
     Symbol     open     high      low    close    volume start_Time
0    NAUKRI  5175.00  5195.95  5117.50  5149.50  106346.0 2024-01-01
1    NAUKRI  5145.05  5175.00  5058.90  5126.20  287607.0 2024-01-02
2    NAUKRI  5030.00  5148.40  5030.00  5088.00  159354.0 2024-01-03
3    NAUKRI  5125.00  5141.20  5056.55  5085.50  132168.0 2024-01-04
4    NAUKRI  5085.05  5290.00  5085.05  5246.15  571151.0 2024-01-05
..      ...      ...      ...      ...      ...       ...        ...
216  NAUKRI  7945.00  8035.00  7802.75  7821.30  162887.0 2024-11-12
217  NAUKRI  7820.00  7820.00  7588.00  7614.95  169525.0 2024-11-13
218  NAUKRI  7615.00  7842.05  7550.00  7768.20  187611.0 2024-11-14
219  NAUKRI  7848.60  7875.80  7491.10  7589.65  286979.0 2024-11-18
220  NAUKRI  7600.80  7749.00  7588.40  7625.10  156589.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

     Symbol     open     high      low    close    volume start_Time
0    GESHIP   983.50   990.05   969.05   972.65  194886.0 2024-01-01
1    GESHIP   970.00   992.80   961.85   978.35  406642.0 2024-01-02
2    GESHIP   980.65  1015.00   980.65   995.45  500820.0 2024-01-03
3    GESHIP   998.95  1006.90   972.70   974.90  554969.0 2024-01-04
4    GESHIP   979.50   992.00   967.15   975.00  496554.0 2024-01-05
..      ...      ...      ...      ...      ...       ...        ...
216  GESHIP  1194.05  1201.75  1115.00  1124.90  722760.0 2024-11-12
217  GESHIP  1125.00  1137.10  1082.00  1085.45  471377.0 2024-11-13
218  GESHIP  1085.60  1114.95  1082.60  1112.10  454501.0 2024-11-14
219  GESHIP  1108.00  1119.90  1065.00  1067.95  335512.0 2024-11-18
220  GESHIP  1071.25  1085.95  1057.15  1062.60  359004.0 2024-11-19

[221 rows x 7 columns]
         Symbol     open     high      low    close     volume start_Time
0    TORNTPOWER   944.80   949.70   936.00   942.45   329025.0 2024-01-01
1    TORNTPOWER   944.45   955.00   930.10   937.70   362520.0 2024-01-02
2    TORNTPOWER   939.65   952.90   939.65   944.30   250137.0 2024-01-03
3    TORNTPOWER  1005.00  1071.95   983.00  1014.60  7975873.0 2024-01-04
4    TORNTPOWER  1030.00  1045.00  1015.00  1038.20  1137345.0 2024-01-05
..          ...      ...      ...      ...      ...        ...        ...
216  TORNTPOWER  1691.45  1709.50  1640.00  1658.70   262961.0 2024-11-12
217  TORNTPOWER  1657.50  1692.00  1634.00  1645.10   289890.0 2024-11-13
218  TORNTPOWER  1600.00  1638.30  1545.70  1559.00   989846.0 2024-11-14
219  TORNTPOWER  1578.50  1597.00  1529.00  1583.10   622083.0 2024-11-18
220  TORNTPOWER  1590.00  1615.40  1570.00  1582.40   451519.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol     open     high      low    close      volume start_Time
0    SOBHA   963.55  1004.48   960.92   994.40    529962.0 2024-01-01
1    SOBHA  1001.56  1002.53   975.37   983.60    631790.0 2024-01-02
2    SOBHA   982.14  1109.60   982.14  1089.64   3641651.0 2024-01-03
3    SOBHA  1092.08  1307.52  1091.10  1260.71  14291405.0 2024-01-04
4    SOBHA  1260.71  1270.00  1202.31  1235.35   4313421.0 2024-01-05
..     ...      ...      ...      ...      ...         ...        ...
216  SOBHA  1604.70  1655.55  1590.00  1597.30     97003.0 2024-11-12
217  SOBHA  1603.70  1603.70  1533.05  1546.80    182042.0 2024-11-13
218  SOBHA  1565.45  1573.45  1490.00  1534.05    107231.0 2024-11-14
219  SOBHA  1575.95  1633.90  1504.70  1522.05    219474.0 2024-11-18
220  SOBHA  1530.05  1606.00  1525.00  1532.95    221191.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close     volume start_Time
0    BSOFT  719.00  722.70  700.30  702.35  2508444.0 2024-01-01
1    BSOFT  703.70  706.30  682.00  687.40  2436418.0 2024-01-02
2    BSOFT  686.95  690.40  670.40  685.75  3079989.0 2024-01-03
3    BSOFT  689.00  701.50  686.15  687.50  2220674.0 2024-01-04
4    BSOFT  692.90  717.20  689.60  714.35  5019317.0 2024-01-05
..     ...     ...     ...     ...     ...        ...        ...
216  BSOFT  572.90  576.90  562.40  564.55  1307650.0 2024-11-12
217  BSOFT  564.80  565.45  547.00  549.90  1004196.0 2024-11-13
218  BSOFT  550.15  560.95  548.50  559.25   923393.0 2024-11-14
219  BSOFT  562.05  563.00  540.10  546.45  1319187.0 2024-11-18
220  BSOFT  548.00  562.85  548.00  552.15   907440.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol    open    high     low   close     volume start_Time
0    HBLPOWER  437.80  444.00  433.50  435.75   979687.0 2024-01-01
1    HBLPOWER  438.55  456.00  428.90  452.45  1916773.0 2024-01-02
2    HBLPOWER  455.50  464.70  455.50  458.80  1607462.0 2024-01-03
3    HBLPOWER  461.75  467.10  453.00  455.65  1449081.0 2024-01-04
4    HBLPOWER  458.35  461.10  450.25  453.85  1055711.0 2024-01-05
..        ...     ...     ...     ...     ...        ...        ...
216  HBLPOWER  539.30  579.00  539.30  556.85  3234949.0 2024-11-12
217  HBLPOWER  556.95  559.95  514.05  518.60  1603166.0 2024-11-13
218  HBLPOWER  520.95  548.00  520.10  540.90  1824681.0 2024-11-14
219  HBLPOWER  545.50  548.95  532.00  540.90   793502.0 2024-11-18
220  HBLPOWER  541.95  565.10  541.95  547.75  1310683.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open     high      low    close    volume start_Time
0    TANLA  1088.00  1110.00  1088.00  1100.35  507337.0 2024-01-01
1    TANLA  1108.00  1141.90  1093.00  1108.65  942320.0 2024-01-02
2    TANLA  1103.00  1108.95  1081.00  1086.45  482937.0 2024-01-03
3    TANLA  1089.90  1097.25  1074.95  1085.45  471445.0 2024-01-04
4    TANLA  1088.80  1114.75  1075.00  1104.20  596433.0 2024-01-05
..     ...      ...      ...      ...      ...       ...        ...
216  TANLA   750.70   752.60   746.00   749.20  333434.0 2024-11-12
217  TANLA   742.85   749.00   720.80   722.80  231204.0 2024-11-13
218  TANLA   724.75   726.95   711.00   713.20  247354.0 2024-11-14
219  TANLA   713.75   717.00   689.35   696.20  380279.0 2024-11-18
220  TANLA   703.00   712.00   690.35   695.65  211978.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol    open    high     low   close     volume start_Time
0    STARHEALTH  536.75  548.75  533.00  545.30   537965.0 2024-01-01
1    STARHEALTH  545.30  551.95  541.00  550.15   611964.0 2024-01-02
2    STARHEALTH  552.80  555.00  542.85  551.40   528664.0 2024-01-03
3    STARHEALTH  552.00  558.25  547.60  557.95   511531.0 2024-01-04
4    STARHEALTH  558.00  558.00  547.20  549.35  1477038.0 2024-01-05
..          ...     ...     ...     ...     ...        ...        ...
216  STARHEALTH  474.45  478.35  469.05  472.05  1169132.0 2024-11-12
217  STARHEALTH  470.00  475.80  462.00  466.75   730877.0 2024-11-13
218  STARHEALTH  470.00  477.00  466.45  474.75   489499.0 2024-11-14
219  STARHEALTH  474.00  474.70  460.35  463.50   633413.0 2024-11-18
220  STARHEALTH  462.40  464.50  452.70  462.10  2033099.0 2024-11-19

[221 rows x 7 columns]
         Symbol     open     high      low    close    volume start_Time
0    ANANDRATHI  2614.00  2638.05  2546.00  2567.40   65516.0 2024-01-01
1    ANANDRATHI  2575.00  2631.00  2510.05  2578.60   65002.0 2024-01-02
2    ANANDRATHI  2570.00  2625.00  2563.50  2598.50   43384.0 2024-01-03
3    ANANDRATHI  2585.05  2797.90  2585.05  2667.40  190778.0 2024-01-04
4    ANANDRATHI  2676.45  2766.80  2676.45  2700.75   85900.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  ANANDRATHI  3988.45  3998.50  3892.40  3903.90   25420.0 2024-11-12
217  ANANDRATHI  3888.05  3895.40  3762.75  3821.60   62761.0 2024-11-13
218  ANANDRATHI  3775.00  3919.90  3775.00  3884.05   37446.0 2024-11-14
219  ANANDRATHI  3885.00  4019.90  3850.00  3985.15   33452.0 2024-11-18
220  ANANDRATHI  3985.15  4070.00  3942.55  4030.60   31606.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close    volume start_Time
0    MAPMYINDIA  1948.80  2013.00  1912.25  1928.80  256823.0 2024-01-01
1    MAPMYINDIA  1936.90  1992.20  1928.45  1962.35  282020.0 2024-01-02
2    MAPMYINDIA  1966.00  1974.65  1937.00  1940.00   96093.0 2024-01-03
3    MAPMYINDIA  1950.00  1959.95  1925.05  1936.90  116525.0 2024-01-04
4    MAPMYINDIA  1946.00  1984.95  1935.00  1965.35  211013.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  MAPMYINDIA  1890.45  1901.40  1850.00  1859.50   97889.0 2024-11-12
217  MAPMYINDIA  1848.00  1848.00  1762.50  1768.75  142047.0 2024-11-13
218  MAPMYINDIA  1792.65  1795.90  1731.05  1742.10   80863.0 2024-11-14
219  MAPMYINDIA  1717.85  1796.65  1700.00  1747.95  102041.0 2024-11-18
220  MAPMYINDIA  1731.00  1744.95  1631.10  1647.60  290906.0 2024-11-19

[221 rows x 7 columns]
      Symbol     open     high      low    close     volume start_Time
0    HCLTECH  1460.00  1495.75  1455.05  1483.75  1222315.0 2024-01-01
1    HCLTECH  1484.05  1488.80  1461.35  1469.55  1440888.0 2024-01-02
2    HCLTECH  1460.00  1465.00  1435.50  1437.75  1651716.0 2024-01-03
3    HCLTECH  1437.00  1444.80  1417.15  1419.95  3392241.0 2024-01-04
4    HCLTECH  1425.00  1438.85  1421.90  1432.80  1776925.0 2024-01-05
..       ...      ...      ...      ...      ...        ...        ...
216  HCLTECH  1891.00  1892.95  1864.45  1872.85  2711052.0 2024-11-12
217  HCLTECH  1866.00  1879.60  1859.10  1864.75  1254074.0 2024-11-13
218  HCLTECH  1872.00  1897.00  1846.35  1858.95  2462563.0 2024-11-14
219  HCLTECH  1858.95  1865.05  1815.00  1835.00  2483933.0 2024-11-18
220  HCLTECH  1837.00  1865.00  1817.30  1820.55  2354204.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close    volume start_Time
0    METROBRAND  1268.00  1273.40  1240.00  1245.05   43847.0 2024-01-01
1    METROBRAND  1244.05  1269.60  1240.00  1242.75   75225.0 2024-01-02
2    METROBRAND  1261.00  1285.00  1245.40  1267.80  164261.0 2024-01-03
3    METROBRAND  1267.80  1282.60  1255.50  1260.20   43940.0 2024-01-04
4    METROBRAND  1263.00  1278.70  1253.10  1259.60   59992.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  METROBRAND  1173.55  1185.85  1141.15  1153.45   47812.0 2024-11-12
217  METROBRAND  1154.00  1180.00  1118.10  1127.75  162226.0 2024-11-13
218  METROBRAND  1126.75  1143.80  1116.00  1128.95   57764.0 2024-11-14
219  METROBRAND  1128.95  1136.90  1105.80  1119.50   82430.0 2024-11-18
220  METROBRAND  1119.50  1138.30  1097.30  1118.15  117863.0 2024-11-19

[221 rows x 7 columns]
      Symbol    open    high     low   close     volume start_Time
0    MEDPLUS  750.75  753.95  734.95  740.60    72431.0 2024-01-01
1    MEDPLUS  746.00  750.30  736.10  745.85   104178.0 2024-01-02
2    MEDPLUS  748.95  756.60  744.55  749.45    77863.0 2024-01-03
3    MEDPLUS  754.80  755.80  747.05  749.75    46338.0 2024-01-04
4    MEDPLUS  751.05  754.45  744.10  750.50    67106.0 2024-01-05
..       ...     ...     ...     ...     ...        ...        ...
216  MEDPLUS  674.95  679.90  670.50  675.25   238673.0 2024-11-12
217  MEDPLUS  717.20  724.95  680.00  683.60  2115342.0 2024-11-13
218  MEDPLUS  709.00  713.70  696.05  704.25   970427.0 2024-11-14
219  MEDPLUS  711.00  727.65  702.70  719.05  1858320.0 2024-11-18
220  MEDPLUS  729.00  746.40  717.00  738.80  2296045.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

        Symbol   open   high    low  close      volume start_Time
0    NETWORK18  88.35  90.80  88.00  88.50   4707765.0 2024-01-01
1    NETWORK18  88.50  90.95  87.05  89.55   4846393.0 2024-01-02
2    NETWORK18  89.95  92.35  89.30  89.70   4532851.0 2024-01-03
3    NETWORK18  90.00  92.05  89.50  90.25   3912059.0 2024-01-04
4    NETWORK18  92.40  97.65  91.25  93.05  17934482.0 2024-01-05
..         ...    ...    ...    ...    ...         ...        ...
216  NETWORK18  80.75  83.36  80.75  81.72   1486057.0 2024-11-12
217  NETWORK18  81.31  81.68  77.11  77.97   1490735.0 2024-11-13
218  NETWORK18  79.00  85.99  78.58  84.82  14244126.0 2024-11-14
219  NETWORK18  84.19  85.73  82.73  84.78   3712336.0 2024-11-18
220  NETWORK18  81.00  87.18  80.80  84.17   3969025.0 2024-11-19

[221 rows x 7 columns]
       Symbol     open     high      low    close     volume start_Time
0    UNOMINDA   695.30   697.60   675.00   682.20   398958.0 2024-01-01
1    UNOMINDA   687.20   692.95   673.10   677.25   282787.0 2024-01-02
2    UNOMINDA   676.90   676.90   662.00   663.60   392510.0 2024-01-03
3    UNOMINDA   668.80   686.35   662.00   684.95   778159.0 2024-01-04
4    UNOMINDA   689.00   707.70   680.55   701.35   504711.0 2024-01-05
..        ...      ...      ...      ...      ...        ...        ...
216  UNOMINDA   929.00  1015.00   929.00  1002.60  8793032.0 2024-11-12
217  UNOMINDA   994.05  1042.95   948.20   964.30  4397818.0 2024-11-13
218  UNOMINDA   964.35  1008.90   941.30   995.15  1726665.0 2024-11-14
219  UNOMINDA   996.00  1015.00   976.50   998.10   694166.0 2024-11-18
220  UNOMINDA  1007.80  1048.00  1000.85  1040.30  1218991.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol   open   high    low  close     volume start_Time
0    NSLNISP  51.50  52.35  51.00  51.30  8438622.0 2024-01-01
1    NSLNISP  51.50  51.75  50.00  50.75  8135898.0 2024-01-02
2    NSLNISP  51.00  51.10  50.15  50.40  4620674.0 2024-01-03
3    NSLNISP  50.40  52.05  50.40  51.05  7162426.0 2024-01-04
4    NSLNISP  51.30  52.15  50.50  50.90  8876183.0 2024-01-05
..       ...    ...    ...    ...    ...        ...        ...
216  NSLNISP  47.10  47.65  46.00  46.15  2173034.0 2024-11-12
217  NSLNISP  44.01  45.09  43.60  43.92  5745748.0 2024-11-13
218  NSLNISP  44.40  44.68  43.58  43.86  2815767.0 2024-11-14
219  NSLNISP  44.01  44.89  43.06  43.97  3722547.0 2024-11-18
220  NSLNISP  44.27  44.92  43.90  44.02  1956510.0 2024-11-19

[221 rows x 7 columns]
     Symbol     open     high      low    close    volume start_Time
0    TIMKEN  3249.00  3249.00  3207.00  3232.00   16655.0 2024-01-01
1    TIMKEN  3240.00  3240.00  3155.00  3180.95   21545.0 2024-01-02
2    TIMKEN  3194.00  3195.00  3132.05  3151.55   18268.0 2024-01-03
3    TIMKEN  3151.55  3239.95  3146.00  3220.50   39542.0 2024-01-04
4    TIMKEN  3237.50  3251.00  3195.00  3245.30   21781.0 2024-01-05
..      ...      ...      ...      ...      ...       ...        ...
216  TIMKEN  3394.65  3413.85  3321.50  3345.85   46153.0 2024-11-12
217  TIMKEN  3337.65  3347.95  3269.25  3329.15   40109.0 2024-11-13
218  TIMKEN  3340.00  3369.70  3189.95  3237.55  215230.0 2024-11-14
219  TIMKEN  3203.80  3220.20  3171.50  3190.55   42689.0 2024-11-18
220  TIMKEN  3185.00  3290.00  3177.35  3271.05   90745.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close    volume start_Time
0    DATAPATTNS  1862.00  1869.45  1830.00  1840.90  404794.0 2024-01-01
1    DATAPATTNS  1849.65  1926.80  1849.65  1898.80  363749.0 2024-01-02
2    DATAPATTNS  1911.40  1916.80  1849.50  1855.95  151537.0 2024-01-03
3    DATAPATTNS  1874.65  1891.35  1866.05  1879.30  213136.0 2024-01-04
4    DATAPATTNS  1900.00  1922.75  1877.00  1903.45  116200.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  DATAPATTNS  2280.00  2349.85  2213.05  2260.60  552146.0 2024-11-12
217  DATAPATTNS  2260.00  2260.00  2165.00  2172.15  174635.0 2024-11-13
218  DATAPATTNS  2172.15  2213.95  2146.95  2166.65  162032.0 2024-11-14
219  DATAPATTNS  2170.00  2198.95  2145.05  2162.65  119899.0 2024-11-18
220  DATAPATTNS  2177.40  2324.25  2172.95  2291.35  661682.0 2024-11-19

[221 rows x 7 columns]
        Symbol    open    high     low   close     volume start_Time
0    REDINGTON  177.25  177.70  174.50  175.00   747804.0 2024-01-01
1    REDINGTON  175.00  178.30  174.50  176.75  1086891.0 2024-01-02
2    REDINGTON  177.00  178.40  174.05  175.60  1702463.0 2024-01-03
3    REDINGTON  176.00  176.90  174.50  174.80  1439024.0 2024-01-04
4    REDINGTON  175.25  176.30  174.40  175.40  1399990.0 2024-01-05
..         ...     ...     ...     ...     ...        ...        ...
216  REDINGTON  192.15  193.83  188.80  189.92  1195825.0 2024-11-12
217  REDINGTON  187.05  187.80  182.36  186.18  1351488.0 2024-11-13
218  REDINGTON  186.18  198.00  186.15  193.37  6865328.0 2024-11-14
219  REDINGTON  193.00  194.89  189.86  191.23  1142125.0 2024-11-18
220  REDINGTON  192.85  196.99  190.53  193.88  1174413.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close      volume start_Time
0      PFC  383.90  400.00  381.00  395.05  15293334.0 2024-01-01
1      PFC  395.00  395.25  382.75  389.65  11799148.0 2024-01-02
2      PFC  389.00  401.30  385.00  393.10  13107047.0 2024-01-03
3      PFC  397.80  409.00  397.10  405.75  19291259.0 2024-01-04
4      PFC  407.70  408.35  398.10  404.00   7735119.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216    PFC  485.00  486.65  465.50  467.15  12030749.0 2024-11-12
217    PFC  469.10  472.00  453.30  461.45  12532360.0 2024-11-13
218    PFC  463.15  467.65  451.80  454.70   8930823.0 2024-11-14
219    PFC  461.95  468.40  456.15  459.20   9440643.0 2024-11-18
220    PFC  470.00  479.50  467.05  471.40  16795032.0 2024-11-19

[221 rows x 7 columns]
         Symbol    open    high     low   close     volume start_Time
0    RAJESHEXPO  367.00  379.65  366.65  377.50  1160006.0 2024-01-01
1    RAJESHEXPO  379.85  379.85  368.50  372.90   717289.0 2024-01-02
2    RAJESHEXPO  373.00  376.00  370.00  372.60   630828.0 2024-01-03
3    RAJESHEXPO  374.85  375.25  370.60  371.35   605841.0 2024-01-04
4    RAJESHEXPO  373.90  379.70  371.60  374.45   733452.0 2024-01-05
..          ...     ...     ...     ...     ...        ...        ...
216  RAJESHEXPO  253.00  256.30  245.00  246.85   344215.0 2024-11-12
217  RAJESHEXPO  247.10  247.80  232.60  234.10   817264.0 2024-11-13
218  RAJESHEXPO  235.00  239.95  233.40  235.50   482141.0 2024-11-14
219  RAJESHEXPO  239.00  252.35  236.50  238.70  1659889.0 2024-11-18
220  RAJESHEXPO  240.00  243.40  235.60  237.20   499567.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol     open     high      low    close     volume start_Time
0    GLENMARK   854.00   861.90   848.00   855.65   415165.0 2024-01-01
1    GLENMARK   855.70   901.80   854.70   888.80  3980406.0 2024-01-02
2    GLENMARK   896.00   903.40   883.00   897.90  1793431.0 2024-01-03
3    GLENMARK   898.05   913.55   890.85   898.40   712492.0 2024-01-04
4    GLENMARK   900.00   905.00   882.05   892.70   438207.0 2024-01-05
..        ...      ...      ...      ...      ...        ...        ...
216  GLENMARK  1475.00  1632.65  1475.00  1577.05  1108375.0 2024-11-12
217  GLENMARK  1566.00  1577.45  1521.40  1539.40   992489.0 2024-11-13
218  GLENMARK  1545.00  1560.00  1524.00  1533.70   460222.0 2024-11-14
219  GLENMARK  1550.00  1597.05  1478.10  1485.75  1439031.0 2024-11-18
220  GLENMARK  1491.75  1517.70  1473.35  1492.65   732905.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close      volume start_Time
0      FSL  185.10  186.35  183.10  185.15    981796.0 2024-01-01
1      FSL  185.25  186.30  181.80  184.15   1626019.0 2024-01-02
2      FSL  183.00  186.75  182.15  186.00   1096851.0 2024-01-03
3      FSL  186.25  192.55  186.25  189.15   3189972.0 2024-01-04
4      FSL  189.00  198.45  188.45  193.25   6971072.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216    FSL  360.00  383.45  354.10  356.75  13764343.0 2024-11-12
217    FSL  356.75  360.00  346.45  349.45   4380015.0 2024-11-13
218    FSL  352.50  363.20  337.70  340.15   5104224.0 2024-11-14
219    FSL  341.35  347.95  335.15  339.10   3176631.0 2024-11-18
220    FSL  340.05  352.05  337.50  339.90   3080925.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol    open    high     low   close     volume start_Time
0    INDIANB  422.00  424.70  419.15  422.00  2159907.0 2024-01-01
1    INDIANB  423.00  423.80  408.60  416.30  3268709.0 2024-01-02
2    INDIANB  419.00  423.00  415.20  421.30  4194188.0 2024-01-03
3    INDIANB  422.00  434.20  422.00  432.40  3583823.0 2024-01-04
4    INDIANB  435.00  441.95  432.00  434.40  3117731.0 2024-01-05
..       ...     ...     ...     ...     ...        ...        ...
216  INDIANB  563.00  574.00  559.00  564.00   426370.0 2024-11-12
217  INDIANB  554.05  559.70  538.05  540.05   544053.0 2024-11-13
218  INDIANB  536.00  549.50  533.05  536.95   483595.0 2024-11-14
219  INDIANB  539.00  539.75  520.30  527.85  2048986.0 2024-11-18
220  INDIANB  524.00  535.70  520.15  523.05  1297484.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close     volume start_Time
0     HSCL  310.85  339.50  309.50  331.40  6026134.0 2024-01-01
1     HSCL  332.65  338.90  326.05  334.80  2097925.0 2024-01-02
2     HSCL  334.90  335.35  328.50  332.35  1004480.0 2024-01-03
3     HSCL  334.05  365.55  332.85  365.55  5282573.0 2024-01-04
4     HSCL  370.50  394.00  368.90  386.90  6587811.0 2024-01-05
..     ...     ...     ...     ...     ...        ...        ...
216   HSCL  545.95  552.50  529.25  532.45   636320.0 2024-11-12
217   HSCL  526.85  532.00  499.35  503.60  1579487.0 2024-11-13
218   HSCL  503.60  517.75  492.55  497.75  1276367.0 2024-11-14
219   HSCL  497.75  509.75  472.00  498.35  1573000.0 2024-11-18
220   HSCL  500.00  514.70  488.95  493.45   782127.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol   open   high    low  close        volume start_Time
0     IDEA  16.20  18.40  15.55  17.00  1.784392e+09 2024-01-01
1     IDEA  17.10  17.80  15.95  16.05  1.095516e+09 2024-01-02
2     IDEA  15.90  16.45  15.60  15.85  5.987265e+08 2024-01-03
3     IDEA  15.90  17.20  15.70  16.80  5.350384e+08 2024-01-04
4     IDEA  17.10  17.65  16.75  17.10  6.867776e+08 2024-01-05
..     ...    ...    ...    ...    ...           ...        ...
216   IDEA   7.80   7.95   7.63   7.67  2.803210e+08 2024-11-12
217   IDEA   7.66   7.69   7.33   7.36  4.240790e+08 2024-11-13
218   IDEA   7.40   7.62   7.32   7.34  4.175661e+08 2024-11-14
219   IDEA   7.47   7.53   7.19   7.25  4.189158e+08 2024-11-18
220   IDEA   7.25   7.39   7.07   7.10  3.385855e+08 2024-11-19

[221 rows x 7 columns]
      Symbol      open      high       low     close   volume start_Time
0    PAGEIND  38516.00  38984.25  38500.00  38773.45  12899.0 2024-01-01
1    PAGEIND  38898.90  39246.35  38111.00  39189.20  27375.0 2024-01-02
2    PAGEIND  39152.00  39374.00  38704.05  38800.90  11523.0 2024-01-03
3    PAGEIND  38899.00  39150.00  38554.85  39074.45  18182.0 2024-01-04
4    PAGEIND  39250.00  39250.00  38660.00  38908.35  23336.0 2024-01-05
..       ...       ...       ...       ...       ...      ...        ...
216  PAGEIND  47573.05  48000.00  47021.40  47107.20  30704.0 2024-11-12
217  PAGEIND  47139.55  47334.55  45612.05  45856.80  41753.0 2024-11-13
218  PAGEIND  45979.95  46158.00  45213.40  45377.25  23936.0 2024-11-14
219  PAGEIND  45450.00  45646.15  43969.55  44098.05  15803.0 2024-11-18
220  PAGEIND  44300.00  45280.00  44300.00  44606.85  34629.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

     Symbol     open     high      low    close    volume start_Time
0    ASTRAL  1909.00  1913.95  1893.05  1904.95  238462.0 2024-01-01
1    ASTRAL  1903.00  1907.05  1868.00  1899.70  279468.0 2024-01-02
2    ASTRAL  1898.00  1898.00  1853.45  1861.10  450711.0 2024-01-03
3    ASTRAL  1865.95  1872.40  1840.00  1853.30  448704.0 2024-01-04
4    ASTRAL  1860.10  1870.45  1835.50  1841.15  391876.0 2024-01-05
..      ...      ...      ...      ...      ...       ...        ...
216  ASTRAL  1725.00  1751.75  1711.85  1742.65  686585.0 2024-11-12
217  ASTRAL  1742.65  1754.60  1721.30  1730.10  573401.0 2024-11-13
218  ASTRAL  1726.00  1742.25  1713.90  1731.15  342533.0 2024-11-14
219  ASTRAL  1727.30  1735.75  1695.50  1716.10  504872.0 2024-11-18
220  ASTRAL  1716.00  1759.65  1715.95  1729.15  390428.0 2024-11-19

[221 rows x 7 columns]
        Symbol     open     high      low    close    volume start_Time
0    BALAMINES  2675.00  2735.00  2657.30  2697.65  237557.0 2024-01-01
1    BALAMINES  2697.65  2719.50  2590.00  2611.35  236949.0 2024-01-02
2    BALAMINES  2625.00  2625.95  2580.25  2591.70   83053.0 2024-01-03
3    BALAMINES  2608.00  2710.00  2595.05  2672.20  257622.0 2024-01-04
4    BALAMINES  2689.00  2689.00  2607.95  2630.35  103094.0 2024-01-05
..         ...      ...      ...      ...      ...       ...        ...
216  BALAMINES  2058.00  2075.95  2015.05  2033.35   19959.0 2024-11-12
217  BALAMINES  2012.00  2048.95  1990.00  1996.90   33281.0 2024-11-13
218  BALAMINES  1996.90  2056.75  1990.15  2031.65   38886.0 2024-11-14
219  BALAMINES  2031.65  2031.65  1950.05  1973.85   65136.0 2024-11-18
220  BALAMINES  1994.40  2033.00  1981.50  1995.60   29433.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close     volume start_Time
0    PHOENIXLTD  1120.00  1132.45  1109.00  1127.05   102062.0 2024-01-01
1    PHOENIXLTD  1132.70  1139.95  1114.00  1117.68   124152.0 2024-01-02
2    PHOENIXLTD  1117.68  1149.50  1116.05  1145.23   196999.0 2024-01-03
3    PHOENIXLTD  1160.00  1193.00  1149.03  1182.25   287814.0 2024-01-04
4    PHOENIXLTD  1185.00  1299.00  1184.50  1244.43  1193179.0 2024-01-05
..          ...      ...      ...      ...      ...        ...        ...
216  PHOENIXLTD  1471.05  1518.95  1451.00  1493.05   448658.0 2024-11-12
217  PHOENIXLTD  1471.00  1480.00  1433.00  1446.00   361711.0 2024-11-13
218  PHOENIXLTD  1459.85  1461.95  1392.10  1397.95   638027.0 2024-11-14
219  PHOENIXLTD  1420.25  1483.50  1406.30  1461.80   990291.0 2024-11-18
220  PHOENIXLTD  1463.40  1499.90  1450.85  1481.35   355739.0 2024-11-19

[221 rows x 7 columns]
     Symbol    open    high     low  close     volume start_Time
0    FORTIS  424.70  448.80  422.00  439.6  3687892.0 2024-01-01
1    FORTIS  443.70  445.05  432.05  435.5  1296066.0 2024-01-02
2    FORTIS  433.20  434.30  422.40  428.8  1142771.0 2024-01-03
3    FORTIS  430.00  430.80  421.05  428.9  1103306.0 2024-01-04
4    FORTIS  430.05  438.00  425.70  434.3  1158967.0 2024-01-05
..      ...     ...     ...     ...    ...        ...        ...
216  FORTIS  625.00  658.85  625.00  643.2  2813521.0 2024-11-12
217  FORTIS  639.90  639.95  616.00  620.4   877467.0 2024-11-13
218  FORTIS  621.90  648.55  620.80  639.1  1899805.0 2024-11-14
219  FORTIS  642.00  653.00  627.05  648.5   942545.0 2024-11-18
220  FORTIS  649.35  662.00  645.00  657.8  1285256.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close    volume start_Time
0    NAVINFLUOR  3852.00  3883.45  3832.05  3857.55   70286.0 2024-01-01
1    NAVINFLUOR  3860.00  3897.40  3811.25  3856.85   90311.0 2024-01-02
2    NAVINFLUOR  3864.60  3882.00  3835.15  3867.85   74420.0 2024-01-03
3    NAVINFLUOR  3870.00  3882.85  3779.60  3796.20  296664.0 2024-01-04
4    NAVINFLUOR  3799.95  3829.90  3782.60  3822.65  150782.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  NAVINFLUOR  3469.90  3492.10  3306.00  3322.05   60245.0 2024-11-12
217  NAVINFLUOR  3319.00  3320.35  3253.85  3267.80  126831.0 2024-11-13
218  NAVINFLUOR  3270.00  3344.90  3204.60  3309.90   63191.0 2024-11-14
219  NAVINFLUOR  3310.00  3317.10  3224.55  3259.75   75198.0 2024-11-18
220  NAVINFLUOR  3275.00  3393.65  3265.05  3338.05  125094.0 2024-11-19

[221 rows x 7 columns]
       Symbol    open    high     low   close     volume start_Time
0    INOXWIND  126.00  133.99  126.00  131.09  2443885.0 2024-01-01
1    INOXWIND  131.00  134.00  126.43  131.91  2070821.0 2024-01-02
2    INOXWIND  131.45  135.04  126.28  128.58  2303164.0 2024-01-03
3    INOXWIND  129.19  130.50  126.28  129.53  1550005.0 2024-01-04
4    INOXWIND  129.64  131.45  126.34  127.54  1002160.0 2024-01-05
..        ...     ...     ...     ...     ...        ...        ...
216  INOXWIND  206.00  208.60  199.20  200.00  3667768.0 2024-11-12
217  INOXWIND  200.00  200.00  184.72  186.85  8379778.0 2024-11-13
218  INOXWIND  185.91  193.80  185.66  190.03  6106680.0 2024-11-14
219  INOXWIND  190.02  191.90  185.50  188.87  5275304.0 2024-11-18
220  INOXWIND  192.00  195.64  189.02  190.07  4661001.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close      volume start_Time
0      DLF  727.20  731.00  721.45  723.60   1400824.0 2024-01-01
1      DLF  725.80  725.80  704.45  713.85   2394602.0 2024-01-02
2      DLF  715.25  720.85  706.70  715.65   1829817.0 2024-01-03
3      DLF  718.00  764.75  717.50  761.40  13312567.0 2024-01-04
4      DLF  760.00  770.00  747.85  752.95   5929704.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216    DLF  781.00  788.50  762.10  764.85   2258658.0 2024-11-12
217    DLF  762.00  769.50  743.95  748.55   4136515.0 2024-11-13
218    DLF  752.05  771.00  751.00  762.70   1985408.0 2024-11-14
219    DLF  779.95  779.95  756.10  759.60   2762739.0 2024-11-18
220    DLF  763.05  777.20  758.80  763.15   1919376.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close      volume start_Time
0    SPARC  287.95  310.00  287.95  307.50   7510877.0 2024-01-01
1    SPARC  309.00  344.70  308.10  338.40  18403129.0 2024-01-02
2    SPARC  340.00  399.00  339.00  387.25  26734140.0 2024-01-03
3    SPARC  390.35  401.20  374.00  384.90   4400438.0 2024-01-04
4    SPARC  387.00  423.35  385.00  420.55   7511505.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216  SPARC  206.11  209.22  203.20  205.37    366514.0 2024-11-12
217  SPARC  205.05  205.89  197.55  198.71    329396.0 2024-11-13
218  SPARC  198.99  201.25  192.97  197.38    448958.0 2024-11-14
219  SPARC  198.10  199.57  193.00  194.36    390106.0 2024-11-18
220  SPARC  195.50  199.76  195.00  195.98    152116.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

        Symbol    open    high     low   close     volume start_Time
0    ZYDUSLIFE  688.10  707.20  685.00  699.15  2371842.0 2024-01-01
1    ZYDUSLIFE  707.45  715.00  699.65  712.25  2433838.0 2024-01-02
2    ZYDUSLIFE  712.40  716.00  708.95  710.40   921911.0 2024-01-03
3    ZYDUSLIFE  712.00  715.85  707.00  709.15  1116138.0 2024-01-04
4    ZYDUSLIFE  713.00  715.35  706.00  714.25  1041423.0 2024-01-05
..         ...     ...     ...     ...     ...        ...        ...
216  ZYDUSLIFE  970.00  990.00  933.00  949.75  3008146.0 2024-11-12
217  ZYDUSLIFE  958.35  968.95  946.85  963.75  2093578.0 2024-11-13
218  ZYDUSLIFE  957.20  976.80  953.50  957.40   840848.0 2024-11-14
219  ZYDUSLIFE  964.05  966.00  938.65  944.70  1050199.0 2024-11-18
220  ZYDUSLIFE  945.00  955.15  941.45  947.60   605361.0 2024-11-19

[221 rows x 7 columns]
         Symbol    open    high     low   close     volume start_Time
0    AVANTIFEED  422.75  438.70  421.30  437.40  1272023.0 2024-01-01
1    AVANTIFEED  437.40  439.90  424.30  430.85   358313.0 2024-01-02
2    AVANTIFEED  429.60  458.50  429.60  449.20  1516014.0 2024-01-03
3    AVANTIFEED  449.20  455.95  442.00  444.60   554312.0 2024-01-04
4    AVANTIFEED  444.00  453.90  444.00  450.35   420794.0 2024-01-05
..          ...     ...     ...     ...     ...        ...        ...
216  AVANTIFEED  593.30  611.00  585.00  589.10   417046.0 2024-11-12
217  AVANTIFEED  589.10  608.40  562.80  565.40   434005.0 2024-11-13
218  AVANTIFEED  565.55  592.90  564.65  581.35   321039.0 2024-11-14
219  AVANTIFEED  610.40  628.65  591.15  601.30  4355553.0 2024-11-18
220  AVANTIFEED  609.85  622.60  601.40  618.45   795707.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

        Symbol   open   high    low  close      volume start_Time
0    CENTRALBK  50.25  51.40  49.70  50.35  14747454.0 2024-01-01
1    CENTRALBK  50.35  52.20  49.90  51.10  33188408.0 2024-01-02
2    CENTRALBK  51.00  52.95  50.65  51.95  49402075.0 2024-01-03
3    CENTRALBK  52.15  53.20  52.00  52.50  21798368.0 2024-01-04
4    CENTRALBK  52.75  53.35  51.25  51.90  20211613.0 2024-01-05
..         ...    ...    ...    ...    ...         ...        ...
216  CENTRALBK  55.70  56.60  54.56  54.90   2397059.0 2024-11-12
217  CENTRALBK  53.00  54.63  51.80  52.02   4550933.0 2024-11-13
218  CENTRALBK  52.21  53.18  51.76  51.92   3689333.0 2024-11-14
219  CENTRALBK  52.08  54.18  50.91  52.86   5643790.0 2024-11-18
220  CENTRALBK  53.00  54.73  52.03  52.65   5498164.0 2024-11-19

[221 rows x 7 columns]
      Symbol    open    high     low   close     volume start_Time
0    KPRMILL  824.80  826.45  808.00  811.05   218813.0 2024-01-01
1    KPRMILL  812.00  816.80  790.25  791.80   490324.0 2024-01-02
2    KPRMILL  791.10  794.90  767.75  774.80   491746.0 2024-01-03
3    KPRMILL  768.00  775.00  762.00  764.40   778752.0 2024-01-04
4    KPRMILL  770.35  772.50  752.55  761.65  1006128.0 2024-01-05
..       ...     ...     ...     ...     ...        ...        ...
216  KPRMILL  930.20  940.00  917.15  929.40    83620.0 2024-11-12
217  KPRMILL  915.45  923.40  871.40  879.05   168665.0 2024-11-13
218  KPRMILL  880.00  928.00  879.05  919.95   248438.0 2024-11-14
219  KPRMILL  925.00  932.45  890.00  898.20   164995.0 2024-11-18
220  KPRMILL  901.25  940.25  901.25  932.10   185178.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol    open    high     low   close     volume start_Time
0    CIEINDIA  472.30  498.50  471.00  495.80  1838941.0 2024-01-01
1    CIEINDIA  495.00  497.35  477.35  489.45  1424262.0 2024-01-02
2    CIEINDIA  489.45  492.00  479.35  487.45   552484.0 2024-01-03
3    CIEINDIA  489.85  491.75  481.60  487.35   440878.0 2024-01-04
4    CIEINDIA  487.55  489.80  480.25  484.75   286602.0 2024-01-05
..        ...     ...     ...     ...     ...        ...        ...
216  CIEINDIA  479.15  480.45  470.30  474.10    65447.0 2024-11-12
217  CIEINDIA  471.20  473.30  457.70  470.90   142545.0 2024-11-13
218  CIEINDIA  470.90  481.45  466.75  471.70   415149.0 2024-11-14
219  CIEINDIA  473.05  474.70  459.85  463.80   127443.0 2024-11-18
220  CIEINDIA  465.05  473.75  465.00  467.00    83598.0 2024-11-19

[221 rows x 7 columns]
         Symbol    open    high     low   close     volume start_Time
0    MOTILALOFS  310.21  315.63  306.50  315.01   169397.0 2024-01-01
1    MOTILALOFS  315.03  316.59  306.50  309.95   160712.0 2024-01-02
2    MOTILALOFS  310.00  313.25  308.35  310.59   114018.0 2024-01-03
3    MOTILALOFS  313.00  331.96  312.75  321.91   866683.0 2024-01-04
4    MOTILALOFS  326.25  331.25  320.65  325.49   242986.0 2024-01-05
..          ...     ...     ...     ...     ...        ...        ...
216  MOTILALOFS  983.90  995.70  963.00  969.00  1893071.0 2024-11-12
217  MOTILALOFS  964.50  964.50  892.05  898.80  2915990.0 2024-11-13
218  MOTILALOFS  900.15  938.95  886.65  900.90  2869090.0 2024-11-14
219  MOTILALOFS  910.60  916.35  882.80  888.15  1585350.0 2024-11-18
220  MOTILALOFS  892.05  919.95  891.00  906.30  1746454.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol    open    high     low   close    volume start_Time
0    CSBBANK  418.65  422.00  415.15  417.65  182117.0 2024-01-01
1    CSBBANK  417.00  421.45  412.25  416.70  252364.0 2024-01-02
2    CSBBANK  410.25  418.90  401.90  407.50  737595.0 2024-01-03
3    CSBBANK  410.00  413.70  407.10  409.20  175388.0 2024-01-04
4    CSBBANK  411.85  413.70  405.85  407.50  552185.0 2024-01-05
..       ...     ...     ...     ...     ...       ...        ...
216  CSBBANK  317.45  322.90  315.45  317.25  249988.0 2024-11-12
217  CSBBANK  312.50  315.75  304.10  308.75  171612.0 2024-11-13
218  CSBBANK  305.15  309.30  297.30  299.60  286474.0 2024-11-14
219  CSBBANK  303.30  307.40  297.05  302.05  108828.0 2024-11-18
220  CSBBANK  300.20  308.25  299.90  307.15  101388.0 2024-11-19

[221 rows x 7 columns]
        Symbol    open    high     low   close      volume start_Time
0    POWERGRID  237.90  239.50  236.40  238.25   5952776.0 2024-01-01
1    POWERGRID  240.00  240.10  236.15  237.85   9128513.0 2024-01-02
2    POWERGRID  236.00  238.70  234.60  237.05   8284439.0 2024-01-03
3    POWERGRID  238.00  243.10  237.05  241.45  19663959.0 2024-01-04
4    POWERGRID  242.00  245.00  239.30  241.25  16345257.0 2024-01-05
..         ...     ...     ...     ...     ...         ...        ...
216  POWERGRID  331.50  332.50  321.80  322.70  12069181.0 2024-11-12
217  POWERGRID  322.65  324.60  317.15  318.00  12918639.0 2024-11-13
218  POWERGRID  315.10  318.80  310.60  312.10  12500377.0 2024-11-14
219  POWERGRID  314.00  315.55  310.10  312.05   9408101.0 2024-11-18
220  POWERGRID  313.05  318.25  312.25  315.05  13157158.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol     open     high      low    close     volume start_Time
0    ARE&M   819.65   827.60   816.65   825.05   527034.0 2024-01-01
1    ARE&M   828.95   833.80   807.40   815.50   579382.0 2024-01-02
2    ARE&M   815.50   819.90   807.05   811.25   306106.0 2024-01-03
3    ARE&M   812.00   826.95   811.55   816.80   401353.0 2024-01-04
4    ARE&M   821.65   843.00   818.10   834.95  1134799.0 2024-01-05
..     ...      ...      ...      ...      ...        ...        ...
216  ARE&M  1289.90  1305.00  1263.00  1269.65   387984.0 2024-11-12
217  ARE&M  1280.00  1304.45  1238.00  1246.40   564205.0 2024-11-13
218  ARE&M  1254.80  1269.95  1245.00  1255.60   355341.0 2024-11-14
219  ARE&M  1259.25  1275.60  1221.00  1224.75   458795.0 2024-11-18
220  ARE&M  1230.00  1278.35  1230.00  1247.80   528143.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open     high      low    close    volume start_Time
0    ROUTE  1608.55  1684.00  1590.70  1668.75  685849.0 2024-01-01
1    ROUTE  1674.25  1735.00  1660.00  1679.15  811967.0 2024-01-02
2    ROUTE  1675.90  1689.40  1655.10  1680.20  171190.0 2024-01-03
3    ROUTE  1685.00  1687.00  1636.00  1646.20  147222.0 2024-01-04
4    ROUTE  1646.10  1703.35  1643.50  1669.90  169901.0 2024-01-05
..     ...      ...      ...      ...      ...       ...        ...
216  ROUTE  1460.70  1484.45  1450.00  1453.50   48004.0 2024-11-12
217  ROUTE  1454.70  1457.70  1420.00  1424.55   58797.0 2024-11-13
218  ROUTE  1424.50  1444.25  1409.30  1414.00   46907.0 2024-11-14
219  ROUTE  1415.00  1418.00  1334.00  1392.15  163469.0 2024-11-18
220  ROUTE  1388.05  1443.70  1388.05  1414.85   48529.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close    volume start_Time
0    APOLLOHOSP  5741.00  5765.00  5707.85  5750.05  127030.0 2024-01-01
1    APOLLOHOSP  5738.10  5782.65  5680.00  5746.35  166449.0 2024-01-02
2    APOLLOHOSP  5730.00  5786.00  5673.05  5768.30  198997.0 2024-01-03
3    APOLLOHOSP  5768.30  5839.95  5731.50  5762.20  220702.0 2024-01-04
4    APOLLOHOSP  5762.20  5808.80  5715.00  5754.25  144894.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  APOLLOHOSP  7161.25  7232.85  7001.00  7019.55  194183.0 2024-11-12
217  APOLLOHOSP  6970.00  6998.20  6830.45  6858.85  299775.0 2024-11-13
218  APOLLOHOSP  6860.00  6908.00  6827.05  6860.65  192648.0 2024-11-14
219  APOLLOHOSP  6874.45  6874.45  6694.55  6741.90  268706.0 2024-11-18
220  APOLLOHOSP  6750.00  6796.90  6661.20  6686.90  290018.0 2024-11-19

[221 rows x 7 columns]
         Symbol    open    high     low   close     volume start_Time
0    APOLLOTYRE  456.45  456.45  450.55  453.25  1679801.0 2024-01-01
1    APOLLOTYRE  454.00  457.95  448.25  456.45  2359662.0 2024-01-02
2    APOLLOTYRE  456.00  460.55  453.55  457.75  1161847.0 2024-01-03
3    APOLLOTYRE  460.00  460.00  447.25  448.90  2539469.0 2024-01-04
4    APOLLOTYRE  452.55  465.00  450.20  460.50  4674473.0 2024-01-05
..          ...     ...     ...     ...     ...        ...        ...
216  APOLLOTYRE  483.30  487.35  470.35  471.35  1268350.0 2024-11-12
217  APOLLOTYRE  468.85  472.35  454.90  456.60  1567349.0 2024-11-13
218  APOLLOTYRE  449.95  478.55  448.15  475.30  4069068.0 2024-11-14
219  APOLLOTYRE  471.30  477.90  465.60  472.05  1013363.0 2024-11-18
220  APOLLOTYRE  471.80  491.35  471.00  486.25  1562532.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol    open    high     low   close      volume start_Time
0    ASHOKLEY  182.50  188.05  181.65  185.95  39354793.0 2024-01-01
1    ASHOKLEY  187.50  189.60  179.70  180.40  34044615.0 2024-01-02
2    ASHOKLEY  182.10  182.10  177.95  179.70  11113724.0 2024-01-03
3    ASHOKLEY  181.40  181.40  179.55  179.90  12256991.0 2024-01-04
4    ASHOKLEY  181.00  182.15  178.20  179.45  12044079.0 2024-01-05
..        ...     ...     ...     ...     ...         ...        ...
216  ASHOKLEY  225.20  226.00  219.16  221.12   8442058.0 2024-11-12
217  ASHOKLEY  218.00  220.18  214.26  217.42   9137458.0 2024-11-13
218  ASHOKLEY  217.42  219.59  214.82  217.57   4818367.0 2024-11-14
219  ASHOKLEY  217.56  221.24  215.75  220.25   5621936.0 2024-11-18
220  ASHOKLEY  217.50  225.73  216.28  221.34   8122856.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close      volume start_Time
0      IEX  169.10  173.35  166.45  168.00  29812120.0 2024-01-01
1      IEX  168.50  168.70  162.05  165.95  22328576.0 2024-01-02
2      IEX  164.10  165.45  162.50  163.15   9076268.0 2024-01-03
3      IEX  166.00  167.90  164.40  165.95  17806032.0 2024-01-04
4      IEX  166.85  167.35  163.00  164.20  10729223.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216    IEX  170.99  171.30  165.50  166.23   5484152.0 2024-11-12
217    IEX  166.00  166.27  162.00  162.72   4718700.0 2024-11-13
218    IEX  162.00  164.20  161.10  161.51   3791381.0 2024-11-14
219    IEX  162.50  163.23  159.40  161.32   3637405.0 2024-11-18
220    IEX  162.00  165.76  161.50  162.49   4422526.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close     volume start_Time
0    ASIANPAINT  3403.00  3411.80  3389.15  3396.10   283951.0 2024-01-01
1    ASIANPAINT  3396.00  3398.90  3345.00  3391.35   552394.0 2024-01-02
2    ASIANPAINT  3391.35  3399.00  3365.00  3373.60   379131.0 2024-01-03
3    ASIANPAINT  3372.00  3401.25  3363.80  3379.95   777127.0 2024-01-04
4    ASIANPAINT  3379.95  3380.40  3348.00  3355.55   416956.0 2024-01-05
..          ...      ...      ...      ...      ...        ...        ...
216  ASIANPAINT  2535.00  2535.00  2470.00  2474.85  3445983.0 2024-11-12
217  ASIANPAINT  2470.00  2498.00  2451.10  2470.50  1803849.0 2024-11-13
218  ASIANPAINT  2482.80  2501.75  2466.20  2483.15  1206975.0 2024-11-14
219  ASIANPAINT  2520.00  2520.00  2470.80  2483.70   945477.0 2024-11-18
220  ASIANPAINT  2488.00  2503.20  2472.35  2483.70   941558.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open     high      low    close   volume start_Time
0     ATUL  7198.00  7210.00  7100.30  7169.10  29878.0 2024-01-01
1     ATUL  7169.95  7220.00  7064.05  7167.65  27505.0 2024-01-02
2     ATUL  7195.00  7225.00  7146.00  7161.35  21035.0 2024-01-03
3     ATUL  7200.00  7216.50  7060.05  7073.60  18692.0 2024-01-04
4     ATUL  7180.00  7180.00  7000.00  7028.75  30268.0 2024-01-05
..     ...      ...      ...      ...      ...      ...        ...
216   ATUL  7530.15  7657.10  7378.15  7423.25  89187.0 2024-11-12
217   ATUL  7400.00  7429.95  7200.90  7225.50  57273.0 2024-11-13
218   ATUL  7176.00  7380.00  7176.00  7303.20  46953.0 2024-11-14
219   ATUL  7303.20  7330.00  7148.00  7175.10  21447.0 2024-11-18
220   ATUL  7242.00  7370.75  7230.05  7283.85  41847.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close     volume start_Time
0    AUROPHARMA  1085.05  1093.95  1077.05  1080.15   985073.0 2024-01-01
1    AUROPHARMA  1082.05  1110.80  1082.05  1091.95  3350206.0 2024-01-02
2    AUROPHARMA  1094.00  1100.25  1077.65  1091.30  1736602.0 2024-01-03
3    AUROPHARMA  1093.00  1122.00  1090.10  1118.45  1766911.0 2024-01-04
4    AUROPHARMA  1118.50  1129.35  1101.00  1123.95  1501322.0 2024-01-05
..          ...      ...      ...      ...      ...        ...        ...
216  AUROPHARMA  1289.05  1302.45  1258.00  1267.40  1007201.0 2024-11-12
217  AUROPHARMA  1273.80  1273.80  1240.55  1249.45   803439.0 2024-11-13
218  AUROPHARMA  1250.40  1272.25  1241.85  1249.00   832369.0 2024-11-14
219  AUROPHARMA  1245.20  1254.75  1232.40  1235.40  1362480.0 2024-11-18
220  AUROPHARMA  1239.15  1267.35  1232.05  1250.10   879809.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close     volume start_Time
0    GICRE  308.95  315.90  307.05  311.95   837234.0 2024-01-01
1    GICRE  311.95  315.90  307.30  309.60   661388.0 2024-01-02
2    GICRE  309.60  314.10  307.25  310.65   907867.0 2024-01-03
3    GICRE  311.65  324.80  311.45  316.60  2845106.0 2024-01-04
4    GICRE  319.00  323.00  311.05  314.25  1156902.0 2024-01-05
..     ...     ...     ...     ...     ...        ...        ...
216  GICRE  375.00  375.80  364.90  366.30   323738.0 2024-11-12
217  GICRE  365.50  366.30  348.00  348.70   423260.0 2024-11-13
218  GICRE  351.95  363.55  348.00  354.20   822267.0 2024-11-14
219  GICRE  352.25  362.50  352.20  358.15   605534.0 2024-11-18
220  GICRE  361.15  374.55  360.00  371.30   766042.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol      open      high       low     close    volume start_Time
0    BAJAJHLDNG   7710.00   7799.00   7700.00   7763.65   17080.0 2024-01-01
1    BAJAJHLDNG   7810.00   7848.95   7756.05   7817.75   30786.0 2024-01-02
2    BAJAJHLDNG   7829.95   8220.55   7711.20   8103.40   86219.0 2024-01-03
3    BAJAJHLDNG   8080.00   8246.00   7968.05   8209.95   46150.0 2024-01-04
4    BAJAJHLDNG   8252.00   8275.00   8020.00   8066.10   26527.0 2024-01-05
..          ...       ...       ...       ...       ...       ...        ...
216  BAJAJHLDNG  10850.00  10888.70  10624.00  10794.15   39197.0 2024-11-12
217  BAJAJHLDNG  10655.00  10750.50  10469.05  10528.65   21623.0 2024-11-13
218  BAJAJHLDNG  10530.00  11154.50  10249.00  10850.10  106278.0 2024-11-14
219  BAJAJHLDNG  10860.00  11005.10  10605.35  10684.75   39537.0 2024-11-18
220  BAJAJHLDNG  10760.00  10799.90  10520.05  10555.30   18870.0 2024-11-19

[221 rows x 7 columns]
      Symbol     open     high      low    close    volume start_Time
0    TIINDIA  3575.00  3604.95  3551.10  3588.10   40530.0 2024-01-01
1    TIINDIA  3593.80  3609.95  3539.25  3602.25   99399.0 2024-01-02
2    TIINDIA  3609.00  3615.00  3483.50  3541.85  191295.0 2024-01-03
3    TIINDIA  3539.00  3634.50  3496.10  3559.65  450305.0 2024-01-04
4    TIINDIA  3559.65  3824.00  3559.65  3751.05  441297.0 2024-01-05
..       ...      ...      ...      ...      ...       ...        ...
216  TIINDIA  3624.85  3695.25  3540.10  3561.80  132038.0 2024-11-12
217  TIINDIA  3562.15  3585.00  3433.00  3447.65  149985.0 2024-11-13
218  TIINDIA  3466.20  3542.70  3361.60  3440.50  208267.0 2024-11-14
219  TIINDIA  3460.00  3482.00  3370.00  3430.60  411614.0 2024-11-18
220  TIINDIA  3434.10  3668.75  3415.00  3611.30  276375.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close     volume start_Time
0    BAJFINANCE  7336.95  7336.95  7273.00  7299.05   331489.0 2024-01-01
1    BAJFINANCE  7324.00  7445.10  7280.05  7430.05  1112990.0 2024-01-02
2    BAJFINANCE  7444.95  7485.85  7368.20  7384.80   553405.0 2024-01-03
3    BAJFINANCE  7560.00  7733.95  7560.00  7705.55  2911879.0 2024-01-04
4    BAJFINANCE  7734.95  7789.00  7673.10  7711.15  1052601.0 2024-01-05
..          ...      ...      ...      ...      ...        ...        ...
216  BAJFINANCE  6819.00  6836.85  6615.00  6638.20  1057233.0 2024-11-12
217  BAJFINANCE  6635.00  6702.25  6526.60  6566.00   867347.0 2024-11-13
218  BAJFINANCE  6572.30  6639.45  6530.00  6549.15   527703.0 2024-11-14
219  BAJFINANCE  6633.00  6657.00  6555.00  6567.95   596535.0 2024-11-18
220  BAJFINANCE  6594.35  6644.80  6561.00  6595.30   804046.0 2024-11-19

[221 rows x 7 columns]
       Symbol     open     high      low    close     volume start_Time
0    ANGELONE  3484.00  3618.90  3463.80  3583.30   313160.0 2024-01-01
1    ANGELONE  3600.00  3642.00  3483.25  3535.95   286624.0 2024-01-02
2    ANGELONE  3516.95  3524.00  3465.00  3479.40   181722.0 2024-01-03
3    ANGELONE  3596.00  3750.00  3550.05  3582.05   846399.0 2024-01-04
4    ANGELONE  3605.00  3772.80  3605.00  3744.10   338899.0 2024-01-05
..        ...      ...      ...      ...      ...        ...        ...
216  ANGELONE  2798.00  2838.95  2720.00  2739.80   831226.0 2024-11-12
217  ANGELONE  2730.00  2748.40  2605.00  2614.05  1103902.0 2024-11-13
218  ANGELONE  2642.00  2782.35  2623.00  2695.65  1679808.0 2024-11-14
219  ANGELONE  2705.95  2717.85  2623.00  2669.05   839861.0 2024-11-18
220  ANGELONE  2685.00  2754.00  2650.00  2677.45   815585.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close    volume start_Time
0    BALKRISIND  2572.00  2596.00  2566.55  2576.25  119304.0 2024-01-01
1    BALKRISIND  2593.00  2593.00  2516.25  2521.75  307356.0 2024-01-02
2    BALKRISIND  2529.80  2534.75  2490.00  2505.90  142806.0 2024-01-03
3    BALKRISIND  2509.55  2517.40  2490.00  2500.10  120156.0 2024-01-04
4    BALKRISIND  2509.95  2604.45  2509.70  2578.55  339025.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  BALKRISIND  2794.00  2823.15  2730.00  2742.25   96922.0 2024-11-12
217  BALKRISIND  2715.00  2746.25  2644.35  2652.70  683520.0 2024-11-13
218  BALKRISIND  2675.00  2760.00  2661.15  2738.70  259506.0 2024-11-14
219  BALKRISIND  2724.75  2769.95  2719.95  2746.75   95252.0 2024-11-18
220  BALKRISIND  2730.50  2811.95  2729.15  2769.65  112631.0 2024-11-19

[221 rows x 7 columns]
         Symbol    open    high     low   close     volume start_Time
0    BALRAMCHIN  412.95  420.40  409.15  414.50  3344980.0 2024-01-01
1    BALRAMCHIN  413.90  413.90  402.00  405.10  2716627.0 2024-01-02
2    BALRAMCHIN  405.00  408.55  403.05  406.40   968215.0 2024-01-03
3    BALRAMCHIN  408.50  410.40  406.45  407.30   795678.0 2024-01-04
4    BALRAMCHIN  409.85  409.85  401.30  403.50  1215990.0 2024-01-05
..          ...     ...     ...     ...     ...        ...        ...
216  BALRAMCHIN  575.05  580.50  563.40  566.95   644966.0 2024-11-12
217  BALRAMCHIN  560.00  564.20  544.75  547.60   680638.0 2024-11-13
218  BALRAMCHIN  551.95  555.70  535.55  539.40   995557.0 2024-11-14
219  BALRAMCHIN  539.40  542.00  517.05  525.30   980309.0 2024-11-18
220  BALRAMCHIN  532.00  539.85  524.35  526.85   530731.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol     open     high      low    close    volume start_Time
0     CAMS  2659.00  2677.00  2643.30  2648.50   66066.0 2024-01-01
1     CAMS  2655.00  2695.00  2650.55  2669.70  143141.0 2024-01-02
2     CAMS  2670.70  2685.80  2649.50  2652.10  112428.0 2024-01-03
3     CAMS  2675.00  2744.75  2671.00  2708.35  268532.0 2024-01-04
4     CAMS  2725.25  2768.00  2712.20  2748.15  354882.0 2024-01-05
..     ...      ...      ...      ...      ...       ...        ...
216   CAMS  4746.00  4892.20  4656.55  4681.70  439487.0 2024-11-12
217   CAMS  4670.00  4706.25  4471.00  4492.30  310748.0 2024-11-13
218   CAMS  4504.95  4649.95  4504.95  4581.95  262219.0 2024-11-14
219   CAMS  4618.00  4618.00  4451.00  4495.25  191325.0 2024-11-18
220   CAMS  4523.00  4635.00  4510.60  4538.10  214155.0 2024-11-19

[221 rows x 7 columns]
        Symbol    open    high     low   close     volume start_Time
0    NAM-INDIA  447.85  458.15  447.15  455.90   472726.0 2024-01-01
1    NAM-INDIA  457.00  471.70  454.00  466.80  1269708.0 2024-01-02
2    NAM-INDIA  467.40  473.80  458.65  460.10   822519.0 2024-01-03
3    NAM-INDIA  462.40  473.90  461.05  471.50   450586.0 2024-01-04
4    NAM-INDIA  474.50  483.00  473.00  480.50   926324.0 2024-01-05
..         ...     ...     ...     ...     ...        ...        ...
216  NAM-INDIA  701.20  718.00  686.90  692.00  1209270.0 2024-11-12
217  NAM-INDIA  689.80  700.00  661.15  670.05   668242.0 2024-11-13
218  NAM-INDIA  666.00  687.85  665.25  679.95   459926.0 2024-11-14
219  NAM-INDIA  672.60  688.40  660.90  677.45   469603.0 2024-11-18
220  NAM-INDIA  677.40  702.00  675.00  687.50   608890.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

        Symbol     open     high      low    close    volume start_Time
0    BATAINDIA  1654.45  1658.65  1632.20  1641.65  234872.0 2024-01-01
1    BATAINDIA  1634.00  1637.00  1592.10  1596.95  537992.0 2024-01-02
2    BATAINDIA  1597.00  1611.95  1594.00  1595.20  368231.0 2024-01-03
3    BATAINDIA  1604.00  1614.95  1594.85  1608.00  480334.0 2024-01-04
4    BATAINDIA  1609.00  1637.05  1609.00  1621.20  528170.0 2024-01-05
..         ...      ...      ...      ...      ...       ...        ...
216  BATAINDIA  1325.10  1350.75  1325.05  1334.90  330309.0 2024-11-12
217  BATAINDIA  1334.90  1340.00  1314.65  1317.95  132831.0 2024-11-13
218  BATAINDIA  1317.95  1337.80  1304.30  1307.35  159862.0 2024-11-14
219  BATAINDIA  1303.00  1306.00  1283.50  1289.30  263399.0 2024-11-18
220  BATAINDIA  1290.00  1305.65  1280.00  1282.65  300203.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open     high      low    close     volume start_Time
0     BBTC  1579.00  1609.70  1495.55  1516.75   456619.0 2024-01-01
1     BBTC  1511.00  1536.25  1463.15  1515.50   291892.0 2024-01-02
2     BBTC  1509.95  1527.95  1482.60  1491.35   102534.0 2024-01-03
3     BBTC  1492.85  1665.15  1492.85  1592.95  1333282.0 2024-01-04
4     BBTC  1599.80  1639.70  1541.00  1593.85   454317.0 2024-01-05
..     ...      ...      ...      ...      ...        ...        ...
216   BBTC  2763.80  2787.95  2661.10  2673.10    94638.0 2024-11-12
217   BBTC  2673.10  2698.15  2535.05  2560.50    99767.0 2024-11-13
218   BBTC  2525.40  2634.75  2525.40  2564.30    77735.0 2024-11-14
219   BBTC  2605.00  2629.65  2469.25  2550.00   126656.0 2024-11-18
220   BBTC  2555.10  2625.00  2551.55  2567.80    52550.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close      volume start_Time
0      BEL  184.80  187.00  184.45  184.95  18008785.0 2024-01-01
1      BEL  186.00  186.20  179.75  182.15  22790965.0 2024-01-02
2      BEL  182.35  184.70  180.60  182.35  18738690.0 2024-01-03
3      BEL  182.50  187.65  182.50  186.90  25403124.0 2024-01-04
4      BEL  187.70  188.65  184.05  185.95  22023938.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216    BEL  300.00  300.85  287.30  290.15  14292965.0 2024-11-12
217    BEL  288.00  288.85  279.45  281.55  20001842.0 2024-11-13
218    BEL  282.00  284.45  275.50  280.95  20541591.0 2024-11-14
219    BEL  283.00  286.70  277.25  278.05  13000137.0 2024-11-18
220    BEL  280.00  285.20  277.00  279.00  13160982.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open     high      low    close     volume start_Time
0     BEML  2831.60  2885.00  2825.00  2844.30   173851.0 2024-01-01
1     BEML  2845.00  2849.00  2703.05  2783.60   235182.0 2024-01-02
2     BEML  2785.00  2835.70  2766.15  2815.25   146650.0 2024-01-03
3     BEML  2810.00  2909.00  2810.00  2888.45   447772.0 2024-01-04
4     BEML  2950.00  3145.00  2920.05  3095.75  1718819.0 2024-01-05
..     ...      ...      ...      ...      ...        ...        ...
216   BEML  4094.55  4139.95  3912.60  3950.45   217736.0 2024-11-12
217   BEML  3950.00  4139.75  3787.65  3811.55   470310.0 2024-11-13
218   BEML  3820.20  3882.80  3720.50  3791.20   381587.0 2024-11-14
219   BEML  3791.50  3827.90  3655.50  3729.65   296408.0 2024-11-18
220   BEML  3750.95  3845.00  3670.00  3699.15   219013.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close     volume start_Time
0    NIACL  212.50  218.80  210.70  216.60  1222181.0 2024-01-01
1    NIACL  217.50  221.45  211.95  213.65  1222196.0 2024-01-02
2    NIACL  215.35  222.00  214.05  218.50  1310544.0 2024-01-03
3    NIACL  219.50  231.50  218.00  227.95  3121729.0 2024-01-04
4    NIACL  229.80  234.15  226.50  229.20  1591835.0 2024-01-05
..     ...     ...     ...     ...     ...        ...        ...
216  NIACL  186.00  187.89  179.93  181.07   678846.0 2024-11-12
217  NIACL  179.70  181.26  173.71  174.24   753985.0 2024-11-13
218  NIACL  174.24  179.49  174.00  176.05   778429.0 2024-11-14
219  NIACL  176.50  178.13  172.14  175.19   683656.0 2024-11-18
220  NIACL  176.75  180.96  175.50  176.46   625040.0 2024-11-19

[221 rows x 7 columns]
         Symbol    open    high     low   close     volume start_Time
0    BERGEPAINT  607.50  609.00  600.05  603.85   631961.0 2024-01-01
1    BERGEPAINT  603.00  605.50  592.75  604.35   613442.0 2024-01-02
2    BERGEPAINT  606.95  606.95  595.15  598.15   334537.0 2024-01-03
3    BERGEPAINT  598.45  601.30  591.60  598.45   639813.0 2024-01-04
4    BERGEPAINT  599.15  603.90  593.15  596.35   465157.0 2024-01-05
..          ...     ...     ...     ...     ...        ...        ...
216  BERGEPAINT  494.00  498.00  490.60  496.15   746801.0 2024-11-12
217  BERGEPAINT  493.40  495.15  485.40  489.75  1258501.0 2024-11-13
218  BERGEPAINT  491.40  495.75  486.00  491.90   364603.0 2024-11-14
219  BERGEPAINT  493.55  494.00  478.40  479.35   460129.0 2024-11-18
220  BERGEPAINT  479.50  483.45  475.00  476.25   476377.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close     volume start_Time
0    BHARATFORG  1242.00  1258.00  1233.95  1247.50   609955.0 2024-01-01
1    BHARATFORG  1255.60  1259.00  1225.55  1241.40   703395.0 2024-01-02
2    BHARATFORG  1242.00  1244.25  1215.75  1235.95   565828.0 2024-01-03
3    BHARATFORG  1229.05  1265.10  1219.30  1260.80   872939.0 2024-01-04
4    BHARATFORG  1268.00  1270.00  1251.00  1267.05   671381.0 2024-01-05
..          ...      ...      ...      ...      ...        ...        ...
216  BHARATFORG  1397.50  1397.55  1340.00  1360.60   745108.0 2024-11-12
217  BHARATFORG  1360.00  1363.35  1312.70  1321.50   584312.0 2024-11-13
218  BHARATFORG  1321.50  1356.90  1301.55  1328.75  1860816.0 2024-11-14
219  BHARATFORG  1329.00  1336.35  1286.60  1304.55  1548457.0 2024-11-18
220  BHARATFORG  1296.00  1355.35  1296.00  1323.35  1521514.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close      volume start_Time
0     BHEL  199.00  204.65  196.90  198.15  75665268.0 2024-01-01
1     BHEL  203.00  204.90  197.60  202.00  72765808.0 2024-01-02
2     BHEL  201.80  201.80  193.50  194.40  52393773.0 2024-01-03
3     BHEL  195.85  196.75  191.85  195.05  30243640.0 2024-01-04
4     BHEL  196.05  197.90  192.85  195.80  31168193.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216   BHEL  239.40  239.84  229.00  230.22  10589650.0 2024-11-12
217   BHEL  229.71  229.71  221.50  222.56  11397140.0 2024-11-13
218   BHEL  222.36  227.80  220.71  223.71  10187321.0 2024-11-14
219   BHEL  225.11  226.35  219.66  222.67  11297324.0 2024-11-18
220   BHEL  224.00  233.20  223.60  225.88  12068006.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol    open    high     low   close     volume start_Time
0    HDFCLIFE  647.00  652.35  644.35  648.70  1343888.0 2024-01-01
1    HDFCLIFE  649.50  654.30  642.60  645.50  3005450.0 2024-01-02
2    HDFCLIFE  644.00  648.45  636.10  637.20  1893956.0 2024-01-03
3    HDFCLIFE  638.00  649.00  638.00  647.95  4412550.0 2024-01-04
4    HDFCLIFE  648.50  654.55  642.45  646.75  1394951.0 2024-01-05
..        ...     ...     ...     ...     ...        ...        ...
216  HDFCLIFE  707.55  719.85  696.10  700.00  2502158.0 2024-11-12
217  HDFCLIFE  695.00  698.85  683.15  685.05  2080391.0 2024-11-13
218  HDFCLIFE  681.50  696.70  681.50  694.00  1715862.0 2024-11-14
219  HDFCLIFE  687.00  693.95  682.50  690.50  1666040.0 2024-11-18
220  HDFCLIFE  688.05  693.00  668.30  680.40  6438490.0 2024-11-19

[221 rows x 7 columns]
      Symbol      open      high       low     close   volume start_Time
0    3MINDIA  37000.00  37500.00  36405.00  36659.95  10350.0 2024-01-01
1    3MINDIA  36868.95  36934.20  35150.05  35633.95   9804.0 2024-01-02
2    3MINDIA  35900.00  36451.90  33532.70  34236.75  18794.0 2024-01-03
3    3MINDIA  34688.95  34732.70  34200.00  34321.80   6087.0 2024-01-04
4    3MINDIA  34325.00  34775.00  33850.00  34696.95   4835.0 2024-01-05
..       ...       ...       ...       ...       ...      ...        ...
216  3MINDIA  35300.00  35857.15  34729.00  34898.85   4665.0 2024-11-12
217  3MINDIA  34100.05  34240.00  33260.15  33363.90   6140.0 2024-11-13
218  3MINDIA  33686.00  33760.00  32247.50  32466.10   5692.0 2024-11-14
219  3MINDIA  32400.00  32830.45  31560.20  31664.15   5292.0 2024-11-18
220  3MINDIA  31900.00  32218.85  31325.00  31901.90   3644.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close    volume start_Time
0    BIRLACORPN  1460.00  1513.70  1450.15  1499.65  201822.0 2024-01-01
1    BIRLACORPN  1513.65  1519.95  1456.00  1469.65   98522.0 2024-01-02
2    BIRLACORPN  1480.00  1481.75  1422.00  1427.20  122186.0 2024-01-03
3    BIRLACORPN  1440.80  1440.85  1422.00  1429.60   78176.0 2024-01-04
4    BIRLACORPN  1443.90  1446.40  1422.35  1434.20   67340.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  BIRLACORPN  1136.00  1142.85  1098.05  1103.65   65084.0 2024-11-12
217  BIRLACORPN  1100.80  1112.45  1080.80  1084.50  110832.0 2024-11-13
218  BIRLACORPN  1084.55  1107.10  1079.85  1085.30   62266.0 2024-11-14
219  BIRLACORPN  1092.35  1128.00  1077.00  1110.40   64405.0 2024-11-18
220  BIRLACORPN  1113.20  1127.00  1102.55  1114.45   94274.0 2024-11-19

[221 rows x 7 columns]
       Symbol    open     high      low    close   volume start_Time
0    BLUEDART  7370.0  7414.45  7305.00  7335.85   5155.0 2024-01-01
1    BLUEDART  7335.0  7395.85  7300.05  7351.85   3977.0 2024-01-02
2    BLUEDART  7357.0  7456.00  7314.00  7411.20   9889.0 2024-01-03
3    BLUEDART  7479.0  7479.00  7352.25  7395.95   4814.0 2024-01-04
4    BLUEDART  7381.0  7441.00  7325.00  7416.55   5910.0 2024-01-05
..        ...     ...      ...      ...      ...      ...        ...
216  BLUEDART  7927.2  7927.30  7539.00  7679.25  10854.0 2024-11-12
217  BLUEDART  7580.0  7679.25  7341.20  7440.70   7484.0 2024-11-13
218  BLUEDART  7509.9  7709.75  7335.05  7657.60  27604.0 2024-11-14
219  BLUEDART  7695.0  7695.00  7287.60  7383.10  22894.0 2024-11-18
220  BLUEDART  7390.0  7555.00  7340.00  7377.65  13270.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol     open     high      low    close     volume start_Time
0    MAZDOCK  2287.70  2323.70  2278.30  2289.75   870417.0 2024-01-01
1    MAZDOCK  2298.00  2300.15  2208.50  2246.95   996360.0 2024-01-02
2    MAZDOCK  2254.00  2299.00  2215.95  2282.75  1133733.0 2024-01-03
3    MAZDOCK  2294.20  2351.25  2246.85  2256.35  1850070.0 2024-01-04
4    MAZDOCK  2267.20  2278.00  2240.00  2261.35   728331.0 2024-01-05
..       ...      ...      ...      ...      ...        ...        ...
216  MAZDOCK  4105.00  4160.00  4041.00  4052.75   672180.0 2024-11-12
217  MAZDOCK  4042.95  4060.00  3872.00  3890.80  1234955.0 2024-11-13
218  MAZDOCK  3939.00  3985.00  3851.20  3926.10  1249981.0 2024-11-14
219  MAZDOCK  3930.00  4035.00  3920.00  3977.55  1073841.0 2024-11-18
220  MAZDOCK  4170.00  4172.95  4060.00  4075.55  1456186.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close      volume start_Time
0     BPCL  229.70  229.70  225.35  226.03   3503144.0 2024-01-01
1     BPCL  226.03  229.70  224.05  228.13   4729409.0 2024-01-02
2     BPCL  229.98  232.65  227.53  230.53   7529442.0 2024-01-03
3     BPCL  228.40  228.75  225.50  226.33   8952458.0 2024-01-04
4     BPCL  227.95  229.83  225.63  226.55   4040234.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216   BPCL  314.10  318.55  309.05  309.80   7192998.0 2024-11-12
217   BPCL  307.95  309.00  302.00  305.85   7306795.0 2024-11-13
218   BPCL  305.80  306.00  296.40  298.20  11061057.0 2024-11-14
219   BPCL  298.15  299.65  288.30  289.20   7940666.0 2024-11-18
220   BPCL  292.65  297.90  286.50  287.50   9912544.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

     Symbol     open     high      low    close    volume start_Time
0    UTIAMC   869.90   873.95   860.15   869.70   86351.0 2024-01-01
1    UTIAMC   869.00   872.65   853.40   868.30   98446.0 2024-01-02
2    UTIAMC   871.90   904.95   860.10   868.60  240041.0 2024-01-03
3    UTIAMC   873.40   888.90   866.65   875.25   70847.0 2024-01-04
4    UTIAMC   883.00   885.55   865.10   875.65   63828.0 2024-01-05
..      ...      ...      ...      ...      ...       ...        ...
216  UTIAMC  1312.00  1399.30  1306.00  1345.90  737817.0 2024-11-12
217  UTIAMC  1333.45  1339.90  1253.95  1263.20  252835.0 2024-11-13
218  UTIAMC  1254.00  1325.00  1253.85  1311.90  266430.0 2024-11-14
219  UTIAMC  1289.55  1297.85  1259.95  1268.60  136811.0 2024-11-18
220  UTIAMC  1270.40  1299.00  1263.00  1282.50  149525.0 2024-11-19

[221 rows x 7 columns]
        Symbol     open     high      low    close     volume start_Time
0    BRITANNIA  5339.00  5349.90  5290.00  5319.80   130032.0 2024-01-01
1    BRITANNIA  5319.80  5334.95  5224.10  5288.85   193517.0 2024-01-02
2    BRITANNIA  5288.85  5333.90  5240.00  5253.80   123303.0 2024-01-03
3    BRITANNIA  5253.80  5375.00  5221.00  5361.30   413391.0 2024-01-04
4    BRITANNIA  5361.30  5363.35  5256.00  5272.35   299017.0 2024-01-05
..         ...      ...      ...      ...      ...        ...        ...
216  BRITANNIA  5420.00  5426.90  5005.00  5027.55  2441209.0 2024-11-12
217  BRITANNIA  5009.00  5087.60  4938.45  5046.50   928244.0 2024-11-13
218  BRITANNIA  5046.50  5050.50  4901.00  4915.60   479979.0 2024-11-14
219  BRITANNIA  4970.00  4970.00  4791.65  4911.35   439087.0 2024-11-18
220  BRITANNIA  4924.95  4951.35  4878.60  4892.70   436205.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol    open    high     low   close    volume start_Time
0    CANFINHOME  777.65  785.60  774.75  776.90  474059.0 2024-01-01
1    CANFINHOME  780.45  780.75  763.35  766.10  404115.0 2024-01-02
2    CANFINHOME  765.00  773.45  760.60  765.95  612518.0 2024-01-03
3    CANFINHOME  768.00  789.90  768.00  785.75  685873.0 2024-01-04
4    CANFINHOME  789.90  795.25  770.10  781.40  830394.0 2024-01-05
..          ...     ...     ...     ...     ...       ...        ...
216  CANFINHOME  841.10  847.25  826.00  828.85  183237.0 2024-11-12
217  CANFINHOME  827.80  827.80  810.50  815.60  299321.0 2024-11-13
218  CANFINHOME  815.60  832.20  813.80  822.95  199382.0 2024-11-14
219  CANFINHOME  816.05  837.95  811.90  829.50  206386.0 2024-11-18
220  CANFINHOME  830.60  852.20  828.60  832.65  248145.0 2024-11-19

[221 rows x 7 columns]
       Symbol    open    high     low   close     volume start_Time
0    GRAPHITE  550.20  559.20  548.10  551.70   766047.0 2024-01-01
1    GRAPHITE  551.50  558.40  539.45  543.60  1191030.0 2024-01-02
2    GRAPHITE  543.60  547.75  535.05  536.50   476454.0 2024-01-03
3    GRAPHITE  537.50  553.70  535.00  550.65  1184715.0 2024-01-04
4    GRAPHITE  551.00  557.70  540.30  544.60   647150.0 2024-01-05
..        ...     ...     ...     ...     ...        ...        ...
216  GRAPHITE  512.00  516.00  496.00  498.45   386755.0 2024-11-12
217  GRAPHITE  497.45  504.95  482.25  485.50   519668.0 2024-11-13
218  GRAPHITE  487.90  497.95  482.00  484.65   322330.0 2024-11-14
219  GRAPHITE  486.00  493.60  472.85  476.30   485674.0 2024-11-18
220  GRAPHITE  480.00  486.40  471.10  473.50   336448.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close    volume start_Time
0    CARBORUNIV  1117.95  1125.00  1106.10  1116.80   48609.0 2024-01-01
1    CARBORUNIV  1117.95  1125.00  1105.15  1116.90   62433.0 2024-01-02
2    CARBORUNIV  1117.55  1129.95  1107.00  1120.05   70187.0 2024-01-03
3    CARBORUNIV  1128.90  1133.10  1110.80  1114.85   75679.0 2024-01-04
4    CARBORUNIV  1124.00  1149.95  1117.00  1145.50  125079.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  CARBORUNIV  1428.75  1432.75  1388.10  1405.85   52876.0 2024-11-12
217  CARBORUNIV  1386.00  1433.90  1378.05  1420.90  143267.0 2024-11-13
218  CARBORUNIV  1420.90  1470.00  1410.05  1461.65  103082.0 2024-11-14
219  CARBORUNIV  1512.00  1530.90  1433.50  1450.80  246829.0 2024-11-18
220  CARBORUNIV  1451.00  1458.95  1402.00  1408.40  134457.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close      volume start_Time
0     CESC  133.00  138.40  132.50  136.85  16092130.0 2024-01-01
1     CESC  137.05  137.55  131.40  134.60   8945971.0 2024-01-02
2     CESC  134.60  137.45  132.10  134.70   8806136.0 2024-01-03
3     CESC  134.85  136.25  134.10  134.85   5754194.0 2024-01-04
4     CESC  135.00  139.90  134.85  138.60  20626872.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216   CESC  184.34  188.62  182.70  183.92   4262381.0 2024-11-12
217   CESC  183.30  183.40  174.03  174.98   3898790.0 2024-11-13
218   CESC  174.98  178.79  174.30  174.96   2990972.0 2024-11-14
219   CESC  175.90  177.18  170.21  171.09   2211164.0 2024-11-18
220   CESC  171.45  174.45  169.00  169.98   2450601.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol    open    high     low   close      volume start_Time
0    CHAMBLFERT  374.90  385.00  373.90  380.15   3629242.0 2024-01-01
1    CHAMBLFERT  381.80  386.15  374.00  380.10   2746779.0 2024-01-02
2    CHAMBLFERT  380.10  388.00  378.05  386.70   3311978.0 2024-01-03
3    CHAMBLFERT  401.20  402.90  385.00  386.65  11227107.0 2024-01-04
4    CHAMBLFERT  388.00  388.05  368.00  372.80   5687508.0 2024-01-05
..          ...     ...     ...     ...     ...         ...        ...
216  CHAMBLFERT  479.95  494.75  479.80  483.95   2103932.0 2024-11-12
217  CHAMBLFERT  482.90  482.90  460.00  461.95   1399534.0 2024-11-13
218  CHAMBLFERT  463.85  475.35  459.60  469.85   1751179.0 2024-11-14
219  CHAMBLFERT  470.00  472.15  461.85  464.30   1009886.0 2024-11-18
220  CHAMBLFERT  461.85  472.00  461.50  463.50   1007123.0 2024-11-19

[221 rows x 7 columns]
       Symbol    open    high     low   close     volume start_Time
0    EXIDEIND  319.85  326.45  318.35  322.00  4091951.0 2024-01-01
1    EXIDEIND  323.75  324.75  315.50  322.15  3175785.0 2024-01-02
2    EXIDEIND  322.15  328.80  318.00  326.00  2969074.0 2024-01-03
3    EXIDEIND  327.00  328.65  324.00  324.70  2563207.0 2024-01-04
4    EXIDEIND  325.50  331.00  321.15  329.35  3866526.0 2024-01-05
..        ...     ...     ...     ...     ...        ...        ...
216  EXIDEIND  438.50  447.35  430.35  431.80  5228338.0 2024-11-12
217  EXIDEIND  431.50  434.60  416.65  418.45  4828918.0 2024-11-13
218  EXIDEIND  418.45  422.60  412.35  418.10  3972370.0 2024-11-14
219  EXIDEIND  418.10  421.00  412.60  414.50  1871986.0 2024-11-18
220  EXIDEIND  415.45  430.80  415.00  421.50  3696768.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol     open     high      low    close     volume start_Time
0    CHOLAFIN  1259.70  1260.00  1220.00  1225.35   726699.0 2024-01-01
1    CHOLAFIN  1229.80  1232.00  1214.55  1220.10  2240606.0 2024-01-02
2    CHOLAFIN  1220.95  1250.00  1218.15  1240.50  1378408.0 2024-01-03
3    CHOLAFIN  1247.20  1300.75  1243.75  1297.25  2922785.0 2024-01-04
4    CHOLAFIN  1305.30  1305.30  1248.10  1257.85  1075135.0 2024-01-05
..        ...      ...      ...      ...      ...        ...        ...
216  CHOLAFIN  1269.00  1278.35  1235.75  1239.75  1006239.0 2024-11-12
217  CHOLAFIN  1225.45  1250.00  1195.00  1205.05  1989571.0 2024-11-13
218  CHOLAFIN  1201.00  1215.00  1181.15  1205.70  1443941.0 2024-11-14
219  CHOLAFIN  1211.75  1253.80  1207.30  1242.80  1661116.0 2024-11-18
220  CHOLAFIN  1243.75  1254.25  1221.05  1236.00  1793763.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open     high      low    close     volume start_Time
0    CIPLA  1252.45  1256.80  1246.70  1251.00   343584.0 2024-01-01
1    CIPLA  1255.10  1285.00  1252.10  1281.55  2589484.0 2024-01-02
2    CIPLA  1291.00  1307.00  1274.05  1300.15  2357093.0 2024-01-03
3    CIPLA  1304.00  1308.00  1286.65  1296.65  1248143.0 2024-01-04
4    CIPLA  1300.00  1301.55  1276.15  1286.90  1013196.0 2024-01-05
..     ...      ...      ...      ...      ...        ...        ...
216  CIPLA  1551.05  1556.95  1521.95  1525.15  2782808.0 2024-11-12
217  CIPLA  1516.50  1525.90  1501.20  1505.60  1552443.0 2024-11-13
218  CIPLA  1497.00  1517.00  1490.25  1499.75  1469143.0 2024-11-14
219  CIPLA  1497.50  1505.15  1460.85  1465.25  1760344.0 2024-11-18
220  CIPLA  1465.00  1485.85  1456.85  1471.55  1116002.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close    volume start_Time
0    COROMANDEL  1251.65  1259.95  1236.00  1247.65  181841.0 2024-01-01
1    COROMANDEL  1242.10  1255.70  1227.50  1230.85  276631.0 2024-01-02
2    COROMANDEL  1225.00  1252.00  1224.20  1248.75  150644.0 2024-01-03
3    COROMANDEL  1255.00  1265.65  1246.50  1254.85  225513.0 2024-01-04
4    COROMANDEL  1258.70  1268.50  1235.85  1246.40  174551.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  COROMANDEL  1737.25  1756.60  1720.00  1730.50  344347.0 2024-11-12
217  COROMANDEL  1714.80  1730.95  1675.55  1684.95  225860.0 2024-11-13
218  COROMANDEL  1686.55  1725.00  1665.20  1715.95  572592.0 2024-11-14
219  COROMANDEL  1715.00  1743.95  1695.05  1721.10  362721.0 2024-11-18
220  COROMANDEL  1730.20  1775.70  1724.55  1764.60  231149.0 2024-11-19

[221 rows x 7 columns]
     Symbol     open     high     low    close   volume start_Time
0    CRISIL  4329.65  4336.00  4260.1  4270.65  18474.0 2024-01-01
1    CRISIL  4291.00  4291.00  4209.1  4220.10  15342.0 2024-01-02
2    CRISIL  4220.10  4241.15  4141.0  4150.20  26366.0 2024-01-03
3    CRISIL  4170.95  4178.80  4080.0  4150.05  24518.0 2024-01-04
4    CRISIL  4166.65  4198.00  4105.0  4120.75  29348.0 2024-01-05
..      ...      ...      ...     ...      ...      ...        ...
216  CRISIL  5530.05  5600.00  5421.1  5460.95  35217.0 2024-11-12
217  CRISIL  5411.55  5456.90  5232.5  5269.65  38572.0 2024-11-13
218  CRISIL  5235.00  5342.70  5171.1  5190.60  34018.0 2024-11-14
219  CRISIL  5190.00  5363.75  5111.0  5283.55  24195.0 2024-11-18
220  CRISIL  5353.25  5353.25  5230.0  5268.90  17886.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol   open    high     low   close     volume start_Time
0    CGPOWER  458.7  458.70  448.30  449.60   552939.0 2024-01-01
1    CGPOWER  450.6  454.20  445.00  452.05  1456207.0 2024-01-02
2    CGPOWER  453.0  458.00  448.35  451.35  2462488.0 2024-01-03
3    CGPOWER  454.6  469.85  453.55  464.10  2427322.0 2024-01-04
4    CGPOWER  480.0  488.00  465.00  468.45  4799854.0 2024-01-05
..       ...    ...     ...     ...     ...        ...        ...
216  CGPOWER  727.0  734.40  710.20  712.70  1268095.0 2024-11-12
217  CGPOWER  710.0  710.80  681.10  689.05  1978434.0 2024-11-13
218  CGPOWER  698.0  708.00  691.75  695.10  1602611.0 2024-11-14
219  CGPOWER  700.0  718.20  696.65  702.80  1565505.0 2024-11-18
220  CGPOWER  702.5  726.70  693.05  718.30  2910502.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close     volume start_Time
0    DABUR  560.00  563.00  555.00  557.45  1417550.0 2024-01-01
1    DABUR  559.45  562.35  551.35  556.85  1201767.0 2024-01-02
2    DABUR  557.00  562.70  546.60  551.10  2733401.0 2024-01-03
3    DABUR  554.65  567.30  550.90  566.25  3064476.0 2024-01-04
4    DABUR  571.00  571.65  564.50  569.05  2834989.0 2024-01-05
..     ...     ...     ...     ...     ...        ...        ...
216  DABUR  522.80  524.15  509.50  510.50  4775306.0 2024-11-12
217  DABUR  511.35  514.20  507.30  510.85  2253481.0 2024-11-13
218  DABUR  510.85  513.95  502.65  508.10  2083472.0 2024-11-14
219  DABUR  509.10  509.60  499.00  508.50  3329177.0 2024-11-18
220  DABUR  511.00  514.50  506.15  508.20  2126926.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close    volume start_Time
0    DCMSHRIRAM  1028.40  1050.00  1025.00  1028.90  132595.0 2024-01-01
1    DCMSHRIRAM  1036.50  1045.00  1020.60  1039.65  155526.0 2024-01-02
2    DCMSHRIRAM  1044.00  1050.00  1028.10  1038.35   71527.0 2024-01-03
3    DCMSHRIRAM  1040.00  1175.00  1026.60  1141.45  615281.0 2024-01-04
4    DCMSHRIRAM  1141.50  1141.50  1059.90  1077.70  572186.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  DCMSHRIRAM  1256.95  1299.60  1232.35  1244.75  252190.0 2024-11-12
217  DCMSHRIRAM  1244.00  1244.15  1180.05  1187.15  118358.0 2024-11-13
218  DCMSHRIRAM  1190.00  1313.90  1168.30  1302.25  867058.0 2024-11-14
219  DCMSHRIRAM  1308.25  1339.55  1273.35  1321.70  533024.0 2024-11-18
220  DCMSHRIRAM  1328.25  1371.10  1280.10  1297.30  414513.0 2024-11-19

[221 rows x 7 columns]
         Symbol     open     high      low    close     volume start_Time
0    DEEPAKFERT   685.00   702.60   678.05   687.80  1506451.0 2024-01-01
1    DEEPAKFERT   693.40   705.20   681.05   692.25  1149524.0 2024-01-02
2    DEEPAKFERT   692.25   695.70   682.45   686.80   504916.0 2024-01-03
3    DEEPAKFERT   705.70   708.80   692.00   695.80   674825.0 2024-01-04
4    DEEPAKFERT   695.85   698.35   676.30   683.85   463395.0 2024-01-05
..          ...      ...      ...      ...      ...        ...        ...
216  DEEPAKFERT  1291.95  1363.95  1284.45  1301.90  1087053.0 2024-11-12
217  DEEPAKFERT  1301.00  1313.40  1225.00  1237.35   954537.0 2024-11-13
218  DEEPAKFERT  1251.90  1324.95  1250.00  1282.45  1627537.0 2024-11-14
219  DEEPAKFERT  1283.00  1342.95  1272.40  1278.75  1165133.0 2024-11-18
220  DEEPAKFERT  1289.00  1357.95  1266.00  1272.55  1629865.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol     open     high      low    close     volume start_Time
0    DRREDDY  1160.00  1172.00  1160.00  1164.33   195680.0 2024-01-01
1    DRREDDY  1161.41  1189.80  1161.13  1185.36   573856.0 2024-01-02
2    DRREDDY  1185.36  1194.00  1177.64  1186.38   282407.0 2024-01-03
3    DRREDDY  1184.43  1184.43  1165.00  1168.44   409660.0 2024-01-04
4    DRREDDY  1174.00  1174.91  1161.30  1167.13   207451.0 2024-01-05
..       ...      ...      ...      ...      ...        ...        ...
216  DRREDDY  1287.85  1288.40  1258.30  1263.90  1110785.0 2024-11-12
217  DRREDDY  1258.00  1265.05  1238.30  1245.00   995217.0 2024-11-13
218  DRREDDY  1249.90  1253.00  1222.20  1226.70  1346891.0 2024-11-14
219  DRREDDY  1206.10  1219.80  1170.20  1193.55  3367815.0 2024-11-18
220  DRREDDY  1193.00  1232.00  1186.25  1213.45  1509716.0 2024-11-19

[221 rows x 7 columns]
        Symbol     open     high      low    close     volume start_Time
0    EICHERMOT  4145.00  4145.00  4030.00  4038.35   763454.0 2024-01-01
1    EICHERMOT  4010.10  4010.75  3882.35  3892.50  1221148.0 2024-01-02
2    EICHERMOT  3894.05  3928.95  3878.45  3887.60   435449.0 2024-01-03
3    EICHERMOT  3887.50  3915.00  3848.50  3861.00   425702.0 2024-01-04
4    EICHERMOT  3864.05  3918.70  3860.00  3877.05   402103.0 2024-01-05
..         ...      ...      ...      ...      ...        ...        ...
216  EICHERMOT  4788.00  4807.25  4705.55  4738.20   326018.0 2024-11-12
217  EICHERMOT  4700.00  4719.95  4536.05  4588.70   656931.0 2024-11-13
218  EICHERMOT  4725.45  4973.00  4705.30  4883.70  2874648.0 2024-11-14
219  EICHERMOT  4879.95  4914.00  4863.00  4875.65   494329.0 2024-11-18
220  EICHERMOT  4880.00  5014.05  4880.00  4965.45   452273.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol    open    high     low   close      volume start_Time
0    EQUITASBNK  105.65  108.30  105.25  107.60   2984516.0 2024-01-01
1    EQUITASBNK  107.65  112.90  106.40  110.25  10205184.0 2024-01-02
2    EQUITASBNK  110.00  111.60  108.80  110.70   5492581.0 2024-01-03
3    EQUITASBNK  110.90  113.70  110.60  111.50   4916387.0 2024-01-04
4    EQUITASBNK  113.45  115.65  111.70  114.55   8051577.0 2024-01-05
..          ...     ...     ...     ...     ...         ...        ...
216  EQUITASBNK   64.82   65.56   64.01   64.92   4048876.0 2024-11-12
217  EQUITASBNK   65.55   65.55   62.60   62.75   3213086.0 2024-11-13
218  EQUITASBNK   63.46   63.63   62.00   62.63   3979557.0 2024-11-14
219  EQUITASBNK   62.61   65.90   62.50   65.69   4516766.0 2024-11-18
220  EQUITASBNK   65.71   66.80   64.85   65.95   3111688.0 2024-11-19

[221 rows x 7 columns]
       Symbol    open   high     low   close     volume start_Time
0    EIDPARRY  559.00  565.1  558.00  560.55   285351.0 2024-01-01
1    EIDPARRY  563.00  563.1  552.65  559.90   411064.0 2024-01-02
2    EIDPARRY  561.50  572.0  557.95  570.10   813114.0 2024-01-03
3    EIDPARRY  571.05  579.5  570.30  575.75   922545.0 2024-01-04
4    EIDPARRY  579.95  591.3  570.00  574.45   925916.0 2024-01-05
..        ...     ...    ...     ...     ...        ...        ...
216  EIDPARRY  815.85  837.0  810.05  816.80   239042.0 2024-11-12
217  EIDPARRY  812.00  812.9  766.85  772.70   231849.0 2024-11-13
218  EIDPARRY  774.00  798.0  770.05  781.50   489674.0 2024-11-14
219  EIDPARRY  771.10  779.0  748.20  766.70   286284.0 2024-11-18
220  EIDPARRY  775.30  829.5  770.10  822.25  1598619.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol    open    high     low   close     volume start_Time
0    EIHOTEL  253.00  254.00  248.50  250.85  1025306.0 2024-01-01
1    EIHOTEL  250.85  268.65  249.00  265.55  6862998.0 2024-01-02
2    EIHOTEL  266.40  270.00  262.85  269.05  1766703.0 2024-01-03
3    EIHOTEL  270.50  288.00  269.40  280.50  2639629.0 2024-01-04
4    EIHOTEL  281.00  287.25  275.10  279.20  1637533.0 2024-01-05
..       ...     ...     ...     ...     ...        ...        ...
216  EIHOTEL  371.90  378.05  359.50  362.75   520801.0 2024-11-12
217  EIHOTEL  374.40  382.15  348.85  354.35  3198333.0 2024-11-13
218  EIHOTEL  356.95  364.90  355.50  357.65   790810.0 2024-11-14
219  EIHOTEL  357.65  363.15  352.50  357.15   405874.0 2024-11-18
220  EIHOTEL  358.40  365.00  355.90  357.85   353223.0 2024-11-19

[221 rows x 7 columns]
        Symbol    open    high     low   close    volume start_Time
0    ELGIEQUIP  547.25  547.65  538.10  542.05   75856.0 2024-01-01
1    ELGIEQUIP  542.65  548.50  535.15  546.25  143968.0 2024-01-02
2    ELGIEQUIP  545.70  562.15  540.10  541.30  401666.0 2024-01-03
3    ELGIEQUIP  542.80  544.75  534.10  535.95  100014.0 2024-01-04
4    ELGIEQUIP  537.00  545.00  533.70  543.10  102631.0 2024-01-05
..         ...     ...     ...     ...     ...       ...        ...
216  ELGIEQUIP  628.00  633.45  599.75  602.50  155092.0 2024-11-12
217  ELGIEQUIP  610.00  613.65  567.05  570.05  232024.0 2024-11-13
218  ELGIEQUIP  578.80  590.95  562.40  584.85  304564.0 2024-11-14
219  ELGIEQUIP  590.00  590.00  557.85  559.80  172955.0 2024-11-18
220  ELGIEQUIP  565.00  568.95  546.80  556.65  412043.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol     open     high      low    close    volume start_Time
0    ESCORTS  2996.00  3019.00  2956.00  2966.35  318161.0 2024-01-01
1    ESCORTS  2968.00  2977.00  2875.00  2887.65  378020.0 2024-01-02
2    ESCORTS  2871.00  2913.10  2860.00  2869.85  338355.0 2024-01-03
3    ESCORTS  2875.00  2884.95  2794.95  2858.45  932890.0 2024-01-04
4    ESCORTS  2858.45  2881.85  2800.00  2804.85  433569.0 2024-01-05
..       ...      ...      ...      ...      ...       ...        ...
216  ESCORTS  3635.00  3703.95  3535.00  3559.45  158647.0 2024-11-12
217  ESCORTS  3564.00  3571.90  3480.00  3495.25  111810.0 2024-11-13
218  ESCORTS  3490.15  3570.00  3474.65  3503.25   86134.0 2024-11-14
219  ESCORTS  3509.95  3537.90  3435.00  3441.35   65265.0 2024-11-18
220  ESCORTS  3440.00  3533.45  3440.00  3494.15   99096.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close     volume start_Time
0      EPL  202.45  203.65  199.10  200.40   342138.0 2024-01-01
1      EPL  200.55  200.95  195.95  198.10   571739.0 2024-01-02
2      EPL  197.30  202.35  197.30  198.10   525555.0 2024-01-03
3      EPL  198.15  201.90  198.15  201.05   514774.0 2024-01-04
4      EPL  202.00  206.20  200.00  200.85  1278827.0 2024-01-05
..     ...     ...     ...     ...     ...        ...        ...
216    EPL  263.95  275.05  260.00  263.90  4857624.0 2024-11-12
217    EPL  261.30  264.95  257.90  261.25   757045.0 2024-11-13
218    EPL  264.40  271.50  262.75  266.70  1170690.0 2024-11-14
219    EPL  266.70  268.50  257.10  259.70   686263.0 2024-11-18
220    EPL  260.00  265.70  258.80  260.30   513981.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol    open    high     low   close     volume start_Time
0    MAHLIFE  547.45  547.50  541.05  545.10   142879.0 2024-01-01
1    MAHLIFE  547.00  547.00  540.10  546.70   191843.0 2024-01-02
2    MAHLIFE  548.00  564.60  543.20  546.15   554575.0 2024-01-03
3    MAHLIFE  549.85  575.90  548.10  571.75  1400596.0 2024-01-04
4    MAHLIFE  572.45  582.45  569.20  575.65   434924.0 2024-01-05
..       ...     ...     ...     ...     ...        ...        ...
216  MAHLIFE  500.00  502.25  486.00  489.50   117269.0 2024-11-12
217  MAHLIFE  485.00  487.20  471.00  474.70   152555.0 2024-11-13
218  MAHLIFE  475.00  479.95  460.10  472.60   170724.0 2024-11-14
219  MAHLIFE  472.65  475.95  459.55  469.25   121151.0 2024-11-18
220  MAHLIFE  470.60  479.00  466.95  469.30    72705.0 2024-11-19

[221 rows x 7 columns]
        Symbol     open     high      low    close    volume start_Time
0    DALBHARAT  2307.50  2382.00  2301.00  2361.25  802488.0 2024-01-01
1    DALBHARAT  2370.00  2378.20  2289.05  2320.55  297631.0 2024-01-02
2    DALBHARAT  2334.90  2334.90  2301.05  2307.65  135305.0 2024-01-03
3    DALBHARAT  2320.00  2365.00  2304.20  2361.00  268910.0 2024-01-04
4    DALBHARAT  2365.00  2428.60  2341.05  2390.70  665883.0 2024-01-05
..         ...      ...      ...      ...      ...       ...        ...
216  DALBHARAT  1760.00  1793.90  1752.00  1786.70   79048.0 2024-11-12
217  DALBHARAT  1782.00  1788.25  1734.70  1737.60  195661.0 2024-11-13
218  DALBHARAT  1736.10  1746.05  1676.55  1713.80  491072.0 2024-11-14
219  DALBHARAT  1709.95  1730.00  1680.20  1686.35  208120.0 2024-11-18
220  DALBHARAT  1700.65  1770.00  1698.55  1745.25  400400.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close      volume start_Time
0      AWL  356.75  375.60  355.05  367.00   3843900.0 2024-01-01
1      AWL  369.05  370.70  361.00  366.60   1767457.0 2024-01-02
2      AWL  382.00  397.80  376.35  380.95  18543241.0 2024-01-03
3      AWL  386.95  389.40  381.00  381.60   2615581.0 2024-01-04
4      AWL  383.40  383.65  376.00  377.70   2316000.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216    AWL  328.95  337.50  328.65  333.50   1251804.0 2024-11-12
217    AWL  335.00  336.60  316.00  323.45   1588687.0 2024-11-13
218    AWL  324.00  334.00  323.50  331.05   1111772.0 2024-11-14
219    AWL  333.95  333.95  324.10  325.15    729819.0 2024-11-18
220    AWL  327.00  331.75  326.00  327.65    715804.0 2024-11-19

[221 rows x 7 columns]
         Symbol     open     high      low    close    volume start_Time
0    AJANTPHARM  2083.00  2170.20  2053.65  2159.65  166867.0 2024-01-01
1    AJANTPHARM  2138.05  2198.00  2128.15  2189.75  127933.0 2024-01-02
2    AJANTPHARM  2176.05  2244.45  2170.05  2232.85  121669.0 2024-01-03
3    AJANTPHARM  2215.00  2353.95  2215.00  2289.50  191780.0 2024-01-04
4    AJANTPHARM  2296.90  2296.90  2193.80  2235.10  116838.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  AJANTPHARM  2856.80  2910.95  2800.00  2838.05  111466.0 2024-11-12
217  AJANTPHARM  2812.20  2919.20  2755.55  2824.90   95550.0 2024-11-13
218  AJANTPHARM  2795.00  2875.10  2792.85  2859.85   71512.0 2024-11-14
219  AJANTPHARM  2859.85  2909.85  2850.05  2888.95   60434.0 2024-11-18
220  AJANTPHARM  2888.95  2964.95  2880.25  2933.95   51785.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol     open     high      low    close    volume start_Time
0    MANYAVAR  1277.45  1280.05  1263.15  1275.45   86359.0 2024-01-01
1    MANYAVAR  1278.45  1291.60  1272.25  1275.80  118317.0 2024-01-02
2    MANYAVAR  1278.70  1282.45  1256.40  1260.40   83352.0 2024-01-03
3    MANYAVAR  1260.00  1269.15  1233.20  1238.65  177474.0 2024-01-04
4    MANYAVAR  1244.50  1248.30  1203.00  1209.55  259203.0 2024-01-05
..        ...      ...      ...      ...      ...       ...        ...
216  MANYAVAR  1420.00  1425.95  1358.00  1366.90   68650.0 2024-11-12
217  MANYAVAR  1358.05  1370.00  1308.30  1327.70  116697.0 2024-11-13
218  MANYAVAR  1330.00  1336.25  1313.50  1321.35   49638.0 2024-11-14
219  MANYAVAR  1300.40  1328.55  1289.10  1319.20   62352.0 2024-11-18
220  MANYAVAR  1337.80  1370.25  1315.60  1360.75   91491.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open     high      low    close   volume start_Time
0     CERA  7871.25  7947.40  7850.00  7912.45  22294.0 2024-01-01
1     CERA  7901.05  7901.05  7766.10  7837.95  33309.0 2024-01-02
2     CERA  7840.15  7925.00  7760.75  7776.95  18776.0 2024-01-03
3     CERA  7958.95  7958.95  7730.25  7747.00  18524.0 2024-01-04
4     CERA  7829.95  7829.95  7670.00  7725.95  24296.0 2024-01-05
..     ...      ...      ...      ...      ...      ...        ...
216   CERA  6945.15  7184.95  6888.00  7065.90  29170.0 2024-11-12
217   CERA  7090.00  7090.00  6750.00  6765.40  25286.0 2024-11-13
218   CERA  6872.00  7070.00  6750.05  7009.10  24826.0 2024-11-14
219   CERA  7180.00  7321.00  7055.20  7281.25  50127.0 2024-11-18
220   CERA  7306.50  7320.05  7091.85  7133.25  13950.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close      volume start_Time
0    ADANIPORTS  1026.55  1057.95  1023.00  1047.85   3989711.0 2024-01-01
1    ADANIPORTS  1047.85  1082.90  1031.10  1078.40   6344621.0 2024-01-02
2    ADANIPORTS  1105.00  1144.00  1062.75  1094.25  33060778.0 2024-01-03
3    ADANIPORTS  1117.00  1131.00  1103.55  1123.20   9771995.0 2024-01-04
4    ADANIPORTS  1129.10  1160.00  1125.40  1154.25  10622789.0 2024-01-05
..          ...      ...      ...      ...      ...         ...        ...
216  ADANIPORTS  1348.05  1354.80  1320.00  1326.00   1038042.0 2024-11-12
217  ADANIPORTS  1322.00  1329.25  1284.85  1287.90   1437072.0 2024-11-13
218  ADANIPORTS  1289.95  1296.65  1260.65  1264.55   2963013.0 2024-11-14
219  ADANIPORTS  1264.00  1288.90  1261.30  1279.30   1445637.0 2024-11-18
220  ADANIPORTS  1285.00  1321.45  1282.00  1289.65   2631778.0 2024-11-19

[221 rows x 7 columns]
     Symbol     open     high      low    close    volume start_Time
0    COLPAL  2520.00  2529.00  2480.45  2486.10  357687.0 2024-01-01
1    COLPAL  2486.15  2514.60  2461.00  2502.60  244582.0 2024-01-02
2    COLPAL  2495.00  2502.25  2471.35  2493.40  157313.0 2024-01-03
3    COLPAL  2502.00  2523.85  2496.10  2502.45  336897.0 2024-01-04
4    COLPAL  2505.00  2527.45  2500.00  2514.65  158294.0 2024-01-05
..      ...      ...      ...      ...      ...       ...        ...
216  COLPAL  2872.65  2877.65  2780.10  2789.30  478409.0 2024-11-12
217  COLPAL  2780.00  2799.90  2750.00  2762.90  356627.0 2024-11-13
218  COLPAL  2762.90  2777.65  2701.55  2708.95  540593.0 2024-11-14
219  COLPAL  2727.00  2777.40  2710.00  2749.75  448709.0 2024-11-18
220  COLPAL  2767.60  2785.15  2720.20  2733.50  264874.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

        Symbol    open    high     low   close     volume start_Time
0    JYOTHYLAB  484.25  507.75  480.00  482.55  1467656.0 2024-01-01
1    JYOTHYLAB  482.50  499.00  477.20  484.00   770736.0 2024-01-02
2    JYOTHYLAB  485.90  495.95  481.00  484.50   595384.0 2024-01-03
3    JYOTHYLAB  486.55  505.05  486.55  502.50  1593134.0 2024-01-04
4    JYOTHYLAB  505.80  522.00  503.55  517.95  1175340.0 2024-01-05
..         ...     ...     ...     ...     ...        ...        ...
216  JYOTHYLAB  477.60  502.90  436.35  441.35  2672996.0 2024-11-12
217  JYOTHYLAB  440.00  446.95  417.65  436.10  1594619.0 2024-11-13
218  JYOTHYLAB  434.00  439.35  421.15  427.00   687546.0 2024-11-14
219  JYOTHYLAB  427.70  427.70  411.00  416.10   473243.0 2024-11-18
220  JYOTHYLAB  416.80  420.70  401.20  404.75  1029872.0 2024-11-19

[221 rows x 7 columns]
     Symbol     open     high      low    close    volume start_Time
0    ECLERX  2620.45  2635.00  2540.00  2553.95   73500.0 2024-01-01
1    ECLERX  2565.00  2588.00  2484.05  2505.30  113297.0 2024-01-02
2    ECLERX  2518.95  2599.40  2505.00  2583.05   65612.0 2024-01-03
3    ECLERX  2590.00  2590.05  2535.00  2555.25   45252.0 2024-01-04
4    ECLERX  2564.75  2590.00  2514.25  2572.55   60790.0 2024-01-05
..      ...      ...      ...      ...      ...       ...        ...
216  ECLERX  3385.00  3443.00  3300.00  3321.70  199297.0 2024-11-12
217  ECLERX  3276.25  3387.95  3276.25  3322.40  132151.0 2024-11-13
218  ECLERX  3370.00  3415.50  3325.00  3339.50  104941.0 2024-11-14
219  ECLERX  3320.30  3399.00  3113.25  3128.85  163834.0 2024-11-18
220  ECLERX  3128.85  3324.00  3128.85  3224.00  157270.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol     open     high      low    close     volume start_Time
0    BRIGADE   898.00   920.00   889.00   894.80   259042.0 2024-01-01
1    BRIGADE   896.15   902.00   875.00   877.50   229127.0 2024-01-02
2    BRIGADE   881.30   888.75   863.20   869.35   422705.0 2024-01-03
3    BRIGADE   872.00   984.90   870.10   922.90  4175600.0 2024-01-04
4    BRIGADE   928.80   957.85   919.00   941.80  1329868.0 2024-01-05
..       ...      ...      ...      ...      ...        ...        ...
216  BRIGADE  1104.35  1146.05  1104.15  1124.75   357127.0 2024-11-12
217  BRIGADE  1116.05  1119.40  1060.00  1073.05   291671.0 2024-11-13
218  BRIGADE  1052.00  1100.00  1049.05  1095.55   494881.0 2024-11-14
219  BRIGADE  1098.75  1148.00  1098.75  1135.00   731565.0 2024-11-18
220  BRIGADE  1130.00  1172.70  1123.20  1149.25   342707.0 2024-11-19

[221 rows x 7 columns]
         Symbol     open     high      low    close    volume start_Time
0    BLUESTARCO   947.30   956.50   938.50   948.80  108660.0 2024-01-01
1    BLUESTARCO   954.00   955.00   936.55   951.10  125731.0 2024-01-02
2    BLUESTARCO   951.10   954.50   939.25   941.75   93822.0 2024-01-03
3    BLUESTARCO   942.90   947.45   930.00   935.65  118801.0 2024-01-04
4    BLUESTARCO   939.00   950.00   929.90   944.00  133623.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  BLUESTARCO  1797.60  1817.60  1751.10  1761.20  122952.0 2024-11-12
217  BLUESTARCO  1755.00  1774.45  1730.10  1760.45  430043.0 2024-11-13
218  BLUESTARCO  1752.00  1820.00  1752.00  1808.45  402442.0 2024-11-14
219  BLUESTARCO  1800.00  1834.15  1781.30  1809.55  198215.0 2024-11-18
220  BLUESTARCO  1815.95  1835.00  1792.50  1813.55  166974.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol   open   high    low  close      volume start_Time
0    UJJIVANSFB  56.90  57.30  56.65  57.00   6284431.0 2024-01-01
1    UJJIVANSFB  57.30  57.30  56.20  56.65   4858929.0 2024-01-02
2    UJJIVANSFB  56.75  57.35  56.50  56.85   5087991.0 2024-01-03
3    UJJIVANSFB  59.00  60.50  58.75  59.00  25595256.0 2024-01-04
4    UJJIVANSFB  59.45  59.65  58.00  58.25   8166865.0 2024-01-05
..          ...    ...    ...    ...    ...         ...        ...
216  UJJIVANSFB  35.87  36.33  35.30  35.40   6228521.0 2024-11-12
217  UJJIVANSFB  35.20  35.30  34.00  34.13  10436157.0 2024-11-13
218  UJJIVANSFB  34.18  34.60  33.87  34.00   8386421.0 2024-11-14
219  UJJIVANSFB  34.06  34.59  33.45  33.91   9650875.0 2024-11-18
220  UJJIVANSFB  33.91  34.35  33.43  33.59   9525107.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol     open     high      low    close    volume start_Time
0    CEATLTD  2458.00  2458.00  2409.65  2431.00   80911.0 2024-01-01
1    CEATLTD  2430.00  2448.25  2381.00  2416.40  132338.0 2024-01-02
2    CEATLTD  2422.95  2471.65  2406.60  2447.45  138087.0 2024-01-03
3    CEATLTD  2445.00  2455.00  2427.00  2446.45   88028.0 2024-01-04
4    CEATLTD  2448.95  2465.00  2411.10  2443.05   95867.0 2024-01-05
..       ...      ...      ...      ...      ...       ...        ...
216  CEATLTD  2847.45  2847.45  2756.00  2771.45  108758.0 2024-11-12
217  CEATLTD  2731.00  2747.40  2692.00  2700.60   55588.0 2024-11-13
218  CEATLTD  2670.00  2799.00  2660.00  2773.95   64360.0 2024-11-14
219  CEATLTD  2770.95  2805.00  2736.60  2764.10   43441.0 2024-11-18
220  CEATLTD  2757.95  2844.15  2755.15  2831.00   82285.0 2024-11-19

[221 rows x 7 columns]
     Symbol    open    high     low   close      volume start_Time
0    KNRCON  257.05  260.80  256.90  257.90    565805.0 2024-01-01
1    KNRCON  260.35  264.10  257.20  262.00   1912219.0 2024-01-02
2    KNRCON  262.80  264.50  258.35  259.60    735988.0 2024-01-03
3    KNRCON  261.90  264.50  258.60  259.50    993820.0 2024-01-04
4    KNRCON  260.90  267.30  260.20  265.30   1780823.0 2024-01-05
..      ...     ...     ...     ...     ...         ...        ...
216  KNRCON  283.65  289.80  282.65  284.30    404121.0 2024-11-12
217  KNRCON  306.45  324.85  300.10  307.60  32026734.0 2024-11-13
218  KNRCON  309.15  313.90  298.50  302.45   4316639.0 2024-11-14
219  KNRCON  302.10  317.60  300.70  314.00   2680150.0 2024-11-18
220  KNRCON  316.35  321.80  308.10  311.85   1505471.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol   open   high    low  close      volume start_Time
0      IRB  41.55  42.50  41.50  41.85  20165348.0 2024-01-01
1      IRB  41.95  42.00  41.10  41.30  13407529.0 2024-01-02
2      IRB  41.30  41.80  41.05  41.55  12161090.0 2024-01-03
3      IRB  41.60  43.60  41.55  43.15  47299270.0 2024-01-04
4      IRB  43.35  43.50  42.00  42.45  20810476.0 2024-01-05
..     ...    ...    ...    ...    ...         ...        ...
216    IRB  51.48  52.19  50.00  50.23  11141250.0 2024-11-12
217    IRB  50.00  50.06  48.30  48.52  14937220.0 2024-11-13
218    IRB  48.51  49.49  47.61  47.76  17659040.0 2024-11-14
219    IRB  47.87  48.46  47.15  47.40  16499498.0 2024-11-18
220    IRB  47.50  48.83  47.27  47.42  14175300.0 2024-11-19

[221 rows x 7 columns]
       Symbol    open     high      low    close     volume start_Time
0    TVSMOTOR  2032.0  2046.55  2012.00  2019.05   474552.0 2024-01-01
1    TVSMOTOR  2025.0  2039.80  1952.15  1969.15  1407673.0 2024-01-02
2    TVSMOTOR  1977.0  2015.90  1960.35  1997.90   837553.0 2024-01-03
3    TVSMOTOR  2008.0  2014.10  1979.30  1982.60   982876.0 2024-01-04
4    TVSMOTOR  1989.8  2011.25  1969.25  1979.30  2259906.0 2024-01-05
..        ...     ...      ...      ...      ...        ...        ...
216  TVSMOTOR  2460.0  2485.00  2430.00  2440.30   488274.0 2024-11-12
217  TVSMOTOR  2421.8  2425.95  2356.95  2385.75  1158274.0 2024-11-13
218  TVSMOTOR  2375.0  2415.00  2360.00  2396.15   308515.0 2024-11-14
219  TVSMOTOR  2409.0  2443.30  2395.05  2416.00   369073.0 2024-11-18
220  TVSMOTOR  2419.8  2469.90  2413.60  2429.25   349283.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close      volume start_Time
0     NMDC  210.90  214.90  209.25  211.45  17205283.0 2024-01-01
1     NMDC  213.05  220.00  210.55  217.75  35438178.0 2024-01-02
2     NMDC  217.65  219.55  213.00  217.40  15118202.0 2024-01-03
3     NMDC  219.05  224.50  219.05  223.55  19777700.0 2024-01-04
4     NMDC  223.00  227.30  220.10  222.70  15321761.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216   NMDC  232.00  232.27  222.80  224.76  31593557.0 2024-11-12
217   NMDC  224.69  226.70  220.50  223.21  15471635.0 2024-11-13
218   NMDC  223.71  228.50  218.10  218.80   9987841.0 2024-11-14
219   NMDC  220.06  229.40  219.16  222.71  15886590.0 2024-11-18
220   NMDC  223.75  225.30  219.50  221.22  11375355.0 2024-11-19

[221 rows x 7 columns]
     Symbol   open    high     low   close      volume start_Time
0    RECLTD  413.7  432.65  410.70  424.85  12660166.0 2024-01-01
1    RECLTD  426.0  426.65  412.00  419.70  11435302.0 2024-01-02
2    RECLTD  421.0  431.85  415.35  423.55  10747906.0 2024-01-03
3    RECLTD  426.0  437.70  425.25  435.80  11523818.0 2024-01-04
4    RECLTD  440.0  440.15  428.65  434.30   7441404.0 2024-01-05
..      ...    ...     ...     ...     ...         ...        ...
216  RECLTD  531.0  534.70  512.80  514.50   6039729.0 2024-11-12
217  RECLTD  515.5  519.55  499.35  508.45   8600781.0 2024-11-13
218  RECLTD  510.0  513.80  500.30  502.35   7471948.0 2024-11-14
219  RECLTD  505.3  510.15  495.50  501.00   6676581.0 2024-11-18
220  RECLTD  510.0  525.70  508.15  516.60  10710390.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

     Symbol    open    high     low   close    volume start_Time
0    VGUARD  293.30  294.60  289.90  291.40  229908.0 2024-01-01
1    VGUARD  291.40  292.40  287.85  290.00  264805.0 2024-01-02
2    VGUARD  289.95  295.50  288.55  294.75  394304.0 2024-01-03
3    VGUARD  296.00  297.00  294.15  295.10  273672.0 2024-01-04
4    VGUARD  295.45  296.50  292.25  293.95  257381.0 2024-01-05
..      ...     ...     ...     ...     ...       ...        ...
216  VGUARD  426.60  428.80  414.45  417.10  133172.0 2024-11-12
217  VGUARD  417.70  417.70  402.90  409.70  265391.0 2024-11-13
218  VGUARD  409.30  413.50  403.10  405.55  152076.0 2024-11-14
219  VGUARD  404.55  405.45  394.40  396.80  222195.0 2024-11-18
220  VGUARD  394.15  429.35  394.10  425.55  619772.0 2024-11-19

[221 rows x 7 columns]
      Symbol     open     high      low    close     volume start_Time
0    MANKIND  1990.00  2007.65  1967.30  1979.20    97989.0 2024-01-01
1    MANKIND  1991.00  2164.80  1983.20  2107.20  1313720.0 2024-01-02
2    MANKIND  2099.00  2177.00  2077.80  2155.55   447782.0 2024-01-03
3    MANKIND  2155.85  2164.45  2060.00  2074.05   588327.0 2024-01-04
4    MANKIND  2090.00  2090.05  2050.00  2057.65   669666.0 2024-01-05
..       ...      ...      ...      ...      ...        ...        ...
216  MANKIND  2654.90  2689.90  2610.00  2622.10   162333.0 2024-11-12
217  MANKIND  2615.05  2615.05  2506.05  2532.15   385462.0 2024-11-13
218  MANKIND  2532.15  2666.00  2532.15  2597.65   347189.0 2024-11-14
219  MANKIND  2599.90  2645.85  2580.00  2597.90   207098.0 2024-11-18
220  MANKIND  2630.00  2639.25  2558.45  2574.40   177969.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

     Symbol    open    high     low   close    volume start_Time
0    CHALET  699.00  700.90  684.15  687.75  188557.0 2024-01-01
1    CHALET  692.60  692.60  674.00  677.80  260946.0 2024-01-02
2    CHALET  677.80  682.05  671.30  677.85   88637.0 2024-01-03
3    CHALET  679.75  693.50  678.05  679.85  149681.0 2024-01-04
4    CHALET  683.25  690.00  678.15  685.05  104880.0 2024-01-05
..      ...     ...     ...     ...     ...       ...        ...
216  CHALET  875.00  886.45  855.50  858.60  117135.0 2024-11-12
217  CHALET  851.20  858.00  813.00  818.55  166205.0 2024-11-13
218  CHALET  814.00  866.00  810.80  844.15   86110.0 2024-11-14
219  CHALET  841.40  855.20  831.05  844.25   76102.0 2024-11-18
220  CHALET  838.00  858.00  831.95  838.90   99639.0 2024-11-19

[221 rows x 7 columns]
       Symbol     open     high      low    close     volume start_Time
0    TITAGARH  1047.90  1063.00  1037.90  1041.80   829383.0 2024-01-01
1    TITAGARH  1045.00  1046.95  1011.00  1029.40  1016167.0 2024-01-02
2    TITAGARH  1030.00  1032.10  1011.00  1013.70   714005.0 2024-01-03
3    TITAGARH  1018.85  1032.00  1018.00  1021.10   499272.0 2024-01-04
4    TITAGARH  1026.20  1027.20  1001.40  1007.10   637072.0 2024-01-05
..        ...      ...      ...      ...      ...        ...        ...
216  TITAGARH  1190.00  1197.45  1137.65  1144.10   629733.0 2024-11-12
217  TITAGARH  1148.70  1153.90  1080.00  1089.20  1081265.0 2024-11-13
218  TITAGARH  1093.40  1119.50  1089.45  1110.40   744104.0 2024-11-14
219  TITAGARH  1116.95  1119.00  1082.20  1098.55   618145.0 2024-11-18
220  TITAGARH  1108.50  1133.90  1102.45  1112.70   667955.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol    open    high     low   close     volume start_Time
0    NLCINDIA  254.90  260.25  249.00  250.20  5471005.0 2024-01-01
1    NLCINDIA  251.05  251.50  238.55  239.85  6151198.0 2024-01-02
2    NLCINDIA  241.95  244.50  228.20  229.20  7899717.0 2024-01-03
3    NLCINDIA  231.50  238.25  228.75  230.90  8208071.0 2024-01-04
4    NLCINDIA  234.05  235.35  223.50  225.15  5711818.0 2024-01-05
..        ...     ...     ...     ...     ...        ...        ...
216  NLCINDIA  247.05  250.40  236.00  238.15   841397.0 2024-11-12
217  NLCINDIA  235.05  241.80  233.95  236.40  1564710.0 2024-11-13
218  NLCINDIA  233.00  238.95  231.50  232.30   728860.0 2024-11-14
219  NLCINDIA  232.00  238.90  226.25  234.60  1402715.0 2024-11-18
220  NLCINDIA  234.60  238.60  232.95  237.00   803088.0 2024-11-19

[221 rows x 7 columns]
    Symbol   open   high    low  close      volume start_Time
0    MSUMI  62.25  63.30  61.70  62.15   8090211.0 2024-01-01
1    MSUMI  62.30  63.05  61.20  61.55  12295620.0 2024-01-02
2    MSUMI  61.80  62.60  61.00  61.50  20314444.0 2024-01-03
3    MSUMI  61.65  62.40  61.65  62.00   4766000.0 2024-01-04
4    MSUMI  62.70  66.00  62.10  65.65  41498481.0 2024-01-05
..     ...    ...    ...    ...    ...         ...        ...
216  MSUMI  63.30  63.69  62.02  62.23   1953221.0 2024-11-12
217  MSUMI  62.00  62.40  60.01  60.28   4636825.0 2024-11-13
218  MSUMI  60.28  61.33  60.10  60.93   5841352.0 2024-11-14
219  MSUMI  60.00  61.85  60.00  61.02   3242583.0 2024-11-18
220  MSUMI  60.68  61.94  60.68  61.47  13026766.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close    volume start_Time
0     GAEL  184.45  184.85  179.88  181.08  268142.0 2024-01-01
1     GAEL  181.08  184.48  179.03  181.65  353577.0 2024-01-02
2     GAEL  183.10  183.25  178.65  179.23  280363.0 2024-01-03
3     GAEL  179.90  182.93  179.90  180.40  181047.0 2024-01-04
4     GAEL  181.95  183.90  180.08  181.85  341396.0 2024-01-05
..     ...     ...     ...     ...     ...       ...        ...
216   GAEL  131.19  132.01  126.70  127.19  460832.0 2024-11-12
217   GAEL  127.20  127.55  121.39  121.90  874932.0 2024-11-13
218   GAEL  124.41  124.94  121.00  121.47  858065.0 2024-11-14
219   GAEL  121.50  122.60  118.89  120.38  533774.0 2024-11-18
220   GAEL  120.80  123.03  120.05  120.79  862726.0 2024-11-19

[221 rows x 7 columns]
       Symbol    open    high     low   close     volume start_Time
0    USHAMART  294.30  298.00  288.50  291.40  1013803.0 2024-01-01
1    USHAMART  291.75  298.35  290.00  294.95   600700.0 2024-01-02
2    USHAMART  294.95  302.65  293.75  299.25   426496.0 2024-01-03
3    USHAMART  300.70  314.30  300.70  312.65  1362200.0 2024-01-04
4    USHAMART  315.10  317.30  308.20  310.55   802518.0 2024-01-05
..        ...     ...     ...     ...     ...        ...        ...
216  USHAMART  392.65  398.80  382.90  384.60   559273.0 2024-11-12
217  USHAMART  384.30  384.30  363.70  367.90  1251190.0 2024-11-13
218  USHAMART  372.35  388.65  370.85  380.80  1180997.0 2024-11-14
219  USHAMART  379.90  389.70  374.95  384.40   711460.0 2024-11-18
220  USHAMART  389.25  402.45  387.00  395.30   712745.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close     volume start_Time
0      JWL  318.95  324.90  318.95  319.90   608036.0 2024-01-01
1      JWL  320.55  322.40  314.55  318.30   426125.0 2024-01-02
2      JWL  318.25  319.90  315.00  317.80   466491.0 2024-01-03
3      JWL  318.00  333.65  316.50  330.90  2437670.0 2024-01-04
4      JWL  339.50  345.00  337.00  342.80  3475002.0 2024-01-05
..     ...     ...     ...     ...     ...        ...        ...
216    JWL  475.70  482.30  455.90  457.05   712436.0 2024-11-12
217    JWL  458.00  473.40  437.85  439.70  2699910.0 2024-11-13
218    JWL  441.00  454.00  434.05  436.20   968071.0 2024-11-14
219    JWL  436.25  440.00  425.20  436.40   695005.0 2024-11-18
220    JWL  440.00  453.80  436.55  440.80   685036.0 2024-11-19

[221 rows x 7 columns]
         Symbol     open     high      low    close     volume start_Time
0    OBEROIRLTY  1441.00  1460.00  1430.00  1448.55   158437.0 2024-01-01
1    OBEROIRLTY  1455.00  1461.15  1432.20  1439.60   304154.0 2024-01-02
2    OBEROIRLTY  1439.65  1467.75  1433.00  1459.00   345845.0 2024-01-03
3    OBEROIRLTY  1462.00  1547.35  1456.20  1533.30  2014137.0 2024-01-04
4    OBEROIRLTY  1556.00  1556.00  1508.60  1518.65  1555320.0 2024-01-05
..          ...      ...      ...      ...      ...        ...        ...
216  OBEROIRLTY  2025.60  2044.00  1981.00  1989.65  1372529.0 2024-11-12
217  OBEROIRLTY  1989.00  2011.15  1911.40  1927.15  1519807.0 2024-11-13
218  OBEROIRLTY  1936.00  2005.20  1922.75  1980.30  1392570.0 2024-11-14
219  OBEROIRLTY  1977.05  1989.30  1905.00  1911.40  1363298.0 2024-11-18
220  OBEROIRLTY  1915.50  1979.75  1915.50  1932.75  1173547.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol   open   high    low  close     volume start_Time
0     TTML  91.70  92.75  91.10  91.40  2624139.0 2024-01-01
1     TTML  91.70  92.40  90.45  91.25  3298817.0 2024-01-02
2     TTML  91.20  92.30  90.45  90.70  2415922.0 2024-01-03
3     TTML  91.15  94.25  91.10  91.80  7588091.0 2024-01-04
4     TTML  92.10  94.00  91.35  91.60  6131970.0 2024-01-05
..     ...    ...    ...    ...    ...        ...        ...
216   TTML  70.50  71.51  69.00  69.53  2897326.0 2024-11-12
217   TTML  69.54  69.65  66.70  67.11  2525546.0 2024-11-13
218   TTML  67.92  68.78  67.30  67.61  2348689.0 2024-11-14
219   TTML  67.65  68.45  66.60  67.40  2227361.0 2024-11-18
220   TTML  67.86  69.69  67.82  68.36  2227524.0 2024-11-19

[221 rows x 7 columns]
       Symbol     open     high      low    close     volume start_Time
0    TATATECH  1184.00  1197.90  1180.00  1180.45   794228.0 2024-01-01
1    TATATECH  1184.00  1188.90  1177.00  1181.95   720393.0 2024-01-02
2    TATATECH  1180.00  1185.00  1168.00  1172.05   937005.0 2024-01-03
3    TATATECH  1175.00  1181.55  1169.45  1171.35   706442.0 2024-01-04
4    TATATECH  1173.50  1179.35  1170.00  1171.35   824122.0 2024-01-05
..        ...      ...      ...      ...      ...        ...        ...
216  TATATECH   999.00  1005.65   990.05   993.30   471171.0 2024-11-12
217  TATATECH   991.35   997.10   956.65   961.50  1248272.0 2024-11-13
218  TATATECH   961.50   971.65   957.00   962.30   639883.0 2024-11-14
219  TATATECH   968.00   968.00   940.00   941.20   985878.0 2024-11-18
220  TATATECH   944.10   959.00   943.10   948.55   633404.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol     open     high      low    close     volume start_Time
0    PRESTIGE  1162.90  1212.90  1160.00  1188.70   826558.0 2024-01-01
1    PRESTIGE  1180.10  1219.65  1171.40  1201.60   547303.0 2024-01-02
2    PRESTIGE  1194.05  1311.15  1188.00  1258.25   723269.0 2024-01-03
3    PRESTIGE  1244.55  1416.90  1240.00  1355.35  1903112.0 2024-01-04
4    PRESTIGE  1343.15  1383.05  1313.05  1329.65  1476137.0 2024-01-05
..        ...      ...      ...      ...      ...        ...        ...
216  PRESTIGE  1600.05  1633.00  1580.00  1592.60   403123.0 2024-11-12
217  PRESTIGE  1587.70  1590.55  1505.95  1519.60   861736.0 2024-11-13
218  PRESTIGE  1524.60  1553.00  1508.65  1547.20   615995.0 2024-11-14
219  PRESTIGE  1569.95  1590.00  1527.30  1541.15   562367.0 2024-11-18
220  PRESTIGE  1531.00  1595.00  1526.05  1582.95   654595.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close    volume start_Time
0     CGCL  191.20  196.25  191.20  193.73   39942.0 2024-01-01
1     CGCL  194.70  195.29  192.08  192.93   49002.0 2024-01-02
2     CGCL  192.93  195.10  192.33  193.86   35015.0 2024-01-03
3     CGCL  193.86  193.86  191.39  193.18   35298.0 2024-01-04
4     CGCL  193.18  198.36  192.51  194.09  124694.0 2024-01-05
..     ...     ...     ...     ...     ...       ...        ...
216   CGCL  203.30  206.80  198.35  199.99  207892.0 2024-11-12
217   CGCL  198.35  199.00  190.00  191.21  124058.0 2024-11-13
218   CGCL  190.50  194.15  189.17  191.48   91851.0 2024-11-14
219   CGCL  191.10  191.10  186.97  189.43   99934.0 2024-11-18
220   CGCL  189.50  193.59  189.01  190.77  114741.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

        Symbol    open    high     low   close      volume start_Time
0    COALINDIA  377.80  386.80  377.45  381.80  11124690.0 2024-01-01
1    COALINDIA  387.40  395.85  384.25  392.65  28363847.0 2024-01-02
2    COALINDIA  394.80  394.80  383.85  384.55  12903439.0 2024-01-03
3    COALINDIA  387.80  389.80  383.90  384.75  11039940.0 2024-01-04
4    COALINDIA  386.80  388.50  382.50  384.25   8369460.0 2024-01-05
..         ...     ...     ...     ...     ...         ...        ...
216  COALINDIA  422.50  424.80  412.80  414.05   6564348.0 2024-11-12
217  COALINDIA  414.00  415.50  405.70  406.90   7170870.0 2024-11-13
218  COALINDIA  407.20  413.35  402.60  409.75   8776485.0 2024-11-14
219  COALINDIA  413.95  418.50  411.00  413.35   7352509.0 2024-11-18
220  COALINDIA  415.95  422.00  410.70  412.25   6291292.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open     high      low    close    volume start_Time
0     DOMS  1250.80  1285.00  1245.55  1278.30  260880.0 2024-01-01
1     DOMS  1283.85  1292.70  1262.00  1281.90  211794.0 2024-01-02
2     DOMS  1280.00  1300.00  1271.00  1294.45  180756.0 2024-01-03
3     DOMS  1285.10  1315.70  1285.10  1311.90  198156.0 2024-01-04
4     DOMS  1310.05  1325.00  1310.00  1321.85  113809.0 2024-01-05
..     ...      ...      ...      ...      ...       ...        ...
216   DOMS  2788.05  2794.50  2660.00  2679.55   94255.0 2024-11-12
217   DOMS  2669.05  2673.00  2580.05  2599.30   59091.0 2024-11-13
218   DOMS  2640.00  2693.60  2599.30  2687.30   89729.0 2024-11-14
219   DOMS  2699.40  2768.90  2652.30  2710.05   53374.0 2024-11-18
220   DOMS  2710.05  2789.95  2665.00  2727.45   79016.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close      volume start_Time
0    HUDCO  126.00  133.95  122.75  129.10  59160163.0 2024-01-01
1    HUDCO  129.80  130.40  125.40  127.15  21117216.0 2024-01-02
2    HUDCO  127.10  130.50  125.75  126.80  17954305.0 2024-01-03
3    HUDCO  127.60  132.35  126.65  128.60  24596544.0 2024-01-04
4    HUDCO  129.35  130.20  124.70  127.70  14924792.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216  HUDCO  216.50  219.50  209.15  210.23   2048294.0 2024-11-12
217  HUDCO  208.50  211.34  200.00  201.88   3583467.0 2024-11-13
218  HUDCO  201.88  208.79  200.40  202.04   3222372.0 2024-11-14
219  HUDCO  203.00  206.74  198.01  203.65   3238799.0 2024-11-18
220  HUDCO  207.80  214.47  205.22  206.70   3556608.0 2024-11-19

[221 rows x 7 columns]
         Symbol     open     high      low    close    volume start_Time
0    HAPPYFORGE  1029.25  1039.70  1006.95  1029.70  421088.0 2024-01-01
1    HAPPYFORGE  1028.00  1032.35  1002.95  1007.05  234307.0 2024-01-02
2    HAPPYFORGE  1006.00  1024.30   997.55  1015.85  251757.0 2024-01-03
3    HAPPYFORGE  1021.00  1030.00  1008.00  1015.85  247094.0 2024-01-04
4    HAPPYFORGE  1020.00  1029.75   997.10  1000.50  432820.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  HAPPYFORGE  1123.50  1125.95  1081.05  1091.20   28454.0 2024-11-12
217  HAPPYFORGE  1083.00  1083.50  1049.05  1072.90   11618.0 2024-11-13
218  HAPPYFORGE  1080.00  1132.50  1065.10  1081.35   26514.0 2024-11-14
219  HAPPYFORGE  1090.00  1115.90  1041.00  1062.10   41201.0 2024-11-18
220  HAPPYFORGE  1065.00  1090.10  1064.75  1081.00   46288.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol    open    high     low   close    volume start_Time
0    PRINCEPIPE  747.00  758.65  734.05  751.60  364598.0 2024-01-01
1    PRINCEPIPE  750.00  756.20  740.00  750.40  203936.0 2024-01-02
2    PRINCEPIPE  748.00  748.00  736.00  737.20  122745.0 2024-01-03
3    PRINCEPIPE  740.85  767.90  738.70  759.95  365775.0 2024-01-04
4    PRINCEPIPE  769.90  776.00  740.00  743.35  336714.0 2024-01-05
..          ...     ...     ...     ...     ...       ...        ...
216  PRINCEPIPE  452.00  458.00  450.95  453.85  145927.0 2024-11-12
217  PRINCEPIPE  453.85  454.20  440.65  442.30  150268.0 2024-11-13
218  PRINCEPIPE  440.65  448.20  438.55  442.15   89287.0 2024-11-14
219  PRINCEPIPE  442.15  449.00  432.55  437.75  103756.0 2024-11-18
220  PRINCEPIPE  438.05  447.15  438.05  441.50   99079.0 2024-11-19

[221 rows x 7 columns]
      Symbol    open    high     low   close     volume start_Time
0    STLTECH  144.00  150.10  143.65  148.45  3569274.0 2024-01-01
1    STLTECH  148.85  148.85  144.55  146.60  1455737.0 2024-01-02
2    STLTECH  146.95  147.70  146.00  146.45   862147.0 2024-01-03
3    STLTECH  146.95  152.50  146.85  148.75  4402321.0 2024-01-04
4    STLTECH  149.30  150.00  147.20  148.10  1934746.0 2024-01-05
..       ...     ...     ...     ...     ...        ...        ...
216  STLTECH  121.20  124.40  118.50  119.05  1411958.0 2024-11-12
217  STLTECH  118.50  121.90  116.52  117.38  5016198.0 2024-11-13
218  STLTECH  117.55  121.25  117.31  118.26  1343460.0 2024-11-14
219  STLTECH  118.20  119.00  115.20  115.77  1070691.0 2024-11-18
220  STLTECH  116.06  117.95  115.00  115.52   984605.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol   open   high    low  close      volume start_Time
0      IOB  43.25  44.30  43.15  43.60  12879177.0 2024-01-01
1      IOB  43.80  44.70  43.25  43.45  18828371.0 2024-01-02
2      IOB  43.50  44.90  43.35  43.95  28327760.0 2024-01-03
3      IOB  44.10  44.60  43.95  44.10  15527140.0 2024-01-04
4      IOB  44.35  44.70  43.50  43.90  13363697.0 2024-01-05
..     ...    ...    ...    ...    ...         ...        ...
216    IOB  52.70  53.36  51.03  51.48   3275324.0 2024-11-12
217    IOB  50.71  51.41  49.17  49.32   5350849.0 2024-11-13
218    IOB  49.50  51.60  49.05  49.55   7255657.0 2024-11-14
219    IOB  49.75  51.15  48.57  49.89   5889091.0 2024-11-18
220    IOB  50.50  52.25  50.10  51.13   8123270.0 2024-11-19

[221 rows x 7 columns]
     Symbol    open    high     low   close     volume start_Time
0    CAMPUS  280.00  286.90  279.90  285.05   887572.0 2024-01-01
1    CAMPUS  286.85  296.50  285.05  295.20  3404098.0 2024-01-02
2    CAMPUS  295.20  296.40  289.40  293.35  1258264.0 2024-01-03
3    CAMPUS  295.55  296.00  290.00  290.25   541963.0 2024-01-04
4    CAMPUS  290.45  294.65  286.05  289.90   581777.0 2024-01-05
..      ...     ...     ...     ...     ...        ...        ...
216  CAMPUS  307.40  309.40  291.80  293.50   569202.0 2024-11-12
217  CAMPUS  290.00  295.65  277.30  279.90   632705.0 2024-11-13
218  CAMPUS  281.85  286.60  273.50  274.60   525100.0 2024-11-14
219  CAMPUS  274.00  277.95  267.50  268.70   680949.0 2024-11-18
220  CAMPUS  265.50  272.65  261.50  262.65   772990.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol    open    high     low   close     volume start_Time
0    PNCINFRA  352.80  354.70  348.10  349.80   145384.0 2024-01-01
1    PNCINFRA  350.80  352.45  344.30  349.20   221019.0 2024-01-02
2    PNCINFRA  349.90  356.00  347.00  348.90   344306.0 2024-01-03
3    PNCINFRA  351.50  354.95  349.75  352.35   275683.0 2024-01-04
4    PNCINFRA  354.75  355.85  350.05  350.90   279111.0 2024-01-05
..        ...     ...     ...     ...     ...        ...        ...
216  PNCINFRA  326.00  327.80  316.35  317.95   260531.0 2024-11-12
217  PNCINFRA  303.95  312.70  295.55  309.20  1193668.0 2024-11-13
218  PNCINFRA  305.00  312.00  298.00  299.05   463294.0 2024-11-14
219  PNCINFRA  291.35  309.90  290.05  302.40   527698.0 2024-11-18
220  PNCINFRA  303.00  306.80  296.30  299.80   382000.0 2024-11-19

[221 rows x 7 columns]
      Symbol     open     high      low    close    volume start_Time
0    RAINBOW  1200.40  1224.00  1183.00  1220.30  234465.0 2024-01-01
1    RAINBOW  1238.55  1238.55  1195.70  1207.20  150464.0 2024-01-02
2    RAINBOW  1210.00  1212.15  1194.00  1201.75  109258.0 2024-01-03
3    RAINBOW  1205.05  1248.00  1194.85  1226.00  156733.0 2024-01-04
4    RAINBOW  1235.00  1256.95  1227.85  1251.15  124393.0 2024-01-05
..       ...      ...      ...      ...      ...       ...        ...
216  RAINBOW  1569.80  1664.00  1550.20  1624.45  641037.0 2024-11-12
217  RAINBOW  1611.05  1619.55  1568.30  1599.35  224625.0 2024-11-13
218  RAINBOW  1618.65  1684.00  1601.00  1649.75  688672.0 2024-11-14
219  RAINBOW  1652.00  1652.55  1577.25  1596.05  199072.0 2024-11-18
220  RAINBOW  1603.30  1605.80  1545.25  1578.50  237118.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close     volume start_Time
0     LICI  831.50  864.00  831.00  858.75  6424762.0 2024-01-01
1     LICI  853.80  856.90  836.00  837.70  3672560.0 2024-01-02
2     LICI  837.70  853.30  836.10  838.75  3684845.0 2024-01-03
3     LICI  837.00  845.90  833.00  835.25  2024609.0 2024-01-04
4     LICI  836.60  860.95  836.60  844.40  4193233.0 2024-01-05
..     ...     ...     ...     ...     ...        ...        ...
216   LICI  930.50  958.00  918.00  921.15  2255309.0 2024-11-12
217   LICI  922.00  924.90  890.05  897.90  1326985.0 2024-11-13
218   LICI  905.00  924.50  895.60  908.65  1221663.0 2024-11-14
219   LICI  908.65  916.95  900.00  901.75   667386.0 2024-11-18
220   LICI  910.00  916.65  894.00  896.65   778486.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close      volume start_Time
0     RVNL  181.90  185.60  181.10  182.00  13833701.0 2024-01-01
1     RVNL  182.40  183.40  177.50  180.80   7909774.0 2024-01-02
2     RVNL  182.90  189.00  182.75  185.30  45596593.0 2024-01-03
3     RVNL  186.65  188.40  184.50  185.50  15879759.0 2024-01-04
4     RVNL  186.35  186.90  183.00  184.65  10233509.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216   RVNL  444.00  450.85  432.00  437.70   3668960.0 2024-11-12
217   RVNL  432.25  451.85  418.00  419.85   5236303.0 2024-11-13
218   RVNL  419.55  428.45  416.10  419.50   3814197.0 2024-11-14
219   RVNL  418.65  427.85  409.50  416.20   4451811.0 2024-11-18
220   RVNL  420.50  435.05  419.50  432.15   5166306.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close    volume start_Time
0    METROPOLIS  1684.50  1702.90  1670.30  1674.55  106392.0 2024-01-01
1    METROPOLIS  1672.20  1728.00  1666.70  1720.20  415671.0 2024-01-02
2    METROPOLIS  1723.00  1742.60  1700.20  1708.05  312062.0 2024-01-03
3    METROPOLIS  1708.05  1720.75  1682.00  1696.00  172725.0 2024-01-04
4    METROPOLIS  1707.45  1714.45  1656.15  1674.45  266244.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  METROPOLIS  2154.80  2235.95  2142.00  2174.30  167022.0 2024-11-12
217  METROPOLIS  2165.00  2195.70  2037.15  2050.15  359837.0 2024-11-13
218  METROPOLIS  2045.00  2069.10  2024.30  2032.20   99058.0 2024-11-14
219  METROPOLIS  2029.50  2041.15  1996.55  2021.20  228048.0 2024-11-18
220  METROPOLIS  2025.70  2059.65  2011.15  2020.70   63237.0 2024-11-19

[221 rows x 7 columns]
      Symbol     open     high      low    close    volume start_Time
0    POLYCAB  5500.00  5530.45  5449.95  5464.70  146403.0 2024-01-01
1    POLYCAB  5464.70  5470.00  5330.00  5346.60  281635.0 2024-01-02
2    POLYCAB  5340.05  5426.60  5309.00  5404.55  250172.0 2024-01-03
3    POLYCAB  5404.55  5452.00  5337.15  5394.60  282732.0 2024-01-04
4    POLYCAB  5433.00  5441.85  5358.05  5401.30  140560.0 2024-01-05
..       ...      ...      ...      ...      ...       ...        ...
216  POLYCAB  6720.00  6756.00  6486.10  6502.75  199839.0 2024-11-12
217  POLYCAB  6465.00  6479.95  6264.15  6328.25  232394.0 2024-11-13
218  POLYCAB  6334.95  6400.00  6277.45  6301.90  191359.0 2024-11-14
219  POLYCAB  6295.90  6485.70  6257.50  6444.65  455631.0 2024-11-18
220  POLYCAB  6493.00  6610.40  6460.00  6517.05  197471.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

        Symbol    open    high     low   close     volume start_Time
0    DELHIVERY  392.40  393.90  382.55  384.35   644267.0 2024-01-01
1    DELHIVERY  384.95  389.00  381.35  388.55  1000156.0 2024-01-02
2    DELHIVERY  389.95  404.40  389.50  397.00  3135290.0 2024-01-03
3    DELHIVERY  403.50  405.00  397.90  404.00  1886025.0 2024-01-04
4    DELHIVERY  406.95  407.65  401.00  403.25  1811978.0 2024-01-05
..         ...     ...     ...     ...     ...        ...        ...
216  DELHIVERY  341.50  348.20  337.05  340.00  1522754.0 2024-11-12
217  DELHIVERY  337.65  338.70  328.00  330.30   871368.0 2024-11-13
218  DELHIVERY  328.35  337.40  328.35  330.55  1408544.0 2024-11-14
219  DELHIVERY  338.95  345.00  325.50  327.30  4113456.0 2024-11-18
220  DELHIVERY  327.30  352.95  327.30  344.25  7769626.0 2024-11-19

[221 rows x 7 columns]
       Symbol     open     high      low    close     volume start_Time
0    KPITTECH  1513.85  1515.90  1488.25  1490.50   813082.0 2024-01-01
1    KPITTECH  1498.45  1498.50  1458.60  1467.85   912412.0 2024-01-02
2    KPITTECH  1472.90  1488.70  1455.10  1462.70   645767.0 2024-01-03
3    KPITTECH  1460.00  1485.00  1459.00  1472.40   702692.0 2024-01-04
4    KPITTECH  1479.00  1509.00  1470.90  1506.55   920923.0 2024-01-05
..        ...      ...      ...      ...      ...        ...        ...
216  KPITTECH  1430.00  1430.95  1385.00  1390.40   503631.0 2024-11-12
217  KPITTECH  1398.00  1447.45  1339.00  1357.95  1283088.0 2024-11-13
218  KPITTECH  1355.00  1367.75  1341.00  1356.95  1185496.0 2024-11-14
219  KPITTECH  1350.25  1356.40  1323.25  1325.75   864715.0 2024-11-18
220  KPITTECH  1322.10  1340.00  1301.80  1305.20  1566382.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol   open   high    low  close       volume start_Time
0    TRIDENT  36.70  36.95  36.05  36.55    8865901.0 2024-01-01
1    TRIDENT  36.85  38.25  36.10  37.40   24691067.0 2024-01-02
2    TRIDENT  37.45  38.65  37.40  37.90   33179315.0 2024-01-03
3    TRIDENT  38.30  39.10  37.85  38.30   28478030.0 2024-01-04
4    TRIDENT  38.65  41.60  37.95  40.90  145424351.0 2024-01-05
..       ...    ...    ...    ...    ...          ...        ...
216  TRIDENT  32.90  33.16  32.60  32.70    2827263.0 2024-11-12
217  TRIDENT  32.70  32.74  31.60  31.72    4987387.0 2024-11-13
218  TRIDENT  31.79  32.36  31.65  31.78    3788739.0 2024-11-14
219  TRIDENT  31.95  32.35  31.32  31.61    4934890.0 2024-11-18
220  TRIDENT  31.63  32.14  31.63  31.87    3213034.0 2024-11-19

[221 rows x 7 columns]
         Symbol     open     high      low    close     volume start_Time
0    BAJAJ-AUTO  6770.00  6795.50  6682.05  6701.10   253274.0 2024-01-01
1    BAJAJ-AUTO  6711.00  6736.80  6560.95  6665.05   361379.0 2024-01-02
2    BAJAJ-AUTO  6644.05  7059.85  6604.00  6986.50  1256275.0 2024-01-03
3    BAJAJ-AUTO  7025.00  7028.95  6887.00  6922.15   619987.0 2024-01-04
4    BAJAJ-AUTO  6950.00  7084.00  6920.50  6978.50   659306.0 2024-01-05
..          ...      ...      ...      ...      ...        ...        ...
216  BAJAJ-AUTO  9900.00  9999.00  9662.00  9678.70   316606.0 2024-11-12
217  BAJAJ-AUTO  9678.70  9710.00  9416.10  9452.15   494123.0 2024-11-13
218  BAJAJ-AUTO  9410.00  9516.95  9400.00  9482.95   275791.0 2024-11-14
219  BAJAJ-AUTO  9459.05  9603.00  9435.85  9516.50   292519.0 2024-11-18
220  BAJAJ-AUTO  9560.00  9698.60  9500.45  9545.70   365397.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close     volume start_Time
0    BAJAJFINSV  1685.80  1691.70  1671.00  1676.40   692280.0 2024-01-01
1    BAJAJFINSV  1675.90  1689.85  1663.45  1686.20  1099965.0 2024-01-02
2    BAJAJFINSV  1680.00  1708.00  1676.00  1677.65   804258.0 2024-01-03
3    BAJAJFINSV  1694.35  1723.95  1690.00  1701.95  2268009.0 2024-01-04
4    BAJAJFINSV  1702.95  1717.10  1697.65  1709.50   835592.0 2024-01-05
..          ...      ...      ...      ...      ...        ...        ...
216  BAJAJFINSV  1725.00  1732.95  1688.75  1691.75   903492.0 2024-11-12
217  BAJAJFINSV  1690.00  1695.95  1657.45  1664.45   668302.0 2024-11-13
218  BAJAJFINSV  1665.00  1673.55  1633.55  1639.80   744472.0 2024-11-14
219  BAJAJFINSV  1634.00  1641.95  1610.00  1616.00  1618700.0 2024-11-18
220  BAJAJFINSV  1622.95  1625.95  1580.55  1596.35  2569730.0 2024-11-19

[221 rows x 7 columns]
       Symbol     open     high      low    close     volume start_Time
0    TEJASNET   875.00   887.95   870.25   872.85   344732.0 2024-01-01
1    TEJASNET   878.00   878.40   853.60   861.90   232960.0 2024-01-02
2    TEJASNET   860.00   861.90   847.00   852.80   149854.0 2024-01-03
3    TEJASNET   858.00   864.50   844.00   857.55   216393.0 2024-01-04
4    TEJASNET   864.30   871.10   856.70   865.65   163698.0 2024-01-05
..        ...      ...      ...      ...      ...        ...        ...
216  TEJASNET  1355.00  1373.00  1292.05  1299.15  1352541.0 2024-11-12
217  TEJASNET  1289.00  1295.40  1235.00  1241.10  1394880.0 2024-11-13
218  TEJASNET  1250.00  1284.90  1236.95  1267.75  1074989.0 2024-11-14
219  TEJASNET  1273.95  1300.00  1235.05  1281.55   954541.0 2024-11-18
220  TEJASNET  1290.00  1335.95  1270.10  1285.25  1145402.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

     Symbol    open    high     low   close    volume start_Time
0    AETHER  888.80  893.00  878.35  882.45  115407.0 2024-01-01
1    AETHER  884.00  887.40  871.50  884.30   99105.0 2024-01-02
2    AETHER  891.00  916.80  880.90  902.25  239281.0 2024-01-03
3    AETHER  910.00  911.00  897.55  902.00   93108.0 2024-01-04
4    AETHER  904.95  910.00  893.60  904.15  162236.0 2024-01-05
..      ...     ...     ...     ...     ...       ...        ...
216  AETHER  831.30  837.90  821.50  832.75   22376.0 2024-11-12
217  AETHER  826.15  830.00  800.95  823.50   44909.0 2024-11-13
218  AETHER  825.95  833.65  809.50  817.10   17225.0 2024-11-14
219  AETHER  815.00  818.95  800.00  814.20   17035.0 2024-11-18
220  AETHER  829.00  836.25  821.25  828.00   14697.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open     high      low    close    volume start_Time
0     ERIS   914.55   916.90   902.00   905.80   35045.0 2024-01-01
1     ERIS   910.85   933.00   904.30   931.35  256552.0 2024-01-02
2     ERIS   931.95   938.10   904.95   913.65  201640.0 2024-01-03
3     ERIS   910.00   930.00   910.00   927.70   72322.0 2024-01-04
4     ERIS   927.00   936.45   922.55   933.00  118781.0 2024-01-05
..     ...      ...      ...      ...      ...       ...        ...
216   ERIS  1326.70  1397.00  1326.65  1369.45  280997.0 2024-11-12
217   ERIS  1374.25  1396.50  1309.55  1329.15  115612.0 2024-11-13
218   ERIS  1329.15  1368.35  1317.65  1352.75   49146.0 2024-11-14
219   ERIS  1350.00  1362.90  1326.60  1353.35   32907.0 2024-11-18
220   ERIS  1341.05  1435.55  1341.05  1368.45  215614.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol     open     high      low    close     volume start_Time
0    HAVELLS  1367.95  1377.00  1356.00  1362.20   240757.0 2024-01-01
1    HAVELLS  1365.45  1383.90  1346.10  1380.10   732232.0 2024-01-02
2    HAVELLS  1385.00  1421.35  1381.30  1397.70  1332808.0 2024-01-03
3    HAVELLS  1404.00  1412.35  1386.80  1399.95   668322.0 2024-01-04
4    HAVELLS  1400.00  1416.00  1396.40  1405.50   488819.0 2024-01-05
..       ...      ...      ...      ...      ...        ...        ...
216  HAVELLS  1643.95  1655.45  1599.35  1603.40   538309.0 2024-11-12
217  HAVELLS  1600.00  1622.00  1586.75  1614.10   723526.0 2024-11-13
218  HAVELLS  1615.00  1637.25  1597.55  1618.85   717761.0 2024-11-14
219  HAVELLS  1619.00  1634.30  1601.70  1619.05   458137.0 2024-11-18
220  HAVELLS  1622.95  1663.95  1618.40  1632.70   575229.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open     high      low    close     volume start_Time
0     CDSL   912.50   919.38   906.00   909.18   454570.0 2024-01-01
1     CDSL   909.18   924.15   904.00   909.55   556956.0 2024-01-02
2     CDSL   909.55   924.00   909.55   921.58   635356.0 2024-01-03
3     CDSL   926.00   954.38   920.00   942.53  1259885.0 2024-01-04
4     CDSL   947.10   952.30   936.93   944.33   668531.0 2024-01-05
..     ...      ...      ...      ...      ...        ...        ...
216   CDSL  1560.00  1583.95  1516.00  1521.90  2901567.0 2024-11-12
217   CDSL  1521.00  1524.40  1427.00  1435.25  4363184.0 2024-11-13
218   CDSL  1445.00  1497.25  1444.00  1472.75  3977598.0 2024-11-14
219   CDSL  1480.00  1515.00  1451.45  1504.65  3341820.0 2024-11-18
220   CDSL  1514.00  1538.25  1494.00  1506.35  2601301.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol     open     high      low    close    volume start_Time
0      UBL  1793.20  1807.95  1772.10  1792.70  364690.0 2024-01-01
1      UBL  1791.30  1822.65  1785.00  1812.60  286287.0 2024-01-02
2      UBL  1815.00  1841.65  1803.60  1824.95  289694.0 2024-01-03
3      UBL  1829.30  1898.10  1829.25  1892.40  490520.0 2024-01-04
4      UBL  1906.20  1906.65  1877.40  1888.25  324201.0 2024-01-05
..     ...      ...      ...      ...      ...       ...        ...
216    UBL  1905.80  1924.00  1873.00  1882.45  285470.0 2024-11-12
217    UBL  1881.00  1888.95  1850.10  1856.40   67083.0 2024-11-13
218    UBL  1855.00  1890.55  1852.15  1883.55  294046.0 2024-11-14
219    UBL  1871.00  1887.95  1835.05  1883.60  125003.0 2024-11-18
220    UBL  1870.65  1898.45  1843.60  1853.80  192913.0 2024-11-19

[221 rows x 7 columns]
     Symbol    open    high     low   close     volume start_Time
0    AUBANK  790.90  790.90  779.00  786.00  1258532.0 2024-01-01
1    AUBANK  786.00  788.00  761.60  766.85  2202630.0 2024-01-02
2    AUBANK  766.85  774.15  754.00  770.35  2031856.0 2024-01-03
3    AUBANK  778.00  804.15  745.05  797.35  2624482.0 2024-01-04
4    AUBANK  805.00  809.70  791.55  801.05  2341793.0 2024-01-05
..      ...     ...     ...     ...     ...        ...        ...
216  AUBANK  577.05  582.00  573.05  579.25  1281942.0 2024-11-12
217  AUBANK  576.65  578.95  557.25  560.80  4788121.0 2024-11-13
218  AUBANK  562.50  575.40  562.50  573.90  1722187.0 2024-11-14
219  AUBANK  574.00  583.15  570.25  579.00  2176589.0 2024-11-18
220  AUBANK  575.05  597.10  575.05  591.00  3260155.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

        Symbol      open      high       low     close   volume start_Time
0    ZFCVINDIA  15860.10  16338.85  15800.00  16307.05   7327.0 2024-01-01
1    ZFCVINDIA  16385.00  16452.00  16023.05  16247.10  19764.0 2024-01-02
2    ZFCVINDIA  16247.10  16350.00  15906.40  15952.10  35063.0 2024-01-03
3    ZFCVINDIA  15952.10  16086.00  15600.00  15877.50  10302.0 2024-01-04
4    ZFCVINDIA  15995.00  16320.00  15902.60  16171.50   4336.0 2024-01-05
..         ...       ...       ...       ...       ...      ...        ...
216  ZFCVINDIA  14886.50  15290.00  14600.10  14919.85   9561.0 2024-11-12
217  ZFCVINDIA  14745.00  15089.95  14601.00  14788.80   6729.0 2024-11-13
218  ZFCVINDIA  14788.80  14985.50  14497.70  14669.35  10179.0 2024-11-14
219  ZFCVINDIA  14410.00  15043.05  14410.00  14568.65   8904.0 2024-11-18
220  ZFCVINDIA  14568.65  15010.95  14427.35  14855.25   9749.0 2024-11-19

[221 rows x 7 columns]
        Symbol    open    high     low   close      volume start_Time
0    ABCAPITAL  169.00  169.00  165.50  166.05   4244834.0 2024-01-01
1    ABCAPITAL  166.80  171.60  164.40  170.60  12968451.0 2024-01-02
2    ABCAPITAL  171.30  172.35  169.25  170.40   6963477.0 2024-01-03
3    ABCAPITAL  171.70  174.60  170.60  174.10   7927230.0 2024-01-04
4    ABCAPITAL  175.00  179.20  173.00  175.10  14396150.0 2024-01-05
..         ...     ...     ...     ...     ...         ...        ...
216  ABCAPITAL  199.95  201.39  194.01  194.77   3700550.0 2024-11-12
217  ABCAPITAL  193.00  194.20  186.72  187.61   6642649.0 2024-11-13
218  ABCAPITAL  187.50  190.80  187.01  188.92   2597625.0 2024-11-14
219  ABCAPITAL  189.03  190.40  184.53  185.03   6572741.0 2024-11-18
220  ABCAPITAL  186.48  189.10  183.25  184.76   8140821.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol      open      high       low     close    volume start_Time
0    DIXON   6560.00   6585.80   6420.50   6460.35  268871.0 2024-01-01
1    DIXON   6465.50   6483.40   6243.15   6316.50  604541.0 2024-01-02
2    DIXON   6316.60   6411.00   6269.00   6350.70  241046.0 2024-01-03
3    DIXON   6379.00   6447.45   6365.65   6396.55  244040.0 2024-01-04
4    DIXON   6396.55   6459.00   6364.30   6378.40  246494.0 2024-01-05
..     ...       ...       ...       ...       ...       ...        ...
216  DIXON  15451.90  15660.95  14960.00  15008.15  478330.0 2024-11-12
217  DIXON  14990.00  15050.00  14540.00  14719.95  518378.0 2024-11-13
218  DIXON  14725.10  15088.50  14674.95  14776.10  446922.0 2024-11-14
219  DIXON  14950.00  15020.95  14740.05  14811.45  372272.0 2024-11-18
220  DIXON  14850.95  15382.00  14762.15  14876.40  516403.0 2024-11-19

[221 rows x 7 columns]
         Symbol     open     high      low    close    volume start_Time
0    CHOLAHLDNG  1030.00  1038.00   998.25  1019.65  448796.0 2024-01-01
1    CHOLAHLDNG  1019.00  1019.00  1002.50  1006.20  137045.0 2024-01-02
2    CHOLAHLDNG  1014.30  1016.05  1002.05  1012.65  100086.0 2024-01-03
3    CHOLAHLDNG  1019.00  1056.45  1009.40  1042.65  533581.0 2024-01-04
4    CHOLAHLDNG  1050.00  1054.60  1030.00  1040.05  103112.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  CHOLAHLDNG  1612.00  1660.95  1601.35  1626.60   84026.0 2024-11-12
217  CHOLAHLDNG  1625.00  1625.00  1545.00  1555.30  107338.0 2024-11-13
218  CHOLAHLDNG  1563.40  1592.90  1547.00  1573.80  134863.0 2024-11-14
219  CHOLAHLDNG  1573.80  1576.85  1487.10  1515.95  152286.0 2024-11-18
220  CHOLAHLDNG  1514.65  1604.05  1505.25  1549.85  244130.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol     open     high      low    close     volume start_Time
0    ICICIGI  1429.00  1443.40  1420.00  1437.20   156358.0 2024-01-01
1    ICICIGI  1443.00  1448.95  1415.55  1419.40   491395.0 2024-01-02
2    ICICIGI  1417.05  1419.40  1373.70  1378.00   701759.0 2024-01-03
3    ICICIGI  1380.05  1398.00  1375.00  1393.20   581309.0 2024-01-04
4    ICICIGI  1394.80  1398.55  1385.40  1395.60   296418.0 2024-01-05
..       ...      ...      ...      ...      ...        ...        ...
216  ICICIGI  1931.20  1933.10  1875.00  1892.25   859956.0 2024-11-12
217  ICICIGI  1876.00  1892.50  1864.00  1868.20   257151.0 2024-11-13
218  ICICIGI  1850.05  1894.35  1849.85  1863.40   308495.0 2024-11-14
219  ICICIGI  1870.05  1873.20  1834.55  1839.45   631045.0 2024-11-18
220  ICICIGI  1843.90  1848.90  1789.05  1840.90  1196590.0 2024-11-19

[221 rows x 7 columns]
      Symbol     open     high      low    close     volume start_Time
0    SBILIFE  1435.85  1437.60  1425.95  1432.10   158288.0 2024-01-01
1    SBILIFE  1437.00  1449.70  1421.75  1437.65   691712.0 2024-01-02
2    SBILIFE  1430.00  1440.90  1415.60  1422.70   550221.0 2024-01-03
3    SBILIFE  1420.80  1436.60  1415.00  1431.60   938454.0 2024-01-04
4    SBILIFE  1435.90  1468.00  1433.70  1454.15  1258280.0 2024-01-05
..       ...      ...      ...      ...      ...        ...        ...
216  SBILIFE  1569.10  1585.95  1557.00  1562.45  1177157.0 2024-11-12
217  SBILIFE  1560.00  1572.00  1540.00  1546.70  2946117.0 2024-11-13
218  SBILIFE  1546.20  1568.95  1546.05  1562.30   684365.0 2024-11-14
219  SBILIFE  1551.00  1566.55  1551.00  1562.60   490930.0 2024-11-18
220  SBILIFE  1568.00  1568.05  1501.00  1522.90  4198931.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close       volume start_Time
0     HFCL   85.90   88.70   84.10   84.55   39295978.0 2024-01-01
1     HFCL   85.00   86.25   82.55   85.20   27995040.0 2024-01-02
2     HFCL   85.00   90.40   83.55   88.05   37469600.0 2024-01-03
3     HFCL   88.90   94.65   88.00   91.25  114078436.0 2024-01-04
4     HFCL   91.85   92.95   89.40   91.95   36278438.0 2024-01-05
..     ...     ...     ...     ...     ...          ...        ...
216   HFCL  129.50  132.88  125.10  126.21   24478044.0 2024-11-12
217   HFCL  125.50  127.47  120.02  120.70   16794140.0 2024-11-13
218   HFCL  121.65  128.30  121.43  126.89   29193373.0 2024-11-14
219   HFCL  128.70  129.90  125.43  127.74   16152272.0 2024-11-18
220   HFCL  128.00  132.40  127.80  129.24   17406221.0 2024-11-19

[221 rows x 7 columns]
        Symbol     open     high      low    close     volume start_Time
0    PATANJALI  1574.00  1591.00  1555.25  1567.45   345140.0 2024-01-01
1    PATANJALI  1567.45  1575.55  1535.00  1563.40   300649.0 2024-01-02
2    PATANJALI  1563.40  1613.00  1552.00  1594.55  1189639.0 2024-01-03
3    PATANJALI  1625.00  1628.00  1592.05  1601.80   836148.0 2024-01-04
4    PATANJALI  1614.95  1614.95  1575.55  1587.30   376345.0 2024-01-05
..         ...      ...      ...      ...      ...        ...        ...
216  PATANJALI  1860.00  1875.55  1831.00  1861.40   273053.0 2024-11-12
217  PATANJALI  1841.10  1863.50  1836.50  1843.00   487973.0 2024-11-13
218  PATANJALI  1838.00  1853.90  1828.00  1843.80   299529.0 2024-11-14
219  PATANJALI  1840.00  1858.95  1825.55  1854.55   271805.0 2024-11-18
220  PATANJALI  1843.05  1865.00  1830.00  1852.60   742174.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol    open    high     low   close      volume start_Time
0    CROMPTON  313.50  317.35  309.60  313.85   2198792.0 2024-01-01
1    CROMPTON  315.80  316.00  306.35  311.40   2295282.0 2024-01-02
2    CROMPTON  312.90  320.75  308.80  318.75   3789724.0 2024-01-03
3    CROMPTON  320.85  323.00  316.35  317.60   2367626.0 2024-01-04
4    CROMPTON  318.90  321.00  314.70  316.45   1649336.0 2024-01-05
..        ...     ...     ...     ...     ...         ...        ...
216  CROMPTON  393.80  400.15  388.25  390.40   4078155.0 2024-11-12
217  CROMPTON  386.25  390.05  382.85  385.00   1375437.0 2024-11-13
218  CROMPTON  384.95  386.50  369.80  371.05   2024594.0 2024-11-14
219  CROMPTON  379.00  397.55  374.35  384.25  10179369.0 2024-11-18
220  CROMPTON  382.00  395.00  378.00  390.70   3577680.0 2024-11-19

[221 rows x 7 columns]
       Symbol    open    high     low   close     volume start_Time
0    SUMICHEM  405.40  411.40  404.20  410.15   507213.0 2024-01-01
1    SUMICHEM  412.50  424.95  411.30  414.35   909272.0 2024-01-02
2    SUMICHEM  415.75  418.90  403.05  405.70   828260.0 2024-01-03
3    SUMICHEM  410.00  413.90  403.30  405.80   726829.0 2024-01-04
4    SUMICHEM  411.90  418.50  407.05  417.40  1413057.0 2024-01-05
..        ...     ...     ...     ...     ...        ...        ...
216  SUMICHEM  536.40  546.65  527.05  528.55   346257.0 2024-11-12
217  SUMICHEM  525.95  527.70  508.15  510.75   264341.0 2024-11-13
218  SUMICHEM  503.00  530.00  503.00  520.90   380765.0 2024-11-14
219  SUMICHEM  527.40  528.40  510.55  516.30   275414.0 2024-11-18
220  SUMICHEM  516.95  529.80  515.00  518.30   344037.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close     volume start_Time
0      BLS  319.90  328.20  318.60  326.50  4374515.0 2024-01-01
1      BLS  327.45  328.00  316.05  321.80  2217555.0 2024-01-02
2      BLS  321.65  328.40  319.45  326.80  2437211.0 2024-01-03
3      BLS  328.90  341.85  328.60  337.90  5986086.0 2024-01-04
4      BLS  338.80  340.60  332.25  336.25  1643799.0 2024-01-05
..     ...     ...     ...     ...     ...        ...        ...
216    BLS  435.00  436.00  395.10  398.05  4902628.0 2024-11-12
217    BLS  395.00  403.25  380.55  384.10  3068764.0 2024-11-13
218    BLS  385.70  396.75  384.20  389.25  1349003.0 2024-11-14
219    BLS  390.00  390.65  378.55  387.45  1011785.0 2024-11-18
220    BLS  389.95  398.75  384.00  385.60  1198226.0 2024-11-19

[221 rows x 7 columns]
       Symbol    open     high     low   close    volume start_Time
0    LLOYDSME  601.45   610.10  596.55  603.80  150418.0 2024-01-01
1    LLOYDSME  608.75   617.95  592.20  602.80  383222.0 2024-01-02
2    LLOYDSME  602.00   608.15  595.55  600.80  111882.0 2024-01-03
3    LLOYDSME  604.90   608.35  573.00  588.35  156485.0 2024-01-04
4    LLOYDSME  595.00   604.80  586.10  589.90  329399.0 2024-01-05
..        ...     ...      ...     ...     ...       ...        ...
216  LLOYDSME  994.50  1014.00  987.00  992.35  205502.0 2024-11-12
217  LLOYDSME  982.05   997.55  932.35  942.05  301208.0 2024-11-13
218  LLOYDSME  942.00   961.95  920.00  924.25  317144.0 2024-11-14
219  LLOYDSME  924.25   938.00  915.00  924.20  209992.0 2024-11-18
220  LLOYDSME  922.00   955.30  920.05  948.70  230497.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close    volume start_Time
0    MHRIL  380.25  388.85  379.50  386.50  164633.0 2024-01-01
1    MHRIL  388.55  391.95  379.95  390.10  192834.0 2024-01-02
2    MHRIL  390.90  397.00  387.65  390.70  284589.0 2024-01-03
3    MHRIL  392.10  395.25  388.50  392.20  157053.0 2024-01-04
4    MHRIL  393.90  394.10  385.00  387.95  126237.0 2024-01-05
..     ...     ...     ...     ...     ...       ...        ...
216  MHRIL  369.05  371.00  358.05  359.65   71937.0 2024-11-12
217  MHRIL  359.60  360.70  351.20  355.20  110159.0 2024-11-13
218  MHRIL  355.00  361.15  353.00  355.60   94864.0 2024-11-14
219  MHRIL  352.60  358.45  349.20  354.20   74325.0 2024-11-18
220  MHRIL  355.45  363.45  354.85  356.60   89919.0 2024-11-19

[221 rows x 7 columns]
         Symbol    open    high    low   close      volume start_Time
0    ADANIPOWER  525.15  533.95  519.1  523.25   1123066.0 2024-01-01
1    ADANIPOWER  525.00  525.00  515.0  518.60   1011777.0 2024-01-02
2    ADANIPOWER  538.00  544.50  525.0  544.50   4044997.0 2024-01-03
3    ADANIPOWER  548.00  561.45  537.3  558.55   3611727.0 2024-01-04
4    ADANIPOWER  564.70  565.00  546.1  551.10   1411436.0 2024-01-05
..          ...     ...     ...    ...     ...         ...        ...
216  ADANIPOWER  579.80  587.10  555.0  557.95   2438708.0 2024-11-12
217  ADANIPOWER  560.00  598.00  541.3  547.00  12401974.0 2024-11-13
218  ADANIPOWER  559.95  567.10  547.0  549.10   3095845.0 2024-11-14
219  ADANIPOWER  555.95  557.40  525.1  526.85   3664843.0 2024-11-18
220  ADANIPOWER  532.00  537.60  521.6  524.10   4024003.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol   open   high    low  close       volume start_Time
0     NHPC  64.95  67.45  64.75  66.15   33495776.0 2024-01-01
1     NHPC  66.25  68.75  64.65  68.00   41210903.0 2024-01-02
2     NHPC  68.20  68.45  67.00  67.35   19256891.0 2024-01-03
3     NHPC  68.00  69.80  67.55  69.05   56887404.0 2024-01-04
4     NHPC  70.00  75.30  70.00  71.95  116761947.0 2024-01-05
..     ...    ...    ...    ...    ...          ...        ...
216   NHPC  81.70  82.04  80.50  80.79   10807995.0 2024-11-12
217   NHPC  80.79  80.79  77.74  77.94   23048732.0 2024-11-13
218   NHPC  77.95  78.74  77.26  78.38   16163462.0 2024-11-14
219   NHPC  78.63  78.95  76.41  78.16   16506105.0 2024-11-18
220   NHPC  78.30  80.48  78.25  80.01   16065815.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close     volume start_Time
0      OIL  249.00  255.07  247.57  252.50  2440997.0 2024-01-01
1      OIL  250.67  259.33  249.50  255.53  4465413.0 2024-01-02
2      OIL  255.73  261.23  251.53  257.13  3137954.0 2024-01-03
3      OIL  259.60  259.60  254.33  255.17  1885391.0 2024-01-04
4      OIL  256.60  257.70  251.17  253.60  2139325.0 2024-01-05
..     ...     ...     ...     ...     ...        ...        ...
216    OIL  506.50  511.85  492.70  496.65  1152726.0 2024-11-12
217    OIL  494.40  501.40  475.00  480.85  2249137.0 2024-11-13
218    OIL  476.00  482.60  464.35  475.45  2114574.0 2024-11-14
219    OIL  475.45  481.85  464.00  472.45   999530.0 2024-11-18
220    OIL  477.30  491.45  477.00  485.45  1270704.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol     open     high      low    close     volume start_Time
0      MGL  1201.00  1224.75  1194.30  1203.65   301407.0 2024-01-01
1      MGL  1210.00  1233.50  1187.95  1215.90   489638.0 2024-01-02
2      MGL  1219.75  1227.00  1200.25  1222.00   315833.0 2024-01-03
3      MGL  1227.00  1241.00  1223.00  1228.30   342832.0 2024-01-04
4      MGL  1228.60  1252.00  1227.00  1238.10   420644.0 2024-01-05
..     ...      ...      ...      ...      ...        ...        ...
216    MGL  1403.00  1416.40  1366.00  1370.20   281833.0 2024-11-12
217    MGL  1370.00  1372.25  1323.35  1329.65   371002.0 2024-11-13
218    MGL  1325.55  1340.00  1306.50  1312.65   383814.0 2024-11-14
219    MGL  1221.00  1221.00  1075.25  1130.00  4854898.0 2024-11-18
220    MGL  1112.60  1145.80  1112.00  1126.05  1700881.0 2024-11-19

[221 rows x 7 columns]
      Symbol    open    high     low   close     volume start_Time
0    SUNTECK  447.00  449.00  442.75  447.85   375299.0 2024-01-01
1    SUNTECK  449.30  450.10  433.50  434.90   756943.0 2024-01-02
2    SUNTECK  434.95  440.50  430.60  437.00   554648.0 2024-01-03
3    SUNTECK  442.00  473.70  437.60  471.15  5679077.0 2024-01-04
4    SUNTECK  473.90  474.90  453.55  458.20  1079168.0 2024-01-05
..       ...     ...     ...     ...     ...        ...        ...
216  SUNTECK  534.40  543.15  500.00  513.75   138101.0 2024-11-12
217  SUNTECK  515.00  527.50  486.00  490.00   372971.0 2024-11-13
218  SUNTECK  502.00  517.90  488.20  493.10   403966.0 2024-11-14
219  SUNTECK  501.90  516.00  492.60  511.50   412784.0 2024-11-18
220  SUNTECK  516.05  520.95  507.80  510.10   233699.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol   open   high    low  close       volume start_Time
0    ALOKINDS  21.40  21.85  21.40  21.50   10352267.0 2024-01-01
1    ALOKINDS  21.65  25.80  21.00  25.80   93697408.0 2024-01-02
2    ALOKINDS  27.45  29.10  27.00  27.65  215644507.0 2024-01-03
3    ALOKINDS  28.20  28.25  26.80  27.15   62997398.0 2024-01-04
4    ALOKINDS  27.50  32.55  27.40  32.30  344757127.0 2024-01-05
..        ...    ...    ...    ...    ...          ...        ...
216  ALOKINDS  21.35  21.58  21.00  21.08    3866472.0 2024-11-12
217  ALOKINDS  21.15  21.15  20.16  20.25    7303746.0 2024-11-13
218  ALOKINDS  20.25  21.04  20.11  20.63    8179654.0 2024-11-14
219  ALOKINDS  21.08  21.49  20.47  20.61    7565495.0 2024-11-18
220  ALOKINDS  20.68  21.11  20.50  20.60    5305548.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close    volume start_Time
0    QUESS  523.00  529.00  512.20  518.35  288707.0 2024-01-01
1    QUESS  516.90  522.90  504.35  506.85  693766.0 2024-01-02
2    QUESS  510.50  517.50  502.55  513.35  305871.0 2024-01-03
3    QUESS  517.00  519.45  511.25  512.85  195298.0 2024-01-04
4    QUESS  512.80  515.40  501.00  505.85  240476.0 2024-01-05
..     ...     ...     ...     ...     ...       ...        ...
216  QUESS  697.10  703.45  672.35  674.55  152484.0 2024-11-12
217  QUESS  675.00  677.95  631.95  635.95  508303.0 2024-11-13
218  QUESS  642.90  648.70  633.20  637.15  243307.0 2024-11-14
219  QUESS  638.65  656.60  622.20  645.15  335340.0 2024-11-18
220  QUESS  645.05  663.95  639.55  655.95  135248.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol     open     high      low    close    volume start_Time
0     LTIM  6308.80  6318.75  6240.00  6261.90  166927.0 2024-01-01
1     LTIM  6230.00  6284.00  6123.45  6144.00  475149.0 2024-01-02
2     LTIM  6110.00  6113.25  5955.00  5961.05  421251.0 2024-01-03
3     LTIM  5963.00  6020.00  5851.70  5866.40  618173.0 2024-01-04
4     LTIM  5945.00  6010.00  5902.00  5947.65  429330.0 2024-01-05
..     ...      ...      ...      ...      ...       ...        ...
216   LTIM  6007.00  6037.00  5964.80  6005.05  289914.0 2024-11-12
217   LTIM  6005.05  6009.70  5914.15  5947.55  181293.0 2024-11-13
218   LTIM  5947.05  6011.00  5920.05  5994.65  143974.0 2024-11-14
219   LTIM  5955.00  5984.95  5711.50  5841.50  276072.0 2024-11-18
220   LTIM  5841.50  5965.00  5832.50  5885.95  218021.0 2024-11-19

[221 rows x 7 columns]
        Symbol    open    high     low   close     volume start_Time
0    JSWENERGY  412.90  413.60  408.85  410.05  1840554.0 2024-01-01
1    JSWENERGY  410.05  414.00  404.15  408.95  1835815.0 2024-01-02
2    JSWENERGY  409.55  422.80  407.80  411.25  3138198.0 2024-01-03
3    JSWENERGY  413.35  428.05  411.05  426.30  4618595.0 2024-01-04
4    JSWENERGY  428.50  431.50  416.40  419.95  3640549.0 2024-01-05
..         ...     ...     ...     ...     ...        ...        ...
216  JSWENERGY  739.95  776.90  739.30  750.05  5503743.0 2024-11-12
217  JSWENERGY  749.95  774.90  722.10  728.95  5348473.0 2024-11-13
218  JSWENERGY  734.90  748.95  718.75  732.00  2339209.0 2024-11-14
219  JSWENERGY  736.00  746.25  707.50  712.80  2123986.0 2024-11-18
220  JSWENERGY  718.00  718.70  706.00  709.90  1355756.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close     volume start_Time
0    GODREJPROP  2015.00  2022.00  1995.00  2002.05   208868.0 2024-01-01
1    GODREJPROP  2007.95  2028.00  1982.50  2016.00   402722.0 2024-01-02
2    GODREJPROP  2016.00  2060.00  2007.15  2052.35   639760.0 2024-01-03
3    GODREJPROP  2063.95  2236.80  2055.00  2216.15  3733260.0 2024-01-04
4    GODREJPROP  2210.00  2252.90  2200.00  2244.30   868364.0 2024-01-05
..          ...      ...      ...      ...      ...        ...        ...
216  GODREJPROP  2680.95  2718.00  2628.45  2645.10   542863.0 2024-11-12
217  GODREJPROP  2625.00  2660.00  2555.00  2569.15   631321.0 2024-11-13
218  GODREJPROP  2573.60  2621.75  2552.95  2595.30   564858.0 2024-11-14
219  GODREJPROP  2598.40  2647.30  2594.30  2629.50   357071.0 2024-11-18
220  GODREJPROP  2620.00  2743.80  2620.00  2692.75   514975.0 2024-11-19

[221 rows x 7 columns]
        Symbol     open     high      low    close     volume start_Time
0    MAXHEALTH   689.00   694.65   684.25   688.45   222961.0 2024-01-01
1    MAXHEALTH   688.45   694.00   672.55   677.85   637956.0 2024-01-02
2    MAXHEALTH   678.25   692.85   669.45   690.90   823250.0 2024-01-03
3    MAXHEALTH   696.90   745.95   692.05   737.75  2104329.0 2024-01-04
4    MAXHEALTH   735.00   735.00   709.20   714.75  1790608.0 2024-01-05
..         ...      ...      ...      ...      ...        ...        ...
216  MAXHEALTH  1030.00  1064.80  1029.05  1030.70  2388597.0 2024-11-12
217  MAXHEALTH  1014.20  1036.30   992.90  1001.90  2268100.0 2024-11-13
218  MAXHEALTH  1010.40  1025.40   996.30  1006.25  1048104.0 2024-11-14
219  MAXHEALTH  1055.10  1058.85   987.05   999.85  2909039.0 2024-11-18
220  MAXHEALTH  1009.00  1009.00   994.10   997.80   742789.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open      high       low     close   volume start_Time
0    ABBOTINDIA  22852.0  22903.90  22720.00  22761.10  24341.0 2024-01-01
1    ABBOTINDIA  22780.0  23456.00  22761.10  23327.25  55844.0 2024-01-02
2    ABBOTINDIA  23450.0  23650.00  23220.20  23606.60  19924.0 2024-01-03
3    ABBOTINDIA  23675.0  23675.00  23143.55  23569.80  34327.0 2024-01-04
4    ABBOTINDIA  23569.8  24000.00  23485.20  23884.60  22754.0 2024-01-05
..          ...      ...       ...       ...       ...      ...        ...
216  ABBOTINDIA  28799.0  29119.00  28501.00  28597.85   5663.0 2024-11-12
217  ABBOTINDIA  28505.0  28593.50  27550.00  27629.80   7236.0 2024-11-13
218  ABBOTINDIA  27750.0  27903.95  27200.05  27351.20   7905.0 2024-11-14
219  ABBOTINDIA  27445.1  27475.00  27051.00  27187.40   4672.0 2024-11-18
220  ABBOTINDIA  27337.7  27506.85  27111.00  27224.35  10942.0 2024-11-19

[221 rows x 7 columns]
        Symbol     open     high      low    close   volume start_Time
0    BAYERCROP  5624.00  5624.95  5451.00  5500.45  39511.0 2024-01-01
1    BAYERCROP  5520.00  5582.80  5461.05  5483.60  22552.0 2024-01-02
2    BAYERCROP  5510.95  5549.90  5470.65  5513.80  65403.0 2024-01-03
3    BAYERCROP  5513.00  5575.00  5464.00  5490.75  70705.0 2024-01-04
4    BAYERCROP  5490.00  5600.00  5490.00  5592.25  21551.0 2024-01-05
..         ...      ...      ...      ...      ...      ...        ...
216  BAYERCROP  6371.00  6449.00  6295.00  6315.35  10135.0 2024-11-12
217  BAYERCROP  6282.00  6348.60  6050.05  6078.80  17352.0 2024-11-13
218  BAYERCROP  5975.00  6150.00  5875.10  5892.85  39894.0 2024-11-14
219  BAYERCROP  5800.05  5913.00  5635.00  5686.70  53453.0 2024-11-18
220  BAYERCROP  5655.00  5795.80  5643.45  5665.90  23896.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol    open    high     low   close      volume start_Time
0    HINDCOPPER  275.80  278.40  266.10  271.50  15856420.0 2024-01-01
1    HINDCOPPER  273.00  275.50  265.45  269.70  11463429.0 2024-01-02
2    HINDCOPPER  269.70  269.90  263.20  265.55   7874797.0 2024-01-03
3    HINDCOPPER  267.55  283.75  266.25  278.05  28522450.0 2024-01-04
4    HINDCOPPER  280.70  286.70  276.60  283.30  22647293.0 2024-01-05
..          ...     ...     ...     ...     ...         ...        ...
216  HINDCOPPER  277.95  279.45  266.75  269.45   4751726.0 2024-11-12
217  HINDCOPPER  267.00  269.75  260.00  261.70   4699363.0 2024-11-13
218  HINDCOPPER  260.00  265.45  259.90  262.70   2669822.0 2024-11-14
219  HINDCOPPER  262.10  267.45  259.55  264.40   4274822.0 2024-11-18
220  HINDCOPPER  265.25  271.05  261.10  263.20   3174138.0 2024-11-19

[221 rows x 7 columns]
        Symbol     open     high      low    close    volume start_Time
0    SUVENPHAR   728.00   740.00   712.00   720.35  207098.0 2024-01-01
1    SUVENPHAR   722.00   731.60   712.45   727.55  424799.0 2024-01-02
2    SUVENPHAR   730.00   750.00   723.05   738.75  389437.0 2024-01-03
3    SUVENPHAR   740.05   768.00   740.05   750.90  277193.0 2024-01-04
4    SUVENPHAR   754.90   760.95   737.20   743.90  120106.0 2024-01-05
..         ...      ...      ...      ...      ...       ...        ...
216  SUVENPHAR  1257.20  1274.00  1198.25  1204.55  117654.0 2024-11-12
217  SUVENPHAR  1220.00  1275.00  1209.60  1262.30  482529.0 2024-11-13
218  SUVENPHAR  1250.95  1289.95  1237.05  1274.70  317361.0 2024-11-14
219  SUVENPHAR  1274.70  1301.10  1258.55  1281.00  187898.0 2024-11-18
220  SUVENPHAR  1275.00  1300.00  1269.10  1279.55  125751.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol   open   high    low  close      volume start_Time
0     MMTC  60.55  61.50  60.00  60.20   3479993.0 2024-01-01
1     MMTC  60.55  60.75  58.80  60.00   3189108.0 2024-01-02
2     MMTC  60.00  60.60  59.35  59.60   2074733.0 2024-01-03
3     MMTC  59.80  65.45  59.70  64.70  29130370.0 2024-01-04
4     MMTC  65.60  66.70  62.70  63.70  12013445.0 2024-01-05
..     ...    ...    ...    ...    ...         ...        ...
216   MMTC  78.67  85.44  77.79  79.42  20548489.0 2024-11-12
217   MMTC  79.17  79.38  74.79  75.44   3450330.0 2024-11-13
218   MMTC  75.99  77.04  74.77  75.35   2302889.0 2024-11-14
219   MMTC  76.70  76.70  73.81  75.54   2450103.0 2024-11-18
220   MMTC  76.70  77.87  74.61  75.27   1957858.0 2024-11-19

[221 rows x 7 columns]
        Symbol     open     high      low    close     volume start_Time
0    NESTLEIND  2665.00  2744.53  2664.00  2737.24   131610.0 2024-01-01
1    NESTLEIND  2750.00  2769.30  2702.41  2722.32   141577.0 2024-01-02
2    NESTLEIND  2734.50  2741.73  2657.30  2663.52   101346.0 2024-01-03
3    NESTLEIND  2685.11  2715.01  2665.21  2711.64   132390.0 2024-01-04
4    NESTLEIND  2754.00  2754.00  2642.45  2666.40  2577064.0 2024-01-05
..         ...      ...      ...      ...      ...        ...        ...
216  NESTLEIND  2290.45  2290.45  2241.00  2256.20  1105339.0 2024-11-12
217  NESTLEIND  2241.25  2251.95  2222.00  2235.25   763388.0 2024-11-13
218  NESTLEIND  2239.05  2244.95  2178.40  2182.80  1159238.0 2024-11-14
219  NESTLEIND  2190.70  2218.95  2168.70  2213.20   691665.0 2024-11-18
220  NESTLEIND  2225.00  2243.65  2203.90  2214.15   806020.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol    open    high     low   close     volume start_Time
0    SBICARD  764.00  771.75  761.25  766.35  1091156.0 2024-01-01
1    SBICARD  766.35  775.90  762.00  773.15  1493730.0 2024-01-02
2    SBICARD  775.65  780.95  768.15  769.85  1390145.0 2024-01-03
3    SBICARD  772.40  776.10  765.40  770.10  1580391.0 2024-01-04
4    SBICARD  772.50  779.95  768.00  771.60  1546574.0 2024-01-05
..       ...     ...     ...     ...     ...        ...        ...
216  SBICARD  694.00  697.20  677.00  679.25   786130.0 2024-11-12
217  SBICARD  679.25  693.00  673.25  680.30  1038299.0 2024-11-13
218  SBICARD  685.00  691.15  681.00  683.35   816979.0 2024-11-14
219  SBICARD  690.00  690.00  676.00  677.05   415550.0 2024-11-18
220  SBICARD  680.00  686.00  676.05  684.55   644318.0 2024-11-19

[221 rows x 7 columns]
        Symbol     open     high      low    close    volume start_Time
0    WHIRLPOOL  1369.00  1375.30  1360.25  1363.55   44624.0 2024-01-01
1    WHIRLPOOL  1363.55  1374.00  1350.00  1355.05   68670.0 2024-01-02
2    WHIRLPOOL  1359.45  1367.00  1355.90  1363.95   47454.0 2024-01-03
3    WHIRLPOOL  1364.50  1373.00  1351.95  1356.25   83477.0 2024-01-04
4    WHIRLPOOL  1359.90  1370.85  1353.70  1364.05  171282.0 2024-01-05
..         ...      ...      ...      ...      ...       ...        ...
216  WHIRLPOOL  1932.00  1933.90  1785.00  1794.50  223704.0 2024-11-12
217  WHIRLPOOL  1780.00  1804.85  1740.35  1779.55  210054.0 2024-11-13
218  WHIRLPOOL  1768.50  1857.00  1755.05  1802.95  168047.0 2024-11-14
219  WHIRLPOOL  1790.90  1845.20  1764.80  1830.05   99757.0 2024-11-18
220  WHIRLPOOL  1811.20  1861.25  1794.05  1836.55  189688.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol   open   high    low  close     volume start_Time
0     SBFC  90.40  90.40  88.75  89.00   837996.0 2024-01-01
1     SBFC  89.00  89.60  87.50  88.00  1133999.0 2024-01-02
2     SBFC  88.70  92.30  87.80  91.35  3048477.0 2024-01-03
3     SBFC  92.25  92.30  89.30  90.45  2322597.0 2024-01-04
4     SBFC  90.80  91.60  89.40  90.15  1327681.0 2024-01-05
..     ...    ...    ...    ...    ...        ...        ...
216   SBFC  84.01  85.24  83.11  83.62   835920.0 2024-11-12
217   SBFC  83.17  84.09  81.23  81.86  2048183.0 2024-11-13
218   SBFC  82.30  83.69  81.50  82.91  1025387.0 2024-11-14
219   SBFC  83.10  84.58  82.69  83.81  1491604.0 2024-11-18
220   SBFC  83.86  85.63  83.55  84.42  1537024.0 2024-11-19

[221 rows x 7 columns]
         Symbol     open     high      low    close    volume start_Time
0    CONCORDBIO  1471.95  1490.00  1449.95  1479.40   53612.0 2024-01-01
1    CONCORDBIO  1491.45  1525.00  1470.00  1512.80  125477.0 2024-01-02
2    CONCORDBIO  1519.60  1587.00  1480.30  1552.70  222460.0 2024-01-03
3    CONCORDBIO  1564.15  1577.50  1530.00  1547.75  123489.0 2024-01-04
4    CONCORDBIO  1550.00  1583.00  1543.10  1549.95  116061.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  CONCORDBIO  1912.00  1933.95  1858.05  1862.25   50673.0 2024-11-12
217  CONCORDBIO  1895.00  1908.45  1836.05  1853.75   95313.0 2024-11-13
218  CONCORDBIO  1835.50  1915.10  1834.00  1897.75   76738.0 2024-11-14
219  CONCORDBIO  1929.95  1933.75  1844.95  1915.00   62414.0 2024-11-18
220  CONCORDBIO  1915.00  1938.00  1872.05  1900.90   36596.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol    open    high     low   close      volume start_Time
0    JUBLFOOD  567.00  567.75  559.65  561.55   1135356.0 2024-01-01
1    JUBLFOOD  561.55  562.65  555.00  558.60   2611704.0 2024-01-02
2    JUBLFOOD  558.05  558.60  552.00  554.00   2337048.0 2024-01-03
3    JUBLFOOD  554.90  562.30  551.05  561.15   1534693.0 2024-01-04
4    JUBLFOOD  565.05  565.75  551.75  555.55   1383045.0 2024-01-05
..        ...     ...     ...     ...     ...         ...        ...
216  JUBLFOOD  626.35  655.95  614.40  636.85  18717555.0 2024-11-12
217  JUBLFOOD  635.05  641.65  615.20  625.20   2564649.0 2024-11-13
218  JUBLFOOD  630.00  630.00  606.45  608.15   2007047.0 2024-11-14
219  JUBLFOOD  615.00  617.10  603.65  607.15   1321339.0 2024-11-18
220  JUBLFOOD  607.15  622.45  604.55  613.05    982618.0 2024-11-19

[221 rows x 7 columns]
     Symbol    open    high     low   close      volume start_Time
0    JIOFIN  233.35  236.40  233.30  234.55   7919961.0 2024-01-01
1    JIOFIN  235.00  236.00  232.00  235.35   9216592.0 2024-01-02
2    JIOFIN  235.40  236.00  233.55  234.50   9864949.0 2024-01-03
3    JIOFIN  238.85  243.25  236.80  241.40  32808937.0 2024-01-04
4    JIOFIN  244.50  248.20  241.50  243.65  29722064.0 2024-01-05
..      ...     ...     ...     ...     ...         ...        ...
216  JIOFIN  312.20  316.15  310.00  310.25   5765828.0 2024-11-12
217  JIOFIN  310.00  310.00  298.00  299.40  14563487.0 2024-11-13
218  JIOFIN  302.75  320.50  302.75  318.35  42750072.0 2024-11-14
219  JIOFIN  320.00  322.90  313.85  318.80  15570302.0 2024-11-18
220  JIOFIN  320.00  323.80  317.10  319.35   9800376.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

     Symbol    open    high     low   close     volume start_Time
0    TVSSCS  198.20  200.20  198.20  198.90   453389.0 2024-01-01
1    TVSSCS  198.90  200.00  196.30  198.90   802992.0 2024-01-02
2    TVSSCS  199.00  200.10  198.35  199.15   596881.0 2024-01-03
3    TVSSCS  200.00  200.90  199.25  199.55   439330.0 2024-01-04
4    TVSSCS  200.00  200.50  198.00  198.75   606840.0 2024-01-05
..      ...     ...     ...     ...     ...        ...        ...
216  TVSSCS  187.50  194.35  182.21  184.10  2493546.0 2024-11-12
217  TVSSCS  182.70  183.30  175.29  176.44   721676.0 2024-11-13
218  TVSSCS  177.35  182.00  177.15  179.92   527348.0 2024-11-14
219  TVSSCS  179.00  182.93  178.32  181.77   360416.0 2024-11-18
220  TVSSCS  181.96  184.79  181.58  182.42   317116.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol    open     high      low    close    volume start_Time
0    PERSISTENT  3712.5  3712.50  3650.58  3658.95  140396.0 2024-01-01
1    PERSISTENT  3677.5  3681.98  3622.35  3664.53  195144.0 2024-01-02
2    PERSISTENT  3650.0  3662.50  3580.18  3643.78  254382.0 2024-01-03
3    PERSISTENT  3656.0  3707.48  3609.08  3632.60  300194.0 2024-01-04
4    PERSISTENT  3635.0  3699.00  3630.00  3675.38  261555.0 2024-01-05
..          ...     ...      ...      ...      ...       ...        ...
216  PERSISTENT  5750.0  5765.00  5656.25  5680.15  250857.0 2024-11-12
217  PERSISTENT  5690.0  5700.00  5589.00  5640.60  283558.0 2024-11-13
218  PERSISTENT  5670.0  5783.90  5660.00  5713.80  379197.0 2024-11-14
219  PERSISTENT  5728.8  5755.00  5582.00  5646.10  411485.0 2024-11-18
220  PERSISTENT  5655.0  5798.15  5632.05  5710.30  361445.0 2024-11-19

[221 rows x 7 columns]
      Symbol    open    high     low   close      volume start_Time
0    RBLBANK  280.50  287.70  278.75  284.60   8540993.0 2024-01-01
1    RBLBANK  284.70  291.95  280.05  280.90  14347750.0 2024-01-02
2    RBLBANK  280.90  287.30  278.30  284.90   6215850.0 2024-01-03
3    RBLBANK  284.90  287.75  282.70  286.20   6818298.0 2024-01-04
4    RBLBANK  292.00  292.60  283.00  287.50   9606918.0 2024-01-05
..       ...     ...     ...     ...     ...         ...        ...
216  RBLBANK  162.44  164.70  158.80  159.68   5007274.0 2024-11-12
217  RBLBANK  158.50  159.68  151.75  152.12  10358574.0 2024-11-13
218  RBLBANK  152.39  155.38  151.46  154.73   6990014.0 2024-11-14
219  RBLBANK  154.75  159.45  152.86  158.39   7609043.0 2024-11-18
220  RBLBANK  158.49  161.64  155.01  156.18   7867180.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol      open      high       low     close    volume start_Time
0    POWERINDIA   5294.60   5489.00   5274.45   5457.30   29028.0 2024-01-01
1    POWERINDIA   5440.05   5545.05   5348.65   5427.30   23372.0 2024-01-02
2    POWERINDIA   5453.10   5537.15   5404.00   5438.00   40560.0 2024-01-03
3    POWERINDIA   5463.85   5680.00   5388.60   5630.80   35565.0 2024-01-04
4    POWERINDIA   5611.00   5747.20   5557.95   5597.25   29513.0 2024-01-05
..          ...       ...       ...       ...       ...       ...        ...
216  POWERINDIA  13485.80  13490.10  12800.00  12952.80  111696.0 2024-11-12
217  POWERINDIA  12850.00  12896.30  11709.05  12121.25  154186.0 2024-11-13
218  POWERINDIA  12121.25  12295.10  11716.05  11782.35  126619.0 2024-11-14
219  POWERINDIA  11782.30  11790.40  11220.90  11392.15  113311.0 2024-11-18
220  POWERINDIA  11419.95  12134.95  11300.30  11729.40  106159.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open     high      low    close    volume start_Time
0     LTTS  5255.00  5267.55  5200.00  5210.35   73532.0 2024-01-01
1     LTTS  5190.00  5209.85  5113.75  5183.50  159950.0 2024-01-02
2     LTTS  5164.05  5164.05  5061.00  5115.05  134958.0 2024-01-03
3     LTTS  5159.00  5294.00  5131.10  5229.55  296732.0 2024-01-04
4     LTTS  5210.00  5283.45  5176.60  5217.70  138812.0 2024-01-05
..     ...      ...      ...      ...      ...       ...        ...
216   LTTS  5157.00  5370.00  5156.95  5278.85  368421.0 2024-11-12
217   LTTS  5295.00  5331.50  5151.85  5174.75  104383.0 2024-11-13
218   LTTS  5174.75  5221.05  5115.65  5170.00   68662.0 2024-11-14
219   LTTS  5185.00  5199.25  5012.05  5104.30   75125.0 2024-11-18
220   LTTS  5126.90  5236.45  5088.10  5132.95   74262.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol     open     high      low    close    volume start_Time
0    RRKABEL  1580.00  1590.00  1575.00  1578.50   63970.0 2024-01-01
1    RRKABEL  1578.50  1610.45  1545.65  1558.10  259832.0 2024-01-02
2    RRKABEL  1564.25  1569.25  1529.00  1542.40  156024.0 2024-01-03
3    RRKABEL  1550.00  1595.00  1548.00  1589.45  144000.0 2024-01-04
4    RRKABEL  1589.40  1597.80  1557.05  1575.45  114119.0 2024-01-05
..       ...      ...      ...      ...      ...       ...        ...
216  RRKABEL  1490.00  1528.95  1485.25  1506.70   40017.0 2024-11-12
217  RRKABEL  1506.70  1552.95  1463.80  1525.30   68043.0 2024-11-13
218  RRKABEL  1510.00  1553.95  1510.00  1527.10   49229.0 2024-11-14
219  RRKABEL  1519.00  1548.00  1508.10  1545.15   32630.0 2024-11-18
220  RRKABEL  1560.60  1569.00  1515.00  1546.30   42935.0 2024-11-19

[221 rows x 7 columns]
         Symbol    open    high     low   close     volume start_Time
0    ICICIPRULI  534.70  536.00  530.75  531.95  1578322.0 2024-01-01
1    ICICIPRULI  531.95  536.00  528.10  534.40  1359923.0 2024-01-02
2    ICICIPRULI  534.20  539.80  531.80  534.90  1334907.0 2024-01-03
3    ICICIPRULI  536.00  541.10  535.00  539.85  1718311.0 2024-01-04
4    ICICIPRULI  538.50  545.55  535.15  541.00  3895158.0 2024-01-05
..          ...     ...     ...     ...     ...        ...        ...
216  ICICIPRULI  704.70  711.25  698.25  702.10  1105532.0 2024-11-12
217  ICICIPRULI  692.25  701.15  685.00  688.00   562534.0 2024-11-13
218  ICICIPRULI  689.80  699.45  688.05  693.90   542297.0 2024-11-14
219  ICICIPRULI  687.00  698.75  683.00  693.20   509365.0 2024-11-18
220  ICICIPRULI  695.00  695.95  668.30  685.20  2346510.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

     Symbol     open     high      low    close    volume start_Time
0    NUVAMA  3620.00  3650.15  3560.00  3615.70   15641.0 2024-01-01
1    NUVAMA  3616.00  3629.70  3515.00  3569.10   30070.0 2024-01-02
2    NUVAMA  3579.00  3625.15  3533.05  3590.85   25185.0 2024-01-03
3    NUVAMA  3600.00  3655.00  3572.60  3605.00   28837.0 2024-01-04
4    NUVAMA  3593.00  3691.05  3593.00  3635.75   36220.0 2024-01-05
..      ...      ...      ...      ...      ...       ...        ...
216  NUVAMA  6815.05  6883.05  6540.00  6575.60   76411.0 2024-11-12
217  NUVAMA  6575.00  6575.00  6273.05  6360.65  150238.0 2024-11-13
218  NUVAMA  6380.65  6760.00  6370.00  6727.60  139453.0 2024-11-14
219  NUVAMA  6739.90  6829.70  6511.00  6606.00   77021.0 2024-11-18
220  NUVAMA  6618.95  6698.90  6538.25  6611.35   38201.0 2024-11-19

[221 rows x 7 columns]
        Symbol     open     high      low    close     volume start_Time
0    SIGNATURE   879.65   945.00   877.40   918.55   493277.0 2024-01-01
1    SIGNATURE   923.00   934.00   911.00   931.55   196884.0 2024-01-02
2    SIGNATURE   931.55   959.80   921.05   950.95   552051.0 2024-01-03
3    SIGNATURE   956.00  1048.00   956.00  1027.10  1928036.0 2024-01-04
4    SIGNATURE  1039.95  1066.40  1031.45  1055.50   613608.0 2024-01-05
..         ...      ...      ...      ...      ...        ...        ...
216  SIGNATURE  1278.80  1348.00  1277.60  1302.20   541693.0 2024-11-12
217  SIGNATURE  1302.20  1303.15  1251.00  1257.25   546859.0 2024-11-13
218  SIGNATURE  1259.90  1319.00  1259.35  1302.95   548356.0 2024-11-14
219  SIGNATURE  1305.00  1309.70  1282.65  1290.80   295764.0 2024-11-18
220  SIGNATURE  1290.80  1320.00  1281.95  1289.10   335711.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

        Symbol     open     high      low    close     volume start_Time
0    ENDURANCE  1945.85  1945.85  1906.50  1929.75    71934.0 2024-01-01
1    ENDURANCE  1917.10  1930.00  1870.00  1881.70    57595.0 2024-01-02
2    ENDURANCE  1870.00  1909.90  1864.60  1892.80    90384.0 2024-01-03
3    ENDURANCE  1884.40  1940.00  1881.45  1932.35    76285.0 2024-01-04
4    ENDURANCE  1932.00  2318.80  1932.00  2116.45  1860825.0 2024-01-05
..         ...      ...      ...      ...      ...        ...        ...
216  ENDURANCE  2532.20  2535.10  2455.00  2468.20   147893.0 2024-11-12
217  ENDURANCE  2450.00  2455.60  2371.00  2398.25   267566.0 2024-11-13
218  ENDURANCE  2384.35  2450.90  2360.00  2375.30    48443.0 2024-11-14
219  ENDURANCE  2376.50  2395.90  2341.50  2360.40    28975.0 2024-11-18
220  ENDURANCE  2350.00  2403.80  2337.80  2356.80    40248.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close      volume start_Time
0     SJVN   94.00   94.20   91.75   92.90  24607805.0 2024-01-01
1     SJVN   94.50   95.10   92.05   93.30  29129762.0 2024-01-02
2     SJVN   93.50   94.10   92.20   92.70  12797596.0 2024-01-03
3     SJVN   92.95   95.95   92.60   94.05  39135556.0 2024-01-04
4     SJVN   94.50   97.00   94.00   94.75  46219735.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216   SJVN  109.95  111.77  107.65  108.63   4305092.0 2024-11-12
217   SJVN  107.20  108.40  103.36  104.19   6363826.0 2024-11-13
218   SJVN  103.50  106.34  103.45  103.77   5101719.0 2024-11-14
219   SJVN  104.00  105.38  101.70  104.62   5543260.0 2024-11-18
220   SJVN  105.10  107.96  104.90  105.83   5049335.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol    open    high     low   close      volume start_Time
0    PNBHOUSING  781.90  794.90  780.90  785.30    144151.0 2024-01-01
1    PNBHOUSING  785.90  792.90  776.00  778.50    223333.0 2024-01-02
2    PNBHOUSING  785.10  803.95  785.10  788.15    347062.0 2024-01-03
3    PNBHOUSING  793.00  798.85  787.95  796.45    135541.0 2024-01-04
4    PNBHOUSING  802.00  807.00  788.30  800.65    184904.0 2024-01-05
..          ...     ...     ...     ...     ...         ...        ...
216  PNBHOUSING  969.95  993.55  959.05  983.15    596629.0 2024-11-12
217  PNBHOUSING  949.00  952.85  905.05  924.65  31406738.0 2024-11-13
218  PNBHOUSING  935.00  944.30  894.95  904.00   2880521.0 2024-11-14
219  PNBHOUSING  895.00  895.00  833.65  871.15   6852378.0 2024-11-18
220  PNBHOUSING  875.00  893.55  854.35  865.15   2334072.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close      volume start_Time
0      VBL  496.72  501.60  494.80  497.00    789487.0 2024-01-01
1      VBL  500.00  500.00  492.90  494.46    982195.0 2024-01-02
2      VBL  490.04  495.90  482.46  490.32   1631101.0 2024-01-03
3      VBL  498.40  510.96  493.60  504.00   2387192.0 2024-01-04
4      VBL  504.00  513.20  497.70  511.66   2029763.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216    VBL  594.55  599.00  583.00  584.30   2680480.0 2024-11-12
217    VBL  591.10  594.95  565.00  568.10   6817240.0 2024-11-13
218    VBL  575.00  596.00  570.30  575.65   6805711.0 2024-11-14
219    VBL  593.00  617.60  582.85  609.85   8284043.0 2024-11-18
220    VBL  616.00  639.60  614.40  630.35  11261723.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close     volume start_Time
0    MUTHOOTFIN  1484.90  1489.60  1460.60  1466.00   373747.0 2024-01-01
1    MUTHOOTFIN  1460.00  1472.55  1440.60  1454.70   385614.0 2024-01-02
2    MUTHOOTFIN  1459.85  1493.35  1452.60  1475.85   798316.0 2024-01-03
3    MUTHOOTFIN  1480.00  1528.60  1460.10  1517.80   782324.0 2024-01-04
4    MUTHOOTFIN  1523.80  1537.35  1492.50  1499.50   336177.0 2024-01-05
..          ...      ...      ...      ...      ...        ...        ...
216  MUTHOOTFIN  1817.15  1830.00  1783.05  1792.70   300260.0 2024-11-12
217  MUTHOOTFIN  1788.00  1803.80  1761.05  1770.30   194824.0 2024-11-13
218  MUTHOOTFIN  1770.30  1790.00  1756.05  1775.85   329256.0 2024-11-14
219  MUTHOOTFIN  1866.00  1925.00  1846.05  1885.65  3587575.0 2024-11-18
220  MUTHOOTFIN  1886.00  1912.95  1875.00  1896.45   758238.0 2024-11-19

[221 rows x 7 columns]
       Symbol    open    high     low   close     volume start_Time
0    JSWINFRA  208.30  212.40  208.30  210.65  4134909.0 2024-01-01
1    JSWINFRA  210.65  213.45  207.50  210.25  3179497.0 2024-01-02
2    JSWINFRA  210.25  216.80  209.50  213.65  4654889.0 2024-01-03
3    JSWINFRA  214.20  216.25  213.40  214.30  2952871.0 2024-01-04
4    JSWINFRA  215.50  223.60  215.05  218.90  6384087.0 2024-01-05
..        ...     ...     ...     ...     ...        ...        ...
216  JSWINFRA  309.90  311.95  301.85  303.20   689290.0 2024-11-12
217  JSWINFRA  301.70  302.50  290.00  291.10  1629640.0 2024-11-13
218  JSWINFRA  291.10  296.90  288.80  290.60  1571106.0 2024-11-14
219  JSWINFRA  292.50  299.00  286.60  296.90  1385760.0 2024-11-18
220  JSWINFRA  298.45  312.00  296.00  299.20  2699945.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol    open    high     low   close      volume start_Time
0    MANAPPURAM  172.10  173.30  170.50  171.35   3600254.0 2024-01-01
1    MANAPPURAM  171.35  173.40  168.10  168.50   5954260.0 2024-01-02
2    MANAPPURAM  168.65  176.70  168.50  173.90  11989734.0 2024-01-03
3    MANAPPURAM  173.95  178.30  173.80  176.30   8827510.0 2024-01-04
4    MANAPPURAM  176.35  181.65  174.45  175.75  12003228.0 2024-01-05
..          ...     ...     ...     ...     ...         ...        ...
216  MANAPPURAM  155.50  160.18  155.01  157.99  14722563.0 2024-11-12
217  MANAPPURAM  160.00  164.00  156.00  158.10  32876884.0 2024-11-13
218  MANAPPURAM  158.90  161.95  155.10  155.63  13659158.0 2024-11-14
219  MANAPPURAM  156.00  156.36  151.51  153.93   9120516.0 2024-11-18
220  MANAPPURAM  155.00  159.20  153.49  154.76   6435732.0 2024-11-19

[221 rows x 7 columns]
         Symbol    open    high     low   close     volume start_Time
0    LAURUSLABS  431.00  441.35  429.00  433.05  2368738.0 2024-01-01
1    LAURUSLABS  433.05  444.70  431.10  435.65  3370927.0 2024-01-02
2    LAURUSLABS  436.00  437.20  425.65  429.45  1472207.0 2024-01-03
3    LAURUSLABS  431.00  433.95  429.05  430.55   964779.0 2024-01-04
4    LAURUSLABS  432.90  433.45  422.00  427.30  1082064.0 2024-01-05
..          ...     ...     ...     ...     ...        ...        ...
216  LAURUSLABS  493.00  503.20  488.20  489.55  1141880.0 2024-11-12
217  LAURUSLABS  489.75  489.75  474.05  476.65  1280607.0 2024-11-13
218  LAURUSLABS  477.90  487.75  477.00  486.00   878316.0 2024-11-14
219  LAURUSLABS  485.05  493.00  475.10  483.65  1030870.0 2024-11-18
220  LAURUSLABS  486.00  495.90  483.65  489.00   650315.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol     open     high      low    close     volume start_Time
0      BSE  2225.00  2227.75  2190.00  2203.05   488056.0 2024-01-01
1      BSE  2214.20  2300.00  2200.50  2235.95   934165.0 2024-01-02
2      BSE  2238.80  2274.00  2210.00  2253.35   524120.0 2024-01-03
3      BSE  2255.00  2293.95  2240.00  2277.10   490105.0 2024-01-04
4      BSE  2287.00  2310.00  2271.90  2303.75   531863.0 2024-01-05
..     ...      ...      ...      ...      ...        ...        ...
216    BSE  4675.00  4783.90  4621.05  4678.20  1810046.0 2024-11-12
217    BSE  4737.55  4789.00  4451.70  4491.80  3647865.0 2024-11-13
218    BSE  4499.00  4665.00  4495.00  4547.80  1878541.0 2024-11-14
219    BSE  4564.00  4740.00  4471.85  4706.00  2507716.0 2024-11-18
220    BSE  4748.00  4858.00  4693.60  4727.35  2328859.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open     high      low    close     volume start_Time
0    PIIND  3529.00  3543.85  3470.00  3478.65   415257.0 2024-01-01
1    PIIND  3500.00  3505.00  3439.80  3486.05   229908.0 2024-01-02
2    PIIND  3487.00  3493.70  3455.25  3463.85   212693.0 2024-01-03
3    PIIND  3470.00  3479.75  3418.85  3438.05   368739.0 2024-01-04
4    PIIND  3458.00  3472.10  3437.00  3460.50   295652.0 2024-01-05
..     ...      ...      ...      ...      ...        ...        ...
216  PIIND  4604.90  4648.35  4516.00  4548.90   247900.0 2024-11-12
217  PIIND  4545.00  4553.35  4400.95  4446.15   174456.0 2024-11-13
218  PIIND  4349.15  4349.15  4045.85  4265.25  1612326.0 2024-11-14
219  PIIND  4260.00  4265.00  4138.80  4191.95   595995.0 2024-11-18
220  PIIND  4192.00  4209.95  4121.30  4148.80   281992.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close     volume start_Time
0     GPPL  153.65  161.50  152.05  158.60  6785151.0 2024-01-01
1     GPPL  159.80  160.25  154.70  158.75  4375827.0 2024-01-02
2     GPPL  158.05  159.00  156.50  156.70  1626505.0 2024-01-03
3     GPPL  158.00  160.15  157.30  159.15  2746947.0 2024-01-04
4     GPPL  159.90  160.60  154.00  157.15  2994748.0 2024-01-05
..     ...     ...     ...     ...     ...        ...        ...
216   GPPL  182.73  183.58  178.00  179.28   637205.0 2024-11-12
217   GPPL  179.10  182.21  174.00  175.51  1343633.0 2024-11-13
218   GPPL  175.99  181.50  175.00  175.56   940163.0 2024-11-14
219   GPPL  176.99  179.93  174.00  175.65   978458.0 2024-11-18
220   GPPL  172.70  178.03  172.05  173.45   910243.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close     volume start_Time
0    CELLO  795.05  799.40  785.25  796.60   194900.0 2024-01-01
1    CELLO  792.00  811.00  792.00  806.55   586064.0 2024-01-02
2    CELLO  806.65  835.00  799.00  828.25   930425.0 2024-01-03
3    CELLO  829.00  875.00  828.95  871.20  1616636.0 2024-01-04
4    CELLO  871.20  881.95  854.75  857.25  1237562.0 2024-01-05
..     ...     ...     ...     ...     ...        ...        ...
216  CELLO  853.15  853.15  831.00  843.60    37709.0 2024-11-12
217  CELLO  839.00  839.00  795.00  816.45   188313.0 2024-11-13
218  CELLO  811.75  820.00  802.00  806.80   181102.0 2024-11-14
219  CELLO  806.90  809.10  782.00  791.05    74835.0 2024-11-18
220  CELLO  793.80  795.95  780.85  782.90   122656.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

     Symbol    open    high     low   close      volume start_Time
0    HONASA  444.60  448.00  424.00  426.85    435620.0 2024-01-01
1    HONASA  431.10  436.00  417.00  432.35    893359.0 2024-01-02
2    HONASA  432.90  444.65  419.40  441.70    718068.0 2024-01-03
3    HONASA  450.00  464.00  444.05  454.25    706476.0 2024-01-04
4    HONASA  458.25  467.80  442.15  445.65    688164.0 2024-01-05
..      ...     ...     ...     ...     ...         ...        ...
216  HONASA  382.00  387.70  372.10  374.15    411136.0 2024-11-12
217  HONASA  374.00  378.80  355.55  364.25    839670.0 2024-11-13
218  HONASA  364.75  379.60  364.75  371.55    520808.0 2024-11-14
219  HONASA  306.00  309.00  297.25  297.25    733228.0 2024-11-18
220  HONASA  254.95  270.00  242.35  264.10  12601303.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open     high      low    close    volume start_Time
0    DMART  4075.0  4080.00  4042.10  4064.75  131614.0 2024-01-01
1    DMART  4070.0  4155.00  4006.25  4103.35  843252.0 2024-01-02
2    DMART  4080.0  4080.00  3919.40  3932.35  964470.0 2024-01-03
3    DMART  3965.0  3965.00  3888.00  3897.85  754490.0 2024-01-04
4    DMART  3902.0  3940.00  3810.00  3863.50  513823.0 2024-01-05
..     ...     ...      ...      ...      ...       ...        ...
216  DMART  3910.0  3910.00  3762.55  3777.00  683988.0 2024-11-12
217  DMART  3774.0  3874.95  3751.00  3759.55  419503.0 2024-11-13
218  DMART  3785.2  3858.85  3769.00  3823.85  305991.0 2024-11-14
219  DMART  3948.0  3948.00  3757.60  3790.55  656068.0 2024-11-18
220  DMART  3792.5  3794.55  3737.65  3752.45  813368.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

        Symbol     open     high      low    close     volume start_Time
0    DEEPAKNTR  2488.00  2521.15  2460.00  2473.90   499429.0 2024-01-01
1    DEEPAKNTR  2474.00  2494.00  2424.85  2479.20   361687.0 2024-01-02
2    DEEPAKNTR  2479.20  2500.00  2435.05  2480.05   401471.0 2024-01-03
3    DEEPAKNTR  2478.00  2519.00  2473.20  2487.00   301557.0 2024-01-04
4    DEEPAKNTR  2475.10  2509.00  2415.60  2447.95   292318.0 2024-01-05
..         ...      ...      ...      ...      ...        ...        ...
216  DEEPAKNTR  2628.00  2654.30  2551.10  2572.90   403641.0 2024-11-12
217  DEEPAKNTR  2564.00  2572.20  2475.65  2493.60   545515.0 2024-11-13
218  DEEPAKNTR  2453.00  2667.00  2453.00  2638.50  1152662.0 2024-11-14
219  DEEPAKNTR  2634.00  2634.00  2511.75  2569.30   688509.0 2024-11-18
220  DEEPAKNTR  2579.75  2714.00  2550.00  2671.30   548742.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close      volume start_Time
0      LTF  165.00  165.60  162.70  163.45   3461469.0 2024-01-01
1      LTF  163.65  164.50  159.60  162.35   5915599.0 2024-01-02
2      LTF  163.00  170.80  162.50  166.15  24444967.0 2024-01-03
3      LTF  167.85  172.20  166.70  171.60   7364747.0 2024-01-04
4      LTF  173.50  174.95  168.60  170.90  13042843.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
217    LTF  141.10  141.61  138.13  138.57   4140867.0 2024-11-12
218    LTF  137.61  138.55  134.10  135.91  12440862.0 2024-11-13
219    LTF  135.90  138.60  135.46  137.51   5267955.0 2024-11-14
220    LTF  136.56  140.50  135.39  138.69   5629198.0 2024-11-18
221    LTF  139.25  142.49  138.69  139.71   5892083.0 2024-11-19

[222 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

     Symbol     open     high      low    close     volume start_Time
0    APLLTD   760.15   768.95   756.70   765.90    46900.0 2024-01-01
1    APLLTD   775.00   820.00   773.40   792.45  2305676.0 2024-01-02
2    APLLTD   798.00   824.95   796.05   807.60   644476.0 2024-01-03
3    APLLTD   811.90   814.50   798.05   809.15   860880.0 2024-01-04
4    APLLTD   813.40   816.75   800.10   811.75   173659.0 2024-01-05
..      ...      ...      ...      ...      ...        ...        ...
216  APLLTD  1041.55  1045.00  1017.15  1034.25   485730.0 2024-11-12
217  APLLTD  1032.70  1038.40   999.95  1019.50   146013.0 2024-11-13
218  APLLTD  1020.50  1035.50  1019.55  1028.00   111101.0 2024-11-14
219  APLLTD  1002.35  1027.90   992.40  1024.65   109039.0 2024-11-18
220  APLLTD  1025.05  1051.00  1025.05  1040.35    91442.0 2024-11-19

[221 rows x 7 columns]
         Symbol    open    high     low   close      volume start_Time
0    TRITURBINE  424.15  426.75  417.55  420.15    148288.0 2024-01-01
1    TRITURBINE  419.70  423.30  412.75  421.10    171802.0 2024-01-02
2    TRITURBINE  421.90  427.80  418.55  420.60    272045.0 2024-01-03
3    TRITURBINE  420.60  425.10  418.10  421.40    221318.0 2024-01-04
4    TRITURBINE  424.70  436.85  411.10  412.85    615565.0 2024-01-05
..          ...     ...     ...     ...     ...         ...        ...
216  TRITURBINE  671.00  698.65  626.05  647.95  19724212.0 2024-11-12
217  TRITURBINE  650.55  659.00  636.95  645.45   2076150.0 2024-11-13
218  TRITURBINE  643.00  658.85  636.10  655.65    944286.0 2024-11-14
219  TRITURBINE  650.00  667.80  645.00  645.90   1021718.0 2024-11-18
220  TRITURBINE  649.85  697.05  642.40  691.65   5623441.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close      volume start_Time
0    ABFRL  226.00  227.20  223.60  225.85   1877648.0 2024-01-01
1    ABFRL  230.55  246.50  227.35  242.35  27564558.0 2024-01-02
2    ABFRL  242.75  244.50  238.45  240.75   6307165.0 2024-01-03
3    ABFRL  241.60  248.80  240.20  246.75   7066222.0 2024-01-04
4    ABFRL  247.60  249.25  234.15  238.10   8252293.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216  ABFRL  299.10  300.80  292.65  293.85   1667511.0 2024-11-12
217  ABFRL  293.00  294.30  287.00  290.10   2647938.0 2024-11-13
218  ABFRL  290.50  295.65  287.15  288.70   1511988.0 2024-11-14
219  ABFRL  288.65  294.00  284.70  291.55   1508717.0 2024-11-18
220  ABFRL  292.00  298.00  288.25  289.20   1793244.0 2024-11-19

[221 rows x 7 columns]
      Symbol     open     high      low    close    volume start_Time
0    POLYMED  1490.00  1503.00  1463.00  1469.65   34960.0 2024-01-01
1    POLYMED  1470.00  1478.45  1435.00  1438.65   53891.0 2024-01-02
2    POLYMED  1460.00  1469.20  1435.30  1445.20   35398.0 2024-01-03
3    POLYMED  1450.00  1457.45  1430.00  1434.90   41678.0 2024-01-04
4    POLYMED  1440.20  1492.00  1435.10  1487.00  154702.0 2024-01-05
..       ...      ...      ...      ...      ...       ...        ...
216  POLYMED  2731.85  2786.90  2680.00  2709.35   98668.0 2024-11-12
217  POLYMED  2680.00  2684.00  2504.00  2655.15  257017.0 2024-11-13
218  POLYMED  2669.95  2748.65  2669.95  2701.10  194979.0 2024-11-14
219  POLYMED  2724.85  2730.00  2590.00  2616.60   88690.0 2024-11-18
220  POLYMED  2604.65  2656.85  2564.70  2607.70  105440.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

        Symbol     open     high      low    close     volume start_Time
0    APLAPOLLO  1553.90  1560.00  1511.15  1528.70   737306.0 2024-01-01
1    APLAPOLLO  1500.00  1525.00  1466.65  1504.35  1576938.0 2024-01-02
2    APLAPOLLO  1491.20  1499.90  1467.00  1470.15  1060686.0 2024-01-03
3    APLAPOLLO  1480.00  1487.60  1432.90  1450.85  1798393.0 2024-01-04
4    APLAPOLLO  1457.90  1551.00  1454.15  1523.75  2264237.0 2024-01-05
..         ...      ...      ...      ...      ...        ...        ...
216  APLAPOLLO  1536.00  1543.00  1509.50  1525.70   235466.0 2024-11-12
217  APLAPOLLO  1525.70  1529.05  1491.10  1498.30   323037.0 2024-11-13
218  APLAPOLLO  1501.00  1524.70  1460.00  1470.50   298600.0 2024-11-14
219  APLAPOLLO  1493.95  1502.50  1453.00  1471.05   330262.0 2024-11-18
220  APLAPOLLO  1471.05  1519.20  1460.00  1466.80   373487.0 2024-11-19

[221 rows x 7 columns]
        Symbol    open    high     low   close    volume start_Time
0    MINDACORP  386.00  387.65  380.00  385.25  178572.0 2024-01-01
1    MINDACORP  385.25  385.25  375.30  377.95  397640.0 2024-01-02
2    MINDACORP  378.00  389.30  377.10  384.35  425901.0 2024-01-03
3    MINDACORP  386.40  387.00  376.00  380.10  254164.0 2024-01-04
4    MINDACORP  385.75  386.00  379.15  380.25  177513.0 2024-01-05
..         ...     ...     ...     ...     ...       ...        ...
216  MINDACORP  500.00  507.65  486.30  494.45  611651.0 2024-11-12
217  MINDACORP  501.00  504.30  470.15  476.55  681831.0 2024-11-13
218  MINDACORP  484.50  500.00  484.50  494.30  917962.0 2024-11-14
219  MINDACORP  494.30  499.25  477.50  489.90  745318.0 2024-11-18
220  MINDACORP  492.00  500.75  481.80  484.35  174309.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close    volume start_Time
0     RHIM  803.00  815.05  796.05  802.45  116521.0 2024-01-01
1     RHIM  803.00  807.20  789.10  794.00   89828.0 2024-01-02
2     RHIM  795.00  798.90  778.50  782.15  150897.0 2024-01-03
3     RHIM  784.35  806.75  781.85  803.35  132457.0 2024-01-04
4     RHIM  804.50  807.55  796.25  805.35   89469.0 2024-01-05
..     ...     ...     ...     ...     ...       ...        ...
216   RHIM  558.85  562.60  540.20  542.05  138537.0 2024-11-12
217   RHIM  541.00  541.20  513.40  530.40  251913.0 2024-11-13
218   RHIM  524.75  532.05  519.15  528.40   90348.0 2024-11-14
219   RHIM  525.30  529.90  514.55  518.65   95189.0 2024-11-18
220   RHIM  518.65  523.95  515.00  516.55   72453.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open     high      low    close    volume start_Time
0      MCX  3195.00  3209.00  3144.00  3169.45  326803.0 2024-01-01
1      MCX  3170.05  3231.90  3110.00  3178.05  638190.0 2024-01-02
2      MCX  3184.90  3189.50  3140.05  3177.55  331804.0 2024-01-03
3      MCX  3185.00  3239.75  3160.00  3181.55  394809.0 2024-01-04
4      MCX  3207.00  3220.00  3102.05  3144.45  461142.0 2024-01-05
..     ...      ...      ...      ...      ...       ...        ...
216    MCX  6420.00  6447.45  6076.80  6104.35  403189.0 2024-11-12
217    MCX  6001.50  6145.00  5910.65  5949.15  361849.0 2024-11-13
218    MCX  5959.95  6115.00  5920.20  5950.65  223201.0 2024-11-14
219    MCX  5940.00  6000.00  5820.80  5909.30  342360.0 2024-11-18
220    MCX  5950.00  6154.00  5930.15  6106.35  386284.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

        Symbol   open    high     low   close     volume start_Time
0    SCHNEIDER  412.0  412.50  402.55  403.85   163037.0 2024-01-01
1    SCHNEIDER  404.0  406.15  395.95  399.40   204156.0 2024-01-02
2    SCHNEIDER  401.0  403.30  394.35  400.80   178537.0 2024-01-03
3    SCHNEIDER  402.0  409.55  402.00  407.95   209462.0 2024-01-04
4    SCHNEIDER  411.0  418.00  408.80  414.15   355939.0 2024-01-05
..         ...    ...     ...     ...     ...        ...        ...
216  SCHNEIDER  772.0  784.00  755.00  759.15    80774.0 2024-11-12
217  SCHNEIDER  750.0  756.55  715.15  720.70   173825.0 2024-11-13
218  SCHNEIDER  730.0  757.85  701.50  724.55   605475.0 2024-11-14
219  SCHNEIDER  736.7  736.70  678.05  704.60   506525.0 2024-11-18
220  SCHNEIDER  706.6  761.80  706.60  732.95  1015887.0 2024-11-19

[221 rows x 7 columns]
    Symbol   open   high    low  close       volume start_Time
0     NBCC  54.63  55.40  54.40  54.57   10161058.0 2024-01-01
1     NBCC  54.77  54.80  52.67  53.73   13866797.0 2024-01-02
2     NBCC  53.73  59.03  53.17  58.67  125974979.0 2024-01-03
3     NBCC  59.07  59.90  57.93  58.40   49933311.0 2024-01-04
4     NBCC  58.63  59.63  57.17  57.73   21657363.0 2024-01-05
..     ...    ...    ...    ...    ...          ...        ...
216   NBCC  94.70  96.40  92.12  93.46    5050522.0 2024-11-12
217   NBCC  92.12  93.27  88.32  89.51    9326900.0 2024-11-13
218   NBCC  90.59  92.80  89.52  90.00    7851055.0 2024-11-14
219   NBCC  90.28  92.01  89.02  89.99    6470782.0 2024-11-18
220   NBCC  90.19  92.20  89.25  89.82    6571685.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close     volume start_Time
0     FACT  805.80  844.90  802.35  821.50  2516139.0 2024-01-01
1     FACT  827.00  849.80  810.50  820.85  1829334.0 2024-01-02
2     FACT  825.00  832.95  815.10  819.85   600545.0 2024-01-03
3     FACT  823.95  837.05  818.10  821.75   560963.0 2024-01-04
4     FACT  825.70  827.00  804.00  810.95   501555.0 2024-01-05
..     ...     ...     ...     ...     ...        ...        ...
216   FACT  869.10  887.00  854.90  858.85   108270.0 2024-11-12
217   FACT  856.80  856.80  812.90  816.50   145715.0 2024-11-13
218   FACT  810.00  838.00  810.00  818.70   144117.0 2024-11-14
219   FACT  820.30  825.90  805.80  813.90   126054.0 2024-11-18
220   FACT  813.05  837.00  810.00  818.15   102356.0 2024-11-19

[221 rows x 7 columns]
         Symbol     open     high      low    close    volume start_Time
0    SCHAEFFLER  3209.10  3224.25  3152.00  3210.20   25957.0 2024-01-01
1    SCHAEFFLER  3221.55  3224.00  3161.55  3191.00   26219.0 2024-01-02
2    SCHAEFFLER  3185.00  3199.00  3100.00  3107.40   62765.0 2024-01-03
3    SCHAEFFLER  3116.10  3131.35  3050.05  3114.10   68246.0 2024-01-04
4    SCHAEFFLER  3108.00  3249.95  3108.00  3225.95  106367.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  SCHAEFFLER  3500.00  3604.70  3475.00  3556.70   60457.0 2024-11-12
217  SCHAEFFLER  3530.00  3535.60  3378.05  3397.40   64281.0 2024-11-13
218  SCHAEFFLER  3383.80  3451.65  3380.05  3424.00   83047.0 2024-11-14
219  SCHAEFFLER  3425.00  3448.65  3325.00  3415.75   74849.0 2024-11-18
220  SCHAEFFLER  3418.95  3478.00  3381.70  3415.10   50141.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol    open    high     low   close      volume start_Time
0    FEDERALBNK  156.20  157.20  155.90  156.55   6210375.0 2024-01-01
1    FEDERALBNK  156.55  156.95  151.10  151.90  13182359.0 2024-01-02
2    FEDERALBNK  153.20  153.20  151.05  151.75  10486168.0 2024-01-03
3    FEDERALBNK  152.50  155.25  152.45  154.85  13766132.0 2024-01-04
4    FEDERALBNK  155.95  155.95  153.05  154.60   7195693.0 2024-01-05
..          ...     ...     ...     ...     ...         ...        ...
216  FEDERALBNK  208.29  209.77  206.06  207.27   8129987.0 2024-11-12
217  FEDERALBNK  206.83  207.44  198.57  199.38  13381335.0 2024-11-13
218  FEDERALBNK  199.20  201.70  196.00  196.98   9354472.0 2024-11-14
219  FEDERALBNK  197.00  200.89  195.04  200.25  13133102.0 2024-11-18
220  FEDERALBNK  202.00  210.60  201.21  206.65  22964708.0 2024-11-19

[221 rows x 7 columns]
        Symbol     open     high      low    close    volume start_Time
0    FINCABLES  1055.00  1087.90  1048.05  1051.60  251346.0 2024-01-01
1    FINCABLES  1055.00  1055.00  1039.00  1041.30  198769.0 2024-01-02
2    FINCABLES  1047.00  1054.00  1026.60  1040.35  142552.0 2024-01-03
3    FINCABLES  1045.95  1051.00  1025.00  1028.75  164434.0 2024-01-04
4    FINCABLES  1040.90  1048.00  1029.85  1044.15  167885.0 2024-01-05
..         ...      ...      ...      ...      ...       ...        ...
216  FINCABLES  1210.00  1224.90  1103.15  1144.05  254973.0 2024-11-12
217  FINCABLES  1144.05  1159.15  1122.00  1136.80  103620.0 2024-11-13
218  FINCABLES  1131.45  1155.95  1105.05  1137.35  194632.0 2024-11-14
219  FINCABLES  1140.65  1170.00  1108.20  1120.55  102931.0 2024-11-18
220  FINCABLES  1120.50  1138.90  1111.25  1118.05   70574.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol    open    high     low   close     volume start_Time
0    FINPIPE  211.50  212.45  210.25  210.85   259760.0 2024-01-01
1    FINPIPE  211.05  211.80  207.70  208.85   420254.0 2024-01-02
2    FINPIPE  207.30  213.60  207.30  212.85   544743.0 2024-01-03
3    FINPIPE  213.20  218.90  213.20  218.30  1658002.0 2024-01-04
4    FINPIPE  222.00  240.00  221.00  237.35  9688548.0 2024-01-05
..       ...     ...     ...     ...     ...        ...        ...
216  FINPIPE  282.95  284.90  273.10  275.25   373460.0 2024-11-12
217  FINPIPE  274.50  274.95  261.25  263.30   539420.0 2024-11-13
218  FINPIPE  261.00  272.95  261.00  264.55   484816.0 2024-11-14
219  FINPIPE  264.55  266.50  259.35  263.40   493178.0 2024-11-18
220  FINPIPE  264.80  267.65  261.10  262.60   674094.0 2024-11-19

[221 rows x 7 columns]
         Symbol    open    high     low   close     volume start_Time
0    ZENSARTECH  613.40  626.65  605.15  607.20  1269873.0 2024-01-01
1    ZENSARTECH  610.60  614.25  587.00  591.70  1627720.0 2024-01-02
2    ZENSARTECH  592.95  596.40  571.05  577.75  1868440.0 2024-01-03
3    ZENSARTECH  582.00  589.00  571.40  584.70  2356075.0 2024-01-04
4    ZENSARTECH  586.55  595.00  577.10  583.85  1184596.0 2024-01-05
..          ...     ...     ...     ...     ...        ...        ...
216  ZENSARTECH  749.35  758.95  722.20  725.80   601011.0 2024-11-12
217  ZENSARTECH  724.45  725.05  694.20  698.00   454300.0 2024-11-13
218  ZENSARTECH  698.00  710.00  696.00  705.65   320758.0 2024-11-14
219  ZENSARTECH  705.70  707.30  682.10  700.15   272763.0 2024-11-18
220  ZENSARTECH  698.85  718.50  698.80  702.60   327598.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol     open     high      low    close     volume start_Time
0    GLAXO  1905.90  1988.85  1904.45  1951.55   599164.0 2024-01-01
1    GLAXO  1952.00  2080.05  1952.00  2049.00  1002951.0 2024-01-02
2    GLAXO  2059.85  2122.00  2042.20  2065.85   446546.0 2024-01-03
3    GLAXO  2090.00  2136.75  2079.70  2090.10   473293.0 2024-01-04
4    GLAXO  2100.00  2157.80  2095.75  2149.55   523909.0 2024-01-05
..     ...      ...      ...      ...      ...        ...        ...
216  GLAXO  2545.00  2589.90  2520.40  2547.35    59505.0 2024-11-12
217  GLAXO  2540.00  2540.10  2439.10  2452.70    65586.0 2024-11-13
218  GLAXO  2455.00  2491.00  2425.15  2457.15    78327.0 2024-11-14
219  GLAXO  2465.45  2485.50  2406.45  2411.65    42354.0 2024-11-18
220  GLAXO  2415.00  2478.45  2414.05  2438.00    69393.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close     volume start_Time
0     GNFC  756.40  809.00  752.50  793.95  5430757.0 2024-01-01
1     GNFC  797.40  809.90  779.05  792.95  2244306.0 2024-01-02
2     GNFC  792.95  802.80  777.00  795.60  1087646.0 2024-01-03
3     GNFC  795.60  814.90  795.00  801.20  1999978.0 2024-01-04
4     GNFC  800.00  804.35  760.00  762.65  2893119.0 2024-01-05
..     ...     ...     ...     ...     ...        ...        ...
216   GNFC  606.55  613.40  585.35  589.20   518462.0 2024-11-12
217   GNFC  587.00  588.10  542.45  545.00  2596724.0 2024-11-13
218   GNFC  524.00  563.70  524.00  554.20  3148142.0 2024-11-14
219   GNFC  560.50  564.00  546.30  558.50   633177.0 2024-11-18
220   GNFC  561.90  567.70  556.75  561.05   323619.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close    volume start_Time
0    GODFRYPHLP  2112.85  2119.90  2081.05  2092.55   31493.0 2024-01-01
1    GODFRYPHLP  2104.75  2200.00  2072.35  2153.25  174093.0 2024-01-02
2    GODFRYPHLP  2190.00  2206.90  2140.20  2181.70  133626.0 2024-01-03
3    GODFRYPHLP  2196.00  2197.00  2150.50  2175.25   44609.0 2024-01-04
4    GODFRYPHLP  2175.25  2225.00  2161.20  2216.90   84873.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  GODFRYPHLP  6780.00  6780.00  6547.95  6583.70   64123.0 2024-11-12
217  GODFRYPHLP  6599.95  6636.90  6280.00  6302.45   51493.0 2024-11-13
218  GODFRYPHLP  6292.00  6323.15  6091.00  6114.60   65715.0 2024-11-14
219  GODFRYPHLP  5965.05  6099.00  5914.60  6016.30   45011.0 2024-11-18
220  GODFRYPHLP  6030.20  6182.90  5955.00  5985.65   41896.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open     high      low    close    volume start_Time
0    AMBER  3155.00  3155.00  3116.00  3139.95   23073.0 2024-01-01
1    AMBER  3135.00  3149.00  3074.00  3106.30   35576.0 2024-01-02
2    AMBER  3146.00  3146.00  3097.10  3112.10   78657.0 2024-01-03
3    AMBER  3138.70  3238.00  3114.00  3189.80  326419.0 2024-01-04
4    AMBER  3232.00  3294.00  3210.10  3259.65  205685.0 2024-01-05
..     ...      ...      ...      ...      ...       ...        ...
216  AMBER  6092.80  6289.80  6072.15  6135.35  358393.0 2024-11-12
217  AMBER  6135.35  6175.00  5962.25  6086.95  301560.0 2024-11-13
218  AMBER  6125.00  6185.05  6055.15  6119.55  171704.0 2024-11-14
219  AMBER  6119.00  6378.90  6090.05  6209.00  362967.0 2024-11-18
220  AMBER  6219.90  6425.00  6131.00  6168.95  452758.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol     open     high      low    close    volume start_Time
0    GLAND  1934.90  1956.55  1900.00  1906.55  106769.0 2024-01-01
1    GLAND  1915.50  1995.00  1905.30  1977.00  383355.0 2024-01-02
2    GLAND  1982.00  2040.00  1979.00  2031.10  336235.0 2024-01-03
3    GLAND  2043.00  2057.60  1968.40  1975.30  211701.0 2024-01-04
4    GLAND  1986.00  2026.00  1980.00  1989.75  275554.0 2024-01-05
..     ...      ...      ...      ...      ...       ...        ...
216  GLAND  1821.70  1831.90  1750.00  1764.55   87563.0 2024-11-12
217  GLAND  1764.00  1764.75  1696.10  1703.40   97009.0 2024-11-13
218  GLAND  1703.00  1782.95  1703.00  1774.00  150733.0 2024-11-14
219  GLAND  1765.00  1792.45  1726.45  1773.30  103079.0 2024-11-18
220  GLAND  1751.15  1798.10  1751.15  1783.00   68744.0 2024-11-19

[221 rows x 7 columns]
        Symbol    open    high     low   close    volume start_Time
0    KANSAINER  333.40  334.95  331.50  332.50  210502.0 2024-01-01
1    KANSAINER  333.60  339.15  330.65  337.10  512045.0 2024-01-02
2    KANSAINER  337.10  338.70  333.85  335.00  186666.0 2024-01-03
3    KANSAINER  337.00  338.60  332.95  333.55  331706.0 2024-01-04
4    KANSAINER  337.00  339.60  334.05  336.70  339419.0 2024-01-05
..         ...     ...     ...     ...     ...       ...        ...
216  KANSAINER  268.25  274.40  264.50  267.20  257101.0 2024-11-12
217  KANSAINER  265.00  265.95  261.00  262.30  196516.0 2024-11-13
218  KANSAINER  262.00  265.60  257.65  259.25  251207.0 2024-11-14
219  KANSAINER  260.60  265.30  258.55  261.65  188933.0 2024-11-18
220  KANSAINER  263.00  264.60  259.00  261.10  254908.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

     Symbol     open     high      low    close     volume start_Time
0    GRASIM  2136.51  2166.39  2103.64  2118.88   804466.0 2024-01-01
1    GRASIM  2121.47  2121.96  2079.73  2093.13   796768.0 2024-01-02
2    GRASIM  2081.72  2111.60  2057.92  2063.99   971170.0 2024-01-03
3    GRASIM  2081.72  2086.70  2051.24  2062.00   958697.0 2024-01-04
4    GRASIM  2089.69  2090.69  2045.42  2071.27  1084779.0 2024-01-05
..      ...      ...      ...      ...      ...        ...        ...
216  GRASIM  2523.25  2546.25  2510.00  2521.20   520250.0 2024-11-12
217  GRASIM  2521.20  2534.65  2472.05  2502.90  1449201.0 2024-11-13
218  GRASIM  2502.90  2539.00  2490.05  2523.95   581846.0 2024-11-14
219  GRASIM  2497.00  2552.80  2479.05  2517.15  1436348.0 2024-11-18
220  GRASIM  2517.15  2552.00  2500.00  2508.15   424096.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close      volume start_Time
0     GSFC  242.00  283.85  240.85  273.75  34305864.0 2024-01-01
1     GSFC  274.95  293.20  271.00  286.55  33329731.0 2024-01-02
2     GSFC  287.00  291.00  281.45  284.90   8465472.0 2024-01-03
3     GSFC  287.00  303.40  284.70  291.65  12082480.0 2024-01-04
4     GSFC  293.05  293.35  282.75  284.45   5170753.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216   GSFC  200.36  203.23  194.50  195.60    827112.0 2024-11-12
217   GSFC  198.90  202.07  191.80  197.97   4186465.0 2024-11-13
218   GSFC  198.90  201.40  193.26  194.40   1577063.0 2024-11-14
219   GSFC  196.00  196.13  189.40  190.07   1482025.0 2024-11-18
220   GSFC  192.50  195.47  191.49  193.84    951413.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol    open    high     low   close      volume start_Time
0    CASTROLIND  179.75  196.40  178.65  191.70  28004549.0 2024-01-01
1    CASTROLIND  191.70  194.40  184.15  189.00  13613043.0 2024-01-02
2    CASTROLIND  189.90  192.60  186.75  189.30   7466454.0 2024-01-03
3    CASTROLIND  189.00  195.60  189.00  193.25   8817370.0 2024-01-04
4    CASTROLIND  194.10  194.10  186.50  188.25   6203212.0 2024-01-05
..          ...     ...     ...     ...     ...         ...        ...
216  CASTROLIND  205.20  205.89  198.63  199.85   2111211.0 2024-11-12
217  CASTROLIND  197.01  199.44  189.60  190.28   3191152.0 2024-11-13
218  CASTROLIND  191.15  195.89  188.93  190.41   3337322.0 2024-11-14
219  CASTROLIND  191.46  193.34  187.26  189.53   2518456.0 2024-11-18
220  CASTROLIND  191.45  194.26  188.97  190.13   1841083.0 2024-11-19

[221 rows x 7 columns]
        Symbol    open    high     low   close      volume start_Time
0    AMBUJACEM  520.85  539.70  519.80  534.30   4251624.0 2024-01-01
1    AMBUJACEM  537.00  537.00  518.50  530.90   2655551.0 2024-01-02
2    AMBUJACEM  538.45  549.00  528.15  536.10  13711402.0 2024-01-03
3    AMBUJACEM  538.35  554.55  536.75  549.45   6112049.0 2024-01-04
4    AMBUJACEM  550.00  557.90  538.40  542.35   5130749.0 2024-01-05
..         ...     ...     ...     ...     ...         ...        ...
216  AMBUJACEM  561.95  565.50  554.50  556.60    761982.0 2024-11-12
217  AMBUJACEM  554.00  558.25  541.25  545.35    838603.0 2024-11-13
218  AMBUJACEM  545.35  552.30  541.05  544.50   1535042.0 2024-11-14
219  AMBUJACEM  541.00  555.00  537.90  550.55   1707792.0 2024-11-18
220  AMBUJACEM  551.05  560.35  546.90  549.55   1267126.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol     open     high      low    close      volume start_Time
0    HDFCBANK  1706.00  1709.15  1692.00  1698.10   7119843.0 2024-01-01
1    HDFCBANK  1698.80  1702.80  1688.70  1699.10  14621046.0 2024-01-02
2    HDFCBANK  1702.00  1704.70  1668.95  1672.90  14194881.0 2024-01-03
3    HDFCBANK  1678.00  1694.95  1670.70  1690.85  13367028.0 2024-01-04
4    HDFCBANK  1687.15  1704.90  1668.10  1682.20  15944735.0 2024-01-05
..        ...      ...      ...      ...      ...         ...        ...
216  HDFCBANK  1772.00  1775.00  1708.65  1718.20  15697703.0 2024-11-12
217  HDFCBANK  1716.75  1729.40  1673.00  1681.35  17864250.0 2024-11-13
218  HDFCBANK  1673.10  1704.85  1672.10  1692.75  13573235.0 2024-11-14
219  HDFCBANK  1700.00  1718.90  1695.00  1705.10  13540984.0 2024-11-18
220  HDFCBANK  1714.00  1753.75  1702.70  1742.25  25490636.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close    volume start_Time
0      HEG  383.74  389.40  383.74  385.56  303300.0 2024-01-01
1      HEG  386.54  388.68  373.32  377.15  308041.0 2024-01-02
2      HEG  376.97  377.76  370.93  373.12  154146.0 2024-01-03
3      HEG  374.40  381.36  373.32  376.23  269843.0 2024-01-04
4      HEG  377.60  382.50  373.00  374.02  195629.0 2024-01-05
..     ...     ...     ...     ...     ...       ...        ...
216    HEG  429.00  430.90  412.00  416.30  229059.0 2024-11-12
217    HEG  415.50  415.50  398.10  405.15  378786.0 2024-11-13
218    HEG  400.00  415.55  395.15  410.20  252774.0 2024-11-14
219    HEG  410.20  419.85  408.60  418.00  254522.0 2024-11-18
220    HEG  422.20  425.70  407.00  410.50  216824.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close     volume start_Time
0    HEROMOTOCO  4139.55  4181.40  4085.00  4118.55   392408.0 2024-01-01
1    HEROMOTOCO  4114.05  4118.95  4025.20  4088.20   507848.0 2024-01-02
2    HEROMOTOCO  4000.00  4061.95  3971.70  3989.85   896596.0 2024-01-03
3    HEROMOTOCO  3997.50  4006.15  3929.85  3946.95   630734.0 2024-01-04
4    HEROMOTOCO  3960.00  4037.00  3953.75  3990.30   593042.0 2024-01-05
..          ...      ...      ...      ...      ...        ...        ...
216  HEROMOTOCO  4757.50  4796.20  4702.80  4724.20   310558.0 2024-11-12
217  HEROMOTOCO  4691.65  4696.75  4492.00  4519.60  1304908.0 2024-11-13
218  HEROMOTOCO  4519.60  4630.00  4467.00  4604.00   889483.0 2024-11-14
219  HEROMOTOCO  4834.15  4839.95  4714.10  4733.00  1783519.0 2024-11-18
220  HEROMOTOCO  4759.95  4853.95  4734.50  4775.80   704072.0 2024-11-19

[221 rows x 7 columns]
       Symbol    open    high     low   close      volume start_Time
0    HINDALCO  614.50  620.50  606.95  610.40   2961919.0 2024-01-01
1    HINDALCO  610.40  620.00  607.40  617.00   4975013.0 2024-01-02
2    HINDALCO  608.25  611.40  592.00  593.05   7226455.0 2024-01-03
3    HINDALCO  594.00  595.85  587.65  590.50   6592370.0 2024-01-04
4    HINDALCO  590.60  597.60  581.55  587.00   2990123.0 2024-01-05
..        ...     ...     ...     ...     ...         ...        ...
216  HINDALCO  668.00  673.50  648.15  651.65  12009560.0 2024-11-12
217  HINDALCO  648.00  649.90  622.55  626.60   7867492.0 2024-11-13
218  HINDALCO  630.00  636.45  625.15  627.35   6937416.0 2024-11-14
219  HINDALCO  641.90  663.10  639.90  651.05  13618683.0 2024-11-18
220  HINDALCO  651.10  655.55  637.65  640.00   5015887.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close     volume start_Time
0    HINDUNILVR  2663.85  2669.40  2638.00  2654.75   526353.0 2024-01-01
1    HINDUNILVR  2648.00  2653.95  2607.00  2613.80  1310629.0 2024-01-02
2    HINDUNILVR  2599.00  2628.60  2595.55  2606.55  1008270.0 2024-01-03
3    HINDUNILVR  2606.55  2623.00  2588.05  2592.55  1376844.0 2024-01-04
4    HINDUNILVR  2595.00  2629.90  2595.00  2620.05  1150738.0 2024-01-05
..          ...      ...      ...      ...      ...        ...        ...
216  HINDUNILVR  2495.00  2496.95  2456.00  2461.50  1624222.0 2024-11-12
217  HINDUNILVR  2462.10  2472.80  2450.40  2464.95  1262017.0 2024-11-13
218  HINDUNILVR  2460.40  2464.70  2383.70  2389.20  2443393.0 2024-11-14
219  HINDUNILVR  2401.15  2425.00  2375.75  2422.90  1374215.0 2024-11-18
220  HINDUNILVR  2431.90  2440.20  2405.10  2410.35  1133370.0 2024-11-19

[221 rows x 7 columns]
        Symbol    open    high     low   close      volume start_Time
0    HINDPETRO  270.67  271.00  265.40  266.40   5801006.0 2024-01-01
1    HINDPETRO  267.53  274.00  262.07  272.47   8216368.0 2024-01-02
2    HINDPETRO  272.70  282.37  270.33  281.20  13173281.0 2024-01-03
3    HINDPETRO  278.00  278.77  274.70  276.93   7789886.0 2024-01-04
4    HINDPETRO  277.67  284.67  277.47  280.00   9713784.0 2024-01-05
..         ...     ...     ...     ...     ...         ...        ...
216  HINDPETRO  384.10  390.00  374.05  375.55   6589595.0 2024-11-12
217  HINDPETRO  375.00  377.90  367.75  371.40   4346895.0 2024-11-13
218  HINDPETRO  372.50  379.30  365.45  372.40   5809877.0 2024-11-14
219  HINDPETRO  372.40  375.75  366.40  367.30   5010823.0 2024-11-18
220  HINDPETRO  366.00  374.80  360.20  362.15   2933169.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol    open    high     low   close     volume start_Time
0    HINDZINC  318.05  320.80  316.85  318.35   579455.0 2024-01-01
1    HINDZINC  318.35  319.20  312.70  317.30   566897.0 2024-01-02
2    HINDZINC  320.10  322.00  318.10  318.80   787990.0 2024-01-03
3    HINDZINC  318.05  319.90  317.90  318.25   447976.0 2024-01-04
4    HINDZINC  318.00  320.00  315.70  318.50   524841.0 2024-01-05
..        ...     ...     ...     ...     ...        ...        ...
216  HINDZINC  509.00  512.25  498.20  500.70  2222208.0 2024-11-12
217  HINDZINC  497.00  503.15  484.00  485.70  2639677.0 2024-11-13
218  HINDZINC  487.05  497.65  484.75  495.35  1576044.0 2024-11-14
219  HINDZINC  503.60  503.90  494.80  496.35  2851127.0 2024-11-18
220  HINDZINC  500.00  500.40  490.00  492.15  1336754.0 2024-11-19

[221 rows x 7 columns]
     Symbol     open     high      low    close    volume start_Time
0    SANOFI  4679.20  4737.95  4654.85  4711.95  12731.00 2024-01-01
1    SANOFI  4711.95  4885.95  4703.65  4817.05  30020.60 2024-01-02
2    SANOFI  4860.40  4868.20  4802.40  4851.80  30265.45 2024-01-03
3    SANOFI  4851.15  4863.00  4814.60  4849.40   7818.95 2024-01-04
4    SANOFI  4863.30  4895.20  4813.25  4882.00  15108.60 2024-01-05
..      ...      ...      ...      ...      ...       ...        ...
216  SANOFI  6341.65  6429.90  6284.00  6409.00   6203.00 2024-11-12
217  SANOFI  6378.65  6393.95  6168.00  6246.40  20754.00 2024-11-13
218  SANOFI  6237.15  6275.00  6099.00  6179.15  14728.00 2024-11-14
219  SANOFI  6179.15  6335.00  6010.00  6170.95  11923.00 2024-11-18
220  SANOFI  6171.00  6186.70  6115.00  6148.30  11731.00 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol   open   high    low  close      volume start_Time
0     IDBI  67.45  68.65  67.20  67.60   7511625.0 2024-01-01
1     IDBI  67.70  68.40  66.50  67.30   6776439.0 2024-01-02
2     IDBI  67.30  68.55  67.10  67.90   7686164.0 2024-01-03
3     IDBI  68.20  70.50  68.20  69.30  18411053.0 2024-01-04
4     IDBI  69.75  69.95  68.10  68.65   9699095.0 2024-01-05
..     ...    ...    ...    ...    ...         ...        ...
216   IDBI  81.84  82.60  79.50  79.89   4154779.0 2024-11-12
217   IDBI  79.99  80.29  76.51  76.82   5890001.0 2024-11-13
218   IDBI  77.00  78.95  76.77  77.06   4989510.0 2024-11-14
219   IDBI  77.96  77.98  75.60  76.44   5511676.0 2024-11-18
220   IDBI  76.92  80.50  76.90  77.68   7489910.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close     volume start_Time
0      RBA  112.25  115.90  111.70  115.05  4304347.0 2024-01-01
1      RBA  115.10  115.55  111.80  113.45  1611432.0 2024-01-02
2      RBA  113.00  116.45  113.00  113.95  4422926.0 2024-01-03
3      RBA  114.70  115.70  112.55  113.40  2857598.0 2024-01-04
4      RBA  113.80  114.95  112.50  113.45  1394848.0 2024-01-05
..     ...     ...     ...     ...     ...        ...        ...
216    RBA   90.27   90.27   87.15   88.00   763243.0 2024-11-12
217    RBA   88.00   88.00   84.50   84.71  1306680.0 2024-11-13
218    RBA   85.15   86.70   84.36   85.23   974085.0 2024-11-14
219    RBA   86.00   86.37   80.37   81.38  3069371.0 2024-11-18
220    RBA   82.20   82.78   78.11   78.82  2739351.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol    open    high     low   close     volume start_Time
0    ASTERDM  411.85  412.70  400.50  403.95   155897.0 2024-01-01
1    ASTERDM  405.05  413.90  403.30  403.55   972360.0 2024-01-02
2    ASTERDM  401.35  408.95  396.00  398.35   142230.0 2024-01-03
3    ASTERDM  399.80  404.90  398.55  401.60   139146.0 2024-01-04
4    ASTERDM  405.00  430.00  405.00  417.45  1563505.0 2024-01-05
..       ...     ...     ...     ...     ...        ...        ...
216  ASTERDM  439.00  452.85  435.50  438.30  2248490.0 2024-11-12
217  ASTERDM  438.30  441.00  430.10  432.30   566641.0 2024-11-13
218  ASTERDM  435.00  440.95  426.75  430.40   730914.0 2024-11-14
219  ASTERDM  431.00  436.50  427.05  430.35   695554.0 2024-11-18
220  ASTERDM  432.90  440.50  428.10  433.05   420963.0 2024-11-19

[221 rows x 7 columns]
       Symbol    open    high     low   close     volume start_Time
0    INDHOTEL  440.00  441.40  434.45  436.10   928581.0 2024-01-01
1    INDHOTEL  437.00  440.40  429.25  438.20  2850481.0 2024-01-02
2    INDHOTEL  439.25  455.00  438.00  451.45  5554842.0 2024-01-03
3    INDHOTEL  454.85  464.65  451.10  462.80  5215576.0 2024-01-04
4    INDHOTEL  467.00  467.00  453.90  456.05  2712213.0 2024-01-05
..        ...     ...     ...     ...     ...        ...        ...
216  INDHOTEL  730.00  738.25  724.85  730.40  3386712.0 2024-11-12
217  INDHOTEL  722.10  732.65  711.00  714.15  3327567.0 2024-11-13
218  INDHOTEL  714.05  742.75  709.65  741.35  5837816.0 2024-11-14
219  INDHOTEL  742.10  745.35  732.90  737.20  4613449.0 2024-11-18
220  INDHOTEL  742.00  760.95  740.25  754.00  4783332.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol    open    high     low   close      volume start_Time
0    INDIACEM  259.90  263.95  259.40  261.30   3165280.0 2024-01-01
1    INDIACEM  262.00  264.55  255.55  261.05   4017254.0 2024-01-02
2    INDIACEM  261.05  269.50  259.85  262.95   8655812.0 2024-01-03
3    INDIACEM  264.45  277.00  263.25  273.10  11686203.0 2024-01-04
4    INDIACEM  274.85  275.50  262.40  265.45   6123604.0 2024-01-05
..        ...     ...     ...     ...     ...         ...        ...
216  INDIACEM  357.40  361.65  356.50  357.50    785108.0 2024-11-12
217  INDIACEM  357.40  357.40  353.10  354.70    659002.0 2024-11-13
218  INDIACEM  354.10  356.75  351.25  355.30    786013.0 2024-11-14
219  INDIACEM  355.50  357.40  352.10  356.95    485185.0 2024-11-18
220  INDIACEM  357.40  360.45  355.25  356.75    415760.0 2024-11-19

[221 rows x 7 columns]
         Symbol     open     high      low    close    volume start_Time
0    GMMPFAUDLR  1612.00  1624.00  1589.05  1592.75  170413.0 2024-01-01
1    GMMPFAUDLR  1600.00  1614.60  1572.15  1596.40  161512.0 2024-01-02
2    GMMPFAUDLR  1586.00  1603.85  1554.55  1557.55  236204.0 2024-01-03
3    GMMPFAUDLR  1572.00  1588.00  1548.00  1553.65  184728.0 2024-01-04
4    GMMPFAUDLR  1563.00  1588.90  1561.00  1580.50  128396.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  GMMPFAUDLR  1269.75  1292.80  1250.05  1257.65  532329.0 2024-11-12
217  GMMPFAUDLR  1257.05  1257.05  1240.10  1241.95   84781.0 2024-11-13
218  GMMPFAUDLR  1250.85  1262.00  1239.15  1241.05   70014.0 2024-11-14
219  GMMPFAUDLR  1241.05  1242.55  1205.00  1210.05   44836.0 2024-11-18
220  GMMPFAUDLR  1214.25  1224.75  1206.45  1209.90   55147.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol     open     high      low    close    volume start_Time
0    GILLETTE  6500.00  6550.00  6430.00  6475.25   10527.0 2024-01-01
1    GILLETTE  6475.25  6497.80  6350.95  6476.25  109330.0 2024-01-02
2    GILLETTE  6475.00  6688.00  6468.50  6626.95   29016.0 2024-01-03
3    GILLETTE  6650.00  6695.00  6502.60  6549.55   53622.0 2024-01-04
4    GILLETTE  6560.00  6671.75  6551.05  6650.45   14420.0 2024-01-05
..        ...      ...      ...      ...      ...       ...        ...
216  GILLETTE  9605.00  9750.00  9370.95  9411.25   19794.0 2024-11-12
217  GILLETTE  9480.00  9719.25  9248.15  9556.15   31188.0 2024-11-13
218  GILLETTE  9590.50  9877.85  9361.65  9427.15   51977.0 2024-11-14
219  GILLETTE  9438.90  9518.95  9282.55  9481.40   31562.0 2024-11-18
220  GILLETTE  9485.00  9572.50  9250.00  9284.40   23680.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open     high      low    close     volume start_Time
0     INFY  1539.00  1557.00  1535.25  1551.35  2808451.0 2024-01-01
1     INFY  1546.00  1549.15  1523.00  1534.40  5396313.0 2024-01-02
2     INFY  1519.95  1519.95  1488.00  1490.00  7550363.0 2024-01-03
3     INFY  1504.95  1519.75  1492.90  1512.70  7056038.0 2024-01-04
4     INFY  1506.75  1539.70  1506.25  1532.55  8895403.0 2024-01-05
..     ...      ...      ...      ...      ...        ...        ...
216   INFY  1871.10  1881.00  1861.00  1868.80  5012450.0 2024-11-12
217   INFY  1861.10  1873.20  1856.30  1868.40  4257495.0 2024-11-13
218   INFY  1865.60  1876.00  1856.00  1864.55  4311431.0 2024-11-14
219   INFY  1849.20  1849.20  1795.00  1811.45  4839244.0 2024-11-18
220   INFY  1825.50  1859.70  1820.55  1824.75  4669769.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close    volume start_Time
0    TATAINVEST  4320.00  4320.50  4241.40  4258.70   42603.0 2024-01-01
1    TATAINVEST  4272.40  4293.05  4168.40  4211.45   56638.0 2024-01-02
2    TATAINVEST  4240.00  4300.00  4211.45  4253.85   81652.0 2024-01-03
3    TATAINVEST  4270.00  4297.00  4230.00  4244.65   44078.0 2024-01-04
4    TATAINVEST  4268.55  4347.00  4242.85  4290.15  137624.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  TATAINVEST  6879.05  6986.00  6800.00  6899.05   51190.0 2024-11-12
217  TATAINVEST  6899.00  6899.00  6570.05  6620.55   46580.0 2024-11-13
218  TATAINVEST  6636.00  6684.70  6536.05  6611.20   34901.0 2024-11-14
219  TATAINVEST  6640.00  6854.35  6562.75  6661.25   58355.0 2024-11-18
220  TATAINVEST  6699.90  6778.00  6614.75  6646.90   22485.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close      volume start_Time
0      IOC  132.10  132.50  130.00  130.30  18629028.0 2024-01-01
1      IOC  131.00  131.45  128.60  130.55  17271309.0 2024-01-02
2      IOC  130.55  133.85  130.30  132.70  24221613.0 2024-01-03
3      IOC  132.00  132.00  128.80  131.20  23880980.0 2024-01-04
4      IOC  132.80  134.60  131.55  132.70  21903222.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216    IOC  139.60  141.96  138.50  138.79  10561738.0 2024-11-12
217    IOC  138.24  139.30  135.50  135.99  12503679.0 2024-11-13
218    IOC  135.50  136.84  133.75  134.76  17425507.0 2024-11-14
219    IOC  135.13  135.82  133.33  134.14  12693551.0 2024-11-18
220    IOC  134.86  136.68  132.65  133.12  12696762.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close    volume start_Time
0    LINDEINDIA  5660.00  5737.30  5631.25  5666.85   24094.0 2024-01-01
1    LINDEINDIA  5680.00  5680.00  5577.55  5597.35   30235.0 2024-01-02
2    LINDEINDIA  5590.05  5597.35  5505.00  5522.65   54923.0 2024-01-03
3    LINDEINDIA  5523.00  5650.00  5523.00  5614.05   54730.0 2024-01-04
4    LINDEINDIA  5636.95  5638.95  5568.00  5583.00   24724.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  LINDEINDIA  7395.00  7395.00  6888.15  6988.00   66282.0 2024-11-12
217  LINDEINDIA  6918.00  6986.00  6628.10  6687.85  114277.0 2024-11-13
218  LINDEINDIA  6744.80  7000.00  6744.80  6816.95   50974.0 2024-11-14
219  LINDEINDIA  6925.65  6934.00  6520.00  6540.10   61910.0 2024-11-18
220  LINDEINDIA  6605.95  6725.00  6586.20  6637.85   37693.0 2024-11-19

[221 rows x 7 columns]
      Symbol     open     high      low    close     volume start_Time
0    IPCALAB  1104.30  1125.85  1103.95  1119.35   254640.0 2024-01-01
1    IPCALAB  1119.35  1142.90  1110.05  1113.35   443895.0 2024-01-02
2    IPCALAB  1114.90  1122.80  1107.10  1110.25   164353.0 2024-01-03
3    IPCALAB  1110.20  1120.00  1105.15  1109.85   106228.0 2024-01-04
4    IPCALAB  1108.00  1119.00  1092.15  1113.40   190888.0 2024-01-05
..       ...      ...      ...      ...      ...        ...        ...
216  IPCALAB  1539.95  1610.00  1539.95  1559.50   840592.0 2024-11-12
217  IPCALAB  1559.50  1566.90  1492.30  1504.85   368252.0 2024-11-13
218  IPCALAB  1494.95  1557.40  1489.25  1536.55  1239370.0 2024-11-14
219  IPCALAB  1544.10  1595.00  1507.25  1566.70   376265.0 2024-11-18
220  IPCALAB  1557.00  1606.70  1555.85  1574.50   337791.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close      volume start_Time
0      ITC  463.50  469.95  462.65  468.05   9346277.0 2024-01-01
1      ITC  470.00  471.35  463.60  470.35  10519771.0 2024-01-02
2      ITC  470.25  480.70  469.35  477.25  24036012.0 2024-01-03
3      ITC  480.00  481.45  474.20  476.40  11786959.0 2024-01-04
4      ITC  479.40  479.40  472.00  473.95   9209405.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216    ITC  477.60  477.95  471.15  472.85   5041916.0 2024-11-12
217    ITC  470.05  474.70  468.25  472.20  11120381.0 2024-11-13
218    ITC  471.20  472.95  462.25  465.95  11639562.0 2024-11-14
219    ITC  466.00  467.80  462.00  466.55   8135260.0 2024-11-18
220    ITC  468.00  473.75  466.25  467.35   6857374.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close      volume start_Time
0      ITI  305.45  313.95  303.70  307.25   2622245.0 2024-01-01
1      ITI  311.00  322.60  305.60  311.20   5960845.0 2024-01-02
2      ITI  312.00  315.45  307.55  311.80   1897284.0 2024-01-03
3      ITI  313.40  321.00  310.55  313.85   2617339.0 2024-01-04
4      ITI  315.10  319.90  308.00  311.60   2143338.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216    ITI  327.35  344.64  294.61  295.03  42823153.0 2024-11-12
217    ITI  298.01  324.53  285.00  292.39   9936068.0 2024-11-13
218    ITI  299.84  311.75  276.37  291.52  16618080.0 2024-11-14
219    ITI  298.80  309.80  280.01  291.40  12222144.0 2024-11-18
220    ITI  298.00  301.80  287.65  292.18  13041427.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open    high      low    close    volume start_Time
0    JBCHEPHARM  1625.00  1632.0  1605.00  1615.60  126077.0 2024-01-01
1    JBCHEPHARM  1620.00  1678.8  1611.85  1640.70  246969.0 2024-01-02
2    JBCHEPHARM  1640.00  1712.0  1630.00  1700.30  382894.0 2024-01-03
3    JBCHEPHARM  1710.00  1733.4  1591.60  1658.80  291371.0 2024-01-04
4    JBCHEPHARM  1649.80  1699.9  1638.85  1691.45   98406.0 2024-01-05
..          ...      ...     ...      ...      ...       ...        ...
216  JBCHEPHARM  1775.00  1799.0  1762.10  1779.55   74860.0 2024-11-12
217  JBCHEPHARM  1760.00  1775.0  1706.85  1715.45  141857.0 2024-11-13
218  JBCHEPHARM  1700.05  1718.0  1660.00  1681.95  135429.0 2024-11-14
219  JBCHEPHARM  1687.40  1696.6  1666.00  1679.40  136382.0 2024-11-18
220  JBCHEPHARM  1681.05  1705.0  1660.00  1667.05  107426.0 2024-11-19

[221 rows x 7 columns]
         Symbol     open     high      low    close    volume start_Time
0    KAJARIACER  1311.85  1320.10  1301.75  1308.50  121064.0 2024-01-01
1    KAJARIACER  1313.00  1315.00  1282.55  1297.45  655201.0 2024-01-02
2    KAJARIACER  1295.05  1309.15  1289.15  1299.20  346734.0 2024-01-03
3    KAJARIACER  1300.00  1310.00  1295.05  1302.40  505674.0 2024-01-04
4    KAJARIACER  1310.00  1346.70  1310.00  1343.45  345757.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  KAJARIACER  1192.00  1201.05  1162.00  1170.55   45120.0 2024-11-12
217  KAJARIACER  1165.00  1176.45  1136.00  1142.15   61063.0 2024-11-13
218  KAJARIACER  1146.00  1161.10  1136.90  1154.65   50587.0 2024-11-14
219  KAJARIACER  1163.00  1175.00  1125.00  1127.90   69182.0 2024-11-18
220  KAJARIACER  1131.65  1170.70  1131.65  1165.55   42385.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol     open     high      low    close    volume start_Time
0     KPIL   704.30   717.50   694.60   716.15  620474.0 2024-01-01
1     KPIL   717.95   721.20   696.20   700.75  219390.0 2024-01-02
2     KPIL   700.70   716.80   696.55   711.55  329281.0 2024-01-03
3     KPIL   709.00   753.85   706.05   738.80  916722.0 2024-01-04
4     KPIL   738.80   756.00   737.85   752.65  550525.0 2024-01-05
..     ...      ...      ...      ...      ...       ...        ...
216   KPIL  1262.50  1270.75  1235.05  1241.65   64067.0 2024-11-12
217   KPIL  1257.90  1270.20  1180.00  1186.70  201072.0 2024-11-13
218   KPIL  1208.05  1210.10  1183.90  1199.00   89785.0 2024-11-14
219   KPIL  1199.85  1217.80  1186.50  1196.85   89433.0 2024-11-18
220   KPIL  1190.00  1215.00  1188.15  1194.85   78994.0 2024-11-19

[221 rows x 7 columns]
         Symbol    open    high     low   close     volume start_Time
0    KARURVYSYA  171.50  171.90  168.80  170.80  2367444.0 2024-01-01
1    KARURVYSYA  171.90  171.90  166.50  168.00  1924217.0 2024-01-02
2    KARURVYSYA  168.00  170.00  165.75  167.30  1532030.0 2024-01-03
3    KARURVYSYA  167.30  169.25  166.00  166.70   980821.0 2024-01-04
4    KARURVYSYA  167.80  169.00  165.30  166.85  1029824.0 2024-01-05
..          ...     ...     ...     ...     ...        ...        ...
216  KARURVYSYA  226.80  231.00  220.00  222.35  2483384.0 2024-11-12
217  KARURVYSYA  220.90  221.01  210.14  211.51  1637201.0 2024-11-13
218  KARURVYSYA  211.70  215.99  209.20  211.27  1262274.0 2024-11-14
219  KARURVYSYA  214.63  216.82  208.82  212.82  1066872.0 2024-11-18
220  KARURVYSYA  214.00  219.90  213.00  216.88  1342296.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close    volume start_Time
0    CUMMINSIND  1965.00  1974.40  1945.55  1957.95  231172.0 2024-01-01
1    CUMMINSIND  1955.00  1965.55  1927.00  1960.85  383818.0 2024-01-02
2    CUMMINSIND  1960.00  1977.25  1946.00  1971.95  170039.0 2024-01-03
3    CUMMINSIND  1977.10  2007.10  1977.10  1992.70  232609.0 2024-01-04
4    CUMMINSIND  2000.00  2018.00  1986.75  1998.40  240305.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  CUMMINSIND  3601.95  3643.50  3457.00  3480.35  743826.0 2024-11-12
217  CUMMINSIND  3480.35  3495.90  3313.35  3326.05  789671.0 2024-11-13
218  CUMMINSIND  3336.05  3379.00  3273.05  3329.80  709817.0 2024-11-14
219  CUMMINSIND  3300.00  3368.00  3270.20  3352.55  897540.0 2024-11-18
220  CUMMINSIND  3377.00  3406.25  3290.55  3301.25  427254.0 2024-11-19

[221 rows x 7 columns]
        Symbol    open     high      low    close     volume start_Time
0    KOTAKBANK  1909.0  1919.00  1893.10  1909.15  1425902.0 2024-01-01
1    KOTAKBANK  1908.0  1908.00  1860.10  1865.05  5120796.0 2024-01-02
2    KOTAKBANK  1864.0  1870.00  1847.65  1865.90  3781515.0 2024-01-03
3    KOTAKBANK  1871.5  1871.50  1860.55  1863.60  2865766.0 2024-01-04
4    KOTAKBANK  1865.5  1869.90  1841.40  1847.60  7799341.0 2024-01-05
..         ...     ...      ...      ...      ...        ...        ...
216  KOTAKBANK  1744.8  1749.40  1715.20  1721.40  3228390.0 2024-11-12
217  KOTAKBANK  1714.0  1728.15  1679.05  1687.85  3593490.0 2024-11-13
218  KOTAKBANK  1690.0  1712.60  1689.80  1707.90  3327758.0 2024-11-14
219  KOTAKBANK  1714.0  1728.25  1699.70  1722.75  2082415.0 2024-11-18
220  KOTAKBANK  1729.8  1739.80  1713.50  1727.75  2759663.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close    volume start_Time
0      KSB  694.60  697.27  677.50  692.72   17176.0 2024-01-01
1      KSB  687.06  703.20  687.06  700.17   19491.0 2024-01-02
2      KSB  703.59  716.00  690.74  697.07   32526.0 2024-01-03
3      KSB  702.55  703.99  688.81  698.34   17077.0 2024-01-04
4      KSB  702.99  717.80  698.34  707.40   32564.0 2024-01-05
..     ...     ...     ...     ...     ...       ...        ...
216    KSB  820.00  852.25  816.50  825.55  127120.0 2024-11-12
217    KSB  825.00  829.50  790.00  799.05   86260.0 2024-11-13
218    KSB  804.00  825.00  793.75  818.90  121112.0 2024-11-14
219    KSB  810.05  817.35  783.50  798.45  120170.0 2024-11-18
220    KSB  798.45  831.10  797.05  813.65  131454.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open     high      low    close     volume start_Time
0    TRENT  3061.80  3067.00  2995.50  3002.10   421730.0 2024-01-01
1    TRENT  3015.45  3017.90  2940.75  2995.20   408928.0 2024-01-02
2    TRENT  3009.00  3107.90  2988.35  3058.35   714968.0 2024-01-03
3    TRENT  3074.00  3108.45  3060.85  3067.85   299498.0 2024-01-04
4    TRENT  3085.45  3096.55  3045.00  3065.55   258565.0 2024-01-05
..     ...      ...      ...      ...      ...        ...        ...
216  TRENT  6520.00  6717.90  6500.00  6528.55  1258152.0 2024-11-12
217  TRENT  6499.00  6619.70  6412.45  6498.25   758642.0 2024-11-13
218  TRENT  6496.00  6550.30  6367.05  6463.00   620489.0 2024-11-14
219  TRENT  6411.60  6453.00  6275.00  6301.65   828906.0 2024-11-18
220  TRENT  6359.85  6579.90  6359.80  6423.85   674042.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

        Symbol    open    high     low   close     volume start_Time
0    LICHSGFIN  538.30  569.00  538.30  563.05  6193413.0 2024-01-01
1    LICHSGFIN  563.70  568.40  553.25  559.60  2659755.0 2024-01-02
2    LICHSGFIN  560.00  562.55  555.15  557.60  1506526.0 2024-01-03
3    LICHSGFIN  558.95  574.00  554.10  572.00  4223351.0 2024-01-04
4    LICHSGFIN  574.00  585.95  568.30  574.80  3054472.0 2024-01-05
..         ...     ...     ...     ...     ...        ...        ...
216  LICHSGFIN  628.00  638.40  612.55  616.95  2155005.0 2024-11-12
217  LICHSGFIN  615.70  619.35  601.45  606.85  2156821.0 2024-11-13
218  LICHSGFIN  606.85  617.30  605.05  608.15  1130270.0 2024-11-14
219  LICHSGFIN  608.15  618.55  602.00  611.15  1026308.0 2024-11-18
220  LICHSGFIN  614.50  625.40  612.10  616.45  1439885.0 2024-11-19

[221 rows x 7 columns]
         Symbol    open    high     low   close      volume start_Time
0    SWANENERGY  514.00  514.75  505.30  509.85   3015852.0 2024-01-01
1    SWANENERGY  512.00  512.55  496.90  502.05   2372316.0 2024-01-02
2    SWANENERGY  503.90  505.00  497.50  499.40   1437262.0 2024-01-03
3    SWANENERGY  500.95  532.90  500.95  524.40   8723012.0 2024-01-04
4    SWANENERGY  537.00  566.40  530.60  560.25  12859232.0 2024-01-05
..          ...     ...     ...     ...     ...         ...        ...
216  SWANENERGY  530.05  555.55  522.60  536.25   4733745.0 2024-11-12
217  SWANENERGY  530.80  544.70  501.75  506.55   3078510.0 2024-11-13
218  SWANENERGY  510.70  534.00  506.10  510.95   4337575.0 2024-11-14
219  SWANENERGY  484.05  552.70  477.00  545.40  11039748.0 2024-11-18
220  SWANENERGY  550.90  560.00  534.10  539.30   5338981.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol   open   high    low  close      volume start_Time
0    RTNINDIA  76.50  77.80  76.00  76.45   3827836.0 2024-01-01
1    RTNINDIA  76.85  77.40  74.85  76.05   3414673.0 2024-01-02
2    RTNINDIA  76.60  79.40  75.50  75.90   8501455.0 2024-01-03
3    RTNINDIA  76.30  82.40  75.70  81.60  16544967.0 2024-01-04
4    RTNINDIA  81.90  88.00  80.80  86.00  26741331.0 2024-01-05
..        ...    ...    ...    ...    ...         ...        ...
216  RTNINDIA  69.71  72.93  66.73  67.91   8276712.0 2024-11-12
217  RTNINDIA  64.50  66.19  62.02  62.53  10588326.0 2024-11-13
218  RTNINDIA  62.55  63.22  61.11  61.50   4754946.0 2024-11-14
219  RTNINDIA  61.60  62.50  59.84  60.07   3634532.0 2024-11-18
220  RTNINDIA  60.50  66.00  60.50  63.43  19308357.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close       volume start_Time
0     IRFC  100.00  102.40   99.40  100.40  102849848.0 2024-01-01
1     IRFC  101.00  101.65   97.80  100.00   70051082.0 2024-01-02
2     IRFC  100.20  101.95   99.00  100.90   96843171.0 2024-01-03
3     IRFC  101.70  103.60  100.90  101.30   66810041.0 2024-01-04
4     IRFC  101.95  102.45   99.90  100.75   43542157.0 2024-01-05
..     ...     ...     ...     ...     ...          ...        ...
216   IRFC  148.00  150.25  144.61  145.32   13172317.0 2024-11-12
217   IRFC  144.70  145.90  139.30  139.62   16372099.0 2024-11-13
218   IRFC  140.99  142.23  139.50  139.66   14794085.0 2024-11-14
219   IRFC  140.98  141.30  137.80  138.29   13930322.0 2024-11-18
220   IRFC  140.30  146.96  139.83  145.18   36796687.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol     open     high      low    close     volume start_Time
0      M&M  1729.40  1730.00  1699.00  1703.30  1307485.0 2024-01-01
1      M&M  1703.60  1705.00  1649.45  1656.20  2857334.0 2024-01-02
2      M&M  1672.00  1678.20  1648.05  1655.25  1927812.0 2024-01-03
3      M&M  1666.90  1674.45  1638.20  1641.70  2835768.0 2024-01-04
4      M&M  1647.95  1661.50  1636.50  1642.00  1709313.0 2024-01-05
..     ...      ...      ...      ...      ...        ...        ...
216    M&M  2931.20  2945.90  2880.00  2898.55  2414528.0 2024-11-12
217    M&M  2876.00  2895.00  2782.90  2798.95  3949602.0 2024-11-13
218    M&M  2815.00  2842.40  2736.25  2807.20  2478112.0 2024-11-14
219    M&M  2844.00  2874.70  2800.05  2846.90  2405351.0 2024-11-18
220    M&M  2845.00  2998.00  2845.00  2948.95  5230405.0 2024-11-19

[221 rows x 7 columns]
       Symbol     open     high      low    close     volume start_Time
0    RAMCOCEM  1022.00  1031.00  1010.00  1014.35   373757.0 2024-01-01
1    RAMCOCEM  1010.00  1020.80   991.45  1018.75   464522.0 2024-01-02
2    RAMCOCEM  1018.95  1023.70  1002.45  1005.65   439029.0 2024-01-03
3    RAMCOCEM  1008.55  1016.90  1001.15  1012.90   622387.0 2024-01-04
4    RAMCOCEM  1019.90  1030.70  1011.50  1028.10   381271.0 2024-01-05
..        ...      ...      ...      ...      ...        ...        ...
216  RAMCOCEM   888.45   927.00   880.75   910.00  5320024.0 2024-11-12
217  RAMCOCEM   915.00   916.75   877.00   883.90   901771.0 2024-11-13
218  RAMCOCEM   883.90   911.00   878.75   902.35   698690.0 2024-11-14
219  RAMCOCEM   901.10   903.65   889.90   894.15  1207564.0 2024-11-18
220  RAMCOCEM   905.35   925.00   897.85   903.55   930468.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close    volume start_Time
0    INDIGOPNTS  1499.00  1504.95  1488.00  1493.20   32780.0 2024-01-01
1    INDIGOPNTS  1498.90  1500.25  1476.80  1482.15   43154.0 2024-01-02
2    INDIGOPNTS  1470.00  1495.00  1470.00  1490.35   55620.0 2024-01-03
3    INDIGOPNTS  1490.95  1501.95  1488.55  1494.80   80404.0 2024-01-04
4    INDIGOPNTS  1499.00  1502.00  1488.05  1498.75   46966.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  INDIGOPNTS  1487.00  1510.00  1487.00  1499.10  107787.0 2024-11-12
217  INDIGOPNTS  1492.00  1515.20  1476.05  1500.40  134054.0 2024-11-13
218  INDIGOPNTS  1510.20  1540.50  1493.30  1500.15   93795.0 2024-11-14
219  INDIGOPNTS  1500.00  1505.95  1456.85  1502.45  146562.0 2024-11-18
220  INDIGOPNTS  1520.00  1521.85  1494.40  1500.80   64272.0 2024-11-19

[221 rows x 7 columns]
         Symbol    open    high     low   close     volume start_Time
0    CHENNPETRO  705.00  709.00  695.05  704.25   634118.0 2024-01-01
1    CHENNPETRO  704.25  711.00  693.05  708.20   972406.0 2024-01-02
2    CHENNPETRO  713.20  732.65  711.65  723.80  1186962.0 2024-01-03
3    CHENNPETRO  724.00  727.25  710.05  713.50   692125.0 2024-01-04
4    CHENNPETRO  717.80  736.00  712.65  720.80   965900.0 2024-01-05
..          ...     ...     ...     ...     ...        ...        ...
216  CHENNPETRO  632.00  632.10  599.50  602.20  1141701.0 2024-11-12
217  CHENNPETRO  595.00  603.90  578.05  597.20  1721109.0 2024-11-13
218  CHENNPETRO  596.00  597.15  569.00  578.30  2242366.0 2024-11-14
219  CHENNPETRO  579.00  596.25  566.00  569.15  1683496.0 2024-11-18
220  CHENNPETRO  592.00  607.70  575.00  578.90  4011835.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

        Symbol     open     high      low    close    volume start_Time
0    HOMEFIRST   931.00   943.75   927.40   932.35   84437.0 2024-01-01
1    HOMEFIRST   938.00   964.95   921.15   957.80  280010.0 2024-01-02
2    HOMEFIRST   955.00   963.50   944.00   955.35   79189.0 2024-01-03
3    HOMEFIRST   963.05   979.00   936.00   941.75  154023.0 2024-01-04
4    HOMEFIRST   946.70   959.00   938.00   949.60   95585.0 2024-01-05
..         ...      ...      ...      ...      ...       ...        ...
216  HOMEFIRST  1067.30  1085.75  1044.30  1048.15  169573.0 2024-11-12
217  HOMEFIRST  1048.15  1052.75  1017.05  1027.95  314871.0 2024-11-13
218  HOMEFIRST  1029.35  1067.90  1029.35  1049.20   83997.0 2024-11-14
219  HOMEFIRST  1032.10  1054.00  1028.55  1049.20  121927.0 2024-11-18
220  HOMEFIRST  1052.20  1080.00  1036.10  1052.00   97640.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close    volume start_Time
0      VTL  386.10  394.95  386.05  392.90  178750.0 2024-01-01
1      VTL  393.05  394.90  387.00  388.00  127762.0 2024-01-02
2      VTL  391.50  391.50  380.10  382.75  227304.0 2024-01-03
3      VTL  382.75  387.75  381.50  382.80  206398.0 2024-01-04
4      VTL  383.25  385.50  380.10  382.10  141677.0 2024-01-05
..     ...     ...     ...     ...     ...       ...        ...
216    VTL  484.95  486.90  474.40  484.35  193063.0 2024-11-12
217    VTL  476.10  477.35  454.50  462.95  195847.0 2024-11-13
218    VTL  463.10  467.35  452.95  454.10  145107.0 2024-11-14
219    VTL  455.95  458.65  443.05  448.60  130434.0 2024-11-18
220    VTL  449.95  457.50  445.00  448.30   89789.0 2024-11-19

[221 rows x 7 columns]
         Symbol    open    high     low   close    volume start_Time
0    MAHSEAMLES  926.40  928.15  902.60  911.40   93031.0 2024-01-01
1    MAHSEAMLES  907.85  925.00  901.00  904.70  150571.0 2024-01-02
2    MAHSEAMLES  905.00  909.00  893.00  895.55  111054.0 2024-01-03
3    MAHSEAMLES  898.00  914.00  895.05  903.20  130311.0 2024-01-04
4    MAHSEAMLES  904.15  929.90  900.00  925.10  153054.0 2024-01-05
..          ...     ...     ...     ...     ...       ...        ...
216  MAHSEAMLES  619.65  627.70  608.50  612.55  187515.0 2024-11-12
217  MAHSEAMLES  610.75  613.25  598.50  599.95  277924.0 2024-11-13
218  MAHSEAMLES  600.00  616.55  598.25  607.70  131608.0 2024-11-14
219  MAHSEAMLES  606.45  623.55  598.05  610.05  188017.0 2024-11-18
220  MAHSEAMLES  612.85  623.70  606.00  610.40  130981.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

     Symbol     open     high      low    close     volume start_Time
0    MASTEK  2800.00  2805.55  2769.00  2785.80    37873.0 2024-01-01
1    MASTEK  2775.00  2785.95  2679.50  2716.25   102174.0 2024-01-02
2    MASTEK  2689.15  2704.90  2651.00  2662.15   142662.0 2024-01-03
3    MASTEK  2682.00  2700.90  2654.00  2686.40    41174.0 2024-01-04
4    MASTEK  2686.40  2764.90  2673.05  2739.40    59372.0 2024-01-05
..      ...      ...      ...      ...      ...        ...        ...
216  MASTEK  2972.25  3189.90  2955.20  3025.60  1145682.0 2024-11-12
217  MASTEK  3030.00  3100.00  2967.25  3011.60   324972.0 2024-11-13
218  MASTEK  3039.00  3134.05  2976.55  3010.25   312522.0 2024-11-14
219  MASTEK  3031.80  3166.55  2935.50  3134.25   333701.0 2024-11-18
220  MASTEK  3175.50  3261.20  3110.00  3150.90   627683.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol     open     high      low    close     volume start_Time
0     MFSL   957.20   963.40   950.10   955.20   180805.0 2024-01-01
1     MFSL   959.95   959.95   929.45   932.20   554096.0 2024-01-02
2     MFSL   932.20   939.70   926.05   933.05   362277.0 2024-01-03
3     MFSL   938.00   943.40   935.80   939.70   389609.0 2024-01-04
4     MFSL   943.70   950.00   938.15   948.15  1545793.0 2024-01-05
..     ...      ...      ...      ...      ...        ...        ...
216   MFSL  1210.80  1236.95  1207.35  1223.30   931840.0 2024-11-12
217   MFSL  1228.25  1228.25  1191.35  1197.55   306537.0 2024-11-13
218   MFSL  1193.60  1235.15  1193.60  1232.65   873917.0 2024-11-14
219   MFSL  1234.20  1244.25  1215.05  1237.65   963456.0 2024-11-18
220   MFSL  1240.00  1245.05  1180.90  1189.60  1786975.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open     high      low    close     volume start_Time
0      BDL   860.00   873.50   858.50   863.33   487179.0 2024-01-01
1      BDL   867.70   868.40   832.50   835.50   869786.0 2024-01-02
2      BDL   835.63   837.88   815.00   820.45   734685.0 2024-01-03
3      BDL   824.58   862.00   823.98   841.48  1183015.0 2024-01-04
4      BDL   847.50   879.50   847.48   868.65  1789998.0 2024-01-05
..     ...      ...      ...      ...      ...        ...        ...
216    BDL  1040.00  1061.85  1015.90  1028.30   465129.0 2024-11-12
217    BDL  1024.65  1027.95   975.05   979.20   652280.0 2024-11-13
218    BDL   988.00  1011.00   968.30   989.55   577725.0 2024-11-14
219    BDL   999.10  1016.70   890.00   939.65   895260.0 2024-11-18
220    BDL   946.15   999.95   946.15   966.40   931303.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol      open      high       low     close    volume start_Time
0    BOSCHLTD  22301.00  22635.95  22209.25  22433.45   19391.0 2024-01-01
1    BOSCHLTD  22400.00  22469.50  22101.00  22334.35   10969.0 2024-01-02
2    BOSCHLTD  22265.00  22382.40  22133.00  22289.15    6363.0 2024-01-03
3    BOSCHLTD  22289.15  22550.00  22202.55  22488.80   14386.0 2024-01-04
4    BOSCHLTD  22400.05  22819.85  22400.05  22691.65   28782.0 2024-01-05
..        ...       ...       ...       ...       ...       ...        ...
216  BOSCHLTD  35270.00  35347.15  33111.00  33278.50   56027.0 2024-11-12
217  BOSCHLTD  34000.00  34480.00  32830.50  33212.00  124257.0 2024-11-13
218  BOSCHLTD  33500.00  33950.00  33139.60  33862.10   25998.0 2024-11-14
219  BOSCHLTD  33862.10  34421.30  33610.00  33794.30   19760.0 2024-11-18
220  BOSCHLTD  34000.00  34829.40  33894.00  34302.00   23271.0 2024-11-19

[221 rows x 7 columns]
         Symbol    open    high     low   close      volume start_Time
0    BANDHANBNK  244.00  245.20  242.15  244.10   6663982.0 2024-01-01
1    BANDHANBNK  245.65  247.00  239.55  242.35   8517423.0 2024-01-02
2    BANDHANBNK  242.35  258.15  241.00  253.90  33106055.0 2024-01-03
3    BANDHANBNK  255.60  263.10  252.70  260.80  20351416.0 2024-01-04
4    BANDHANBNK  262.80  262.95  248.05  251.70  26254869.0 2024-01-05
..          ...     ...     ...     ...     ...         ...        ...
216  BANDHANBNK  175.31  177.30  172.00  172.59   5526480.0 2024-11-12
217  BANDHANBNK  172.00  172.40  164.20  165.10  14618927.0 2024-11-13
218  BANDHANBNK  165.80  168.75  165.05  167.26  12377786.0 2024-11-14
219  BANDHANBNK  167.30  167.65  164.12  165.69  11130039.0 2024-11-18
220  BANDHANBNK  166.00  172.43  166.00  167.61  10399744.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol      open       high        low      close  volume start_Time
0      MRF  129570.0  130734.35  129000.00  129423.55  9043.0 2024-01-01
1      MRF  129450.0  130269.60  127257.10  129992.30  8846.0 2024-01-02
2      MRF  129740.0  130955.00  129000.00  130595.85  7203.0 2024-01-03
3      MRF  130500.0  131950.00  130149.00  131509.75  6833.0 2024-01-04
4      MRF  131600.0  133500.05  131600.00  132701.25  8182.0 2024-01-05
..     ...       ...        ...        ...        ...     ...        ...
216    MRF  123700.0  124107.70  120717.10  120924.15  8804.0 2024-11-12
217    MRF  120900.0  121659.95  119925.30  120483.70  7941.0 2024-11-13
218    MRF  120400.0  121901.00  120283.00  120551.75  5012.0 2024-11-14
219    MRF  119088.1  121174.65  119024.15  120861.10  6728.0 2024-11-18
220    MRF  120900.0  124194.55  120570.85  122950.60  9833.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close     volume start_Time
0     MRPL  133.40  134.20  132.40  132.75  1384128.0 2024-01-01
1     MRPL  132.60  133.20  128.00  129.55  2836841.0 2024-01-02
2     MRPL  129.65  133.50  129.10  132.75  3009841.0 2024-01-03
3     MRPL  132.75  134.75  131.55  134.25  1880372.0 2024-01-04
4     MRPL  134.30  137.70  133.30  134.15  3528932.0 2024-01-05
..     ...     ...     ...     ...     ...        ...        ...
216   MRPL  159.10  161.55  152.55  153.65  1671520.0 2024-11-12
217   MRPL  151.10  155.31  147.21  152.62  4018132.0 2024-11-13
218   MRPL  149.69  155.40  148.40  149.26  2350584.0 2024-11-14
219   MRPL  150.00  150.67  146.02  147.71  2182084.0 2024-11-18
220   MRPL  150.00  155.38  146.81  147.97  2897145.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol     open     high      low    close     volume start_Time
0      HAL  2805.10  2859.90  2805.10  2826.35  1038164.0 2024-01-01
1      HAL  2829.90  2838.75  2748.45  2791.80  1047639.0 2024-01-02
2      HAL  2763.00  2886.55  2763.00  2870.00  2164728.0 2024-01-03
3      HAL  2876.00  2918.00  2865.35  2904.25  1740167.0 2024-01-04
4      HAL  2980.00  3079.00  2965.10  2998.85  5560237.0 2024-01-05
..     ...      ...      ...      ...      ...        ...        ...
216    HAL  4455.00  4469.00  4221.00  4243.50  1366992.0 2024-11-12
217    HAL  4220.00  4220.00  4045.55  4066.90  2076393.0 2024-11-13
218    HAL  4080.00  4185.00  3920.35  4087.05  3878379.0 2024-11-14
219    HAL  4189.95  4248.00  4060.05  4077.85  1939714.0 2024-11-18
220    HAL  4100.00  4148.70  4040.00  4057.15  1425438.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close      volume start_Time
0      NCC  167.25  169.70  166.00  166.55   2716433.0 2024-01-01
1      NCC  166.55  168.30  164.60  166.90   2560716.0 2024-01-02
2      NCC  167.00  172.20  166.50  170.65   7099867.0 2024-01-03
3      NCC  171.90  177.00  170.50  175.75  11013894.0 2024-01-04
4      NCC  177.20  178.40  172.30  174.50   5095188.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216    NCC  303.70  306.10  292.00  296.20   2713526.0 2024-11-12
217    NCC  293.70  293.80  278.35  279.65   2829137.0 2024-11-13
218    NCC  279.95  284.80  277.35  280.00   1771988.0 2024-11-14
219    NCC  279.95  279.95  271.10  277.65   2106803.0 2024-11-18
220    NCC  277.60  287.30  276.90  279.35   2132933.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol     open     high      low    close     volume start_Time
0      PEL   930.00   947.10   925.00   934.20  1044566.0 2024-01-01
1      PEL   938.90   941.80   918.60   935.20  1027809.0 2024-01-02
2      PEL   933.40   944.90   930.10   935.40   837162.0 2024-01-03
3      PEL   935.80   960.00   931.80   950.90  1919378.0 2024-01-04
4      PEL   953.95   961.60   925.00   939.70  1236884.0 2024-01-05
..     ...      ...      ...      ...      ...        ...        ...
216    PEL  1037.00  1046.90  1016.95  1023.15   447763.0 2024-11-12
217    PEL  1020.00  1023.85   994.05  1012.30   943984.0 2024-11-13
218    PEL  1008.90  1056.95  1003.65  1044.25   961682.0 2024-11-14
219    PEL  1033.15  1059.95  1014.30  1048.55  1000482.0 2024-11-18
220    PEL  1051.15  1090.10  1051.15  1060.20  1650687.0 2024-11-19

[221 rows x 7 columns]
      Symbol    open    high     low   close      volume start_Time
0    RAILTEL  340.90  371.15  339.95  353.05  31508799.0 2024-01-01
1    RAILTEL  355.15  363.90  345.35  353.95  12587553.0 2024-01-02
2    RAILTEL  354.00  374.00  349.20  363.25  15491354.0 2024-01-03
3    RAILTEL  366.00  369.70  353.00  355.25  10470903.0 2024-01-04
4    RAILTEL  357.40  361.00  347.70  355.85   4043982.0 2024-01-05
..       ...     ...     ...     ...     ...         ...        ...
216  RAILTEL  399.00  406.95  390.00  390.75   1066766.0 2024-11-12
217  RAILTEL  389.05  392.60  373.60  375.25   1404290.0 2024-11-13
218  RAILTEL  376.15  381.70  371.10  372.20   1022050.0 2024-11-14
219  RAILTEL  372.20  376.45  362.20  366.20   1135038.0 2024-11-18
220  RAILTEL  371.05  384.90  369.90  374.45   1628549.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close      volume start_Time
0     ONGC  206.00  207.10  204.75  205.35   4820168.0 2024-01-01
1     ONGC  205.35  210.75  203.65  207.05  21141219.0 2024-01-02
2     ONGC  205.50  210.45  204.50  208.25  11650902.0 2024-01-03
3     ONGC  210.50  215.40  209.30  214.65  31054419.0 2024-01-04
4     ONGC  215.45  217.50  213.05  216.45  20743811.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216   ONGC  260.85  263.20  255.40  256.15  22445400.0 2024-11-12
217   ONGC  256.15  256.95  249.00  252.55  17483332.0 2024-11-13
218   ONGC  252.55  254.30  249.00  250.80  12454540.0 2024-11-14
219   ONGC  251.10  252.10  247.10  250.65  14636541.0 2024-11-18
220   ONGC  250.00  255.40  247.10  248.00  17397559.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close    volume start_Time
0     ISEC  720.00  721.85  706.20  709.95  230557.0 2024-01-01
1     ISEC  711.05  723.30  708.35  719.95  191443.0 2024-01-02
2     ISEC  715.00  721.95  706.05  720.40  146327.0 2024-01-03
3     ISEC  723.05  732.35  719.90  725.95  115306.0 2024-01-04
4     ISEC  729.70  762.00  727.40  757.45  811937.0 2024-01-05
..     ...     ...     ...     ...     ...       ...        ...
216   ISEC  842.00  858.35  840.80  842.65   90408.0 2024-11-12
217   ISEC  845.00  850.80  838.10  841.00  386558.0 2024-11-13
218   ISEC  841.40  849.15  828.00  843.65  121996.0 2024-11-14
219   ISEC  829.10  845.95  829.10  841.55  101861.0 2024-11-18
220   ISEC  836.20  846.95  833.20  839.55  123910.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol      open      high       low     close   volume start_Time
0     PGHH  17377.55  17552.45  17253.05  17356.90   4860.0 2024-01-01
1     PGHH  17374.30  17414.90  17155.10  17368.80   3836.0 2024-01-02
2     PGHH  17373.45  17378.70  16987.00  17075.35  22494.0 2024-01-03
3     PGHH  17399.95  17399.95  17001.85  17094.35   4660.0 2024-01-04
4     PGHH  17198.95  17348.90  17010.00  17234.60   5049.0 2024-01-05
..     ...       ...       ...       ...       ...      ...        ...
216   PGHH  15500.00  15839.70  15401.00  15648.90  40582.0 2024-11-12
217   PGHH  15510.00  15792.95  15346.00  15534.95  28976.0 2024-11-13
218   PGHH  15550.00  15839.95  15450.00  15704.00  11048.0 2024-11-14
219   PGHH  15704.00  15895.00  15540.20  15698.55   3014.0 2024-11-18
220   PGHH  15711.45  15848.95  15632.15  15800.40   2521.0 2024-11-19

[221 rows x 7 columns]
        Symbol    open    high     low   close      volume start_Time
0    LEMONTREE  119.90  120.75  118.50  118.70   1627367.0 2024-01-01
1    LEMONTREE  121.25  133.70  121.00  129.85  80174681.0 2024-01-02
2    LEMONTREE  132.00  135.80  127.50  128.90  21584469.0 2024-01-03
3    LEMONTREE  130.00  132.50  129.00  129.60  10193376.0 2024-01-04
4    LEMONTREE  130.55  131.90  128.40  129.35   4645556.0 2024-01-05
..         ...     ...     ...     ...     ...         ...        ...
216  LEMONTREE  125.35  125.35  120.71  121.63   4165472.0 2024-11-12
217  LEMONTREE  120.41  120.79  115.67  118.16   3875253.0 2024-11-13
218  LEMONTREE  118.23  122.79  117.21  121.76   6078884.0 2024-11-14
219  LEMONTREE  123.00  123.40  118.52  121.53   5343798.0 2024-11-18
220  LEMONTREE  123.96  123.96  120.50  121.64   6196498.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close     volume start_Time
0     PCBL  251.75  256.50  251.10  255.60  1126270.0 2024-01-01
1     PCBL  257.00  261.70  252.60  256.80  1733874.0 2024-01-02
2     PCBL  257.00  257.95  253.30  254.60   860445.0 2024-01-03
3     PCBL  255.45  259.40  253.50  255.20  1046522.0 2024-01-04
4     PCBL  256.15  266.00  255.55  262.70  5159414.0 2024-01-05
..     ...     ...     ...     ...     ...        ...        ...
216   PCBL  415.00  424.90  401.50  404.45  1316916.0 2024-11-12
217   PCBL  399.05  405.90  383.00  385.15  2679055.0 2024-11-13
218   PCBL  385.00  402.85  385.00  392.95  1579226.0 2024-11-14
219   PCBL  393.95  397.80  384.45  386.25   973005.0 2024-11-18
220   PCBL  386.50  404.85  386.50  390.00  1287062.0 2024-11-19

[221 rows x 7 columns]
         Symbol     open     high      low    close    volume start_Time
0    PIDILITIND  2737.10  2737.10  2693.45  2697.50  130958.0 2024-01-01
1    PIDILITIND  2695.00  2749.00  2661.50  2737.70  267832.0 2024-01-02
2    PIDILITIND  2749.00  2792.00  2728.05  2772.25  347830.0 2024-01-03
3    PIDILITIND  2778.00  2790.30  2750.30  2769.05  300002.0 2024-01-04
4    PIDILITIND  2765.55  2769.05  2714.40  2722.60  377109.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  PIDILITIND  3102.00  3120.85  3032.55  3040.30  201463.0 2024-11-12
217  PIDILITIND  3025.00  3038.30  2968.30  2988.55  193385.0 2024-11-13
218  PIDILITIND  3000.00  3039.95  2969.65  3021.70  299390.0 2024-11-14
219  PIDILITIND  3075.00  3075.30  3007.05  3019.30  292227.0 2024-11-18
220  PIDILITIND  3009.30  3031.55  2981.55  3001.90  184764.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol    open    high     low   close    volume start_Time
0    PRAJIND  560.00  562.90  555.35  556.55  385363.0 2024-01-01
1    PRAJIND  556.55  559.60  544.85  547.90  797897.0 2024-01-02
2    PRAJIND  547.90  558.00  546.10  551.25  555369.0 2024-01-03
3    PRAJIND  553.40  555.10  550.25  552.65  399653.0 2024-01-04
4    PRAJIND  557.50  561.20  545.95  548.20  842720.0 2024-01-05
..       ...     ...     ...     ...     ...       ...        ...
216  PRAJIND  706.00  711.10  696.00  697.20  424127.0 2024-11-12
217  PRAJIND  694.00  694.00  665.55  675.40  511419.0 2024-11-13
218  PRAJIND  675.95  692.00  666.00  689.70  611855.0 2024-11-14
219  PRAJIND  689.70  707.00  682.05  697.15  436297.0 2024-11-18
220  PRAJIND  706.35  716.85  691.75  694.85  273514.0 2024-11-19

[221 rows x 7 columns]
       Symbol     open     high      low    close    volume start_Time
0    MTARTECH  2209.00  2228.00  2191.00  2202.35  171546.0 2024-01-01
1    MTARTECH  2202.35  2218.80  2170.00  2180.10  174301.0 2024-01-02
2    MTARTECH  2180.00  2204.95  2156.20  2185.40  186547.0 2024-01-03
3    MTARTECH  2196.90  2207.00  2181.00  2188.70  106199.0 2024-01-04
4    MTARTECH  2198.00  2212.60  2175.05  2191.10  126143.0 2024-01-05
..        ...      ...      ...      ...      ...       ...        ...
216  MTARTECH  1621.10  1622.95  1563.05  1586.60   95192.0 2024-11-12
217  MTARTECH  1575.00  1609.85  1530.55  1559.85  130433.0 2024-11-13
218  MTARTECH  1560.00  1600.00  1551.65  1572.25   98587.0 2024-11-14
219  MTARTECH  1599.90  1652.95  1557.00  1614.25  206171.0 2024-11-18
220  MTARTECH  1624.70  1775.00  1619.30  1743.30  870683.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol    open    high     low   close     volume start_Time
0    PRSMJOHNSN  184.00  189.90  183.65  184.35   801146.0 2024-01-01
1    PRSMJOHNSN  185.90  185.95  181.50  182.25   202407.0 2024-01-02
2    PRSMJOHNSN  182.40  183.90  178.60  181.30   447397.0 2024-01-03
3    PRSMJOHNSN  182.65  184.70  180.90  183.20   727146.0 2024-01-04
4    PRSMJOHNSN  182.50  186.50  182.50  183.80   282993.0 2024-01-05
..          ...     ...     ...     ...     ...        ...        ...
216  PRSMJOHNSN  185.00  188.80  180.20  186.40   908033.0 2024-11-12
217  PRSMJOHNSN  186.02  192.00  181.26  187.58  1729334.0 2024-11-13
218  PRSMJOHNSN  181.90  189.40  181.76  184.30   751843.0 2024-11-14
219  PRSMJOHNSN  184.00  184.30  181.96  182.43   262441.0 2024-11-18
220  PRSMJOHNSN  182.05  185.00  181.61  182.44   355255.0 2024-11-19

[221 rows x 7 columns]
         Symbol    open    high     low   close    volume start_Time
0    JUBLINGREA  512.20  516.85  505.00  509.65  251387.0 2024-01-01
1    JUBLINGREA  510.80  510.80  491.25  496.95  326642.0 2024-01-02
2    JUBLINGREA  495.00  502.80  490.50  493.05  196570.0 2024-01-03
3    JUBLINGREA  495.00  504.00  493.50  499.80  391430.0 2024-01-04
4    JUBLINGREA  501.00  505.45  494.90  499.60  312406.0 2024-01-05
..          ...     ...     ...     ...     ...       ...        ...
216  JUBLINGREA  699.55  711.00  681.15  683.55  119579.0 2024-11-12
217  JUBLINGREA  686.30  686.30  661.55  665.30  169845.0 2024-11-13
218  JUBLINGREA  662.00  678.80  653.05  656.60  239730.0 2024-11-14
219  JUBLINGREA  650.00  664.50  642.00  656.30  152348.0 2024-11-18
220  JUBLINGREA  664.95  683.50  659.05  663.35  217439.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol   open   high    low  close      volume start_Time
0    EASEMYTRIP  40.55  41.35  40.15  40.70  22465247.0 2024-01-01
1    EASEMYTRIP  40.95  41.25  39.70  40.45  20404935.0 2024-01-02
2    EASEMYTRIP  40.45  41.15  40.00  40.95  26996483.0 2024-01-03
3    EASEMYTRIP  41.30  41.60  40.75  40.85  24828893.0 2024-01-04
4    EASEMYTRIP  41.10  41.70  40.45  41.40  39031119.0 2024-01-05
..          ...    ...    ...    ...    ...         ...        ...
216  EASEMYTRIP  31.55  32.18  31.07  31.27   6300090.0 2024-11-12
217  EASEMYTRIP  31.39  31.39  29.96  30.03   9094352.0 2024-11-13
218  EASEMYTRIP  30.39  30.56  29.92  30.10   7607757.0 2024-11-14
219  EASEMYTRIP  29.70  30.58  29.05  29.95  11989732.0 2024-11-18
220  EASEMYTRIP  30.10  30.95  30.01  30.16   8716975.0 2024-11-19

[221 rows x 7 columns]
     Symbol     open     high      low    close    volume start_Time
0    ANURAS  1050.00  1080.00  1044.75  1072.50  427842.0 2024-01-01
1    ANURAS  1075.00  1099.80  1061.05  1095.65  415086.0 2024-01-02
2    ANURAS  1097.10  1104.40  1069.10  1091.05  338019.0 2024-01-03
3    ANURAS  1100.00  1106.30  1062.00  1068.35  257975.0 2024-01-04
4    ANURAS  1072.95  1079.60  1052.00  1070.80  108094.0 2024-01-05
..      ...      ...      ...      ...      ...       ...        ...
216  ANURAS   736.00   741.85   727.45   729.35   93667.0 2024-11-12
217  ANURAS   729.00   729.00   702.00   723.30  104354.0 2024-11-13
218  ANURAS   722.25   743.30   707.90   734.85  113909.0 2024-11-14
219  ANURAS   728.00   730.80   710.25   715.10  146158.0 2024-11-18
220  ANURAS   717.60   738.90   716.40   731.55   71444.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

     Symbol    open    high     low   close     volume start_Time
0    LXCHEM  290.25  294.75  290.20  291.95   723592.0 2024-01-01
1    LXCHEM  292.80  295.25  284.65  288.25  1086160.0 2024-01-02
2    LXCHEM  288.10  289.85  285.00  285.65   478072.0 2024-01-03
3    LXCHEM  286.70  296.90  286.00  293.90  1960979.0 2024-01-04
4    LXCHEM  294.15  296.20  287.30  288.95   947874.0 2024-01-05
..      ...     ...     ...     ...     ...        ...        ...
216  LXCHEM  263.70  266.80  258.30  259.90   410475.0 2024-11-12
217  LXCHEM  259.00  260.50  250.10  251.20   555193.0 2024-11-13
218  LXCHEM  251.20  258.85  251.10  254.00   357719.0 2024-11-14
219  LXCHEM  254.65  256.90  249.05  254.10   463515.0 2024-11-18
220  LXCHEM  254.15  259.15  250.00  251.80   355853.0 2024-11-19

[221 rows x 7 columns]
        Symbol     open     high      low    close    volume start_Time
0    CRAFTSMAN  5406.25  5441.45  5305.00  5339.35   13491.0 2024-01-01
1    CRAFTSMAN  5366.05  5366.05  5202.20  5234.55   20890.0 2024-01-02
2    CRAFTSMAN  5258.10  5273.55  5121.00  5143.25   29737.0 2024-01-03
3    CRAFTSMAN  5169.95  5169.95  5035.10  5060.20   35282.0 2024-01-04
4    CRAFTSMAN  5119.95  5119.95  4973.55  4998.80   43847.0 2024-01-05
..         ...      ...      ...      ...      ...       ...        ...
216  CRAFTSMAN  5006.85  5064.00  4965.00  4988.15    9468.0 2024-11-12
217  CRAFTSMAN  4960.00  4975.05  4654.00  4670.50   42940.0 2024-11-13
218  CRAFTSMAN  4750.00  4820.10  4651.50  4690.65   28030.0 2024-11-14
219  CRAFTSMAN  4751.15  4780.00  4602.40  4659.85   21339.0 2024-11-18
220  CRAFTSMAN  4620.00  5072.45  4620.00  5009.25  131886.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol     open     high      low    close    volume start_Time
0    RAYMOND  1044.16  1053.19  1041.74  1050.23   94041.0 2024-01-01
1    RAYMOND  1056.84  1058.35  1032.96  1038.24  108711.0 2024-01-02
2    RAYMOND  1038.24  1044.46  1029.67  1031.87  112487.0 2024-01-03
3    RAYMOND  1043.10  1067.11  1031.87  1052.80  463023.0 2024-01-04
4    RAYMOND  1055.18  1071.55  1039.93  1050.53  280401.0 2024-01-05
..       ...      ...      ...      ...      ...       ...        ...
216  RAYMOND  1578.00  1600.75  1550.00  1557.85  142678.0 2024-11-12
217  RAYMOND  1557.85  1575.00  1495.00  1497.85  138566.0 2024-11-13
218  RAYMOND  1498.00  1521.55  1488.05  1504.70   87800.0 2024-11-14
219  RAYMOND  1507.00  1533.95  1456.05  1465.60  163509.0 2024-11-18
220  RAYMOND  1474.85  1501.00  1457.05  1482.40  156324.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close      volume start_Time
0      RCF  160.20  171.40  160.15  167.35  30315307.0 2024-01-01
1      RCF  168.00  176.55  166.75  170.05  27441070.0 2024-01-02
2      RCF  169.95  173.40  166.10  171.65  10542307.0 2024-01-03
3      RCF  174.35  176.40  170.60  171.55  10158400.0 2024-01-04
4      RCF  172.15  172.55  165.10  167.90   5465038.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216    RCF  162.55  165.52  156.10  159.56    972579.0 2024-11-12
217    RCF  157.60  158.46  151.75  152.48   1391908.0 2024-11-13
218    RCF  156.70  160.71  152.72  155.94   4362609.0 2024-11-14
219    RCF  155.00  156.80  151.41  152.41   1764259.0 2024-11-18
220    RCF  153.85  156.72  152.25  152.63   1328264.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol     open     high      low    close      volume start_Time
0    RELIANCE  1290.28  1303.43  1286.58  1295.13   2015270.0 2024-01-01
1    RELIANCE  1292.50  1307.50  1286.50  1305.85   3724400.0 2024-01-02
2    RELIANCE  1305.00  1317.00  1288.60  1291.65   4518768.0 2024-01-03
3    RELIANCE  1294.00  1304.93  1289.55  1298.33   4806389.0 2024-01-04
4    RELIANCE  1301.45  1309.93  1299.00  1303.85   4043203.0 2024-01-05
..        ...      ...      ...      ...      ...         ...        ...
216  RELIANCE  1275.55  1289.30  1267.50  1274.25  10671091.0 2024-11-12
217  RELIANCE  1270.25  1275.45  1249.50  1252.05  14633633.0 2024-11-13
218  RELIANCE  1253.60  1272.60  1251.10  1267.60  12612633.0 2024-11-14
219  RELIANCE  1267.60  1272.90  1243.90  1260.75  13620611.0 2024-11-18
220  RELIANCE  1260.75  1281.50  1235.15  1241.65  14183746.0 2024-11-19

[221 rows x 7 columns]
         Symbol    open    high     low   close     volume start_Time
0    KALYANKJIL  355.15  364.90  351.05  362.30  2369504.0 2024-01-01
1    KALYANKJIL  362.25  370.00  351.45  362.70  4853351.0 2024-01-02
2    KALYANKJIL  363.05  366.60  355.60  359.60  1674304.0 2024-01-03
3    KALYANKJIL  361.00  364.95  355.35  363.80  1562063.0 2024-01-04
4    KALYANKJIL  370.00  379.75  350.10  357.75  5025301.0 2024-01-05
..          ...     ...     ...     ...     ...        ...        ...
216  KALYANKJIL  705.00  719.45  695.60  704.30  4319306.0 2024-11-12
217  KALYANKJIL  703.95  709.55  665.00  670.45  6086731.0 2024-11-13
218  KALYANKJIL  664.95  694.50  642.65  653.90  9828648.0 2024-11-14
219  KALYANKJIL  656.00  675.40  654.10  668.25  6958109.0 2024-11-18
220  KALYANKJIL  674.00  707.00  670.35  701.35  7435686.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close      volume start_Time
0     SAIL  123.65  126.90  122.65  124.70  37525817.0 2024-01-01
1     SAIL  124.65  124.65  120.25  123.00  38718627.0 2024-01-02
2     SAIL  122.40  122.70  118.70  119.10  30459539.0 2024-01-03
3     SAIL  119.25  120.70  118.25  118.65  21439561.0 2024-01-04
4     SAIL  119.50  120.75  115.70  116.95  22784093.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216   SAIL  116.00  117.40  113.66  114.17  14476729.0 2024-11-12
217   SAIL  113.10  114.49  111.00  111.69  24360081.0 2024-11-13
218   SAIL  111.69  114.38  111.43  111.84  15061567.0 2024-11-14
219   SAIL  112.20  115.11  111.26  112.77  17936991.0 2024-11-18
220   SAIL  113.15  114.45  111.08  111.45  11670566.0 2024-11-19

[221 rows x 7 columns]
        Symbol    open    high     low   close     volume start_Time
0    JINDALSAW  206.03  212.83  202.00  211.08  1587727.0 2024-01-01
1    JINDALSAW  213.00  223.00  213.00  221.30  3006645.0 2024-01-02
2    JINDALSAW  224.03  226.28  217.58  225.20  1623994.0 2024-01-03
3    JINDALSAW  225.50  228.53  222.50  223.85  1113201.0 2024-01-04
4    JINDALSAW  225.00  229.35  221.20  224.80  1332991.0 2024-01-05
..         ...     ...     ...     ...     ...        ...        ...
216  JINDALSAW  307.00  312.00  301.50  302.85   758565.0 2024-11-12
217  JINDALSAW  300.25  303.85  287.50  288.55  1179382.0 2024-11-13
218  JINDALSAW  292.05  298.90  287.55  295.00   939362.0 2024-11-14
219  JINDALSAW  299.00  308.45  295.25  303.65  1418077.0 2024-11-18
220  JINDALSAW  305.10  309.70  298.15  300.95   546196.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close      volume start_Time
0     SBIN  642.20  646.90  638.00  641.35   8295548.0 2024-01-01
1     SBIN  641.35  648.00  633.85  639.45  15164482.0 2024-01-02
2     SBIN  639.35  648.00  635.80  643.45  14571772.0 2024-01-03
3     SBIN  642.50  646.40  638.65  642.75  13883388.0 2024-01-04
4     SBIN  645.00  651.75  637.75  641.95  15984585.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216   SBIN  852.50  853.40  824.30  826.70  11350729.0 2024-11-12
217   SBIN  823.35  831.75  804.65  808.65  13756706.0 2024-11-13
218   SBIN  808.65  818.00  801.05  804.25   9461484.0 2024-11-14
219   SBIN  811.00  816.70  799.25  814.30   9322451.0 2024-11-18
220   SBIN  819.00  820.30  800.10  803.00  13677029.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close      volume start_Time
0     VEDL  258.55  260.30  256.00  257.15   6352734.0 2024-01-01
1     VEDL  257.50  259.40  253.10  258.15   5803881.0 2024-01-02
2     VEDL  258.50  267.25  255.85  263.80  22285124.0 2024-01-03
3     VEDL  270.00  270.65  265.35  266.15  10745140.0 2024-01-04
4     VEDL  266.15  271.25  263.10  265.85  12327980.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216   VEDL  456.20  458.85  443.05  444.75   8421968.0 2024-11-12
217   VEDL  444.00  445.40  432.30  434.75   7960930.0 2024-11-13
218   VEDL  435.00  439.90  430.25  433.40   7028180.0 2024-11-14
219   VEDL  444.35  459.40  439.05  447.50  13385897.0 2024-11-18
220   VEDL  449.00  451.50  441.15  443.55   5930593.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol      open      high       low     close   volume start_Time
0    SHREECEM  28750.00  28750.00  28351.00  28461.60   5760.0 2024-01-01
1    SHREECEM  28610.00  28610.00  27950.00  28088.55  16850.0 2024-01-02
2    SHREECEM  28088.55  28435.00  28020.40  28221.75   9011.0 2024-01-03
3    SHREECEM  28440.00  28498.00  28175.00  28357.90  14453.0 2024-01-04
4    SHREECEM  28200.00  28250.05  26931.35  27023.30  78459.0 2024-01-05
..        ...       ...       ...       ...       ...      ...        ...
216  SHREECEM  23500.00  24470.85  23500.00  24372.80  84516.0 2024-11-12
217  SHREECEM  24300.20  24300.20  23925.60  24049.20  34750.0 2024-11-13
218  SHREECEM  24049.20  24238.35  23670.05  24091.70  40911.0 2024-11-14
219  SHREECEM  23984.90  24182.40  23836.85  23935.05   8464.0 2024-11-18
220  SHREECEM  23935.00  24356.75  23850.10  24106.35  61232.0 2024-11-19

[221 rows x 7 columns]
        Symbol    open    high     low   close     volume start_Time
0    BORORENEW  439.90  443.45  437.00  438.70   216085.0 2024-01-01
1    BORORENEW  438.70  441.65  429.30  431.60   257584.0 2024-01-02
2    BORORENEW  433.45  470.00  430.20  466.00  2590204.0 2024-01-03
3    BORORENEW  475.00  493.45  471.05  485.90  3911784.0 2024-01-04
4    BORORENEW  488.55  492.75  472.05  482.45   971154.0 2024-01-05
..         ...     ...     ...     ...     ...        ...        ...
216  BORORENEW  494.95  496.95  465.10  470.15   739386.0 2024-11-12
217  BORORENEW  462.50  469.40  440.00  442.00   390310.0 2024-11-13
218  BORORENEW  442.75  453.10  440.30  442.40   245566.0 2024-11-14
219  BORORENEW  441.35  441.40  429.40  434.00   189150.0 2024-11-18
220  BORORENEW  435.15  449.45  435.15  439.65   204938.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol     open     high      low    close    volume start_Time
0    SIEMENS  4029.00  4058.00  4009.00  4025.55  127992.0 2024-01-01
1    SIEMENS  4045.05  4049.00  3966.70  4041.60  210466.0 2024-01-02
2    SIEMENS  4055.00  4110.00  4054.15  4085.15  347303.0 2024-01-03
3    SIEMENS  4102.00  4127.10  4076.55  4088.65  221232.0 2024-01-04
4    SIEMENS  4099.15  4114.55  4057.00  4077.20  140037.0 2024-01-05
..       ...      ...      ...      ...      ...       ...        ...
216  SIEMENS  7059.95  7097.75  6777.00  6799.45  223437.0 2024-11-12
217  SIEMENS  6799.55  6825.00  6645.05  6704.55  214678.0 2024-11-13
218  SIEMENS  6704.00  6767.85  6586.25  6736.85  254611.0 2024-11-14
219  SIEMENS  6825.00  6836.35  6612.10  6640.20  141436.0 2024-11-18
220  SIEMENS  6683.00  6787.80  6629.55  6645.65  221623.0 2024-11-19

[221 rows x 7 columns]
       Symbol     open    high      low    close    volume start_Time
0    SKFINDIA  4618.85  4642.9  4583.00  4600.90   32986.0 2024-01-01
1    SKFINDIA  4601.00  4640.0  4497.00  4520.80   35176.0 2024-01-02
2    SKFINDIA  4542.50  4584.9  4535.00  4551.20    9738.0 2024-01-03
3    SKFINDIA  4575.20  4595.0  4515.05  4539.30   12148.0 2024-01-04
4    SKFINDIA  4540.00  4608.4  4530.80  4589.70   18088.0 2024-01-05
..        ...      ...     ...      ...      ...       ...        ...
216  SKFINDIA  5126.20  5126.2  5009.00  5031.70   15847.0 2024-11-12
217  SKFINDIA  5011.70  5044.3  4852.00  4880.30   31736.0 2024-11-13
218  SKFINDIA  4800.00  4840.0  4400.00  4518.55  294484.0 2024-11-14
219  SKFINDIA  4489.40  4489.4  4334.00  4439.70  136927.0 2024-11-18
220  SKFINDIA  4463.10  4769.0  4442.45  4662.10  103035.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol     open     high      low    close     volume start_Time
0    GODREJCP  1134.80  1149.15  1127.45  1144.80   686392.0 2024-01-01
1    GODREJCP  1149.00  1162.00  1136.30  1159.15  1201742.0 2024-01-02
2    GODREJCP  1159.00  1173.50  1155.00  1168.10  1503336.0 2024-01-03
3    GODREJCP  1168.10  1207.35  1167.05  1202.00  1531104.0 2024-01-04
4    GODREJCP  1202.00  1230.00  1178.20  1219.85  2079251.0 2024-01-05
..        ...      ...      ...      ...      ...        ...        ...
216  GODREJCP  1220.85  1222.25  1172.15  1176.20  2993508.0 2024-11-12
217  GODREJCP  1176.05  1189.45  1166.30  1183.90  1208369.0 2024-11-13
218  GODREJCP  1184.35  1194.30  1162.25  1175.10  1131043.0 2024-11-14
219  GODREJCP  1175.10  1191.75  1163.40  1181.65  1161297.0 2024-11-18
220  GODREJCP  1191.00  1198.85  1177.00  1185.30   983651.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open     high      low    close     volume start_Time
0    LODHA  1015.00  1061.00   997.00  1052.40   407624.0 2024-01-01
1    LODHA  1055.00  1063.30  1002.20  1014.50   914756.0 2024-01-02
2    LODHA  1012.05  1012.50   980.10  1004.05   460650.0 2024-01-03
3    LODHA  1015.00  1124.95  1012.00  1097.10  3271539.0 2024-01-04
4    LODHA  1104.00  1198.90  1079.05  1090.55  4672353.0 2024-01-05
..     ...      ...      ...      ...      ...        ...        ...
216  LODHA  1195.00  1291.00  1187.50  1240.95  4639217.0 2024-11-12
217  LODHA  1232.50  1240.05  1179.00  1202.10  1154288.0 2024-11-13
218  LODHA  1197.00  1247.35  1195.10  1222.15   917068.0 2024-11-14
219  LODHA  1263.00  1267.65  1218.25  1236.25  2147088.0 2024-11-18
220  LODHA  1256.00  1294.00  1240.05  1260.15  1893843.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol     open     high      low    close    volume start_Time
0      SRF  2488.75  2497.45  2460.00  2467.70  158733.0 2024-01-01
1      SRF  2482.95  2496.90  2424.80  2488.30  602156.0 2024-01-02
2      SRF  2488.15  2525.00  2464.85  2506.35  527559.0 2024-01-03
3      SRF  2509.00  2521.75  2487.15  2506.05  356989.0 2024-01-04
4      SRF  2511.00  2522.90  2461.00  2480.60  644040.0 2024-01-05
..     ...      ...      ...      ...      ...       ...        ...
216    SRF  2298.05  2308.95  2238.50  2253.05  222545.0 2024-11-12
217    SRF  2230.00  2247.00  2187.75  2197.90  417811.0 2024-11-13
218    SRF  2195.00  2244.05  2191.00  2235.20  152578.0 2024-11-14
219    SRF  2238.00  2242.30  2171.85  2179.35  294619.0 2024-11-18
220    SRF  2186.00  2226.00  2185.00  2199.50  315906.0 2024-11-19

[221 rows x 7 columns]
         Symbol     open     high      low    close   volume start_Time
0    SUNDARMFIN  3508.30  3595.00  3465.00  3496.35  12983.0 2024-01-01
1    SUNDARMFIN  3518.00  3543.95  3447.00  3531.10  16004.0 2024-01-02
2    SUNDARMFIN  3531.10  3640.90  3505.00  3611.50  39098.0 2024-01-03
3    SUNDARMFIN  3622.00  3642.60  3600.00  3613.10   9072.0 2024-01-04
4    SUNDARMFIN  3610.40  3640.00  3558.45  3625.85  16476.0 2024-01-05
..          ...      ...      ...      ...      ...      ...        ...
216  SUNDARMFIN  4280.00  4381.75  4261.60  4287.60  46646.0 2024-11-12
217  SUNDARMFIN  4281.45  4373.90  4130.05  4167.05  48791.0 2024-11-13
218  SUNDARMFIN  4160.00  4325.95  4154.85  4178.20  44267.0 2024-11-14
219  SUNDARMFIN  4145.15  4182.65  4106.05  4134.10  47638.0 2024-11-18
220  SUNDARMFIN  4134.10  4182.30  4056.50  4086.90  52181.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close    volume start_Time
0    SUNDRMFAST  1242.95  1254.45  1241.00  1246.80   28369.0 2024-01-01
1    SUNDRMFAST  1247.30  1254.10  1225.10  1229.90  212305.0 2024-01-02
2    SUNDRMFAST  1229.40  1253.70  1221.35  1250.50  127155.0 2024-01-03
3    SUNDRMFAST  1247.95  1257.00  1240.00  1246.55  100559.0 2024-01-04
4    SUNDRMFAST  1248.00  1254.20  1225.00  1243.55   72694.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  SUNDRMFAST  1253.00  1255.50  1220.00  1226.10   37153.0 2024-11-12
217  SUNDRMFAST  1225.20  1225.90  1189.35  1198.95   45488.0 2024-11-13
218  SUNDRMFAST  1210.25  1210.85  1182.60  1188.45   35311.0 2024-11-14
219  SUNDRMFAST  1188.45  1194.95  1161.00  1164.20   42320.0 2024-11-18
220  SUNDRMFAST  1170.30  1191.40  1162.00  1179.65   62473.0 2024-11-19

[221 rows x 7 columns]
        Symbol     open     high      low    close     volume start_Time
0    SUNPHARMA  1261.00  1263.95  1252.50  1260.25   733452.0 2024-01-01
1    SUNPHARMA  1261.00  1299.00  1257.15  1296.20  3174447.0 2024-01-02
2    SUNPHARMA  1296.20  1304.65  1291.15  1298.60  1699057.0 2024-01-03
3    SUNPHARMA  1304.00  1328.50  1297.05  1312.95  2851729.0 2024-01-04
4    SUNPHARMA  1318.00  1318.00  1287.00  1300.20  2960339.0 2024-01-05
..         ...      ...      ...      ...      ...        ...        ...
216  SUNPHARMA  1801.90  1825.00  1795.10  1800.85  2471888.0 2024-11-12
217  SUNPHARMA  1791.00  1797.30  1770.45  1779.00  1810332.0 2024-11-13
218  SUNPHARMA  1779.70  1796.00  1763.15  1768.20  1473358.0 2024-11-14
219  SUNPHARMA  1799.00  1799.00  1743.20  1747.75  1533025.0 2024-11-18
220  SUNPHARMA  1730.05  1806.75  1730.00  1777.25  1933316.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close    volume start_Time
0    SUPREMEIND  4540.00  4565.00  4456.00  4476.15   78967.0 2024-01-01
1    SUPREMEIND  4476.15  4498.00  4410.45  4484.20   50198.0 2024-01-02
2    SUPREMEIND  4450.00  4488.45  4420.00  4437.65   35101.0 2024-01-03
3    SUPREMEIND  4438.00  4496.00  4341.05  4398.45   98876.0 2024-01-04
4    SUPREMEIND  4404.45  4449.90  4360.00  4379.65   53534.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  SUPREMEIND  4650.00  4674.40  4600.00  4614.55  171018.0 2024-11-12
217  SUPREMEIND  4590.00  4624.95  4465.00  4516.20  200789.0 2024-11-13
218  SUPREMEIND  4500.00  4667.75  4420.00  4543.25  116213.0 2024-11-14
219  SUPREMEIND  4615.70  4684.00  4479.20  4635.05  164487.0 2024-11-18
220  SUPREMEIND  4623.80  4682.30  4512.55  4650.25  109097.0 2024-11-19

[221 rows x 7 columns]
         Symbol     open     high      low    close      volume start_Time
0    ADANIENSOL  1040.00  1073.00  1036.05  1055.05    676574.0 2024-01-01
1    ADANIENSOL  1060.00  1072.00  1034.00  1062.45   2716805.0 2024-01-02
2    ADANIENSOL  1150.00  1250.00  1072.00  1183.20  13493682.0 2024-01-03
3    ADANIENSOL  1210.00  1219.70  1150.00  1179.80   2693790.0 2024-01-04
4    ADANIENSOL  1180.00  1186.85  1155.45  1164.00   1343094.0 2024-01-05
..          ...      ...      ...      ...      ...         ...        ...
216  ADANIENSOL   903.60   937.95   901.55   924.05   3720874.0 2024-11-12
217  ADANIENSOL   920.00   936.70   885.10   889.85   2753677.0 2024-11-13
218  ADANIENSOL   900.00   905.95   875.85   879.70   1903461.0 2024-11-14
219  ADANIENSOL   888.00   889.00   855.00   866.55   1743209.0 2024-11-18
220  ADANIENSOL   866.55   887.40   865.25   871.55   1551260.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol    open    high     low   close     volume start_Time
0    SYNGENE  702.30  711.90  701.30  709.75   487675.0 2024-01-01
1    SYNGENE  714.95  724.30  708.00  721.70  1508789.0 2024-01-02
2    SYNGENE  722.80  730.00  714.10  723.65   696719.0 2024-01-03
3    SYNGENE  728.00  733.20  720.00  728.90   864004.0 2024-01-04
4    SYNGENE  732.80  733.35  717.55  723.60   771509.0 2024-01-05
..       ...     ...     ...     ...     ...        ...        ...
216  SYNGENE  889.20  901.70  886.55  889.30   504706.0 2024-11-12
217  SYNGENE  889.30  891.15  852.00  862.75   486609.0 2024-11-13
218  SYNGENE  862.75  869.15  856.80  861.60   427092.0 2024-11-14
219  SYNGENE  861.60  864.00  835.15  842.75   358986.0 2024-11-18
220  SYNGENE  846.95  862.20  845.10  850.80   256795.0 2024-11-19

[221 rows x 7 columns]
       Symbol     open     high      low    close     volume start_Time
0    TATACHEM  1113.00  1134.90  1106.25  1117.85  1851611.0 2024-01-01
1    TATACHEM  1117.90  1139.50  1101.00  1122.35  1578917.0 2024-01-02
2    TATACHEM  1122.30  1129.55  1097.00  1112.65  1404894.0 2024-01-03
3    TATACHEM  1117.05  1137.95  1113.00  1131.55   867201.0 2024-01-04
4    TATACHEM  1139.95  1141.00  1094.25  1104.70  1608206.0 2024-01-05
..        ...      ...      ...      ...      ...        ...        ...
216  TATACHEM  1095.50  1112.45  1068.00  1072.35   673271.0 2024-11-12
217  TATACHEM  1076.65  1080.80  1034.80  1041.15   848792.0 2024-11-13
218  TATACHEM  1041.15  1066.95  1041.05  1058.55   588233.0 2024-11-14
219  TATACHEM  1058.00  1069.00  1047.20  1058.95   470959.0 2024-11-18
220  TATACHEM  1067.95  1086.50  1061.00  1068.25   442292.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

        Symbol     open     high      low    close    volume start_Time
0    TATAELXSI  8793.00  8793.00  8710.00  8744.20   34849.0 2024-01-01
1    TATAELXSI  8740.00  8784.60  8609.00  8711.45   47188.0 2024-01-02
2    TATAELXSI  8722.95  8728.80  8600.00  8607.55   53427.0 2024-01-03
3    TATAELXSI  8607.55  8698.00  8607.55  8639.65   51866.0 2024-01-04
4    TATAELXSI  8677.95  8718.95  8575.10  8645.85   48283.0 2024-01-05
..         ...      ...      ...      ...      ...       ...        ...
216  TATAELXSI  6560.00  6694.95  6483.30  6635.50  387058.0 2024-11-12
217  TATAELXSI  6630.00  6719.90  6379.60  6417.30  328149.0 2024-11-13
218  TATAELXSI  6445.30  6511.00  6338.20  6374.55  241446.0 2024-11-14
219  TATAELXSI  6405.05  6565.00  6286.00  6456.00  251620.0 2024-11-18
220  TATAELXSI  6492.20  6598.00  6473.85  6549.00  118483.0 2024-11-19

[221 rows x 7 columns]
     Symbol      open      high       low     close  volume start_Time
0    HONAUT  37070.00  37750.00  36780.20  37490.00  6084.0 2024-01-01
1    HONAUT  37725.00  37725.00  36900.00  37008.30  3823.0 2024-01-02
2    HONAUT  37008.30  37008.30  36500.50  36716.30  2547.0 2024-01-03
3    HONAUT  36925.00  36925.00  36500.05  36681.65  2088.0 2024-01-04
4    HONAUT  37049.90  37049.90  36509.00  36855.20  2568.0 2024-01-05
..      ...       ...       ...       ...       ...     ...        ...
216  HONAUT  43997.05  43997.05  43201.00  43231.55  1652.0 2024-11-12
217  HONAUT  43299.00  43605.85  41690.10  41987.75  5691.0 2024-11-13
218  HONAUT  42250.00  42853.55  41812.00  42104.85  2970.0 2024-11-14
219  HONAUT  42000.15  42324.95  41270.00  41615.10  6537.0 2024-11-18
220  HONAUT  41500.00  42740.95  41500.00  42001.05  5390.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

        Symbol    open    high     low   close      volume start_Time
0    TATAPOWER  333.90  335.85  328.15  330.30  10096386.0 2024-01-01
1    TATAPOWER  331.70  332.70  319.60  329.85  15689859.0 2024-01-02
2    TATAPOWER  329.60  329.60  324.85  326.70   9954264.0 2024-01-03
3    TATAPOWER  326.80  340.80  326.80  337.85  26968463.0 2024-01-04
4    TATAPOWER  339.35  349.70  336.15  340.75  37557423.0 2024-01-05
..         ...     ...     ...     ...     ...         ...        ...
216  TATAPOWER  432.05  436.35  412.50  414.15  11039936.0 2024-11-12
217  TATAPOWER  413.00  416.20  396.95  399.35  13327466.0 2024-11-13
218  TATAPOWER  401.95  411.85  400.50  404.65  11063591.0 2024-11-14
219  TATAPOWER  408.00  410.90  397.60  404.70  10703937.0 2024-11-18
220  TATAPOWER  406.25  417.80  406.25  408.10   8869625.0 2024-11-19

[221 rows x 7 columns]
         Symbol     open     high      low    close     volume start_Time
0    TATACONSUM  1080.42  1080.42  1062.79  1066.84   936544.0 2024-01-01
1    TATACONSUM  1073.01  1089.50  1066.24  1084.27  2635193.0 2024-01-02
2    TATACONSUM  1084.47  1085.60  1069.40  1071.63  1100701.0 2024-01-03
3    TATACONSUM  1074.74  1114.74  1072.81  1111.73  2777186.0 2024-01-04
4    TATACONSUM  1111.19  1117.26  1103.33  1109.16  1207155.0 2024-01-05
..          ...      ...      ...      ...      ...        ...        ...
216  TATACONSUM   975.95   986.35   965.55   967.55   968082.0 2024-11-12
217  TATACONSUM   965.00   969.95   950.00   952.75   948691.0 2024-11-13
218  TATACONSUM   950.00   955.25   922.00   925.00  1950720.0 2024-11-14
219  TATACONSUM   929.80   942.50   916.00   930.75  2193819.0 2024-11-18
220  TATACONSUM   935.00   940.50   915.05   917.15  1844903.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol    open    high     low   close      volume start_Time
0    TATAMOTORS  785.00  798.70  781.05  790.60  12570717.0 2024-01-01
1    TATAMOTORS  800.50  804.00  779.00  784.40  13791090.0 2024-01-02
2    TATAMOTORS  786.05  790.00  776.25  781.45   8559060.0 2024-01-03
3    TATAMOTORS  798.00  801.80  791.30  795.75  14298444.0 2024-01-04
4    TATAMOTORS  799.00  805.90  787.10  790.95  11091198.0 2024-01-05
..          ...     ...     ...     ...     ...         ...        ...
216  TATAMOTORS  806.00  813.10  783.05  784.85  16526921.0 2024-11-12
217  TATAMOTORS  787.00  792.65  775.55  786.25  14674022.0 2024-11-13
218  TATAMOTORS  786.60  792.00  772.00  774.30  11740909.0 2024-11-14
219  TATAMOTORS  778.00  781.75  759.20  771.90  17053446.0 2024-11-18
220  TATAMOTORS  771.90  799.90  771.90  783.20  14012014.0 2024-11-19

[221 rows x 7 columns]
      Symbol     open     high      low    close    volume start_Time
0    THERMAX  3099.70  3115.00  3069.65  3091.40   18894.0 2024-01-01
1    THERMAX  3091.00  3120.00  3055.55  3095.80   36530.0 2024-01-02
2    THERMAX  3095.00  3246.10  3082.05  3174.35  210564.0 2024-01-03
3    THERMAX  3190.00  3221.95  3154.30  3187.75   95719.0 2024-01-04
4    THERMAX  3203.00  3268.00  3174.30  3209.85   86405.0 2024-01-05
..       ...      ...      ...      ...      ...       ...        ...
216  THERMAX  5280.00  5355.00  5095.00  5111.70   71629.0 2024-11-12
217  THERMAX  5105.20  5107.70  4888.35  4908.10   40951.0 2024-11-13
218  THERMAX  4998.90  5119.70  4893.00  5003.85  125079.0 2024-11-14
219  THERMAX  5100.00  5165.70  4780.00  4859.45   95184.0 2024-11-18
220  THERMAX  4872.55  4880.00  4601.00  4632.55  122676.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

        Symbol    open    high     low   close      volume start_Time
0    TATASTEEL  140.00  140.95  139.05  139.85  21186105.0 2024-01-01
1    TATASTEEL  140.50  140.60  137.05  139.60  27764060.0 2024-01-02
2    TATASTEEL  139.50  139.60  134.35  135.35  45176618.0 2024-01-03
3    TATASTEEL  136.00  136.35  134.00  134.25  43913498.0 2024-01-04
4    TATASTEEL  135.00  135.95  132.85  133.65  71330190.0 2024-01-05
..         ...     ...     ...     ...     ...         ...        ...
216  TATASTEEL  145.65  147.13  143.60  144.17  28861672.0 2024-11-12
217  TATASTEEL  143.60  143.60  138.60  139.17  57609083.0 2024-11-13
218  TATASTEEL  139.71  140.73  137.50  137.98  36345184.0 2024-11-14
219  TATASTEEL  139.49  143.25  138.00  141.21  40233848.0 2024-11-18
220  TATASTEEL  142.00  142.49  139.06  139.46  37611903.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open     high      low    close     volume start_Time
0    TITAN  3689.00  3698.00  3667.50  3677.15   286683.0 2024-01-01
1    TITAN  3689.00  3707.85  3642.50  3698.25   453685.0 2024-01-02
2    TITAN  3708.00  3709.95  3665.00  3693.05   356757.0 2024-01-03
3    TITAN  3696.00  3727.00  3686.65  3719.70   545228.0 2024-01-04
4    TITAN  3719.70  3750.00  3687.25  3712.55   963628.0 2024-01-05
..     ...      ...      ...      ...      ...        ...        ...
216  TITAN  3201.65  3239.00  3185.00  3198.45   992983.0 2024-11-12
217  TITAN  3175.00  3221.60  3162.20  3187.85   911537.0 2024-11-13
218  TITAN  3145.05  3195.15  3136.00  3183.70  1161637.0 2024-11-14
219  TITAN  3183.70  3207.20  3157.50  3172.30   943251.0 2024-11-18
220  TITAN  3192.00  3283.00  3172.30  3224.70  1174506.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close    volume start_Time
0    TORNTPHARM  2325.00  2331.70  2288.70  2296.30   99208.0 2024-01-01
1    TORNTPHARM  2300.95  2328.25  2291.60  2322.20  235455.0 2024-01-02
2    TORNTPHARM  2310.05  2368.20  2301.60  2351.40  292829.0 2024-01-03
3    TORNTPHARM  2355.00  2385.90  2330.85  2371.70  337858.0 2024-01-04
4    TORNTPHARM  2381.00  2381.00  2333.00  2350.10  324466.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  TORNTPHARM  3170.00  3200.35  3052.00  3151.05  382160.0 2024-11-12
217  TORNTPHARM  3151.05  3159.30  3097.90  3116.60  184256.0 2024-11-13
218  TORNTPHARM  3116.05  3141.45  3094.60  3102.40  223405.0 2024-11-14
219  TORNTPHARM  3103.05  3141.00  3075.25  3105.60  195002.0 2024-11-18
220  TORNTPHARM  3105.60  3133.55  3085.90  3094.85  171432.0 2024-11-19

[221 rows x 7 columns]
         Symbol     open     high      low    close     volume start_Time
0    ADANIGREEN  1598.00  1620.00  1585.00  1598.40   912757.0 2024-01-01
1    ADANIGREEN  1598.80  1616.00  1565.70  1603.55  1031651.0 2024-01-02
2    ADANIGREEN  1699.00  1747.40  1610.00  1697.25  8064214.0 2024-01-03
3    ADANIGREEN  1706.55  1723.00  1675.05  1692.50  1492988.0 2024-01-04
4    ADANIGREEN  1695.00  1700.00  1660.00  1674.00   871729.0 2024-01-05
..          ...      ...      ...      ...      ...        ...        ...
216  ADANIGREEN  1550.00  1573.00  1511.00  1524.15   523181.0 2024-11-12
217  ADANIGREEN  1503.00  1542.55  1459.55  1468.45   632049.0 2024-11-13
218  ADANIGREEN  1480.00  1519.95  1473.85  1490.30   571469.0 2024-11-14
219  ADANIGREEN  1512.45  1517.75  1450.00  1456.95   626638.0 2024-11-18
220  ADANIGREEN  1448.05  1467.00  1400.10  1412.70   972102.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol     open     high      low    close     volume start_Time
0    LUPIN  1324.00  1330.00  1308.65  1312.85   854557.0 2024-01-01
1    LUPIN  1340.00  1404.70  1332.00  1394.35  7120785.0 2024-01-02
2    LUPIN  1391.00  1412.90  1388.10  1406.40  1485207.0 2024-01-03
3    LUPIN  1406.85  1422.40  1394.35  1399.00  1534642.0 2024-01-04
4    LUPIN  1425.00  1425.00  1383.25  1389.45  1771551.0 2024-01-05
..     ...      ...      ...      ...      ...        ...        ...
216  LUPIN  2085.15  2129.00  2077.85  2090.10  1313915.0 2024-11-12
217  LUPIN  2088.45  2088.45  2030.15  2039.00   681649.0 2024-11-13
218  LUPIN  2039.00  2053.25  2004.65  2015.85   663815.0 2024-11-14
219  LUPIN  2007.50  2044.80  2000.00  2035.75  1117238.0 2024-11-18
220  LUPIN  2042.70  2054.40  2024.20  2038.20   585164.0 2024-11-19

[221 rows x 7 columns]
       Symbol    open     high      low    close    volume start_Time
0    UNITDSPR  1124.0  1125.00  1101.85  1107.20  563368.0 2024-01-01
1    UNITDSPR  1110.9  1113.85  1078.80  1093.90  686566.0 2024-01-02
2    UNITDSPR  1097.2  1105.10  1085.05  1098.20  444285.0 2024-01-03
3    UNITDSPR  1102.0  1114.55  1100.60  1108.60  512069.0 2024-01-04
4    UNITDSPR  1110.0  1117.35  1093.20  1101.05  616100.0 2024-01-05
..        ...     ...      ...      ...      ...       ...        ...
217  UNITDSPR  1475.0  1481.55  1439.10  1446.80  681448.0 2024-11-12
218  UNITDSPR  1433.1  1443.85  1423.45  1427.70  296683.0 2024-11-13
219  UNITDSPR  1427.7  1454.55  1425.20  1442.35  548233.0 2024-11-14
220  UNITDSPR  1443.0  1481.85  1440.25  1470.80  934866.0 2024-11-18
221  UNITDSPR  1479.0  1505.95  1475.25  1487.40  701161.0 2024-11-19

[222 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close     volume start_Time
0    JUBLPHARMA   572.00   584.00   560.40   580.15  2182903.0 2024-01-01
1    JUBLPHARMA   582.05   587.20   571.45   577.95   673114.0 2024-01-02
2    JUBLPHARMA   583.20   591.00   573.35   579.85   605306.0 2024-01-03
3    JUBLPHARMA   583.00   585.90   574.95   578.45   580606.0 2024-01-04
4    JUBLPHARMA   579.00   598.20   577.10   584.80  1139654.0 2024-01-05
..          ...      ...      ...      ...      ...        ...        ...
216  JUBLPHARMA  1230.00  1258.00  1150.00  1190.30   338909.0 2024-11-12
217  JUBLPHARMA  1162.00  1192.35  1085.80  1145.55   495408.0 2024-11-13
218  JUBLPHARMA  1145.55  1209.95  1145.55  1168.75   225326.0 2024-11-14
219  JUBLPHARMA  1158.10  1162.15  1115.00  1145.35   187995.0 2024-11-18
220  JUBLPHARMA  1158.50  1167.95  1115.00  1130.50   166735.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close     volume start_Time
0     KRBL  376.50  380.90  375.10  376.75   492945.0 2024-01-01
1     KRBL  376.75  378.60  368.70  373.95   284221.0 2024-01-02
2     KRBL  374.80  378.45  372.05  374.05   241721.0 2024-01-03
3     KRBL  376.70  377.90  371.95  373.25   246951.0 2024-01-04
4     KRBL  373.25  380.00  372.25  376.35   386728.0 2024-01-05
..     ...     ...     ...     ...     ...        ...        ...
216   KRBL  277.00  281.25  273.95  275.35   374491.0 2024-11-12
217   KRBL  274.70  279.90  265.30  267.70  1010999.0 2024-11-13
218   KRBL  266.90  280.65  265.60  275.85   690989.0 2024-11-14
219   KRBL  276.00  282.90  275.85  280.00   541809.0 2024-11-18
220   KRBL  281.00  289.60  281.00  287.40   779118.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

        Symbol    open    high     low   close     volume start_Time
0    GUJGASLTD  464.80  495.40  461.70  484.00  5898898.0 2024-01-01
1    GUJGASLTD  485.00  503.45  480.65  498.35  5085625.0 2024-01-02
2    GUJGASLTD  497.95  501.50  491.60  498.75  1583945.0 2024-01-03
3    GUJGASLTD  500.10  507.70  496.90  506.20  1822819.0 2024-01-04
4    GUJGASLTD  508.90  511.20  501.10  506.75  1315727.0 2024-01-05
..         ...     ...     ...     ...     ...        ...        ...
216  GUJGASLTD  519.00  523.05  501.50  503.05   558217.0 2024-11-12
217  GUJGASLTD  501.15  506.50  489.65  491.70   470223.0 2024-11-13
218  GUJGASLTD  493.00  497.00  484.70  486.00   311664.0 2024-11-14
219  GUJGASLTD  476.05  481.75  442.50  452.50  4498545.0 2024-11-18
220  GUJGASLTD  452.00  459.00  448.20  451.25  1357441.0 2024-11-19

[221 rows x 7 columns]
     Symbol    open    high     low   close     volume start_Time
0    VIPIND  599.00  613.80  597.20  609.95   868087.0 2024-01-01
1    VIPIND  614.00  614.65  597.55  599.00   665228.0 2024-01-02
2    VIPIND  601.40  603.00  589.00  592.25   566159.0 2024-01-03
3    VIPIND  592.25  597.00  587.10  588.20   783883.0 2024-01-04
4    VIPIND  592.00  606.40  587.20  589.05  1240109.0 2024-01-05
..      ...     ...     ...     ...     ...        ...        ...
216  VIPIND  469.85  479.70  464.10  471.55   437195.0 2024-11-12
217  VIPIND  471.00  472.05  458.05  461.90   769404.0 2024-11-13
218  VIPIND  463.25  474.80  462.05  466.55   433413.0 2024-11-14
219  VIPIND  467.95  472.70  461.00  463.75   248040.0 2024-11-18
220  VIPIND  465.95  469.90  456.95  460.10   197279.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

     Symbol     open     high      low    close     volume start_Time
0    VOLTAS   979.00   982.35   972.50   977.95   764752.0 2024-01-01
1    VOLTAS   977.40   998.00   968.00   992.20  1525164.0 2024-01-02
2    VOLTAS   992.35  1000.15   983.00   986.90  1252415.0 2024-01-03
3    VOLTAS   986.90  1022.95   986.20  1014.10  2398169.0 2024-01-04
4    VOLTAS  1010.00  1013.15   998.30  1009.20   871685.0 2024-01-05
..      ...      ...      ...      ...      ...        ...        ...
216  VOLTAS  1760.00  1783.90  1690.00  1699.60  2230594.0 2024-11-12
217  VOLTAS  1700.00  1705.00  1671.85  1685.40  1383751.0 2024-11-13
218  VOLTAS  1697.45  1735.80  1685.00  1708.60  1787679.0 2024-11-14
219  VOLTAS  1720.00  1744.00  1689.70  1695.95  1849251.0 2024-11-18
220  VOLTAS  1709.00  1732.35  1672.10  1686.75  1830677.0 2024-11-19

[221 rows x 7 columns]
       Symbol     open     high     low    close    volume start_Time
0    TATACOMM  1784.00  1784.00  1756.0  1766.85  381834.0 2024-01-01
1    TATACOMM  1770.00  1771.90  1735.0  1739.75  400171.0 2024-01-02
2    TATACOMM  1749.00  1757.50  1730.6  1750.00  238662.0 2024-01-03
3    TATACOMM  1750.00  1773.85  1744.5  1766.40  572327.0 2024-01-04
4    TATACOMM  1768.00  1794.40  1739.0  1758.45  901783.0 2024-01-05
..        ...      ...      ...     ...      ...       ...        ...
216  TATACOMM  1776.00  1794.85  1753.0  1759.65  149047.0 2024-11-12
217  TATACOMM  1759.65  1779.75  1737.0  1745.10  447599.0 2024-11-13
218  TATACOMM  1740.20  1777.35  1740.2  1749.90  121569.0 2024-11-14
219  TATACOMM  1749.90  1755.80  1715.2  1727.35  227643.0 2024-11-18
220  TATACOMM  1727.25  1773.00  1721.0  1736.70  162668.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol     open     high      low    close   volume start_Time
0    FINEORG  4935.15  5049.95  4935.15  4962.45  37728.0 2024-01-01
1    FINEORG  4965.00  4989.95  4853.00  4914.00  37502.0 2024-01-02
2    FINEORG  4910.00  4949.90  4850.00  4854.40  27039.0 2024-01-03
3    FINEORG  4854.00  4910.65  4802.00  4834.35  26501.0 2024-01-04
4    FINEORG  4869.00  4897.00  4810.70  4855.80  22795.0 2024-01-05
..       ...      ...      ...      ...      ...      ...        ...
216  FINEORG  5014.10  5049.55  4838.85  4869.50  12278.0 2024-11-12
217  FINEORG  4869.50  4869.50  4697.10  4711.40  21367.0 2024-11-13
218  FINEORG  4705.00  4835.85  4677.10  4766.15  14894.0 2024-11-14
219  FINEORG  4766.50  4772.95  4664.00  4729.45  13004.0 2024-11-18
220  FINEORG  4745.85  4838.95  4725.80  4738.50  13731.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close     volume start_Time
0    BHARTIARTL  1031.95  1031.95  1007.00  1013.05  3804406.0 2024-01-01
1    BHARTIARTL  1017.40  1025.45  1016.00  1021.70  6865791.0 2024-01-02
2    BHARTIARTL  1031.95  1037.00  1021.35  1035.20  3604276.0 2024-01-03
3    BHARTIARTL  1035.25  1058.80  1027.55  1047.90  4664043.0 2024-01-04
4    BHARTIARTL  1053.80  1063.65  1038.95  1046.60  4008221.0 2024-01-05
..          ...      ...      ...      ...      ...        ...        ...
216  BHARTIARTL  1568.80  1595.00  1550.10  1555.65  4479934.0 2024-11-12
217  BHARTIARTL  1559.90  1572.50  1546.35  1550.45  5816699.0 2024-11-13
218  BHARTIARTL  1550.00  1568.00  1536.55  1550.50  5139154.0 2024-11-14
219  BHARTIARTL  1568.95  1568.95  1529.45  1537.00  4816078.0 2024-11-18
220  BHARTIARTL  1537.00  1558.00  1519.30  1525.50  6238241.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close     volume start_Time
0    RITES  252.20  256.20  249.50  251.63   745956.0 2024-01-01
1    RITES  251.63  253.38  246.70  250.65   662635.0 2024-01-02
2    RITES  251.33  265.00  249.75  259.43  4771115.0 2024-01-03
3    RITES  260.98  262.00  257.50  258.65  1085590.0 2024-01-04
4    RITES  260.03  262.50  253.60  255.88   940498.0 2024-01-05
..     ...     ...     ...     ...     ...        ...        ...
216  RITES  277.00  283.90  277.00  279.95   898291.0 2024-11-12
217  RITES  275.00  278.45  268.50  269.60   943483.0 2024-11-13
218  RITES  267.70  275.80  267.60  272.90   696484.0 2024-11-14
219  RITES  272.55  274.60  267.00  270.60   594895.0 2024-11-18
220  RITES  270.05  277.65  270.05  274.70   704188.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close      volume start_Time
0    WIPRO  473.00  483.50  468.30  477.15  10173639.0 2024-01-01
1    WIPRO  478.00  478.00  464.30  469.20   7141257.0 2024-01-02
2    WIPRO  463.90  463.90  455.00  455.90   9767182.0 2024-01-03
3    WIPRO  457.00  459.85  451.40  452.40   7585168.0 2024-01-04
4    WIPRO  455.05  463.00  453.50  456.60   8444565.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216  WIPRO  575.00  579.70  569.05  570.65   5630445.0 2024-11-12
217  WIPRO  570.00  573.60  565.55  569.00   5695600.0 2024-11-13
218  WIPRO  568.95  574.55  564.20  566.70   4891760.0 2024-11-14
219  WIPRO  566.70  566.70  540.30  552.85   7644882.0 2024-11-18
220  WIPRO  556.00  569.80  554.70  562.00   6459889.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol     open     high      low    close     volume start_Time
0    OLECTRA  1349.00  1429.00  1345.05  1373.45  4636805.0 2024-01-01
1    OLECTRA  1377.95  1398.80  1327.40  1356.45  2143274.0 2024-01-02
2    OLECTRA  1357.00  1368.45  1332.60  1338.30   793802.0 2024-01-03
3    OLECTRA  1344.20  1379.80  1340.40  1349.05   722156.0 2024-01-04
4    OLECTRA  1354.35  1493.30  1344.00  1452.80  9772667.0 2024-01-05
..       ...      ...      ...      ...      ...        ...        ...
216  OLECTRA  1565.00  1582.85  1496.50  1510.25   596330.0 2024-11-12
217  OLECTRA  1507.95  1507.95  1420.95  1426.25   703917.0 2024-11-13
218  OLECTRA  1429.35  1452.30  1412.00  1417.55   431087.0 2024-11-14
219  OLECTRA  1420.90  1437.95  1386.25  1426.10   420374.0 2024-11-18
220  OLECTRA  1435.00  1463.00  1414.00  1419.45   320976.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close      volume start_Time
0      PNB   96.25   99.25   95.75   97.80  55329198.0 2024-01-01
1      PNB   97.80   98.90   96.10   97.00  50741670.0 2024-01-02
2      PNB   96.00   97.95   94.80   96.45  73009456.0 2024-01-03
3      PNB   96.50   97.85   96.45   97.40  37426897.0 2024-01-04
4      PNB   97.90   97.90   95.65   97.25  42729858.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216    PNB  105.50  106.34  103.35  103.73  26013763.0 2024-11-12
217    PNB  103.30  103.80  100.00  100.56  38963115.0 2024-11-13
218    PNB  101.10  102.48   99.30   99.49  25816807.0 2024-11-14
219    PNB  100.70  102.28   97.93  100.53  32300511.0 2024-11-18
220    PNB  101.15  103.72  100.45  100.86  25456236.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close      volume start_Time
0     ZEEL  275.10  287.65  274.15  285.05  17805173.0 2024-01-01
1     ZEEL  286.00  291.25  278.55  287.70  28467964.0 2024-01-02
2     ZEEL  288.00  291.00  282.35  285.65  12136773.0 2024-01-03
3     ZEEL  286.40  292.65  284.50  290.60  12952680.0 2024-01-04
4     ZEEL  292.00  293.20  280.60  283.05  20893253.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216   ZEEL  121.02  122.29  118.85  119.05   3947990.0 2024-11-12
217   ZEEL  118.42  120.90  114.36  114.90   8135008.0 2024-11-13
218   ZEEL  114.70  116.76  114.58  115.54   4648289.0 2024-11-14
219   ZEEL  115.60  116.63  114.61  115.40   4208969.0 2024-11-18
220   ZEEL  119.75  126.19  119.72  122.54  54141979.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

     Symbol    open    high     low   close    volume start_Time
0    VARROC  554.20  564.20  552.00  559.60  316566.0 2024-01-01
1    VARROC  562.00  562.00  546.05  551.45  208326.0 2024-01-02
2    VARROC  549.00  558.75  542.00  554.30  255882.0 2024-01-03
3    VARROC  557.00  570.00  552.95  566.80  593684.0 2024-01-04
4    VARROC  570.00  570.95  555.15  560.60  435326.0 2024-01-05
..      ...     ...     ...     ...     ...       ...        ...
216  VARROC  531.00  550.80  526.40  540.05  221163.0 2024-11-12
217  VARROC  540.05  540.05  494.10  500.05  482800.0 2024-11-13
218  VARROC  504.70  516.95  500.30  508.00  202920.0 2024-11-14
219  VARROC  508.10  510.00  493.15  498.50  564436.0 2024-11-18
220  VARROC  496.35  506.00  496.00  498.15   92226.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

        Symbol     open     high      low    close    volume start_Time
0    INDIAMART  2721.00  2753.65  2700.95  2725.25   92309.0 2024-01-01
1    INDIAMART  2736.00  2736.55  2675.00  2707.95  140094.0 2024-01-02
2    INDIAMART  2708.00  2739.00  2697.80  2705.55  155474.0 2024-01-03
3    INDIAMART  2720.00  2738.95  2703.40  2729.25   69129.0 2024-01-04
4    INDIAMART  2745.00  2783.95  2730.05  2743.15  124632.0 2024-01-05
..         ...      ...      ...      ...      ...       ...        ...
216  INDIAMART  2379.95  2387.65  2300.00  2308.15  158104.0 2024-11-12
217  INDIAMART  2308.15  2332.00  2283.20  2297.60  286532.0 2024-11-13
218  INDIAMART  2307.55  2335.30  2276.45  2284.15  250209.0 2024-11-14
219  INDIAMART  2280.00  2288.80  2234.15  2242.00  284801.0 2024-11-18
220  INDIAMART  2245.05  2312.00  2245.05  2263.25  227007.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol      open      high       low     close    volume start_Time
0     OFSS   4300.00   4358.00   4280.00   4338.85  363086.0 2024-01-01
1     OFSS   4349.90   4508.00   4340.00   4466.55  339737.0 2024-01-02
2     OFSS   4498.00   4498.00   4326.00   4337.40  139559.0 2024-01-03
3     OFSS   4330.00   4377.95   4307.25   4337.70  154455.0 2024-01-04
4     OFSS   4379.90   4566.55   4354.70   4457.65  496114.0 2024-01-05
..     ...       ...       ...       ...       ...       ...        ...
216   OFSS  11989.00  12141.95  11783.15  11855.75  150298.0 2024-11-12
217   OFSS  11840.05  11977.55  11681.60  11762.15   94042.0 2024-11-13
218   OFSS  11729.95  12004.50  11700.10  11768.55  108716.0 2024-11-14
219   OFSS  11800.45  11844.90  11009.40  11272.25  179726.0 2024-11-18
220   OFSS  11275.00  11562.55  11096.55  11169.05  127844.0 2024-11-19

[221 rows x 7 columns]
        Symbol    open    high     low   close      volume start_Time
0    UNIONBANK  119.65  121.50  119.10  120.75   8090321.0 2024-01-01
1    UNIONBANK  121.40  123.75  120.00  120.90  15399801.0 2024-01-02
2    UNIONBANK  121.05  123.55  120.25  123.05  13474009.0 2024-01-03
3    UNIONBANK  123.60  125.00  123.40  124.05  16066005.0 2024-01-04
4    UNIONBANK  124.35  125.55  123.35  124.15  12856589.0 2024-01-05
..         ...     ...     ...     ...     ...         ...        ...
216  UNIONBANK  119.16  120.64  117.80  119.00   7092442.0 2024-11-12
217  UNIONBANK  117.60  117.85  114.71  115.66   8694315.0 2024-11-13
218  UNIONBANK  115.66  117.64  113.25  113.90   6290516.0 2024-11-14
219  UNIONBANK  114.00  116.00  112.00  115.18   6674880.0 2024-11-18
220  UNIONBANK  115.18  117.79  115.10  116.02   5367834.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close     volume start_Time
0    SYRMA  665.45  672.80  658.00  659.55   366596.0 2024-01-01
1    SYRMA  662.95  666.45  651.05  658.05   282971.0 2024-01-02
2    SYRMA  662.40  670.75  656.00  664.05   529219.0 2024-01-03
3    SYRMA  664.95  669.85  634.00  639.05   726868.0 2024-01-04
4    SYRMA  641.90  646.85  623.35  631.20   490668.0 2024-01-05
..     ...     ...     ...     ...     ...        ...        ...
216  SYRMA  543.00  554.55  530.00  537.80   978958.0 2024-11-12
217  SYRMA  529.95  543.45  522.75  536.90  1047629.0 2024-11-13
218  SYRMA  539.85  558.00  537.05  547.65   855834.0 2024-11-14
219  SYRMA  550.00  566.00  533.35  560.10   891959.0 2024-11-18
220  SYRMA  570.00  584.00  552.80  559.40  1690701.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close      volume start_Time
0    CANBK   88.10   89.18   87.60   88.48  21701345.0 2024-01-01
1    CANBK   88.37   90.10   88.04   88.79  33168170.0 2024-01-02
2    CANBK   90.00   92.55   88.87   91.65  97005400.0 2024-01-03
3    CANBK   92.46   93.36   91.40   93.06  43984105.0 2024-01-04
4    CANBK   93.60   93.85   91.17   92.39  34552380.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
218  CANBK  104.15  104.80  101.12  101.50  14401385.0 2024-11-12
219  CANBK  101.00  102.00   97.54   98.33  29270560.0 2024-11-13
220  CANBK   99.00  100.46   97.22   97.49  17064169.0 2024-11-14
221  CANBK   97.50   98.80   95.72   98.18  17115166.0 2024-11-18
222  CANBK   99.23  101.27   97.10   97.81  21458767.0 2024-11-19

[223 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close    volume start_Time
0    CAPLIPOINT  1368.30  1425.40  1341.05  1355.95  313018.0 2024-01-01
1    CAPLIPOINT  1366.90  1398.00  1345.95  1393.95  213457.0 2024-01-02
2    CAPLIPOINT  1400.00  1420.00  1380.10  1399.70  129735.0 2024-01-03
3    CAPLIPOINT  1399.00  1419.90  1382.05  1406.85  121300.0 2024-01-04
4    CAPLIPOINT  1415.75  1424.00  1379.85  1399.75  107829.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  CAPLIPOINT  2007.70  2061.00  2002.30  2010.90   67150.0 2024-11-12
217  CAPLIPOINT  2001.40  2009.50  1951.00  1954.00   79100.0 2024-11-13
218  CAPLIPOINT  1953.70  2009.00  1914.55  1951.50  116252.0 2024-11-14
219  CAPLIPOINT  1958.50  2014.00  1958.50  1988.75   75496.0 2024-11-18
220  CAPLIPOINT  1990.00  2001.05  1942.80  1952.15   55774.0 2024-11-19

[221 rows x 7 columns]
         Symbol     open     high      low    close     volume start_Time
0    NATCOPHARM   811.95   824.00   811.00   818.35   535166.0 2024-01-01
1    NATCOPHARM   824.00   834.80   809.35   820.85   975916.0 2024-01-02
2    NATCOPHARM   828.00   842.00   823.55   835.45  1024810.0 2024-01-03
3    NATCOPHARM   842.00   844.95   834.95   838.60   607756.0 2024-01-04
4    NATCOPHARM   840.15   851.00   831.00   849.35   777719.0 2024-01-05
..          ...      ...      ...      ...      ...        ...        ...
216  NATCOPHARM  1402.00  1450.00  1377.40  1390.85  2277316.0 2024-11-12
217  NATCOPHARM  1397.00  1433.15  1360.10  1366.95  2009833.0 2024-11-13
218  NATCOPHARM  1373.00  1427.00  1372.60  1376.55  1205234.0 2024-11-14
219  NATCOPHARM  1388.05  1392.00  1351.00  1355.55   630359.0 2024-11-18
220  NATCOPHARM  1361.95  1387.60  1354.05  1364.65   593011.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

        Symbol     open     high     low    close     volume start_Time
0    GODREJIND   752.85   794.60  750.00   779.90  1340729.0 2024-01-01
1    GODREJIND   779.90   823.75  768.00   802.70  2784636.0 2024-01-02
2    GODREJIND   805.05   815.00  790.00   794.00  1411030.0 2024-01-03
3    GODREJIND   793.00   832.55  788.10   823.20   772045.0 2024-01-04
4    GODREJIND   832.00   854.00  812.40   841.15  1823485.0 2024-01-05
..         ...      ...      ...     ...      ...        ...        ...
216  GODREJIND   980.00   985.00  931.95   953.95    66504.0 2024-11-12
217  GODREJIND   948.00   948.00  923.00   932.85   106748.0 2024-11-13
218  GODREJIND   950.00  1021.45  921.00   931.95   843498.0 2024-11-14
219  GODREJIND   934.15  1079.85  934.15  1023.80  1370328.0 2024-11-18
220  GODREJIND  1015.05  1037.65  995.80  1027.50   304494.0 2024-11-19

[221 rows x 7 columns]
       Symbol     open     high      low    close     volume start_Time
0    DIVISLAB  3910.00  3939.95  3882.15  3915.90   240126.0 2024-01-01
1    DIVISLAB  3925.00  4052.10  3905.20  4030.00  1386959.0 2024-01-02
2    DIVISLAB  4050.00  4064.50  4012.00  4030.60   452402.0 2024-01-03
3    DIVISLAB  4050.00  4074.40  3973.20  4042.15   485788.0 2024-01-04
4    DIVISLAB  4052.00  4070.10  3980.00  4014.75   313459.0 2024-01-05
..        ...      ...      ...      ...      ...        ...        ...
216  DIVISLAB  5915.00  5949.85  5782.05  5810.70   433122.0 2024-11-12
217  DIVISLAB  5809.60  5831.70  5710.55  5770.10   250370.0 2024-11-13
218  DIVISLAB  5770.10  5825.95  5723.15  5750.10   220287.0 2024-11-14
219  DIVISLAB  5700.00  5814.05  5690.50  5766.65   390727.0 2024-11-18
220  DIVISLAB  5769.85  5960.95  5769.85  5900.85   427565.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close    volume start_Time
0      TMB  510.00  512.00  502.85  503.85  101232.0 2024-01-01
1      TMB  504.05  508.30  500.25  501.80  103034.0 2024-01-02
2      TMB  503.80  506.00  500.05  500.65   75708.0 2024-01-03
3      TMB  502.00  505.90  499.15  500.40  134220.0 2024-01-04
4      TMB  502.00  506.35  499.15  500.10  153655.0 2024-01-05
..     ...     ...     ...     ...     ...       ...        ...
216    TMB  444.00  447.80  438.00  440.15   54945.0 2024-11-12
217    TMB  440.00  441.40  433.45  435.05   81923.0 2024-11-13
218    TMB  435.00  441.00  435.00  439.30   97762.0 2024-11-14
219    TMB  441.45  444.95  435.00  438.85   81432.0 2024-11-18
220    TMB  439.10  449.50  439.10  447.30  135235.0 2024-11-19

[221 rows x 7 columns]
     Symbol     open     high      low    close    volume start_Time
0    RADICO  1669.30  1692.55  1660.05  1686.05  432273.0 2024-01-01
1    RADICO  1690.00  1703.00  1652.95  1656.10  130216.0 2024-01-02
2    RADICO  1660.00  1669.40  1645.10  1656.35   72925.0 2024-01-03
3    RADICO  1650.00  1695.00  1650.00  1674.45  252580.0 2024-01-04
4    RADICO  1676.00  1685.00  1651.10  1677.60   75523.0 2024-01-05
..      ...      ...      ...      ...      ...       ...        ...
216  RADICO  2284.80  2324.65  2279.50  2296.10   91735.0 2024-11-12
217  RADICO  2261.70  2284.20  2215.40  2257.50  158274.0 2024-11-13
218  RADICO  2250.00  2283.60  2228.05  2249.15  111556.0 2024-11-14
219  RADICO  2274.85  2274.85  2186.10  2223.25  137735.0 2024-11-18
220  RADICO  2229.70  2295.40  2217.65  2256.20  228088.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

     Symbol      open      high       low     close    volume start_Time
0    MARUTI  10345.00  10345.00  10214.65  10283.30  411724.0 2024-01-01
1    MARUTI  10283.30  10294.70  10151.05  10197.75  776837.0 2024-01-02
2    MARUTI  10200.00  10210.00  10065.00  10077.65  521046.0 2024-01-03
3    MARUTI  10100.00  10120.00   9985.55  10015.30  711733.0 2024-01-04
4    MARUTI  10010.65  10075.00   9970.00  10017.00  673131.0 2024-01-05
..      ...       ...       ...       ...       ...       ...        ...
216  MARUTI  11392.05  11516.90  11107.25  11143.10  549747.0 2024-11-12
217  MARUTI  11140.00  11142.85  10864.30  11049.60  507710.0 2024-11-13
218  MARUTI  11055.00  11117.70  10892.10  11006.05  431348.0 2024-11-14
219  MARUTI  10950.00  11182.95  10915.00  11093.95  333440.0 2024-11-18
220  MARUTI  11090.00  11195.25  10896.40  10959.30  864067.0 2024-11-19

[221 rows x 7 columns]
         Symbol    open    high     low   close      volume start_Time
0    INDUSTOWER  198.10  206.35  195.50  202.75  25210453.0 2024-01-01
1    INDUSTOWER  201.80  209.00  197.25  202.15  20581788.0 2024-01-02
2    INDUSTOWER  202.95  209.35  200.30  207.70  16523995.0 2024-01-03
3    INDUSTOWER  208.00  219.80  208.00  216.45  20981115.0 2024-01-04
4    INDUSTOWER  218.00  229.95  217.10  222.15  40926196.0 2024-01-05
..          ...     ...     ...     ...     ...         ...        ...
216  INDUSTOWER  326.00  331.10  319.25  321.00   3353016.0 2024-11-12
217  INDUSTOWER  321.90  322.70  316.60  318.10   7525374.0 2024-11-13
218  INDUSTOWER  319.00  321.10  315.60  317.75   8628870.0 2024-11-14
219  INDUSTOWER  320.00  326.60  317.00  323.15   6992604.0 2024-11-18
220  INDUSTOWER  328.75  335.25  325.15  328.15   5955778.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol     open     high      low    close    volume start_Time
0    JUSTDIAL   802.20   816.85   799.95   804.45  314165.0 2024-01-01
1    JUSTDIAL   811.85   819.95   801.20   804.55  331884.0 2024-01-02
2    JUSTDIAL   802.00   812.50   801.35   806.95  135773.0 2024-01-03
3    JUSTDIAL   808.00   816.00   803.25   810.35  135702.0 2024-01-04
4    JUSTDIAL   819.50   830.35   811.00   814.60  356307.0 2024-01-05
..        ...      ...      ...      ...      ...       ...        ...
216  JUSTDIAL  1119.80  1135.30  1094.10  1101.70  106136.0 2024-11-12
217  JUSTDIAL  1099.95  1099.95  1042.15  1061.15  116939.0 2024-11-13
218  JUSTDIAL  1060.30  1095.00  1060.30  1081.35  181371.0 2024-11-14
219  JUSTDIAL  1086.90  1092.50  1051.15  1058.70  168904.0 2024-11-18
220  JUSTDIAL  1068.90  1103.95  1056.85  1074.90  257929.0 2024-11-19

[221 rows x 7 columns]
     Symbol    open    high     low   close     volume start_Time
0    MARICO  550.00  552.45  540.00  542.25   965961.0 2024-01-01
1    MARICO  544.00  547.75  537.40  547.00  1243897.0 2024-01-02
2    MARICO  546.70  551.85  540.05  543.55  1190743.0 2024-01-03
3    MARICO  544.95  556.00  544.00  553.75  1325514.0 2024-01-04
4    MARICO  555.00  557.50  545.00  546.00   933806.0 2024-01-05
..      ...     ...     ...     ...     ...        ...        ...
216  MARICO  618.90  618.90  594.10  595.55  5562123.0 2024-11-12
217  MARICO  594.50  603.15  589.05  597.20  4858275.0 2024-11-13
218  MARICO  600.40  600.95  591.60  592.25   855697.0 2024-11-14
219  MARICO  592.25  596.45  579.60  595.15  2092848.0 2024-11-18
220  MARICO  597.40  599.85  590.00  590.95   861557.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

        Symbol    open    high     low   close      volume start_Time
0    MOTHERSON  102.80  108.40  102.50  105.85  52712410.0 2024-01-01
1    MOTHERSON  107.90  108.90  103.45  105.00  22614823.0 2024-01-02
2    MOTHERSON  105.50  105.70  101.35  101.90  22167688.0 2024-01-03
3    MOTHERSON  102.20  104.50  102.10  103.45  21403253.0 2024-01-04
4    MOTHERSON  104.30  106.65  103.05  104.05  24161892.0 2024-01-05
..         ...     ...     ...     ...     ...         ...        ...
216  MOTHERSON  175.20  176.10  163.30  166.04  30442591.0 2024-11-12
217  MOTHERSON  167.00  169.42  158.80  159.89  45864484.0 2024-11-13
218  MOTHERSON  160.50  168.31  160.50  165.36  25258283.0 2024-11-14
219  MOTHERSON  166.50  168.00  163.80  164.95  13114587.0 2024-11-18
220  MOTHERSON  165.55  169.99  164.50  165.36  13498210.0 2024-11-19

[221 rows x 7 columns]
      Symbol     open     high      low    close    volume start_Time
0    HDFCAMC  3205.00  3228.70  3181.50  3221.30  151964.0 2024-01-01
1    HDFCAMC  3230.00  3270.00  3203.50  3260.95  374265.0 2024-01-02
2    HDFCAMC  3260.00  3277.70  3227.00  3237.25  183450.0 2024-01-03
3    HDFCAMC  3245.00  3352.25  3237.25  3326.35  604988.0 2024-01-04
4    HDFCAMC  3339.00  3339.00  3288.00  3303.60  304963.0 2024-01-05
..       ...      ...      ...      ...      ...       ...        ...
216  HDFCAMC  4474.00  4540.00  4380.05  4397.50  477903.0 2024-11-12
217  HDFCAMC  4360.95  4372.10  4220.00  4249.15  364377.0 2024-11-13
218  HDFCAMC  4249.05  4360.00  4248.05  4278.75  393645.0 2024-11-14
219  HDFCAMC  4276.00  4278.75  4167.05  4182.35  684781.0 2024-11-18
220  HDFCAMC  4182.00  4229.00  4151.75  4190.15  455486.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol   open   high    low  close      volume start_Time
0    IDFCFIRSTB  88.80  88.90  87.60  87.80  34249920.0 2024-01-01
1    IDFCFIRSTB  87.90  87.95  85.60  86.10  35436796.0 2024-01-02
2    IDFCFIRSTB  86.00  86.75  84.55  86.10  31080242.0 2024-01-03
3    IDFCFIRSTB  86.20  87.20  86.20  87.05  18289264.0 2024-01-04
4    IDFCFIRSTB  87.30  87.55  85.90  86.70  22962991.0 2024-01-05
..          ...    ...    ...    ...    ...         ...        ...
216  IDFCFIRSTB  66.99  67.19  66.00  66.24  19572073.0 2024-11-12
217  IDFCFIRSTB  66.00  66.14  63.10  63.62  45002825.0 2024-11-13
218  IDFCFIRSTB  64.01  64.85  63.01  63.41  28532246.0 2024-11-14
219  IDFCFIRSTB  63.98  65.80  63.12  65.53  35353480.0 2024-11-18
220  IDFCFIRSTB  65.54  66.50  64.18  64.62  21394881.0 2024-11-19

[221 rows x 7 columns]
     Symbol     open     high      low    close    volume start_Time
0    INDIGO  3000.00  3049.95  2970.00  2978.50  615820.0 2024-01-01
1    INDIGO  2980.00  2989.90  2918.60  2925.70  439889.0 2024-01-02
2    INDIGO  2933.90  3000.00  2929.35  2990.45  655799.0 2024-01-03
3    INDIGO  2995.05  3005.75  2966.00  2995.85  416938.0 2024-01-04
4    INDIGO  3008.40  3025.00  2945.55  2954.95  715186.0 2024-01-05
..      ...      ...      ...      ...      ...       ...        ...
216  INDIGO  4020.00  4040.65  3895.00  3912.90  822043.0 2024-11-12
217  INDIGO  3894.00  3906.20  3830.00  3848.80  692857.0 2024-11-13
218  INDIGO  3864.00  3919.90  3838.95  3891.20  583377.0 2024-11-14
219  INDIGO  3950.00  4014.45  3907.05  3976.30  754253.0 2024-11-18
220  INDIGO  4002.00  4114.00  3982.05  4045.90  940659.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close     volume start_Time
0    SHRIRAMFIN  2055.55  2060.00  2041.10  2048.85   304722.0 2024-01-01
1    SHRIRAMFIN  2050.00  2059.75  2016.00  2030.05  1077927.0 2024-01-02
2    SHRIRAMFIN  2035.00  2098.00  2029.00  2090.05  1357534.0 2024-01-03
3    SHRIRAMFIN  2100.00  2152.50  2090.20  2148.15  1539021.0 2024-01-04
4    SHRIRAMFIN  2153.00  2176.75  2119.45  2172.40  1622887.0 2024-01-05
..          ...      ...      ...      ...      ...        ...        ...
216  SHRIRAMFIN  3014.45  3025.35  2922.65  2931.20  1086132.0 2024-11-12
217  SHRIRAMFIN  2930.50  2930.50  2839.25  2853.85  1351101.0 2024-11-13
218  SHRIRAMFIN  2852.80  2867.00  2783.00  2822.60  1434537.0 2024-11-14
219  SHRIRAMFIN  2822.60  2866.80  2800.00  2848.15   968379.0 2024-11-18
220  SHRIRAMFIN  2848.00  2866.00  2801.70  2824.75  1188509.0 2024-11-19

[221 rows x 7 columns]
      Symbol   open   high    low  close      volume start_Time
0    UCOBANK  39.85  40.35  39.60  40.00   8350081.0 2024-01-01
1    UCOBANK  40.05  40.75  39.65  39.85  11186544.0 2024-01-02
2    UCOBANK  39.85  41.75  39.80  41.05  31102708.0 2024-01-03
3    UCOBANK  41.45  42.35  41.35  41.70  21629930.0 2024-01-04
4    UCOBANK  42.10  42.60  41.00  41.35  15382544.0 2024-01-05
..       ...    ...    ...    ...    ...         ...        ...
216  UCOBANK  44.55  45.18  43.52  43.87   2949524.0 2024-11-12
217  UCOBANK  42.50  43.64  41.36  41.61   5791301.0 2024-11-13
218  UCOBANK  41.80  42.20  40.20  41.27   4957458.0 2024-11-14
219  UCOBANK  41.86  42.42  40.60  41.59   4366441.0 2024-11-18
220  UCOBANK  41.75  43.17  41.71  42.48   6765690.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol   open    high     low   close     volume start_Time
0      JSL  575.5  580.30  565.15  573.50  1272725.0 2024-01-01
1      JSL  577.0  600.00  573.50  596.30  3060686.0 2024-01-02
2      JSL  600.0  604.80  595.50  597.05  1918651.0 2024-01-03
3      JSL  596.4  610.20  593.50  601.40  2224961.0 2024-01-04
4      JSL  605.0  619.90  600.00  606.20  1989855.0 2024-01-05
..     ...    ...     ...     ...     ...        ...        ...
216    JSL  706.0  718.90  690.10  698.10   606328.0 2024-11-12
217    JSL  692.0  706.25  686.70  692.10   509872.0 2024-11-13
218    JSL  692.1  704.10  687.00  694.55   477721.0 2024-11-14
219    JSL  693.8  708.05  682.10  688.95   684545.0 2024-11-18
220    JSL  684.7  694.50  676.20  686.00   533314.0 2024-11-19

[221 rows x 7 columns]
         Symbol    open    high     low   close     volume start_Time
0    WELSPUNLIV  145.90  147.40  144.45  145.65  1426474.0 2024-01-01
1    WELSPUNLIV  146.85  146.85  142.20  143.25  2011396.0 2024-01-02
2    WELSPUNLIV  143.25  148.20  143.25  147.40  1908958.0 2024-01-03
3    WELSPUNLIV  148.55  152.80  148.50  149.75  2552918.0 2024-01-04
4    WELSPUNLIV  151.50  152.30  148.75  151.00  1041227.0 2024-01-05
..          ...     ...     ...     ...     ...        ...        ...
216  WELSPUNLIV  157.00  158.39  153.50  154.63  1880047.0 2024-11-12
217  WELSPUNLIV  154.30  154.30  147.80  148.73  1459611.0 2024-11-13
218  WELSPUNLIV  150.00  152.89  148.10  149.61  1475606.0 2024-11-14
219  WELSPUNLIV  150.00  152.40  144.79  147.45  1403453.0 2024-11-18
220  WELSPUNLIV  148.30  151.89  147.80  148.66   648001.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

        Symbol     open     high     low    close    volume start_Time
0    JAIBALAJI   765.00   779.00  750.00   760.15   98204.0 2024-01-01
1    JAIBALAJI   775.00   778.05  729.00   770.00  145871.0 2024-01-02
2    JAIBALAJI   768.60   808.50  750.00   808.50  296668.0 2024-01-03
3    JAIBALAJI   824.00   848.90  808.50   848.90  253935.0 2024-01-04
4    JAIBALAJI   864.00   891.00  860.00   868.95  330704.0 2024-01-05
..         ...      ...      ...     ...      ...       ...        ...
216  JAIBALAJI  1025.00  1039.95  980.90  1009.50   86603.0 2024-11-12
217  JAIBALAJI   960.00  1000.45  959.05   959.05   78114.0 2024-11-13
218  JAIBALAJI   959.00   966.70  931.00   941.25   53815.0 2024-11-14
219  JAIBALAJI   941.25   953.35  905.00   911.70   89775.0 2024-11-18
220  JAIBALAJI   924.95   935.00  911.00   921.75   79447.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close      volume start_Time
0      IGL  420.40  426.05  419.00  421.25   2097206.0 2024-01-01
1      IGL  421.00  427.70  416.05  425.90   2717197.0 2024-01-02
2      IGL  423.30  426.95  421.00  422.20   1643005.0 2024-01-03
3      IGL  422.20  428.00  421.10  424.40   1417133.0 2024-01-04
4      IGL  427.00  434.50  426.00  430.85   3389229.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216    IGL  436.05  437.85  424.35  427.30   3500647.0 2024-11-12
217    IGL  424.30  427.85  417.40  419.50   5029555.0 2024-11-13
218    IGL  420.00  421.85  403.60  405.80   2738096.0 2024-11-14
219    IGL  370.00  373.10  323.10  325.05  47575269.0 2024-11-18
220    IGL  329.00  329.50  316.75  320.45  14810634.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close     volume start_Time
0      UPL  588.00  599.90  587.20  592.70  2825708.0 2024-01-01
1      UPL  593.00  603.80  589.05  594.45  3406640.0 2024-01-02
2      UPL  595.35  596.80  585.30  586.85  2435233.0 2024-01-03
3      UPL  587.00  589.20  582.65  587.65  3606404.0 2024-01-04
4      UPL  589.30  590.95  576.50  581.25  2433275.0 2024-01-05
..     ...     ...     ...     ...     ...        ...        ...
216    UPL  530.00  552.80  524.00  527.75  9415040.0 2024-11-12
217    UPL  528.00  530.50  504.30  515.40  3436328.0 2024-11-13
218    UPL  519.90  532.80  509.45  525.80  3741207.0 2024-11-14
219    UPL  528.50  541.80  514.65  536.90  3036277.0 2024-11-18
220    UPL  533.10  555.55  531.85  546.80  2877510.0 2024-11-19

[221 rows x 7 columns]
        Symbol     open     high      low    close     volume start_Time
0    CREDITACC  1596.55  1610.00  1585.05  1594.15   143057.0 2024-01-01
1    CREDITACC  1602.00  1602.15  1560.00  1573.75   217805.0 2024-01-02
2    CREDITACC  1573.75  1624.00  1561.00  1585.30   132857.0 2024-01-03
3    CREDITACC  1572.60  1606.45  1572.60  1595.70   119118.0 2024-01-04
4    CREDITACC  1597.00  1744.80  1597.00  1729.10  1070524.0 2024-01-05
..         ...      ...      ...      ...      ...        ...        ...
216  CREDITACC   920.00   923.00   909.25   913.90   141599.0 2024-11-12
217  CREDITACC   917.60   917.60   890.00   897.00   172215.0 2024-11-13
218  CREDITACC   897.00   898.00   870.00   884.70   370332.0 2024-11-14
219  CREDITACC   884.70   888.30   869.00   880.35   226226.0 2024-11-18
220  CREDITACC   882.00   895.45   872.45   884.60   388566.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close    volume start_Time
0    ALKYLAMINE  2550.00  2710.00  2531.05  2701.35  382516.0 2024-01-01
1    ALKYLAMINE  2699.40  2735.00  2625.10  2691.20  274792.0 2024-01-02
2    ALKYLAMINE  2691.00  2691.00  2638.10  2647.85   69898.0 2024-01-03
3    ALKYLAMINE  2668.50  2719.80  2652.00  2661.75  114003.0 2024-01-04
4    ALKYLAMINE  2683.00  2692.00  2611.00  2641.10   58847.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  ALKYLAMINE  2023.20  2032.20  1980.00  1990.75   38456.0 2024-11-12
217  ALKYLAMINE  1980.75  1995.00  1928.00  1933.30   55880.0 2024-11-13
218  ALKYLAMINE  1950.20  1969.95  1903.55  1954.35   45889.0 2024-11-14
219  ALKYLAMINE  1960.05  1963.15  1913.35  1925.30   29943.0 2024-11-18
220  ALKYLAMINE  1939.35  1970.00  1928.65  1948.90   22927.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open     high      low    close    volume start_Time
0    AFFLE  1318.00  1336.90  1310.00  1320.10  460112.0 2024-01-01
1    AFFLE  1325.00  1334.95  1285.10  1309.60  377951.0 2024-01-02
2    AFFLE  1314.95  1325.90  1302.00  1309.50  289884.0 2024-01-03
3    AFFLE  1312.00  1328.95  1306.50  1312.95  197981.0 2024-01-04
4    AFFLE  1306.55  1323.00  1295.90  1306.35  193273.0 2024-01-05
..     ...      ...      ...      ...      ...       ...        ...
216  AFFLE  1608.10  1643.95  1555.55  1567.65  263688.0 2024-11-12
217  AFFLE  1562.00  1565.65  1505.05  1518.35  177664.0 2024-11-13
218  AFFLE  1501.05  1600.00  1501.05  1580.20  443710.0 2024-11-14
219  AFFLE  1581.95  1587.75  1536.10  1541.90  217358.0 2024-11-18
220  AFFLE  1541.90  1598.00  1535.05  1573.45  283837.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol    open    high     low   close     volume start_Time
0    PETRONET  223.00  228.70  222.50  225.60  4150472.0 2024-01-01
1    PETRONET  226.85  230.00  223.65  226.65  4779931.0 2024-01-02
2    PETRONET  227.95  229.80  225.60  228.30  3907477.0 2024-01-03
3    PETRONET  229.80  232.70  229.10  232.05  4018835.0 2024-01-04
4    PETRONET  232.85  233.95  227.70  228.65  3747630.0 2024-01-05
..        ...     ...     ...     ...     ...        ...        ...
216  PETRONET  326.30  328.55  320.85  322.70  1706554.0 2024-11-12
217  PETRONET  323.00  323.00  312.75  314.85  2295506.0 2024-11-13
218  PETRONET  313.00  318.45  312.95  313.85  3129940.0 2024-11-14
219  PETRONET  313.85  315.05  308.85  311.75  1651629.0 2024-11-18
220  PETRONET  311.10  318.75  311.10  313.95  1103399.0 2024-11-19

[221 rows x 7 columns]
         Symbol    open    high     low   close     volume start_Time
0    VAIBHAVGBL  396.85  398.75  393.15  394.90   195171.0 2024-01-01
1    VAIBHAVGBL  394.30  409.00  394.30  406.85   364653.0 2024-01-02
2    VAIBHAVGBL  406.00  442.55  402.65  432.20  6145063.0 2024-01-03
3    VAIBHAVGBL  430.00  447.70  415.15  418.60  2520664.0 2024-01-04
4    VAIBHAVGBL  420.70  427.85  409.00  413.55   888689.0 2024-01-05
..          ...     ...     ...     ...     ...        ...        ...
216  VAIBHAVGBL  284.65  286.25  275.60  276.40   188656.0 2024-11-12
217  VAIBHAVGBL  278.00  289.80  267.55  269.70   649203.0 2024-11-13
218  VAIBHAVGBL  272.00  279.45  267.00  269.55   480122.0 2024-11-14
219  VAIBHAVGBL  270.20  272.50  265.80  268.40   376459.0 2024-11-18
220  VAIBHAVGBL  268.60  277.00  268.60  272.15   202375.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

     Symbol    open    high     low   close      volume start_Time
0    BIOCON  249.80  259.65  249.65  255.55   7038993.0 2024-01-01
1    BIOCON  257.60  267.70  255.85  266.20  17494142.0 2024-01-02
2    BIOCON  267.95  284.50  265.60  282.35  28706243.0 2024-01-03
3    BIOCON  286.00  287.85  281.20  283.60   9653743.0 2024-01-04
4    BIOCON  285.35  294.50  278.70  291.30  12166860.0 2024-01-05
..      ...     ...     ...     ...     ...         ...        ...
216  BIOCON  348.70  353.55  345.85  347.50   5707023.0 2024-11-12
217  BIOCON  345.20  346.90  328.50  331.55   3915358.0 2024-11-13
218  BIOCON  333.85  339.85  330.55  335.80   4264527.0 2024-11-14
219  BIOCON  336.45  337.65  324.70  325.35   2389049.0 2024-11-18
220  BIOCON  326.95  334.20  325.20  327.05   1376851.0 2024-11-19

[221 rows x 7 columns]
       Symbol   open   high    low  close      volume start_Time
0    MAHABANK  45.25  45.95  45.10  45.65  12901280.0 2024-01-01
1    MAHABANK  45.50  46.20  45.10  45.45  17628818.0 2024-01-02
2    MAHABANK  46.00  47.60  45.60  47.30  63018012.0 2024-01-03
3    MAHABANK  47.55  47.75  46.95  47.20  27700055.0 2024-01-04
4    MAHABANK  47.30  47.60  46.30  46.70  18698418.0 2024-01-05
..        ...    ...    ...    ...    ...         ...        ...
216  MAHABANK  53.35  54.21  52.00  52.51   7587064.0 2024-11-12
217  MAHABANK  51.50  52.50  50.00  50.17  10761224.0 2024-11-13
218  MAHABANK  50.20  51.27  50.20  50.50  10199910.0 2024-11-14
219  MAHABANK  50.50  52.99  49.61  51.79  16310997.0 2024-11-18
220  MAHABANK  51.79  53.25  51.74  52.43  11149270.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol     open     high      low    close    volume start_Time
0    MPHASIS  2740.00  2775.00  2721.00  2736.85  252020.0 2024-01-01
1    MPHASIS  2736.00  2750.70  2653.85  2673.35  355638.0 2024-01-02
2    MPHASIS  2653.00  2658.95  2571.00  2578.70  646613.0 2024-01-03
3    MPHASIS  2591.95  2641.00  2581.50  2598.65  535052.0 2024-01-04
4    MPHASIS  2601.95  2682.00  2601.95  2637.55  395701.0 2024-01-05
..       ...      ...      ...      ...      ...       ...        ...
216  MPHASIS  2889.00  2903.75  2844.90  2853.45  612297.0 2024-11-12
217  MPHASIS  2854.00  2882.10  2823.15  2845.35  530900.0 2024-11-13
218  MPHASIS  2855.00  2887.55  2828.95  2839.30  330713.0 2024-11-14
219  MPHASIS  2840.00  2849.00  2752.00  2758.15  790762.0 2024-11-18
220  MPHASIS  2760.45  2848.75  2751.05  2789.25  514635.0 2024-11-19

[221 rows x 7 columns]
         Symbol    open    high     low   close     volume start_Time
0    POONAWALLA  440.00  442.85  437.00  438.00   607106.0 2024-01-01
1    POONAWALLA  437.00  439.00  429.10  431.00   720168.0 2024-01-02
2    POONAWALLA  432.70  437.65  430.00  431.10   972813.0 2024-01-03
3    POONAWALLA  441.00  454.00  433.80  450.40  4730223.0 2024-01-04
4    POONAWALLA  450.40  462.90  443.35  458.90  5327387.0 2024-01-05
..          ...     ...     ...     ...     ...        ...        ...
216  POONAWALLA  362.35  371.90  359.55  361.65  1248305.0 2024-11-12
217  POONAWALLA  361.65  363.30  345.40  347.45  1021221.0 2024-11-13
218  POONAWALLA  346.00  362.50  344.55  355.95  1456921.0 2024-11-14
219  POONAWALLA  355.95  360.00  351.40  356.30   746307.0 2024-11-18
220  POONAWALLA  359.50  364.00  355.55  358.30   733962.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol    open    high     low   close    volume start_Time
0    RKFORGE  720.00  728.80  710.00  711.70  183636.0 2024-01-01
1    RKFORGE  711.70  717.95  702.20  704.20  188120.0 2024-01-02
2    RKFORGE  707.00  722.00  702.00  717.00  153476.0 2024-01-03
3    RKFORGE  712.00  741.00  712.00  735.80  297146.0 2024-01-04
4    RKFORGE  741.00  755.70  727.55  738.80  331148.0 2024-01-05
..       ...     ...     ...     ...     ...       ...        ...
216  RKFORGE  964.00  972.30  935.10  943.85  100856.0 2024-11-12
217  RKFORGE  937.00  938.70  904.75  922.80  225466.0 2024-11-13
218  RKFORGE  923.00  943.95  923.00  932.70  135410.0 2024-11-14
219  RKFORGE  934.85  958.40  934.85  940.60  198120.0 2024-11-18
220  RKFORGE  955.95  983.70  939.65  946.85  627377.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close    volume start_Time
0      CCL  643.75  647.95  632.60  633.50  135892.0 2024-01-01
1      CCL  635.95  635.95  624.10  629.85  163082.0 2024-01-02
2      CCL  630.00  632.95  621.30  623.90  114519.0 2024-01-03
3      CCL  628.00  636.00  625.00  630.40  210606.0 2024-01-04
4      CCL  630.60  636.90  626.80  632.00   58663.0 2024-01-05
..     ...     ...     ...     ...     ...       ...        ...
216    CCL  716.30  724.00  686.55  691.20  195853.0 2024-11-12
217    CCL  690.00  710.00  676.00  697.30  292882.0 2024-11-13
218    CCL  698.55  709.70  691.05  695.00   99297.0 2024-11-14
219    CCL  695.00  701.85  685.80  694.20   66373.0 2024-11-18
220    CCL  702.00  713.75  689.10  701.55  125125.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol     open     high      low    close     volume start_Time
0       LT  3538.00  3538.00  3496.05  3525.45   777080.0 2024-01-01
1       LT  3525.05  3525.45  3432.00  3438.10  1511464.0 2024-01-02
2       LT  3433.00  3465.85  3411.60  3440.35  1283859.0 2024-01-03
3       LT  3441.05  3480.10  3423.00  3458.70  1651616.0 2024-01-04
4       LT  3464.95  3555.00  3460.00  3521.90  2069018.0 2024-01-05
..     ...      ...      ...      ...      ...        ...        ...
216     LT  3650.00  3651.00  3580.00  3591.35  1116206.0 2024-11-12
217     LT  3585.00  3604.85  3535.65  3547.95  1568694.0 2024-11-13
218     LT  3558.00  3565.75  3500.15  3526.25  1291765.0 2024-11-14
219     LT  3521.10  3568.30  3510.85  3542.15  1233217.0 2024-11-18
220     LT  3559.90  3607.00  3495.00  3505.90  1826460.0 2024-11-19

[221 rows x 7 columns]
       Symbol     open     high      low    close    volume start_Time
0    APARINDS  6053.40  6133.00  6000.05  6058.25   70761.0 2024-01-01
1    APARINDS  6058.00  6077.10  5885.95  6028.90   89835.0 2024-01-02
2    APARINDS  6008.00  6019.90  5842.50  5868.30   68542.0 2024-01-03
3    APARINDS  5900.00  5999.75  5841.05  5884.15   72148.0 2024-01-04
4    APARINDS  5884.20  5917.00  5752.05  5819.40   85509.0 2024-01-05
..        ...      ...      ...      ...      ...       ...        ...
216  APARINDS  8819.50  9074.45  8574.35  8958.15  214438.0 2024-11-12
217  APARINDS  8800.00  8800.20  8664.15  8737.85  112882.0 2024-11-13
218  APARINDS  8737.85  9044.70  8625.00  8959.35   96755.0 2024-11-14
219  APARINDS  8900.00  8900.00  8692.50  8821.05   59090.0 2024-11-18
220  APARINDS  8880.00  9689.00  8830.00  9479.30  519174.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol    open    high     low   close      volume start_Time
0    BANKBARODA  232.45  236.75  231.10  233.75  13199707.0 2024-01-01
1    BANKBARODA  233.70  235.80  228.85  230.70  12803886.0 2024-01-02
2    BANKBARODA  230.40  235.45  227.25  232.85  21410875.0 2024-01-03
3    BANKBARODA  233.05  240.10  232.90  237.75  14698523.0 2024-01-04
4    BANKBARODA  239.00  239.40  230.90  234.65  14545656.0 2024-01-05
..          ...     ...     ...     ...     ...         ...        ...
216  BANKBARODA  259.00  260.50  252.00  252.70   6461353.0 2024-11-12
217  BANKBARODA  250.15  252.85  241.90  243.30  15240064.0 2024-11-13
218  BANKBARODA  243.45  246.90  240.85  241.50   6939685.0 2024-11-14
219  BANKBARODA  241.50  243.85  236.15  241.40  15402466.0 2024-11-18
220  BANKBARODA  242.50  246.00  236.25  237.20  12811548.0 2024-11-19

[221 rows x 7 columns]
       Symbol    open    high     low   close     volume start_Time
0    SONACOMS  646.00  657.90  639.60  645.65  2080698.0 2024-01-01
1    SONACOMS  646.00  651.70  630.00  641.70  1783141.0 2024-01-02
2    SONACOMS  643.50  643.85  630.10  638.05  1062492.0 2024-01-03
3    SONACOMS  640.25  669.95  638.35  648.50  3434482.0 2024-01-04
4    SONACOMS  650.85  662.85  644.15  647.10  1446002.0 2024-01-05
..        ...     ...     ...     ...     ...        ...        ...
216  SONACOMS  699.20  707.80  679.10  684.05   892443.0 2024-11-12
217  SONACOMS  680.00  680.55  662.15  665.95   980137.0 2024-11-13
218  SONACOMS  678.70  682.95  660.55  668.65   756869.0 2024-11-14
219  SONACOMS  679.00  679.00  658.65  667.75   943201.0 2024-11-18
220  SONACOMS  667.95  696.60  667.95  680.40  1167001.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol      open      high      low     close    volume start_Time
0    ULTRACEMCO  10503.05  10520.00  10414.6  10464.00   97677.0 2024-01-01
1    ULTRACEMCO  10489.90  10489.90  10104.1  10204.70  337528.0 2024-01-02
2    ULTRACEMCO  10204.75  10245.00  10089.6  10111.55  179575.0 2024-01-03
3    ULTRACEMCO  10160.00  10164.55  10001.0  10014.80  313755.0 2024-01-04
4    ULTRACEMCO  10100.00  10100.00   9995.0  10016.05  163191.0 2024-01-05
..          ...       ...       ...      ...       ...       ...        ...
216  ULTRACEMCO  10970.50  11074.75  10840.0  10892.00  166347.0 2024-11-12
217  ULTRACEMCO  10803.30  10873.50  10750.0  10782.20  216900.0 2024-11-13
218  ULTRACEMCO  10726.00  10832.50  10542.5  10728.50  297442.0 2024-11-14
219  ULTRACEMCO  10632.10  10766.85  10580.4  10630.90  424186.0 2024-11-18
220  ULTRACEMCO  10684.05  10870.00  10657.9  10769.55  220357.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open     high      low    close     volume start_Time
0      TCS  3790.00  3832.00  3773.00  3811.10   825907.0 2024-01-01
1      TCS  3811.10  3811.10  3767.25  3783.20  1344068.0 2024-01-02
2      TCS  3767.00  3771.85  3687.05  3691.75  1803075.0 2024-01-03
3      TCS  3701.75  3719.00  3651.00  3666.80  3598144.0 2024-01-04
4      TCS  3675.00  3747.75  3674.85  3737.90  1963127.0 2024-01-05
..     ...      ...      ...      ...      ...        ...        ...
216    TCS  4216.00  4218.00  4164.35  4197.40  1587640.0 2024-11-12
217    TCS  4178.10  4196.75  4131.05  4150.35  1098813.0 2024-11-13
218    TCS  4135.00  4160.00  4116.45  4145.90  1825432.0 2024-11-14
219    TCS  4213.00  4213.00  3990.20  4019.50  3313944.0 2024-11-18
220    TCS  4019.90  4132.15  4014.10  4039.55  1776233.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

        Symbol    open    high     low   close     volume start_Time
0    SHYAMMETL  636.00  646.60  628.35  641.90  2400493.0 2024-01-01
1    SHYAMMETL  648.00  654.00  635.10  643.00  2557701.0 2024-01-02
2    SHYAMMETL  635.50  677.00  632.55  668.70  2861553.0 2024-01-03
3    SHYAMMETL  670.00  682.00  651.55  655.15  1956706.0 2024-01-04
4    SHYAMMETL  656.00  668.00  645.00  653.75  1053483.0 2024-01-05
..         ...     ...     ...     ...     ...        ...        ...
216  SHYAMMETL  803.25  827.75  799.95  810.15   419757.0 2024-11-12
217  SHYAMMETL  796.00  811.25  778.65  796.25   433815.0 2024-11-13
218  SHYAMMETL  793.00  823.05  790.30  812.80   360847.0 2024-11-14
219  SHYAMMETL  809.00  829.00  799.15  804.05   277112.0 2024-11-18
220  SHYAMMETL  805.05  827.45  805.05  821.80   252045.0 2024-11-19

[221 rows x 7 columns]
      Symbol     open     high      low    close    volume start_Time
0    COFORGE  6289.95  6289.95  6181.00  6192.55  183642.0 2024-01-01
1    COFORGE  6210.00  6217.40  6001.00  6038.30  315763.0 2024-01-02
2    COFORGE  6049.40  6050.00  5841.55  5928.20  400286.0 2024-01-03
3    COFORGE  5945.00  6037.00  5911.60  5954.05  210040.0 2024-01-04
4    COFORGE  5954.10  6148.85  5954.10  6076.35  498803.0 2024-01-05
..       ...      ...      ...      ...      ...       ...        ...
216  COFORGE  8150.00  8159.95  8025.00  8099.25  390338.0 2024-11-12
217  COFORGE  8099.25  8157.30  8010.00  8056.20  528790.0 2024-11-13
218  COFORGE  8060.00  8155.55  7990.00  8074.00  312854.0 2024-11-14
219  COFORGE  8075.00  8091.90  7905.45  8006.60  378011.0 2024-11-18
220  COFORGE  8006.60  8239.50  7995.00  8116.50  344199.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

        Symbol    open    high     low   close      volume start_Time
0    PPLPHARMA  138.90  139.60  137.80  138.55   3223669.0 2024-01-01
1    PPLPHARMA  138.60  143.80  138.30  140.50  12577983.0 2024-01-02
2    PPLPHARMA  140.90  142.40  139.65  140.25   4697766.0 2024-01-03
3    PPLPHARMA  140.65  142.95  140.15  142.10   5720391.0 2024-01-04
4    PPLPHARMA  143.50  145.80  143.00  144.80  11990936.0 2024-01-05
..         ...     ...     ...     ...     ...         ...        ...
216  PPLPHARMA  268.20  269.40  248.70  250.60   9251904.0 2024-11-12
217  PPLPHARMA  250.00  277.00  244.60  259.70  38049068.0 2024-11-13
218  PPLPHARMA  263.55  267.45  254.45  258.45  11280342.0 2024-11-14
219  PPLPHARMA  260.10  262.50  244.10  251.75   7666402.0 2024-11-18
220  PPLPHARMA  255.05  260.00  248.55  250.60   4256286.0 2024-11-19

[221 rows x 7 columns]
       Symbol    open    high     low   close    volume start_Time
0    WESTLIFE  820.05  822.60  813.70  819.20   44169.0 2024-01-01
1    WESTLIFE  815.00  826.00  811.15  823.95   68025.0 2024-01-02
2    WESTLIFE  826.05  827.00  812.20  815.95   55311.0 2024-01-03
3    WESTLIFE  824.00  831.50  810.00  816.55  186879.0 2024-01-04
4    WESTLIFE  820.55  825.00  817.00  823.10   51782.0 2024-01-05
..        ...     ...     ...     ...     ...       ...        ...
216  WESTLIFE  756.00  756.00  740.55  747.05   20947.0 2024-11-12
217  WESTLIFE  740.00  741.45  716.70  726.45   89796.0 2024-11-13
218  WESTLIFE  728.50  732.00  674.45  705.90  632545.0 2024-11-14
219  WESTLIFE  704.10  704.10  685.55  699.90  117964.0 2024-11-18
220  WESTLIFE  700.05  727.65  697.90  722.85  159899.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close      volume start_Time
0     GAIL  163.70  169.35  162.65  166.20  40952729.0 2024-01-01
1     GAIL  167.10  167.60  158.10  164.05  40801901.0 2024-01-02
2     GAIL  164.00  164.40  160.75  162.15  22338899.0 2024-01-03
3     GAIL  162.30  165.70  162.25  163.15  16795469.0 2024-01-04
4     GAIL  166.00  167.10  161.90  163.65  36182162.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216   GAIL  203.00  205.20  193.50  194.15  17295996.0 2024-11-12
217   GAIL  193.90  194.70  188.95  189.47  12112022.0 2024-11-13
218   GAIL  189.51  192.00  187.93  188.89  12252336.0 2024-11-14
219   GAIL  190.00  190.85  184.62  185.46  14792702.0 2024-11-18
220   GAIL  185.64  189.50  185.64  186.68   9668218.0 2024-11-19

[221 rows x 7 columns]
        Symbol    open    high     low   close      volume start_Time
0    BANKINDIA  113.20  114.20  112.35  113.05  16485079.0 2024-01-01
1    BANKINDIA  113.15  115.00  111.95  114.40  23191028.0 2024-01-02
2    BANKINDIA  114.50  116.95  113.40  116.20  30456365.0 2024-01-03
3    BANKINDIA  116.30  118.95  116.30  118.65  31814561.0 2024-01-04
4    BANKINDIA  119.00  122.40  117.30  118.85  38103338.0 2024-01-05
..         ...     ...     ...     ...     ...         ...        ...
216  BANKINDIA  111.98  114.36  108.00  108.69  11559079.0 2024-11-12
217  BANKINDIA  108.30  108.30  104.26  104.74   6511151.0 2024-11-13
218  BANKINDIA  106.00  106.90  103.80  104.30   3862235.0 2024-11-14
219  BANKINDIA  104.40  104.80  101.50  103.07   6355112.0 2024-11-18
220  BANKINDIA  103.49  107.60  103.43  104.57   5196762.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

     Symbol    open    high     low   close     volume start_Time
0    CONCOR  860.00  873.80  854.10  861.20   759906.0 2024-01-01
1    CONCOR  864.50  882.70  845.00  879.65  1362479.0 2024-01-02
2    CONCOR  882.95  890.30  869.30  882.15  1965216.0 2024-01-03
3    CONCOR  885.00  932.70  885.00  913.30  4075191.0 2024-01-04
4    CONCOR  919.25  920.15  886.35  895.90   983472.0 2024-01-05
..      ...     ...     ...     ...     ...        ...        ...
216  CONCOR  829.95  836.85  806.00  809.75   622501.0 2024-11-12
217  CONCOR  805.00  814.00  785.55  792.35   724162.0 2024-11-13
218  CONCOR  792.00  795.55  776.50  785.65   656637.0 2024-11-14
219  CONCOR  789.65  792.30  782.35  785.85   703483.0 2024-11-18
220  CONCOR  795.50  810.20  780.30  785.75  2035040.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close      volume start_Time
0     NTPC  312.00  313.30  307.80  309.75   8024960.0 2024-01-01
1     NTPC  310.80  310.80  302.05  306.00  13506040.0 2024-01-02
2     NTPC  307.20  308.00  303.30  306.20  14259987.0 2024-01-03
3     NTPC  310.90  321.75  308.60  317.10  40057506.0 2024-01-04
4     NTPC  322.90  325.65  312.70  314.95  27456415.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216   NTPC  393.15  394.80  379.05  380.30  10549517.0 2024-11-12
217   NTPC  384.00  387.60  379.35  381.35  20602407.0 2024-11-13
218   NTPC  380.05  385.20  371.35  372.50  15086601.0 2024-11-14
219   NTPC  380.00  380.00  362.65  366.70  16383636.0 2024-11-18
220   NTPC  368.00  378.50  365.05  366.70  17055094.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close    volume start_Time
0    LALPATHLAB  2579.95  2594.95  2561.35  2575.35   97108.0 2024-01-01
1    LALPATHLAB  2575.95  2655.00  2570.05  2644.80  284235.0 2024-01-02
2    LALPATHLAB  2658.00  2658.00  2621.15  2638.05  185729.0 2024-01-03
3    LALPATHLAB  2638.80  2662.00  2614.10  2638.75  118771.0 2024-01-04
4    LALPATHLAB  2639.30  2659.20  2577.00  2597.60  135153.0 2024-01-05
..          ...      ...      ...      ...      ...       ...        ...
216  LALPATHLAB  3011.25  3068.00  3011.25  3029.90  133841.0 2024-11-12
217  LALPATHLAB  3002.30  3027.95  2942.05  2957.15  206496.0 2024-11-13
218  LALPATHLAB  2960.00  2990.00  2928.05  2956.40  149233.0 2024-11-14
219  LALPATHLAB  2957.45  3013.40  2918.00  2967.75  136290.0 2024-11-18
220  LALPATHLAB  2971.45  3073.20  2970.45  3041.45  213413.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open    high      low    close    volume start_Time
0     JBMA  1498.00  1667.0  1490.15  1619.35  971472.0 2024-01-01
1     JBMA  1645.00  1735.0  1629.05  1721.50  741322.0 2024-01-02
2     JBMA  1743.25  1744.8  1652.50  1672.80  246834.0 2024-01-03
3     JBMA  1680.00  1719.9  1660.00  1681.45  192407.0 2024-01-04
4     JBMA  1690.00  1744.0  1664.90  1698.90  315586.0 2024-01-05
..     ...      ...     ...      ...      ...       ...        ...
216   JBMA  1549.15  1560.0  1456.85  1530.50  473666.0 2024-11-12
217   JBMA  1512.50  1513.6  1464.00  1468.30  103784.0 2024-11-13
218   JBMA  1473.95  1490.2  1450.00  1454.05   82643.0 2024-11-14
219   JBMA  1480.00  1493.8  1437.15  1454.85   79920.0 2024-11-18
220   JBMA  1470.00  1509.0  1425.00  1442.00  111298.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close    volume start_Time
0     KIMS  395.80  398.41  390.59  391.62   64419.0 2024-01-01
1     KIMS  394.60  397.99  387.60  388.74   48936.0 2024-01-02
2     KIMS  391.20  393.34  380.65  389.00   40347.0 2024-01-03
3     KIMS  391.98  398.61  390.07  395.70   39525.0 2024-01-04
4     KIMS  399.24  408.80  398.81  400.04  532706.0 2024-01-05
..     ...     ...     ...     ...     ...       ...        ...
216   KIMS  562.95  575.35  545.10  554.55  508829.0 2024-11-12
217   KIMS  554.35  561.85  546.10  554.20  265893.0 2024-11-13
218   KIMS  556.15  566.00  555.00  560.10  250533.0 2024-11-14
219   KIMS  560.10  566.05  550.70  557.75  270715.0 2024-11-18
220   KIMS  562.95  572.30  558.15  567.20  573902.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open     high      low    close    volume start_Time
0    ALKEM  5209.95  5225.00  5093.20  5120.00  101017.0 2024-01-01
1    ALKEM  5135.00  5199.90  5113.85  5186.00  101061.0 2024-01-02
2    ALKEM  5201.95  5266.95  5156.20  5240.50  275095.0 2024-01-03
3    ALKEM  5240.50  5301.00  5228.60  5269.45  442884.0 2024-01-04
4    ALKEM  5275.00  5315.50  5202.95  5238.60  223430.0 2024-01-05
..     ...      ...      ...      ...      ...       ...        ...
216  ALKEM  5650.00  5677.40  5444.10  5503.40  306620.0 2024-11-12
217  ALKEM  5500.00  5637.60  5361.05  5571.20  621020.0 2024-11-13
218  ALKEM  5566.05  5665.95  5491.55  5524.95  308852.0 2024-11-14
219  ALKEM  5550.00  5608.60  5492.50  5515.15  266630.0 2024-11-18
220  ALKEM  5490.00  5599.80  5463.00  5529.80  284770.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol    open    high     low   close     volume start_Time
0    JSWSTEEL  880.25  884.80  875.00  877.60   778184.0 2024-01-01
1    JSWSTEEL  883.85  883.85  859.10  870.20  1615515.0 2024-01-02
2    JSWSTEEL  870.00  870.00  836.00  837.65  3983411.0 2024-01-03
3    JSWSTEEL  840.25  843.80  835.00  837.10  1878399.0 2024-01-04
4    JSWSTEEL  838.95  845.80  827.20  829.40  2060548.0 2024-01-05
..        ...     ...     ...     ...     ...        ...        ...
216  JSWSTEEL  987.00  987.80  953.65  957.25   731821.0 2024-11-12
217  JSWSTEEL  953.50  958.25  928.05  935.95  1167594.0 2024-11-13
218  JSWSTEEL  935.05  949.35  932.45  939.05  1662673.0 2024-11-14
219  JSWSTEEL  935.05  956.05  934.90  949.85  1143965.0 2024-11-18
220  JSWSTEEL  949.85  960.95  945.00  947.30   617409.0 2024-11-19

[221 rows x 7 columns]
       Symbol    open    high     low   close     volume start_Time
0    SAREGAMA  374.70  375.55  368.10  369.75   193230.0 2024-01-01
1    SAREGAMA  371.50  376.00  367.85  373.40   255859.0 2024-01-02
2    SAREGAMA  375.20  379.00  369.55  375.05   396183.0 2024-01-03
3    SAREGAMA  377.75  382.45  373.55  374.50   332298.0 2024-01-04
4    SAREGAMA  379.50  379.90  370.55  373.65   214728.0 2024-01-05
..        ...     ...     ...     ...     ...        ...        ...
216  SAREGAMA  482.90  484.00  470.00  473.10   284819.0 2024-11-12
217  SAREGAMA  470.00  483.95  439.10  475.70  1260328.0 2024-11-13
218  SAREGAMA  477.45  497.05  471.00  488.40   664126.0 2024-11-14
219  SAREGAMA  485.00  485.00  459.00  466.70   483804.0 2024-11-18
220  SAREGAMA  462.00  482.55  462.00  469.80   541218.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close     volume start_Time
0      FDC  399.70  405.10  393.00  394.20   150106.0 2024-01-01
1      FDC  397.40  400.30  392.00  398.60   183845.0 2024-01-02
2      FDC  400.00  432.80  400.00  411.70  4256883.0 2024-01-03
3      FDC  413.95  423.00  411.70  415.00   843420.0 2024-01-04
4      FDC  419.00  421.90  411.30  414.80   373344.0 2024-01-05
..     ...     ...     ...     ...     ...        ...        ...
216    FDC  518.75  518.75  494.35  498.65    98076.0 2024-11-12
217    FDC  492.00  509.70  484.00  495.70   280612.0 2024-11-13
218    FDC  498.20  504.60  492.35  496.15    68966.0 2024-11-14
219    FDC  492.00  493.55  480.05  488.00    70492.0 2024-11-18
220    FDC  489.70  496.95  486.45  487.95    68450.0 2024-11-19

[221 rows x 7 columns]
         Symbol    open    high     low   close      volume start_Time
0    ENGINERSIN  172.45  184.80  170.25  181.75  26971428.0 2024-01-01
1    ENGINERSIN  182.70  204.40  176.20  197.20  56855386.0 2024-01-02
2    ENGINERSIN  196.10  209.50  194.35  203.85  47223552.0 2024-01-03
3    ENGINERSIN  205.10  205.50  199.45  201.10   9040359.0 2024-01-04
4    ENGINERSIN  202.00  204.90  194.60  199.45  10796664.0 2024-01-05
..          ...     ...     ...     ...     ...         ...        ...
216  ENGINERSIN  189.00  194.00  185.91  187.24   2168672.0 2024-11-12
217  ENGINERSIN  185.80  187.23  178.75  179.29   2151699.0 2024-11-13
218  ENGINERSIN  179.29  184.39  179.20  180.36   1631446.0 2024-11-14
219  ENGINERSIN  180.36  183.39  177.00  179.36   2062522.0 2024-11-18
220  ENGINERSIN  180.00  185.66  179.97  181.30   1816050.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close     volume start_Time
0     IIFL  572.13  591.36  570.92  585.49   755028.0 2024-01-01
1     IIFL  589.08  599.52  579.37  597.68  1047716.0 2024-01-02
2     IIFL  595.54  601.27  586.70  589.62   826485.0 2024-01-03
3     IIFL  591.56  619.24  585.73  616.47  1549128.0 2024-01-04
4     IIFL  631.34  636.14  611.96  623.27  1892805.0 2024-01-05
..     ...     ...     ...     ...     ...        ...        ...
216   IIFL  442.45  444.65  430.05  433.10   464898.0 2024-11-12
217   IIFL  433.70  434.85  417.00  420.25   769829.0 2024-11-13
218   IIFL  425.00  431.85  420.05  422.15   669924.0 2024-11-14
219   IIFL  422.15  423.35  413.45  417.60   645666.0 2024-11-18
220   IIFL  418.00  428.85  413.55  416.30   955715.0 2024-11-19

[221 rows x 7 columns]
        Symbol     open     high      low    close      volume start_Time
0    ICICIBANK   991.55  1004.85   991.00   999.40   7683792.0 2024-01-01
1    ICICIBANK   997.00   997.65   980.25   982.25  16263825.0 2024-01-02
2    ICICIBANK   984.70   988.00   975.10   984.05  16826752.0 2024-01-03
3    ICICIBANK   986.40   989.15   981.90   987.15  22789140.0 2024-01-04
4    ICICIBANK   988.00   998.30   983.80   993.70  14875499.0 2024-01-05
..         ...      ...      ...      ...      ...         ...        ...
216  ICICIBANK  1276.15  1295.00  1264.50  1270.60  13486168.0 2024-11-12
217  ICICIBANK  1270.60  1276.25  1250.00  1253.70  12260404.0 2024-11-13
218  ICICIBANK  1253.75  1267.70  1243.05  1256.95   9506892.0 2024-11-14
219  ICICIBANK  1260.00  1262.60  1249.40  1253.45   6195554.0 2024-11-18
220  ICICIBANK  1257.05  1261.00  1240.85  1249.10  11537317.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol    open    high     low   close     volume start_Time
0    WELCORP  548.00  579.30  543.85  570.80  1790229.0 2024-01-01
1    WELCORP  574.90  575.90  554.55  573.35   858090.0 2024-01-02
2    WELCORP  566.50  574.00  553.50  559.35  1072888.0 2024-01-03
3    WELCORP  559.30  571.00  554.35  558.05  1327008.0 2024-01-04
4    WELCORP  558.45  573.90  555.35  557.70   624647.0 2024-01-05
..       ...     ...     ...     ...     ...        ...        ...
216  WELCORP  746.05  764.95  730.00  734.20   979267.0 2024-11-12
217  WELCORP  728.05  735.00  686.00  690.10   754738.0 2024-11-13
218  WELCORP  689.00  703.20  673.50  678.30   623248.0 2024-11-14
219  WELCORP  680.00  699.00  671.30  675.90   436859.0 2024-11-18
220  WELCORP  679.95  702.00  676.50  686.90   786646.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close      volume start_Time
0    IRCON  172.20  176.00  171.80  174.55  17625826.0 2024-01-01
1    IRCON  175.75  177.70  169.80  174.30  13412685.0 2024-01-02
2    IRCON  175.00  189.70  172.75  187.10  86311747.0 2024-01-03
3    IRCON  188.90  190.85  184.25  185.90  24310822.0 2024-01-04
4    IRCON  186.50  187.65  181.10  184.15  11878159.0 2024-01-05
..     ...     ...     ...     ...     ...         ...        ...
216  IRCON  202.75  204.35  197.00  197.90   2572256.0 2024-11-12
217  IRCON  198.00  199.00  191.18  191.86   3409762.0 2024-11-13
218  IRCON  191.86  196.00  191.10  191.78   2923372.0 2024-11-14
219  IRCON  193.07  194.50  183.50  184.33   5421257.0 2024-11-18
220  IRCON  186.00  194.27  185.64  188.77   5769343.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol     open     high      low    close    volume start_Time
0       NH  1205.00  1215.00  1199.00  1203.40  160775.0 2024-01-01
1       NH  1212.85  1212.90  1190.00  1192.80  153930.0 2024-01-02
2       NH  1199.85  1199.85  1147.05  1170.20  251566.0 2024-01-03
3       NH  1178.90  1188.70  1162.65  1179.90  785274.0 2024-01-04
4       NH  1189.90  1224.90  1183.75  1217.45  492949.0 2024-01-05
..     ...      ...      ...      ...      ...       ...        ...
216     NH  1295.00  1319.70  1271.80  1282.85  291351.0 2024-11-12
217     NH  1272.25  1276.80  1249.70  1258.80  234460.0 2024-11-13
218     NH  1263.65  1285.80  1260.00  1276.45  559369.0 2024-11-14
219     NH  1276.45  1298.00  1255.00  1261.15  231041.0 2024-11-18
220     NH  1265.00  1275.60  1256.00  1262.00  406237.0 2024-11-19

[221 rows x 7 columns]
      Symbol    open    high     low   close    volume start_Time
0    JKPAPER  407.95  410.40  404.30  405.40  417724.0 2024-01-01
1    JKPAPER  405.50  406.90  394.15  397.60  755238.0 2024-01-02
2    JKPAPER  397.00  404.20  395.35  397.85  698355.0 2024-01-03
3    JKPAPER  399.00  401.80  397.75  400.90  460590.0 2024-01-04
4    JKPAPER  401.90  403.75  395.25  396.85  661852.0 2024-01-05
..       ...     ...     ...     ...     ...       ...        ...
216  JKPAPER  430.50  441.00  417.50  418.60  466500.0 2024-11-12
217  JKPAPER  418.60  421.90  407.00  408.30  378037.0 2024-11-13
218  JKPAPER  410.00  416.40  395.30  397.20  606041.0 2024-11-14
219  JKPAPER  397.40  402.95  388.10  400.35  314385.0 2024-11-18
220  JKPAPER  404.80  414.45  403.35  409.90  297158.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol    open    high     low   close     volume start_Time
0    GRANULES  407.00  417.85  404.10  411.80  3168914.0 2024-01-01
1    GRANULES  413.00  426.00  411.30  420.60  3696477.0 2024-01-02
2    GRANULES  424.10  424.85  418.10  419.95  1510400.0 2024-01-03
3    GRANULES  421.35  422.35  415.55  417.45   795773.0 2024-01-04
4    GRANULES  419.00  420.45  409.05  413.65   878386.0 2024-01-05
..        ...     ...     ...     ...     ...        ...        ...
216  GRANULES  572.60  581.30  558.00  562.15  1401163.0 2024-11-12
217  GRANULES  560.00  560.00  530.10  532.40  1750943.0 2024-11-13
218  GRANULES  536.05  545.40  526.80  533.90  1097209.0 2024-11-14
219  GRANULES  533.00  544.00  522.65  529.10  1787942.0 2024-11-18
220  GRANULES  530.05  556.00  530.05  552.65  3282793.0 2024-11-19

[221 rows x 7 columns]
      Symbol   open   high    low  close       volume start_Time
0    YESBANK  21.50  23.00  21.40  22.65  577972312.0 2024-01-01
1    YESBANK  22.70  23.70  22.30  23.20  618101025.0 2024-01-02
2    YESBANK  23.25  23.75  22.75  22.90  378099590.0 2024-01-03
3    YESBANK  23.05  23.60  22.90  23.25  271346506.0 2024-01-04
4    YESBANK  23.35  24.30  23.25  24.00  561257556.0 2024-01-05
..       ...    ...    ...    ...    ...          ...        ...
216  YESBANK  19.95  20.14  19.65  19.75   44546382.0 2024-11-12
217  YESBANK  19.63  19.73  19.02  19.07   80085697.0 2024-11-13
218  YESBANK  19.20  19.63  19.20  19.31   67917020.0 2024-11-14
219  YESBANK  19.29  19.50  19.15  19.28   61476591.0 2024-11-18
220  YESBANK  19.33  19.82  19.28  19.56   57492511.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol     open    high      low    close    volume start_Time
0    MEDANTA   965.40   967.0   947.20   951.35  138433.0 2024-01-01
1    MEDANTA   951.30   957.0   941.85   944.55  147467.0 2024-01-02
2    MEDANTA   943.00   965.0   938.45   959.00  168149.0 2024-01-03
3    MEDANTA   959.00  1000.0   959.00   990.25  343491.0 2024-01-04
4    MEDANTA  1000.00  1022.8   996.00  1001.85  299322.0 2024-01-05
..       ...      ...     ...      ...      ...       ...        ...
216  MEDANTA  1079.00  1083.0  1040.00  1059.20  110371.0 2024-11-12
217  MEDANTA  1045.95  1054.8  1016.60  1032.55  190702.0 2024-11-13
218  MEDANTA  1033.95  1083.7  1018.00  1071.95  529762.0 2024-11-14
219  MEDANTA  1075.05  1089.0  1053.95  1080.90  203555.0 2024-11-18
220  MEDANTA  1080.95  1100.7  1067.45  1091.90  186115.0 2024-11-19

[221 rows x 7 columns]
     Symbol    open    high     low   close     volume start_Time
0    BIKAJI  546.00  556.00  543.05  546.40   145982.0 2024-01-01
1    BIKAJI  548.30  559.00  545.55  553.90   156524.0 2024-01-02
2    BIKAJI  553.70  558.25  548.00  550.95   103818.0 2024-01-03
3    BIKAJI  552.90  574.90  552.60  567.55   524870.0 2024-01-04
4    BIKAJI  570.00  585.00  568.90  573.35  1276363.0 2024-01-05
..      ...     ...     ...     ...     ...        ...        ...
216  BIKAJI  862.40  874.35  845.90  849.95   130951.0 2024-11-12
217  BIKAJI  845.00  848.70  819.20  822.85   274087.0 2024-11-13
218  BIKAJI  815.00  830.00  782.05  786.60   472139.0 2024-11-14
219  BIKAJI  786.00  790.00  755.00  758.15   523977.0 2024-11-18
220  BIKAJI  760.25  766.70  735.00  739.35   545505.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol     open     high      low    close    volume start_Time
0    CLEAN  1557.00  1622.00  1556.95  1591.20  488216.0 2024-01-01
1    CLEAN  1601.00  1619.45  1570.50  1574.75  322107.0 2024-01-02
2    CLEAN  1574.75  1589.85  1563.00  1570.55  118458.0 2024-01-03
3    CLEAN  1577.00  1588.00  1563.00  1568.00   90087.0 2024-01-04
4    CLEAN  1574.00  1588.00  1560.00  1571.55  106308.0 2024-01-05
..     ...      ...      ...      ...      ...       ...        ...
216  CLEAN  1395.75  1406.50  1355.40  1361.20   77153.0 2024-11-12
217  CLEAN  1360.00  1366.75  1305.00  1308.65  144625.0 2024-11-13
218  CLEAN  1310.00  1338.20  1290.25  1298.65  123160.0 2024-11-14
219  CLEAN  1311.00  1311.40  1280.80  1283.85   81259.0 2024-11-18
220  CLEAN  1285.50  1313.95  1285.00  1290.75   52234.0 2024-11-19

[221 rows x 7 columns]
     Symbol    open    high     low   close      volume start_Time
0    ZOMATO  124.45  125.60  122.85  124.50  24228685.0 2024-01-01
1    ZOMATO  127.00  129.45  125.50  128.70  69395959.0 2024-01-02
2    ZOMATO  128.80  130.25  127.10  127.55  39101172.0 2024-01-03
3    ZOMATO  128.40  130.90  126.45  129.75  45285624.0 2024-01-04
4    ZOMATO  130.90  134.35  128.95  133.30  55608923.0 2024-01-05
..      ...     ...     ...     ...     ...         ...        ...
216  ZOMATO  259.95  264.90  255.30  260.99  50975031.0 2024-11-12
217  ZOMATO  258.08  263.43  254.53  258.40  61475328.0 2024-11-13
218  ZOMATO  261.50  271.00  260.70  269.66  84971093.0 2024-11-14
219  ZOMATO  274.30  274.40  269.36  270.79  59799056.0 2024-11-18
220  ZOMATO  271.94  272.70  267.66  271.36  42992794.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

     Symbol   open   high    low  close       volume start_Time
0    SUZLON  38.50  38.60  38.00  38.50   35078873.0 2024-01-01
1    SUZLON  38.70  38.80  37.10  38.25   30864924.0 2024-01-02
2    SUZLON  38.25  38.25  37.70  37.80   21788140.0 2024-01-03
3    SUZLON  37.80  39.30  37.75  38.70   38232279.0 2024-01-04
4    SUZLON  38.90  40.60  38.70  40.60   75799676.0 2024-01-05
..      ...    ...    ...    ...    ...          ...        ...
216  SUZLON  62.16  62.87  59.10  59.39   67563924.0 2024-11-12
217  SUZLON  58.00  59.28  53.45  54.03  194511406.0 2024-11-13
218  SUZLON  54.03  56.73  53.65  56.73   56957801.0 2024-11-14
219  SUZLON  59.45  59.56  56.80  59.26  119110598.0 2024-11-18
220  SUZLON  60.50  62.22  59.42  62.22   74476083.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close     volume start_Time
0      ACI  653.40  677.10  646.00  647.20   793927.0 2024-01-01
1      ACI  650.85  659.80  638.70  644.75   425081.0 2024-01-02
2      ACI  641.00  656.00  640.00  646.85   368123.0 2024-01-03
3      ACI  649.70  658.85  644.00  648.60   416363.0 2024-01-04
4      ACI  653.00  667.75  635.00  637.35  1145373.0 2024-01-05
..     ...     ...     ...     ...     ...        ...        ...
216    ACI  686.00  696.80  670.30  687.85   370820.0 2024-11-12
217    ACI  685.00  685.00  659.25  676.20   317135.0 2024-11-13
218    ACI  671.65  694.50  670.50  679.80   248870.0 2024-11-14
219    ACI  671.45  691.80  670.85  688.90   229309.0 2024-11-18
220    ACI  694.85  703.90  670.20  677.90   321352.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

     Symbol   open   high    low  close      volume start_Time
0    RENUKA  47.40  48.30  47.20  47.40   7332647.0 2024-01-01
1    RENUKA  47.50  47.55  46.70  47.20   6116139.0 2024-01-02
2    RENUKA  47.25  47.50  46.85  46.95   4597424.0 2024-01-03
3    RENUKA  47.30  47.65  47.00  47.10   5122343.0 2024-01-04
4    RENUKA  47.20  48.25  47.00  47.25  12825105.0 2024-01-05
..      ...    ...    ...    ...    ...         ...        ...
216  RENUKA  41.90  42.39  40.51  40.75   6447215.0 2024-11-12
217  RENUKA  40.65  40.76  39.55  39.82   6553569.0 2024-11-13
218  RENUKA  39.98  40.49  39.75  40.08   5843842.0 2024-11-14
219  RENUKA  40.47  40.47  39.00  39.56   6076995.0 2024-11-18
220  RENUKA  40.09  40.59  39.56  39.86   4995830.0 2024-11-19

[221 rows x 7 columns]
       Symbol    open    high     low   close     volume start_Time
0    FIVESTAR  740.00  741.50  729.25  734.70   145695.0 2024-01-01
1    FIVESTAR  737.10  738.00  722.20  725.30   268560.0 2024-01-02
2    FIVESTAR  722.05  725.35  705.10  723.70   306414.0 2024-01-03
3    FIVESTAR  727.90  735.00  715.00  722.55   199800.0 2024-01-04
4    FIVESTAR  726.00  735.80  725.00  733.95   184113.0 2024-01-05
..        ...     ...     ...     ...     ...        ...        ...
216  FIVESTAR  632.80  646.15  632.10  638.65   491484.0 2024-11-12
217  FIVESTAR  638.65  650.00  636.55  642.75  1285450.0 2024-11-13
218  FIVESTAR  642.80  651.25  637.65  647.70   584041.0 2024-11-14
219  FIVESTAR  650.00  650.00  626.65  638.70   430758.0 2024-11-18
220  FIVESTAR  643.30  649.00  626.00  636.35  1983140.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

     Symbol     open     high      low    close    volume start_Time
0    KAYNES  2600.00  2680.10  2600.00  2669.05   74461.0 2024-01-01
1    KAYNES  2680.00  2692.45  2605.00  2663.30   83254.0 2024-01-02
2    KAYNES  2660.00  2664.65  2481.05  2555.95  483749.0 2024-01-03
3    KAYNES  2625.00  2640.00  2445.05  2521.00  366474.0 2024-01-04
4    KAYNES  2549.65  2588.95  2523.00  2556.25   75701.0 2024-01-05
..      ...      ...      ...      ...      ...       ...        ...
216  KAYNES  5655.00  5848.15  5647.15  5728.85  465960.0 2024-11-12
217  KAYNES  5720.00  5720.00  5412.90  5437.90  352496.0 2024-11-13
218  KAYNES  5450.00  5583.15  5351.35  5538.15  398853.0 2024-11-14
219  KAYNES  5551.00  5674.00  5494.60  5622.65  330582.0 2024-11-18
220  KAYNES  5665.95  5980.00  5612.70  5775.85  633187.0 2024-11-19

[221 rows x 7 columns]
      Symbol    open    high     low   close      volume start_Time
0    GMDCLTD  409.45  439.95  407.90  432.75  15590376.0 2024-01-01
1    GMDCLTD  435.50  447.00  422.35  433.60   9875294.0 2024-01-02
2    GMDCLTD  435.80  445.00  430.05  432.35   6910138.0 2024-01-03
3    GMDCLTD  434.95  445.00  433.50  439.00   5650960.0 2024-01-04
4    GMDCLTD  451.00  461.35  441.30  450.05  10605503.0 2024-01-05
..       ...     ...     ...     ...     ...         ...        ...
216  GMDCLTD  349.35  361.50  343.10  344.75   1089301.0 2024-11-12
217  GMDCLTD  344.00  346.80  327.70  329.65    793101.0 2024-11-13
218  GMDCLTD  330.95  336.90  329.70  330.65    550101.0 2024-11-14
219  GMDCLTD  330.50  333.00  323.60  327.20    843700.0 2024-11-18
220  GMDCLTD  330.95  347.45  330.70  334.85   1646321.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol     open     high      low    close     volume start_Time
0    INDUSINDBK  1598.95  1611.40  1591.80  1598.85  1341121.0 2024-01-01
1    INDUSINDBK  1594.10  1598.25  1570.00  1575.60  1227193.0 2024-01-02
2    INDUSINDBK  1575.50  1604.95  1558.00  1601.15  2620296.0 2024-01-03
3    INDUSINDBK  1593.00  1655.00  1593.00  1648.55  4271262.0 2024-01-04
4    INDUSINDBK  1654.00  1654.00  1629.00  1643.20  2294140.0 2024-01-05
..          ...      ...      ...      ...      ...        ...        ...
216  INDUSINDBK  1061.30  1065.45  1051.55  1059.55  2186055.0 2024-11-12
217  INDUSINDBK  1053.80  1067.80  1032.20  1036.70  4850346.0 2024-11-13
218  INDUSINDBK  1043.00  1045.00  1015.00  1017.15  2612235.0 2024-11-14
219  INDUSINDBK  1015.50  1017.95  1000.05  1004.60  5427908.0 2024-11-18
220  INDUSINDBK  1010.50  1032.00   998.10  1000.20  5718490.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open     high      low    close     volume start_Time
0      GLS   659.00   660.00   652.10   655.20    60771.0 2024-01-01
1      GLS   659.45   719.95   655.65   714.20  1648198.0 2024-01-02
2      GLS   721.80   735.75   700.70   729.90   388117.0 2024-01-03
3      GLS   732.00   735.00   716.40   725.50   204137.0 2024-01-04
4      GLS   721.00   728.85   693.05   697.65   187024.0 2024-01-05
..     ...      ...      ...      ...      ...        ...        ...
216    GLS  1076.25  1121.00  1075.00  1099.25    88602.0 2024-11-12
217    GLS  1100.00  1105.75  1052.50  1059.75    74345.0 2024-11-13
218    GLS  1040.00  1102.00  1040.00  1082.60    72185.0 2024-11-14
219    GLS  1082.60  1100.00  1051.55  1081.55   106571.0 2024-11-18
220    GLS  1083.00  1103.80  1070.20  1082.90    68207.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol    open    high     low   close     volume start_Time
0    DEVYANI  193.90  194.85  191.45  191.75  1006774.0 2024-01-01
1    DEVYANI  191.95  192.40  188.70  190.05   933725.0 2024-01-02
2    DEVYANI  189.95  192.00  188.85  190.45   876505.0 2024-01-03
3    DEVYANI  190.80  191.30  189.00  189.70  1671244.0 2024-01-04
4    DEVYANI  189.80  190.60  185.90  186.35  2423940.0 2024-01-05
..       ...     ...     ...     ...     ...        ...        ...
216  DEVYANI  176.40  176.40  170.71  172.26  1401419.0 2024-11-12
217  DEVYANI  170.10  172.55  165.02  169.09  2968769.0 2024-11-13
218  DEVYANI  167.55  172.03  163.14  163.96  1437981.0 2024-11-14
219  DEVYANI  164.53  165.00  160.55  160.97   441990.0 2024-11-18
220  DEVYANI  161.59  164.51  160.56  162.58  1366262.0 2024-11-19

[221 rows x 7 columns]
         Symbol    open    high     low   close    volume start_Time
0    ASAHIINDIA  578.95  587.00  567.10  569.75  167523.0 2024-01-01
1    ASAHIINDIA  575.00  588.10  561.05  582.75  743574.0 2024-01-02
2    ASAHIINDIA  583.50  587.20  573.00  580.95  123174.0 2024-01-03
3    ASAHIINDIA  580.95  584.15  573.10  575.40   59734.0 2024-01-04
4    ASAHIINDIA  580.00  580.00  567.20  570.10  166235.0 2024-01-05
..          ...     ...     ...     ...     ...       ...        ...
216  ASAHIINDIA  693.00  708.70  678.00  680.95   91510.0 2024-11-12
217  ASAHIINDIA  680.95  683.05  651.20  657.25   95774.0 2024-11-13
218  ASAHIINDIA  654.20  670.95  654.20  665.65   52612.0 2024-11-14
219  ASAHIINDIA  662.00  663.85  642.45  650.90  109885.0 2024-11-18
220  ASAHIINDIA  641.80  663.95  638.00  656.50   73932.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol     open     high      low    close    volume start_Time
0    AAVAS  1538.00  1565.00  1528.00  1561.20  238095.0 2024-01-01
1    AAVAS  1565.15  1583.15  1552.45  1575.45  397197.0 2024-01-02
2    AAVAS  1583.15  1583.15  1564.00  1567.70  152707.0 2024-01-03
3    AAVAS  1575.50  1584.20  1562.20  1571.20  108469.0 2024-01-04
4    AAVAS  1571.40  1578.95  1561.55  1566.05   81430.0 2024-01-05
..     ...      ...      ...      ...      ...       ...        ...
216  AAVAS  1656.30  1665.00  1650.00  1654.55   59869.0 2024-11-12
217  AAVAS  1642.00  1672.35  1640.00  1659.25  116513.0 2024-11-13
218  AAVAS  1666.05  1690.70  1644.55  1650.20   87443.0 2024-11-14
219  AAVAS  1650.25  1658.90  1635.05  1641.20  149637.0 2024-11-18
220  AAVAS  1640.25  1669.20  1640.00  1640.55  207356.0 2024-11-19

[221 rows x 7 columns]
     Symbol    open    high     low   close    volume start_Time
0    NUVOCO  383.00  386.10  376.55  377.20  276052.0 2024-01-01
1    NUVOCO  379.85  379.85  371.00  372.25  253608.0 2024-01-02
2    NUVOCO  373.90  377.85  364.00  364.70  514031.0 2024-01-03
3    NUVOCO  365.95  371.90  364.70  370.15  270931.0 2024-01-04
4    NUVOCO  371.95  372.80  363.05  367.10  203717.0 2024-01-05
..      ...     ...     ...     ...     ...       ...        ...
216  NUVOCO  344.20  346.70  338.35  341.45   38516.0 2024-11-12
217  NUVOCO  338.00  338.10  327.50  328.60   74296.0 2024-11-13
218  NUVOCO  328.00  336.95  327.40  335.05   72647.0 2024-11-14
219  NUVOCO  333.30  336.00  327.70  334.25   64406.0 2024-11-18
220  NUVOCO  335.20  343.45  334.40  338.05   80050.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol    open    high     low   close    volume start_Time
0    APTUS  320.90  336.65  319.90  330.10  342938.0 2024-01-01
1    APTUS  335.00  335.00  324.60  329.25  455560.0 2024-01-02
2    APTUS  329.00  331.30  320.95  324.05  740745.0 2024-01-03
3    APTUS  324.05  331.00  323.50  329.95  183084.0 2024-01-04
4    APTUS  330.05  333.30  326.40  331.45  268398.0 2024-01-05
..     ...     ...     ...     ...     ...       ...        ...
216  APTUS  332.60  336.20  326.15  327.45  326192.0 2024-11-12
217  APTUS  325.05  328.25  315.05  317.15  854049.0 2024-11-13
218  APTUS  318.00  323.35  314.25  316.80  478334.0 2024-11-14
219  APTUS  316.00  317.90  310.05  315.95  274731.0 2024-11-18
220  APTUS  317.05  319.35  311.20  313.70  353844.0 2024-11-19

[221 rows x 7 columns]
         Symbol    open    high     low   close     volume start_Time
0    CHEMPLASTS  499.95  504.90  486.05  488.25   114011.0 2024-01-01
1    CHEMPLASTS  493.00  504.45  481.50  502.85   150082.0 2024-01-02
2    CHEMPLASTS  503.00  515.05  499.25  510.05  1152596.0 2024-01-03
3    CHEMPLASTS  512.55  522.05  510.80  517.00   879732.0 2024-01-04
4    CHEMPLASTS  520.30  522.65  510.00  518.65   144201.0 2024-01-05
..          ...     ...     ...     ...     ...        ...        ...
216  CHEMPLASTS  492.00  492.00  475.45  481.55   105424.0 2024-11-12
217  CHEMPLASTS  480.00  486.50  468.00  474.80   185979.0 2024-11-13
218  CHEMPLASTS  473.00  486.55  471.00  482.20   195986.0 2024-11-14
219  CHEMPLASTS  480.00  485.95  474.90  482.55    69439.0 2024-11-18
220  CHEMPLASTS  483.00  494.00  482.65  488.35    94188.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

    Symbol     open     high      low    close    volume start_Time
0     GRSE   874.00   886.80   870.00   873.80  604835.0 2024-01-01
1     GRSE   878.65   878.65   851.10   865.00  465924.0 2024-01-02
2     GRSE   865.00   877.00   860.05   868.05  537995.0 2024-01-03
3     GRSE   872.40   889.90   860.10   863.70  952233.0 2024-01-04
4     GRSE   867.90   877.00   856.75   863.60  422997.0 2024-01-05
..     ...      ...      ...      ...      ...       ...        ...
216   GRSE  1499.95  1523.00  1458.15  1462.55  273441.0 2024-11-12
217   GRSE  1454.00  1457.30  1370.00  1384.20  703813.0 2024-11-13
218   GRSE  1438.40  1470.00  1375.00  1406.40  828483.0 2024-11-14
219   GRSE  1428.85  1432.95  1371.10  1387.40  500890.0 2024-11-18
220   GRSE  1422.00  1456.00  1401.40  1409.25  411727.0 2024-11-19

[221 rows x 7 columns]
     Symbol     open     high      low    close    volume start_Time
0    VIJAYA   675.00   684.15   645.35   675.50  304374.0 2024-01-01
1    VIJAYA   669.00   691.55   658.65   677.60  209975.0 2024-01-02
2    VIJAYA   676.00   676.00   660.00   662.30   99155.0 2024-01-03
3    VIJAYA   669.50   670.25   651.70   666.15  132547.0 2024-01-04
4    VIJAYA   669.30   683.45   668.50   675.70  157911.0 2024-01-05
..      ...      ...      ...      ...      ...       ...        ...
216  VIJAYA  1070.00  1086.00  1057.50  1069.75  223222.0 2024-11-12
217  VIJAYA  1058.70  1074.15  1012.70  1017.05  178071.0 2024-11-13
218  VIJAYA  1017.05  1055.00  1015.00  1038.20  268333.0 2024-11-14
219  VIJAYA  1047.00  1075.40  1003.40  1009.05  108004.0 2024-11-18
220  VIJAYA  1001.00  1073.90  1001.00  1068.75  580125.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol    open    high     low   close     volume start_Time
0    SWSOLAR  439.00  453.95  436.80  445.50  2852672.0 2024-01-01
1    SWSOLAR  449.10  452.00  434.00  441.90  1455721.0 2024-01-02
2    SWSOLAR  445.15  461.00  445.15  448.80  2683355.0 2024-01-03
3    SWSOLAR  452.00  455.80  441.25  445.20  1047368.0 2024-01-04
4    SWSOLAR  447.70  450.00  443.00  448.10   879774.0 2024-01-05
..       ...     ...     ...     ...     ...        ...        ...
216  SWSOLAR  536.15  539.00  509.35  509.35  1985520.0 2024-11-12
217  SWSOLAR  500.00  506.00  483.90  483.90  3960068.0 2024-11-13
218  SWSOLAR  468.35  502.00  468.35  490.65  1566988.0 2024-11-14
219  SWSOLAR  491.00  496.80  473.70  477.05   914714.0 2024-11-18
220  SWSOLAR  479.90  500.90  472.10  476.10  1769604.0 2024-11-19

[221 rows x 7 columns]
       Symbol     open     high      low    close    volume start_Time
0    ASTRAZEN  5500.00  5690.00  5500.00  5645.40   30202.0 2024-01-01
1    ASTRAZEN  5612.10  5759.00  5523.00  5698.05   30876.0 2024-01-02
2    ASTRAZEN  5698.05  5796.00  5650.00  5686.35   21464.0 2024-01-03
3    ASTRAZEN  5686.05  5732.00  5556.90  5586.45   10189.0 2024-01-04
4    ASTRAZEN  5586.45  5677.95  5510.00  5563.05    9652.0 2024-01-05
..        ...      ...      ...      ...      ...       ...        ...
216  ASTRAZEN  7255.00  7777.00  7216.55  7404.55  129683.0 2024-11-12
217  ASTRAZEN  7390.00  7390.00  7095.35  7128.65   22936.0 2024-11-13
218  ASTRAZEN  7100.00  7130.75  6680.35  6772.95   66156.0 2024-11-14
219  ASTRAZEN  6735.05  6773.50  6359.10  6415.65   33447.0 2024-11-18
220  ASTRAZEN  6490.50  6599.95  6453.45  6496.65   29174.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol    open    high     low   close     volume start_Time
0    J&KBANK  124.40  127.70  123.25  124.75  4601461.0 2024-01-01
1    J&KBANK  125.00  126.50  122.80  124.40  2910411.0 2024-01-02
2    J&KBANK  123.60  126.90  123.50  124.95  2691493.0 2024-01-03
3    J&KBANK  126.25  129.80  126.00  128.95  7174363.0 2024-01-04
4    J&KBANK  130.60  131.60  127.55  129.70  4912064.0 2024-01-05
..       ...     ...     ...     ...     ...        ...        ...
216  J&KBANK  102.00  103.30   99.15   99.59  1779312.0 2024-11-12
217  J&KBANK   99.00  100.48   95.50   95.96  3305153.0 2024-11-13
218  J&KBANK   96.00   97.50   94.55   95.07  2603551.0 2024-11-14
219  J&KBANK   96.00   96.87   92.66   93.33  3270153.0 2024-11-18
220  J&KBANK   94.00   98.78   94.00   95.86  3219160.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close     volume start_Time
0      CUB  149.90  152.90  149.25  152.25  4698244.0 2024-01-01
1      CUB  152.95  153.65  149.30  151.20  3160012.0 2024-01-02
2      CUB  150.95  154.20  150.70  152.95  3998380.0 2024-01-03
3      CUB  153.90  154.80  152.50  153.85  2842465.0 2024-01-04
4      CUB  154.00  154.90  152.25  153.15  3280827.0 2024-01-05
..     ...     ...     ...     ...     ...        ...        ...
216    CUB  175.00  176.50  173.25  174.14  4540898.0 2024-11-12
217    CUB  173.80  174.80  169.23  170.67  4106697.0 2024-11-13
218    CUB  170.66  173.25  170.65  172.27  4229357.0 2024-11-14
219    CUB  170.10  173.15  168.50  171.24  3137876.0 2024-11-18
220    CUB  172.13  174.59  169.67  170.57  3102692.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

     Symbol     open     high      low    close    volume start_Time
0    CYIENT  2315.10  2356.00  2292.00  2300.80  140667.0 2024-01-01
1    CYIENT  2277.00  2349.85  2262.00  2308.15  172597.0 2024-01-02
2    CYIENT  2310.25  2337.95  2252.15  2285.10  130542.0 2024-01-03
3    CYIENT  2316.50  2321.70  2261.20  2267.20  107331.0 2024-01-04
4    CYIENT  2275.50  2275.50  2222.00  2235.30  199278.0 2024-01-05
..      ...      ...      ...      ...      ...       ...        ...
216  CYIENT  1882.05  1882.05  1812.35  1820.80  174524.0 2024-11-12
217  CYIENT  1817.80  1838.40  1791.00  1795.40  152479.0 2024-11-13
218  CYIENT  1794.00  1825.00  1786.15  1801.60  130458.0 2024-11-14
219  CYIENT  1780.00  1805.95  1742.85  1776.85  186966.0 2024-11-18
220  CYIENT  1793.70  1823.95  1783.65  1813.20  163087.0 2024-11-19

[221 rows x 7 columns]
       Symbol     open     high      low    close      volume start_Time
0    AXISBANK  1095.00  1104.00  1093.00  1097.70   4083732.0 2024-01-01
1    AXISBANK  1095.10  1099.35  1082.30  1093.25   7895577.0 2024-01-02
2    AXISBANK  1091.00  1102.60  1081.30  1098.60  10225290.0 2024-01-03
3    AXISBANK  1103.00  1130.00  1100.05  1123.40  11411683.0 2024-01-04
4    AXISBANK  1124.00  1139.90  1119.00  1136.95   8025466.0 2024-01-05
..        ...      ...      ...      ...      ...         ...        ...
216  AXISBANK  1171.65  1187.00  1153.80  1158.15   9606088.0 2024-11-12
217  AXISBANK  1151.90  1165.50  1135.10  1139.15   8079113.0 2024-11-13
218  AXISBANK  1137.55  1150.75  1131.60  1140.70   5975873.0 2024-11-14
219  AXISBANK  1131.20  1135.00  1121.55  1126.20   9474971.0 2024-11-18
220  AXISBANK  1130.00  1139.00  1122.05  1133.95  19225966.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

        Symbol    open    high     low   close    volume start_Time
0    INTELLECT  835.00  837.00  826.00  829.05  111419.0 2024-01-01
1    INTELLECT  833.50  841.05  799.30  819.15  732411.0 2024-01-02
2    INTELLECT  818.00  844.00  815.00  826.80  568706.0 2024-01-03
3    INTELLECT  828.00  846.80  817.00  818.60  236926.0 2024-01-04
4    INTELLECT  824.10  827.35  814.00  822.50  207583.0 2024-01-05
..         ...     ...     ...     ...     ...       ...        ...
216  INTELLECT  746.65  751.80  730.00  731.70  103285.0 2024-11-12
217  INTELLECT  729.70  735.20  715.00  717.05  156123.0 2024-11-13
218  INTELLECT  720.65  734.80  708.45  722.40  192863.0 2024-11-14
219  INTELLECT  728.90  731.95  707.35  718.50  171305.0 2024-11-18
220  INTELLECT  725.00  734.05  710.00  717.00  169550.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open     high      low    close      volume start_Time
0     ATGL   992.40  1013.90   983.50  1000.95   1726490.0 2024-01-01
1     ATGL  1005.05  1014.90   985.20  1000.90   2907798.0 2024-01-02
2     ATGL  1078.95  1100.95  1032.20  1099.30  17295243.0 2024-01-03
3     ATGL  1140.00  1159.80  1094.10  1115.10   6280871.0 2024-01-04
4     ATGL  1115.40  1117.00  1080.00  1090.55   2558514.0 2024-01-05
..     ...      ...      ...      ...      ...         ...        ...
216   ATGL   700.05   713.25   697.60   701.20    259021.0 2024-11-12
217   ATGL   701.00   706.90   673.55   678.90    439495.0 2024-11-13
218   ATGL   687.10   693.70   677.65   683.90    283810.0 2024-11-14
219   ATGL   665.00   673.00   652.15   669.90   1135461.0 2024-11-18
220   ATGL   665.00   683.70   662.30   671.75    353628.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

     Symbol     open     high      low    close    volume start_Time
0    SAFARI  1940.00  1951.35  1884.00  1889.05  239503.0 2024-01-01
1    SAFARI  1891.95  1912.60  1844.20  1868.10  148508.0 2024-01-02
2    SAFARI  1868.00  1886.80  1845.10  1881.00   67719.0 2024-01-03
3    SAFARI  1882.20  1939.45  1873.60  1932.30  129861.0 2024-01-04
4    SAFARI  1943.15  1959.60  1928.20  1944.50   98177.0 2024-01-05
..      ...      ...      ...      ...      ...       ...        ...
216  SAFARI  2292.00  2331.90  2272.45  2317.55   33425.0 2024-11-12
217  SAFARI  2290.00  2309.85  2217.05  2300.20   51026.0 2024-11-13
218  SAFARI  2298.35  2343.35  2236.00  2333.45   38456.0 2024-11-14
219  SAFARI  2333.80  2366.10  2290.00  2355.75   33051.0 2024-11-18
220  SAFARI  2375.00  2489.90  2349.55  2476.35   61989.0 2024-11-19

[221 rows x 7 columns]
     Symbol     open     high      low    close     volume start_Time
0    360ONE   709.85   714.40   693.00   702.85   175009.0 2024-01-01
1    360ONE   695.25   699.95   675.00   676.90   348865.0 2024-01-02
2    360ONE   681.10   682.05   652.90   655.25   203415.0 2024-01-03
3    360ONE   660.00   662.05   651.25   653.85   133259.0 2024-01-04
4    360ONE   653.85   664.95   644.05   662.45  1231143.0 2024-01-05
..      ...      ...      ...      ...      ...        ...        ...
216  360ONE  1055.20  1058.80  1033.55  1038.75   191794.0 2024-11-12
217  360ONE  1035.50  1035.50  1005.05  1016.80   220799.0 2024-11-13
218  360ONE  1001.05  1054.25  1001.05  1050.40   433088.0 2024-11-14
219  360ONE  1051.00  1060.00  1031.50  1048.05   282451.0 2024-11-18
220  360ONE  1051.15  1075.50  1039.05  1065.50   235557.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol    open    high     low   close    volume start_Time
0    TRIVENI  345.05  349.00  342.10  345.10  518097.0 2024-01-01
1    TRIVENI  346.05  346.95  337.30  339.70  350186.0 2024-01-02
2    TRIVENI  341.00  341.60  337.65  338.65  263244.0 2024-01-03
3    TRIVENI  340.00  344.05  338.50  341.00  320282.0 2024-01-04
4    TRIVENI  340.10  344.60  338.50  341.15  298937.0 2024-01-05
..       ...     ...     ...     ...     ...       ...        ...
216  TRIVENI  403.00  407.90  387.50  391.20  423551.0 2024-11-12
217  TRIVENI  391.20  391.75  378.00  379.05  293740.0 2024-11-13
218  TRIVENI  378.00  388.15  374.10  377.50  302717.0 2024-11-14
219  TRIVENI  372.00  377.50  366.10  367.40  286450.0 2024-11-18
220  TRIVENI  369.20  380.00  363.20  365.70  355410.0 2024-11-19

[221 rows x 7 columns]
     Symbol     open     high      low    close    volume start_Time
0    AIAENG  3707.95  3709.80  3655.00  3684.10   20291.0 2024-01-01
1    AIAENG  3703.50  3703.50  3591.00  3630.30   24277.0 2024-01-02
2    AIAENG  3620.50  3632.05  3550.05  3560.95  113777.0 2024-01-03
3    AIAENG  3579.00  3617.45  3525.75  3602.90   72899.0 2024-01-04
4    AIAENG  3602.00  3625.50  3580.00  3624.35   39916.0 2024-01-05
..      ...      ...      ...      ...      ...       ...        ...
216  AIAENG  3630.10  3630.10  3520.60  3534.00  140414.0 2024-11-12
217  AIAENG  3515.25  3546.10  3489.15  3514.70   26506.0 2024-11-13
218  AIAENG  3518.20  3526.75  3418.25  3430.90   29275.0 2024-11-14
219  AIAENG  3430.90  3560.00  3366.50  3406.80   29152.0 2024-11-18
220  AIAENG  3416.75  3489.75  3411.95  3447.45   48401.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

      Symbol     open     high      low    close     volume start_Time
0    PVRINOX  1671.00  1674.50  1656.30  1660.40   327117.0 2024-01-01
1    PVRINOX  1671.05  1675.00  1647.95  1667.80   369868.0 2024-01-02
2    PVRINOX  1672.00  1720.60  1667.00  1713.80   991740.0 2024-01-03
3    PVRINOX  1720.00  1720.00  1656.40  1665.05  1275014.0 2024-01-04
4    PVRINOX  1678.30  1678.80  1638.00  1649.30   782358.0 2024-01-05
..       ...      ...      ...      ...      ...        ...        ...
216  PVRINOX  1465.00  1502.50  1464.95  1478.60   338471.0 2024-11-12
217  PVRINOX  1475.00  1495.00  1435.00  1443.35   164139.0 2024-11-13
218  PVRINOX  1449.15  1479.00  1447.00  1461.55   527499.0 2024-11-14
219  PVRINOX  1455.00  1470.80  1431.90  1435.75   825613.0 2024-11-18
220  PVRINOX  1447.90  1493.55  1444.05  1475.50   413564.0 2024-11-19

[221 rows x 7 columns]
    Symbol    open    high     low   close     volume start_Time
0     GSPL  307.50  324.35  306.10  320.10  4231364.0 2024-01-01
1     GSPL  321.80  335.40  319.25  330.10  6360561.0 2024-01-02
2     GSPL  329.80  331.40  323.30  326.00  1192282.0 2024-01-03
3     GSPL  327.00  337.00  323.15  334.10  2282546.0 2024-01-04
4     GSPL  334.00  339.50  332.10  334.00  1176568.0 2024-01-05
..     ...     ...     ...     ...     ...        ...        ...
216   GSPL  385.00  388.75  370.80  372.15   699537.0 2024-11-12
217   GSPL  370.80  371.65  357.30  359.85  1048455.0 2024-11-13
218   GSPL  357.25  362.70  350.00  351.20  1445877.0 2024-11-14
219   GSPL  349.00  349.00  322.20  324.50  3179455.0 2024-11-18
220   GSPL  325.00  329.70  321.05  325.25  2004863.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol    open    high     low   close       volume start_Time
0    NATIONALUM  132.70  138.85  132.15  136.15   43783940.0 2024-01-01
1    NATIONALUM  136.60  139.85  131.80  139.05   51857420.0 2024-01-02
2    NATIONALUM  138.50  138.50  129.30  129.85   59450714.0 2024-01-03
3    NATIONALUM  131.00  132.90  129.65  130.50   22117963.0 2024-01-04
4    NATIONALUM  131.45  132.80  127.20  128.10   21198368.0 2024-01-05
..          ...     ...     ...     ...     ...          ...        ...
216  NATIONALUM  233.80  237.37  225.00  225.91   17481388.0 2024-11-12
217  NATIONALUM  224.00  226.99  218.60  219.69   11787326.0 2024-11-13
218  NATIONALUM  230.00  230.67  219.05  219.87   35439142.0 2024-11-14
219  NATIONALUM  226.00  247.90  225.00  239.93  107332099.0 2024-11-18
220  NATIONALUM  240.00  245.68  237.32  240.31   35673049.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open     high     low    close     volume start_Time
0      KEC   595.75   611.70  588.00   605.55  1043801.0 2024-01-01
1      KEC   605.55   607.25  596.20   601.50   186255.0 2024-01-02
2      KEC   604.55   604.55  596.00   597.05   249243.0 2024-01-03
3      KEC   600.00   605.00  589.05   590.70   349166.0 2024-01-04
4      KEC   596.00   607.40  591.75   604.30   617898.0 2024-01-05
..     ...      ...      ...     ...      ...        ...        ...
216    KEC   999.70  1028.80  994.05  1002.65   673633.0 2024-11-12
217    KEC   996.00   996.00  960.00   965.65   261798.0 2024-11-13
218    KEC   960.00  1014.85  956.75  1005.85   808131.0 2024-11-14
219    KEC  1005.85  1037.95  998.55  1006.15   781808.0 2024-11-18
220    KEC  1006.00  1022.45  988.00   994.95   337971.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

       Symbol     open     high      low    close    volume start_Time
0    JKCEMENT  3788.25  3865.00  3776.50  3827.20  118855.0 2024-01-01
1    JKCEMENT  3845.00  3864.95  3740.00  3851.40   96592.0 2024-01-02
2    JKCEMENT  3850.00  3893.00  3829.00  3847.25   36876.0 2024-01-03
3    JKCEMENT  3847.25  3932.05  3822.80  3900.00   69306.0 2024-01-04
4    JKCEMENT  3915.00  3950.30  3894.10  3930.60   44675.0 2024-01-05
..        ...      ...      ...      ...      ...       ...        ...
216  JKCEMENT  4069.95  4128.40  4039.20  4062.55   41747.0 2024-11-12
217  JKCEMENT  4024.20  4073.05  3951.05  3973.85   88885.0 2024-11-13
218  JKCEMENT  3975.00  4011.05  3938.45  3999.30   52170.0 2024-11-14
219  JKCEMENT  3970.05  4001.95  3891.45  3924.30  178190.0 2024-11-18
220  JKCEMENT  3920.00  4030.00  3916.30  3952.40   63336.0 2024-11-19

[221 rows x 7 columns]
     Symbol    open    high     low   close     volume start_Time
0    M&MFIN  277.65  279.20  274.15  275.20  2472769.0 2024-01-01
1    M&MFIN  276.00  278.00  268.60  274.70  4986465.0 2024-01-02
2    M&MFIN  274.00  280.70  272.00  275.65  7622772.0 2024-01-03
3    M&MFIN  276.05  279.65  275.65  278.00  2474932.0 2024-01-04
4    M&MFIN  279.70  283.80  275.75  277.05  6485221.0 2024-01-05
..      ...     ...     ...     ...     ...        ...        ...
216  M&MFIN  270.20  271.65  263.90  265.40  1571141.0 2024-11-12
217  M&MFIN  265.00  265.20  256.65  258.25  1538121.0 2024-11-13
218  M&MFIN  258.00  261.25  255.00  256.85  1042293.0 2024-11-14
219  M&MFIN  255.60  261.60  254.30  258.20   727558.0 2024-11-18
220  M&MFIN  258.50  264.45  258.00  259.80  1123396.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

         Symbol    open    high     low   close    volume start_Time
0    CENTURYPLY  776.00  811.00  755.10  798.40  317997.0 2024-01-01
1    CENTURYPLY  800.15  801.00  774.80  780.00  276030.0 2024-01-02
2    CENTURYPLY  783.00  791.85  772.00  773.80  108673.0 2024-01-03
3    CENTURYPLY  776.00  784.15  758.10  764.25  196493.0 2024-01-04
4    CENTURYPLY  770.00  775.50  761.65  772.30   96298.0 2024-01-05
..          ...     ...     ...     ...     ...       ...        ...
216  CENTURYPLY  815.00  821.00  795.10  798.30   37174.0 2024-11-12
217  CENTURYPLY  795.00  800.00  745.05  749.55  316263.0 2024-11-13
218  CENTURYPLY  750.00  767.95  736.50  748.65  174289.0 2024-11-14
219  CENTURYPLY  751.90  754.70  733.80  744.40  112172.0 2024-11-18
220  CENTURYPLY  735.05  762.35  729.50  735.25  106764.0 2024-11-19

[221 rows x 7 columns]
    Symbol     open     high      low    close    volume start_Time
0      KEI  3249.95  3249.95  3167.00  3192.75  147099.0 2024-01-01
1      KEI  3198.95  3225.00  3114.05  3183.30  173926.0 2024-01-02
2      KEI  3208.55  3259.95  3131.10  3226.45  175970.0 2024-01-03
3      KEI  3258.60  3415.00  3240.45  3345.90  420591.0 2024-01-04
4      KEI  3390.10  3416.00  3316.00  3380.25  163745.0 2024-01-05
..     ...      ...      ...      ...      ...       ...        ...
216    KEI  4006.00  4034.05  3960.00  3998.40  146246.0 2024-11-12
217    KEI  3940.00  3959.05  3856.00  3889.95  203014.0 2024-11-13
218    KEI  3889.95  3909.45  3780.00  3811.95  156409.0 2024-11-14
219    KEI  3817.00  3842.45  3705.00  3716.95  188200.0 2024-11-18
220    KEI  3760.00  3881.90  3715.00  3842.25  297339.0 2024-11-19

[221 rows x 7 columns]

DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.dhan.co:443 "POST /charts/historical HTTP/1.1" 200 None

        Symbol      open      high      low     close    volume start_Time
0    SOLARINDS   6781.35   6812.95  6728.95   6778.05   40189.0 2024-01-01
1    SOLARINDS   6817.00   6866.75  6603.00   6678.85   73311.0 2024-01-02
2    SOLARINDS   6728.45   6765.00  6590.00   6707.80  200360.0 2024-01-03
3    SOLARINDS   6750.00   6810.00  6680.00   6733.70   92613.0 2024-01-04
4    SOLARINDS   6787.75   6820.00  6664.10   6703.50   69701.0 2024-01-05
..         ...       ...       ...      ...       ...       ...        ...
216  SOLARINDS  10286.05  10325.00  9951.00  10019.70   30955.0 2024-11-12
217  SOLARINDS  10050.00  10096.90  9630.55   9688.35   44513.0 2024-11-13
218  SOLARINDS   9735.00  10132.00  9735.00  10008.55   58802.0 2024-11-14
219  SOLARINDS  10008.55  10242.10  9659.05   9726.40   68157.0 2024-11-18
220  SOLARINDS   9800.00  10025.00  9720.65   9983.50   49414.0 2024-11-19

[221 rows x 7 columns]
       Symbol     open     high      low    close     volume start_Time
0    KFINTECH   485.00   492.50   482.05   482.95   608311.0 2024-01-01
1    KFINTECH   484.30   489.70   479.20   481.50   669246.0 2024-01-02
2    KFINTECH   480.00   493.00   479.80   488.35   509102.0 2024-01-03
3    KFINTECH   486.00   498.00   484.15   496.55   508234.0 2024-01-04
4    KFINTECH   499.45   508.40   498.00   506.95  1241376.0 2024-01-05
..        ...      ...      ...      ...      ...        ...        ...
216  KFINTECH  1005.00  1045.95  1002.05  1020.25   534441.0 2024-11-12
217  KFINTECH  1018.70  1018.70   956.60   963.90   497140.0 2024-11-13
218  KFINTECH   963.90   983.90   963.50   977.50   410461.0 2024-11-14
219  KFINTECH   987.95   997.05   969.40   978.95   243782.0 2024-11-18
220  KFINTECH   980.60  1026.10   980.00  1013.95   674749.0 2024-11-19

[221 rows x 7 columns]

In [176]:
last_rows

,Symbol,open,high,low,close,volume,start_Time,diff,per,type,rsi14,obv,ema20,bbl,bbm,bbu,bbb,bbp,adx,psl,doji,zscore,hmid,hupper,hlower,imi
0,NYKAA,170.70,173.44,169.00,170.31,7449516.0,2024-11-19,4.44,2.627219,down,33.494799,141029562.0,179.802167,164.048316,170.234991,176.421666,7.268394,0.400189,24.006186,33.333333,100.0,-1.756421,177.108152,183.778769,170.437535,37.934540
1,AARTIIND,433.00,441.95,431.00,434.90,965128.0,2024-11-19,10.95,2.540603,up,31.285945,-24405403.0,479.776054,426.016605,435.763317,445.510029,4.473397,0.255645,31.571357,50.000000,0.0,-1.849529,428.072660,448.862260,407.283060,25.556601
2,SUNTV,732.00,749.95,727.55,740.60,306046.0,2024-11-19,22.40,3.078826,up,43.843313,27161873.0,747.299526,701.400727,721.661289,741.921852,5.614978,0.645324,23.759987,50.000000,0.0,-0.631440,718.639771,743.540173,693.739369,54.702657
3,GPIL,187.07,192.79,184.45,185.93,1081333.0,2024-11-19,8.34,4.521551,down,43.579494,11433174.0,191.540003,177.539432,185.965709,194.391986,9.062184,0.410061,13.606871,50.000000,0.0,-0.499983,186.584246,199.057912,174.110580,70.133034
4,SONATSOFTW,556.00,565.00,544.05,547.00,440708.0,2024-11-19,20.95,3.850749,down,32.562182,6891581.0,591.024555,531.570577,558.893534,586.216492,9.777518,0.228369,14.135413,16.666667,0.0,-2.318994,571.800426,596.409137,547.191715,28.891910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,M&MFIN,258.50,264.45,258.00,259.80,1123396.0,2024-11-19,6.45,2.500000,up,34.108131,-36171600.0,271.571855,251.815763,258.650849,265.485935,5.285183,0.452389,31.111326,58.333333,0.0,-1.604463,259.966832,276.009243,243.924421,30.769231
491,CENTURYPLY,735.05,762.35,729.50,735.25,106764.0,2024-11-19,32.85,4.503084,up,20.783902,15601413.0,812.488831,701.612903,749.806280,797.999657,12.854888,0.289325,28.163126,25.000000,100.0,-2.331850,732.813838,754.559336,711.068341,8.072546
492,KEI,3760.00,3881.90,3715.00,3842.25,297339.0,2024-11-19,166.90,4.492598,up,40.498655,47008.0,3968.940891,3590.573797,3781.014969,3971.456141,10.073548,0.326679,18.938447,50.000000,0.0,-0.938742,3812.977299,3948.615085,3677.339513,54.358266
493,SOLARINDS,9800.00,10025.00,9720.65,9983.50,49414.0,2024-11-19,304.35,3.130963,up,42.716667,6774580.0,10249.254299,9535.457562,9760.757034,9986.056506,4.616434,0.410992,20.190269,58.333333,0.0,-1.052520,9326.966068,9814.318982,8839.613155,32.913209
494,KFINTECH,980.60,1026.10,980.00,1013.95,674749.0,2024-11-19,46.10,4.704082,up,50.925995,67916177.0,1005.616076,945.920560,977.625348,1009.330137,6.486081,0.537449,16.951682,58.333333,0.0,-0.042410,994.987023,1027.815739,962.158306,50.194265

In [186]:
last_rows[(last_rows['zscore']<-3)]

,Symbol,open,high,low,close,volume,start_Time,diff,per,type,rsi14,obv,ema20,bbl,bbm,bbu,bbb,bbp,adx,psl,doji,zscore,hmid,hupper,hlower,imi
242,HONASA,254.95,270.0,242.35,264.10,12601303.0,2024-11-19,27.65,11.409119,up,14.377473,-16082369.0,373.134417,210.831663,310.121380,409.411098,64.032810,0.158719,30.405407,25.000000,0.0,-3.572863,332.892096,346.930088,318.854103,26.358854
365,THERMAX,4872.55,4880.0,4601.00,4632.55,122676.0,2024-11-19,279.00,6.063899,down,35.873894,215843.0,5013.561764,4480.863443,4803.645002,5126.426560,13.439026,0.186096,17.807751,58.333333,0.0,-3.136573,4708.018022,4935.854533,4480.181511,21.474359
454,BIKAJI,760.25,766.7,735.00,739.35,545505.0,2024-11-19,31.70,4.312925,down,26.591343,30949016.0,836.068093,696.773823,778.051756,859.329689,20.892680,0.235157,16.401900,33.333333,0.0,-3.019327,793.893792,826.461734,761.325850,26.850299

In [165]:
ny=all_data[all_data['Symbol']=='NYKAA']

In [166]:
ny

,Symbol,open,high,low,close,volume,start_Time,diff,per,type,rsi14,obv,ema20,bbl,bbm,bbu,bbb,bbp,adx,psl,doji,zscore,hmid,hupper,hlower
0,NYKAA,173.70,173.85,170.50,171.90,2822724.0,2024-01-01,3.35,1.964809,down,NaN,2822724.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,171.900000,171.900000,171.900000
1,NYKAA,172.00,173.40,168.35,169.30,3711343.0,2024-01-02,5.05,2.999703,down,NaN,-888619.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,171.325400,171.325400,171.325400
2,NYKAA,171.20,172.95,167.20,167.90,3883044.0,2024-01-03,5.75,3.438995,down,NaN,-4771663.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,170.508860,170.508860,170.508860
3,NYKAA,169.00,171.00,168.50,170.05,2442473.0,2024-01-04,2.50,1.483680,up,NaN,-2329190.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,170.264598,170.905085,169.624110
4,NYKAA,170.55,177.00,170.05,173.40,11042757.0,2024-01-05,6.95,4.087033,up,NaN,8713567.0,NaN,166.514506,168.920000,171.325494,2.848086,0.734879,NaN,NaN,0.0,NaN,170.792826,171.817431,169.768220
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,NYKAA,183.40,189.25,175.26,177.81,6011460.0,2024-11-12,13.99,7.982426,down,39.557460,177475412.0,184.266904,173.685776,179.369643,185.053509,6.337601,0.138482,24.242016,50.000000,0.0,-1.280581,183.136725,189.444969,176.828482
217,NYKAA,179.01,188.00,167.89,172.23,29113654.0,2024-11-13,20.11,11.978081,down,34.500457,148361758.0,183.120532,164.057930,175.543095,187.028260,13.085294,0.166827,23.994062,41.666667,0.0,-1.996977,181.622014,187.610293,175.633735
218,NYKAA,174.60,177.00,168.42,171.05,8232043.0,2024-11-14,8.58,5.094407,down,33.524436,140129715.0,181.970958,160.121403,173.168730,186.216057,15.068918,0.318019,23.763820,33.333333,0.0,-1.992377,180.060202,185.985651,174.134754
219,NYKAA,171.05,171.40,166.22,169.69,6549669.0,2024-11-18,5.18,3.116352,down,32.387205,133580046.0,180.801343,159.589916,170.852487,182.115058,13.183971,0.294342,23.889491,25.000000,0.0,-1.986345,178.408374,184.766112,172.050635
220,NYKAA,170.70,173.44,169.00,170.31,7449516.0,2024-11-19,4.44,2.627219,down,33.494799,141029562.0,179.802167,164.048316,170.234991,176.421666,7.268394,0.400189,24.006186,33.333333,100.0,-1.756421,177.108152,183.778769,170.437535

In [169]:
imi(ny['close'],ny['open'])

0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
         ...
216    52.463054
217    44.439710
218    42.022562
219    39.659660
220    37.934540
Name: IMI, Length: 221, dtype: float64

In [187]:
rsi20l=last_rows[last_rows['rsi14']<20]
(rsi20)

,Symbol,open,high,low,close,volume,start_Time,diff,per,type,rsi14,obv,ema20,bbl,bbm,bbu,bbb,bbp,adx,psl,doji,zscore,hmid,hupper,hlower
76,ASIANPAINT,2488.00,2503.20,2472.35,2483.70,941558.0,2024-11-19,30.85,1.247801,down,15.048312,-12518131.0,2747.713932,2486.481617,2502.008935,2517.536253,1.241188,-0.455057,44.129588,33.333333,100.0,-1.909656,2448.359453,2550.308557,2346.410349
133,COLPAL,2767.60,2785.15,2720.20,2733.50,264874.0,2024-11-19,64.95,2.387692,down,17.145071,21741043.0,2983.083937,2687.780933,2745.659205,2803.537478,4.215984,0.280062,61.426703,25.000000,0.0,-1.402896,2557.358842,2672.024898,2442.692786
201,MGL,1112.60,1145.80,1112.00,1126.05,1700881.0,2024-11-19,33.80,3.039568,up,16.567135,3643604.0,1407.679221,970.716192,1208.564737,1446.413283,39.360497,0.297004,39.615003,25.000000,0.0,-1.959171,1111.460757,1247.101831,975.819683
242,HONASA,254.95,270.00,242.35,264.10,12601303.0,2024-11-19,27.65,11.409119,up,14.377473,-16082369.0,373.134417,210.831663,310.121380,409.411098,64.032810,0.158719,30.405407,25.000000,0.0,-3.572863,332.892096,346.930088,318.854103
281,RBA,82.20,82.78,78.11,78.82,2739351.0,2024-11-19,4.67,5.978748,down,16.621901,74696605.0,90.490457,75.897420,82.353368,88.809316,15.678650,0.171360,44.001585,25.000000,0.0,-2.091353,78.828834,82.749727,74.907941
374,GUJGASLTD,452.00,459.00,448.20,451.25,1357441.0,2024-11-19,10.80,2.409639,down,19.982880,58137020.0,514.362719,422.074583,469.158950,516.243317,20.071819,0.277432,40.258638,25.000000,100.0,-2.147433,461.367028,485.425154,437.308902
410,IGL,329.00,329.50,316.75,320.45,14810634.0,2024-11-19,12.75,4.025257,down,16.608476,-15565244.0,418.491609,268.547845,362.853760,457.159675,51.980123,0.255563,39.067319,41.666667,0.0,-2.240713,350.903657,391.804387,310.002927
486,GSPL,325.00,329.70,321.05,325.25,2004863.0,2024-11-19,8.65,2.694284,up,18.626133,169627307.0,372.591814,301.063218,340.384540,379.705863,23.104059,0.254147,20.796960,41.666667,100.0,-2.861353,347.170564,362.826063,331.515064