In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import neo_api_client as kapi
import threading
import json

In [4]:
from neo_api_client import NeoAPI
df=pd.DataFrame()
def on_message(message):
    
    formatted_json=json.dumps(message, indent=2)
    print(formatted_json)
    global a
    a=pd.DataFrame.from_dict(formatted_json)
    print(type(message))
    flattened_data = []
    for item in formatted_json['data']:
        ohlc_data = item.pop('ohlc')
        item.update(ohlc_data)
        flattened_data.append(item)
    # Create a DataFrame
    global df
    df = pd.DataFrame(flattened_data)
    print(df)
#def on_message(message):
    #formatted_json=json.dumps(message, indent=2)
    #print(formatted_json)
    
def on_error(error_message):
    print(error_message)

def on_close(message):
    print(message)
    
def on_open(message):
    print(message)

In [5]:
client.quotes(instrument_tokens=tokens[:98])

NameError: name 'client' is not defined

In [6]:
a

NameError: name 'a' is not defined

In [13]:
consumer_key="hGZIbGDe7RPxoRD3cZ3UJaGftUUa"
consumer_secret="j24xLx4_1Kbl4acvpc8iDo2hHcIa"
access_token='eyJ4NXQiOiJNbUprWWpVMlpETmpNelpqTURBM05UZ3pObUUxTm1NNU1qTXpNR1kyWm1OaFpHUTFNakE1TmciLCJraWQiOiJaalJqTUdRek9URmhPV1EwTm1WallXWTNZemRtWkdOa1pUUmpaVEUxTlRnMFkyWTBZVEUyTlRCaVlURTRNak5tWkRVeE5qZ3pPVGM0TWpGbFkyWXpOUV9SUzI1NiIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJjbGllbnQyMTQ5NCIsImF1dCI6IkFQUExJQ0FUSU9OIiwiYXVkIjoiaEdaSWJHRGU3UlB4b1JEM2NaM1VKYUdmdFVVYSIsIm5iZiI6MTcyODQ5Mjg3MiwiYXpwIjoiaEdaSWJHRGU3UlB4b1JEM2NaM1VKYUdmdFVVYSIsInNjb3BlIjoiZGVmYXVsdCIsImlzcyI6Imh0dHBzOlwvXC9uYXBpLmtvdGFrc2VjdXJpdGllcy5jb206NDQzXC9vYXV0aDJcL3Rva2VuIiwiZXhwIjoxODE0ODkyODcyLCJpYXQiOjE3Mjg0OTI4NzIsImp0aSI6IjQyYjI1Mzk4LTBiN2EtNDFkMy1iYjdhLTYxZGFkYzZkMTQxNiJ9.TkDyBcpj0Tgucallvb_hEOH9DdbzJ6q5G2rGPFqKO-XnzDbAm7GehnjMjLNKa8kThEZLj9o9iyGWJ2fO9CmEAF_kLku6okDfSuZEemQswKw2aYzGOR_onXPKc_qAPIVEIfTV9bDN-kHbdEEQVQ8VH4LwNqndzXkHRjDOdghMKvknNZGGkLjDTJ9HCM9XYlVkMQ8wLDoP1K8agM73Iannk_xwMtnNhICvxxFCpIDefhXCC7C64JSzhRS18-Yr1Fe8lCn29t3BYVkcf1z9gl-jE_xFmNHSrsszd2Ceu-FtNAj2XXSbHIVfayRJ68FVTY_Qe0Pp99riwM3l_0IdVuAeSw'
mobilenumber='+919936053873'
password="21900@Agr"
mpin=

In [19]:
client = NeoAPI(consumer_key=consumer_key,
                consumer_secret=consumer_secret,
                environment='prod',
                access_token=access_token,
                neo_fin_key=None
               )

In [15]:
client.on_message = on_message  # called when message is received from websocket
client.on_error = on_error  # called when any error or exception occurs in code or websocket
client.on_close = on_close  # called when websocket connection is closed
client.on_open = on_open  # called when websocket successfully connects

In [17]:
client.login( mobilenumber=mobilenumber,
             password=password)

{'data': {'token': 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJWaWV3Il0sImV4cCI6MTc0NjIxMDYwMCwianRpIjoiNzVmMDAyOGEtNzFiNS00YjQ4LThhOTQtMTBlMzg2MTUyMDEzIiwiaWF0IjoxNzQ2MTUwMDk2LCJpc3MiOiJsb2dpbi1zZXJ2aWNlIiwic3ViIjoiMGU1OTZiMzItNDJiNC00MDM1LWJmNTAtMTY1NTc2MmIwNGFkIiwidWNjIjoiWUQySFUiLCJuYXAiOiIiLCJ5Y2UiOiJlWVxcNiUnOzUucFx0XHJcdTAwMDN9XHUwMDAwXHUwMDEwYiIsImZldGNoY2FjaGluZ3J1bGUiOjAsImNhdGVnb3Jpc2F0aW9uIjoiIn0.UhPK68nrtvXqw_ytKwpjaA_JEDQsRwSjGTMOh588NsuKpWq0PfWfx0ct6c4jXLGn4DvKEydYhWgQaAfMklWbalON7vQ4TyVX_76Q5m1s9uUr9PPGnibPb49F9WRL3p9RqC1-biV1V6zkaRRtoIMshb8fbRcG9n53TiYiDbLbabvyXPCHv5EASC69Qgik93LmkifbkEQhiKLxcd4YoxK3HYlbNXQ6K_yZ-44ksyFD26qHsVj0zXYQ1hlBvxPbEtUDrrmQ0fay1fneNxxXRAcb76EJAAIfrnvbjKZGhQX6eWJ71n2emEsMIxut7gTzlocD93nLy9BaPW8A-nwOMr87zg',
  'sid': '9bcd32ff-f1ad-4299-86ac-e0781ae95875',
  'rid': 'e5f964a9-52f0-4a74-aac5-5ee390746712',
  'hsServerId': '',
  'isUserPwdExpired': False,
  'caches': {'baskets': '1746124081', 'lastUpdatedTS': '1746124081'},
  'ucc': 'YD2HU',
  'greetingName': 'ATHARVA',
  'isTrialAccount': False,
  'dataCenter': 'E21',
  'searchAPIKey': '',
  'derivativesRiskDisclosure': 'Risk Disclosure on Derivatives\n\nAs per a SEBI study dated 25 Jan 2023- \n• 9 out of 10 individual traders in equity Futures and Options Segment, incurred net losses.\n• On an average, loss makers registered net trading loss close to Rs.50,000.\n• Over and above the net trading losses incurred, loss makers expended an additional 28% of net trading losses as transaction costs.\n• Those making net trading profits, incurred between 15% to 50% of such profits as transaction cost.\n\nFor more information please check out : https://www.sebi.gov.in/reports-and-statistics/research/jan-2023/study-analysis-of-profit-and-loss-of-individual-traders-dealing-in-equity-fando-segment_67525.html',
  'mfAccess': 1,
  'dataCenterMap': None,
  'dormancyStatus': 'A',
  'asbaStatus': '',
  'clientType': 'RI',
  'isNRI': False,
  'incRange': 0,
  'incUpdFlag': '',
  'clientGroup': ''}}

In [18]:
client.session_2fa(OTP="9905")

{'data': {'token': 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJUcmFkZSJdLCJleHAiOjE3NDYyMTA2MDAsImp0aSI6ImRlYzA3YzJlLWViZWEtNDczYy1iZWI1LWM1MjUzYTU0NGM4NSIsImlhdCI6MTc0NjE1MDExNywiaXNzIjoibG9naW4tc2VydmljZSIsInN1YiI6IjBlNTk2YjMyLTQyYjQtNDAzNS1iZjUwLTE2NTU3NjJiMDRhZCIsInVjYyI6IllEMkhVIiwibmFwIjoiIiwieWNlIjoiZVlcXDYlJzs1LnBcdFxyXHUwMDAzfVx1MDAwMFx1MDAxMGIiLCJmZXRjaGNhY2hpbmdydWxlIjowLCJjYXRlZ29yaXNhdGlvbiI6IiJ9.bNtjNxzMc7vrM1jWSeTkvxb-QzpSiezx-CKgCDOP2ihn7BY8700FDOsJbBQf81hBvZnW8247PJyyDEO5VwDTgih3CZ43jqbTKzIAcF7GAGKBwaQ-HtM9ZyS_hM5zzK_bZ9BEVkUV-pJpuHRe19MlNbEYICBsJoysmQokZyqRy1q0T5GfZY58qOtiWOCkTRtuPVkBAjWU3tzp7L7aaH2J62ZZacL4Frz4OgNAfMeN8o6ryh64dnTdo4cHuvUxkUFDBqZM2wUcyVMqhicIxNtg2zSyUPaTnT4l4F8SGPRIrnhduDLdyYYtYChMeSgtwE2pDB9XpqDC0XeNKA4XTJ-aXA',
  'sid': '9bcd32ff-f1ad-4299-86ac-e0781ae95875',
  'rid': 'e5f964a9-52f0-4a74-aac5-5ee390746712',
  'hsServerId': '',
  'isUserPwdExpired': False,
  'caches': {'baskets': '1746124081', 'lastUpdatedTS': '1746124081'},
  'ucc': 'YD2HU',
  'greetingName': 'ATHARVA',
  'isTrialAccount': False,
  'dataCenter': 'E21',
  'searchAPIKey': '',
  'derivativesRiskDisclosure': 'Risk Disclosure on Derivatives\n\nAs per a SEBI study dated 25 Jan 2023- \n• 9 out of 10 individual traders in equity Futures and Options Segment, incurred net losses.\n• On an average, loss makers registered net trading loss close to Rs.50,000.\n• Over and above the net trading losses incurred, loss makers expended an additional 28% of net trading losses as transaction costs.\n• Those making net trading profits, incurred between 15% to 50% of such profits as transaction cost.\n\nFor more information please check out : https://www.sebi.gov.in/reports-and-statistics/research/jan-2023/study-analysis-of-profit-and-loss-of-individual-traders-dealing-in-equity-fando-segment_67525.html',
  'mfAccess': 1,
  'dataCenterMap': None,
  'dormancyStatus': 'A',
  'asbaStatus': '',
  'clientType': 'RI',
  'isNRI': False,
  'incRange': 0,
  'incUpdFlag': '',
  'clientGroup': ''}}

In [9]:
master_list_equity=client.scrip_master(exchange_segment='NSE')
master_list_nfo=client.scrip_master(exchange_segment='NFO')
master_list_equity,master_list_nfo

('https://lapi.kotaksecurities.com/wso2-scripmaster/v1/prod/2025-05-01/transformed/nse_cm.csv',
 'https://lapi.kotaksecurities.com/wso2-scripmaster/v1/prod/2025-05-01/transformed/nse_fo.csv')

In [10]:
equ=pd.read_csv(master_list_equity)  # There is the presence of all the stock available , from kotak neo 
stock=pd.read_csv('/Users/Macbook/Desktop/n500.csv')  # This is the nifty 500 stock download from nse site
nifty500=equ[equ['pSymbolName'].isin(stock['Symbol'])]
nifty500=nifty500[nifty500['pGroup']=='EQ'].reset_index(drop=True)
nifty500

,pSymbol,pGroup,pExchSeg,pInstType,pSymbolName,pTrdSymbol,pOptionType,pScripRefKey,pISIN,pAssetCode,...,dGenDen,dGenNum,dPriceQuatation,dIssuerate,dPriceDen,dWarningQty,dIssueCapital,dExposureMargin,dMinRedemptionQty,lFreezeQty
0,6545,EQ,nse_cm,NaN,NYKAA,NYKAA-EQ,NaN,NYKAA,INE388Y01029,NaN,...,1,1,0,0,1,0,2.858350e+09,0,0,511644
1,7,EQ,nse_cm,NaN,AARTIIND,AARTIIND-EQ,NaN,AARTIIND,INE769A01020,NaN,...,1,1,0,0,1,0,3.625200e+08,0,0,237088
2,13404,EQ,nse_cm,NaN,SUNTV,SUNTV-EQ,NaN,SUNTV,INE424H01027,NaN,...,1,1,0,0,1,0,3.940850e+08,0,0,160786
3,13409,EQ,nse_cm,NaN,GPIL,GPIL-EQ,NaN,GPIL,INE177H01039,NaN,...,1,1,0,0,1,0,6.689750e+08,0,0,547890
4,6596,EQ,nse_cm,NaN,SONATSOFTW,SONATSOFTW-EQ,NaN,SONATSOFTW,INE269A01021,NaN,...,1,1,0,0,1,0,2.804250e+08,0,0,236958
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485,13285,EQ,nse_cm,NaN,M&MFIN,M&MFIN-EQ,NaN,M&MFIN,INE774D01024,NaN,...,1,1,0,0,1,0,1.235530e+09,0,0,380543
486,13305,EQ,nse_cm,NaN,CENTURYPLY,CENTURYPLY-EQ,NaN,CENTURYPLY,INE348B01021,NaN,...,1,1,0,0,1,0,2.221730e+08,0,0,143079
487,13310,EQ,nse_cm,NaN,KEI,KEI-EQ,NaN,KEI,INE878B01027,NaN,...,1,1,0,0,1,0,9.555260e+07,0,0,32583
488,13332,EQ,nse_cm,NaN,SOLARINDS,SOLARINDS-EQ,NaN,SOLARINDS,INE343H01029,NaN,...,1,1,0,0,1,0,9.049010e+07,0,0,7510
489,13359,EQ,nse_cm,NaN,KFINTECH,KFINTECH-EQ,NaN,KFINTECH,INE138Y01010,NaN,...,1,1,0,0,1,0,1.720760e+08,0,0,83456

In [11]:
dir(client)

['NeoWebSocket',
 '_NeoAPI__on_close',
 '_NeoAPI__on_error',
 '_NeoAPI__on_message',
 '_NeoAPI__on_open',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'api_client',
 'cancel_order',
 'check_callbacks',
 'configuration',
 'help',
 'holdings',
 'limits',
 'login',
 'logout',
 'margin_required',
 'modify_order',
 'on_close',
 'on_error',
 'on_message',
 'on_open',
 'order_history',
 'order_report',
 'place_order',
 'positions',
 'quotes',
 'scrip_master',
 'search_scrip',
 'session_2fa',
 'set_neowebsocket_callbacks',
 'subscribe',
 'subscribe_to_orderfeed',
 'trade_report',
 'un_subscribe']

In [12]:
# this is to create the tokens to get the data 
tokens=[{"instrument_token": f"{sym}", "exchange_segment": "nse_cm"} for sym in nifty500['pSymbol']] 
tokens

[{'instrument_token': '6545', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '7', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '13404', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '13409', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '6596', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '13451', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '13491', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '6656', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '13501', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '13517', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '13538', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '13560', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '13587', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '13', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '22', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '25', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '40', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '48', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '6705', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '6718', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '6733', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '13611', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '13637', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '13643', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '6818', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '13750', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '13751', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '13776', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '13786', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '13826', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '6994', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '13976', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '7083', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '7145', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '7227', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '7229', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '7242', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '7254', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '14111', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '14154', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '14180', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '14198', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '7358', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '14255', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '14299', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '7401', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '7406', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '14304', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '14309', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '14334', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '14366', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '14413', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '14418', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '14501', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '14552', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '14592', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '14672', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '7852', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '14732', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '14788', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '7929', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '7936', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '14894', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '14912', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '14937', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '14947', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '14966', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '14977', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '100', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '128', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '157', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '163', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '212', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '220', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '236', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '263', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '275', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '277', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '305', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '312', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '317', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '324', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '335', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '341', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '342', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '357', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '371', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '380', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '383', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '395', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '399', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '404', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '422', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '438', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '467', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '474', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '480', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '495', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '509', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '526', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '527', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '547', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '583', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '592', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '595', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '628', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '637', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '676', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '685', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '694', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '739', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '757', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '760', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '772', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '811', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '827', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '881', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '910', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '913', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '916', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '919', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '937', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '958', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '981', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '8050', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '8075', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '8110', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '8124', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '8167', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '15039', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '15083', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '15141', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '15146', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '15179', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '15184', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '8311', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '15228', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '15254', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '15283', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '15313', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '8479', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '15332', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '15355', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '15362', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '15380', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '8546', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '15414', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '8585', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '8596', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '8828', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '8840', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '20224', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '20242', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '8954', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '20293', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '20302', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '20329', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '20374', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '20551', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '20825', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '20854', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '16045', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '9348', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '9362', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '9385', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '9408', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '9480', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '9552', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '9581', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '9590', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '9599', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '9683', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '9685', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '16669', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '16675', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '21131', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '9810', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '21154', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '9819', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '21174', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '16713', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '21238', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '16915', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '21508', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '21614', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '21690', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '21740', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '21770', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '21808', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '21951', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '17029', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '17094', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '17105', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '17279', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '17313', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '17333', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '17388', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '17400', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '17438', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '17534', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '17641', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '17675', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '17704', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '17818', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '17869', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '17875', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '22377', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '17903', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '17927', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '17939', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '17945', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '17957', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '17963', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '17971', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '18011', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '18026', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '18060', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '18096', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '18143', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '18151', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '18365', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '18391', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '18457', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '18564', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '18566', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '18652', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '18721', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '18743', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '18822', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '18883', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '18908', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '18921', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '23650', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '19020', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '19061', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '19234', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '19585', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '24184', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '19731', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '19795', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '19813', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '19913', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '19943', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '24948', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '25328', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '25584', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '30108', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '25718', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '25780', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '25897', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '31163', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '31181', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '31234', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '31415', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1008', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1011', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1023', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1038', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1041', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1076', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1153', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1174', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1181', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1185', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1186', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1196', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1232', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1247', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1250', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1270', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1333', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1336', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1348', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1363', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1394', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1406', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1424', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1442', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1476', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1494', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1508', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1512', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1515', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1570', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1576', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1594', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1621', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1624', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1627', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1633', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1660', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1675', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1726', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1808', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1814', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1838', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1901', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1922', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1949', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1964', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '1997', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '27095', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '27297', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '2029', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '2031', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '2043', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '2048', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '2049', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '2056', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '2073', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '2088', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '2124', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '2142', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '2144', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '2181', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '2263', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '2277', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '2283', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '2303', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '2319', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '2412', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '2431', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '2475', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '2535', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '2606', 'exchange_segment': 'nse_cm'},
 {'instrument_token': '2649', 'exchange_segment': 'nse_cm'},

In [13]:
client.quotes(instrument_tokens=tokens[:98],quote_type='ohlc')

ValueError: Error! Login or Kindly pass the server ID token to proceed further

In [45]:
inst_tokens = [{"instrument_token": "11536", "exchange_segment": "nse_cm"},
               {"instrument_token": "1594", "exchange_segment": "nse_cm"},
               {"instrument_token": "11915", "exchange_segment": "nse_cm"},
               {"instrument_token": "13245", "exchange_segment": "nse_cm"},
               {"instrument_token": "1333", "exchange_segment": "nse_cm"}]
client.quotes(instrument_tokens=inst_tokens)



    # Get live feed data
client.subscribe(instrument_tokens=instrument_tokens)

NameError: name 'instrument_tokens' is not defined

The Session has been Opened!
{
  "type": "quotes",
  "data": [
    {
      "last_traded_price": "0.00",
      "buy_price": "0.00",
      "sell_price": "0.00",
      "buy_quantity": "0",
      "lower_circuit_limit": "95.00",
      "upper_circuit_limit": "105.00",
      "multiplier": "1",
      "precision": "2",
      "instrument_token": "13245",
      "exchange_segment": "nse_cm",
      "trading_symbol": "76KA32-SG",
      "request_type": "SNAP",
      "ohlc": {
        "open": "0.00",
        "high": null,
        "low": null,
        "close": null
      }
    },
    {
      "last_traded_time": "14/10/2024 12:19:22",
      "volume": "24464016",
      "last_traded_price": "21.25",
      "last_traded_quantity": "200",
      "total_buy_quantity": "6160384",
      "total_sell_quantity": "18186617",
      "buy_price": "21.23",
      "sell_price": "21.25",
      "buy_quantity": "23654",
      "average_price": "21.35",
      "lower_circuit_limit": "17.12",
      "upper_circuit_limit": "25.68",
      "52week_high": "32.85",
      "52week_low": "15.70",
      "multiplier": "1",
      "precision": "2",
      "change": "-0.15",
      "net_change_percentage": "-0.70",
      "total_traded_value": "522306741.60",
      "instrument_token": "11915",
      "exchange_segment": "nse_cm",
      "trading_symbol": "YESBANK-EQ",
      "request_type": "SNAP",
      "ohlc": {
        "open": "21.40",
        "high": "21.49",
        "low": "21.22",
        "close": "21.40"
      }
    },
    {
      "last_traded_time": "14/10/2024 12:19:21",
      "volume": "1014749",
      "last_traded_price": "4153.55",
      "last_traded_quantity": "3",
      "total_buy_quantity": "115321",
      "total_sell_quantity": "127465",
      "buy_price": "4153.05",
      "sell_price": "4153.50",
      "buy_quantity": "1",
      "average_price": "4141.43",
      "lower_circuit_limit": "3734.30",
      "upper_circuit_limit": "4564.10",
      "52week_high": "4592.25",
      "52week_low": "3311.00",
      "multiplier": "1",
      "precision": "2",
      "change": "4.35",
      "net_change_percentage": "0.10",
      "total_traded_value": "4202511951.07",
      "instrument_token": "11536",
      "exchange_segment": "nse_cm",
      "trading_symbol": "TCS-EQ",
      "request_type": "SNAP",
      "ohlc": {
        "open": "4140.00",
        "high": "4165.40",
        "low": "4122.20",
        "close": "4149.20"
      }
    },
    {
      "last_traded_time": "14/10/2024 12:19:22",
      "volume": "3308153",
      "last_traded_price": "1684.55",
      "last_traded_quantity": "15",
      "total_buy_quantity": "413030",
      "total_sell_quantity": "583920",
      "buy_price": "1684.50",
      "sell_price": "1684.55",
      "buy_quantity": "21",
      "average_price": "1675.59",
      "lower_circuit_limit": "1485.90",
      "upper_circuit_limit": "1816.10",
      "52week_high": "1794.00",
      "52week_low": "1363.55",
      "multiplier": "1",
      "precision": "2",
      "change": "33.55",
      "net_change_percentage": "2.03",
      "total_traded_value": "5543108085.27",
      "instrument_token": "1333",
      "exchange_segment": "nse_cm",
      "trading_symbol": "HDFCBANK-EQ",
      "request_type": "SNAP",
      "ohlc": {
        "open": "1656.05",
        "high": "1685.00",
        "low": "1654.00",
        "close": "1651.00"
      }
    },
    {
      "last_traded_time": "14/10/2024 12:19:22",
      "volume": "1506108",
      "last_traded_price": "1961.70",
      "last_traded_quantity": "1",
      "total_buy_quantity": "196224",
      "total_sell_quantity": "404749",
      "buy_price": "1961.65",
      "sell_price": "1961.70",
      "buy_quantity": "2",
      "average_price": "1950.39",
      "lower_circuit_limit": "1741.60",
      "upper_circuit_limit": "2128.60",
      "52week_high": "1977.00",
      "52week_low": "1351.65",
      "multiplier": "1",
      "precision": "2",
      "change": "26.60",
      "net_change_percentage": "1.37",
      "total_traded_value": "2937497982.12",
      "instrument_token": "1594",
      "exchange_segment": "nse_cm",
      "trading_symbol": "INFY-EQ",
      "request_type": "SNAP",
      "ohlc": {
        "open": "1932.15",
        "high": "1965.00",
        "low": "1931.10",
        "close": "1935.10"
      }
    }
  ]
}
The Session has been Closed!
DataFrame constructor not properly called!

In [13]:
def websock():
    inst_tokens = [{"instrument_token": "1333", "exchange_segment": "nse_cm"}]
    client.subscribe(instrument_tokens=inst_tokens)

In [14]:
thread=threading.Thread(target=websock)

In [15]:
thread.start()

The Session has been Opened!
Raw message: {'type': 'stock_feed', 'data': [{'ftm0': '02/01/1970 02:53:56', 'dtm1': '06/06/1971 00:27:09', 'fdtm': '10/10/2024 12:44:56', 'ltt': '10/10/2024 12:44:55', 'v': '5722812', 'ltp': '1649.55', 'ltq': '29', 'tbq': '1409547', 'tsq': '437350', 'bp': '1649.15', 'sp': '1649.55', 'bq': '21', 'bs': '40', 'ap': '1641.52', 'lo': '1632.50', 'h': '1652.50', 'lcl': '1469.85', 'ucl': '1796.45', 'yh': '1794.00', 'yl': '1363.55', 'op': '1639.00', 'c': '1633.15', 'mul': '1', 'prec': '2', 'cng': '16.40', 'nc': '1.00', 'to': '9394110354.24', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'ts': 'HDFCBANK-EQ', 'request_type': 'SNAP'}]}
The Session has been Closed!
the JSON object must be str, bytes or bytearray, not dict

In [31]:
thread.stop()

{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:31:56', 'dtm1': '31/03/1971 06:57:35', 'ltq': '68', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}

AttributeError: 'Thread' object has no attribute 'stop'

{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:31:59', 'dtm1': '31/03/1971 07:04:15', 'ltt': '10/10/2024 11:08:50', 'v': '3475789', 'ltp': '1638.00', 'ltq': '1', 'tbq': '330314', 'tsq': '422668', 'bp': '1638.00', 'sp': '1638.25', 'bq': '439', 'bs': '102', 'cng': '4.85', 'nc': '0.30', 'to': '5695601644.85', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:32:02', 'dtm1': '31/03/1971 07:10:56', 'fdtm': '10/10/2024 11:08:51', 'ltp': '1638.40', 'ltq': '122', 'cng': '5.25', 'nc': '0.32', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:32:05', 'dtm1': '31/03/1971 07:17:36', 'ltt': '10/10/2024 11:08:51', 'v': '3476976', 'ltp': '1638.05', 'ltq': '3', 'tbq': '333380', 'tsq': '421790', 'bp': '1638.05', 'sp': '1638.65', 'bq': '3', 'bs': '26', 'cng': '4.90', 'nc': '0.30', 'to': '5697546722.40', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:32:11', 'dtm1': '31/03/1971 07:30:56', 'fdtm': '10/10/2024 11:08:52', 'ltt': '10/10/2024 11:08:52', 'v': '3477103', 'ltp': '1638.00', 'ltq': '42', 'tbq': '317642', 'tsq': '423159', 'bp': '1638.00', 'sp': '1638.50', 'bq': '362', 'bs': '42', 'cng': '4.85', 'nc': '0.30', 'to': '5697754830.95', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:32:14', 'dtm1': '31/03/1971 07:44:17', 'fdtm': '10/10/2024 11:08:53', 'ltq': '85', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:32:17', 'dtm1': '31/03/1971 07:50:57', 'ltt': '10/10/2024 11:08:53', 'v': '3477627', 'tbq': '334291', 'tsq': '425340', 'sp': '1638.20', 'bq': '373', 'bs': '76', 'to': '5698613483.55', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:32:23', 'dtm1': '31/03/1971 08:04:17', 'fdtm': '10/10/2024 11:08:54', 'ltt': '10/10/2024 11:08:54', 'v': '3478442', 'ltq': '42', 'tbq': '329443', 'tsq': '425485', 'bq': '207', 'bs': '134', 'to': '5699948983.30', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:32:29', 'dtm1': '31/03/1971 08:17:38', 'fdtm': '10/10/2024 11:08:55', 'ltt': '10/10/2024 11:08:55', 'v': '3478969', 'ltq': '338', 'tbq': '333546', 'tsq': '423779', 'bq': '500', 'bs': '14', 'to': '5700812551.85', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:32:35', 'dtm1': '31/03/1971 08:37:39', 'fdtm': '10/10/2024 11:08:56', 'ltt': '10/10/2024 11:08:56', 'v': '3479613', 'ltp': '1638.50', 'ltq': '1', 'tbq': '333733', 'tsq': '424693', 'bp': '1638.20', 'sp': '1638.40', 'bq': '25', 'bs': '550', 'cng': '5.35', 'nc': '0.33', 'to': '5701867842.45', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:32:41', 'dtm1': '31/03/1971 08:51:00', 'fdtm': '10/10/2024 11:08:57', 'ltt': '10/10/2024 11:08:57', 'v': '3479816', 'ltp': '1638.00', 'ltq': '67', 'tbq': '334243', 'tsq': '425251', 'bp': '1638.00', 'sp': '1638.30', 'bq': '519', 'bs': '82', 'cng': '4.85', 'nc': '0.30', 'to': '5702200488.40', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:32:47', 'dtm1': '31/03/1971 09:11:00', 'fdtm': '10/10/2024 11:08:58', 'v': '3479900', 'ltq': '1', 'tbq': '334197', 'tsq': '425159', 'sp': '1638.40', 'bq': '518', 'bs': '677', 'to': '5702338135.00', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:32:53', 'dtm1': '31/03/1971 09:24:21', 'fdtm': '10/10/2024 11:08:59', 'ltt': '10/10/2024 11:08:58', 'v': '3479901', 'tbq': '334081', 'bq': '517', 'bs': '643', 'to': '5702339773.65', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:32:59', 'dtm1': '31/03/1971 09:44:21', 'fdtm': '10/10/2024 11:09:00', 'ltt': '10/10/2024 11:08:59', 'v': '3479902', 'tbq': '334080', 'tsq': '425164', 'bq': '516', 'to': '5702341412.30', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:33:02', 'dtm1': '31/03/1971 09:51:02', 'fdtm': '10/10/2024 11:09:01', 'ltt': '10/10/2024 11:09:00', 'v': '3480050', 'tbq': '334079', 'tsq': '425022', 'bq': '515', 'bs': '530', 'to': '5702583932.50', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:33:05', 'dtm1': '31/03/1971 09:57:42', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:33:08', 'dtm1': '31/03/1971 10:04:22', 'fdtm': '10/10/2024 11:09:02', 'ltt': '10/10/2024 11:09:02', 'v': '3480051', 'tbq': '334622', 'tsq': '425967', 'sp': '1638.30', 'bq': '514', 'bs': '34', 'to': '5702585571.15', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:33:11', 'dtm1': '31/03/1971 10:17:43', 'ltp': '1638.30', 'cng': '5.15', 'nc': '0.32', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:33:14', 'dtm1': '31/03/1971 10:24:23', 'fdtm': '10/10/2024 11:09:03', 'v': '3480052', 'tbq': '334890', 'tsq': '426539', 'sp': '1638.25', 'bq': '515', 'bs': '33', 'to': '5702587209.80', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:33:17', 'dtm1': '31/03/1971 10:31:04', 'ltp': '1638.00', 'cng': '4.85', 'nc': '0.30', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:33:20', 'dtm1': '31/03/1971 10:37:44', 'ltt': '10/10/2024 11:09:03', 'v': '3480136', 'ltp': '1638.25', 'ltq': '41', 'tbq': '335093', 'tsq': '426569', 'bp': '1638.05', 'sp': '1638.30', 'bq': '9', 'bs': '12', 'cng': '5.10', 'nc': '0.31', 'to': '5702724856.40', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:33:23', 'dtm1': '31/03/1971 10:51:04', 'fdtm': '10/10/2024 11:09:04', 'ltp': '1638.30', 'ltq': '66', 'cng': '5.15', 'nc': '0.32', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:33:26', 'dtm1': '31/03/1971 10:57:44', 'ltt': '10/10/2024 11:09:04', 'v': '3480212', 'tbq': '326937', 'tsq': '412724', 'bq': '10', 'bs': '3', 'to': '5702849393.80', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:33:29', 'dtm1': '31/03/1971 11:04:25', 'fdtm': '10/10/2024 11:09:05', 'ltp': '1638.00', 'ltq': '3', 'cng': '4.85', 'nc': '0.30', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:33:32', 'dtm1': '31/03/1971 11:11:05', 'ltt': '10/10/2024 11:09:05', 'v': '3480591', 'tbq': '335210', 'tsq': '424590', 'bp': '1638.00', 'bq': '181', 'bs': '89', 'to': '5703470442.15', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:33:38', 'dtm1': '31/03/1971 11:24:25', 'fdtm': '10/10/2024 11:09:06', 'ltt': '10/10/2024 11:09:06', 'v': '3480608', 'ltp': '1638.30', 'ltq': '1', 'tbq': '335213', 'tsq': '424541', 'bq': '183', 'bs': '92', 'cng': '5.15', 'nc': '0.32', 'to': '5703498299.20', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:33:44', 'dtm1': '31/03/1971 11:37:46', 'fdtm': '10/10/2024 11:09:07', 'ltt': '10/10/2024 11:09:07', 'v': '3480694', 'ltp': '1638.00', 'tbq': '335152', 'tsq': '423902', 'bq': '181', 'bs': '8', 'cng': '4.85', 'nc': '0.30', 'to': '5703639223.10', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:33:50', 'dtm1': '31/03/1971 11:57:47', 'fdtm': '10/10/2024 11:09:08', 'ltt': '10/10/2024 11:09:08', 'v': '3480700', 'tbq': '335154', 'tsq': '424032', 'bq': '180', 'bs': '3', 'to': '5703649055.00', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:33:56', 'dtm1': '31/03/1971 12:11:07', 'fdtm': '10/10/2024 11:09:09', 'ltt': '10/10/2024 11:09:09', 'v': '3480738', 'tbq': '335135', 'tsq': '424037', 'bq': '152', 'to': '5703711323.70', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:34:02', 'dtm1': '31/03/1971 12:31:08', 'fdtm': '10/10/2024 11:09:10', 'ltt': '10/10/2024 11:09:10', 'v': '3480832', 'tbq': '335100', 'tsq': '424068', 'sp': '1638.25', 'bq': '141', 'bs': '18', 'to': '5703865356.80', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:34:08', 'dtm1': '31/03/1971 12:44:28', 'fdtm': '10/10/2024 11:09:11', 'ltt': '10/10/2024 11:09:11', 'v': '3480836', 'ltp': '1638.05', 'tbq': '335287', 'tsq': '423667', 'bp': '1638.05', 'sp': '1638.20', 'bq': '153', 'cng': '4.90', 'nc': '0.30', 'to': '5703871911.40', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:34:14', 'dtm1': '31/03/1971 13:04:29', 'fdtm': '10/10/2024 11:09:12', 'ltt': '10/10/2024 11:09:12', 'v': '3481018', 'ltq': '3', 'tbq': '335370', 'tsq': '423564', 'sp': '1638.35', 'bq': '150', 'bs': '7', 'to': '5704170145.70', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:34:17', 'dtm1': '31/03/1971 13:11:09', 'fdtm': '10/10/2024 11:09:13', 'ltt': '10/10/2024 11:09:13', 'v': '3481182', 'ltp': '1638.40', 'ltq': '2', 'tbq': '336053', 'tsq': '424528', 'bp': '1638.40', 'sp': '1638.50', 'bq': '112', 'bs': '155', 'cng': '5.25', 'nc': '0.32', 'to': '5704438884.30', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:34:20', 'dtm1': '31/03/1971 13:17:50', 'ltp': '1638.50', 'ltq': '7', 'cng': '5.35', 'nc': '0.33', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:34:26', 'dtm1': '31/03/1971 13:37:50', 'fdtm': '10/10/2024 11:09:14', 'v': '3481316', 'ltp': '1638.35', 'ltq': '2', 'tbq': '336705', 'tsq': '424703', 'bq': '1', 'bs': '24', 'cng': '5.20', 'nc': '0.32', 'to': '5704658463.40', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:34:29', 'dtm1': '31/03/1971 13:44:31', 'fdtm': '10/10/2024 11:09:15', 'ltt': '10/10/2024 11:09:14', 'v': '3481396', 'ltp': '1638.40', 'ltq': '71', 'tbq': '335758', 'tsq': '424687', 'bp': '1638.35', 'sp': '1638.40', 'bq': '7', 'bs': '13', 'cng': '5.25', 'nc': '0.32', 'to': '5704789555.40', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:34:32', 'dtm1': '31/03/1971 13:51:11', 'ltp': '1638.75', 'cng': '5.60', 'nc': '0.34', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:34:35', 'dtm1': '31/03/1971 13:57:51', 'ltt': '10/10/2024 11:09:15', 'v': '3482111', 'ltp': '1638.30', 'ltq': '5', 'tbq': '335138', 'tsq': '423852', 'bp': '1638.10', 'sp': '1638.30', 'bq': '5', 'bs': '73', 'cng': '5.15', 'nc': '0.32', 'to': '5705961190.15', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:34:38', 'dtm1': '31/03/1971 14:11:11', 'fdtm': '10/10/2024 11:09:16', 'ltq': '2', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:34:41', 'dtm1': '31/03/1971 14:17:52', 'ltt': '10/10/2024 11:09:16', 'v': '3482186', 'ltp': '1638.05', 'ltq': '9', 'tbq': '335146', 'tsq': '422881', 'bp': '1638.00', 'sp': '1638.60', 'bq': '220', 'bs': '88', 'cng': '4.90', 'nc': '0.30', 'to': '5706084088.90', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:34:44', 'dtm1': '31/03/1971 14:24:32', 'fdtm': '10/10/2024 11:09:17', 'ltp': '1638.10', 'ltq': '1', 'cng': '4.95', 'nc': '0.30', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:34:47', 'dtm1': '31/03/1971 14:31:12', 'ltt': '10/10/2024 11:09:17', 'v': '3482187', 'tbq': '335327', 'tsq': '422496', 'sp': '1638.50', 'bq': '225', 'bs': '92', 'to': '5706085727.55', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:34:53', 'dtm1': '31/03/1971 14:44:33', 'fdtm': '10/10/2024 11:09:18', 'ltt': '10/10/2024 11:09:18', 'v': '3482356', 'ltp': '1638.60', 'ltq': '84', 'tbq': '335599', 'tsq': '422569', 'bp': '1638.05', 'sp': '1638.55', 'bq': '151', 'bs': '42', 'cng': '5.45', 'nc': '0.33', 'to': '5706362659.40', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:34:59', 'dtm1': '31/03/1971 14:57:53', 'fdtm': '10/10/2024 11:09:19', 'ltt': '10/10/2024 11:09:19', 'v': '3482847', 'ltp': '1638.00', 'ltq': '18', 'tbq': '336600', 'tsq': '424400', 'bp': '1638.00', 'sp': '1638.05', 'bq': '475', 'bs': '473', 'cng': '4.85', 'nc': '0.30', 'to': '5707167236.55', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:35:05', 'dtm1': '31/03/1971 15:17:54', 'fdtm': '10/10/2024 11:09:20', 'ltt': '10/10/2024 11:09:20', 'v': '3483313', 'ltq': '42', 'tbq': '335909', 'tsq': '424478', 'bq': '609', 'bs': '592', 'to': '5707930847.45', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:35:11', 'dtm1': '31/03/1971 15:31:15', 'fdtm': '10/10/2024 11:09:21', 'ltt': '10/10/2024 11:09:21', 'v': '3484523', 'ltq': '91', 'tbq': '330374', 'tsq': '422251', 'bp': '1637.85', 'bq': '500', 'bs': '422', 'to': '5709913613.95', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:35:17', 'dtm1': '31/03/1971 15:51:15', 'fdtm': '10/10/2024 11:09:22', 'ltt': '10/10/2024 11:09:22', 'v': '3485065', 'ltp': '1638.40', 'ltq': '1', 'tbq': '335009', 'tsq': '422563', 'bp': '1637.90', 'sp': '1638.40', 'bq': '93', 'bs': '282', 'cng': '5.25', 'nc': '0.32', 'to': '5710801762.25', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:35:23', 'dtm1': '31/03/1971 16:04:36', 'fdtm': '10/10/2024 11:09:23', 'ltt': '10/10/2024 11:09:23', 'v': '3485067', 'ltp': '1637.90', 'ltq': '2', 'tbq': '335044', 'tsq': '422677', 'bq': '91', 'bs': '283', 'cng': '4.75', 'nc': '0.29', 'to': '5710805039.55', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:35:29', 'dtm1': '31/03/1971 16:24:36', 'fdtm': '10/10/2024 11:09:24', 'ltt': '10/10/2024 11:09:24', 'v': '3486188', 'ltp': '1638.00', 'tbq': '334781', 'tsq': '421547', 'bp': '1638.00', 'sp': '1638.65', 'bq': '79', 'bs': '60', 'cng': '4.85', 'nc': '0.30', 'to': '5712641966.20', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:35:32', 'dtm1': '31/03/1971 16:31:17', 'fdtm': '10/10/2024 11:09:25', 'ltt': '10/10/2024 11:09:25', 'v': '3487284', 'ltp': '1638.70', 'tbq': '336146', 'tsq': '422872', 'bp': '1638.05', 'sp': '1638.60', 'bq': '77', 'bs': '82', 'cng': '5.55', 'nc': '0.34', 'to': '5714437926.60', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:35:35', 'dtm1': '31/03/1971 16:37:57', 'ltp': '1638.00', 'ltq': '6', 'cng': '4.85', 'nc': '0.30', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:35:41', 'dtm1': '31/03/1971 16:57:58', 'fdtm': '10/10/2024 11:09:26', 'v': '3487291', 'ltp': '1638.10', 'ltq': '3', 'tbq': '335310', 'tsq': '423374', 'bp': '1638.10', 'bq': '65', 'cng': '4.95', 'nc': '0.30', 'to': '5714449397.15', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:35:44', 'dtm1': '31/03/1971 17:04:38', 'fdtm': '10/10/2024 11:09:27', 'ltt': '10/10/2024 11:09:26', 'v': '3487423', 'ltp': '1638.60', 'ltq': '47', 'tbq': '335343', 'tsq': '424428', 'bq': '62', 'bs': '13', 'cng': '5.45', 'nc': '0.33', 'to': '5714665698.95', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:35:47', 'dtm1': '31/03/1971 17:11:18', 'ltp': '1638.10', 'ltq': '6', 'cng': '4.95', 'nc': '0.30', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:35:50', 'dtm1': '31/03/1971 17:17:59', 'ltt': '10/10/2024 11:09:27', 'v': '3487569', 'ltp': '1638.60', 'ltq': '55', 'tbq': '335098', 'tsq': '423508', 'bp': '1638.05', 'bq': '1', 'bs': '112', 'cng': '5.45', 'nc': '0.33', 'to': '5714904941.85', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:35:56', 'dtm1': '31/03/1971 17:31:19', 'fdtm': '10/10/2024 11:09:28', 'ltp': '1638.05', 'ltq': '22', 'cng': '4.90', 'nc': '0.30', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:35:59', 'dtm1': '31/03/1971 17:37:59', 'ltt': '10/10/2024 11:09:28', 'v': '3487930', 'tbq': '335257', 'tsq': '425208', 'bp': '1637.90', 'sp': '1638.05', 'bq': '72', 'bs': '68', 'to': '5715496494.50', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:36:02', 'dtm1': '31/03/1971 17:44:39', 'fdtm': '10/10/2024 11:09:29', 'ltp': '1638.75', 'ltq': '4', 'cng': '5.60', 'nc': '0.34', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:36:05', 'dtm1': '31/03/1971 17:51:20', 'ltt': '10/10/2024 11:09:29', 'v': '3488937', 'tbq': '333516', 'tsq': '422619', 'bp': '1637.95', 'sp': '1638.65', 'bq': '97', 'bs': '52', 'to': '5717146615.05', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:36:14', 'dtm1': '31/03/1971 18:04:40', 'fdtm': '10/10/2024 11:09:30', 'ltt': '10/10/2024 11:09:30', 'v': '3489024', 'ltp': '1638.60', 'ltq': '84', 'tbq': '333944', 'tsq': '422440', 'sp': '1638.60', 'bq': '81', 'bs': '4', 'cng': '5.45', 'nc': '0.33', 'to': '5717289177.60', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:36:17', 'dtm1': '31/03/1971 18:18:01', 'fdtm': '10/10/2024 11:09:31', 'ltq': '7', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 16:36:20', 'dtm1': '31/03/1971 18:24:41', 'ltt': '10/10/2024 11:09:31', 'v': '3489240', 'tbq': '334732', 'tsq': '421177', 'bp': '1638.05', 'sp': '1638.65', 'bq': '38', 'bs': '5', 'to': '5717643126.00', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}

In [32]:
def quotes():
    inst_tokens = [{"instrument_token": "1333", "exchange_segment": "nse_cm"}]
    client.quotes(instrument_tokens=instrument_tokens,quote_type='ohlc')
    time.sleep(1)

{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:40:20', 'dtm1': '07/04/1971 14:10:57', 'fdtm': '10/10/2024 11:19:21', 'ltt': '10/10/2024 11:19:21', 'v': '3645856', 'ltq': '3', 'tbq': '363089', 'tsq': '433670', 'bq': '35', 'bs': '30', 'to': '5974464227.20', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:40:26', 'dtm1': '07/04/1971 14:24:18', 'fdtm': '10/10/2024 11:19:22', 'ltt': '10/10/2024 11:19:22', 'v': '3645948', 'ltp': '1640.15', 'ltq': '9', 'tbq': '363029', 'tsq': '434378', 'sp': '1640.75', 'bq': '26', 'bs': '77', 'cng': '7.00', 'nc': '0.43', 'to': '5974614987.60', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:40:29', 'dtm1': '07/04/1971 14:30:58', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:40:32', 'dtm1': '07/04/1971 14:44:18', 'fdtm': '10/10/2024 11:19:23', 'ltt': '10/10/2024 11:19:23', 'v': '3645951', 'ltp': '1640.10', 'ltq': '1', 'tbq': '363286', 'tsq': '435316', 'bp': '1640.10', 'sp': '1640.50', 'bq': '81', 'bs': '54', 'cng': '6.95', 'nc': '0.43', 'to': '5974619903.70', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:40:38', 'dtm1': '07/04/1971 14:57:39', 'fdtm': '10/10/2024 11:19:24', 'ltt': '10/10/2024 11:19:24', 'v': '3645987', 'ltp': '1640.50', 'ltq': '5', 'tbq': '363151', 'tsq': '434927', 'bq': '74', 'bs': '30', 'cng': '7.35', 'nc': '0.45', 'to': '5974678896.90', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:40:41', 'dtm1': '07/04/1971 15:04:19', 'ltq': '85', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:40:44', 'dtm1': '07/04/1971 15:17:39', 'fdtm': '10/10/2024 11:19:25', 'ltt': '10/10/2024 11:19:25', 'v': '3646081', 'ltp': '1640.35', 'ltq': '9', 'tbq': '364339', 'tsq': '434792', 'bp': '1640.35', 'bq': '10', 'bs': '54', 'cng': '7.20', 'nc': '0.44', 'to': '5974832934.70', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:40:50', 'dtm1': '07/04/1971 15:31:00', 'fdtm': '10/10/2024 11:19:26', 'ltt': '10/10/2024 11:19:26', 'v': '3646283', 'ltp': '1640.10', 'ltq': '1', 'tbq': '362994', 'tsq': '435162', 'bp': '1640.10', 'bq': '147', 'bs': '55', 'cng': '6.95', 'nc': '0.43', 'to': '5975163952.10', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:40:53', 'dtm1': '07/04/1971 15:37:41', 'ltq': '4', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:40:56', 'dtm1': '07/04/1971 15:44:21', 'fdtm': '10/10/2024 11:19:27', 'ltt': '10/10/2024 11:19:27', 'v': '3646587', 'ltp': '1640.75', 'ltq': '2', 'tbq': '363698', 'tsq': '434465', 'bp': '1640.15', 'sp': '1640.75', 'bq': '59', 'bs': '148', 'cng': '7.60', 'nc': '0.47', 'to': '5975662116.90', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:41:02', 'dtm1': '07/04/1971 15:57:41', 'fdtm': '10/10/2024 11:19:28', 'v': '3646686', 'ltp': '1640.50', 'ltq': '8', 'tbq': '365387', 'tsq': '434722', 'bp': '1640.20', 'sp': '1640.50', 'bq': '32', 'bs': '72', 'cng': '7.35', 'nc': '0.45', 'to': '5975824348.20', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:41:05', 'dtm1': '07/04/1971 16:11:02', 'ltp': '1640.20', 'ltq': '54', 'cng': '7.05', 'nc': '0.43', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:41:08', 'dtm1': '07/04/1971 16:17:42', 'ltt': '10/10/2024 11:19:28', 'v': '3646799', 'tbq': '364330', 'tsq': '434151', 'sp': '1640.75', 'bq': '44', 'bs': '83', 'to': '5976009521.30', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:41:14', 'dtm1': '07/04/1971 16:31:02', 'fdtm': '10/10/2024 11:19:29', 'ltt': '10/10/2024 11:19:29', 'v': '3647512', 'ltp': '1640.85', 'ltq': '110', 'tbq': '365102', 'tsq': '422500', 'bp': '1640.35', 'sp': '1640.85', 'bq': '16', 'bs': '42', 'cng': '7.70', 'nc': '0.47', 'to': '5977177914.40', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:41:20', 'dtm1': '07/04/1971 16:44:23', 'fdtm': '10/10/2024 11:19:30', 'ltt': '10/10/2024 11:19:30', 'v': '3647854', 'ltp': '1640.80', 'ltq': '43', 'tbq': '364260', 'tsq': '434873', 'sp': '1640.80', 'bq': '276', 'bs': '507', 'cng': '7.65', 'nc': '0.47', 'to': '5977738349.80', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:41:26', 'dtm1': '07/04/1971 17:04:24', 'fdtm': '10/10/2024 11:19:31', 'ltt': '10/10/2024 11:19:31', 'v': '3648558', 'ltp': '1640.95', 'ltq': '134', 'tbq': '365115', 'tsq': '433017', 'bp': '1640.45', 'sp': '1640.95', 'bq': '60', 'bs': '78', 'cng': '7.80', 'nc': '0.48', 'to': '5978891994.60', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:41:32', 'dtm1': '07/04/1971 17:17:44', 'fdtm': '10/10/2024 11:19:32', 'ltt': '10/10/2024 11:19:32', 'v': '3648562', 'ltq': '2', 'tbq': '364926', 'tsq': '433027', 'bp': '1640.40', 'sp': '1641.00', 'bq': '132', 'bs': '2558', 'to': '5978898549.40', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:41:35', 'dtm1': '07/04/1971 17:31:05', 'fdtm': '10/10/2024 11:19:33', 'ltt': '10/10/2024 11:19:33', 'v': '3648564', 'ltp': '1640.75', 'ltq': '1', 'tbq': '365859', 'tsq': '433745', 'sp': '1640.75', 'bq': '104', 'bs': '4', 'cng': '7.60', 'nc': '0.47', 'to': '5978901826.80', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:41:38', 'dtm1': '07/04/1971 17:37:45', 'ltq': '4', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:41:44', 'dtm1': '07/04/1971 17:51:05', 'fdtm': '10/10/2024 11:19:34', 'ltt': '10/10/2024 11:19:34', 'v': '3648570', 'ltp': '1641.00', 'ltq': '1', 'tbq': '366233', 'tsq': '432611', 'bp': '1640.75', 'sp': '1641.00', 'bq': '59', 'bs': '2557', 'cng': '7.85', 'nc': '0.48', 'to': '5978911659.00', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:41:47', 'dtm1': '07/04/1971 18:04:26', 'fdtm': '10/10/2024 11:19:35', 'ltt': '10/10/2024 11:19:35', 'v': '3648717', 'ltp': '1640.40', 'ltq': '2', 'tbq': '366270', 'tsq': '432991', 'bp': '1640.40', 'sp': '1640.75', 'bq': '2', 'bs': '25', 'cng': '7.25', 'nc': '0.44', 'to': '5979152547.90', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:41:53', 'dtm1': '07/04/1971 18:17:47', 'fdtm': '10/10/2024 11:19:36', 'ltt': '10/10/2024 11:19:36', 'v': '3648797', 'ltq': '21', 'tbq': '364573', 'tsq': '432998', 'sp': '1640.95', 'bq': '36', 'bs': '58', 'to': '5979283643.90', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:41:56', 'dtm1': '07/04/1971 18:24:28', 'ltp': '1641.00', 'ltq': '85', 'cng': '7.85', 'nc': '0.48', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:42:02', 'dtm1': '07/04/1971 18:44:27', 'fdtm': '10/10/2024 11:19:37', 'ltt': '10/10/2024 11:19:37', 'v': '3648996', 'ltp': '1640.95', 'ltq': '1', 'tbq': '364769', 'tsq': '432837', 'bq': '40', 'bs': '99', 'cng': '7.80', 'nc': '0.48', 'to': '5979609745.20', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:42:05', 'dtm1': '07/04/1971 18:51:08', 'fdtm': '10/10/2024 11:19:38', 'v': '3648997', 'tbq': '364774', 'tsq': '432838', 'bs': '100', 'to': '5979611383.90', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:42:08', 'dtm1': '07/04/1971 18:57:48', 'ltp': '1640.40', 'ltq': '10', 'cng': '7.25', 'nc': '0.44', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:42:11', 'dtm1': '07/04/1971 19:04:28', 'fdtm': '10/10/2024 11:19:39', 'ltt': '10/10/2024 11:19:38', 'v': '3649007', 'tbq': '364747', 'tsq': '432958', 'sp': '1641.00', 'bq': '25', 'bs': '2473', 'to': '5979627770.90', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:42:14', 'dtm1': '07/04/1971 19:17:49', 'ltp': '1641.00', 'ltq': '83', 'cng': '7.85', 'nc': '0.48', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:42:17', 'dtm1': '07/04/1971 19:24:29', 'fdtm': '10/10/2024 11:19:40', 'ltt': '10/10/2024 11:19:39', 'v': '3649099', 'tbq': '364749', 'tsq': '433432', 'bq': '27', 'bs': '2386', 'to': '5979778531.30', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:42:20', 'dtm1': '07/04/1971 19:31:12', 'ltp': '1640.40', 'ltq': '5', 'cng': '7.25', 'nc': '0.44', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:42:23', 'dtm1': '07/04/1971 19:37:51', 'ltt': '10/10/2024 11:19:40', 'v': '3649205', 'ltp': '1641.00', 'ltq': '100', 'tbq': '364750', 'tsq': '433537', 'bq': '21', 'bs': '2286', 'cng': '7.85', 'nc': '0.48', 'to': '5979952233.50', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:42:29', 'dtm1': '07/04/1971 19:51:10', 'fdtm': '10/10/2024 11:19:41', 'ltt': '10/10/2024 11:19:41', 'v': '3649301', 'ltp': '1640.40', 'ltq': '65', 'tbq': '375647', 'tsq': '433406', 'sp': '1640.90', 'bq': '229', 'bs': '5', 'cng': '7.25', 'nc': '0.44', 'to': '5980109548.70', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:42:35', 'dtm1': '07/04/1971 20:04:31', 'fdtm': '10/10/2024 11:19:42', 'ltt': '10/10/2024 11:19:42', 'v': '3649391', 'ltp': '1640.90', 'ltq': '36', 'tbq': '376045', 'tsq': '433718', 'sp': '1640.85', 'bq': '227', 'bs': '7', 'cng': '7.75', 'nc': '0.47', 'to': '5980257031.70', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:42:41', 'dtm1': '07/04/1971 20:24:31', 'fdtm': '10/10/2024 11:19:43', 'ltt': '10/10/2024 11:19:43', 'v': '3649648', 'ltp': '1640.40', 'ltq': '34', 'tbq': '375938', 'tsq': '433506', 'bq': '16', 'bs': '6', 'cng': '7.25', 'nc': '0.44', 'to': '5980678177.60', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:42:47', 'dtm1': '07/04/1971 20:37:52', 'fdtm': '10/10/2024 11:19:44', 'ltt': '10/10/2024 11:19:44', 'v': '3649997', 'ltp': '1640.85', 'ltq': '1', 'tbq': '375439', 'tsq': '434092', 'bq': '431', 'bs': '2', 'cng': '7.70', 'nc': '0.47', 'to': '5981250083.90', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:42:53', 'dtm1': '07/04/1971 20:57:53', 'fdtm': '10/10/2024 11:19:45', 'ltt': '10/10/2024 11:19:45', 'v': '3650279', 'ltq': '22', 'tbq': '376773', 'tsq': '433862', 'bp': '1640.85', 'sp': '1640.90', 'bq': '9', 'bs': '335', 'to': '5981712197.30', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:42:59', 'dtm1': '07/04/1971 21:11:13', 'fdtm': '10/10/2024 11:19:46', 'ltt': '10/10/2024 11:19:46', 'v': '3651588', 'ltp': '1640.40', 'ltq': '100', 'tbq': '375404', 'tsq': '432252', 'bp': '1640.40', 'sp': '1640.95', 'bq': '94', 'bs': '82', 'cng': '7.25', 'nc': '0.44', 'to': '5983857255.60', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:43:05', 'dtm1': '07/04/1971 21:31:14', 'fdtm': '10/10/2024 11:19:47', 'ltt': '10/10/2024 11:19:47', 'v': '3651689', 'ltq': '1', 'tbq': '375300', 'tsq': '432695', 'sp': '1640.90', 'bq': '95', 'bs': '34', 'to': '5984022764.30', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:43:08', 'dtm1': '07/04/1971 21:37:54', 'fdtm': '10/10/2024 11:19:48', 'ltt': '10/10/2024 11:19:48', 'v': '3651706', 'ltp': '1640.75', 'tbq': '376096', 'tsq': '433724', 'bp': '1640.75', 'bq': '12', 'bs': '387', 'cng': '7.60', 'nc': '0.47', 'to': '5984050622.20', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:43:11', 'dtm1': '07/04/1971 21:44:34', 'ltp': '1640.90', 'ltq': '65', 'cng': '7.75', 'nc': '0.47', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:43:17', 'dtm1': '07/04/1971 22:04:35', 'fdtm': '10/10/2024 11:19:49', 'v': '3651791', 'ltp': '1640.75', 'ltq': '1', 'tbq': '374859', 'tsq': '433438', 'sp': '1640.95', 'bq': '13', 'bs': '306', 'cng': '7.60', 'nc': '0.47', 'to': '5984189911.70', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:43:20', 'dtm1': '07/04/1971 22:11:16', 'fdtm': '10/10/2024 11:19:50', 'ltt': '10/10/2024 11:19:50', 'v': '3654100', 'ltp': '1640.85', 'ltq': '84', 'tbq': '374516', 'tsq': '434076', 'bp': '1640.85', 'sp': '1641.00', 'bq': '510', 'bs': '3503', 'ap': '1638.71', 'cng': '7.70', 'nc': '0.47', 'to': '5988010211.00', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:43:23', 'dtm1': '07/04/1971 22:17:56', 'ltp': '1641.00', 'ltq': '5', 'cng': '7.85', 'nc': '0.48', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:43:26', 'dtm1': '07/04/1971 22:24:36', 'fdtm': '10/10/2024 11:19:51', 'v': '3654107', 'tbq': '377163', 'tsq': '433763', 'bq': '502', 'bs': '3498', 'to': '5988021681.97', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:43:29', 'dtm1': '07/04/1971 22:37:57', 'ltq': '83', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:43:32', 'dtm1': '07/04/1971 22:44:37', 'fdtm': '10/10/2024 11:19:52', 'ltt': '10/10/2024 11:19:52', 'v': '3659079', 'ltp': '1641.50', 'ltq': '1', 'tbq': '378039', 'tsq': '426967', 'bp': '1641.05', 'sp': '1641.50', 'bq': '515', 'bs': '793', 'cng': '8.35', 'nc': '0.51', 'to': '5996169348.09', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:43:35', 'dtm1': '07/04/1971 22:51:17', 'ltp': '1641.30', 'cng': '8.15', 'nc': '0.50', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:43:38', 'dtm1': '07/04/1971 22:57:58', 'fdtm': '10/10/2024 11:19:53', 'v': '3659632', 'tbq': '376222', 'tsq': '429244', 'bp': '1640.85', 'sp': '1641.10', 'bq': '64', 'bs': '1100', 'to': '5997075554.72', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:43:44', 'dtm1': '07/04/1971 23:11:18', 'ltt': '10/10/2024 11:19:53', 'v': '3659745', 'ltp': '1640.85', 'ltq': '19', 'tbq': '375921', 'tsq': '429690', 'bq': '46', 'bs': '1076', 'cng': '7.70', 'nc': '0.47', 'to': '5997260728.95', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:43:47', 'dtm1': '07/04/1971 23:24:39', 'fdtm': '10/10/2024 11:19:54', 'ltq': '1', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:43:50', 'dtm1': '07/04/1971 23:31:19', 'ltt': '10/10/2024 11:19:54', 'v': '3660137', 'ltq': '3', 'tbq': '374656', 'tsq': '429586', 'sp': '1641.05', 'bq': '7', 'bs': '268', 'to': '5997903103.27', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:43:56', 'dtm1': '07/04/1971 23:44:39', 'fdtm': '10/10/2024 11:19:55', 'ltt': '10/10/2024 11:19:55', 'v': '3660350', 'ltp': '1641.00', 'ltq': '190', 'tbq': '375767', 'tsq': '430858', 'bp': '1640.75', 'sp': '1641.00', 'bq': '9', 'bs': '360', 'cng': '7.85', 'nc': '0.48', 'to': '5998252148.50', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:44:02', 'dtm1': '07/04/1971 23:58:00', 'fdtm': '10/10/2024 11:19:56', 'ltt': '10/10/2024 11:19:56', 'v': '3660372', 'ltq': '12', 'tbq': '375766', 'tsq': '430172', 'bq': '6', 'bs': '589', 'to': '5998288200.12', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:44:08', 'dtm1': '08/04/1971 00:18:01', 'fdtm': '10/10/2024 11:19:57', 'ltt': '10/10/2024 11:19:57', 'v': '3660509', 'ltq': '83', 'tbq': '375758', 'tsq': '430179', 'bp': '1640.60', 'bq': '3', 'bs': '554', 'to': '5998512703.39', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:44:14', 'dtm1': '08/04/1971 00:31:21', 'fdtm': '10/10/2024 11:19:58', 'ltt': '10/10/2024 11:19:58', 'v': '3660520', 'ltp': '1640.60', 'ltq': '1', 'tbq': '375815', 'tsq': '430174', 'bq': '1', 'bs': '545', 'cng': '7.45', 'nc': '0.46', 'to': '5998530729.20', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:44:20', 'dtm1': '08/04/1971 00:51:22', 'fdtm': '10/10/2024 11:19:59', 'ltt': '10/10/2024 11:19:59', 'v': '3660523', 'ltp': '1640.50', 'ltq': '84', 'tbq': '375889', 'tsq': '429760', 'bp': '1640.50', 'bq': '148', 'bs': '544', 'cng': '7.35', 'nc': '0.45', 'to': '5998535645.33', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:44:23', 'dtm1': '08/04/1971 00:58:02', 'fdtm': '10/10/2024 11:20:00', 'v': '3660707', 'ltp': '1641.00', 'ltq': '5', 'tbq': '376005', 'tsq': '429748', 'bq': '13', 'bs': '543', 'cng': '7.85', 'nc': '0.48', 'to': '5998837167.97', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:44:26', 'dtm1': '08/04/1971 01:04:43', 'ltq': '85', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:44:32', 'dtm1': '08/04/1971 01:24:43', 'fdtm': '10/10/2024 11:20:01', 'ltt': '10/10/2024 11:20:00', 'v': '3661175', 'ltp': '1640.80', 'ltq': '2', 'tbq': '376819', 'tsq': '430786', 'bp': '1640.45', 'sp': '1640.80', 'bq': '199', 'bs': '42', 'cng': '7.65', 'nc': '0.47', 'to': '5999604084.25', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 17:44:35', 'dtm1': '08/04/1971 01:31:24', 'fdtm': '10/10/2024 11:20:02', 'ltt': '10/10/2024 11:20:02', 'v': '3661267', 'ltp': '1640.45', 'ltq': '23', 'tbq': '377378', 'tsq': '430525', 'bq': '84', 'bs': '35', 'cng': '7.30', 'nc': '0.45', 'to': '5999754845.57', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}

In [33]:
print(5+1)

{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:03:47', 'dtm1': '10/04/1971 02:53:18', 'fdtm': '10/10/2024 11:23:00', 'ltt': '10/10/2024 11:22:59', 'v': '3699890', 'ltp': '1641.00', 'ltq': '5', 'tbq': '407139', 'tsq': '461588', 'bq': '60', 'bs': '40', 'cng': '7.85', 'nc': '0.48', 'to': '6063120739.70', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
6
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:03:53', 'dtm1': '10/04/1971 03:06:38', 'ltt': '10/10/2024 11:23:00', 'v': '3700146', 'ltq': '78', 'tbq': '407282', 'tsq': '462141', 'bq': '147', 'bs': '118', 'to': '6063540254.58', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:03:59', 'dtm1': '10/04/1971 03:26:39', 'fdtm': '10/10/2024 11:23:01', 'ltt': '10/10/2024 11:23:01', 'v': '3700336', 'ltq': '4', 'tbq': '407164', 'tsq': '462749', 'bq': '51', 'bs': '70', 'to': '6063851613.28', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:04:05', 'dtm1': '10/04/1971 03:40:00', 'fdtm': '10/10/2024 11:23:02', 'ltt': '10/10/2024 11:23:02', 'v': '3700388', 'ltp': '1640.95', 'ltq': '12', 'tbq': '407431', 'tsq': '463244', 'bq': '80', 'bs': '595', 'cng': '7.80', 'nc': '0.48', 'to': '6063936827.24', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:04:11', 'dtm1': '10/04/1971 03:53:20', 'fdtm': '10/10/2024 11:23:03', 'ltt': '10/10/2024 11:23:03', 'v': '3700529', 'ltq': '51', 'tbq': '407376', 'tsq': '463234', 'bq': '25', 'bs': '587', 'to': '6064167888.17', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:04:17', 'dtm1': '10/04/1971 04:13:21', 'fdtm': '10/10/2024 11:23:04', 'ltt': '10/10/2024 11:23:04', 'v': '3700976', 'ltq': '1', 'tbq': '407270', 'tsq': '463249', 'bq': '67', 'bs': '586', 'to': '6064900400.48', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:04:23', 'dtm1': '10/04/1971 04:26:42', 'fdtm': '10/10/2024 11:23:05', 'ltt': '10/10/2024 11:23:05', 'v': '3701053', 'ltp': '1640.70', 'ltq': '17', 'tbq': '407257', 'tsq': '463742', 'bp': '1640.70', 'sp': '1640.95', 'bq': '20', 'bs': '438', 'cng': '7.55', 'nc': '0.46', 'to': '6065026582.69', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:04:26', 'dtm1': '10/04/1971 04:40:02', 'fdtm': '10/10/2024 11:23:06', 'ltt': '10/10/2024 11:23:06', 'v': '3701180', 'ltq': '3', 'tbq': '407274', 'tsq': '464012', 'sp': '1640.75', 'bq': '89', 'bs': '306', 'to': '6065234701.40', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:04:29', 'dtm1': '10/04/1971 04:46:42', 'ltp': '1640.75', 'ltq': '84', 'cng': '7.60', 'nc': '0.47', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:04:35', 'dtm1': '10/04/1971 05:00:03', 'fdtm': '10/10/2024 11:23:07', 'ltt': '10/10/2024 11:23:07', 'v': '3701267', 'ltp': '1640.70', 'ltq': '1', 'tbq': '407279', 'tsq': '463114', 'bs': '224', 'cng': '7.55', 'nc': '0.46', 'to': '6065377270.91', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:04:38', 'dtm1': '10/04/1971 05:13:24', 'fdtm': '10/10/2024 11:23:08', 'ltt': '10/10/2024 11:23:08', 'v': '3701297', 'ltp': '1640.75', 'ltq': '7', 'tbq': '407250', 'tsq': '460421', 'bq': '88', 'bs': '536', 'cng': '7.60', 'nc': '0.47', 'to': '6065426432.81', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:04:41', 'dtm1': '10/04/1971 05:20:04', 'ltp': '1640.70', 'ltq': '1', 'cng': '7.55', 'nc': '0.46', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:04:44', 'dtm1': '10/04/1971 05:26:45', 'fdtm': '10/10/2024 11:23:09', 'ltt': '10/10/2024 11:23:09', 'v': '3701345', 'ltq': '43', 'tbq': '407204', 'tsq': '463718', 'bq': '40', 'bs': '195', 'to': '6065505091.85', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:04:47', 'dtm1': '10/04/1971 05:33:25', 'ltq': '50', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:04:50', 'dtm1': '10/04/1971 05:46:45', 'fdtm': '10/10/2024 11:23:10', 'v': '3701722', 'ltp': '1640.75', 'ltq': '4', 'tbq': '404713', 'tsq': '464288', 'sp': '1641.00', 'bq': '146', 'bs': '575', 'cng': '7.60', 'nc': '0.47', 'to': '6066122893.06', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:04:53', 'dtm1': '10/04/1971 05:53:25', 'ltp': '1640.70', 'ltq': '1', 'cng': '7.55', 'nc': '0.46', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:04:56', 'dtm1': '10/04/1971 06:00:06', 'fdtm': '10/10/2024 11:23:11', 'ltt': '10/10/2024 11:23:10', 'v': '3701724', 'tbq': '405580', 'tsq': '464198', 'bq': '145', 'to': '6066126170.52', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:05:02', 'dtm1': '10/04/1971 06:13:26', 'fdtm': '10/10/2024 11:23:12', 'ltt': '10/10/2024 11:23:11', 'v': '3701727', 'ltq': '3', 'tbq': '405603', 'tsq': '463136', 'bq': '142', 'to': '6066131086.71', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:05:05', 'dtm1': '10/04/1971 06:26:47', 'ltp': '1640.80', 'ltq': '1', 'cng': '7.65', 'nc': '0.47', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:05:08', 'dtm1': '10/04/1971 06:33:27', 'fdtm': '10/10/2024 11:23:13', 'ltt': '10/10/2024 11:23:12', 'v': '3701824', 'ltp': '1641.00', 'ltq': '3', 'tbq': '406696', 'tsq': '462697', 'bp': '1640.80', 'sp': '1640.90', 'bq': '46', 'bs': '1', 'cng': '7.85', 'nc': '0.48', 'to': '6066290043.52', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:05:14', 'dtm1': '10/04/1971 06:46:48', 'ltt': '10/10/2024 11:23:13', 'v': '3701894', 'ltq': '69', 'tbq': '407156', 'tsq': '463338', 'sp': '1641.00', 'bs': '413', 'to': '6066404754.62', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:05:20', 'dtm1': '10/04/1971 07:00:08', 'fdtm': '10/10/2024 11:23:14', 'ltt': '10/10/2024 11:23:14', 'v': '3701901', 'ltq': '6', 'tbq': '407113', 'tsq': '463293', 'bp': '1640.85', 'bq': '40', 'bs': '407', 'to': '6066416225.73', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:05:26', 'dtm1': '10/04/1971 07:20:09', 'fdtm': '10/10/2024 11:23:15', 'ltt': '10/10/2024 11:23:15', 'v': '3702045', 'ltp': '1640.95', 'ltq': '31', 'tbq': '407261', 'tsq': '463453', 'bp': '1640.95', 'bq': '28', 'bs': '566', 'cng': '7.80', 'nc': '0.48', 'to': '6066652202.85', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:05:32', 'dtm1': '10/04/1971 07:33:29', 'fdtm': '10/10/2024 11:23:16', 'ltt': '10/10/2024 11:23:16', 'v': '3702204', 'ltp': '1641.00', 'ltq': '71', 'tbq': '408143', 'tsq': '462567', 'bq': '27', 'bs': '250', 'cng': '7.85', 'nc': '0.48', 'to': '6066912760.92', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:05:38', 'dtm1': '10/04/1971 07:46:50', 'fdtm': '10/10/2024 11:23:17', 'ltt': '10/10/2024 11:23:17', 'v': '3702208', 'ltq': '70', 'tbq': '408144', 'tsq': '462564', 'bq': '26', 'bs': '247', 'to': '6066919315.84', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:05:41', 'dtm1': '10/04/1971 08:00:10', 'fdtm': '10/10/2024 11:23:18', 'ltt': '10/10/2024 11:23:18', 'v': '3702312', 'ltp': '1640.95', 'ltq': '26', 'tbq': '407507', 'tsq': '455607', 'bq': '28', 'bs': '172', 'cng': '7.80', 'nc': '0.48', 'to': '6067089743.76', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:05:44', 'dtm1': '10/04/1971 08:06:50', 'ltp': '1641.00', 'ltq': '84', 'cng': '7.85', 'nc': '0.48', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:05:50', 'dtm1': '10/04/1971 08:20:11', 'fdtm': '10/10/2024 11:23:19', 'ltt': '10/10/2024 11:23:19', 'v': '3702403', 'ltp': '1640.95', 'ltq': '6', 'tbq': '407637', 'tsq': '462716', 'bq': '22', 'bs': '332', 'cng': '7.80', 'nc': '0.48', 'to': '6067238868.19', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:05:53', 'dtm1': '10/04/1971 08:33:31', 'fdtm': '10/10/2024 11:23:20', 'ltt': '10/10/2024 11:23:20', 'v': '3702493', 'ltp': '1641.00', 'ltq': '1', 'tbq': '407793', 'tsq': '462471', 'bq': '47', 'bs': '82', 'cng': '7.85', 'nc': '0.48', 'to': '6067386353.89', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:05:56', 'dtm1': '10/04/1971 08:40:12', 'ltq': '4', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:05:59', 'dtm1': '10/04/1971 08:46:52', 'fdtm': '10/10/2024 11:23:21', 'ltt': '10/10/2024 11:23:21', 'v': '3702510', 'ltp': '1640.95', 'ltq': '3', 'tbq': '407768', 'tsq': '462457', 'bq': '44', 'bs': '368', 'cng': '7.80', 'nc': '0.48', 'to': '6067414212.30', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:06:02', 'dtm1': '10/04/1971 08:53:32', 'ltp': '1641.00', 'ltq': '456', 'cng': '7.85', 'nc': '0.48', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:06:05', 'dtm1': '10/04/1971 09:06:53', 'fdtm': '10/10/2024 11:23:22', 'ltt': '10/10/2024 11:23:22', 'v': '3704208', 'ltq': '13', 'tbq': '407696', 'tsq': '461856', 'bs': '62', 'to': '6070196775.84', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:06:08', 'dtm1': '10/04/1971 09:13:33', 'ltq': '340', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:06:11', 'dtm1': '10/04/1971 09:20:13', 'fdtm': '10/10/2024 11:23:23', 'v': '3705852', 'tbq': '407721', 'tsq': '461980', 'bq': '43', 'bs': '75', 'to': '6072890847.96', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:06:17', 'dtm1': '10/04/1971 09:33:34', 'fdtm': '10/10/2024 11:23:24', 'ltt': '10/10/2024 11:23:24', 'v': '3709153', 'ltp': '1641.05', 'ltq': '1', 'tbq': '408536', 'tsq': '462513', 'bp': '1641.00', 'sp': '1641.05', 'bq': '466', 'bs': '14', 'ap': '1638.74', 'cng': '7.90', 'nc': '0.48', 'to': '6078337387.22', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:06:20', 'dtm1': '10/04/1971 09:46:54', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:06:23', 'dtm1': '10/04/1971 09:53:34', 'fdtm': '10/10/2024 11:23:25', 'v': '3709748', 'ltp': '1641.40', 'ltq': '12', 'tbq': '405861', 'tsq': '461151', 'bp': '1640.95', 'sp': '1641.40', 'bq': '48', 'bs': '200', 'cng': '8.25', 'nc': '0.51', 'to': '6079312437.52', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:06:29', 'dtm1': '10/04/1971 10:06:55', 'fdtm': '10/10/2024 11:23:26', 'ltt': '10/10/2024 11:23:25', 'v': '3709851', 'ltp': '1640.85', 'ltq': '4', 'tbq': '407033', 'tsq': '461347', 'bp': '1640.85', 'bq': '266', 'cng': '7.70', 'nc': '0.47', 'to': '6079481227.74', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:06:35', 'dtm1': '10/04/1971 10:20:15', 'ltt': '10/10/2024 11:23:26', 'v': '3709852', 'ltp': '1641.00', 'ltq': '1', 'tbq': '405885', 'tsq': '461350', 'bp': '1640.90', 'bq': '33', 'cng': '7.85', 'nc': '0.48', 'to': '6079482866.48', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:06:41', 'dtm1': '10/04/1971 10:40:16', 'fdtm': '10/10/2024 11:23:27', 'ltt': '10/10/2024 11:23:27', 'v': '3709947', 'ltp': '1641.40', 'ltq': '83', 'tbq': '405865', 'tsq': '461260', 'bq': '31', 'bs': '110', 'cng': '8.25', 'nc': '0.51', 'to': '6079638546.78', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:06:47', 'dtm1': '10/04/1971 10:53:36', 'fdtm': '10/10/2024 11:23:28', 'ltt': '10/10/2024 11:23:28', 'v': '3710131', 'ltp': '1641.50', 'ltq': '26', 'tbq': '405348', 'tsq': '461270', 'sp': '1641.50', 'bq': '116', 'bs': '1289', 'cng': '8.35', 'nc': '0.51', 'to': '6079940074.94', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:06:53', 'dtm1': '10/04/1971 11:06:57', 'fdtm': '10/10/2024 11:23:29', 'ltt': '10/10/2024 11:23:29', 'v': '3710136', 'ltp': '1641.40', 'ltq': '3', 'tbq': '407684', 'tsq': '460358', 'bp': '1641.40', 'bq': '256', 'bs': '737', 'cng': '8.25', 'nc': '0.51', 'to': '6079948268.64', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:06:59', 'dtm1': '10/04/1971 11:26:58', 'fdtm': '10/10/2024 11:23:30', 'ltt': '10/10/2024 11:23:30', 'v': '3710313', 'ltp': '1641.45', 'ltq': '84', 'tbq': '407494', 'tsq': '460783', 'sp': '1641.45', 'bq': '182', 'bs': '505', 'cng': '8.30', 'nc': '0.51', 'to': '6080238325.62', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:07:05', 'dtm1': '10/04/1971 11:40:18', 'fdtm': '10/10/2024 11:23:31', 'ltt': '10/10/2024 11:23:31', 'v': '3711607', 'ltp': '1641.00', 'ltq': '1', 'tbq': '402999', 'tsq': '459067', 'bp': '1640.85', 'sp': '1641.35', 'bq': '135', 'bs': '12', 'cng': '7.85', 'nc': '0.48', 'to': '6082358855.18', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:07:08', 'dtm1': '10/04/1971 11:53:39', 'fdtm': '10/10/2024 11:23:32', 'ltt': '10/10/2024 11:23:32', 'v': '3711864', 'ltp': '1640.85', 'ltq': '3', 'tbq': '406663', 'tsq': '462891', 'bp': '1640.80', 'sp': '1641.00', 'bq': '46', 'bs': '94', 'cng': '7.70', 'nc': '0.47', 'to': '6082780011.36', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:07:11', 'dtm1': '10/04/1971 12:00:19', 'ltp': '1641.00', 'ltq': '23', 'cng': '7.85', 'nc': '0.48', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:07:17', 'dtm1': '10/04/1971 12:13:39', 'fdtm': '10/10/2024 11:23:33', 'ltt': '10/10/2024 11:23:33', 'v': '3712029', 'ltp': '1640.90', 'ltq': '83', 'tbq': '407144', 'tsq': '463490', 'bp': '1640.70', 'sp': '1640.90', 'bq': '128', 'bs': '247', 'cng': '7.75', 'nc': '0.47', 'to': '6083050403.46', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:07:20', 'dtm1': '10/04/1971 12:27:01', 'fdtm': '10/10/2024 11:23:34', 'v': '3712212', 'tbq': '407074', 'tsq': '463158', 'bp': '1640.75', 'bq': '76', 'bs': '37', 'to': '6083350292.88', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:07:23', 'dtm1': '10/04/1971 12:33:41', 'ltq': '5', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:07:26', 'dtm1': '10/04/1971 12:40:21', 'fdtm': '10/10/2024 11:23:35', 'ltt': '10/10/2024 11:23:35', 'v': '3712224', 'ltq': '1', 'tbq': '407441', 'tsq': '463462', 'bq': '189', 'bs': '27', 'to': '6083369957.76', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:07:32', 'dtm1': '10/04/1971 12:53:41', 'fdtm': '10/10/2024 11:23:36', 'v': '3712225', 'ltp': '1640.75', 'tbq': '407438', 'tsq': '463741', 'bq': '188', 'bs': '77', 'cng': '7.60', 'nc': '0.47', 'to': '6083371596.50', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:07:35', 'dtm1': '10/04/1971 13:07:01', 'ltp': '1640.80', 'ltq': '44', 'cng': '7.65', 'nc': '0.47', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:07:41', 'dtm1': '10/04/1971 13:20:22', 'fdtm': '10/10/2024 11:23:37', 'ltt': '10/10/2024 11:23:37', 'v': '3713488', 'ltp': '1640.75', 'ltq': '31', 'tbq': '407720', 'tsq': '462935', 'sp': '1641.00', 'bq': '163', 'bs': '87', 'cng': '7.60', 'nc': '0.47', 'to': '6085441325.12', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:07:44', 'dtm1': '10/04/1971 13:27:02', 'fdtm': '10/10/2024 11:23:38', 'v': '3713606', 'ltp': '1640.95', 'ltq': '3', 'tbq': '407436', 'tsq': '463733', 'sp': '1640.95', 'bq': '91', 'bs': '20', 'cng': '7.80', 'nc': '0.48', 'to': '6085634696.44', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:07:50', 'dtm1': '10/04/1971 13:40:23', 'ltt': '10/10/2024 11:23:38', 'v': '3713888', 'ltp': '1640.90', 'ltq': '10', 'tbq': '407494', 'tsq': '464622', 'sp': '1640.90', 'bq': '67', 'bs': '284', 'cng': '7.75', 'nc': '0.47', 'to': '6086096821.12', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:07:56', 'dtm1': '10/04/1971 14:00:23', 'fdtm': '10/10/2024 11:23:39', 'ltt': '10/10/2024 11:23:39', 'v': '3714020', 'ltq': '4', 'tbq': '407389', 'tsq': '464059', 'bq': '24', 'bs': '195', 'to': '6086313134.80', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:08:02', 'dtm1': '10/04/1971 14:13:44', 'fdtm': '10/10/2024 11:23:40', 'ltt': '10/10/2024 11:23:40', 'v': '3714045', 'ltp': '1640.75', 'ltq': '2', 'tbq': '407135', 'tsq': '464112', 'bq': '118', 'bs': '235', 'cng': '7.60', 'nc': '0.47', 'to': '6086354103.30', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:08:08', 'dtm1': '10/04/1971 14:27:05', 'fdtm': '10/10/2024 11:23:41', 'ltt': '10/10/2024 11:23:41', 'v': '3714048', 'ltp': '1640.80', 'ltq': '1', 'tbq': '407205', 'tsq': '464071', 'bs': '150', 'cng': '7.65', 'nc': '0.47', 'to': '6086359019.52', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '01/01/1970 18:08:14', 'dtm1': '10/04/1971 14:47:05', 'fdtm': '10/10/2024 11:23:42', 'ltt': '10/10/2024 11:23:42', 'v': '3714137', 'ltp': '1640.90', 'ltq': '84', 'tbq': '407239', 'tsq': '464086', 'bq': '116', 'bs': '108', 'cng': '7.75', 'nc': '0.47', 'to': '6086504867.38', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}

In [54]:
def on_message(message):
    global df
    data=json.load(message)
    if 'data' in data:
        new_row=pd.DataFrame(data['data'])
        df=pd.concat([df,new_row],ignore_index=True)
        print(df.tail(1))

{'type': 'stock_feed', 'data': [{'ftm0': '02/01/1970 00:59:44', 'dtm1': '24/05/1971 18:29:06', 'fdtm': '10/10/2024 12:27:17', 'ltt': '10/10/2024 12:27:17', 'v': '5496034', 'ltq': '25', 'tbq': '1414461', 'tsq': '433427', 'sp': '1649.85', 'bs': '35', 'to': '9020365802.50', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '02/01/1970 00:59:47', 'dtm1': '24/05/1971 18:42:26', 'fdtm': '10/10/2024 12:27:18', 'ltt': '10/10/2024 12:27:18', 'v': '5496163', 'ltq': '1', 'tbq': '1411482', 'tsq': '433146', 'sp': '1649.80', 'bq': '172', 'bs': '42', 'to': '9020577523.75', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '02/01/1970 00:59:50', 'dtm1': '24/05/1971 18:49:07', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '02/01/1970 00:59:56', 'dtm1': '24/05/1971 19:02:27', 'fdtm': '10/10/2024 12:27:19', 'ltt': '10/10/2024 12:27:19', 'v': '5496167', 'tbq': '1415087', 'tsq': '434129', 'sp': '1649.65', 'bq': '168', 'bs': '597', 'to': '9020584088.75', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '02/01/1970 00:59:59', 'dtm1': '24/05/1971 19:15:48', 'fdtm': '10/10/2024 12:27:20', 'ltt': '10/10/2024 12:27:20', 'v': '5496173', 'tbq': '1415636', 'tsq': '434002', 'bq': '167', 'bs': '592', 'to': '9020593936.25', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '02/01/1970 01:00:02', 'dtm1': '24/05/1971 19:22:28', 'ltp': '1649.65', 'ltq': '3', 'cng': '16.50', 'nc': '1.01', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '02/01/1970 01:00:08', 'dtm1': '24/05/1971 19:35:48', 'fdtm': '10/10/2024 12:27:21', 'v': '5496177', 'ltp': '1649.60', 'ltq': '5', 'tbq': '1415642', 'tsq': '433968', 'bs': '546', 'cng': '16.45', 'nc': '1.01', 'to': '9020600501.25', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '02/01/1970 01:00:11', 'dtm1': '24/05/1971 19:42:28', 'fdtm': '10/10/2024 12:27:22', 'ltt': '10/10/2024 12:27:22', 'v': '5496193', 'ltq': '10', 'tbq': '1411174', 'tsq': '433958', 'bq': '152', 'to': '9020626761.25', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '02/01/1970 01:00:14', 'dtm1': '24/05/1971 19:55:49', 'ltq': '2', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '02/01/1970 01:00:20', 'dtm1': '24/05/1971 20:09:09', 'fdtm': '10/10/2024 12:27:23', 'ltt': '10/10/2024 12:27:23', 'v': '5496881', 'ltp': '1649.65', 'ltq': '10', 'tbq': '1414989', 'tsq': '433837', 'bq': '113', 'bs': '461', 'cng': '16.50', 'nc': '1.01', 'to': '9021755941.25', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '02/01/1970 01:00:23', 'dtm1': '24/05/1971 20:15:50', 'fdtm': '10/10/2024 12:27:24', 'ltt': '10/10/2024 12:27:24', 'v': '5497293', 'ltp': '1649.55', 'ltq': '4', 'tbq': '1414847', 'tsq': '435398', 'bp': '1649.30', 'sp': '1649.55', 'bq': '5', 'bs': '24', 'cng': '16.40', 'nc': '1.00', 'to': '9022432136.25', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '02/01/1970 01:00:29', 'dtm1': '24/05/1971 20:29:10', 'fdtm': '10/10/2024 12:27:25', 'v': '5497868', 'ltq': '5', 'tbq': '1413161', 'tsq': '434510', 'bp': '1649.20', 'bq': '70', 'bs': '16', 'to': '9023375855.00', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '02/01/1970 01:00:32', 'dtm1': '24/05/1971 20:42:31', 'ltp': '1649.20', 'ltq': '11', 'cng': '16.05', 'nc': '0.98', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}
{'type': 'stock_feed', 'data': [{'ftm0': '02/01/1970 01:00:35', 'dtm1': '24/05/1971 20:49:11', 'fdtm': '10/10/2024 12:27:26', 'ltt': '10/10/2024 12:27:25', 'v': '5498028', 'ltq': '26', 'tbq': '1414659', 'tsq': '435465', 'sp': '1649.40', 'bq': '68', 'bs': '80', 'to': '9023638455.00', 'name': 'sf', 'tk': '1333', 'e': 'nse_cm', 'request_type': 'SUB'}]}

In [49]:
thread.start()

RuntimeError: threads can only be started once

In [104]:
equ[equ['pSymbolName']== 'TCS']

,pSymbol,pGroup,pExchSeg,pInstType,pSymbolName,pTrdSymbol,pOptionType,pScripRefKey,pISIN,pAssetCode,...,dGenDen,dGenNum,dPriceQuatation,dIssuerate,dPriceDen,dWarningQty,dIssueCapital,dExposureMargin,dMinRedemptionQty,lFreezeQty
8072,11536,EQ,nse_cm,NaN,TCS,TCS-EQ,NaN,TCS,INE467B01029,NaN,...,1,1,0,0,1,0,3.618090e+09,0,0,21708
9243,12825,BL,nse_cm,NaN,TCS,TCS-BL,NaN,TCS-BL,INE467B01029,NaN,...,1,1,0,0,1,0,3.618090e+09,0,0,99999999

In [83]:
client.place_order(exchange_segment="nse_cm",
                   product="MIS",
                   price="498.25",
                   order_type="L",
                   quantity="1",
                   validity="DAY",
                   trading_symbol="ITC-EQ",
                   transaction_type="S",
                   amo="NO",
                   disclosed_quantity="0",
                   market_protection="0",
                   pf="N",
                   trigger_price="498.25",
                   tag="NONE")

{'stat': 'Ok',
 'nOrdNo': '241014001621944',
 'tid': 'server6_2528151',
 'stCode': 200}

In [87]:
client.positions()

{'tid': 'server6_2555406',
 'stat': 'Ok',
 'stCode': 200,
 'data': [{'buyAmt': '498.05',
   'cfSellAmt': '0.00',
   'prod': 'MIS',
   'exSeg': 'nse_cm',
   'sqrFlg': 'Y',
   'actId': 'YD2HU',
   'cfBuyQty': '0',
   'hsUpTm': '2024/10/14 14:50:49',
   'updRecvTm': 1728897649730473091,
   'cfSellQty': '0',
   'tok': '1660',
   'upldPrc': '0.00',
   'flBuyQty': '1',
   'flSellQty': '1',
   'sellAmt': '497.40',
   'posFlg': 'true',
   'cfBuyAmt': '0.00',
   'stkPrc': '0.00',
   'trdSym': 'ITC-EQ',
   'sym': 'ITC',
   'multiplier': '1',
   'precision': '2',
   'expDt': 'NA',
   'type': 'NA',
   'genNum': '1',
   'series': 'EQ',
   'prcNum': '1',
   'genDen': '1',
   'brdLtQty': 1,
   'exp': '--',
   'lotSz': '1',
   'optTp': 'XX',
   'prcDen': '1'}]}

In [86]:
client.trade_report()

{'tid': 'server6_2553443',
 'stat': 'Ok',
 'stCode': 200,
 'data': [{'exOrdId': '1100000040976208',
   'brkClnt': 'NA',
   'cstFrm': 'C',
   'actId': 'YD2HU',
   'rmk': '--',
   'fldQty': 1,
   'flDt': '14-Oct-2024',
   'avgPrc': '497.40',
   'ordSrc': 'NA',
   'algId': 'NA',
   'locId': '111111111111100',
   'prcTp': 'L',
   'prod': 'MIS',
   'exTm': '14-Oct-2024 14:50:20',
   'nReqId': '1',
   'exSeg': 'nse_cm',
   'trdSym': 'ITC-EQ',
   'GuiOrdId': '1728897620-831695-DLUPA0946K-ADMINAPI',
   'flLeg': 1,
   'rptTp': 'fill',
   'usrId': 'DLUPA0946K',
   'uSec': '838051',
   'hsUpTm': '2024/10/14 14:51:26',
   'updRecvTm': 1728897686213466564,
   'ordGenTp': '--',
   'flId': '206880507',
   'flTm': '14:50:20',
   'trnsTp': 'S',
   'nOrdNo': '241014001634037',
   'strategyCode': 'NA',
   'algCat': 'NA',
   'ordDur': 'DAY',
   'boeSec': 1728897620,
   'stkPrc': '0.00',
   'sym': 'ITC',
   'multiplier': '1',
   'precision': '2',
   'expDt': 'NA',
   'tok': '1660',
   'genNum': '1',
   'series': 'EQ',
   'prcNum': '1',
   'genDen': '1',
   'brdLtQty': 1,
   'exp': '--',
   'lotSz': '1',
   'minQty': 0,
   'optTp': 'XX',
   'prcDen': '1'},
  {'exOrdId': '1100000038759034',
   'brkClnt': 'NA',
   'cstFrm': 'C',
   'actId': 'YD2HU',
   'rmk': '--',
   'fldQty': 1,
   'flDt': '14-Oct-2024',
   'avgPrc': '498.05',
   'ordSrc': 'NA',
   'algId': 'NA',
   'locId': '333333333333100',
   'prcTp': 'L',
   'prod': 'MIS',
   'exTm': '14-Oct-2024 14:31:23',
   'nReqId': '1',
   'exSeg': 'nse_cm',
   'trdSym': 'ITC-EQ',
   'GuiOrdId': '1728896483-823266-DLUPA0946K-ADMINAPI',
   'flLeg': 1,
   'rptTp': 'fill',
   'usrId': 'DLUPA0946K',
   'uSec': '831140',
   'hsUpTm': '2024/10/14 14:51:26',
   'updRecvTm': 1728897686213610046,
   'ordGenTp': '--',
   'flId': '206503636',
   'flTm': '14:31:23',
   'trnsTp': 'B',
   'nOrdNo': '241014001528442',
   'strategyCode': 'NA',
   'algCat': 'NA',
   'ordDur': 'DAY',
   'boeSec': 1728896483,
   'stkPrc': '0.00',
   'sym': 'ITC',
   'multiplier': '1',
   'precision': '2',
   'expDt': 'NA',
   'tok': '1660',
   'genNum': '1',
   'series': 'EQ',
   'prcNum': '1',
   'genDen': '1',
   'brdLtQty': 1,
   'exp': '--',
   'lotSz': '1',
   'minQty': 0,
   'optTp': 'XX',
   'prcDen': '1'}]}

In [78]:
client.limits()

{'AddPreExpMrgnMisPrsnt': '0.00',
 'CurExpMrgnNrmlPrsnt': '0.00',
 'CurPremiumNrmlPrsnt': '0.00',
 'RmsPayOutAmt': '0.00',
 'AdhocMargin': '0.00',
 'MrgnScrpBsktCncPrsnt': '0.00',
 'FoPremiumMisPrsnt': '0.00',
 'tid': 'server4_2547484',
 'MrgnVarNrmlPrsnt': '0.00',
 'AmountUtilizedPrsnt': '0.00',
 'SplMrgnMisPrsnt': '0.00',
 'CurSpanMrgnNrmlPrsnt': '0.00',
 'SlbmVarElm': '0.00',
 'AuxRmsCollateral': '0.00',
 'FoUnRlsMtomPrsnt': '0.00',
 'AuxNotionalCash': '0.00',
 'AuxAdhocMargin': '0.00',
 'DaneLimit': '0.00',
 'RmsMutualFundAmt': '0.00',
 'RmsPayInAmt': '200.00',
 'CurPremiumMisPrsnt': '0.00',
 'SlbmLimit': '0',
 'MarginWarningPrcntPrsnt': '49.93',
 'MrgnVarMisPrsnt': '0.00',
 'CurRlsMtomPrsnt': '0.00',
 'RMSRequiredMargin': '0.00',
 'ExposureMarginPrsnt': '0.00',
 'NfospreadBenefit': '0.00',
 'stCode': 200,
 'CollateralValue': '0.00',
 'AddMrgnNrmlPrsnt': '0.00',
 'RmsCollateralMult': '0.00',
 'CncMrgnVarPrsnt': '0.00',
 'MfCashCollateral': '0.00',
 'BoardLotLimit': '10000',
 'ComRlsMtomPrsnt': '0.00',
 'MarginVarPrsnt': '0.00',
 'DeliveryMarginPresent': '0.00',
 'RmsCollateral': '0.00',
 'ComExpsrMrgnMisPrsnt': '0.00',
 'RmsIpoAmt': '0.00',
 'CollateralValueMult': '0.00',
 'FoSpanrgnMisPrsnt': '0.00',
 'Category': 'CLIENT',
 'LiquidCashCollateral': '0.00',
 'CurUnRlsMtomPrsnt': '0.00',
 'SpanMarginPrsnt': '0.00',
 'CncSellcrdPresent': '0.00',
 'Collateral': '0.00',
 'MrgnScrpBsktNrmlPrsnt': '0.00',
 'UnrealizedMtomPrsnt': '0.25',
 'MrgnScrpBsktMisPrsnt': '99.61',
 'RealizedMtomPrsnt': '0.00',
 'MtomWarningPrcntPrsnt': '0.12',
 'ComSpanMrgnNrmlPrsnt': '0.00',
 'DeliveryMrgnNrmlPrsnt': '0.00',
 'AdhocLimitMult': '0.00',
 'FoPremiumNrmlPrsnt': '0.00',
 'SpecialMarginPrsnt': '0.00',
 'SplMrgnNrmlPrsnt': '0.00',
 'MtomSquareOffWarningPrcntPrsnt': '0.12',
 'MarginUsedPrsnt': '99.86',
 'FoRlsMtomPrsnt': '0.00',
 'stat': 'Ok',
 'NationalCashMult': '0.00',
 'FoSpanrgnNrmlPrsnt': '0.00',
 'AmtUntilizedPrsnt': '0.00',
 'PremiumPrsnt': '0.00',
 'AddMrgnMisPrsnt': '0.00',
 'DeliveryMrgnMisPrsnt': '0.00',
 'SlbmMtom': '0.00',
 'CdsSpreadBenefit': '0.00',
 'ComExpsrMrgnNrmlPrsnt': '0.00',
 'FoExpMrgnNrmlPrsnt': '0.00',
 'BrokeragePrsnt': '0.00',
 'CashUnRlsMtomPrsnt': '0.25',
 'AddPreExpMrgnNrmlPrsnt': '0.00',
 'CurSpanMrgnMisPrsnt': '0.00',
 'ComUnRlsMtomPrsnt': '0.00',
 'CashRlsMtomPrsnt': '0.00',
 'NotionalCash': '0.00',
 'CurExpMrgnMisPrsnt': '0.00',
 'MfCollateral': '0.00',
 'MarginUsed': '99.86',
 'LendingFee': '0.00',
 'Net': '100.14',
 'TenderMrgnMisPrsnt': '0.00',
 'FoExpMrgnMisPrsnt': '0.00',
 'TenderMrgnNrmlPrsnt': '0.00',
 'MarginScripBasketPrsnt': '99.61',
 'ComSpanMrgnMisPrsnt': '0.00'}

In [56]:
client.holdings()

{'data': []}

In [95]:
pip show websockets

Name: websockets
Version: 13.1
Summary: An implementation of the WebSocket Protocol (RFC 6455 & 7692)
Home-page:
Author:
Author-email: Aymeric Augustin <aymeric.augustin@m4x.org>
License: BSD-3-Clause
Location: /Users/Macbook/anaconda3/lib/python3.11/site-packages
Requires:
Required-by: dhanhq, neo-api-client
Note: you may need to restart the kernel to use updated packages.